INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, called <span class=\"supplied\">to be</span> an apostle of Christ Jesus through the will of God, and Sosthenes our brother,'),
('LEB', '1 Corinthians', '1', '2', '1', 'to the church of God sanctified in Christ Jesus that is in Corinth,<span class=\"note\">Some manuscripts have “to the church of God that is in Corinth, sanctified in Christ Jesus”</span>called <span class=\"supplied\">to be</span> saints, together with all those who call upon the name of our Lord Jesus Christ in every place, their <span class=\"supplied\">Lord</span>and ours.'),
('LEB', '1 Corinthians', '1', '3', '1', 'Grace to you and peace from God our Father and the Lord Jesus Christ.'),
('LEB', '1 Corinthians', '1', '4', '3', '<span class=\"verse-title\">Thanksgiving for the Corinthian Believers</span>I give thanks to my God always concerning you, because of the grace of God which was given to you in Christ Jesus,'),
('LEB', '1 Corinthians', '1', '5', '3', 'thatin everything you were made rich in him, in all speech and all knowledge,'),
('LEB', '1 Corinthians', '1', '6', '3', 'just as the testimony about Christ has been confirmed in you,'),
('LEB', '1 Corinthians', '1', '7', '3', 'so that you do not lack in any spiritual gift <span class=\"supplied\">as you</span>eagerly await the revelation of our Lord Jesus Christ,'),
('LEB', '1 Corinthians', '1', '8', '3', 'who will also confirm you until the end, blameless in the day of our Lord Jesus Christ.'),
('LEB', '1 Corinthians', '1', '9', '3', 'God <span class=\"supplied\">is</span> faithful, by whom you were called to fellowship with his Son Jesus Christ our Lord.'),
('LEB', '1 Corinthians', '1', '10', '5', '<span class=\"verse-title\">Divisions in the Church at Corinth</span>Now I exhort you, brothers, by the name of our Lord Jesus Christ, that you all say the same <span class=\"supplied\">thing</span> and there not be divisions among you, and that you be made complete in the same mind and with the same purpose.'),
('LEB', '1 Corinthians', '1', '11', '5', 'For it has been made clear to me concerning you, my brothers, by <span class=\"idiom\">Chloe’s people</span><span class=\"note\">“those of Chloe”</span>, that there are quarrels among you.'),
('LEB', '1 Corinthians', '1', '12', '5', 'But I say this, that each of you is saying, “I am with Paul,” and “I <span class=\"supplied\">am</span> with Apollos,” and “I <span class=\"supplied\">am</span> with Cephas,” and “I <span class=\"supplied\">am</span> with Christ.”'),
('LEB', '1 Corinthians', '1', '13', '5', 'Has Christ been divided? Paul was not crucified for you, was he?Or were you baptized in the name of Paul?'),
('LEB', '1 Corinthians', '1', '14', '5', 'I give thanks<span class=\"note\">Some manuscripts have “I give thanks to God”</span>that I baptized none of you except Crispus and Gaius,'),
('LEB', '1 Corinthians', '1', '15', '5', 'lest anyone should say that you were baptized in my name.'),
('LEB', '1 Corinthians', '1', '16', '5', '(Now I also baptized the household of Stephanas. Beyond that I do not know if I baptized anyone else.)'),
('LEB', '1 Corinthians', '1', '17', '5', 'For Christ did not send me to baptize, but to proclaim the gospel, not with <span class=\"idiom\">clever speech</span><span class=\"note\">“wisdom of word”</span>, lest the cross of Christ be emptied.'),
('LEB', '1 Corinthians', '1', '18', '7', '<span class=\"verse-title\">Christ Crucified, the Power and Wisdom of God</span>For the message about the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.'),
('LEB', '1 Corinthians', '1', '19', '7', 'For it is written, “I will destroy the wisdom of the wise,  and the intelligence of the intelligent I will confound.”<span class=\"note\">Isa 29:14</span>'),
('LEB', '1 Corinthians', '1', '20', '9', 'Where <span class=\"supplied\">is</span> the wise person? Where <span class=\"supplied\">is</span> the scribe? Where <span class=\"supplied\">is</span> the debater of this age? Has not God made foolish the wisdom of the world?'),
('LEB', '1 Corinthians', '1', '21', '9', 'For since, in the wisdom of God, the world through its wisdom did not know God, God was pleased through the foolishness of preaching to save those who believe.'),
('LEB', '1 Corinthians', '1', '22', '9', 'For indeed, Jews ask for sign miracles and Greeks seek wisdom,'),
('LEB', '1 Corinthians', '1', '23', '9', 'but we preach Christ crucified, to the Jews a cause for stumbling, but to the Gentiles foolishness,'),
('LEB', '1 Corinthians', '1', '24', '9', 'but to those <span class=\"supplied\">who are</span> called, both Jews and Greeks, Christ <span class=\"supplied\">is</span> the power of God and the wisdom of God.'),
('LEB', '1 Corinthians', '1', '25', '9', 'For the foolishness of God is wiser than human <span class=\"supplied\">wisdom</span>,<span class=\"note\">“man”</span>and the weakness of God <span class=\"supplied\">is</span> stronger than human <span class=\"supplied\">strength</span>.<span class=\"note\">“man”</span>'),
('LEB', '1 Corinthians', '1', '26', '11', '<span class=\"verse-title\">Boast in the Lord</span>For consider your calling, brothers, that not many <span class=\"supplied\">were</span> wise according to human standards,<span class=\"note\">“according to flesh”</span>not many <span class=\"supplied\">were</span> powerful, not many <span class=\"supplied\">were</span> well born.'),
('LEB', '1 Corinthians', '1', '27', '11', 'But the foolish <span class=\"supplied\">things</span> of the world God chose in order that he might put to shame the wise, and the weak <span class=\"supplied\">things</span> of the world God chose in order that he might put to shame the strong,'),
('LEB', '1 Corinthians', '1', '28', '11', 'and the insignificant of the world, and the despised, God chose, the things that are not, in order that he might abolish the things that are,'),
('LEB', '1 Corinthians', '1', '29', '11', 'so that all flesh may not boast before God.'),
('LEB', '1 Corinthians', '1', '30', '11', 'But from him you are in Christ Jesus, who became wisdom to us from God, and righteousness and sanctification and redemption,'),
('LEB', '1 Corinthians', '1', '31', '11', 'so that, just as it is written, “The one who boasts, let him boast in the Lord.”<span class=\"note\">Jer 9:24</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '2', '1', '1', '<span class=\"verse-title\">Paul’s Approach to Ministry in Corinth</span>And I, <span class=\"supplied\">when I</span>came to you, brothers, did not come with superiority of speech or of wisdom, proclaiming to you the testimony<span class=\"note\">Some manuscripts have “mystery”</span>of God.'),
('LEB', '1 Corinthians', '2', '2', '1', 'For I decided not to know anything among you except Jesus Christ and him crucified.'),
('LEB', '1 Corinthians', '2', '3', '1', 'And I came to you in weakness and in fear and with much trembling,'),
('LEB', '1 Corinthians', '2', '4', '1', 'and my speech and my preaching <span class=\"supplied\">were</span> not with the persuasiveness<span class=\"note\">Some manuscripts have “with persuasive words”</span>of wisdom, but with a demonstration of the Spirit and power,'),
('LEB', '1 Corinthians', '2', '5', '1', 'in order that your faith would not be in the wisdom of men, but in the power of God.'),
('LEB', '1 Corinthians', '2', '6', '3', '<span class=\"verse-title\">The Wisdom Revealed by the Spirit</span>Now we do speak wisdom among the mature, but wisdom not of this age or of the rulers of this age, who are perishing,'),
('LEB', '1 Corinthians', '2', '7', '3', 'but we speak the hidden wisdom of God in a mystery, which God predestined before the ages for our glory,'),
('LEB', '1 Corinthians', '2', '8', '3', 'which none of the rulers of this age knew. For if they had known <span class=\"supplied\">it</span>, they would not have crucified the Lord of glory.'),
('LEB', '1 Corinthians', '2', '9', '3', 'But just as it is written, “<span class=\"supplied\">Things</span> which eye has not seen and ear has not heard,  and have not entered into the heart of man,  all that<span class=\"note\">Some manuscripts have “which”</span>God has prepared for those who love him.”<span class=\"note\">Isa 64:4</span>'),
('LEB', '1 Corinthians', '2', '10', '5', 'For<span class=\"note\">Some manuscripts have “But to us God has revealed <span class=\"supplied\">them</span>”</span>to us God has revealed <span class=\"supplied\">them</span> through the Spirit. For the Spirit searches all <span class=\"supplied\">things</span>, even the depths of God.'),
('LEB', '1 Corinthians', '2', '11', '5', 'For who among men knows the things of a man, except the spirit of the man that <span class=\"supplied\">is</span> in him? Thus also no one knows the things of God except the Spirit of God.'),
('LEB', '1 Corinthians', '2', '12', '5', 'Now we have received not the spirit of the world, but the Spirit who <span class=\"supplied\">is</span> from God, in order that we may know the things freely given to us by God,'),
('LEB', '1 Corinthians', '2', '13', '5', '<span class=\"supplied\">things</span> which we also speak, not in words taught by human wisdom, but in <span class=\"supplied\">words</span> taught by the Spirit, explaining spiritual <span class=\"supplied\">things</span> to spiritual <span class=\"supplied\">people</span>.<span class=\"note\">Or “in spiritual <span class=\"supplied\">words</span>”</span>'),
('LEB', '1 Corinthians', '2', '14', '5', 'But the natural man does not accept the things of the Spirit of God, for they are foolishness to him, and he is not able to understand <span class=\"supplied\">them</span>, because they are spiritually discerned.'),
('LEB', '1 Corinthians', '2', '15', '5', 'Now the spiritual <span class=\"supplied\">person</span> discerns all <span class=\"supplied\">things</span>, but he himself is judged by no one.'),
('LEB', '1 Corinthians', '2', '16', '5', '“For who has known the mind of the Lord; who has advised him?”<span class=\"note\">Isa 40:13</span>But we have the mind of Christ.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '3', '1', '1', '<span class=\"verse-title\">Divisiveness and Immaturity</span>And I, brothers, was not able to speak to you as to spiritual <span class=\"supplied\">people</span>, but as to fleshly <span class=\"supplied\">people</span>, as to infants in Christ.'),
('LEB', '1 Corinthians', '3', '2', '1', 'I gave you milk to drink, not solid food, for you were not yet able <span class=\"supplied\">to eat it</span>. But now you are still not able,'),
('LEB', '1 Corinthians', '3', '3', '1', 'for you are still fleshly. For where <span class=\"supplied\">there is</span> jealousy and strife among you, are you not fleshly, and do you not live like <span class=\"supplied\">unregenerate</span> people?<span class=\"note\">That is, like people who do not possess the Spirit at all</span>'),
('LEB', '1 Corinthians', '3', '4', '1', 'For whenever anyone says, “I am with Paul,” and another, “I <span class=\"supplied\">am</span> with Apollos,” are you not <span class=\"supplied\">merely</span> human?'),
('LEB', '1 Corinthians', '3', '5', '2', 'Therefore, what is Apollos and what is Paul? Servants through whom you believed, and to each as the Lord gave.'),
('LEB', '1 Corinthians', '3', '6', '2', 'I planted, Apollos watered, but God was causing <span class=\"supplied\">it</span> to grow.'),
('LEB', '1 Corinthians', '3', '7', '2', 'So then, neither the one who plants nor the one who waters is anything, but God who is causing <span class=\"supplied\">it</span> to grow.'),
('LEB', '1 Corinthians', '3', '8', '2', 'Now the one who plants and the one who waters are one, but each one will receive his own reward according to his own labor.'),
('LEB', '1 Corinthians', '3', '9', '2', 'For we are God’s fellow workers; you are God’s field, God’s building.'),
('LEB', '1 Corinthians', '3', '10', '3', 'According to the grace of God given to me, like a skilled master builder I laid a foundation, and another is building upon <span class=\"supplied\">it</span>. But each one must direct his attention to how he is building upon <span class=\"supplied\">it</span>.'),
('LEB', '1 Corinthians', '3', '11', '3', 'For no one is able to lay another foundation than the one which is laid, which is Jesus Christ.'),
('LEB', '1 Corinthians', '3', '12', '3', 'Now if anyone builds upon the foundation <span class=\"supplied\">with</span> gold, silver, precious stones, wood, grass, straw,'),
('LEB', '1 Corinthians', '3', '13', '3', 'the work of each one will become evident. For the day will reveal <span class=\"supplied\">it</span>, because it will be revealed with fire, and the fire itself will test the work of each one, of what sort it is.'),
('LEB', '1 Corinthians', '3', '14', '3', 'If anyone’s work that he has built upon <span class=\"supplied\">it</span> remains, he will receive a reward.'),
('LEB', '1 Corinthians', '3', '15', '3', 'If anyone’s work is burned up, he will suffer loss, but he himself will be saved, but so as through fire.'),
('LEB', '1 Corinthians', '3', '16', '4', 'Do you not know that you are God’s temple and the Spirit of God dwells in you?'),
('LEB', '1 Corinthians', '3', '17', '4', 'If anyone destroys God’s temple, God will destroy this one. For God’s temple is holy, which you are.'),
('LEB', '1 Corinthians', '3', '18', '5', 'Let no one deceive himself. If anyone thinks <span class=\"supplied\">himself</span> to be wise among you in this age, let him become a fool, in order that he may become wise.'),
('LEB', '1 Corinthians', '3', '19', '5', 'For the wisdom of this world is foolishness with God, for it is written, “The one who catches the wise in their craftiness,”<span class=\"note\">Job 5:13</span>'),
('LEB', '1 Corinthians', '3', '20', '5', 'and again, “The Lord knows the thoughts of the wise, that they are futile.”<span class=\"note\">Ps 94:11</span>'),
('LEB', '1 Corinthians', '3', '21', '5', 'So then, let no one boast in people. For all <span class=\"supplied\">things</span> are yours,'),
('LEB', '1 Corinthians', '3', '22', '5', 'whether Paul or Apollos or Cephas or the world or life or death or things present or things to come, all <span class=\"supplied\">things</span> <span class=\"supplied\">are</span> yours,'),
('LEB', '1 Corinthians', '3', '23', '5', 'and you <span class=\"supplied\">are</span> Christ’s, and Christ <span class=\"supplied\">is</span> God’s.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '4', '1', '1', '<span class=\"verse-title\">Christ’s Servant, God’s Steward</span>Thus let a person consider us as servants of Christ and stewards of God’s mysteries.'),
('LEB', '1 Corinthians', '4', '2', '1', 'In this case, moreover, it is sought in stewards that one be found faithful.'),
('LEB', '1 Corinthians', '4', '3', '1', 'But to me it is a very little matter that I be judged by you or by a human court,<span class=\"note\">“day”</span>but I do not <span class=\"supplied\">even</span> judge myself.'),
('LEB', '1 Corinthians', '4', '4', '1', 'For I am conscious of nothing against myself, but not by this am I vindicated. But the one who judges me is the Lord.'),
('LEB', '1 Corinthians', '4', '5', '1', 'Therefore do not judge anything before the time, until the Lord should come, who will both enlighten the hidden things of darkness and will reveal the counsels of hearts, and then praise will come to each one from God.'),
('LEB', '1 Corinthians', '4', '6', '3', '<span class=\"verse-title\">The Apostles’ Humility</span>Now I have applied these things, brothers, to myself and Apollos for your sake, in order that in us you may learn not <span class=\"supplied\">to go</span> beyond what is written, lest someone be inflated with pride on behalf of one <span class=\"supplied\">person</span> against the other.'),
('LEB', '1 Corinthians', '4', '7', '3', 'For who concedes you <span class=\"supplied\">superiority</span>? And what do you have that you did not receive? But if indeed you received <span class=\"supplied\">it</span>, why do you boast as <span class=\"supplied\">if you</span>did not receive <span class=\"supplied\">it</span>?'),
('LEB', '1 Corinthians', '4', '8', '3', 'Already you are satiated! Already you are rich! Apart from us you reign as kings! And would that indeed you reigned as kings, in order that we also might reign as kings with you!'),
('LEB', '1 Corinthians', '4', '9', '3', 'For, I think, God has exhibited us apostles last of all, as condemned to death, because we have become a spectacle to the world and to angels and to people.'),
('LEB', '1 Corinthians', '4', '10', '3', 'We <span class=\"supplied\">are</span> fools for the sake of Christ, but you <span class=\"supplied\">are</span> prudent in Christ! We <span class=\"supplied\">are</span> weak, but you <span class=\"supplied\">are</span> strong! You <span class=\"supplied\">are</span> honored, but we <span class=\"supplied\">are</span> dishonored!'),
('LEB', '1 Corinthians', '4', '11', '3', 'Until the present hour we are both hungry and thirsty and poorly clothed and roughly treated and homeless,'),
('LEB', '1 Corinthians', '4', '12', '3', 'and we toil, working with our own hands. <span class=\"supplied\">When we are</span>reviled, we bless; <span class=\"supplied\">when we are</span>persecuted, we endure;'),
('LEB', '1 Corinthians', '4', '13', '3', '<span class=\"supplied\">when we are</span>slandered, we encourage. We have become like the refuse of the world, the offscouring of all <span class=\"supplied\">things</span>, until now.'),
('LEB', '1 Corinthians', '4', '14', '5', '<span class=\"verse-title\">Paul’s Concern for the Corinthian Believers</span>I am not writing these <span class=\"supplied\">things</span> to shame you, but admonishing <span class=\"supplied\">you</span> as my dear children.'),
('LEB', '1 Corinthians', '4', '15', '5', 'For if you have ten thousand guardians in Christ, yet <span class=\"supplied\">you do</span> not <span class=\"supplied\">have</span> many fathers, for in Christ Jesus I fathered you through the gospel.'),
('LEB', '1 Corinthians', '4', '16', '5', 'Therefore I exhort you, become imitators of me.'),
('LEB', '1 Corinthians', '4', '17', '5', 'Because of this, I have sent to you Timothy, who is my dear and faithful child in the Lord, who will remind you of my ways in Christ Jesus, just as I teach everywhere in every church.'),
('LEB', '1 Corinthians', '4', '18', '5', 'But some have become arrogant, as <span class=\"supplied\">if</span> I were not coming to you.'),
('LEB', '1 Corinthians', '4', '19', '5', 'But I am coming to you soon, if the Lord wills, and I will know not the talk of the ones who have become arrogant, but the power.'),
('LEB', '1 Corinthians', '4', '20', '5', 'For the kingdom of God <span class=\"supplied\">is</span> not with talk, but with power.'),
('LEB', '1 Corinthians', '4', '21', '5', 'What do you want? Shall I come to you with a rod, or with love and a spirit of gentleness?')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '5', '1', '1', '<span class=\"verse-title\">Immoral Behavior and Church Discipline</span>It is reported everywhere <span class=\"supplied\">that there</span> is sexual immorality among you, and sexual immorality of such a kind which <span class=\"supplied\">does</span> not <span class=\"supplied\">even exist</span> among the Gentiles, so that someone has the wife of <span class=\"supplied\">his</span> father.'),
('LEB', '1 Corinthians', '5', '2', '1', 'And you are inflated with pride, and should you not rather have mourned, so that the one who has done this deed would be removed from your midst?'),
('LEB', '1 Corinthians', '5', '3', '1', 'For <span class=\"supplied\">although I</span>am absent in body but present in spirit, I have already passed judgment on the one who has done this in this way, as <span class=\"supplied\">if I</span>were present.'),
('LEB', '1 Corinthians', '5', '4', '1', 'In the name of our Lord Jesus, <span class=\"supplied\">when</span>you are assembled, and my spirit, together with the power of our Lord Jesus,'),
('LEB', '1 Corinthians', '5', '5', '1', '<span class=\"supplied\">I have decided</span>to hand over such a person to Satan for the destruction of the flesh, in order that his spirit may be saved in the day of the Lord.'),
('LEB', '1 Corinthians', '5', '6', '2', 'Your boasting <span class=\"supplied\">is</span> not good. Do you not know that a little leaven leavens the whole batch of dough?'),
('LEB', '1 Corinthians', '5', '7', '2', 'Clean out the old leaven in order that you may be a new batch of dough, just as you are unleavened. For Christ our Passover has been sacrificed.'),
('LEB', '1 Corinthians', '5', '8', '2', 'So then, let us celebrate the feast, not with the old leaven or with the leaven of wickedness and sinfulness, but with the unleavened bread of sincerity and truth.'),
('LEB', '1 Corinthians', '5', '9', '3', 'I wrote to you in the letter not to associate with sexually immoral people.'),
('LEB', '1 Corinthians', '5', '10', '3', 'By no means <span class=\"supplied\">did I mean</span> the sexually immoral people of this world or the greedy people and swindlers or idolaters, since then you would have to depart out of the world.'),
('LEB', '1 Corinthians', '5', '11', '3', 'But now I have written to you not to associate with any so-called brother, if he is a sexually immoral person or a greedy person or an idolater or an abusive person or a drunkard or a swindler—with such a person not even to eat.'),
('LEB', '1 Corinthians', '5', '12', '3', 'For what <span class=\"supplied\">is it</span> to me to judge those outside? Should you not judge those inside?'),
('LEB', '1 Corinthians', '5', '13', '3', 'But those outside God will judge. Remove the evil person <span class=\"idiom\">from among yourselves</span><span class=\"note\">“from you of them”</span>.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '6', '1', '1', '<span class=\"verse-title\">Lawsuits between Believers</span>Does anyone among you, <span class=\"supplied\">if he</span>has a matter against someone else, dare to go to court before the unrighteous, and not before the saints?'),
('LEB', '1 Corinthians', '6', '2', '1', 'Or do you not know that the saints will judge the world? And if by you the world is judged, are you unworthy of the most insignificant courts?'),
('LEB', '1 Corinthians', '6', '3', '1', 'Do you not know that we will judge angels, not to mention ordinary matters?'),
('LEB', '1 Corinthians', '6', '4', '1', 'Therefore, if you have courts with regard to ordinary matters, do you seat<span class=\"note\">Or “seat” (imperative); the Greek verb can be either indicative mood or imperative mood by its form</span>these despised <span class=\"supplied\">people</span> in the church?'),
('LEB', '1 Corinthians', '6', '5', '1', 'I say <span class=\"supplied\">this</span> to your shame. So is there not anyone wise among you who will be able to render a decision between his brothers?'),
('LEB', '1 Corinthians', '6', '6', '1', 'But brother goes to court with brother, and this before unbelievers!'),
('LEB', '1 Corinthians', '6', '7', '1', 'Therefore it is already completely a loss for you that you have lawsuits with one another. Why not rather be wronged? Why not rather be defrauded?'),
('LEB', '1 Corinthians', '6', '8', '1', 'But you wrong and defraud, and <span class=\"supplied\">do</span> this <span class=\"supplied\">to</span> brothers!'),
('LEB', '1 Corinthians', '6', '9', '2', 'Or do you not know that the unrighteous will not inherit the kingdom of God? Do not be deceived! Neither sexually immoral people, nor idolaters, nor adulterers, nor passive homosexual partners, nor dominant homosexual partners,'),
('LEB', '1 Corinthians', '6', '10', '2', 'nor thieves, nor greedy persons, not drunkards, not abusive persons, not swindlers will inherit the kingdom of God.'),
('LEB', '1 Corinthians', '6', '11', '2', 'And some of you were these <span class=\"supplied\">things</span>, but you were washed, but you were sanctified, but you were justified in the name of the Lord Jesus<span class=\"note\">Some manuscripts have “of the Lord Jesus Christ”</span>and by the Spirit of our God.'),
('LEB', '1 Corinthians', '6', '12', '4', '<span class=\"verse-title\">Avoid Sexual Immorality</span>All <span class=\"supplied\">things</span> are permitted for me, but not all <span class=\"supplied\">things</span> are profitable. All <span class=\"supplied\">things</span> are permitted for me, but I will not be controlled by anything.'),
('LEB', '1 Corinthians', '6', '13', '4', 'Food <span class=\"supplied\">is</span> for the stomach, and the stomach for food, but God will abolish <span class=\"idiom\">both of them</span><span class=\"note\">“both this and these”</span>. Now the body <span class=\"supplied\">is</span> not for sexual immorality, but for the Lord, and the Lord for the body.'),
('LEB', '1 Corinthians', '6', '14', '4', 'And God both raised up the Lord and will raise us up by his power.'),
('LEB', '1 Corinthians', '6', '15', '4', 'Do you not know that your bodies are members of Christ? Therefore, shall I take away the members of Christ <span class=\"supplied\">and</span> make <span class=\"supplied\">them</span> members of a prostitute? May it never be!'),
('LEB', '1 Corinthians', '6', '16', '4', 'Or do you not know that the one who joins himself to a prostitute is one body <span class=\"supplied\">with her</span>? For it says, “The two will become one flesh.”<span class=\"note\">Gen 2:24</span>'),
('LEB', '1 Corinthians', '6', '17', '4', 'But the one who joins himself to the Lord is one spirit <span class=\"supplied\">with him</span>.'),
('LEB', '1 Corinthians', '6', '18', '4', 'Flee sexual immorality. Every sin that a person commits is outside his body, but the one who commits sexual immorality sins against his own body.'),
('LEB', '1 Corinthians', '6', '19', '4', 'Or do you not know that your body is the temple of the Holy Spirit <span class=\"supplied\">who is</span> in you, whom you have from God, and you are not your own?'),
('LEB', '1 Corinthians', '6', '20', '4', 'For you were bought at a price; therefore glorify God with your body.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '7', '1', '1', '<span class=\"verse-title\">Concerning Christian Marriage</span>Now concerning <span class=\"supplied\">the things</span> about which you wrote: “<span class=\"supplied\">It is</span> good for a man not to touch<span class=\"note\">I.e., in a sexual sense</span>a woman.”'),
('LEB', '1 Corinthians', '7', '2', '1', 'But because of sexual immorality, let each man have<span class=\"note\">I.e., in the sense of “have sexual relations with”</span>his own wife and let each woman have her own husband.'),
('LEB', '1 Corinthians', '7', '3', '1', 'The husband must fulfill his obligation to his wife, and likewise also the wife to her husband.'),
('LEB', '1 Corinthians', '7', '4', '1', 'The wife does not have authority over her own body, but her husband <span class=\"supplied\">does</span>. And likewise also the husband does not have authority over his own body, but his wife <span class=\"supplied\">does</span>.'),
('LEB', '1 Corinthians', '7', '5', '1', 'Do not defraud one another, except perhaps by agreement, for a time, in order that you may devote yourselves to prayer, and <span class=\"supplied\">then</span> you should be <span class=\"idiom\">together</span><span class=\"note\">“at the same”</span>again, lest Satan tempt you because of your lack of self control.'),
('LEB', '1 Corinthians', '7', '6', '1', 'But I say this as a concession, not as a command.'),
('LEB', '1 Corinthians', '7', '7', '1', 'I wish all people could be like myself, but each one has his own gift from God, one in this way and another in that way.'),
('LEB', '1 Corinthians', '7', '8', '2', 'Now I say to the unmarried and to the widows: <span class=\"supplied\">It is</span> good for them if they remain as I <span class=\"supplied\">am</span>.'),
('LEB', '1 Corinthians', '7', '9', '2', 'But if they cannot control themselves, they should marry, for it is better to marry than to burn <span class=\"supplied\">with sexual desire</span>.'),
('LEB', '1 Corinthians', '7', '10', '3', 'To the married I command—not I, but the Lord—a wife must not separate from <span class=\"supplied\">her</span> husband.'),
('LEB', '1 Corinthians', '7', '11', '3', 'But if indeed she does separate, she must remain unmarried or be reconciled to her husband. And a husband must not divorce <span class=\"supplied\">his</span> wife.'),
('LEB', '1 Corinthians', '7', '12', '4', 'Now to the rest I say—not the Lord—if any brother has an unbelieving wife and she consents to live with him, he must not divorce her.'),
('LEB', '1 Corinthians', '7', '13', '4', 'And if any wife has an unbelieving husband and he consents to live with her, she must not divorce her husband.'),
('LEB', '1 Corinthians', '7', '14', '4', 'For the unbelieving husband is sanctified by his wife, and the unbelieving wife is sanctified by the brother, since otherwise your children are unclean, but now they are holy.'),
('LEB', '1 Corinthians', '7', '15', '4', 'But if the unbeliever leaves, let him leave. The brother or the sister is not bound in such <span class=\"supplied\">cases</span>. But God has called us<span class=\"note\">Some manuscripts have “you” (plural)</span>in peace.'),
('LEB', '1 Corinthians', '7', '16', '4', 'For how do you know, wife, whether you will save your husband? Or how do you know, husband, whether you will save your wife?'),
('LEB', '1 Corinthians', '7', '17', '5', 'But to each one as the Lord has apportioned. As God has called each one, thus let him live—and thus I order in all the churches.'),
('LEB', '1 Corinthians', '7', '18', '5', 'Was anyone called <span class=\"supplied\">after</span>being circumcised? He must not undo his circumcision. Was anyone called in uncircumcision? He must not become circumcised.'),
('LEB', '1 Corinthians', '7', '19', '5', 'Circumcision is nothing and uncircumcision is nothing, but the keeping of the commandments of God.'),
('LEB', '1 Corinthians', '7', '20', '5', 'Each one in the calling in which he was called—in this he should remain.'),
('LEB', '1 Corinthians', '7', '21', '5', 'Were you called <span class=\"supplied\">while</span> a slave? Do not let it be a concern to you. But if indeed you are able to become free, rather make use of <span class=\"supplied\">it</span>.'),
('LEB', '1 Corinthians', '7', '22', '5', 'For the one who is called in the Lord <span class=\"supplied\">while</span> a slave is the Lord’s freedperson. Likewise the one who is called <span class=\"supplied\">while</span> free is a slave of Christ.'),
('LEB', '1 Corinthians', '7', '23', '5', 'You were bought at a price; do not become slaves of men.'),
('LEB', '1 Corinthians', '7', '24', '5', 'Each one in <span class=\"supplied\">the situation</span> in which he was called, brothers—in this he should remain with God.'),
('LEB', '1 Corinthians', '7', '25', '7', '<span class=\"verse-title\">Concerning the Unmarried</span>Now concerning virgins I do not have a command from the Lord, but I am giving an opinion as one shown mercy by the Lord to be trustworthy.'),
('LEB', '1 Corinthians', '7', '26', '7', 'Therefore, I consider this to be good because of the impending distress, that <span class=\"supplied\">it is</span> good for a man to be thus.'),
('LEB', '1 Corinthians', '7', '27', '7', 'Are you bound to a wife? Do not seek release. Are you free from a wife? Do not seek a wife.'),
('LEB', '1 Corinthians', '7', '28', '7', 'But if you marry, you have not sinned, and if the virgin marries, she has not sinned. But such people will have affliction in the flesh, and I would spare you.'),
('LEB', '1 Corinthians', '7', '29', '7', 'But I say this, brothers: the time is shortened, that from now on even those who have wives should be as <span class=\"supplied\">if they</span> do not have <span class=\"supplied\">wives</span>,'),
('LEB', '1 Corinthians', '7', '30', '7', 'and those who weep as <span class=\"supplied\">if they</span> do not weep, and those who rejoice as <span class=\"supplied\">if they</span> do not rejoice, and those who buy as <span class=\"supplied\">if they</span> do not possess,'),
('LEB', '1 Corinthians', '7', '31', '7', 'and those who make use of the world as <span class=\"supplied\">if they</span> do not make full use of <span class=\"supplied\">it</span>. For the present form of this world is passing away.'),
('LEB', '1 Corinthians', '7', '32', '8', 'But I want you to be free from care. The unmarried person cares for the things of the Lord, how he may please the Lord.'),
('LEB', '1 Corinthians', '7', '33', '8', 'But the one who is married cares for the things of the world, how he may please his wife,'),
('LEB', '1 Corinthians', '7', '34', '8', 'and he is divided. And the unmarried woman or the virgin cares for the things of the Lord, in order that she may be holy both in body and in spirit. But the married woman cares for the things of the world, how she may please her husband.'),
('LEB', '1 Corinthians', '7', '35', '8', 'Now I am saying this for your own benefit, not that I may put a restriction on you, but to promote appropriate and devoted service to the Lord without distraction.'),
('LEB', '1 Corinthians', '7', '36', '9', 'But if anyone thinks he is behaving dishonorably concerning his virgin, if she is past her prime<span class=\"note\">Or “if his passions are strong” (it is not clear in context whether this term refers to the man or to the woman)</span>and it ought to be thus, let him do what he wishes. He does not sin. Let them marry.'),
('LEB', '1 Corinthians', '7', '37', '9', 'But he who stands firm in his heart, not having necessity, but has authority concerning his own will, and has decided this in his own heart, to keep his own virgin, he will do well.'),
('LEB', '1 Corinthians', '7', '38', '9', 'So then, the one who marries<span class=\"note\">Or perhaps “the one who gives in marriage”</span>his own virgin does well, and the one who does not marry <span class=\"supplied\">her</span> will do better.'),
('LEB', '1 Corinthians', '7', '39', '10', 'A wife is bound for as long a time <span class=\"supplied\">as</span> her husband lives. But if her husband <span class=\"idiom\">dies</span><span class=\"note\">“falls asleep”</span>, she is free to marry whomever she wishes, only in the Lord.'),
('LEB', '1 Corinthians', '7', '40', '10', 'But she is happier if she remains thus, according to my opinion—and I think I have the Spirit of God.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '8', '1', '1', '<span class=\"verse-title\">Concerning Food Sacrificed to Idols</span>Now concerning food sacrificed to idols, we know that “we all have knowledge.”<span class=\"note\">Considered by many interpreters to be a slogan used by the Corinthians to justify their behavior</span>Knowledge puffs up, but love builds up.'),
('LEB', '1 Corinthians', '8', '2', '1', 'If anyone thinks he knows anything, he has not yet known as it is necessary to know.'),
('LEB', '1 Corinthians', '8', '3', '1', 'But if anyone loves God, this one is known by him.'),
('LEB', '1 Corinthians', '8', '4', '2', 'Therefore, concerning the eating of food sacrificed to idols, we know that “an idol <span class=\"supplied\">is</span> nothing in the world” and that “<span class=\"supplied\">there is</span> no God except one.”<span class=\"note\">Considered by many interpreters to be slogans used by the Corinthians to justify their behavior</span>'),
('LEB', '1 Corinthians', '8', '5', '2', 'For even if after all <span class=\"supplied\">there</span> are so-called gods, whether in heaven or on earth, just as <span class=\"supplied\">there</span> are many gods and many lords,'),
('LEB', '1 Corinthians', '8', '6', '3', 'yet to us <span class=\"supplied\">there is</span> one God, the Father,  from whom <span class=\"supplied\">are</span> all <span class=\"supplied\">things</span>, and we <span class=\"supplied\">are</span> for him,  and <span class=\"supplied\">there is</span> one Lord, Jesus Christ,  through whom <span class=\"supplied\">are</span> all <span class=\"supplied\">things</span>, and we <span class=\"supplied\">are</span> through him.'),
('LEB', '1 Corinthians', '8', '7', '4', 'But this knowledge <span class=\"supplied\">is</span> not in everyone. But some, being accustomed until now to the idol, eat <span class=\"supplied\">this food</span> as food sacrificed to idols, and their conscience, <span class=\"supplied\">because it</span>is weak, is defiled.'),
('LEB', '1 Corinthians', '8', '8', '4', 'But food does not bring us close to God. For neither if we eat do we have more, nor if we do not eat do we lack.<span class=\"note\">Some manuscripts omit “For” and have “Neither if we do not eat do we lack, nor if we do eat do we have more”</span>'),
('LEB', '1 Corinthians', '8', '9', '4', 'But watch out lest somehow this right of yours becomes a cause for stumbling to the weak.'),
('LEB', '1 Corinthians', '8', '10', '4', 'For if someone should see you who has knowledge reclining for a meal in an idol’s temple, will not his conscience, <span class=\"supplied\">because it</span>is weak, be strengthened so that <span class=\"supplied\">he</span> eats the food sacrificed to idols?'),
('LEB', '1 Corinthians', '8', '11', '4', 'For the one who is weak—the brother for whom Christ died—is destroyed by your knowledge.'),
('LEB', '1 Corinthians', '8', '12', '4', 'Now <span class=\"supplied\">if you</span>sin in this way against the brothers and wound their conscience, which is weak, you sin against Christ.'),
('LEB', '1 Corinthians', '8', '13', '4', 'Therefore, if food causes my brother to sin, I will never eat meat <span class=\"idiom\">forever</span><span class=\"note\">“for the age”</span>, in order that I may not cause my brother to sin.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '9', '1', '1', '<span class=\"verse-title\">Paul Gives Up His Rights as an Apostle</span>Am I not free? Am I not an apostle? Have I not seen Jesus our Lord? Are you not my work in the Lord?'),
('LEB', '1 Corinthians', '9', '2', '1', 'If to others I am not an apostle, yet indeed I am to you, for you are my seal of apostleship in the Lord.'),
('LEB', '1 Corinthians', '9', '3', '1', 'My defense to those who examine me is this:'),
('LEB', '1 Corinthians', '9', '4', '1', 'Do we not have the right to eat and drink?'),
('LEB', '1 Corinthians', '9', '5', '1', 'Do we not have the right to take along a sister <span class=\"supplied\">as</span> wife, like the rest of the apostles and the brothers of the Lord and Cephas?'),
('LEB', '1 Corinthians', '9', '6', '1', 'Or do only I and Barnabas not have the right <span class=\"idiom\">to refrain from working</span><span class=\"note\">“not to work”</span>?'),
('LEB', '1 Corinthians', '9', '7', '1', 'Who ever serves as a soldier at his own expense? Who plants a vineyard and does not eat the fruit of it? Who<span class=\"note\">Some manuscripts have “Or who”</span>shepherds a flock and does not drink<span class=\"note\">“eat”</span>from the milk of the flock?'),
('LEB', '1 Corinthians', '9', '8', '1', 'I am not saying these <span class=\"supplied\">things</span> according to a human perspective. Or does the law not also say these <span class=\"supplied\">things</span>?'),
('LEB', '1 Corinthians', '9', '9', '1', 'For in the law of Moses it is written, “You must not muzzle an ox <span class=\"supplied\">while it</span>is threshing.”<span class=\"note\">Deut 25:4</span>It is not about oxen God is concerned, is it?'),
('LEB', '1 Corinthians', '9', '10', '1', 'Or doubtless does he speak <span class=\"idiom\">for our sake</span><span class=\"note\">“for the sake of us”</span>? For it is written <span class=\"idiom\">for our sake</span><span class=\"note\">“for the sake of us”</span>, because the one who plows ought to plow in hope and the one who threshes <span class=\"supplied\">ought to do so</span> in hope of a share.'),
('LEB', '1 Corinthians', '9', '11', '1', 'If we have sown spiritual <span class=\"supplied\">things</span> among you, <span class=\"supplied\">is it too</span> great <span class=\"supplied\">a thing</span> if we reap material <span class=\"supplied\">things</span> from you?'),
('LEB', '1 Corinthians', '9', '12', '1', 'If others share this right over you, do we not <span class=\"supplied\">do so</span> even more? Yet we have not made use of this right, but we endure all <span class=\"supplied\">things</span>, in order that we may not cause any hindrance to the gospel of Christ.'),
('LEB', '1 Corinthians', '9', '13', '2', 'Do you not know that those performing the holy services eat the things from the temple, <span class=\"supplied\">and</span> those attending to the altar have a share with the altar?'),
('LEB', '1 Corinthians', '9', '14', '2', 'In the <span class=\"supplied\">same</span> way also the Lord ordered those who proclaim the gospel to live from the gospel.'),
('LEB', '1 Corinthians', '9', '15', '2', 'But I have not made use of any of these <span class=\"supplied\">rights</span>. And I am not writing these <span class=\"supplied\">things</span> in order that it may be thus with me. For <span class=\"supplied\">it would be</span> better to me rather to die than <span class=\"supplied\">for</span> anyone to deprive me of my reason for boasting.'),
('LEB', '1 Corinthians', '9', '16', '2', 'For if I proclaim the gospel, it is not to me a reason for boasting, for necessity is imposed on me. For woe is to me if I do not proclaim the gospel.'),
('LEB', '1 Corinthians', '9', '17', '2', 'For if I do this voluntarily, I have a reward, but if <span class=\"supplied\">I do so</span> unwillingly, I have been entrusted with a stewardship.'),
('LEB', '1 Corinthians', '9', '18', '2', 'What then is my reward? That <span class=\"supplied\">when I</span>proclaim the gospel, I may offer the gospel free of charge, in order not to make full use of my right in the gospel.'),
('LEB', '1 Corinthians', '9', '19', '3', 'For <span class=\"supplied\">although I</span>am free from all <span class=\"supplied\">people</span>, I have enslaved myself to all, in order that I may gain more.'),
('LEB', '1 Corinthians', '9', '20', '3', 'I have become like a Jew to the Jews, in order that I may gain the Jews. To those under the law <span class=\"supplied\">I became</span> as under the law (<span class=\"supplied\">although I</span>myself am not under the law) in order that I may gain those under the law.'),
('LEB', '1 Corinthians', '9', '21', '3', 'To those outside the law <span class=\"supplied\">I became</span> as outside the law (<span class=\"supplied\">although I</span>am not outside the law of God, but subject to the law of Christ) in order that I may gain those outside the law.'),
('LEB', '1 Corinthians', '9', '22', '3', 'To the weak I became weak, in order that I may gain the weak. I have become all <span class=\"supplied\">things</span> to all <span class=\"supplied\">people</span>, in order that by all means I may save some.'),
('LEB', '1 Corinthians', '9', '23', '3', 'I do all <span class=\"supplied\">this</span> for the sake of the gospel, in order that I may become a participant with it.'),
('LEB', '1 Corinthians', '9', '24', '4', 'Do you not know that those who run in the stadium all run, but one receives the prize? Run in such a way that you may win.'),
('LEB', '1 Corinthians', '9', '25', '4', 'And everyone who competes exercises self-control in all <span class=\"supplied\">things</span>. Thus those <span class=\"supplied\">do so</span> in order that they may receive a perishable crown, but we an imperishable <span class=\"supplied\">one</span>.'),
('LEB', '1 Corinthians', '9', '26', '4', 'Therefore I run in this way, not as <span class=\"supplied\">running</span> aimlessly; I box in this way, not as beating the air.'),
('LEB', '1 Corinthians', '9', '27', '4', 'But I discipline my body and subjugate <span class=\"supplied\">it</span>, lest somehow <span class=\"supplied\">after</span>preaching to others, <span class=\"supplied\">I</span> myself should become disqualified.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '10', '1', '1', '<span class=\"verse-title\">A History Lesson from Israel</span>For I do not want you to be ignorant, brothers, that our fathers were all under the cloud and all went through the sea,'),
('LEB', '1 Corinthians', '10', '2', '1', 'and all were baptized into Moses in the cloud and in the sea,'),
('LEB', '1 Corinthians', '10', '3', '1', 'and all ate the same spiritual food,'),
('LEB', '1 Corinthians', '10', '4', '1', 'and all drank the same spiritual drink. For they drank from the spiritual rock that followed <span class=\"supplied\">them</span>, and the rock was Christ.'),
('LEB', '1 Corinthians', '10', '5', '1', 'But God was not pleased with the majority of them, for they were struck down in the desert.'),
('LEB', '1 Corinthians', '10', '6', '2', 'Now these <span class=\"supplied\">things</span> happened <span class=\"supplied\">as</span> examples for us, so that we should not be desirers of evil <span class=\"supplied\">things</span>, just as those also desired <span class=\"supplied\">them</span>,'),
('LEB', '1 Corinthians', '10', '7', '2', 'and not become idolaters, as some of them <span class=\"supplied\">did</span>, just as it is written, “The people sat down to eat and drink, and stood up to play,”<span class=\"note\">Exod 32:6</span>'),
('LEB', '1 Corinthians', '10', '8', '2', 'nor commit sexual immorality, as some of them committed sexual immorality, and twenty-three thousand fell in one day,'),
('LEB', '1 Corinthians', '10', '9', '2', 'nor put Christ to the test, as some of them tested <span class=\"supplied\">him</span>, and were destroyed by snakes,'),
('LEB', '1 Corinthians', '10', '10', '2', 'nor grumble, just as some of them grumbled, and were destroyed by the destroyer.'),
('LEB', '1 Corinthians', '10', '11', '2', 'Now these <span class=\"supplied\">things</span> happened to those <span class=\"supplied\">people</span> as an example, but are written for our instruction, on whom the ends of the ages have come.'),
('LEB', '1 Corinthians', '10', '12', '2', 'Therefore, the one who thinks that he stands must watch out lest he fall.'),
('LEB', '1 Corinthians', '10', '13', '2', 'Temptation has not come upon you except <span class=\"supplied\">what is</span> common to humanity. But God <span class=\"supplied\">is</span> faithful, who will not permit you to be tempted beyond what you are able, but will also make a way out together with the temptation, <span class=\"supplied\">so that you</span> may be able to endure <span class=\"supplied\">it</span>.'),
('LEB', '1 Corinthians', '10', '14', '4', '<span class=\"verse-title\">Warning Against Idolatry</span>Therefore, my dear friends, flee from idolatry.'),
('LEB', '1 Corinthians', '10', '15', '4', 'I am speaking as to sensible <span class=\"supplied\">people</span>; you judge what I am saying.'),
('LEB', '1 Corinthians', '10', '16', '4', 'The cup of blessing which we bless, is it not a participation in the blood of Christ? The bread which we break, is it not a participation in the body of Christ?'),
('LEB', '1 Corinthians', '10', '17', '4', 'Because <span class=\"supplied\">there is</span> one bread, <span class=\"supplied\">we</span> who <span class=\"supplied\">are</span> many are one body, for <span class=\"supplied\">we</span> all share from the one bread.'),
('LEB', '1 Corinthians', '10', '18', '4', 'Consider Israel according to the flesh: are not the ones who eat the sacrifices sharers in the altar?'),
('LEB', '1 Corinthians', '10', '19', '4', 'Therefore, what am I saying? That food sacrificed to idols is anything, or that an idol is anything?'),
('LEB', '1 Corinthians', '10', '20', '4', '<span class=\"supplied\">No</span>, but that <span class=\"supplied\">the things</span> which they sacrifice, they sacrifice to demons and not to God, and I do not want you to become sharers with demons.'),
('LEB', '1 Corinthians', '10', '21', '4', 'You are not able to drink the cup of the Lord and the cup of demons. You are not able to share the table of the Lord and the table of demons.'),
('LEB', '1 Corinthians', '10', '22', '4', 'Or are we attempting to provoke the Lord to jealousy? We are not stronger than he <span class=\"supplied\">is, are we</span>?'),
('LEB', '1 Corinthians', '10', '23', '6', '<span class=\"verse-title\">Freedom in Christ</span>All <span class=\"supplied\">things</span> are permitted, but not all <span class=\"supplied\">things</span> are profitable. All <span class=\"supplied\">things</span> are permitted, but not all <span class=\"supplied\">things</span> build up.'),
('LEB', '1 Corinthians', '10', '24', '6', 'Let no one seek <span class=\"idiom\">his own good</span><span class=\"note\">“the <span class=\"supplied\">-</span> of himself”; “good” is implied</span>but the <span class=\"supplied\">good</span> of the other.'),
('LEB', '1 Corinthians', '10', '25', '6', 'Eat everything that is sold in the meat market, <span class=\"idiom\">asking no questions</span><span class=\"note\">“questioning nothing”</span>for the sake of the conscience,'),
('LEB', '1 Corinthians', '10', '26', '6', 'for “the earth <span class=\"supplied\">is</span> the Lord’s, and its fullness.”<span class=\"note\">Ps 24:1, and an allusion to Ps 50:12; 89:11</span>'),
('LEB', '1 Corinthians', '10', '27', '6', 'If any of the unbelievers invites you, and you want to go, eat everything that is set before you, <span class=\"idiom\">asking no questions</span><span class=\"note\">“questioning nothing”</span>for the sake of the conscience.'),
('LEB', '1 Corinthians', '10', '28', '6', 'But if someone says to you, “This is offered to idols,” do not eat <span class=\"supplied\">it</span>, for the sake of that one who informed <span class=\"supplied\">you</span> and the conscience.'),
('LEB', '1 Corinthians', '10', '29', '6', 'Now I am not speaking about your own conscience, but the <span class=\"supplied\">conscience</span> of the other <span class=\"supplied\">person</span>. For why <span class=\"supplied\">is</span> my freedom judged by another’s conscience?'),
('LEB', '1 Corinthians', '10', '30', '6', 'If I partake with thankfulness, why am I slandered concerning that for which I give thanks?'),
('LEB', '1 Corinthians', '10', '31', '7', 'Therefore, whether you eat or you drink or whatever you do, do all <span class=\"supplied\">things</span> for the glory of God.'),
('LEB', '1 Corinthians', '10', '32', '7', '<span class=\"idiom\">Give no offense</span><span class=\"note\">“be blameless”</span>both to Jews and to Greeks and to the church of God,'),
('LEB', '1 Corinthians', '10', '33', '7', 'just as I also please all <span class=\"supplied\">people</span> in all <span class=\"supplied\">things</span>, not seeking my own benefit, but the <span class=\"supplied\">benefit</span> of the many, in order that they may be saved.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '11', '1', '1', '<span class=\"verse-title\">Concerning Head Coverings in Worship</span>Become imitators of me, just as I also <span class=\"supplied\">am</span> of Christ.'),
('LEB', '1 Corinthians', '11', '2', '2', 'Now I praise you that you remember me <span class=\"supplied\">in</span> all <span class=\"supplied\">things</span>, and just as I handed over to you the traditions, you hold fast to <span class=\"supplied\">them</span>.'),
('LEB', '1 Corinthians', '11', '3', '2', 'But I want you to know that Christ is the head of every man, and the man <span class=\"supplied\">is the</span> head of the woman, and <span class=\"supplied\">the</span> head of Christ <span class=\"supplied\">is</span> God.'),
('LEB', '1 Corinthians', '11', '4', '2', 'Every man who prays or prophesies <span class=\"supplied\">while</span>having <span class=\"supplied\">something</span>on <span class=\"supplied\">his</span> head dishonors his head,'),
('LEB', '1 Corinthians', '11', '5', '2', 'but every woman who prays or prophesies with uncovered head dishonors her head, for she is one and the same with the one whose <span class=\"supplied\">head</span> is shaved.'),
('LEB', '1 Corinthians', '11', '6', '2', 'For if a woman does not cover herself, let her <span class=\"supplied\">hair</span> be shorn off. But if <span class=\"supplied\">it is</span> shameful for a woman to <span class=\"supplied\">have her head</span><span class=\"note\">“to be”</span>shorn or shaved, let her cover her <span class=\"supplied\">head</span>.<span class=\"note\">“herself”</span>'),
('LEB', '1 Corinthians', '11', '7', '2', 'For indeed a man ought not to cover his head, <span class=\"supplied\">because he</span>is the image and glory of God, but the woman is the glory of the man.'),
('LEB', '1 Corinthians', '11', '8', '2', 'For man is not from woman, but woman from man.'),
('LEB', '1 Corinthians', '11', '9', '2', 'For indeed man was not created for the sake of the woman, but woman for the sake of the man.'),
('LEB', '1 Corinthians', '11', '10', '2', 'Because of this, the woman ought to have <span class=\"supplied\">a symbol of</span> authority on her head, on account of the angels.'),
('LEB', '1 Corinthians', '11', '11', '2', 'Nevertheless, neither <span class=\"supplied\">is</span> woman <span class=\"supplied\">anything</span> apart from man, nor <span class=\"supplied\">is</span> man <span class=\"supplied\">anything</span> apart from woman in the Lord.'),
('LEB', '1 Corinthians', '11', '12', '2', 'For just as the woman <span class=\"supplied\">is</span> from the man, thus also the man <span class=\"supplied\">is</span> through the woman. But all <span class=\"supplied\">things</span> <span class=\"supplied\">are</span> from God.'),
('LEB', '1 Corinthians', '11', '13', '2', 'You judge <span class=\"idiom\">for yourselves</span><span class=\"note\">“in you yourselves”</span>: is it fitting for a woman to pray to God <span class=\"supplied\">with her head</span>uncovered?'),
('LEB', '1 Corinthians', '11', '14', '2', 'And does not nature itself teach you that a man, if he wears long hair, it is a dishonor to him?'),
('LEB', '1 Corinthians', '11', '15', '2', 'But a woman, if she wears long hair, it is her glory, because her hair is given<span class=\"note\">Some manuscripts have “is given to her”</span>for a covering.'),
('LEB', '1 Corinthians', '11', '16', '2', 'But if anyone is disposed to be contentious, we have no such custom, nor do the churches of God.'),
('LEB', '1 Corinthians', '11', '17', '4', '<span class=\"verse-title\">Improper Conduct at the Lord’s Supper</span>But in giving this instruction I do not praise <span class=\"supplied\">you</span>, because you come together not for the better but for the worse.'),
('LEB', '1 Corinthians', '11', '18', '4', 'For in the first place, <span class=\"supplied\">when you</span>come together as a church, I hear there are divisions among you, and in part I believe it.'),
('LEB', '1 Corinthians', '11', '19', '4', 'For indeed it is necessary that there be factions among you, in order that those who are approved may become evident among you.'),
('LEB', '1 Corinthians', '11', '20', '4', 'Therefore, <span class=\"supplied\">when</span>you come together in the same <span class=\"supplied\">place</span>, it is not to eat the Lord’s supper.'),
('LEB', '1 Corinthians', '11', '21', '4', 'For <span class=\"supplied\">when you</span>eat <span class=\"supplied\">it</span>, each one of you goes ahead to take his own supper, and one is hungry and another is drunk.'),
('LEB', '1 Corinthians', '11', '22', '4', 'For do you not have houses for eating and drinking? Or do you despise the church of God and humiliate those who do not have <span class=\"supplied\">anything</span>? What shall I say to you? Shall I praise you? In this I will not praise <span class=\"supplied\">you</span>!'),
('LEB', '1 Corinthians', '11', '23', '5', 'For I received from the Lord what I also passed on to you, that the Lord Jesus, on the night in which he was betrayed, took bread,'),
('LEB', '1 Corinthians', '11', '24', '5', 'and <span class=\"supplied\">after he</span>had given thanks, he broke <span class=\"supplied\">it</span> and said, “This is my body which <span class=\"supplied\">is</span> for you. Do this in remembrance of me.”'),
('LEB', '1 Corinthians', '11', '25', '5', 'Likewise also the cup, after they had eaten, saying, “This cup is the new covenant in my blood. Do this, as often as you drink <span class=\"supplied\">it</span>, in remembrance of me.”'),
('LEB', '1 Corinthians', '11', '26', '5', 'For as often as you eat this bread and drink this cup, you proclaim the Lord’s death until he comes.'),
('LEB', '1 Corinthians', '11', '27', '5', 'So then, whoever eats the bread or drinks the cup of the Lord in an unworthy manner will be guilty of the body and the blood of the Lord.'),
('LEB', '1 Corinthians', '11', '28', '5', 'But let a person examine himself, and in this way let him eat from the bread and let him drink from the cup.'),
('LEB', '1 Corinthians', '11', '29', '5', 'For the one who eats and drinks, <span class=\"supplied\">if he</span>does not recognize the body, eats and drinks judgment against himself.'),
('LEB', '1 Corinthians', '11', '30', '5', 'Because of this, many <span class=\"supplied\">are</span> weak and sick among you, and quite a few <span class=\"idiom\">have died</span><span class=\"note\">“have fallen asleep”</span>.'),
('LEB', '1 Corinthians', '11', '31', '5', 'But if we were evaluating ourselves, we would not be judged.'),
('LEB', '1 Corinthians', '11', '32', '5', 'But <span class=\"supplied\">if we</span>are judged by the Lord, we are being disciplined, in order that we will not be condemned with the world.'),
('LEB', '1 Corinthians', '11', '33', '6', 'So then, my brothers, <span class=\"supplied\">when you</span>come together in order to eat <span class=\"supplied\">the Lord’s supper</span>,wait for one another.'),
('LEB', '1 Corinthians', '11', '34', '6', 'If anyone is hungry, let him eat at home, lest you come together for judgment. And I will give directions about the remaining <span class=\"supplied\">matters</span> whenever I come.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '12', '1', '1', '<span class=\"verse-title\">Varieties of Spiritual Gifts</span>Now concerning spiritual <span class=\"supplied\">gifts</span>,<span class=\"note\">Or “spiritual <span class=\"supplied\">things</span>”; possibly “those who possess spiritual gifts”</span>brothers, I do not want you to be ignorant.'),
('LEB', '1 Corinthians', '12', '2', '1', 'You know that when you were pagans, you were led astray to the speechless idols, however you were led.'),
('LEB', '1 Corinthians', '12', '3', '1', 'Therefore I make known to you that no one speaking by the Spirit of God says, “Jesus <span class=\"supplied\">is</span> accursed,” and no one is able to say “Jesus <span class=\"supplied\">is</span> Lord” except by the Holy Spirit.'),
('LEB', '1 Corinthians', '12', '4', '2', 'Now there are varieties of gifts, but the same Spirit,'),
('LEB', '1 Corinthians', '12', '5', '2', 'and there are varieties of ministries, and the same Lord,'),
('LEB', '1 Corinthians', '12', '6', '2', 'and there are varieties of activities, but the same God, who works all <span class=\"supplied\">things</span> in all <span class=\"supplied\">people</span>.'),
('LEB', '1 Corinthians', '12', '7', '2', 'But to each one is given the manifestation of the Spirit for what is beneficial <span class=\"supplied\">to all</span>.'),
('LEB', '1 Corinthians', '12', '8', '2', 'For to one is given a word of wisdom through the Spirit, and to another a word of knowledge by the same Spirit,'),
('LEB', '1 Corinthians', '12', '9', '2', 'to another faith by the same Spirit, to another<span class=\"note\">Some manuscripts have “and to another”</span>gifts of healing by the one Spirit,'),
('LEB', '1 Corinthians', '12', '10', '2', 'to another<span class=\"note\">Some manuscripts have “and to another”</span><span class=\"idiom\">miraculous powers</span><span class=\"note\">“activities of power”</span>, to another<span class=\"note\">Some manuscripts have “and to another”</span>prophecy, to another<span class=\"note\">Some manuscripts have “and to another”</span>distinguishing of spirits, to another kinds of tongues, to another<span class=\"note\">Some manuscripts have “and to another”</span>interpretation of tongues.'),
('LEB', '1 Corinthians', '12', '11', '2', 'But in all these <span class=\"supplied\">things</span> one and the same Spirit is at work, distributing to each one individually just as he wishes.'),
('LEB', '1 Corinthians', '12', '12', '4', '<span class=\"verse-title\">Unity in the Midst of Diversity</span>For just as the body is one and has many members, but all the members of the body, <span class=\"supplied\">although they</span>are many, are one body, thus also Christ.'),
('LEB', '1 Corinthians', '12', '13', '4', 'For by<span class=\"note\">Or “in”</span>one Spirit we were all baptized into one body, whether Jews or Greeks, whether slaves or free <span class=\"supplied\">persons</span>, and all were made to drink one Spirit.'),
('LEB', '1 Corinthians', '12', '14', '4', 'For the body is not one member, but many.'),
('LEB', '1 Corinthians', '12', '15', '4', 'If the foot should say, “Because I am not a hand, I am not <span class=\"supplied\">a part</span> of the body,” not because of this is it not <span class=\"supplied\">a part</span> of the body.'),
('LEB', '1 Corinthians', '12', '16', '4', 'And if the ear should say, “Because I am not an eye, I am not <span class=\"supplied\">a part</span> of the body, not because of this is it not <span class=\"supplied\">a part</span> of the body.'),
('LEB', '1 Corinthians', '12', '17', '4', 'If the whole body <span class=\"supplied\">were</span> an eye, where <span class=\"supplied\">would</span> the hearing <span class=\"supplied\">be</span>? If the whole <span class=\"supplied\">were</span> hearing, where <span class=\"supplied\">would</span> the sense of smell <span class=\"supplied\">be</span>?'),
('LEB', '1 Corinthians', '12', '18', '4', 'But now God has placed the members, each one of them, in the body just as he wanted.'),
('LEB', '1 Corinthians', '12', '19', '4', 'And if they all were one member, where <span class=\"supplied\">would</span> the body <span class=\"supplied\">be</span>?'),
('LEB', '1 Corinthians', '12', '20', '4', 'But now <span class=\"supplied\">there are</span> many members, but one body.'),
('LEB', '1 Corinthians', '12', '21', '5', 'Now the eye is not able to say to the hand, “I do not have need of you,” or again, the head to the feet, “I do not have need of you.”'),
('LEB', '1 Corinthians', '12', '22', '5', 'But by much more the members of the body which are thought to be weaker are necessary,'),
('LEB', '1 Corinthians', '12', '23', '5', 'and <span class=\"supplied\">the parts</span> of the body which we think to be less honorable, these we clothe with more abundant honor, and our unpresentable <span class=\"supplied\">parts</span> come to have more abundant presentability,'),
('LEB', '1 Corinthians', '12', '24', '5', 'but our presentable <span class=\"supplied\">parts</span> do not have need <span class=\"supplied\">of this</span>. Yet God composed the body by giving more abundant honor to the part which lacked <span class=\"supplied\">it</span>,'),
('LEB', '1 Corinthians', '12', '25', '5', 'in order that there not be a division in the body, but the members would have the same concern for one another.'),
('LEB', '1 Corinthians', '12', '26', '5', 'And if one member suffers, all the members suffer together; if a member<span class=\"note\">Some manuscripts have “one member”</span>is honored, all the members rejoice with <span class=\"supplied\">it</span>.'),
('LEB', '1 Corinthians', '12', '27', '6', 'Now you are the body of Christ, and members <span class=\"idiom\">of it individually</span><span class=\"note\">“by part”</span>,'),
('LEB', '1 Corinthians', '12', '28', '6', 'and whom God has appointed in the church: first, apostles, second, prophets, third, teachers, then miracles, then gifts of healing, helps, administrations, kinds of tongues.'),
('LEB', '1 Corinthians', '12', '29', '6', 'Not all <span class=\"supplied\">are</span> apostles, <span class=\"supplied\">are they</span>?Not all <span class=\"supplied\">are</span> prophets, <span class=\"supplied\">are they</span>?Not all <span class=\"supplied\">are</span> teachers, <span class=\"supplied\">are they</span>?Not all <span class=\"supplied\">are workers of</span> miracles, <span class=\"supplied\">are they</span>?'),
('LEB', '1 Corinthians', '12', '30', '6', 'Not all have gifts of healing, <span class=\"supplied\">do they</span>?Not all speak with tongues, <span class=\"supplied\">do they</span>?Not all interpret, <span class=\"supplied\">do they</span>?'),
('LEB', '1 Corinthians', '12', '31', '6', 'But strive<span class=\"note\">Or “you are striving” (some understand the form of this verb to be indicative mood rather than imperative mood)</span>for the greater gifts. And I will show you a still more excellent way.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '13', '1', '1', '<span class=\"verse-title\">Love, the More Excellent Way</span>If I speak with the tongues of men and of angels, but do not have love, I have become a ringing brass gong or a clashing cymbal.'),
('LEB', '1 Corinthians', '13', '2', '1', 'And if I have <span class=\"supplied\">the gift of</span> prophecy and I know all mysteries and all knowledge, and if I have all faith so that <span class=\"supplied\">I can</span> remove mountains, but do not have love, I am nothing.'),
('LEB', '1 Corinthians', '13', '3', '1', 'And if I parcel out all my possessions, and if I hand over my body in order that I will be burned,<span class=\"note\">Some manuscripts have “in order that I may boast”</span>but do not have love, it benefits <span class=\"supplied\">me</span> nothing.'),
('LEB', '1 Corinthians', '13', '4', '2', 'Love is patient, love is kind, love is not jealous, <span class=\"supplied\">it</span> does not boast, <span class=\"supplied\">it</span> does not become conceited,'),
('LEB', '1 Corinthians', '13', '5', '2', '<span class=\"supplied\">it</span> does not behave dishonorably, <span class=\"supplied\">it</span> <span class=\"idiom\">is not selfish</span><span class=\"note\">“does not seek the things of itself”</span>, <span class=\"supplied\">it</span> does not become angry, <span class=\"supplied\">it</span> does not keep a record of wrongs,'),
('LEB', '1 Corinthians', '13', '6', '2', '<span class=\"supplied\">it</span> does not rejoice at unrighteousness, but rejoices with the truth,'),
('LEB', '1 Corinthians', '13', '7', '2', 'bears all <span class=\"supplied\">things</span>, believes all <span class=\"supplied\">things</span>, hopes all <span class=\"supplied\">things</span>, endures all <span class=\"supplied\">things</span>.'),
('LEB', '1 Corinthians', '13', '8', '3', 'Love never ends. But if <span class=\"supplied\">there are</span> prophecies, they will pass away. If <span class=\"supplied\">there are</span> tongues, they will cease. If <span class=\"supplied\">there is</span> knowledge, it will pass away.'),
('LEB', '1 Corinthians', '13', '9', '3', 'For we know in part and we prophesy in part,'),
('LEB', '1 Corinthians', '13', '10', '3', 'but whenever the perfect comes, the partial will pass away.'),
('LEB', '1 Corinthians', '13', '11', '3', 'When I was a child, I spoke like a child, I thought like a child, I reasoned like a child. When I became a man, I set aside the things of a child.'),
('LEB', '1 Corinthians', '13', '12', '3', 'For now we see through a mirror <span class=\"idiom\">indirectly</span><span class=\"note\">“in an indirect image”</span>, but then face to face. Now I know in part, but then I will know completely, just as I have also been completely known.'),
('LEB', '1 Corinthians', '13', '13', '3', 'And now these three <span class=\"supplied\">things</span> remain: faith, hope, <span class=\"supplied\">and</span> love. But the greatest of these <span class=\"supplied\">is</span> love.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '14', '1', '1', '<span class=\"verse-title\">Appropriate Use of Prophecy and Tongues</span>Pursue love, and strive for spiritual <span class=\"supplied\">gifts</span>, but especially that you may prophesy.'),
('LEB', '1 Corinthians', '14', '2', '1', 'For the one who speaks in a tongue does not speak to people but to God, because no one understands, but by the Spirit<span class=\"note\">Or “in the Spirit”; or “in <span class=\"supplied\">his</span> spirit”</span>he speaks mysteries.'),
('LEB', '1 Corinthians', '14', '3', '1', 'But the one who prophesies speaks to people edification and encouragement and consolation.'),
('LEB', '1 Corinthians', '14', '4', '1', 'The one who speaks in a tongue edifies himself, but the one who prophesies edifies the church.'),
('LEB', '1 Corinthians', '14', '5', '1', 'Now I want you all to speak with tongues, but even more that you may prophesy. The one who prophesies <span class=\"supplied\">is</span> greater than the one who speaks with tongues, unless he interprets, in order that the church may receive edification.'),
('LEB', '1 Corinthians', '14', '6', '2', 'But now, brothers, if I come to you speaking with tongues, how do I benefit you, unless I speak to you either with a revelation or with knowledge or with a prophecy or with a teaching?'),
('LEB', '1 Corinthians', '14', '7', '2', 'Likewise, the inanimate things which produce a sound, whether flute or lyre, if they do not produce a distinction in the tones, how will it be known what is played on the flute or on the lyre?'),
('LEB', '1 Corinthians', '14', '8', '2', 'For indeed, if the trumpet produces an indistinct sound, who will prepare for battle?'),
('LEB', '1 Corinthians', '14', '9', '2', 'And so you through the tongue, unless you produce a clear message, how will it be known what is spoken? For you will be speaking into the air.'),
('LEB', '1 Corinthians', '14', '10', '2', 'There are probably so many kinds of languages in the world, and none without meaning.'),
('LEB', '1 Corinthians', '14', '11', '2', 'Therefore, if I do not know the meaning of the language, I will be a barbarian to the one who is speaking, and the one who is speaking <span class=\"supplied\">will be</span> a barbarian in my <span class=\"supplied\">judgment</span>.'),
('LEB', '1 Corinthians', '14', '12', '2', 'In this way also you, since you are zealous of spiritual <span class=\"supplied\">gifts</span>, seek for the edification of the church, in order that you may abound.'),
('LEB', '1 Corinthians', '14', '13', '3', 'Therefore the one who speaks in a tongue must pray that he may interpret.'),
('LEB', '1 Corinthians', '14', '14', '3', 'For if I pray in a tongue, my spirit prays but my mind is unproductive.'),
('LEB', '1 Corinthians', '14', '15', '3', '<span class=\"idiom\">Therefore what should I do</span><span class=\"note\">“what therefore is it”</span>? I will pray with my spirit, but I will also pray with my mind. I will sing praise with my spirit, but I will also sing praise with my mind.'),
('LEB', '1 Corinthians', '14', '16', '3', 'For otherwise, if you praise in <span class=\"supplied\">your</span> spirit, how will the one who fills the place of the outsider say the “amen” at your thanksgiving, because he does not know what you are saying?'),
('LEB', '1 Corinthians', '14', '17', '3', 'For indeed you are giving thanks well, but the other person is not edified.'),
('LEB', '1 Corinthians', '14', '18', '3', 'I give thanks to God <span class=\"supplied\">that</span> I speak with tongues more than all of you,'),
('LEB', '1 Corinthians', '14', '19', '3', 'but in the church I prefer to speak five words with my mind, in order that I may instruct other <span class=\"supplied\">people</span>, than ten thousand words in a tongue.'),
('LEB', '1 Corinthians', '14', '20', '4', 'Brothers, do not become children in <span class=\"supplied\">your</span> understanding, but with respect to wickedness be as a child, and in <span class=\"supplied\">your</span> understanding be mature.'),
('LEB', '1 Corinthians', '14', '21', '4', 'In the law it is written: “By those who speak a foreign language  and by the lips of others  I will speak to this people,  and not even in this way will they obey me,”<span class=\"note\">Isa 28:11–12</span>'),
('LEB', '1 Corinthians', '14', '22', '6', 'says the Lord.'),
('LEB', '1 Corinthians', '14', '23', '6', 'So then, tongues are for a sign not to those who believe, but to unbelievers, but prophecy <span class=\"supplied\">is</span> not for unbelievers, but for those who believe.'),
('LEB', '1 Corinthians', '14', '24', '6', 'Therefore, if the whole church comes together at the same <span class=\"supplied\">time</span> and all speak with tongues, and outsiders or unbelievers enter, will they not say that you are out of your minds?'),
('LEB', '1 Corinthians', '14', '25', '6', 'But if all prophesy, and some unbeliever or outsider enters, he is convicted by all, he is judged by all,'),
('LEB', '1 Corinthians', '14', '26', '8', '<span class=\"verse-title\">Specific Instructions for Orderly Worship Services</span><span class=\"idiom\">Therefore what should you do</span><span class=\"note\">“what therefore is it”</span>, brothers? Whenever you come together, each one of you has a psalm, has a teaching, has a revelation, has a tongue, has an interpretation. All <span class=\"supplied\">things</span> must be <span class=\"supplied\">done</span> for edification.'),
('LEB', '1 Corinthians', '14', '27', '8', 'If anyone speaks in a tongue, <span class=\"supplied\">it must be</span> on one occasion two or at most three, and <span class=\"idiom\">one after the other</span><span class=\"note\">“in turn”</span>, and one must interpret.'),
('LEB', '1 Corinthians', '14', '28', '8', 'But if there is no interpreter, he must be silent in the church, but let him speak to himself and to God.'),
('LEB', '1 Corinthians', '14', '29', '8', 'Let two or three prophets speak, and the others evaluate.'),
('LEB', '1 Corinthians', '14', '30', '8', 'And if <span class=\"supplied\">something</span> is revealed to another who is seated, the first must be silent.'),
('LEB', '1 Corinthians', '14', '31', '8', 'For you are all able to prophesy <span class=\"idiom\">in turn</span><span class=\"note\">“one at a time</span>, in order that all may learn and all may be encouraged,'),
('LEB', '1 Corinthians', '14', '32', '8', 'and the spirits of prophets are subject to prophets.'),
('LEB', '1 Corinthians', '14', '33', '8', 'For God is not <span class=\"supplied\">a God of</span> disorder but of peace.'),
('LEB', '1 Corinthians', '14', '34', '9', 'As in all the churches of the saints,'),
('LEB', '1 Corinthians', '14', '35', '9', 'the women must be silent in the churches, for it is not permitted for them to speak, but they must be in submission, just as the law also says.'),
('LEB', '1 Corinthians', '14', '36', '9', 'But if they want to learn something, let them ask their own husbands at home, for it is shameful for a woman to speak in church.'),
('LEB', '1 Corinthians', '14', '37', '10', 'If anyone thinks he is a prophet or spiritual,<span class=\"note\">Or “or one who possesses the Spirit”</span>he should recognize that <span class=\"supplied\">the things</span> which I am writing to you are of the Lord.<span class=\"note\">Some manuscripts have “are a command of the Lord”</span>'),
('LEB', '1 Corinthians', '14', '38', '10', 'But if anyone ignores <span class=\"supplied\">this</span>, he is ignored.<span class=\"note\">Or “if anyone is ignorant, let him be ignorant”</span>'),
('LEB', '1 Corinthians', '14', '39', '10', 'So then, my brothers, desire to prophesy, and do not prevent speaking with tongues.'),
('LEB', '1 Corinthians', '14', '40', '10', 'But let all <span class=\"supplied\">things</span> be <span class=\"supplied\">done</span> decently and according to proper procedure.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '15', '1', '1', '<span class=\"verse-title\">Paul’s Gospel and the Resurrection of Christ</span>Now I make known to you, brothers, the gospel which I proclaimed to you, which you have also received, in which you also stand,'),
('LEB', '1 Corinthians', '15', '2', '1', 'by which you are also being saved, if you hold fast to the message I proclaimed to you, unless you believed to no purpose.'),
('LEB', '1 Corinthians', '15', '3', '1', 'For I passed on to you <span class=\"idiom\">as of first importance</span><span class=\"note\">“among the first <span class=\"supplied\">things</span>”</span>what I also received, that Christ died for our sins according to the scriptures,'),
('LEB', '1 Corinthians', '15', '4', '1', 'and that he was buried, and that he was raised up on the third day according to the scriptures,'),
('LEB', '1 Corinthians', '15', '5', '1', 'and that he appeared to Cephas, then to the twelve,'),
('LEB', '1 Corinthians', '15', '6', '1', 'then he appeared to more than five hundred brothers at once, the majority of whom remain until now, but some have fallen asleep.'),
('LEB', '1 Corinthians', '15', '7', '1', 'Then he appeared to James, then to all the apostles,'),
('LEB', '1 Corinthians', '15', '8', '1', 'and last of all, as it were to one born at the wrong time, he appeared also to me.'),
('LEB', '1 Corinthians', '15', '9', '1', 'For I am the least of the apostles, not worthy to be called an apostle, because I persecuted the church of God.'),
('LEB', '1 Corinthians', '15', '10', '1', 'But by the grace of God I am what I am, and his grace to me has not been in vain, but I labored even more than all of them, and not I, but the grace of God with me.'),
('LEB', '1 Corinthians', '15', '11', '1', 'Therefore whether I or those, in this way we preached, and in this way you believed.'),
('LEB', '1 Corinthians', '15', '12', '3', '<span class=\"verse-title\">Concerning the Resurrection of the Dead</span>Now if Christ is preached as raised up from the dead, how do some among you say that <span class=\"supplied\">there</span> is no resurrection of the dead?'),
('LEB', '1 Corinthians', '15', '13', '3', 'But if <span class=\"supplied\">there</span> is no resurrection of the dead, Christ has not been raised <span class=\"supplied\">either</span>.'),
('LEB', '1 Corinthians', '15', '14', '3', 'But if Christ has not been raised, then<span class=\"note\">Some manuscripts have “then both”</span>our preaching <span class=\"supplied\">is</span> in vain, and your faith <span class=\"supplied\">is</span> in vain.'),
('LEB', '1 Corinthians', '15', '15', '3', 'And also we are found <span class=\"supplied\">to be</span> false witnesses of God, because we testified against God that he raised Christ, whom he did not raise if after all, then, the dead are not raised.'),
('LEB', '1 Corinthians', '15', '16', '3', 'For if the dead are not raised, Christ has not been raised <span class=\"supplied\">either</span>.'),
('LEB', '1 Corinthians', '15', '17', '3', 'But if Christ has not been raised, your faith <span class=\"supplied\">is</span> empty; you are still in your sins.'),
('LEB', '1 Corinthians', '15', '18', '3', 'And as a further result, those who have fallen asleep in Christ have perished.'),
('LEB', '1 Corinthians', '15', '19', '3', 'If <span class=\"idiom\">we have put our hope</span><span class=\"note\">“we are having put our hope”</span>in Christ in this life only, we are of all people most pitiable.'),
('LEB', '1 Corinthians', '15', '20', '4', 'But now Christ has been raised from the dead, the first fruits of those who have fallen asleep.'),
('LEB', '1 Corinthians', '15', '21', '4', 'For since through a man <span class=\"supplied\">came</span> death, also through a man <span class=\"supplied\">came</span> the resurrection of the dead.'),
('LEB', '1 Corinthians', '15', '22', '4', 'For just as in Adam all die, so also in Christ all will be made alive.'),
('LEB', '1 Corinthians', '15', '23', '4', 'But each in his own group: Christ the first fruits, then those <span class=\"supplied\">who are</span> Christ’s at his coming,'),
('LEB', '1 Corinthians', '15', '24', '4', 'then the end, when he hands over the kingdom to the God and Father, when he has abolished all rule and all authority and power.'),
('LEB', '1 Corinthians', '15', '25', '4', 'For it is necessary for him to reign until he has put all his enemies under his feet.'),
('LEB', '1 Corinthians', '15', '26', '4', 'The last enemy to be abolished <span class=\"supplied\">is</span> death.'),
('LEB', '1 Corinthians', '15', '27', '4', 'For “he subjected all <span class=\"supplied\">things</span> under his feet.”<span class=\"note\">Ps 8:6</span>But when it says “all <span class=\"supplied\">things</span>” are subjected, <span class=\"supplied\">it is</span> clear that the one who subjected all <span class=\"supplied\">things</span> to him <span class=\"supplied\">is</span> not included.'),
('LEB', '1 Corinthians', '15', '28', '4', 'But whenever all <span class=\"supplied\">things</span> are subjected to him, then the Son himself will be subjected<span class=\"note\">Some manuscripts have “also will be subjected”</span>to the one who subjected all <span class=\"supplied\">things</span> to him, in order that God may be all in all.'),
('LEB', '1 Corinthians', '15', '29', '5', 'Otherwise, why do they do <span class=\"supplied\">it</span>, those who are being baptized on behalf of the dead? If the dead are not raised at all, why indeed are they being baptized on behalf of them?'),
('LEB', '1 Corinthians', '15', '30', '5', 'And why are we in danger every hour?'),
('LEB', '1 Corinthians', '15', '31', '5', 'I die every day—yes indeed, by my boasting in you,<span class=\"note\">Some manuscripts have “in you, brothers,”</span>which I have in Christ Jesus our Lord!'),
('LEB', '1 Corinthians', '15', '32', '5', 'If according to a human perspective I fought wild beasts at Ephesus, what benefit <span class=\"supplied\">is it</span> to me? If the dead are not raised, let us eat and drink, for tomorrow we die.<span class=\"note\">An allusion to Isa 22:13; 56:12</span>'),
('LEB', '1 Corinthians', '15', '33', '5', 'Do not be deceived! “Bad company corrupts good morals.”<span class=\"note\">the Greek poet Menander’s comedy <span class=\"italic\">Thais</span>, 218</span>'),
('LEB', '1 Corinthians', '15', '34', '5', 'Sober up correctly and <span class=\"idiom\">stop sinning</span><span class=\"note\">“do not sin”</span>, for some have no knowledge of God—I say <span class=\"supplied\">this</span> to your shame.'),
('LEB', '1 Corinthians', '15', '35', '7', '<span class=\"verse-title\">Questions Concerning the Resurrection Body</span>But someone will say, “How are the dead raised? And with what sort of body do they come?”'),
('LEB', '1 Corinthians', '15', '36', '7', 'Foolish person! What you sow does not come to life unless it dies.'),
('LEB', '1 Corinthians', '15', '37', '7', 'And what you sow <span class=\"supplied\">is</span> not the body which it will become, but you sow the bare seed, whether perhaps of wheat or of some of the rest.'),
('LEB', '1 Corinthians', '15', '38', '7', 'But God gives to it a body just as he wishes, and to each one of the seeds its own body.'),
('LEB', '1 Corinthians', '15', '39', '7', 'Not all flesh <span class=\"supplied\">is</span> the same, but <span class=\"supplied\">there is</span> one flesh of human beings, and another flesh of animals, and another flesh of birds, and another of fish,'),
('LEB', '1 Corinthians', '15', '40', '7', 'and heavenly bodies and earthly bodies. But the glory of the heavenly <span class=\"supplied\">bodies</span> <span class=\"supplied\">is</span> of one kind, and the <span class=\"supplied\">glory</span> of the earthly <span class=\"supplied\">bodies</span> <span class=\"supplied\">is</span> of another kind.'),
('LEB', '1 Corinthians', '15', '41', '7', '<span class=\"supplied\">There is</span> one glory of the sun, and another glory of the moon, and another glory of the stars, for star differs from star in glory.'),
('LEB', '1 Corinthians', '15', '42', '8', 'Thus also <span class=\"supplied\">is</span> the resurrection of the dead. It is sown in corruption, it is raised in incorruptibility.'),
('LEB', '1 Corinthians', '15', '43', '8', 'It is sown in dishonor, it is raised in glory. It is sown in weakness, it is raised in power.'),
('LEB', '1 Corinthians', '15', '44', '8', 'It is sown a natural body, it is raised a spiritual body. If <span class=\"supplied\">there</span> is a natural body, <span class=\"supplied\">there</span> is also a spiritual <span class=\"supplied\">body</span>.'),
('LEB', '1 Corinthians', '15', '45', '8', 'Thus also it is written, “The first man, Adam, became a living soul”;<span class=\"note\">Gen 2:7</span>the last Adam <span class=\"supplied\">became</span> a life-giving spirit.'),
('LEB', '1 Corinthians', '15', '46', '8', 'But the spiritual <span class=\"supplied\">is</span> not first, but the natural; then the spiritual.'),
('LEB', '1 Corinthians', '15', '47', '8', 'The first man <span class=\"supplied\">is</span> from the earth, made of earth; the second man <span class=\"supplied\">is</span> from heaven.'),
('LEB', '1 Corinthians', '15', '48', '8', 'As the one <span class=\"supplied\">who is</span> made of earth, so also <span class=\"supplied\">are</span> those <span class=\"supplied\">who are</span> made of earth, and as the heavenly, so also <span class=\"supplied\">are</span> those <span class=\"supplied\">who are</span> heavenly.'),
('LEB', '1 Corinthians', '15', '49', '8', 'And just as we have borne the image of the <span class=\"supplied\">one who is</span> made of earth, we will also bear the image of the heavenly.'),
('LEB', '1 Corinthians', '15', '50', '9', 'But I say this, brothers, that flesh and blood is not able to inherit the kingdom of God, nor can corruption inherit incorruptibility.'),
('LEB', '1 Corinthians', '15', '51', '9', 'Behold, I tell you a mystery: we will not all fall asleep, but we will all be changed,'),
('LEB', '1 Corinthians', '15', '52', '9', 'in a moment, in the blink of an eye, at the last trumpet. For the trumpet will sound, and the dead will be raised imperishable, and we will be changed.'),
('LEB', '1 Corinthians', '15', '53', '9', 'For it is necessary <span class=\"supplied\">for</span> this perishable <span class=\"supplied\">body</span> to put on incorruptibility, and this mortal <span class=\"supplied\">body</span> to put on immortality.'),
('LEB', '1 Corinthians', '15', '54', '9', 'But whenever this perishable <span class=\"supplied\">body</span> puts on incorruptibility and this mortal <span class=\"supplied\">body</span> puts on immortality, then the saying that is written will take place:'),
('LEB', '1 Corinthians', '15', '55', '10', '“Death is swallowed up in victory.'),
('LEB', '1 Corinthians', '15', '56', '11', 'Now the sting of death <span class=\"supplied\">is</span> sin, and the power of sin <span class=\"supplied\">is</span> the law.'),
('LEB', '1 Corinthians', '15', '57', '11', 'But thanks <span class=\"supplied\">be</span> to God, who gives us the victory through our Lord Jesus Christ!'),
('LEB', '1 Corinthians', '15', '58', '11', 'So then, my dear brothers, be steadfast, immovable, always abounding in the work of the Lord, <span class=\"supplied\">because you</span>know that your labor is not <span class=\"supplied\">in</span> vain in the Lord.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Corinthians', '16', '1', '1', '<span class=\"verse-title\">Concerning the Collection for the Saints</span>Now concerning the collection for the saints: just as I gave directions about <span class=\"supplied\">it</span> to the churches of Galatia, so you do also.'),
('LEB', '1 Corinthians', '16', '2', '1', 'On the first <span class=\"supplied\">day</span> of the week, each one of you <span class=\"idiom\">put aside</span><span class=\"note\">“put from himself”</span><span class=\"supplied\">something</span>, saving up <span class=\"idiom\">to whatever extent he has prospered</span><span class=\"note\">“whatever if anything he has been prospered”</span>, in order that whenever I come, at that time collections do not take place.'),
('LEB', '1 Corinthians', '16', '3', '1', 'And whenever I arrive, whomever you approve by letters, I will send these to take your gift to Jerusalem.'),
('LEB', '1 Corinthians', '16', '4', '1', 'And if it is worthwhile for me to go also, they will travel with me.'),
('LEB', '1 Corinthians', '16', '5', '3', '<span class=\"verse-title\">Travel Plans for Paul and Associates</span>But I will come to you whenever I go through Macedonia (for I am going through Macedonia),'),
('LEB', '1 Corinthians', '16', '6', '3', 'and perhaps I will stay with you, or even spend the winter, so that you may send me on my way wherever I may go.'),
('LEB', '1 Corinthians', '16', '7', '3', 'For I do not want to see you now in passing, for I hope to remain some time with you, if the Lord allows <span class=\"supplied\">it</span>.'),
('LEB', '1 Corinthians', '16', '8', '3', 'But I will remain in Ephesus until Pentecost,'),
('LEB', '1 Corinthians', '16', '9', '3', 'for a great and effective door has opened for me, and <span class=\"supplied\">there are</span> many opponents.'),
('LEB', '1 Corinthians', '16', '10', '4', 'But if Timothy comes, see that he is with you without cause to fear, for he is carrying out the Lord’s work, as I also <span class=\"supplied\">am</span>.'),
('LEB', '1 Corinthians', '16', '11', '4', 'Therefore do not let anyone disdain him, but send him <span class=\"supplied\">on his way</span> in peace in order that he may come to me, for I am expecting him with the brothers.'),
('LEB', '1 Corinthians', '16', '12', '5', 'Now concerning Apollos our brother, I urged him many <span class=\"supplied\">times</span> that he should come to you with the brothers, and he was not at all willing that he should come now, but he will come whenever he has <span class=\"supplied\">an</span> opportunity.'),
('LEB', '1 Corinthians', '16', '13', '7', '<span class=\"verse-title\">Concluding Exhortations</span>Be on the alert, stand firm in the faith, act courageously, be strong.'),
('LEB', '1 Corinthians', '16', '14', '7', 'All your <span class=\"supplied\">actions</span> must be done in love.'),
('LEB', '1 Corinthians', '16', '15', '8', 'Now I urge you, brothers—you know about the household of Stephanas, that they are the first fruits of Achaia, and they have devoted themselves to the ministry for the saints—'),
('LEB', '1 Corinthians', '16', '16', '8', 'that you also be subject to such people, and to all those who work together and labor.'),
('LEB', '1 Corinthians', '16', '17', '8', 'Now I rejoice over the arrival of Stephanas and Fortunatus and Achaicus, because these make up for your absence,'),
('LEB', '1 Corinthians', '16', '18', '8', 'for they have refreshed my spirit and yours. Therefore recognize such people.'),
('LEB', '1 Corinthians', '16', '19', '10', '<span class=\"verse-title\">Final Greetings and Benediction</span>The churches of <span class=\"supplied\">the province of</span> Asia<span class=\"note\">That is, the Roman province of Asia, known today as Asia Minor</span>greet you. Aquila and Prisca greet you in the Lord many <span class=\"supplied\">times</span>, together with the church in their house.'),
('LEB', '1 Corinthians', '16', '20', '10', 'All the brothers greet you. Greet one another with a holy kiss.'),
('LEB', '1 Corinthians', '16', '21', '11', 'The greeting <span class=\"supplied\">is</span> by my hand—Paul’s.'),
('LEB', '1 Corinthians', '16', '22', '11', 'If anyone does not love the Lord, let him be accursed. O Lord, come!<span class=\"note\">The Aramaic expression <span class=\"italic\">marana tha</span> (“O Lord, come!”) can also be rendered <span class=\"italic\">maran atha</span> (“our Lord has come”); it is used here by Paul without explanation</span>'),
('LEB', '1 Corinthians', '16', '23', '12', 'The grace of the Lord Jesus <span class=\"supplied\">be</span> with you.'),
('LEB', '1 Corinthians', '16', '24', '12', 'My love <span class=\"supplied\">be</span> with all of you in Christ Jesus.')
;

