INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 John', '1', '1', '1', '<span class=\"verse-title\">Prologue</span>What was from the beginning, what we have heard, what we have seen with our eyes, what we have looked at and our hands have touched, concerning the word of life—'),
('LEB', '1 John', '1', '2', '1', 'and the life was revealed, and we have seen and testify and announce to you the eternal life which was with the Father and was revealed to us—'),
('LEB', '1 John', '1', '3', '1', 'what we have seen and heard, we announce to you also, in order that you also may have fellowship with us, and indeed our fellowship <span class=\"supplied\">is</span> with the Father and with his Son Jesus Christ.'),
('LEB', '1 John', '1', '4', '1', 'And these <span class=\"supplied\">things</span> we write, in order that our joy may be complete.'),
('LEB', '1 John', '1', '5', '3', '<span class=\"verse-title\">God is Light, so Walk in the Light</span>And this is the message which we have heard from him and announce to you, that God is light and there <span class=\"supplied\">is</span> no darkness in him at all.'),
('LEB', '1 John', '1', '6', '3', 'If we say that we have fellowship with him and walk in the darkness, we lie and do not practice the truth.<span class=\"note\">Or “we are lying and are not practicing the truth”</span>'),
('LEB', '1 John', '1', '7', '3', 'But if we walk in the light as he is in the light, we have fellowship with one another, and the blood of Jesus his Son cleanses us from all sin.'),
('LEB', '1 John', '1', '8', '3', 'If we say that we do not have sin, we deceive ourselves and the truth is not in us.'),
('LEB', '1 John', '1', '9', '3', 'If we confess our sins, he is faithful and just, so that he will forgive us <span class=\"supplied\">our</span>sins and will cleanse us from all unrighteousness.'),
('LEB', '1 John', '1', '10', '3', 'If we say that we have not sinned, we make him a liar, and his word is not in us.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 John', '2', '1', '1', '<span class=\"verse-title\">Keeping the New Commandment</span>My little children, I am writing these <span class=\"supplied\">things</span> to you in order that you may not sin. And if anyone sins, we have an advocate with the Father, Jesus Christ the righteous <span class=\"supplied\">one</span>,'),
('LEB', '1 John', '2', '2', '1', 'and he<span class=\"note\">Or “he himself” (emphatic)</span>is the propitiation<span class=\"note\">Or “expiation”; or “atoning sacrifice”</span>for our sins, and not for ours only, but also for <span class=\"supplied\">the sins of</span> the whole world.'),
('LEB', '1 John', '2', '3', '1', 'And by this we know that we have come to know him, if we keep his commandments.'),
('LEB', '1 John', '2', '4', '1', 'The one who says “I have come to know him,” and does not keep his commandments is a liar, and the truth is not in this person.'),
('LEB', '1 John', '2', '5', '1', 'But whoever keeps his word, truly in this person the love of God has been perfected. By this we know that we are in him.'),
('LEB', '1 John', '2', '6', '1', 'The one who says <span class=\"supplied\">that he</span> resides in him ought also to walk<span class=\"note\">Some manuscripts have “to walk in this way”</span>just as that one walked.'),
('LEB', '1 John', '2', '7', '2', 'Dear friends, I am not writing a new commandment to you, but an old commandment which you have had from the beginning. The old commandment is the message which you have heard.'),
('LEB', '1 John', '2', '8', '2', 'Again, I am writing a new commandment to you, which is true in him and in you, because<span class=\"note\">Or perhaps “that”</span>the darkness is passing away and the true light already is shining.'),
('LEB', '1 John', '2', '9', '2', 'The one who says <span class=\"supplied\">he</span> is in the light and hates his brother is in the darkness until now.'),
('LEB', '1 John', '2', '10', '2', 'The one who loves his brother resides in the light, and <span class=\"supplied\">there</span> is no cause for stumbling in him.'),
('LEB', '1 John', '2', '11', '2', 'But the one who hates his brother is in the darkness, and walks in the darkness, and does not know where he is going, because the darkness has blinded his eyes.'),
('LEB', '1 John', '2', '12', '4', '<span class=\"verse-title\">Encouragement and Assurance</span>I am writing to you, little children, because<span class=\"note\">Or “that”</span>your sins have been forgiven you on account of his name.'),
('LEB', '1 John', '2', '13', '4', 'I am writing to you, fathers, because<span class=\"note\">Or “that”</span>you have known the <span class=\"supplied\">One who is</span> from the beginning. I am writing to you, young men, because<span class=\"note\">Or “that”</span>you have conquered the evil one.'),
('LEB', '1 John', '2', '14', '4', 'I have written to you, children, because<span class=\"note\">Or “that”</span>you have known the Father. I have written to you, fathers, because<span class=\"note\">Or “that”</span>you have known the <span class=\"supplied\">One who is</span> from the beginning. I have written to you, young men, because<span class=\"note\">Or “that”</span>you are strong, and the word of God resides in you, and you have conquered the evil one.'),
('LEB', '1 John', '2', '15', '6', '<span class=\"verse-title\">Do Not Love the World</span>Do not love the world or the things in the world. If anyone loves the world, the love of the Father is not in him,'),
('LEB', '1 John', '2', '16', '6', 'because everything <span class=\"supplied\">that is</span> in the world—the desire of the flesh and the desire of the eyes and the arrogance of material possessions—is not from the Father, but is from the world.'),
('LEB', '1 John', '2', '17', '6', 'And the world is passing away, and its desire,<span class=\"note\">Or “and the desire for it”</span>but the one who does the will of God remains <span class=\"idiom\">forever</span><span class=\"note\">Literally “for the age”</span>.'),
('LEB', '1 John', '2', '18', '8', '<span class=\"verse-title\">Departure of the False Teachers</span>Children, it is the last hour, and just as you have heard that antichrist is coming, even now many antichrists have arisen, by which we know that it is the last hour.'),
('LEB', '1 John', '2', '19', '8', 'They went out from us, but they were not of us; for if they had been of us, they would have remained with us. But <span class=\"supplied\">they went out</span>, in order that it might be shown that all of them are not of us.'),
('LEB', '1 John', '2', '20', '9', 'And you have an anointing from the Holy One, and you all know.'),
('LEB', '1 John', '2', '21', '9', 'I have not written to you because<span class=\"note\">Or “that”</span>you do not know the truth, but because<span class=\"note\">Or “that”</span>you do know it, and because<span class=\"note\">Or “that”</span>every lie is not of the truth.'),
('LEB', '1 John', '2', '22', '9', 'Who is the liar except the one who denies that Jesus is the Christ? This person is the antichrist, the one who denies the Father and the Son.'),
('LEB', '1 John', '2', '23', '9', 'Everyone who denies the Son does not have the Father <span class=\"supplied\">either</span>; the one who confesses the Son has the Father also.'),
('LEB', '1 John', '2', '24', '10', '<span class=\"supplied\">As for</span> you, what you have heard from the beginning must remain in you. If what you have heard from the beginning remains in you, you also will remain in the Son and in the Father.'),
('LEB', '1 John', '2', '25', '10', 'And this is the promise which he himself promised us: eternal life.'),
('LEB', '1 John', '2', '26', '10', 'These <span class=\"supplied\">things</span> I have written to you concerning the ones who are trying to deceive you.'),
('LEB', '1 John', '2', '27', '11', 'And <span class=\"supplied\">as for</span> you, the anointing which you received from him remains in you, and you do not have need that anyone teach you. But as his anointing teaches you about all <span class=\"supplied\">things</span>, and is true and is not a lie, and just as it has taught you, you residein him.'),
('LEB', '1 John', '2', '28', '13', '<span class=\"verse-title\">God’s Children</span>And now, little children, remain in him, so that whenever he is revealed we may have confidence and not be put to shame before him at his coming.'),
('LEB', '1 John', '2', '29', '13', 'If you know that he is righteous, you know that everyone<span class=\"note\">Some manuscripts have “everyone also”</span>who practices righteousness has been fathered by him.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 John', '3', '1', '0', 'See what sort of love the Father has given to us: that we should be called children of God, and we are! Because of this the world does not know us: because it did not know him.'),
('LEB', '1 John', '3', '2', '0', 'Dear friends, now we are children of God, and what we will be has not yet been revealed. We know that whenever he is revealed we will be like him, because we will see him just as he is.'),
('LEB', '1 John', '3', '3', '0', 'And everyone who has this hope in him purifies himself, just as that one is pure.'),
('LEB', '1 John', '3', '4', '1', 'Everyone who practices sin also practices lawlessness, and sin is lawlessness.'),
('LEB', '1 John', '3', '5', '1', 'And you know that that one was revealed in order that he might take away sins, and in him <span class=\"supplied\">there</span> is no sin.'),
('LEB', '1 John', '3', '6', '1', 'Everyone who resides in him does not sin. Everyone who sins has neither seen him nor known him.'),
('LEB', '1 John', '3', '7', '1', 'Little children, let no one deceive you: the one who practices righteousness is righteous, just as that one is righteous.'),
('LEB', '1 John', '3', '8', '1', 'The one who practices sin is of the devil, because the devil has been sinning from the beginning. For this <span class=\"supplied\">reason</span> the Son of God was revealed: in order to destroy the works of the devil.'),
('LEB', '1 John', '3', '9', '1', 'Everyone who is fathered by God does not practice sin, because his seed resides in him, and <span class=\"supplied\">he is</span> not able to sin, because he has been fathered by God.'),
('LEB', '1 John', '3', '10', '1', 'By this the children of God and the children of the devil are evident: everyone who does not practice righteousness is not of God, namely, the one who does not love his brother.'),
('LEB', '1 John', '3', '11', '3', '<span class=\"verse-title\">God is Love, so Love One Another</span>For this is the message that you have heard from the beginning: that we should love one another,'),
('LEB', '1 John', '3', '12', '3', 'not as Cain, who was of the evil one and violently murdered his brother. And <span class=\"idiom\">for what reason</span><span class=\"note\">Literally “on account of what”</span>did he violently murder him? Because his deeds were evil and the <span class=\"supplied\">deeds</span> of his brother <span class=\"supplied\">were</span> righteous.'),
('LEB', '1 John', '3', '13', '4', 'Do not marvel,<span class=\"note\">Some manuscripts have “And do not marvel”</span>brothers, if the world hates you.'),
('LEB', '1 John', '3', '14', '4', 'We know that we have passed over from death to life because we love the brothers. The one who does not love remains in death.'),
('LEB', '1 John', '3', '15', '4', 'Everyone who hates his brother is a murderer, and you know that every murderer does not have eternal life residing in him.'),
('LEB', '1 John', '3', '16', '4', 'We have come to know love by this: that <span class=\"idiom\">he</span><span class=\"note\">Literally “that one” (referring to Jesus Christ)</span>laid down his life on behalf of us, and we ought to lay down our lives on behalf of the brothers.'),
('LEB', '1 John', '3', '17', '4', 'But whoever has the world’s material possessions and observes his brother <span class=\"idiom\">in need</span><span class=\"note\">Literally “having need”</span>and shuts his heart against him, how does the love of God reside in him?'),
('LEB', '1 John', '3', '18', '5', 'Little children, let us not love with word or with tongue, but in deed and truth.'),
('LEB', '1 John', '3', '19', '5', 'By this<span class=\"note\">Some manuscripts have “And by this”</span>we know that we are of the truth and will convince our heart before him,'),
('LEB', '1 John', '3', '20', '5', 'that<span class=\"note\">Or “because”</span>if our heart condemns us, that God is greater than our heart and knows all <span class=\"supplied\">things</span>.'),
('LEB', '1 John', '3', '21', '5', 'Dear friends, if our heart does not condemn <span class=\"supplied\">us</span>, we have confidence before God,'),
('LEB', '1 John', '3', '22', '5', 'and whatever we ask we receive from him, because we keep his commandments and do <span class=\"supplied\">what is</span> pleasing <span class=\"idiom\">in his sight</span><span class=\"note\">Literally “in the sight of him”</span>.'),
('LEB', '1 John', '3', '23', '5', 'And this is his commandment: that we believe in the name of his Son Jesus Christ and love one another, just as <span class=\"idiom\">he commanded us</span><span class=\"note\">Literally “he gave us commandment”</span>.'),
('LEB', '1 John', '3', '24', '5', 'And the one who keeps his commandments resides in him, and he in him. And by this we know that he resides in us: by the Spirit whom he has given to us.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 John', '4', '1', '1', '<span class=\"verse-title\">How to Recognize the Spirit of God</span>Dear friends, do not believe every spirit, but test the spirits <span class=\"supplied\">to determine</span> if they are from God, because many false prophets have gone out into the world.'),
('LEB', '1 John', '4', '2', '1', 'By this you know the Spirit of God: every spirit that confesses Jesus Christ<span class=\"note\">Or “confesses Jesus <span class=\"supplied\">as</span> Christ who has come in the flesh” (see also 2 John 7)</span>has come in the flesh is from God,'),
('LEB', '1 John', '4', '3', '1', 'and every spirit that does not confess Jesus is not from God, and this is the <span class=\"supplied\">spirit</span> of the antichrist, <span class=\"supplied\">of</span> which you have heard that it is coming, and now it is already in the world.'),
('LEB', '1 John', '4', '4', '2', 'You are from God, little children, and have conquered them, because the one <span class=\"supplied\">who is</span> in you is greater than the one <span class=\"supplied\">who is</span> in the world.'),
('LEB', '1 John', '4', '5', '2', 'They are from the world; <span class=\"idiom\">therefore</span><span class=\"note\">Literally “because of this”</span>they speak from the world and the world listens to them.'),
('LEB', '1 John', '4', '6', '2', 'We are from God. The one who knows God listens to us; whoever is not from God does not listen to us. By this we know the Spirit of truth and the spirit of deceit.'),
('LEB', '1 John', '4', '7', '4', '<span class=\"verse-title\">God’s Love Revealed</span>Dear friends, let us love one another, because love is from God, and everyone who loves has been fathered by God and knows God.'),
('LEB', '1 John', '4', '8', '4', 'The one who does not love does not know God, because God is love.'),
('LEB', '1 John', '4', '9', '4', 'By this the love of God is revealed in us: that God sent his one and only Son into the world in order that we may live through him.'),
('LEB', '1 John', '4', '10', '4', 'In this is love: not that we have loved God, but that he loved us and sent his Son <span class=\"supplied\">to be the</span> propitiation<span class=\"note\">Or “expiation”; or “atoning sacrifice”</span>for our sins.'),
('LEB', '1 John', '4', '11', '5', 'Dear friends, if God loved us in this way, we also ought to love one another.'),
('LEB', '1 John', '4', '12', '5', 'No one has seen God at any time. If we love one another, God resides in us and his love is perfected in us.'),
('LEB', '1 John', '4', '13', '5', 'By this we know that we reside in him and he in us: that<span class=\"note\">Or “because”</span>he has given us of his Spirit.'),
('LEB', '1 John', '4', '14', '5', 'And we have seen and testify that the Father has sent the Son <span class=\"supplied\">to be the</span> Savior of the world.'),
('LEB', '1 John', '4', '15', '6', 'Whoever confesses that Jesus is the Son of God, God resides in him and he in God.'),
('LEB', '1 John', '4', '16', '6', 'And we have come to know and have believed the love that God has in us. God is love, and the one who resides in love resides in God, and God resides in him.'),
('LEB', '1 John', '4', '17', '6', 'By this love is perfected with us, so that we may have confidence in the day of judgment, because just as that one is, <span class=\"supplied\">so</span> also are we in this world.'),
('LEB', '1 John', '4', '18', '6', '<span class=\"supplied\">There</span> is no fear in love, but perfect love drives out fear, because fear includes punishment, and the one who is afraid has not been perfected in love.'),
('LEB', '1 John', '4', '19', '6', 'We love, because he first loved us.'),
('LEB', '1 John', '4', '20', '7', 'If anyone says, “I love God,” and hates his brother, he is a liar, for the one who does not love his brother whom he has seen is not able to love God whom he has not seen.'),
('LEB', '1 John', '4', '21', '7', 'And this <span class=\"supplied\">is</span> the commandment we have from him: that the one who loves God should love his brother also.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 John', '5', '1', '0', 'Everyone who believes that Jesus is the Christ has been fathered by God, and everyone who loves <span class=\"idiom\">the father</span><span class=\"note\">Literally “the one who fathers”</span>also loves the <span class=\"supplied\">child</span> fathered by him.'),
('LEB', '1 John', '5', '2', '0', 'By this we know that we love the children of God: whenever we love God and keep his commandments.'),
('LEB', '1 John', '5', '3', '0', 'For this is the love of God: that we keep his commandments. And his commandments are not burdensome,'),
('LEB', '1 John', '5', '4', '0', 'because everyone who is fathered by God conquers the world.'),
('LEB', '1 John', '5', '5', '2', '<span class=\"verse-title\">God Has Given Us Eternal Life in the Son</span>And this is the victory which has conquered the world: our faith.'),
('LEB', '1 John', '5', '6', '2', 'Now who is the one who conquers the world except the one who believes that Jesus is the Son of God?'),
('LEB', '1 John', '5', '7', '2', 'This is the one who came by water and blood—Jesus Christ, not with the water only, but with the water and with the blood. And the Spirit is the one who testifies, because the Spirit is the truth.'),
('LEB', '1 John', '5', '8', '2', 'For <span class=\"supplied\">there</span> are three that testify,<span class=\"note\">Later Latin manuscripts add the following words to v. 7 and v. 8: “in heaven, the Father, the Word, and the Holy Spirit, and these three are one. <span class=\"bold\">8</span> And there are three that testify on earth”</span>'),
('LEB', '1 John', '5', '9', '3', 'If we receive the testimony of people, the testimony of God is greater, because this is the testimony of God that he has testified concerning his Son.'),
('LEB', '1 John', '5', '10', '3', '(The one who believes in the Son of God has the testimony in himself. The one who does not believe God has made him a liar, because he has not believed in the testimony that God has testified concerning his Son.)'),
('LEB', '1 John', '5', '11', '3', 'And this is the testimony: that God has given us eternal life, and this life is in his Son.'),
('LEB', '1 John', '5', '12', '3', 'The one who has the Son has the life; the one who does not have the Son of God does not have the life.'),
('LEB', '1 John', '5', '13', '5', '<span class=\"verse-title\">Our Assurance of Eternal Life</span>These <span class=\"supplied\">things</span> I have written to you who believe in the name of the Son of God, in order that you may know that you have eternal life.'),
('LEB', '1 John', '5', '14', '6', 'And this is the confidence that we have before him: that if we ask anything according to his will, he hears us.'),
('LEB', '1 John', '5', '15', '6', 'And if we know that he hears us <span class=\"supplied\">in</span> whatever we ask, we know that we have the requests that we have asked from him.'),
('LEB', '1 John', '5', '16', '6', 'If anyone should see his brother sinning a sin not <span class=\"supplied\">leading</span> to death, he should ask, and he will grant life to him, to those who sin not <span class=\"supplied\">leading</span> to death. (<span class=\"supplied\">There</span> is a sin <span class=\"supplied\">leading</span> to death; I do not say that he should ask about that.'),
('LEB', '1 John', '5', '17', '6', 'All unrighteousness is sin, and <span class=\"supplied\">there</span> is a sin not <span class=\"supplied\">leading</span> to death.)'),
('LEB', '1 John', '5', '18', '7', 'We know that everyone who is fathered by God does not sin, but the one fathered by God, he protects him, and the evil one does not touch him.'),
('LEB', '1 John', '5', '19', '7', 'We know that we are from God, and the whole world lies in <span class=\"supplied\">the power of</span> the evil one.'),
('LEB', '1 John', '5', '20', '7', 'And we know that the Son of God has come and has given us understanding, in order that we may know the one who is true, and we are in the one who is true, in his Son Jesus Christ. This one is the true God and eternal life.'),
('LEB', '1 John', '5', '21', '7', 'Little children, guard yourselves from idols.')
;

