INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Timothy', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, an apostle of Christ Jesus according to the command of God our Savior and of Christ Jesus our hope,'),
('LEB', '1 Timothy', '1', '2', '1', 'to Timothy, <span class=\"supplied\">my</span> true child in the faith. Grace, mercy, <span class=\"supplied\">and</span> peace from God the Father and Christ Jesus our Lord.'),
('LEB', '1 Timothy', '1', '3', '3', '<span class=\"verse-title\">Instructions for Timothy in Ephesus</span>Just as I urged you <span class=\"supplied\">when I</span>traveled to Macedonia, remain in Ephesus, so that you may instruct certain people not to teach other doctrine,'),
('LEB', '1 Timothy', '1', '4', '3', 'and not to pay attention to myths and endless genealogies, which cause useless speculations rather than God’s plan <span class=\"supplied\">that is</span> by faith.'),
('LEB', '1 Timothy', '1', '5', '3', 'But the goal of our instruction is love from a pure heart and a good conscience and a faith without hypocrisy,'),
('LEB', '1 Timothy', '1', '6', '3', 'from which some have deviated, <span class=\"supplied\">and</span> have turned away into fruitless discussion,'),
('LEB', '1 Timothy', '1', '7', '3', 'wanting to be teachers of the law, <span class=\"supplied\">although they</span>do not understand either <span class=\"supplied\">the things</span> which they are saying or <span class=\"supplied\">the things</span> concerning which they are speaking confidently.'),
('LEB', '1 Timothy', '1', '8', '4', 'But we know that the law <span class=\"supplied\">is</span> good, if anyone makes use of it lawfully,'),
('LEB', '1 Timothy', '1', '9', '4', 'knowing this, that the law <span class=\"supplied\">is</span> not given for a righteous <span class=\"supplied\">person</span> but for the lawless and rebellious, for the ungodly and sinners, for the unholy and totally worldly, for the one who kills his father and the one who kills his mother, for murderers,'),
('LEB', '1 Timothy', '1', '10', '4', 'sexually immoral people, homosexuals, kidnappers, liars, perjurers, and <span class=\"idiom\">whatever</span><span class=\"note\">Literally “if anything”</span>else is opposed to sound teaching,'),
('LEB', '1 Timothy', '1', '11', '4', 'according to the glorious gospel of the blessed God that I was entrusted with.'),
('LEB', '1 Timothy', '1', '12', '6', '<span class=\"verse-title\">Paul’s Thankfulness for the Mercy Shown to Him</span><span class=\"idiom\">I give thanks</span><span class=\"note\">Literally “I have thankfulness”</span>to the one who strengthens me, Christ Jesus our Lord, because he considered me faithful, placing <span class=\"supplied\">me</span> into ministry,<span class=\"note\">Or “service”</span>'),
('LEB', '1 Timothy', '1', '13', '6', '<span class=\"supplied\">although I</span>was formerly a blasphemer and a persecutor and a violent man, but I was shown mercy because I acted ignorantly in unbelief,'),
('LEB', '1 Timothy', '1', '14', '6', 'and the grace of our Lord abounded with the faith and love <span class=\"supplied\">that are</span> in Christ Jesus.'),
('LEB', '1 Timothy', '1', '15', '6', 'The saying <span class=\"supplied\">is</span> trustworthy and worthy of all acceptance: Christ Jesus came into the world to save sinners, of whom I am the foremost.'),
('LEB', '1 Timothy', '1', '16', '6', 'But because of this I was shown mercy, in order that in me foremost, Christ Jesus might demonstrate his total patience, for an example for those who are going to believe in him for eternal life.'),
('LEB', '1 Timothy', '1', '17', '6', 'Now to the King of the ages, immortal, invisible, to the only God, <span class=\"supplied\">be</span> honor and glory <span class=\"idiom\">forever and ever</span><span class=\"note\">Literally “to the ages of the ages”</span>. Amen.'),
('LEB', '1 Timothy', '1', '18', '8', '<span class=\"verse-title\">Paul’s Charge to Timothy</span>I am setting before you this instruction, Timothy <span class=\"supplied\">my</span> child, in accordance with the prophecies spoken long ago about you, in order that by them you may fight the good fight,'),
('LEB', '1 Timothy', '1', '19', '8', 'having faith and a good conscience, which some, <span class=\"supplied\">because they</span>have rejected <span class=\"supplied\">these</span>, have suffered shipwreck concerning their faith,'),
('LEB', '1 Timothy', '1', '20', '8', 'among whom are Hymenaeus and Alexander, whom I have handed over to Satan, in order that they may be taught not to blaspheme.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Timothy', '2', '1', '1', '<span class=\"verse-title\">Instructions to Pray for All People</span>Therefore, I urge first of all <span class=\"supplied\">that</span> petitions, prayers, requests, <span class=\"supplied\">and</span> thanksgiving be made on behalf of all people,'),
('LEB', '1 Timothy', '2', '2', '1', 'on behalf of kings and all those who are in authority, in order that we may live a tranquil and quiet life in all godliness and dignity.'),
('LEB', '1 Timothy', '2', '3', '1', 'This <span class=\"supplied\">is</span> good and acceptable before God our Savior,'),
('LEB', '1 Timothy', '2', '4', '1', 'who wants all people to be saved and to come to a knowledge of the truth.'),
('LEB', '1 Timothy', '2', '5', '1', 'For <span class=\"supplied\">there is</span> one God and one mediator between God and human beings, the man Christ Jesus,'),
('LEB', '1 Timothy', '2', '6', '1', 'who gave himself a ransom for all, the testimony at the proper time,'),
('LEB', '1 Timothy', '2', '7', '1', 'for which I was appointed a herald and an apostle—I am speaking the truth, <span class=\"supplied\">I am</span> not lying—a teacher of the Gentiles in faith and truth.'),
('LEB', '1 Timothy', '2', '8', '1', 'Therefore I want the men in every place to pray, lifting up holy hands without anger and dispute.'),
('LEB', '1 Timothy', '2', '9', '3', '<span class=\"verse-title\">Instructions for Women</span>Likewise also the women should adorn themselves in appropriate clothing, with modesty and self-control, not with braided hair and gold jewelry or pearls or expensive clothing,'),
('LEB', '1 Timothy', '2', '10', '3', 'but with good deeds which are fitting for women who profess godliness.'),
('LEB', '1 Timothy', '2', '11', '3', 'A woman must learn in quietness with all submission.'),
('LEB', '1 Timothy', '2', '12', '3', 'But I do not permit a woman to teach or to exercise authority over a man, but <span class=\"idiom\">to remain quiet</span><span class=\"note\">Literally “to be in quietness”</span>.'),
('LEB', '1 Timothy', '2', '13', '3', 'For Adam was formed first, then Eve,'),
('LEB', '1 Timothy', '2', '14', '3', 'and Adam was not deceived, but the woman, <span class=\"supplied\">because she</span>was deceived, came into transgression.'),
('LEB', '1 Timothy', '2', '15', '3', 'But she will be saved through the bearing of children, if she continues in faith and love and holiness with self-control.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Timothy', '3', '1', '1', '<span class=\"verse-title\">Qualifications for Overseers</span>The saying <span class=\"supplied\">is</span> trustworthy: if anyone aspires to supervision, he desires a good work.'),
('LEB', '1 Timothy', '3', '2', '1', 'Therefore the overseer must be irreproachable, the husband of one wife, temperate, self-controlled, respectable, hospitable, skillful in teaching,'),
('LEB', '1 Timothy', '3', '3', '1', 'not addicted to wine, not a violent person, but gentle, peaceable, not loving money,'),
('LEB', '1 Timothy', '3', '4', '1', 'managing his own household well, having children in submission with all dignity'),
('LEB', '1 Timothy', '3', '5', '1', '(but if someone does not know how to manage his own household, how will he take care of the church of God?),'),
('LEB', '1 Timothy', '3', '6', '1', 'not newly converted, lest he become conceited <span class=\"supplied\">and</span> fall into the condemnation of the devil.'),
('LEB', '1 Timothy', '3', '7', '1', 'But <span class=\"supplied\">he</span> must also have a good testimony from those outside, in order that he may not fall into disgrace and the trap of the devil.'),
('LEB', '1 Timothy', '3', '8', '3', '<span class=\"verse-title\">Qualifications for Deacons</span>Deacons likewise <span class=\"supplied\">must be</span> dignified, not insincere, not devoted to much wine, not fond of dishonest gain,'),
('LEB', '1 Timothy', '3', '9', '3', 'holding the mystery of the faith with a clear conscience,'),
('LEB', '1 Timothy', '3', '10', '3', 'and these also must be tested first; then let them serve <span class=\"supplied\">if they</span>are above reproach.'),
('LEB', '1 Timothy', '3', '11', '3', 'The wives<span class=\"note\">Or “The women”</span>likewise <span class=\"supplied\">must be</span> dignified, not slanderous, temperate, faithful in all <span class=\"supplied\">things</span>.'),
('LEB', '1 Timothy', '3', '12', '3', 'Deacons must be husbands of one wife, managing <span class=\"supplied\">their</span> children and their own households well.'),
('LEB', '1 Timothy', '3', '13', '3', 'For those who have served well acquire a good standing for themselves, and great boldness in the faith <span class=\"supplied\">that is</span> in Christ Jesus.'),
('LEB', '1 Timothy', '3', '14', '5', '<span class=\"verse-title\">The Mystery of Godliness Described</span>I am writing these <span class=\"supplied\">things</span> to you, hoping to come to you in a short time.'),
('LEB', '1 Timothy', '3', '15', '5', 'But if I am delayed, <span class=\"supplied\">I am writing</span>in order that you may know how one must conduct oneself in the household of God, which is the church of the living God, the pillar and mainstay<span class=\"note\">Or “basis”; or “support”</span>of the truth.'),
('LEB', '1 Timothy', '3', '16', '5', 'And most certainly, great is the mystery of godliness: Who was revealed in the flesh,  was vindicated by<span class=\"note\">Or perhaps “in”</span>the Spirit,  was seen by angels,  was proclaimed among the Gentiles<span class=\"note\">Or “nations”; the same Greek word can be translated “nations” or “Gentiles” depending on the context</span>,  was believed on in the world,  was taken up in glory.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Timothy', '4', '1', '1', '<span class=\"verse-title\">The Coming Apostasy</span>Now the Spirit explicitly says that in the last times some will depart from the faith, paying attention to deceitful spirits and teachings of demons,'),
('LEB', '1 Timothy', '4', '2', '1', 'by the hypocrisy of liars, who are seared in their own conscience,'),
('LEB', '1 Timothy', '4', '3', '1', 'who forbid marrying <span class=\"supplied\">and insist on</span> abstaining from foods that God created for sharing in with thankfulness by those who believe and who know the truth,'),
('LEB', '1 Timothy', '4', '4', '1', 'because everything created by God <span class=\"supplied\">is</span> good and nothing <span class=\"supplied\">is to be</span> rejected <span class=\"supplied\">if it is</span>received with thankfulness,'),
('LEB', '1 Timothy', '4', '5', '1', 'for it is made holy by the word of God and prayer.'),
('LEB', '1 Timothy', '4', '6', '3', '<span class=\"verse-title\">The Good Servant of Christ</span><span class=\"supplied\">By</span>teaching these <span class=\"supplied\">things</span> to the brothers, you will be a good servant of Christ Jesus, trained in the words of the faith and of the good teaching that you have followed faithfully.'),
('LEB', '1 Timothy', '4', '7', '3', 'But reject those <span class=\"idiom\">worthless myths told by elderly women</span><span class=\"note\">Literally “worthless and characteristic of an elderly woman myths”</span>, and train yourself for godliness.'),
('LEB', '1 Timothy', '4', '8', '3', 'For the training of the body is <span class=\"idiom\">somewhat</span><span class=\"note\">Literally “for a little”</span>profitable, but godliness is profitable for everything, <span class=\"supplied\">because it</span>holds promise for the present life and for the <span class=\"supplied\">life</span> to come.'),
('LEB', '1 Timothy', '4', '9', '3', 'The statement <span class=\"supplied\">is</span> trustworthy and deserving of complete acceptance.'),
('LEB', '1 Timothy', '4', '10', '3', 'For to this <span class=\"supplied\">end</span> we labor and suffer reproach,<span class=\"note\">Some manuscripts have “and strive”</span>because we have put our hope in <span class=\"supplied\">the</span> living God, who is the Savior of all people, especially of believers.'),
('LEB', '1 Timothy', '4', '11', '4', 'Command these <span class=\"supplied\">things</span> and teach <span class=\"supplied\">them</span>.'),
('LEB', '1 Timothy', '4', '12', '4', 'Let no one look down on your youth, but be an example for the believers in word, in conduct, in love, in faith, in purity.'),
('LEB', '1 Timothy', '4', '13', '4', 'Until I come, pay attention to the <span class=\"supplied\">public</span> reading,<span class=\"note\">Many English translations supply “of scripture” here to clarify what is to be read aloud</span>to exhortation, to teaching.'),
('LEB', '1 Timothy', '4', '14', '4', 'Do not neglect the gift <span class=\"supplied\">that is</span> in you, that was granted to you through prophecy with the laying on of hands by the council of elders.'),
('LEB', '1 Timothy', '4', '15', '4', 'Practice these <span class=\"supplied\">things</span>. Be <span class=\"supplied\">diligent</span><span class=\"note\">Literally “be in these <span class=\"supplied\">things</span>,” though most English versions supply a predicate here</span>in these <span class=\"supplied\">things</span>, in order that your progress may be evident to everyone.'),
('LEB', '1 Timothy', '4', '16', '4', 'Fix <span class=\"supplied\">your</span> attention on yourself and on your teaching. Continue in them, for <span class=\"supplied\">by</span>doing this you will save both yourself and those who hear you.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Timothy', '5', '1', '1', '<span class=\"verse-title\">Instructions About Widows</span>Do not rebuke an older man, but appeal to <span class=\"supplied\">him</span> as a father, younger men as brothers,'),
('LEB', '1 Timothy', '5', '2', '1', 'older women as mothers, younger women as sisters, with all purity.'),
('LEB', '1 Timothy', '5', '3', '1', 'Honor widows <span class=\"supplied\">who are</span> truly widows.'),
('LEB', '1 Timothy', '5', '4', '1', 'But if any widow has children or grandchildren, they must learn to show profound respect for their own household first, and to pay back recompense to their parents, for this is pleasing in the sight of God.'),
('LEB', '1 Timothy', '5', '5', '1', 'But the widow <span class=\"supplied\">who is one</span> truly, and is left alone, has put her hope in God and continues in her petitions and prayers night and day.'),
('LEB', '1 Timothy', '5', '6', '1', 'But the one who lives for sensual pleasure is dead <span class=\"supplied\">even though she</span>lives.'),
('LEB', '1 Timothy', '5', '7', '1', 'And command these <span class=\"supplied\">things</span>, in order that they may be irreproachable.'),
('LEB', '1 Timothy', '5', '8', '1', 'But if someone does not provide for his own <span class=\"supplied\">relatives</span>, and especially the members of his household, he has denied the faith and is worse than an unbeliever.'),
('LEB', '1 Timothy', '5', '9', '2', 'Let a widow be put on the list <span class=\"supplied\">if she</span>is not less than sixty years <span class=\"supplied\">old</span>, the wife of one husband,'),
('LEB', '1 Timothy', '5', '10', '2', 'being well-attested by good works, if she has brought up children, if she has shown hospitality, if she has washed the feet of the saints, if she has helped those who are oppressed, if she has devoted herself to every good work.'),
('LEB', '1 Timothy', '5', '11', '2', 'But refuse younger widows, for whenever their physical desires lead them away from Christ, they want to marry,'),
('LEB', '1 Timothy', '5', '12', '2', '<span class=\"supplied\">thus</span> incurring condemnation because they have broken their former pledge.'),
('LEB', '1 Timothy', '5', '13', '2', 'And at the same time also, going around from house to house, they learn <span class=\"supplied\">to be</span> idle, and not only idle, but also gossipy and busybodies, saying the things <span class=\"supplied\">that are</span> not necessary.'),
('LEB', '1 Timothy', '5', '14', '2', 'Therefore I want younger <span class=\"supplied\">widows</span> to marry, to bear children, to manage a household, to give the adversary no opportunity for reproach.'),
('LEB', '1 Timothy', '5', '15', '2', 'For already some have turned away <span class=\"supplied\">and followed</span> after Satan.'),
('LEB', '1 Timothy', '5', '16', '2', 'If any believing woman has widows, she must help them, and the church must not be burdened, in order that it may help those <span class=\"supplied\">who are</span> truly widows.'),
('LEB', '1 Timothy', '5', '17', '4', '<span class=\"verse-title\">Honoring Worthy Elders and Dealing With Sinners</span>The elders who lead well must be considered worthy of double honor, especially those who labor by speaking and teaching.'),
('LEB', '1 Timothy', '5', '18', '4', 'For the scripture says, “You must not muzzle an ox <span class=\"supplied\">while it</span>is threshing,”<span class=\"note\">A quotation from Deut 25:4</span>and “The worker <span class=\"supplied\">is</span> worthy of his wages.”'),
('LEB', '1 Timothy', '5', '19', '4', 'Do not accept an accusation against an elder except on the evidence of two or three witnesses.'),
('LEB', '1 Timothy', '5', '20', '4', 'Reprove those who sin in the presence of all, in order that the rest also may experience fear.'),
('LEB', '1 Timothy', '5', '21', '4', 'I testify solemnly before God and Christ Jesus and the elect angels that you observe these <span class=\"supplied\">things</span> without prejudice, doing nothing according to partiality.'),
('LEB', '1 Timothy', '5', '22', '4', 'Lay hands on no one hastily, and do not participate in the sins of others. Keep yourself pure.'),
('LEB', '1 Timothy', '5', '23', '4', '(No longer drink only water, but use a little wine for your stomach and your frequent illnesses.)'),
('LEB', '1 Timothy', '5', '24', '4', 'The sins of some people are evident, preceding <span class=\"supplied\">them</span> to judgment, but for some also they follow after <span class=\"supplied\">them</span>.'),
('LEB', '1 Timothy', '5', '25', '4', 'Likewise also good works <span class=\"supplied\">are</span> evident, and those considered otherwise are not able to be hidden.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '1 Timothy', '6', '1', '1', '<span class=\"verse-title\">Slaves and Masters</span>All those who are under the yoke as slaves must regard their own masters as worthy of all honor, lest the name of God and the teaching be slandered.'),
('LEB', '1 Timothy', '6', '2', '1', 'And those who have believing masters must not look down on <span class=\"supplied\">them</span> because they are brothers, but rather they must serve, because those who benefit by their service are believers and dearly loved.'),
('LEB', '1 Timothy', '6', '3', '3', '<span class=\"verse-title\">False Teachers and the Love of Money</span>Teach and encourage these <span class=\"supplied\">things</span>.'),
('LEB', '1 Timothy', '6', '4', '3', 'If anyone teaches other doctrine and does not devote himself to the sound words of our Lord Jesus Christ and the teaching <span class=\"supplied\">that is</span> in accordance with godliness,'),
('LEB', '1 Timothy', '6', '5', '3', 'he is conceited, understanding nothing, but having a morbid interest concerning controversies and disputes about words, from which come envy, strife, slanders, evil suspicions,'),
('LEB', '1 Timothy', '6', '6', '3', 'constant wrangling by people of depraved mind and deprived of the truth, who consider godliness to be a means of gain.'),
('LEB', '1 Timothy', '6', '7', '3', 'But godliness with contentment is a great means of gain.'),
('LEB', '1 Timothy', '6', '8', '3', 'For we have brought nothing into the world, so that neither can we bring anything out.'),
('LEB', '1 Timothy', '6', '9', '3', 'But <span class=\"supplied\">if we</span>have food and clothing, with these <span class=\"supplied\">things</span> we will be content.'),
('LEB', '1 Timothy', '6', '10', '3', 'But those who want to be rich fall into temptation and a trap and many foolish and harmful desires, which plunge those people into ruin and destruction.'),
('LEB', '1 Timothy', '6', '11', '5', '<span class=\"verse-title\">Renewed Charge to Timothy</span>But you, O man of God, flee from these <span class=\"supplied\">things</span>, and pursue righteousness, godliness, faith, love, patient endurance, gentleness.'),
('LEB', '1 Timothy', '6', '12', '5', 'Fight the good fight of the faith; take hold of the eternal life to which you were called, and confessed the good confession in the presence of many witnesses.'),
('LEB', '1 Timothy', '6', '13', '5', 'I command you, in the sight of God who gives life to all <span class=\"supplied\">things</span> and Christ Jesus who testified the good confession before Pontius Pilate,'),
('LEB', '1 Timothy', '6', '14', '5', '<span class=\"supplied\">that</span> you observe the commandment without fault, irreproachable until the appearing of our Lord Jesus Christ,'),
('LEB', '1 Timothy', '6', '15', '5', 'which he will make known in his own time, the blessed and only Sovereign, the King of those who reign as kings and Lord of those who rule as lords,'),
('LEB', '1 Timothy', '6', '16', '5', 'the <span class=\"supplied\">one who</span> alone possesses immortality, who lives <span class=\"supplied\">in</span> unapproachable light, whom no human being has seen nor is able to see, to whom <span class=\"supplied\">be</span> honor and eternal power. Amen.'),
('LEB', '1 Timothy', '6', '17', '7', '<span class=\"verse-title\">Instructions to the Rich</span>Command those <span class=\"supplied\">who are</span> rich in this present age not to be proud and not to put their hope in the uncertainty of riches, but in God, who provides us all <span class=\"supplied\">things</span> richly for enjoyment,'),
('LEB', '1 Timothy', '6', '18', '7', 'to do good, to be rich in good works, to be generous, sharing freely,'),
('LEB', '1 Timothy', '6', '19', '7', 'storing up for themselves a good foundation for the future, in order that they may take hold of <span class=\"supplied\">what is</span> truly life.'),
('LEB', '1 Timothy', '6', '20', '9', '<span class=\"verse-title\">Final Charge and Benediction</span>O Timothy, guard what has been entrusted <span class=\"supplied\">to you</span>. Turn away from pointless empty talk and contradictions of <span class=\"supplied\">what is</span> falsely called knowledge,'),
('LEB', '1 Timothy', '6', '21', '9', 'which some, <span class=\"supplied\">by</span>professing <span class=\"supplied\">it</span>, have deviated concerning the faith. Grace <span class=\"supplied\">be</span> with you <span class=\"supplied\">all</span>.')
;

