INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '2 Timothy', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, an apostle of Christ Jesus through the will of God, according to the promise of life which <span class=\"supplied\">is</span> in Christ Jesus,'),
('LEB', '2 Timothy', '1', '2', '1', 'to Timothy, <span class=\"supplied\">my</span> dear child. Grace, mercy, <span class=\"supplied\">and</span> peace from God the Father and Christ Jesus our Lord.'),
('LEB', '2 Timothy', '1', '3', '3', '<span class=\"verse-title\">Timothy’s Spiritual Heritage</span><span class=\"idiom\">I am thankful</span><span class=\"note\">“I have thankfulness”</span>to God, whom I have served with a clear conscience <span class=\"idiom\">as my ancestors did</span><span class=\"note\">“from ancestors”</span>, when <span class=\"idiom\">I remember you constantly</span><span class=\"note\">“I have remembrance concerning you constantly”</span>in my prayers night and day,'),
('LEB', '2 Timothy', '1', '4', '3', 'longing to see you <span class=\"supplied\">as I</span>remember your tears, so that I may be filled with joy,'),
('LEB', '2 Timothy', '1', '5', '3', '<span class=\"idiom\">remembering the</span><span class=\"note\">“receiving a remembrance of the”</span>sincere faith in you, which lived first in your grandmother Lois and your mother Eunice, and I am convinced that <span class=\"supplied\">is</span> in you also,'),
('LEB', '2 Timothy', '1', '6', '3', 'for which reason I remind you to rekindle the gift of God that is in you through the laying on of my hands.'),
('LEB', '2 Timothy', '1', '7', '3', 'For God has not given us a spirit of cowardice, but of power and love and self-discipline.'),
('LEB', '2 Timothy', '1', '8', '5', '<span class=\"verse-title\">Exhortation to Share Paul’s Suffering</span>Therefore, do not be ashamed of the testimony about our Lord, nor me his prisoner, but suffer along with <span class=\"supplied\">me</span> for the gospel, according to the power of God,'),
('LEB', '2 Timothy', '1', '9', '5', 'who saved us and called <span class=\"supplied\">us</span> with a holy calling, not according to our works but according to his own purpose and grace that was given to us in Christ Jesus <span class=\"idiom\">before time began</span><span class=\"note\">“before times eternal”</span>,'),
('LEB', '2 Timothy', '1', '10', '5', 'but has now been disclosed by the appearing of our Savior Jesus Christ,<span class=\"note\">Some manuscripts have “our Savior Christ Jesus”</span>who has abolished death and brought to light life and immortality through the gospel,'),
('LEB', '2 Timothy', '1', '11', '5', 'for which I was appointed a proclaimer and an apostle and a teacher,'),
('LEB', '2 Timothy', '1', '12', '5', 'for which reason also I suffer these <span class=\"supplied\">things</span>. But <span class=\"supplied\">I am</span> not ashamed, because I know in whom I have believed, and I am convinced that he is able to guard <span class=\"supplied\">what</span> I have entrusted until that day.'),
('LEB', '2 Timothy', '1', '13', '5', 'Hold fast to the pattern of sound words which you heard from me, in the faith and love <span class=\"supplied\">that are</span> in Christ Jesus.'),
('LEB', '2 Timothy', '1', '14', '5', 'Guard the good deposit through the Holy Spirit who lives in us.'),
('LEB', '2 Timothy', '1', '15', '6', 'You know this, that all those in Asia turned away from me, among whom are Phygelus and Hermogenes.'),
('LEB', '2 Timothy', '1', '16', '6', 'May the Lord grant mercy to the household of Onesiphorus, because he refreshed me many times, and was not ashamed of my imprisonment,'),
('LEB', '2 Timothy', '1', '17', '6', 'but <span class=\"supplied\">when he</span>was in Rome, he diligently sought me and found <span class=\"supplied\">me</span>.'),
('LEB', '2 Timothy', '1', '18', '6', 'May the Lord grant him to find mercy from the Lord in that day! And how much he served <span class=\"supplied\">me</span> in Ephesus you know very well.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '2 Timothy', '2', '1', '1', '<span class=\"verse-title\">Exhortation to Be Strong in Grace</span>You, therefore, my child, be strong in the grace <span class=\"supplied\">that is</span> in Christ Jesus,'),
('LEB', '2 Timothy', '2', '2', '1', 'and <span class=\"supplied\">the things</span> which you have heard from me in the presence of many witnesses, entrust these <span class=\"supplied\">things</span> to faithful people who will be competent to teach others also.'),
('LEB', '2 Timothy', '2', '3', '1', 'Suffer together with <span class=\"supplied\">me</span> as a good soldier of Christ Jesus.'),
('LEB', '2 Timothy', '2', '4', '1', 'No one who serves as a soldier is entangled in the activities of <span class=\"supplied\">everyday</span> life, so that he may please the one who enlisted <span class=\"supplied\">him</span>.'),
('LEB', '2 Timothy', '2', '5', '1', 'And also if anyone competes he is not crowned unless he competes according to the rules.'),
('LEB', '2 Timothy', '2', '6', '1', 'The farmer who works hard must <span class=\"supplied\">be</span> the first to receive a share of the crops.'),
('LEB', '2 Timothy', '2', '7', '1', 'Consider what I am saying, for the Lord will grant you understanding in all <span class=\"supplied\">these things</span>.'),
('LEB', '2 Timothy', '2', '8', '3', '<span class=\"verse-title\">A Trustworthy Saying</span>Remember Jesus Christ, raised from the dead, a descendant of David according to my gospel,'),
('LEB', '2 Timothy', '2', '9', '3', 'in connection with which I suffer misfortune to the point of <span class=\"idiom\">imprisonment</span><span class=\"note\">“bonds”</span>as a criminal, but the word of God is not bound.'),
('LEB', '2 Timothy', '2', '10', '3', 'Because of this, I endure all <span class=\"supplied\">things</span> for the sake of the chosen, in order that they also may obtain salvation <span class=\"supplied\">which is</span> in Christ Jesus with eternal glory.'),
('LEB', '2 Timothy', '2', '11', '3', 'The saying <span class=\"supplied\">is</span> trustworthy:'),
('LEB', '2 Timothy', '2', '12', '4', 'For if we died with <span class=\"supplied\">him</span>, we will also live with <span class=\"supplied\">him</span>;'),
('LEB', '2 Timothy', '2', '13', '4', 'if we endure, we will also reign with <span class=\"supplied\">him</span>;  if we deny <span class=\"supplied\">him</span>, he also will deny us;'),
('LEB', '2 Timothy', '2', '14', '6', '<span class=\"verse-title\">A Worker Approved to God and Not Ashamed</span>Remind <span class=\"supplied\">people</span> of these <span class=\"supplied\">things</span>, solemnly urging <span class=\"supplied\">them</span> before the Lord<span class=\"note\">Some manuscripts have “before God”</span>not to dispute about words. <span class=\"supplied\">This is</span> in no way beneficial <span class=\"supplied\">and leads to</span> the ruin of the hearers.'),
('LEB', '2 Timothy', '2', '15', '6', 'Make every effort to present yourself approved to God, a worker having no need to be ashamed, guiding the word of truth along a straight path.'),
('LEB', '2 Timothy', '2', '16', '6', 'But avoid pointless chatter, for it will progress to greater ungodliness,'),
('LEB', '2 Timothy', '2', '17', '6', 'and their message <span class=\"idiom\">will spread</span><span class=\"note\">“will experience spreading”</span>like gangrene, among whom are Hymenaeus and Philetus,'),
('LEB', '2 Timothy', '2', '18', '6', 'who have deviated concerning the truth <span class=\"supplied\">by</span>saying the resurrection has already taken place, and they are upsetting the faith of some.'),
('LEB', '2 Timothy', '2', '19', '6', 'However, the solid foundation of God stands firm, having this seal: “The Lord knows those who are his,”<span class=\"note\">Num 16:5</span>and “Everyone who names the name of the Lord must abstain from unrighteousness.”'),
('LEB', '2 Timothy', '2', '20', '7', 'Now in a great house <span class=\"supplied\">there</span> are not only gold and silver vessels, but also wooden and earthenware <span class=\"supplied\">ones</span>, some of which <span class=\"supplied\">are</span> for honorable use, and some of which <span class=\"supplied\">are</span> for ordinary use.'),
('LEB', '2 Timothy', '2', '21', '7', 'Therefore, if someone cleanses himself from these <span class=\"supplied\">things</span>, he will be a vessel for honorable use, set apart, useful to the Master, prepared for every good work.'),
('LEB', '2 Timothy', '2', '22', '8', 'But flee from youthful desires, and pursue righteousness, faith, love, <span class=\"supplied\">and</span> peace, in company with those who call upon the Lord from a pure heart.'),
('LEB', '2 Timothy', '2', '23', '8', 'But avoid foolish and uninformed controversies, <span class=\"supplied\">because you</span>know that they produce quarrels.'),
('LEB', '2 Timothy', '2', '24', '8', 'And the slave of the Lord must not quarrel, but be kind toward everyone, skillful in teaching, tolerant,'),
('LEB', '2 Timothy', '2', '25', '8', 'correcting those who are opposed with gentleness, <span class=\"supplied\">seeing</span> whether perhaps God may grant them repentance to a knowledge of the truth,'),
('LEB', '2 Timothy', '2', '26', '8', 'and they will come to their senses again <span class=\"supplied\">and escape</span> from the trap of the devil, being held captive by him to <span class=\"supplied\">do</span> his will.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '2 Timothy', '3', '1', '1', '<span class=\"verse-title\">Difficult Times Ahead in the Last Days</span>But know this, that in the last days difficult times will come,'),
('LEB', '2 Timothy', '3', '2', '1', 'for people will be lovers of themselves, lovers of money, boasters, arrogant, slanderers, disobedient to parents, ungrateful, unholy,'),
('LEB', '2 Timothy', '3', '3', '1', 'hardhearted, irreconcilable, slanderous, without self-control, savage, with no interest for what is good,'),
('LEB', '2 Timothy', '3', '4', '1', 'traitors, reckless, conceited, loving pleasure rather than loving God,'),
('LEB', '2 Timothy', '3', '5', '1', 'maintaining a form of godliness, but denying its power. Avoid these <span class=\"supplied\">people</span>.'),
('LEB', '2 Timothy', '3', '6', '1', 'For from these are those who slip into houses and captivate foolish women loaded down with sins, led by various kinds of desires,'),
('LEB', '2 Timothy', '3', '7', '1', 'always learning and never able to come to a knowledge of the truth.'),
('LEB', '2 Timothy', '3', '8', '1', 'And <span class=\"idiom\">just as</span><span class=\"note\">“in the manner in which”</span>Jannes and Jambres opposed Moses, so also these oppose the truth, people corrupted in mind, disqualified concerning the faith.'),
('LEB', '2 Timothy', '3', '9', '1', 'But they will not progress to a greater extent, for their folly will be quite evident to everyone, as also the <span class=\"supplied\">folly</span> of those <span class=\"supplied\">two</span> was.'),
('LEB', '2 Timothy', '3', '10', '3', '<span class=\"verse-title\">The Value of the Scriptures</span>But you have faithfully followed my teaching, way of life, purpose, faith, patience, love, endurance,'),
('LEB', '2 Timothy', '3', '11', '3', 'persecutions, <span class=\"supplied\">and</span> sufferings that happened to me in Antioch, in Iconium, <span class=\"supplied\">and</span> in Lystra, what sort of persecutions I endured, and the Lord delivered me from all <span class=\"supplied\">of them</span>.'),
('LEB', '2 Timothy', '3', '12', '3', 'And indeed, all those who want to live in a godly manner in Christ Jesus will be persecuted.'),
('LEB', '2 Timothy', '3', '13', '3', 'But evil people and imposters will progress to the worse, deceiving and being deceived.'),
('LEB', '2 Timothy', '3', '14', '3', 'But you continue in <span class=\"supplied\">the things</span> which you have learned and are convinced <span class=\"supplied\">of</span>, <span class=\"supplied\">because you</span>know from whom you learned <span class=\"supplied\">them</span>,'),
('LEB', '2 Timothy', '3', '15', '3', 'and that from childhood you have known the holy writings that are able <span class=\"supplied\">to make</span> you wise for salvation through faith in Christ Jesus.'),
('LEB', '2 Timothy', '3', '16', '3', 'All scripture <span class=\"supplied\">is</span> inspired by God and profitable for teaching, for reproof, for correction, for training in righteousness,'),
('LEB', '2 Timothy', '3', '17', '3', 'in order that the person of God may be competent, equipped for every good work.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', '2 Timothy', '4', '1', '1', '<span class=\"verse-title\">Paul’s Charge to Timothy</span>I solemnly charge <span class=\"supplied\">you</span> before God and Christ Jesus, who is going to judge the living and the dead, and by his appearing and his kingdom,'),
('LEB', '2 Timothy', '4', '2', '1', 'preach the word, be ready in season <span class=\"supplied\">and</span> out of season, reprove, rebuke, exhort, with all patience and instruction.'),
('LEB', '2 Timothy', '4', '3', '1', 'For there will be a time when they will not put up with sound teaching, but in accordance with their own desires, they will accumulate for themselves teachers, <span class=\"idiom\">because they have an insatiable curiosity</span><span class=\"note\">“feeling an itching in the ear”; “because” is supplied as a component of the participle (“feeling an itching”) which is understood as causal</span>,'),
('LEB', '2 Timothy', '4', '4', '1', 'and they will turn away from the hearing of the truth, but will turn to myths.'),
('LEB', '2 Timothy', '4', '5', '1', 'But you, be self-controlled in all <span class=\"supplied\">things</span>, bear hardship patiently, do the work of an evangelist, fulfill your ministry.'),
('LEB', '2 Timothy', '4', '6', '2', 'For I am already being poured out as a drink offering, and the time of my departure is imminent.'),
('LEB', '2 Timothy', '4', '7', '2', 'I have fought the good fight, I have completed the race, I have kept the faith.'),
('LEB', '2 Timothy', '4', '8', '2', 'Finally, the crown of righteousness is reserved for me, that the Lord, the righteous Judge, will award to me on that day, and not only to me, but also to all who have loved his appearing.'),
('LEB', '2 Timothy', '4', '9', '4', '<span class=\"verse-title\">Final Instructions to Timothy</span>Make haste to come to me quickly.'),
('LEB', '2 Timothy', '4', '10', '4', 'For Demas deserted me, <span class=\"supplied\">because he</span>loved the present age, and went to Thessalonica. Crescens <span class=\"supplied\">went</span> to Galatia; Titus <span class=\"supplied\">went</span> to Dalmatia.'),
('LEB', '2 Timothy', '4', '11', '4', 'Luke alone is with me. Take along Mark <span class=\"supplied\">and</span>bring <span class=\"supplied\">him</span> with you, because he is useful to me for ministry.'),
('LEB', '2 Timothy', '4', '12', '4', 'But I have sent Tychicus to Ephesus.'),
('LEB', '2 Timothy', '4', '13', '4', '<span class=\"supplied\">When you</span>come, bring the cloak that I left behind in Troas with Carpus, and the scrolls, especially the parchments.'),
('LEB', '2 Timothy', '4', '14', '4', 'Alexander the metalworker did me much harm; may the Lord pay back to him according to his deeds,'),
('LEB', '2 Timothy', '4', '15', '4', 'against whom you also be on guard, because he vehemently opposed our words.'),
('LEB', '2 Timothy', '4', '16', '4', 'At my first defense, no one came to my <span class=\"supplied\">aid</span>, but <span class=\"supplied\">they</span> all deserted me; may it not be counted against them.'),
('LEB', '2 Timothy', '4', '17', '4', 'But the Lord helped me and strengthened me, so that through me the proclamation might be fulfilled and all the Gentiles might hear, and he rescued <span class=\"supplied\">me</span> from the lion’s mouth.'),
('LEB', '2 Timothy', '4', '18', '4', 'The Lord will rescue me from every evil deed, and will save <span class=\"supplied\">me</span> for his heavenly kingdom, to whom <span class=\"supplied\">be</span> the glory <span class=\"idiom\">forever and ever</span><span class=\"note\">“to the ages of the ages”</span>. Amen.'),
('LEB', '2 Timothy', '4', '19', '6', '<span class=\"verse-title\">Final Greetings and Benediction</span>Greet Prisca and Aquila and the household of Onesiphorus.'),
('LEB', '2 Timothy', '4', '20', '6', 'Erastus remained in Corinth, but Trophimus I left behind in Miletus <span class=\"supplied\">because he</span>was sick.'),
('LEB', '2 Timothy', '4', '21', '6', 'Make haste to come before winter. Eubulus and Pudens and Linus and Claudia and all the brothers greet you.'),
('LEB', '2 Timothy', '4', '22', '6', 'The Lord <span class=\"supplied\">be</span> with your spirit. Grace <span class=\"supplied\">be</span> with you.')
;

