INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Colossians', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, an apostle of Christ Jesus through the will of God, and Timothy our brother,'),
('LEB', 'Colossians', '1', '2', '1', 'to the saints and faithful brothers in Christ in Colossae. Grace to you and peace from God our Father.'),
('LEB', 'Colossians', '1', '3', '3', '<span class=\"verse-title\">Thanksgiving for the Colossian Believers</span>We give thanks always to God the Father of our Lord Jesus Christ <span class=\"supplied\">when we</span>pray for you,'),
('LEB', 'Colossians', '1', '4', '3', '<span class=\"supplied\">since we</span>heard about your faith in Christ Jesus and the love that you have for all the saints,'),
('LEB', 'Colossians', '1', '5', '3', 'because of the hope reserved for you in heaven, which you have heard about beforehand in the word of truth, the gospel,'),
('LEB', 'Colossians', '1', '6', '3', 'that has come to you, just as also in all the world it is bearing fruit and increasing, just as also among you from the day you heard about and understood the grace of God in truth,'),
('LEB', 'Colossians', '1', '7', '3', 'just as you learned <span class=\"supplied\">it</span>from Epaphras, our dear fellow slave who is a faithful minister of Christ <span class=\"supplied\">on</span> our behalf,<span class=\"note\">Some manuscripts have “on your behalf”</span>'),
('LEB', 'Colossians', '1', '8', '3', '<span class=\"supplied\">who</span> also made clear to us your love in the Spirit.'),
('LEB', 'Colossians', '1', '9', '5', '<span class=\"verse-title\">Prayer for Maturity Based on Christ’s Preeminence</span>Because of this also we, from the day we heard about <span class=\"supplied\">it</span>,did not cease praying for you, and asking that you may be filled <span class=\"supplied\">with</span> the knowledge of his will in all wisdom and spiritual insight,'),
('LEB', 'Colossians', '1', '10', '5', 'so that you may live in a manner worthy of the Lord, <span class=\"idiom\">to please <span class=\"supplied\">him</span> in all respects</span><span class=\"note\">Literally “to all pleasing”</span>, bearing fruit in every good deed and increasing in the knowledge of God,'),
('LEB', 'Colossians', '1', '11', '5', 'enabled with all power, according to his glorious might, for all steadfastness and patience with joy,'),
('LEB', 'Colossians', '1', '12', '5', 'giving thanks to the Father who has qualified you for a share of the inheritance of the saints in light,'),
('LEB', 'Colossians', '1', '13', '5', 'who has rescued us from the domain of darkness and transferred <span class=\"supplied\">us</span>to the kingdom of the Son <span class=\"idiom\">he loves</span><span class=\"note\">Literally “of his love”</span>,'),
('LEB', 'Colossians', '1', '14', '5', 'in whom we have the redemption, the forgiveness of sins,'),
('LEB', 'Colossians', '1', '15', '5', 'who is the image of the invisible God, the firstborn over allcreation,'),
('LEB', 'Colossians', '1', '16', '5', 'because all <span class=\"supplied\">things</span> in the heavens and on the earth were created by him, things visible and things invisible, whether thrones or dominions or rulers or powers, all <span class=\"supplied\">things</span> were created through him and for him,'),
('LEB', 'Colossians', '1', '17', '5', 'and he himself is before all <span class=\"supplied\">things</span>, and in him all <span class=\"supplied\">things</span> are held together,'),
('LEB', 'Colossians', '1', '18', '5', 'and he himself is the head of the body, the church, who is the beginning, the firstborn from the dead, so that he himself may become first in everything,'),
('LEB', 'Colossians', '1', '19', '5', 'because he was well pleased <span class=\"supplied\">for</span> all the fullness to dwell in him,'),
('LEB', 'Colossians', '1', '20', '5', 'and through him to reconcile all <span class=\"supplied\">things</span> to himself, <span class=\"supplied\">by</span>making peace through the blood of his cross, through him, whether things on earth or things in heaven.'),
('LEB', 'Colossians', '1', '21', '6', 'And <span class=\"idiom\">although you were formerly alienated</span><span class=\"note\">Literally “and you formerly being alienated”</span>and enemies in attitude, because of your evil deeds,'),
('LEB', 'Colossians', '1', '22', '6', 'but now you have been reconciled<span class=\"note\">Some manuscripts have “he has reconciled <span class=\"supplied\">you</span>”</span>by <span class=\"idiom\">his physical body</span><span class=\"note\">Literally “the body of his flesh”</span>through death, to present you holy and blameless and above reproach before him,'),
('LEB', 'Colossians', '1', '23', '6', 'if indeed you remain in the faith, established and steadfast and not shifted away from the hope of the gospel that you heard, which was proclaimed in all creation under heaven, of which I, Paul, became a minister.'),
('LEB', 'Colossians', '1', '24', '8', '<span class=\"verse-title\">Paul’s Suffering and Stewardship</span>Now I rejoice in my sufferings on behalf of you, and I fill up in my flesh what is lacking of the afflictions of Christ, on behalf of his body which is the church,'),
('LEB', 'Colossians', '1', '25', '8', 'of which I became a minister, according to God’s stewardship which was given to me for you, to complete the word of God,'),
('LEB', 'Colossians', '1', '26', '8', 'the mystery <span class=\"supplied\">which</span> has been hidden from the ages and from the generations, but has now been revealed to his saints,'),
('LEB', 'Colossians', '1', '27', '8', 'to whom God wanted to make known what <span class=\"supplied\">is</span> the glorious wealth of this mystery among the Gentiles, which is Christ in you, the hope of glory,'),
('LEB', 'Colossians', '1', '28', '8', 'whom we proclaim, <span class=\"supplied\">by</span>admonishing every person<span class=\"note\">Literally “man,” used here in a generic sense to refer to persons of either gender</span>and teaching every person<span class=\"note\">Literally “man,” used here in a generic sense to refer to persons of either gender</span>with all wisdom, in order that we may present every person<span class=\"note\">Literally “man,” used here in a generic sense to refer to persons of either gender</span>mature in Christ,'),
('LEB', 'Colossians', '1', '29', '8', 'for which <span class=\"supplied\">purpose</span> also I labor, striving according to his working which is at work powerfully in me.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Colossians', '2', '1', '1', '<span class=\"verse-title\">Christ, the Mystery of God</span>For I want you to know how great a struggle I have on behalf of you, and those in Laodicea, and all those who have not seen my face <span class=\"idiom\">in person</span><span class=\"note\">Literally “in the flesh”</span>,'),
('LEB', 'Colossians', '2', '2', '1', 'so that their hearts may be encouraged, united in love and into all the wealth of the full assurance of insight into the knowledge of the mystery of God, Christ,'),
('LEB', 'Colossians', '2', '3', '1', 'in whom all the treasures of wisdom and knowledge are hidden.'),
('LEB', 'Colossians', '2', '4', '1', 'I say this in order that no one will deceive you with persuasive speech,'),
('LEB', 'Colossians', '2', '5', '1', 'for even if I am absent in the flesh, yet I am with you in spirit, rejoicing and seeing your good order and the steadfastness of your faith in Christ.'),
('LEB', 'Colossians', '2', '6', '3', '<span class=\"verse-title\">Made Alive in Christ</span>Therefore as you have received Christ Jesus the Lord, live in him,'),
('LEB', 'Colossians', '2', '7', '3', 'firmly rooted and built up in him and established in the faith, just as you were taught, abounding with thankfulness.'),
('LEB', 'Colossians', '2', '8', '3', 'Beware lest <span class=\"idiom\">anyone take you captive</span><span class=\"note\">Literally “anyone be the one who takes captive you”</span>through philosophy and empty deceit, according to <span class=\"idiom\">human tradition</span><span class=\"note\">Literally “the tradition of men”</span>, according to the elemental spirits of the world and not according to Christ,'),
('LEB', 'Colossians', '2', '9', '3', 'because in him all the fullness of deity dwells bodily,'),
('LEB', 'Colossians', '2', '10', '3', 'and you are filled in him, who is the head over every ruler and authority,'),
('LEB', 'Colossians', '2', '11', '3', 'in whom also you were circumcised with a circumcision not made by hands, by the removal of the body of the flesh, by the circumcision of Christ,'),
('LEB', 'Colossians', '2', '12', '3', 'having been buried with him in baptism, in which also you were raised together with <span class=\"supplied\">him</span> through faith in the working of God, who raised him from the dead.'),
('LEB', 'Colossians', '2', '13', '3', 'And <span class=\"idiom\">although you were dead</span><span class=\"note\">Literally “and you being dead”</span>in the trespasses and the uncircumcision of your flesh, he made you alive together with him, having forgiven us all our trespasses,'),
('LEB', 'Colossians', '2', '14', '3', 'having destroyed the certificate of indebtedness in ordinances against us, which was hostile to us, and removed it out of the way <span class=\"supplied\">by</span>nailing it to the cross.'),
('LEB', 'Colossians', '2', '15', '3', '<span class=\"supplied\">When he</span>had disarmed the rulers and the authorities, he made a display of <span class=\"supplied\">them</span> in public, triumphing over them by it.<span class=\"note\">Or “in him”</span>'),
('LEB', 'Colossians', '2', '16', '5', '<span class=\"verse-title\">Do Not Be Judged by Human Religious Rules</span>Therefore do not let anyone judge you with reference to eating or<span class=\"note\">Some manuscripts have “and”</span>drinking or participation in a feast or a new moon or a Sabbath,'),
('LEB', 'Colossians', '2', '17', '5', 'which are a shadow of what is to come, but the reality <span class=\"supplied\">is</span> Christ.'),
('LEB', 'Colossians', '2', '18', '5', 'Let no one condemn you, taking pleasure in humility and the worship of angels, going into detail <span class=\"supplied\">about</span> <span class=\"supplied\">the things</span> which he has seen, inflated without cause by his fleshly mind,'),
('LEB', 'Colossians', '2', '19', '5', 'and not holding fast to the head, from whom the whole body, supported and held together by the ligaments and sinews, grows with the growth of God.'),
('LEB', 'Colossians', '2', '20', '6', 'If you have died with Christ to the elemental spirits of the world, why do you submit <span class=\"supplied\">to them</span> as <span class=\"supplied\">if</span> living in the world?'),
('LEB', 'Colossians', '2', '21', '6', '“Do not handle, do not taste, do not touch,”'),
('LEB', 'Colossians', '2', '22', '6', 'which <span class=\"supplied\">things</span> are all <span class=\"supplied\">meant</span> for destruction by consuming according to human commandments and teachings,'),
('LEB', 'Colossians', '2', '23', '6', 'which <span class=\"supplied\">things</span> <span class=\"idiom\">although they have</span><span class=\"note\">Literally “having”</span>,to be sure, an appearance of wisdom in self-made religion and humility and unsparing treatment of the body, <span class=\"idiom\">do not have any value</span><span class=\"note\">Literally “are not with any value”</span>against the indulgence of the flesh.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Colossians', '3', '1', '1', '<span class=\"verse-title\">Seek the Things Above</span>Therefore, if you have been raised together with Christ, seek the things above, where Christ is, seated at the right hand of God.'),
('LEB', 'Colossians', '3', '2', '1', 'Set your mind on the things above, not <span class=\"supplied\">on</span> the things on earth.'),
('LEB', 'Colossians', '3', '3', '1', 'For you have died, and your life is hidden with Christ in God.'),
('LEB', 'Colossians', '3', '4', '1', 'When Christ, <span class=\"supplied\">who is</span> your life, is revealed, then you also will be revealed with him in glory.'),
('LEB', 'Colossians', '3', '5', '3', '<span class=\"verse-title\">Put Off the Old Behavior</span>Therefore put to death <span class=\"idiom\">what is earthly in you</span><span class=\"note\">Literally “the members on the earth”</span>: sexual immorality, uncleanness, lustful passion, evil desire, and greediness, which is idolatry,'),
('LEB', 'Colossians', '3', '6', '3', 'because of which the wrath of God is coming upon the sons of disobedience,'),
('LEB', 'Colossians', '3', '7', '3', 'in which also you once lived, when you used to live in them.<span class=\"note\">Or “among them” (the pronoun may refer either to people or to sins)</span>'),
('LEB', 'Colossians', '3', '8', '3', 'But now you also lay aside all <span class=\"supplied\">these</span> things: anger, rage, wickedness, slander, abusive language from your mouth.'),
('LEB', 'Colossians', '3', '9', '3', 'Do not lie to one another, <span class=\"supplied\">because you</span>have taken off the old man together with his deeds,'),
('LEB', 'Colossians', '3', '10', '3', 'and have put on the new <span class=\"supplied\">man</span> that is being renewed in knowledge according to the image of the one who created him,'),
('LEB', 'Colossians', '3', '11', '3', 'where there is neither Greek nor Jew, circumcision nor uncircumcision, barbarian, Scythian, slave, <span class=\"supplied\">or</span> free, but Christ <span class=\"supplied\">is</span> all, and in all.'),
('LEB', 'Colossians', '3', '12', '5', '<span class=\"verse-title\">Appeal for New Behavior</span>Therefore, as <span class=\"supplied\">the</span> chosen of God, holy and <span class=\"supplied\">dearly</span> loved, put on affection, compassion, kindness, humility, gentleness, patience,'),
('LEB', 'Colossians', '3', '13', '5', 'putting up with one another and forgiving one another. If anyone should have a complaint against anyone, just as also the Lord forgave you, thus also you <span class=\"supplied\">do the same</span>.'),
('LEB', 'Colossians', '3', '14', '5', 'And to all these <span class=\"supplied\">things</span> <span class=\"supplied\">add</span> love, which is <span class=\"supplied\">the</span> bond of perfection.'),
('LEB', 'Colossians', '3', '15', '5', 'And the peace of Christ must rule in your hearts, to which also you were called in one body, and be thankful.'),
('LEB', 'Colossians', '3', '16', '5', 'Let the word of Christ dwell in you richly, teaching and admonishing one another with all wisdom, with psalms, hymns, <span class=\"supplied\">and</span> spiritual songs, singing with thankfulness in your hearts to God,'),
('LEB', 'Colossians', '3', '17', '5', 'and everything <span class=\"idiom\">whatever</span><span class=\"note\">Literally “if anything that”</span>you do in word or in deed, giving thanks <span class=\"supplied\">for</span> all <span class=\"supplied\">things</span> in the name of the Lord Jesus to God the Father through him.'),
('LEB', 'Colossians', '3', '18', '7', '<span class=\"verse-title\">Mutual Responsibilities in Christian Relationships</span>Wives, be subject to your husbands, as is fitting in the Lord.'),
('LEB', 'Colossians', '3', '19', '7', 'Husbands, love your wives and do not be embittered against them.'),
('LEB', 'Colossians', '3', '20', '7', 'Children, obey your parents in everything, for this is pleasing in the Lord.'),
('LEB', 'Colossians', '3', '21', '7', 'Fathers, do not provoke your children, so that they will not become discouraged.'),
('LEB', 'Colossians', '3', '22', '7', 'Slaves, obey your <span class=\"idiom\">human</span><span class=\"note\">Literally “according to the flesh”</span>masters in everything, not <span class=\"idiom\">while being watched</span><span class=\"note\">Literally “with eye-service”</span>, as people pleasers, but with sincerity of heart, fearing the Lord.'),
('LEB', 'Colossians', '3', '23', '7', 'Whatever you do, accomplish <span class=\"supplied\">it</span> from the soul, as to the Lord, and not to people,'),
('LEB', 'Colossians', '3', '24', '7', '<span class=\"supplied\">because you</span>know that from the Lord you will receive the reward of the inheritance. Serve<span class=\"note\">Or “You serve”; the same Greek verb form can be understood as either imperative (“serve”) or indicative (“you serve”), so that commentators and Bible translations differ</span>the Lord Christ.'),
('LEB', 'Colossians', '3', '25', '7', 'For the one who does wrong will receive back whatever wrong he has done, and there is no partiality.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Colossians', '4', '1', '0', 'Masters, grant your slaves justice and fairness, knowing that you also have a master in heaven.'),
('LEB', 'Colossians', '4', '2', '2', '<span class=\"verse-title\">Further Advice for the Christian Life</span>Be devoted to prayer, keeping alert in it with thanksgiving,'),
('LEB', 'Colossians', '4', '3', '2', 'praying at the same time for us also, that God may open for us a door of the message, to speak the mystery of Christ, for which also <span class=\"idiom\">I am a prisoner</span><span class=\"note\">Literally “I have been bound”</span>,'),
('LEB', 'Colossians', '4', '4', '2', 'so that I may reveal<span class=\"note\">Or “may make it clear”</span>it, as it is necessary for me to speak.'),
('LEB', 'Colossians', '4', '5', '2', 'Live with wisdom toward those outside, making the most of the time.'),
('LEB', 'Colossians', '4', '6', '2', 'Let your speech always <span class=\"supplied\">be</span> with grace, seasoned with salt, so that <span class=\"supplied\">you</span> may know how it is necessary for you to answer each one.'),
('LEB', 'Colossians', '4', '7', '4', '<span class=\"verse-title\">Exhortations Regarding Fellow Workers</span>Tychicus, my dear brother and faithful servant and fellow slave in the Lord, will make known to you all <span class=\"idiom\">my circumstances</span><span class=\"note\">Literally “the things according to me”</span>,'),
('LEB', 'Colossians', '4', '8', '4', 'whom I have sent to you for this very <span class=\"supplied\">reason</span>, in order that you may know <span class=\"idiom\">our circumstances</span><span class=\"note\">Literally “the things concerning us”</span>and he may encourage your hearts,'),
('LEB', 'Colossians', '4', '9', '4', 'together with Onesimus, my faithful and dear brother, who is <span class=\"supplied\">one</span> of you. They will make known to you all <span class=\"idiom\">the circumstances</span><span class=\"note\">Literally “the things”</span>here.'),
('LEB', 'Colossians', '4', '10', '5', 'Aristarchus, my fellow prisoner, greets you, and Mark, the cousin of Barnabas (about whom you received instructions—if he should come to you, welcome him),'),
('LEB', 'Colossians', '4', '11', '5', 'and Jesus who is called Justus. These <span class=\"supplied\">are</span> the only ones who are fellow workers for the kingdom of God from the circumcision, who have been a comfort to me.'),
('LEB', 'Colossians', '4', '12', '5', 'Epaphras, who is <span class=\"supplied\">one</span> of you, greets you, a slave of Christ<span class=\"note\">Some manuscripts have “of Christ Jesus”</span>always struggling on behalf of you in his prayers, that you may stand mature and fully assured<span class=\"note\">Or “and filled”</span>in all the will of God.'),
('LEB', 'Colossians', '4', '13', '5', 'For I testify to him that <span class=\"idiom\">he is working hard</span><span class=\"note\">Literally “he has much labor”</span>on behalf of you and those in Laodicea and those in Hierapolis.'),
('LEB', 'Colossians', '4', '14', '5', 'Luke the physician, our dear friend, greets you, <span class=\"supplied\">as does</span> Demas.'),
('LEB', 'Colossians', '4', '15', '5', 'Greet the brothers in Laodicea, and Nympha and the church in her<span class=\"note\">Some manuscripts, including the majority of Byzantine minuscules, read the masculine form of the pronoun here (“his”), understanding the form of the name “Nympha” earlier in the verse to be masculine</span>house.'),
('LEB', 'Colossians', '4', '16', '5', 'And whenever this letter is read among you, <span class=\"idiom\">see to it</span><span class=\"note\">Literally “cause”</span>that it is read also among the Laodicean church, and that you also read the <span class=\"supplied\">letter</span> from Laodicea.'),
('LEB', 'Colossians', '4', '17', '5', 'And tell Archippus, “Direct your attention to the ministry that you received in the Lord, in order that you may complete it.”'),
('LEB', 'Colossians', '4', '18', '7', '<span class=\"verse-title\">Final Greeting and Benediction</span>The greeting <span class=\"supplied\">is</span> by my hand, Paul’s. Remember my <span class=\"idiom\">imprisonment</span><span class=\"note\">Literally “bonds”</span>. Grace <span class=\"supplied\">be</span> with you.')
;

