INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ephesians', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, an apostle of Christ Jesus by the will of God, to the saints who are in Ephesus<span class=\"note\">A number of the earliest and most important manuscripts omit “in Ephesus,” though it is hard to make sense of the line without this phrase (cf. rsv, “to the saints who are also faithful”)</span>and faithful in Christ Jesus:'),
('LEB', 'Ephesians', '1', '2', '1', 'Grace to you and peace from God our Father and the Lord Jesus Christ.'),
('LEB', 'Ephesians', '1', '3', '3', '<span class=\"verse-title\">Praise to God for Spiritual Blessings</span>Blessed <span class=\"supplied\">is</span><span class=\"note\">Or “blessed <span class=\"supplied\">be</span>”</span>the God and Father of our Lord Jesus Christ, who has blessed us with every spiritual blessing in the heavenly <span class=\"supplied\">places</span> in Christ,'),
('LEB', 'Ephesians', '1', '4', '3', 'just as he chose us in him before the foundation of the world, <span class=\"supplied\">that</span> we should be holy and blameless before him in love,<span class=\"note\">Or “before him, having predestined us in love” (the phrase “in love” could go either with v. 4 or v. 5)</span>'),
('LEB', 'Ephesians', '1', '5', '3', 'having predestined us to adoption through Jesus Christ to himself according to the good pleasure of his will,'),
('LEB', 'Ephesians', '1', '6', '3', 'to the praise of the glory of his grace that he bestowed on us in the beloved,'),
('LEB', 'Ephesians', '1', '7', '3', 'in whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace,'),
('LEB', 'Ephesians', '1', '8', '3', 'that he caused to abound to us in all wisdom and insight,'),
('LEB', 'Ephesians', '1', '9', '3', 'making known to us the mystery of his will, according to his good pleasure that he purposed in him,'),
('LEB', 'Ephesians', '1', '10', '3', 'for the administration of the fullness of times, to bring together all things in Christ, the things in the heavens and the things on the earth, in him'),
('LEB', 'Ephesians', '1', '11', '3', 'in whom also we were chosen, having been predestined according to the purpose of the One who works all <span class=\"supplied\">things</span> according to the counsel of his will,'),
('LEB', 'Ephesians', '1', '12', '3', '<span class=\"supplied\">that</span> we who hoped beforehand in Christ should be for the praise of his glory,'),
('LEB', 'Ephesians', '1', '13', '3', 'in whom also you, when you heardthe word of truth, the gospel of your salvation, in whom also when you believed you were sealed with the promised Holy Spirit,'),
('LEB', 'Ephesians', '1', '14', '3', 'who is the down payment of our inheritance, until the redemption of the possession, to the praise of his glory.'),
('LEB', 'Ephesians', '1', '15', '5', '<span class=\"verse-title\">Prayer for Spiritual Wisdom</span>Because of this I also, hearing of <span class=\"idiom\">your faith</span><span class=\"note\">Literally “the according to you faith”</span>in the Lord Jesus and your love for all the saints,'),
('LEB', 'Ephesians', '1', '16', '5', 'do not cease giving thanks for you, making mention in my prayers,'),
('LEB', 'Ephesians', '1', '17', '5', 'that the God of our Lord Jesus Christ, <span class=\"idiom\">the glorious Father</span><span class=\"note\">Literally “the Father of glory”</span>,may give you a spirit of wisdomand revelation in the knowledge of him'),
('LEB', 'Ephesians', '1', '18', '5', '(the eyes of your hearts having been enlightened), so that you may know what is the hope of his calling, what <span class=\"supplied\">are</span> the riches of the glory of his inheritance among the saints,'),
('LEB', 'Ephesians', '1', '19', '5', 'and what <span class=\"supplied\">is</span> the surpassing greatness of his power toward us who believe, according to the working of his mighty strength'),
('LEB', 'Ephesians', '1', '20', '5', 'which he has worked<span class=\"note\">Some manuscripts have “he worked”</span>in Christ, raisinghim from the dead and seating <span class=\"supplied\">him</span>at his right hand in the heavenly <span class=\"supplied\">places</span>,'),
('LEB', 'Ephesians', '1', '21', '5', 'above all rule and authority and power and lordship and every name named, not only in this age but also in the coming one,'),
('LEB', 'Ephesians', '1', '22', '5', 'and he subjected all <span class=\"supplied\">things</span> under his feet<span class=\"note\">An allusion to Ps 8:6</span>and gave him <span class=\"supplied\">as</span> head over all <span class=\"supplied\">things</span> to the church,'),
('LEB', 'Ephesians', '1', '23', '5', 'which is his body, the fullness of the one who fills all <span class=\"supplied\">things</span> in every <span class=\"supplied\">way</span>.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ephesians', '2', '1', '1', '<span class=\"verse-title\">Made Alive in Christ</span>And you, <span class=\"idiom\">although you were dead</span><span class=\"note\">Literally “and you being dead”</span>in your trespasses and sins,'),
('LEB', 'Ephesians', '2', '2', '1', 'in which you formerly walked according to the course of this world, according to the ruler of the authority of the air, the spirit now working in the sons of disobedience,'),
('LEB', 'Ephesians', '2', '3', '1', 'among whom also we all formerly lived in the desires of our flesh, doing the will<span class=\"note\">Or “desires”</span>of the flesh and of the mind, and we were children of wrath<span class=\"note\">This phrase is a Semitic idiom which can mean either (1) “children characterized by wrath” or (2) “children destined for wrath”</span>by nature, as also the rest of <span class=\"supplied\">them</span> were.'),
('LEB', 'Ephesians', '2', '4', '2', 'But God, being rich in mercy, because of his great love <span class=\"supplied\">with</span> which he loved us,'),
('LEB', 'Ephesians', '2', '5', '2', 'and we being dead in trespasses, he made <span class=\"supplied\">us</span> alive together with Christ (by grace you are saved),'),
('LEB', 'Ephesians', '2', '6', '2', 'and raised <span class=\"supplied\">us</span> together and seated <span class=\"supplied\">us</span> together in the heavenly <span class=\"supplied\">places</span> in Christ Jesus,'),
('LEB', 'Ephesians', '2', '7', '2', 'in order that he might show in the coming ages the surpassing riches of his grace in kindness upon us in Christ Jesus.'),
('LEB', 'Ephesians', '2', '8', '2', 'For by grace you are saved through faith, and this <span class=\"supplied\">is</span> not from yourselves, <span class=\"supplied\">it is</span> the gift of God;'),
('LEB', 'Ephesians', '2', '9', '2', '<span class=\"supplied\">it is</span> not from works, so that no one can boast.'),
('LEB', 'Ephesians', '2', '10', '2', 'For we are his creation, created in Christ Jesus for good works, which God prepared beforehand, so that we may walk in them.'),
('LEB', 'Ephesians', '2', '11', '4', '<span class=\"verse-title\">Jewish and Gentile Believers United in Christ</span>Therefore remember that formerly you, the Gentiles in <span class=\"supplied\">the</span> flesh, the so-called uncircumcision by the so-called circumcision in <span class=\"supplied\">the</span> flesh, made by hands,'),
('LEB', 'Ephesians', '2', '12', '4', 'that you were at that time apart from Christ, alienated from the citizenship of Israel, and strangers to the covenants of promise, not having hope, and without God in the world.'),
('LEB', 'Ephesians', '2', '13', '4', 'But now in Christ Jesus you, the ones who once were far away, have become near by the blood of Christ.'),
('LEB', 'Ephesians', '2', '14', '4', 'For he himself is our peace, who made both one and broke down the dividing wall of the partition, the enmity, in his flesh,'),
('LEB', 'Ephesians', '2', '15', '4', 'invalidating the law of commandments in ordinances, in order that he might create the two in himself into one new man, <span class=\"supplied\">thus</span>making peace,'),
('LEB', 'Ephesians', '2', '16', '4', 'and might reconcile both in one body to God through the cross, killing the enmity in himself.<span class=\"note\">Or “by it” (referring to the cross)</span>'),
('LEB', 'Ephesians', '2', '17', '4', 'And coming, he proclaimed the good news of peace to you who were far away and peace to the ones who were near,'),
('LEB', 'Ephesians', '2', '18', '4', 'because through him <span class=\"supplied\">we</span> both have access in one Spirit to the Father.'),
('LEB', 'Ephesians', '2', '19', '4', 'Consequently, therefore, you are no longer strangers and foreigners, but you are fellow citizens of the saints and members of the household of God,'),
('LEB', 'Ephesians', '2', '20', '4', 'built on the foundation of the apostles and prophets, Christ Jesus himself being the cornerstone,<span class=\"note\">Or perhaps “capstone”</span>'),
('LEB', 'Ephesians', '2', '21', '4', 'in whom the whole building, joined together, grows into a holy temple in the Lord,'),
('LEB', 'Ephesians', '2', '22', '4', 'in whom you also are built up together into a dwelling place of God in <span class=\"supplied\">the</span> Spirit.<span class=\"note\">Or “are built up together in spirit <span class=\"supplied\">= spiritually</span> into a dwelling place of God” (cf. nrsv)</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ephesians', '3', '1', '1', '<span class=\"verse-title\">The Mystery of Christ Revealed</span>On account of this I, Paul, the prisoner of Christ Jesus for the sake of you Gentiles'),
('LEB', 'Ephesians', '3', '2', '1', '—if indeed you have heard <span class=\"supplied\">about</span> the stewardship of God’s grace given to me for you.'),
('LEB', 'Ephesians', '3', '3', '1', 'According to<span class=\"note\">Some manuscripts have “given to me for you, that according to”</span>revelation the mystery was made known to me, just as I wrote beforehand in brief,'),
('LEB', 'Ephesians', '3', '4', '1', 'so that you may be able when you read<span class=\"note\">Or “by reading”</span>to understand my insight into the mystery of Christ'),
('LEB', 'Ephesians', '3', '5', '1', '(which in other generations was not made known to the sons of men as it has now been revealed to his holy apostles and prophets by the Spirit):'),
('LEB', 'Ephesians', '3', '6', '1', '<span class=\"supplied\">that</span> the Gentiles are fellow heirs, and fellow members of the body, and fellow sharers of the promise in Christ Jesus through the gospel,'),
('LEB', 'Ephesians', '3', '7', '1', 'of which I became a servant, according to the gift of God’s grace given to me, according to the working of his power.'),
('LEB', 'Ephesians', '3', '8', '2', 'To me, the least of all the saints, was given this grace: to proclaim the good news of the fathomless riches of Christ to the Gentiles,'),
('LEB', 'Ephesians', '3', '9', '2', 'and to enlighten everyone <span class=\"supplied\">as to</span> what <span class=\"supplied\">is</span> the administration of the mystery hidden from the ages by God, who created all <span class=\"supplied\">things</span>,'),
('LEB', 'Ephesians', '3', '10', '2', 'in order that the many-sided wisdom of God might be made known now to the rulers and the authorities in the heavenly <span class=\"supplied\">places</span> through the church,'),
('LEB', 'Ephesians', '3', '11', '2', 'according to the purpose of the ages which he carried out in Christ Jesus our Lord,'),
('LEB', 'Ephesians', '3', '12', '2', 'in whom we have boldness and access in confidence through faith in him.<span class=\"note\">Or “through his <span class=\"supplied\">i.e., Christ’s</span> faithfulness”</span>'),
('LEB', 'Ephesians', '3', '13', '2', 'Therefore I ask <span class=\"supplied\">you</span>not to be discouraged at my afflictions on behalf of you, which are your glory.'),
('LEB', 'Ephesians', '3', '14', '4', '<span class=\"verse-title\">Prayer for Spiritual Strength</span>On account of this, I bend my knees before the Father,'),
('LEB', 'Ephesians', '3', '15', '4', 'from whom every<span class=\"note\">Or “the whole”</span>family in heaven and on earth is named,'),
('LEB', 'Ephesians', '3', '16', '4', 'that he may grant you according to the riches of his glory to be strengthened with power through his Spirit in the inner person,'),
('LEB', 'Ephesians', '3', '17', '4', '<span class=\"supplied\">that</span> Christ may dwell in your hearts through faith (you having been firmly rooted and established in love),'),
('LEB', 'Ephesians', '3', '18', '4', 'in order that you may be strong enough to grasp together with all the saints what <span class=\"supplied\">is</span> the breadth, and length, and height, and depth,'),
('LEB', 'Ephesians', '3', '19', '4', 'and to know the love of Christ that surpasses knowledge, in order that you may be filled up to all the fullness of God.'),
('LEB', 'Ephesians', '3', '20', '5', 'Now to the one who is able to do beyond all measure more than all that we ask or think, according to the power that is at work in us,'),
('LEB', 'Ephesians', '3', '21', '5', 'to him <span class=\"supplied\">be</span> the glory in the church and in Christ Jesus to all generations forever and ever. Amen.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ephesians', '4', '1', '1', '<span class=\"verse-title\">Christians Should Live in Unity</span>Therefore I, the prisoner in the Lord, exhort you to live in a manner worthy of the calling with which you were called:'),
('LEB', 'Ephesians', '4', '2', '1', 'with all humility and gentleness, with patience, putting up with one another in love,'),
('LEB', 'Ephesians', '4', '3', '1', 'being eager to keep the unity of the Spirit in the bond of peace;'),
('LEB', 'Ephesians', '4', '4', '1', 'one body and one Spirit (just as also you were called with one hope of your calling),'),
('LEB', 'Ephesians', '4', '5', '1', 'one Lord, one faith, one baptism,'),
('LEB', 'Ephesians', '4', '6', '1', 'one God and Father of all, who <span class=\"supplied\">is</span> over all, and through all, and in all.'),
('LEB', 'Ephesians', '4', '7', '3', '<span class=\"verse-title\">Gifted Leaders Bring the Church to Maturity</span>Now to each one of us was given this grace, according to the measure of Christ’s gift.'),
('LEB', 'Ephesians', '4', '8', '3', 'Therefore it says, “Ascending on high he led captivity captive;  he gave gifts to men.”'),
('LEB', 'Ephesians', '4', '9', '5', 'Now “he ascended,” what is <span class=\"supplied\">it</span>, except that he also descended<span class=\"note\">Some secondary manuscripts add “first”</span>to the lower regions of the earth?'),
('LEB', 'Ephesians', '4', '10', '5', 'The one who descended himself is also the one who ascended above all the heavens, in order that he might fill all <span class=\"supplied\">things</span>.'),
('LEB', 'Ephesians', '4', '11', '6', 'And he himself gave some <span class=\"supplied\">as</span> apostles and some <span class=\"supplied\">as</span> prophets and some <span class=\"supplied\">as</span> evangelists and some <span class=\"supplied\">as</span> pastors and teachers'),
('LEB', 'Ephesians', '4', '12', '6', 'for the equipping of the saints, for the work of the ministry, for building up the body of Christ,'),
('LEB', 'Ephesians', '4', '13', '6', 'until we all reach the unity of the faith and the knowledge of the Son of God, to a mature man, to a measure of the maturity of the fullness of Christ,'),
('LEB', 'Ephesians', '4', '14', '6', 'so that we may no longer be infants, tossed about by waves and carried about by every wind of teaching, by the trickery of people, by craftiness with reference to the scheming of deceit.'),
('LEB', 'Ephesians', '4', '15', '6', 'But speaking the truth in love, we are to grow into him <span class=\"supplied\">with reference to</span> all <span class=\"supplied\">things</span>, who is the head, Christ,'),
('LEB', 'Ephesians', '4', '16', '6', 'from whom the whole body, joined together and held together by every supporting ligament, according to the working by measure of each single part, the growth of the body makes for the building up of itself in love.'),
('LEB', 'Ephesians', '4', '17', '8', '<span class=\"verse-title\">Appeal for New Behavior</span>This therefore I say and testify in the Lord, <span class=\"supplied\">that</span> you no longer walk as the Gentiles walk: in the futility of their mind,'),
('LEB', 'Ephesians', '4', '18', '8', 'being darkened in understanding, alienated from the life of God, because of the ignorance <span class=\"supplied\">that</span> is in them, because of the hardness of their heart,'),
('LEB', 'Ephesians', '4', '19', '8', 'who, becoming callous, gave themselves over to licentiousness, for the pursuit of all uncleanness in greediness.'),
('LEB', 'Ephesians', '4', '20', '9', 'But you did not learn Christ in this way,'),
('LEB', 'Ephesians', '4', '21', '9', 'if indeed you have heard <span class=\"supplied\">about</span> him, and you were taught by him (just as truth is in Jesus),'),
('LEB', 'Ephesians', '4', '22', '9', '<span class=\"supplied\">that</span> you take off, according to your former way of life, the old man, who is being destroyed according to deceitful desires,'),
('LEB', 'Ephesians', '4', '23', '9', 'be renewed in the spirit of your mind,'),
('LEB', 'Ephesians', '4', '24', '9', 'and put on the new man (in accordance with God), who is created in righteousness and holiness from the truth.'),
('LEB', 'Ephesians', '4', '25', '11', '<span class=\"verse-title\">Old Behavior, New Behavior, and Motivation</span>Therefore, putting aside the lie, speak truth each one of you with his neighbor,<span class=\"note\">An allusion to Zech 8:16</span>because we are members of one another.'),
('LEB', 'Ephesians', '4', '26', '11', 'Be angry and do not sin;<span class=\"note\">An allusion to Ps 4:4</span>do not let the sun set on your anger,'),
('LEB', 'Ephesians', '4', '27', '11', 'nor give place to the devil.'),
('LEB', 'Ephesians', '4', '28', '11', 'The one who steals must steal no longer, but instead must labor, working with his own hands <span class=\"supplied\">what is</span> good, so that he may have <span class=\"supplied\">something</span> to share with the one who has need.'),
('LEB', 'Ephesians', '4', '29', '11', '<span class=\"idiom\">No rotten word must proceed</span><span class=\"note\">Literally “Every rotten word must not proceed”</span>from your mouth, but only something good for the building up of the need, in order that it may give grace to those who hear,'),
('LEB', 'Ephesians', '4', '30', '11', 'and do not grieve the Holy Spirit of God, by whom you were sealed for the day of redemption.'),
('LEB', 'Ephesians', '4', '31', '11', 'All bitterness, and rage, and wrath, and clamor, and abusive speech, must be removed from you, together with all wickedness.'),
('LEB', 'Ephesians', '4', '32', '11', 'Become<span class=\"note\">Some manuscripts have “But become”</span>kind toward one another, compassionate, forgiving one another, just as also God in Christ has forgiven you.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ephesians', '5', '1', '1', '<span class=\"verse-title\">Imitators of God</span>Therefore become imitators of God, as beloved children,'),
('LEB', 'Ephesians', '5', '2', '1', 'and live in love, just as also Christ loved us, and gave himself for us an offering and sacrifice to God for a fragrant smell.<span class=\"note\">Or “a fragrant offering”</span>'),
('LEB', 'Ephesians', '5', '3', '1', 'But sexual immorality, and all uncleanness, or greediness, must not even be named among you (as is fitting for saints),'),
('LEB', 'Ephesians', '5', '4', '1', 'and obscenity, and foolish talk, or coarse jesting (which <span class=\"supplied\">are</span> not proper), but rather thanksgiving.'),
('LEB', 'Ephesians', '5', '5', '1', 'For this you know <span class=\"idiom\">for certain</span><span class=\"note\">Literally “for this you know, knowing”</span>, that every sexually immoral <span class=\"supplied\">person</span>, or unclean <span class=\"supplied\">person</span>, or greedy <span class=\"supplied\">person</span> (who is an idolater), does not have an inheritance in the kingdom of Christ and God.'),
('LEB', 'Ephesians', '5', '6', '1', 'Let no one deceive you with empty words, for because of these <span class=\"supplied\">things</span> the wrath of God is coming on the sons of disobedience.'),
('LEB', 'Ephesians', '5', '7', '3', '<span class=\"verse-title\">Walk Like Children of Light</span>Therefore do not be sharers<span class=\"note\">Or “partners”</span>with them,'),
('LEB', 'Ephesians', '5', '8', '3', 'for you were formerly darkness, but now <span class=\"supplied\">you are</span> light in the Lord. Live like children of light'),
('LEB', 'Ephesians', '5', '9', '3', '(for the fruit of the light <span class=\"supplied\">is</span> in all goodness and righteousness and truth),'),
('LEB', 'Ephesians', '5', '10', '3', 'trying to learn what is well-pleasing to the Lord.'),
('LEB', 'Ephesians', '5', '11', '3', 'And do not participate in the unfruitful deeds of darkness, but rather even expose <span class=\"supplied\">them</span>.'),
('LEB', 'Ephesians', '5', '12', '3', 'For it is shameful even to speak <span class=\"supplied\">about</span> the things being <span class=\"supplied\">done</span> by them in secret,'),
('LEB', 'Ephesians', '5', '13', '3', 'but all <span class=\"supplied\">things</span> exposed by the light are made visible,'),
('LEB', 'Ephesians', '5', '14', '3', 'for everything made visible is light. Therefore it says, Wake up, sleeper,  and rise from the dead,  and Christ will shine on you.<span class=\"note\">A quotation of unknown origin with possible allusions to Isa 26:19, 51:17, 52:1, 60:1</span>'),
('LEB', 'Ephesians', '5', '15', '5', 'Therefore, consider carefully how you live, not as unwise but as wise,'),
('LEB', 'Ephesians', '5', '16', '5', 'making the most of the time because the days are evil.'),
('LEB', 'Ephesians', '5', '17', '7', '<span class=\"verse-title\">Being Filled by the Spirit</span>Because of this do not become foolish, but understand what the will of the Lord <span class=\"supplied\">is</span>.'),
('LEB', 'Ephesians', '5', '18', '7', 'And do not be drunk with wine (in which is dissipation), but be filled by the Spirit,'),
('LEB', 'Ephesians', '5', '19', '7', 'speaking to one another in psalms and hymns and spiritual songs, singing and singing praise in your heart to the Lord,'),
('LEB', 'Ephesians', '5', '20', '7', 'giving thanks always for all <span class=\"supplied\">things</span> in the name of our Lord Jesus Christ to the God and Father,'),
('LEB', 'Ephesians', '5', '21', '7', 'being subject to one another <span class=\"idiom\">out of reverence for</span><span class=\"note\">Literally “in <span class=\"supplied\">the</span> fear of”</span>Christ'),
('LEB', 'Ephesians', '5', '22', '7', '—wives to their own husbands as to the Lord,'),
('LEB', 'Ephesians', '5', '23', '7', 'because <span class=\"supplied\">the</span> husband is <span class=\"supplied\">the</span> head of the wife, as also Christ <span class=\"supplied\">is the</span> head of the church (he himself <span class=\"supplied\">being the</span> Savior of the body).'),
('LEB', 'Ephesians', '5', '24', '7', 'But as the church is subject to Christ, thus also wives <span class=\"supplied\">should be subject</span>to their husbands in everything.'),
('LEB', 'Ephesians', '5', '25', '9', '<span class=\"verse-title\">Husbands and Wives</span>Husbands, love your wives, just as Christ also loved the church, and gave himself for her;'),
('LEB', 'Ephesians', '5', '26', '9', 'in order that he might sanctify her by cleansing <span class=\"supplied\">her</span>with the washing of water by the word;'),
('LEB', 'Ephesians', '5', '27', '9', 'in order that he might present to himself the church glorious, not having a spot or wrinkle or any such <span class=\"supplied\">thing</span>, but that she may be holy and blameless.'),
('LEB', 'Ephesians', '5', '28', '9', 'Thus also husbands ought to love their own wives as their own bodies. The one who loves his own wife loves himself.'),
('LEB', 'Ephesians', '5', '29', '9', 'For no one ever hated his own flesh, but nourishes and cherishes it, just as also Christ <span class=\"supplied\">does</span> the church,'),
('LEB', 'Ephesians', '5', '30', '9', 'because we are members of his body.'),
('LEB', 'Ephesians', '5', '31', '9', '“For this <span class=\"supplied\">reason</span> a man will leave his father and mother and be joined to his wife, and the two will become one flesh.”<span class=\"note\">A quotation from Gen 2:24</span>'),
('LEB', 'Ephesians', '5', '32', '9', '(This mystery is great, but I am speaking with reference to Christ and the church.)'),
('LEB', 'Ephesians', '5', '33', '9', 'Only you also, each one <span class=\"supplied\">of you</span>, must thus love his own wife as himself, and the wife <span class=\"idiom\">must respect</span><span class=\"note\">Literally “that she fear”</span>her husband.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ephesians', '6', '1', '1', '<span class=\"verse-title\">Children and Parents</span>Children, obey your parents in the Lord, for this is right.'),
('LEB', 'Ephesians', '6', '2', '1', '“Honor your father and mother” (which is the first<span class=\"note\">Or “is a very important”</span>commandment with a promise),'),
('LEB', 'Ephesians', '6', '3', '1', '“in order that it may be well with you, and you may <span class=\"idiom\">live a long time</span><span class=\"note\">Literally “be long-lived”</span>on the earth.”'),
('LEB', 'Ephesians', '6', '4', '1', 'And fathers, do not make your children angry, but bring them up in the discipline and instruction of the Lord.'),
('LEB', 'Ephesians', '6', '5', '3', '<span class=\"verse-title\">Slaves and Masters</span>Slaves, obey your earthly masters with fear and trembling, in the sincerity of your heart, as to Christ,'),
('LEB', 'Ephesians', '6', '6', '3', 'not <span class=\"idiom\">while being watched</span><span class=\"note\">Literally “with eye service”</span>, as people pleasers, but as slaves of Christ doing the will of God from the heart,'),
('LEB', 'Ephesians', '6', '7', '3', 'serving with goodwill as to the Lord and not to people,'),
('LEB', 'Ephesians', '6', '8', '3', '<span class=\"supplied\">because you</span>know that each one of you, whatever good he should do,<span class=\"note\">Some manuscripts have “if he should do anything good”</span>this he will receive back from the Lord, whether slave or free.'),
('LEB', 'Ephesians', '6', '9', '3', 'And masters, do the same <span class=\"supplied\">things</span> to them, giving up threats, knowing that both their Lord and yours is in heaven, and there is no partiality with him.'),
('LEB', 'Ephesians', '6', '10', '5', '<span class=\"verse-title\">Spiritual Warfare</span>Finally, become strong in the Lord and in the might of his strength.'),
('LEB', 'Ephesians', '6', '11', '5', 'Put on the full armor of God, so that you may be able to stand against the stratagems of the devil,'),
('LEB', 'Ephesians', '6', '12', '5', 'because our struggle is not against blood and flesh, but against the rulers, against the authorities, against the world rulers of this darkness, against the spiritual <span class=\"supplied\">forces</span> of wickedness in the heavenly <span class=\"supplied\">places</span>.'),
('LEB', 'Ephesians', '6', '13', '5', 'Because of this, take up the full armor of God, in order that you may be able to resist in the evil day, and having done everything, to stand.'),
('LEB', 'Ephesians', '6', '14', '5', 'Stand therefore, girding your waist with truth, and putting on the breastplate of righteousness,'),
('LEB', 'Ephesians', '6', '15', '5', 'and binding <span class=\"supplied\">shoes</span> under your feet with the preparation of the good news of peace,'),
('LEB', 'Ephesians', '6', '16', '5', 'in everything taking up the shield of faith, with which you are able to quench all the flaming arrows of the evil one,'),
('LEB', 'Ephesians', '6', '17', '5', 'and receive the helmet of salvation, and the sword of the Spirit, which is the word of God,'),
('LEB', 'Ephesians', '6', '18', '5', 'with all prayer and supplication praying at all times in the Spirit, and to this <span class=\"supplied\">end</span> being alert with all perseverance and supplication for all the saints,'),
('LEB', 'Ephesians', '6', '19', '5', 'and for me, that a word may be given to me at the opening of my mouth, to make known with boldness the mystery of the gospel,'),
('LEB', 'Ephesians', '6', '20', '5', 'for the sake of which I am an ambassador in chains, that <span class=\"idiom\">in them</span><span class=\"note\">Literally “in it” since “chain” is singular in the Greek text</span>I may speak freely, as it is necessary for me to speak.'),
('LEB', 'Ephesians', '6', '21', '7', '<span class=\"verse-title\">Conclusion and Benediction</span>Now, so that you also may know <span class=\"idiom\">my circumstances</span><span class=\"note\">Literally “the things with me”</span>, what I am doing, Tychicus, my dear brother and faithful servant in the Lord, will make known to you all <span class=\"supplied\">things</span>,'),
('LEB', 'Ephesians', '6', '22', '7', 'whom I have sent<span class=\"note\">Or “whom I am sending”</span>to you for this very <span class=\"supplied\">reason</span>, that you may know <span class=\"idiom\">our circumstances</span><span class=\"note\">Literally “the things concerning us”</span>, and he may encourage your hearts.'),
('LEB', 'Ephesians', '6', '23', '8', 'Peace to the brothers and love with faith, from God the Father and the Lord Jesus Christ.'),
('LEB', 'Ephesians', '6', '24', '8', 'Grace <span class=\"supplied\">be</span> with all who love our Lord Jesus Christ in incorruptibility.<span class=\"note\">Or “with undying love”</span>')
;

