INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Galatians', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, an apostle not from men nor by men but through Jesus Christ and God the Father who raised him from the dead,'),
('LEB', 'Galatians', '1', '2', '1', 'and all the brothers with me, to the churches of Galatia.'),
('LEB', 'Galatians', '1', '3', '1', 'Grace to you and peace from God the Father and our Lord Jesus Christ,<span class=\"note\">Some manuscripts have “God our Father and the Lord Jesus Christ”</span>'),
('LEB', 'Galatians', '1', '4', '1', 'who gave himself for our sins in order to rescue us from the present evil age, according to the will of our God and Father,'),
('LEB', 'Galatians', '1', '5', '1', 'to whom <span class=\"supplied\">be</span> the glory forever and ever. Amen.'),
('LEB', 'Galatians', '1', '6', '3', '<span class=\"verse-title\">A Different Gospel</span>I am astonished that you are turning away so quickly from the one who called you by the grace of Christ to a different gospel,'),
('LEB', 'Galatians', '1', '7', '3', 'not that <span class=\"supplied\">there</span> is a different <span class=\"supplied\">gospel</span>, except there are some who are disturbing you and wanting to distort the gospel of Christ.'),
('LEB', 'Galatians', '1', '8', '3', 'But even if we or an angel from heaven should proclaim a gospel to you contrary to what we proclaimed to you, let him be accursed!'),
('LEB', 'Galatians', '1', '9', '3', 'As we said before, and now I say again, if anyone is proclaiming a gospel <span class=\"supplied\">to</span> you contrary to what you have received, let him be accursed!'),
('LEB', 'Galatians', '1', '10', '3', 'For am I now making an appeal to people or <span class=\"supplied\">to</span> God? Or am I seeking to please people? If I were still trying to please people, I would not be a slave of Christ.'),
('LEB', 'Galatians', '1', '11', '5', '<span class=\"verse-title\">Paul’s Defense of His Apostleship</span>For I make known to you, brothers, the gospel that has been proclaimed by me, that it is not <span class=\"idiom\">of human origin</span><span class=\"note\">Literally “according to man”</span>.'),
('LEB', 'Galatians', '1', '12', '5', 'For neither did I receive it from man, nor was I taught <span class=\"supplied\">it</span>, but <span class=\"supplied\">I received it</span> through a revelation of Jesus Christ.'),
('LEB', 'Galatians', '1', '13', '5', 'For you have heard about my former way of life in Judaism, that to an extraordinary degree I was persecuting the church of God, and trying to destroy it,'),
('LEB', 'Galatians', '1', '14', '5', 'and was progressing in Judaism beyond many contemporaries in my nation, <span class=\"supplied\">because</span>I was a far more zealous adherent of the traditions handed down by my forefathers.'),
('LEB', 'Galatians', '1', '15', '6', 'But when the one who set me apart<span class=\"note\">Some manuscripts have “when God who set me apart”</span>from my mother’s womb and called <span class=\"supplied\">me</span> by his grace was pleased'),
('LEB', 'Galatians', '1', '16', '6', 'to reveal his Son in me in order that I would proclaim the gospel <span class=\"supplied\">about</span> him among the Gentiles, immediately I did not consult with flesh and blood,'),
('LEB', 'Galatians', '1', '17', '6', 'nor did I go up to Jerusalem to those <span class=\"supplied\">who were</span> apostles before me, but I went away to Arabia and I returned again to Damascus.'),
('LEB', 'Galatians', '1', '18', '6', 'Then after three years I went up to Jerusalem to become acquainted with Cephas, and I stayed with him fifteen days,'),
('LEB', 'Galatians', '1', '19', '6', 'but I did not see <span class=\"supplied\">any</span> others of the apostles except James, the brother of the Lord.'),
('LEB', 'Galatians', '1', '20', '6', '(Now <span class=\"supplied\">the things</span> which I am writing to you, behold, <span class=\"supplied\">I assure you</span> before God that I am not lying.)'),
('LEB', 'Galatians', '1', '21', '6', 'Then I came to the regions of Syria and of Cilicia,'),
('LEB', 'Galatians', '1', '22', '6', 'but I was unknown <span class=\"idiom\">in person</span><span class=\"note\">Literally “by face”</span>to the churches of Judea <span class=\"supplied\">that are</span> in Christ,'),
('LEB', 'Galatians', '1', '23', '6', 'and they were only hearing, “The one formerly persecuting us is now proclaiming the faith that formerly he was attempting to destroy,”'),
('LEB', 'Galatians', '1', '24', '6', 'and they were glorifying God because of me.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Galatians', '2', '1', '1', '<span class=\"verse-title\">Paul’s Ministry Recognized by the Jerusalem Apostles</span>Then after fourteen years I went up again to Jerusalem with Barnabas, taking along Titus also.'),
('LEB', 'Galatians', '2', '2', '1', 'Now I went up <span class=\"supplied\">there</span> because of a revelation and laid out to them the gospel that I preach among the Gentiles, but in private to the influential people, lest somehow I was running, or had run, in vain.'),
('LEB', 'Galatians', '2', '3', '1', 'But not even Titus <span class=\"supplied\">who was</span> with me, <span class=\"supplied\">although</span>he was a Greek, was compelled to be circumcised.'),
('LEB', 'Galatians', '2', '4', '1', 'Now <span class=\"supplied\">this was</span> because of the false brothers secretly brought in, who slipped in to spy out our freedom that we have in Christ Jesus, in order that they might enslave us,'),
('LEB', 'Galatians', '2', '5', '1', 'to whom not even for an hour did we yield in subjection, in order that the truth of the gospel might remain continually with you.'),
('LEB', 'Galatians', '2', '6', '1', 'But from those <span class=\"idiom\">who were influential</span><span class=\"note\">Literally “who were thought to be something”</span>(whatever they were, <span class=\"supplied\">it makes</span> no difference to me, <span class=\"idiom\">God does not show partiality</span><span class=\"note\">Literally “God does not receive the face of man”</span>)—for those who were influential added nothing to me.'),
('LEB', 'Galatians', '2', '7', '1', 'But these, <span class=\"supplied\">when they</span>saw that I had been entrusted <span class=\"supplied\">with</span> the gospel to the uncircumcision, just as Peter to the circumcision'),
('LEB', 'Galatians', '2', '8', '1', '(for the one who was at work through Peter for <span class=\"supplied\">his</span> apostleship to the circumcision was at work also through me for the Gentiles),'),
('LEB', 'Galatians', '2', '9', '1', 'and <span class=\"supplied\">when</span> James and Cephas and John—those thought to be pillars—acknowledged the grace given to me, they gave to me and Barnabas the right <span class=\"supplied\">hand</span> of fellowship, in order that we <span class=\"supplied\">should go</span> to the Gentiles and they to the circumcision.'),
('LEB', 'Galatians', '2', '10', '1', '<span class=\"supplied\">They asked</span> only that we should remember the poor, the very thing I was also eager to do.'),
('LEB', 'Galatians', '2', '11', '3', '<span class=\"verse-title\">Paul Confronts Peter at Antioch</span>But when Cephas came to Antioch, I opposed <span class=\"supplied\">him</span> to his face, because he was condemned.'),
('LEB', 'Galatians', '2', '12', '3', 'For before certain people came from James, he used to eat with the Gentiles, but when they came, he withdrew and separated himself, <span class=\"supplied\">because he</span>was afraid of those <span class=\"supplied\">who were</span> of the circumcision,'),
('LEB', 'Galatians', '2', '13', '3', 'and the rest of the Jews also joined in <span class=\"supplied\">this</span> hypocrisy with him, so that even Barnabas was carried away with them in <span class=\"supplied\">their</span> hypocrisy.'),
('LEB', 'Galatians', '2', '14', '3', 'But when I saw that they were not being straightforward with the truth of the gospel, I said to Cephas in the presence of <span class=\"supplied\">them</span> all, “If you, <span class=\"supplied\">although you</span>are a Jew, live like a Gentile and not like a Jew, how can you try to compel the Gentiles to live like Jews?”'),
('LEB', 'Galatians', '2', '15', '5', '<span class=\"verse-title\">Justified by Faith in Christ</span>We <span class=\"supplied\">are</span> Jews by nature and not sinners from among the Gentiles,'),
('LEB', 'Galatians', '2', '16', '5', 'but knowing that a person is not justified by the works of the law, if not by faith in Jesus Christ,<span class=\"note\">Or “by the faithfulness of Jesus Christ”</span>and we have believed in Christ Jesus so that we may be justified by faith in Christ<span class=\"note\">Or “by the faithfulness of Christ”</span>and not by the works of the law, because by the works of the law <span class=\"idiom\">no human being will be justified</span><span class=\"note\">Literally “all flesh will not be justified”</span>.'),
('LEB', 'Galatians', '2', '17', '5', 'But if <span class=\"supplied\">while</span> seeking to be justified by Christ, <span class=\"supplied\">we</span> ourselves also have been found <span class=\"supplied\">to be</span> sinners, then <span class=\"supplied\">is</span> Christ an agent of sin? May it never be!'),
('LEB', 'Galatians', '2', '18', '5', 'For if I build up again these <span class=\"supplied\">things</span> which I destroyed, I show myself <span class=\"supplied\">to be</span> a transgressor.'),
('LEB', 'Galatians', '2', '19', '5', 'For through the law I died to the law, in order that I might live to God. I have been crucified with Christ,'),
('LEB', 'Galatians', '2', '20', '5', 'and I no longer live, but Christ lives in me, and that <span class=\"supplied\">life</span> I now live in the flesh, I live by faith in the Son of God, who loved me and gave himself for me.'),
('LEB', 'Galatians', '2', '21', '5', 'I do not declare invalid the grace of God, for if righteousness <span class=\"supplied\">is</span> through the law, then Christ died to no purpose.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Galatians', '3', '1', '1', '<span class=\"verse-title\">Justified by the Law, or Justified by Faith?</span>O foolish Galatians, who has bewitched you, before whose eyes Jesus Christ was publicly portrayed <span class=\"supplied\">as</span> having been crucified?'),
('LEB', 'Galatians', '3', '2', '1', 'I want only to learn this from you: Did you receive the Spirit by the works of the law, or by the hearing of faith?'),
('LEB', 'Galatians', '3', '3', '1', 'Are you so foolish? Having begun by the Spirit, are you now trying to be made complete by the flesh?'),
('LEB', 'Galatians', '3', '4', '1', 'Have you suffered so many <span class=\"supplied\">things</span> for nothing—if indeed also <span class=\"supplied\">it was</span> for nothing?'),
('LEB', 'Galatians', '3', '5', '1', 'Therefore does the one who gives you the Spirit and who works miracles among you <span class=\"supplied\">do so</span> by the works of the law, or by the hearing of faith?'),
('LEB', 'Galatians', '3', '6', '2', 'Just as Abraham believed God, and it was credited to him for righteousness,'),
('LEB', 'Galatians', '3', '7', '2', 'then understand that the ones <span class=\"idiom\">who have faith</span><span class=\"note\">Literally “of faith”</span>, these are sons of Abraham.'),
('LEB', 'Galatians', '3', '8', '2', 'And the scripture, foreseeing that God would justify the Gentiles by faith, proclaimed the good news in advance to Abraham: “In you all the nations<span class=\"note\">Or “Gentiles”; the same Greek word can be translated “nations” or “Gentiles” depending on the context</span>will be blessed.”'),
('LEB', 'Galatians', '3', '9', '2', 'So then, the ones <span class=\"supplied\">who have</span> faith are blessed together with Abraham who believed.'),
('LEB', 'Galatians', '3', '10', '2', 'For as many as are of the works of the law are under a curse, for it is written, “Cursed <span class=\"supplied\">is</span> everyone who does not abide by all <span class=\"supplied\">the things</span> that are written in the book of the law to do them.”'),
('LEB', 'Galatians', '3', '11', '2', 'Now <span class=\"supplied\">it is</span> clear that no one is justified in the sight of God by the law, because “the one who is righteous will live by faith.”<span class=\"note\">Or “the one who is righteous by faith will live,” a quotation from Hab 2:4</span>'),
('LEB', 'Galatians', '3', '12', '2', 'But the law is not from faith, but “the one who does these <span class=\"supplied\">things</span> will live by them.”<span class=\"note\">A quotation from Lev 18:5</span>'),
('LEB', 'Galatians', '3', '13', '3', 'Christ redeemed us from the curse of the law <span class=\"supplied\">by</span>becoming a curse for us, because it is written, “Cursed <span class=\"supplied\">is</span> everyone who hangs on a tree,”'),
('LEB', 'Galatians', '3', '14', '3', 'in order that the blessing of Abraham might come to the Gentiles in Christ Jesus, so that we might receive the promise of the Spirit through faith.'),
('LEB', 'Galatians', '3', '15', '5', '<span class=\"verse-title\">The Promise to Abraham and His Descendant</span>Brothers, I am speaking according to a human perspective. Nevertheless, <span class=\"supplied\">when</span>the covenant of a man has been ratified, no one declares <span class=\"supplied\">it</span> invalid or adds additional provisions <span class=\"supplied\">to it</span>.'),
('LEB', 'Galatians', '3', '16', '5', 'Now to Abraham and to his descendant the promises were spoken. It does not say, “and to descendants,” as concerning many, but as concerning one, “and to your descendant,”who is Christ.'),
('LEB', 'Galatians', '3', '17', '5', 'Now I am saying this: the law, that came after four hundred and thirty years, does not revoke a covenant previously ratified by God, in order to nullify the promise.'),
('LEB', 'Galatians', '3', '18', '5', 'For if the inheritance <span class=\"supplied\">is</span> from the law, <span class=\"supplied\">it is</span> no longer from the promise, but God graciously gave <span class=\"supplied\">it</span> to Abraham through the promise.'),
('LEB', 'Galatians', '3', '19', '7', '<span class=\"verse-title\">The Addition of the Law</span>Why then the law? It was added on account of transgressions, until the descendant should come to whom it had been promised, having been ordered through angels by the hand of a mediator.'),
('LEB', 'Galatians', '3', '20', '7', 'Now the mediator is not for one, but God is one.'),
('LEB', 'Galatians', '3', '21', '8', 'Therefore <span class=\"supplied\">is</span> the law opposed to the promises of God? May it never be! For if a law had been given that was able to give life, certainly righteousness would have been from the law.'),
('LEB', 'Galatians', '3', '22', '8', 'But the scripture imprisoned all under sin, in order that the promise could be given by faith<span class=\"note\">Or “through the faithfulness of Jesus Christ”</span>in Jesus Christ to those who believe.'),
('LEB', 'Galatians', '3', '23', '9', 'But before faith came, we were detained under the law, imprisoned until the coming faith was revealed.'),
('LEB', 'Galatians', '3', '24', '9', 'So then, the law became our guardian until Christ, in order that we could be justified by faith.'),
('LEB', 'Galatians', '3', '25', '9', 'But <span class=\"supplied\">after</span>faith has come, we are no longer under a guardian.'),
('LEB', 'Galatians', '3', '26', '9', 'For you are all sons of God through faith in Christ Jesus,<span class=\"note\">Or “For in Christ Jesus you are all sons of God through faith”</span>'),
('LEB', 'Galatians', '3', '27', '9', 'for as many <span class=\"supplied\">of you</span> as were baptized into Christ have put on Christ.'),
('LEB', 'Galatians', '3', '28', '9', 'There is neither Jew nor Greek, there is neither slave nor free, there is neither male and female, for you are all one in Christ Jesus.'),
('LEB', 'Galatians', '3', '29', '9', 'And if you <span class=\"supplied\">are</span> Christ’s, then you are descendants of Abraham, heirs according to the promise.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Galatians', '4', '1', '1', '<span class=\"verse-title\">No Longer Slaves But Sons and Heirs</span>Now I say, for as long a time <span class=\"supplied\">as</span> the heir is a child, <span class=\"supplied\">he is</span> no different from a slave, <span class=\"supplied\">although he</span>is master of everything,'),
('LEB', 'Galatians', '4', '2', '1', 'but he is under guardians and managers until the time set by <span class=\"supplied\">his</span> father.'),
('LEB', 'Galatians', '4', '3', '1', 'So also we, when we were children, we were enslaved under the elemental spirits of the world.'),
('LEB', 'Galatians', '4', '4', '1', 'But when the fullness of time came, God sent out his Son, born of a woman, born under the law,'),
('LEB', 'Galatians', '4', '5', '1', 'in order that he might redeem those under the law, in order that we might receive the adoption.'),
('LEB', 'Galatians', '4', '6', '1', 'And because you are sons, God sent out the Spirit of his Son into our hearts, crying out, “Abba!<span class=\"note\">“Abba” is Aramaic for “father”</span>(Father!),”'),
('LEB', 'Galatians', '4', '7', '1', 'so that you are no longer a slave but a son, and if a son, also an heir through God.'),
('LEB', 'Galatians', '4', '8', '3', '<span class=\"verse-title\">Do Not Be Enslaved Again</span>But at that time <span class=\"supplied\">when you</span>did not know God, you were enslaved to the things which by nature are not gods.'),
('LEB', 'Galatians', '4', '9', '3', 'But now, <span class=\"supplied\">because you</span> have come to know God, or rather have come to be known by God, how can you turn back again to the weak and miserable elemental spirits? Do you want to be enslaved to them<span class=\"note\">Literally “to whom”</span>all over again?'),
('LEB', 'Galatians', '4', '10', '3', 'You carefully observe days and months and seasons and years.'),
('LEB', 'Galatians', '4', '11', '3', 'I am afraid <span class=\"supplied\">for</span> you, lest perhaps I have labored for you in vain!'),
('LEB', 'Galatians', '4', '12', '3', 'I ask you, brothers, become like me, because I also <span class=\"supplied\">have become</span> like you. You have done me no <span class=\"supplied\">wrong</span>!'),
('LEB', 'Galatians', '4', '13', '5', '<span class=\"verse-title\">Paul’s Personal Appeal</span>But you know that because of an illness of the flesh I proclaimed the gospel to you the first time.'),
('LEB', 'Galatians', '4', '14', '5', 'And you did not despise or disdain <span class=\"supplied\">what was</span> a trial for you in my flesh, but you welcomed me like an angel of God, like Christ Jesus.'),
('LEB', 'Galatians', '4', '15', '5', 'So where <span class=\"supplied\">is</span> your blessing? For I testify to you that, if possible, you would have torn out your eyes <span class=\"supplied\">and</span> given <span class=\"supplied\">them</span> to me!'),
('LEB', 'Galatians', '4', '16', '5', 'So then, have I become your enemy <span class=\"supplied\">by</span>being truthful to you?'),
('LEB', 'Galatians', '4', '17', '5', 'They zealously seek you, not commendably, but they want to exclude you, in order that you may seek them <span class=\"supplied\">zealously</span>.'),
('LEB', 'Galatians', '4', '18', '5', 'But <span class=\"supplied\">it is</span> good to be sought zealously in good at all times, and not only when I am present with you.'),
('LEB', 'Galatians', '4', '19', '5', 'My children, for whom I am having birth pains again, until Christ is formed in you!'),
('LEB', 'Galatians', '4', '20', '5', 'But I could wish to be present with you now, and to change my tone because I am perplexed about you.'),
('LEB', 'Galatians', '4', '21', '7', '<span class=\"verse-title\">Hagar and Sarah Represent Two Covenants</span>Tell me, <span class=\"supplied\">you</span> who are wanting to be under the law, do you not understand<span class=\"note\">Literally “hear”</span>the law?'),
('LEB', 'Galatians', '4', '22', '7', 'For it is written that Abraham had two sons, one by the female slave and one by the free woman.'),
('LEB', 'Galatians', '4', '23', '7', 'But the one by the female slave was born according to human descent, and the one by the free woman through the promise,'),
('LEB', 'Galatians', '4', '24', '7', 'which <span class=\"supplied\">things</span> are spoken allegorically, for these <span class=\"supplied\">women</span> are two covenants, one from Mount Sinai, bearing <span class=\"supplied\">children</span> for slavery, who is Hagar.'),
('LEB', 'Galatians', '4', '25', '7', 'Now Hagar is Mount Sinai in Arabia, and corresponds to the present Jerusalem, for she is a slave with her children.'),
('LEB', 'Galatians', '4', '26', '7', 'But the Jerusalem above is free, which is our mother.'),
('LEB', 'Galatians', '4', '27', '7', 'For it is written, “Rejoice, O barren woman, who does not give birth to <span class=\"supplied\">children</span>;  burst out and shout, <span class=\"supplied\">you</span> who do not have birth pains,  because many <span class=\"supplied\">are</span> the children of the desolate <span class=\"supplied\">woman</span>,  even more than <span class=\"supplied\">those of</span> the one who has a husband.”'),
('LEB', 'Galatians', '4', '28', '9', 'But you, brothers, are children of the promise, just as Isaac.'),
('LEB', 'Galatians', '4', '29', '9', 'But just as at that time the <span class=\"supplied\">child</span> born according to human descent persecuted the <span class=\"supplied\">child born</span> according to the Spirit, so also now.'),
('LEB', 'Galatians', '4', '30', '9', 'But what does the scripture say? “Drive out the female slave and her son, for the son of the female slave will never inherit with the son”of the free woman.'),
('LEB', 'Galatians', '4', '31', '9', 'Therefore, brothers, we are not children of the female slave but of the free woman.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Galatians', '5', '1', '1', '<span class=\"verse-title\">Live in Freedom and Love One Another</span>For freedom Christ has set us free. Stand firm, therefore, and do not be subject again to a yoke of slavery.'),
('LEB', 'Galatians', '5', '2', '1', 'Look! I, Paul, tell you that if you become circumcised, Christ will profit you nothing!'),
('LEB', 'Galatians', '5', '3', '1', 'And again I testify to every man who becomes circumcised, that he is under obligation to keep the whole law.'),
('LEB', 'Galatians', '5', '4', '1', 'You are estranged from Christ, <span class=\"supplied\">you</span> who are attempting to be justifiedby the law; you have fallen from grace.'),
('LEB', 'Galatians', '5', '5', '1', 'For through the Spirit by faith we eagerly await the hope of righteousness.'),
('LEB', 'Galatians', '5', '6', '1', 'For in Christ Jesus neither circumcision counts for anything nor uncircumcision, but faith working through love.'),
('LEB', 'Galatians', '5', '7', '2', 'You were running well. Who hindered you from obeying the truth?'),
('LEB', 'Galatians', '5', '8', '2', 'This persuasion <span class=\"supplied\">is</span> not from the one who calls you!'),
('LEB', 'Galatians', '5', '9', '2', 'A little leaven leavens the whole batch of dough.'),
('LEB', 'Galatians', '5', '10', '2', 'I have confidence in you in the Lord that you will think nothing different, but the one who is confusing you <span class=\"idiom\">will pay the penalty</span><span class=\"note\">Literally “will bear the <span class=\"supplied\">= his</span> condemnation”</span>, whoever he may be.'),
('LEB', 'Galatians', '5', '11', '2', 'Now, brothers, if I am still preaching circumcision, why am I still being persecuted? In that case the stumbling block of the cross has been abolished.'),
('LEB', 'Galatians', '5', '12', '2', 'I wish that the ones who are disturbing you would also <span class=\"idiom\">castrate themselves</span><span class=\"note\">Literally “cut themselves off”</span>!'),
('LEB', 'Galatians', '5', '13', '3', 'For you were called to freedom, brothers. Only do not let your freedom <span class=\"supplied\">become</span> an opportunity for the flesh, but through love serve one another.'),
('LEB', 'Galatians', '5', '14', '3', 'For the whole law is fulfilled in one statement, namely, “You shall love your neighbor as yourself.”<span class=\"note\">A quotation from Lev 19:18</span>'),
('LEB', 'Galatians', '5', '15', '3', 'But if you bite and devour one another, watch out <span class=\"supplied\">that</span> you are not consumed by one another.'),
('LEB', 'Galatians', '5', '16', '5', '<span class=\"verse-title\">Live by the Spirit and Reject the Deeds of the Flesh</span>But I say, live by the Spirit, and you will never carry out the desire of the flesh.'),
('LEB', 'Galatians', '5', '17', '5', 'For the flesh desires against the Spirit, and the Spirit against the flesh, for these are in opposition to one another, so that whatever you want, you may not do these <span class=\"supplied\">things</span>.'),
('LEB', 'Galatians', '5', '18', '5', 'But if you are led by the Spirit, you are not under the law.'),
('LEB', 'Galatians', '5', '19', '6', 'Now the deeds of the flesh are evident, which are sexual immorality, impurity, licentiousness,'),
('LEB', 'Galatians', '5', '20', '6', 'idolatry, sorcery, enmity, strife, jealousy, outbursts of anger, selfish ambition, dissension, factions,'),
('LEB', 'Galatians', '5', '21', '6', 'envy, drunkenness, carousing, and things like these, <span class=\"supplied\">things</span> which I am telling you <span class=\"supplied\">in advance</span>, just as I said before, that the ones who practice such things will not inherit the kingdom of God.'),
('LEB', 'Galatians', '5', '22', '6', 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness,'),
('LEB', 'Galatians', '5', '23', '6', 'gentleness, self control. Against such things <span class=\"supplied\">there</span> is no law.'),
('LEB', 'Galatians', '5', '24', '6', 'Now those <span class=\"idiom\">who belong to Christ</span><span class=\"note\">Literally “of Christ”</span><span class=\"note\">Some manuscripts have “Christ Jesus”</span>have crucified the flesh together with its feelings and its desires.'),
('LEB', 'Galatians', '5', '25', '7', 'If we live by the Spirit, we must also follow the Spirit.'),
('LEB', 'Galatians', '5', '26', '7', 'We must not become conceited, provoking one another, envying one another.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Galatians', '6', '1', '1', '<span class=\"verse-title\">Carry One Another’s Burdens</span>Brothers, even if a person is caught in some trespass, you <span class=\"supplied\">who are</span> spiritual restore such a person in a spirit of humility, looking out for yourself, lest you also be tempted.'),
('LEB', 'Galatians', '6', '2', '1', 'Carry the burdens of one another, and so fulfill the law of Christ.'),
('LEB', 'Galatians', '6', '3', '1', 'For if anyone thinks he is something <span class=\"supplied\">although he</span>is nothing, he is deceiving himself.'),
('LEB', 'Galatians', '6', '4', '1', 'But let each one examine his own work, and then he will have a reason for boasting in himself alone, and not in someone else.'),
('LEB', 'Galatians', '6', '5', '1', 'For each one will carry his own burden.'),
('LEB', 'Galatians', '6', '6', '3', '<span class=\"verse-title\">Do Good to All People</span>Now the one who is taught the word must share in all good <span class=\"supplied\">things</span> with the one who teaches.'),
('LEB', 'Galatians', '6', '7', '3', 'Do not be deceived: God is not to be mocked, for whatever a person sows, this he will also reap,'),
('LEB', 'Galatians', '6', '8', '3', 'because the one who sows to his own flesh will reap corruption from the flesh, but the one who sows to the Spirit will reap eternal life from the Spirit.'),
('LEB', 'Galatians', '6', '9', '3', 'And let us not grow weary in doing good, for at the proper time we will reap, <span class=\"supplied\">if we</span>do not give up.'),
('LEB', 'Galatians', '6', '10', '3', 'So then, as we have opportunity, let us do good to all <span class=\"supplied\">people</span>, and especially to those who belong to the household of faith.'),
('LEB', 'Galatians', '6', '11', '5', '<span class=\"verse-title\">A Final Warning</span>See with what large letters I am writing to you with my <span class=\"supplied\">own</span> hand.'),
('LEB', 'Galatians', '6', '12', '5', 'As many as are wanting to make a good showing in the flesh, these are attempting to compelyou to be circumcised, only so that they will not be persecuted for the cross of Christ.'),
('LEB', 'Galatians', '6', '13', '5', 'For not even those who are circumcised observe the law themselves, but they want you to be circumcised in order that they may boast in your flesh.'),
('LEB', 'Galatians', '6', '14', '5', 'But <span class=\"supplied\">as</span> for me, may it never be <span class=\"supplied\">that I</span> boast, except in the cross of our Lord Jesus Christ, through whom the world has been crucified to me, and I to the world.'),
('LEB', 'Galatians', '6', '15', '5', 'For neither is circumcision anything nor uncircumcision, but a new creation.'),
('LEB', 'Galatians', '6', '16', '5', 'And all those who follow this rule, peace and mercy <span class=\"supplied\">be</span> on them and on the Israel of God.'),
('LEB', 'Galatians', '6', '17', '7', '<span class=\"verse-title\">Conclusion and Benediction</span>Finally, let no one cause me trouble, for I carry on my body the marks of Jesus.'),
('LEB', 'Galatians', '6', '18', '7', 'The grace of our Lord Jesus Christ <span class=\"supplied\">be</span> with your spirit, brothers. Amen.')
;

