INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'James', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>James, a slave of God and of the Lord Jesus Christ, to the twelve tribes in the dispersion. Greetings!'),
('LEB', 'James', '1', '2', '3', '<span class=\"verse-title\">Trials, Testing, and Faith</span>Consider <span class=\"supplied\">it</span> all joy, my brothers, whenever you encounter various trials,'),
('LEB', 'James', '1', '3', '3', '<span class=\"supplied\">because you</span>know that the testing of your faith produces endurance.'),
('LEB', 'James', '1', '4', '3', 'And let endurance have <span class=\"supplied\">its</span> perfect effect, so that you may be mature and complete, lacking in nothing.'),
('LEB', 'James', '1', '5', '4', 'Now if any of you lacks wisdom, let him ask for <span class=\"supplied\">it</span> from God, who gives to all without reservation and not reproaching, and it will be given to him.'),
('LEB', 'James', '1', '6', '4', 'But let him ask for <span class=\"supplied\">it</span> in faith, without any doubting, for the one who doubts is like the surf of the sea, driven by the wind and tossed about.'),
('LEB', 'James', '1', '7', '4', 'For that person must not suppose that he will receive anything from the Lord;'),
('LEB', 'James', '1', '8', '4', '<span class=\"supplied\">he is</span> a double-minded man, unstable in all his ways.'),
('LEB', 'James', '1', '9', '5', 'Now let the brother of humble circumstances boast in his high position,'),
('LEB', 'James', '1', '10', '5', 'but the rich person in his humiliation, because he will pass away like a flower of the grass.'),
('LEB', 'James', '1', '11', '5', 'For the sun rises with its burning heat and dries up the grass, and its flower falls off, and the beauty of its appearance is lost. So also the rich person in his pursuits<span class=\"note\">Or “on his (business) journeys”; or “in his ways”</span>will wither away.'),
('LEB', 'James', '1', '12', '6', 'Blessed <span class=\"supplied\">is</span> the person<span class=\"note\">Literally “the man,” but clearly in a generic sense here meaning “someone, a person”</span>who endures testing, because <span class=\"supplied\">when he</span>is approved he will receive the crown of life that he<span class=\"note\">Most manuscripts read “the Lord” here, while others read “God”</span>has promised to those who love him.'),
('LEB', 'James', '1', '13', '6', 'No one who is being tempted should say, “I am being tempted by God,” for God <span class=\"idiom\">cannot be tempted</span><span class=\"note\">Literally “is without temptation”</span>by evil, and he himself tempts no one.'),
('LEB', 'James', '1', '14', '6', 'But each one is tempted <span class=\"supplied\">when he</span>is dragged away and enticed by his own desires.'),
('LEB', 'James', '1', '15', '6', 'Then desire, <span class=\"supplied\">after it</span>has conceived, gives birth to sin, and sin, <span class=\"supplied\">when it</span>is brought to completion, gives birth to death.'),
('LEB', 'James', '1', '16', '7', 'Do not be deceived, my dear brothers.'),
('LEB', 'James', '1', '17', '7', 'Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom there is no variation or shadow of change.'),
('LEB', 'James', '1', '18', '7', '<span class=\"supplied\">By his</span>will he gave birth to us through the message of truth, so that we should be a kind of first fruits of his creatures.'),
('LEB', 'James', '1', '19', '9', '<span class=\"verse-title\">Doers of the Message, Not Just Hearers</span>Understand <span class=\"supplied\">this</span>, my dear brothers: every person must be quick to hear, slow to speak, slow to anger,'),
('LEB', 'James', '1', '20', '9', 'for human<span class=\"note\">Literally “man’s”</span>anger does not accomplish the righteousness of God.'),
('LEB', 'James', '1', '21', '9', 'Therefore, putting aside all moral uncleanness and wicked excess, welcome<span class=\"note\">Or “receive”</span>with humility the implanted message which is able to save your souls.'),
('LEB', 'James', '1', '22', '10', 'But be doers of the message and not hearers only,<span class=\"note\">Some manuscripts have “not only hearers”</span>deceiving yourselves,'),
('LEB', 'James', '1', '23', '10', 'because if anyone is a hearer of the message and not a doer, this one is like someone<span class=\"note\">Literally “a man,” but clearly in a generic sense here meaning “someone, a person”</span>staring at <span class=\"idiom\">his own face</span><span class=\"note\">Literally “the face of his existence”</span>in a mirror,'),
('LEB', 'James', '1', '24', '10', 'for he looks at himself and goes away and immediately forgets what sort of <span class=\"supplied\">person</span> he was.'),
('LEB', 'James', '1', '25', '10', 'But the one who looks into the perfect law of liberty and continues <span class=\"supplied\">to do it</span>, not being a forgetful hearer but a doer who acts, this one will be blessed <span class=\"idiom\">in what he does</span><span class=\"note\">Literally “in his doing”</span>.'),
('LEB', 'James', '1', '26', '11', 'If anyone thinks he is religious, <span class=\"supplied\">although he</span>does not bridle his tongue but deceives his heart, this person’s religion <span class=\"supplied\">is</span> worthless.'),
('LEB', 'James', '1', '27', '11', 'Pure and undefiled religion in the sight of ourGod and Father is this: to look after orphans and widows in their affliction, <span class=\"supplied\">and</span> to keep oneself unstained by the world.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'James', '2', '1', '1', '<span class=\"verse-title\">Partiality Forbidden</span>My brothers, do not hold your faith in our glorious Lord Jesus Christ with partiality.'),
('LEB', 'James', '2', '2', '1', 'For if someone<span class=\"note\">Literally “a man,” but clearly in a generic sense here meaning “someone, a person”</span>enters into your assembly<span class=\"note\">Literally “synagogue,” but here probably referring to a Christian assembly</span>in fine clothing with a gold ring on his finger, and a poor person in filthy clothing also enters,'),
('LEB', 'James', '2', '3', '1', 'and you look favorably on the one wearing the fine clothing and you say, “Be seated here in a good place,” and to the poor person you say, “You stand or be seated there<span class=\"note\">Some manuscripts have “you stand there or be seated”</span>by my footstool,”'),
('LEB', 'James', '2', '4', '1', 'have you not made distinctions among yourselves and become judges with evil thoughts?'),
('LEB', 'James', '2', '5', '1', 'Listen, my dear brothers! Did not God choose the poor of the world <span class=\"supplied\">to be</span> rich in faith, and heirs of the kingdom that he has promised to those who love him?'),
('LEB', 'James', '2', '6', '1', 'But you have dishonored the poor! Are not the rich exploiting you and they themselves dragging you into the courts?'),
('LEB', 'James', '2', '7', '1', 'Do they themselves not blaspheme the good name <span class=\"idiom\">of the one to whom you belong</span><span class=\"note\">Literally “that was called over you”</span>?'),
('LEB', 'James', '2', '8', '2', 'However, if you carry out the royal law according to the scripture, “You shall love your neighbor as yourself,”<span class=\"note\">A quotation from Lev 19:18</span>you are doing well.'),
('LEB', 'James', '2', '9', '2', 'But if you show partiality, you commit sin, <span class=\"supplied\">and thus</span>are convicted by the law as transgressors.'),
('LEB', 'James', '2', '10', '2', 'For whoever keeps the whole law but stumbles in one <span class=\"supplied\">point only</span> has become guilty of all <span class=\"supplied\">of it</span>.'),
('LEB', 'James', '2', '11', '2', 'For the one who said “Do not commit adultery”also said “Do not murder.”<span class=\"note\">A quotation from Exod 20:13; Deut 5:17</span>Now if you do not commit adultery but you do murder, you have become a transgressor of the law.'),
('LEB', 'James', '2', '12', '2', 'Thus speak and thus act as those who are going to be judged by the law of liberty.'),
('LEB', 'James', '2', '13', '2', 'For judgment <span class=\"supplied\">is</span> merciless to the one who has not practiced mercy. Mercy triumphs over judgment.'),
('LEB', 'James', '2', '14', '4', '<span class=\"verse-title\">Faith and Works</span>What <span class=\"supplied\">is</span> the benefit, my brothers, if someone says <span class=\"supplied\">that he</span> has faith but does not have works? That faith <span class=\"supplied\">is</span> not able to save him, <span class=\"supplied\">is it</span>?'),
('LEB', 'James', '2', '15', '4', 'If a brother or a sister is poorly clothed and lacking food for the day,'),
('LEB', 'James', '2', '16', '4', 'and one of you should say to them, “Go in peace, keep warm and <span class=\"idiom\">eat well</span><span class=\"note\">Literally, “be satisfied”</span>,” but does not give them what is necessary for the body, what <span class=\"supplied\">is</span> the benefit?'),
('LEB', 'James', '2', '17', '4', 'Thus also faith, if it does not have works, is dead by itself.'),
('LEB', 'James', '2', '18', '5', 'But someone will say, “You have faith and I have works.”<span class=\"note\">Some see the quotation by “someone” extending to the end of v. 18, while others see it extending through v. 19</span>Show me your faith apart from yourworks, and I will show you myfaith by my works.'),
('LEB', 'James', '2', '19', '5', 'You believe that God is one; you do well. Even the demons believe, and shudder!'),
('LEB', 'James', '2', '20', '5', 'But do you want to know, O foolish person, that faith apart from works is useless?'),
('LEB', 'James', '2', '21', '5', 'Was not Abraham our father justified by works <span class=\"supplied\">when he</span>offered up his son Isaac on the altar?'),
('LEB', 'James', '2', '22', '5', 'You see that faith was working together with his works, and by the works the faith was perfected.'),
('LEB', 'James', '2', '23', '5', 'And the scripture was fulfilled that says, “And Abraham believed God, and it was credited to him for righteousness,”<span class=\"note\">A quotation from Gen 15:6</span>and he was called God’s friend.'),
('LEB', 'James', '2', '24', '5', 'You see that a person is justified by works and not by faith alone.'),
('LEB', 'James', '2', '25', '5', 'And likewise was not Rahab the prostitute also justified by works <span class=\"supplied\">when she</span>welcomed the messengers and sent <span class=\"supplied\">them</span> out by a different route?'),
('LEB', 'James', '2', '26', '5', 'For just as the body without the spirit is dead, so also faith without works is dead.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'James', '3', '1', '1', '<span class=\"verse-title\">Restraining the Tongue</span>Not many should become teachers, my brothers, <span class=\"supplied\">because you</span>know that we will receive a greater judgment.<span class=\"note\">Or “greater condemnation”</span>'),
('LEB', 'James', '3', '2', '1', 'For we all stumble <span class=\"supplied\">in</span> many <span class=\"supplied\">ways</span>. If anyone does not stumble in what he says, he <span class=\"supplied\">is</span> a perfect individual,<span class=\"note\">Literally “man,” but clearly in a generic sense here meaning “someone, a person”</span>able to hold in check his whole body also.'),
('LEB', 'James', '3', '3', '1', 'And if we put bits in the mouths of horses so that they obey us, we also guide their whole bodies.'),
('LEB', 'James', '3', '4', '1', 'Behold also ships: <span class=\"supplied\">although they</span> are so large and are driven by strong winds, they are guided by a very small rudder wherever the inclination of the pilot wishes.'),
('LEB', 'James', '3', '5', '1', 'So also the tongue is a small member <span class=\"supplied\">of the body</span>and boasts great <span class=\"supplied\">things</span>. Behold how small a fire sets ablaze how great a forest!'),
('LEB', 'James', '3', '6', '1', 'And the tongue <span class=\"supplied\">is</span> a fire! The world of unrighteousness,<span class=\"note\">Or “a fire, the world of unrighteousness! The tongue is set among our members”</span>the tongue, is set among our members, defiling the whole body and setting on fire <span class=\"idiom\">the course of human existence</span><span class=\"note\">Literally “the wheel of origin”</span>, being set on fire by hell.'),
('LEB', 'James', '3', '7', '2', 'For every species of animals and birds, of reptiles and sea creatures, is being tamed and has been tamed by the human species,'),
('LEB', 'James', '3', '8', '2', 'but no human being is able to tame the tongue. <span class=\"supplied\">It is</span> a restless evil, full of deadly poison.'),
('LEB', 'James', '3', '9', '2', 'With it we bless theLord and Father, and with it we curse people who are made in the likeness of God.'),
('LEB', 'James', '3', '10', '2', 'From the same mouth come blessing and cursing. My brothers, these <span class=\"supplied\">things</span> ought not to be so!'),
('LEB', 'James', '3', '11', '2', 'A spring does not pour forth from the same opening fresh and bitter <span class=\"supplied\">water, does it</span>?'),
('LEB', 'James', '3', '12', '2', 'A fig tree is not able, my brothers, to produce olives, or a grapevine figs. Neither can a saltwater spring produce fresh water.'),
('LEB', 'James', '3', '13', '4', '<span class=\"verse-title\">The Wisdom That Comes Down from Above</span>Who <span class=\"supplied\">is</span> wise and understanding among you? Let him show by hisgood behavior his works, with the humility of wisdom.'),
('LEB', 'James', '3', '14', '4', 'But if you have bitter jealousy and selfish ambition in your hearts, do not boast and tell lies against the truth.'),
('LEB', 'James', '3', '15', '4', 'This is not the wisdom that comes down from above, but <span class=\"supplied\">is</span> earthly, unspiritual, demonic.'),
('LEB', 'James', '3', '16', '4', 'For where <span class=\"supplied\">there is</span> jealousy and selfish ambition, there <span class=\"supplied\">is</span> disorder and every evil practice.'),
('LEB', 'James', '3', '17', '4', 'But the wisdom from above is first pure, then peaceful, gentle, obedient, full of mercy and good fruits, nonjudgmental, without hypocrisy,'),
('LEB', 'James', '3', '18', '4', 'And the fruit of righteousness is sown in peace among<span class=\"note\">Or “for”; or possibly “by”</span>those who make peace.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'James', '4', '1', '1', '<span class=\"verse-title\">Subject Yourselves to God</span>From where <span class=\"supplied\">are</span> conflicts and from where <span class=\"supplied\">are</span> quarrels among you? <span class=\"supplied\">Is it</span> not from this, from your pleasures that wage war among your members?'),
('LEB', 'James', '4', '2', '1', 'You desire and do not have; you murder and are filled with envy, and are not able to obtain; you fight and quarrel. You do not have because you do not ask.'),
('LEB', 'James', '4', '3', '1', 'You ask and do not receive, because you ask with wrong motives, in order that you may spend <span class=\"supplied\">it</span> on your pleasures.'),
('LEB', 'James', '4', '4', '2', 'Adulterous people! Do you not know that friendship with the world is enmity with God? Therefore whoever wants to be a friend of the world makes <span class=\"supplied\">himself</span> an enemy of God.'),
('LEB', 'James', '4', '5', '2', 'Or do you think that in vain the scripture says, “The spirit which he caused to dwell in us desires jealously”?<span class=\"note\">This translation takes “spirit” to be the capacity within people that produces a divided mind and conflicts regarding God; other translations take this to refer to the Holy Spirit: “He (God) jealously desires the Spirit which he caused to dwell in us”</span>'),
('LEB', 'James', '4', '6', '2', 'But he gives greater grace. Therefore it says, “God opposes the proud,  but gives grace to the humble.”'),
('LEB', 'James', '4', '7', '4', 'Therefore subject yourselves to God. But resist the devil, and he will flee from you.'),
('LEB', 'James', '4', '8', '4', 'Draw near to God, and he will draw near to you. Cleanse <span class=\"supplied\">your</span> hands, <span class=\"supplied\">you</span> sinners, and purify <span class=\"supplied\">your</span> hearts, <span class=\"supplied\">you</span> double-minded!'),
('LEB', 'James', '4', '9', '4', 'Lament and mourn and weep! Let your laughter be turned to mourning, and yourjoy to gloominess.'),
('LEB', 'James', '4', '10', '4', 'Humble yourselves before the Lord, and he will exalt you.'),
('LEB', 'James', '4', '11', '5', 'Do not speak evil of one another, brothers. The one who speaks evil of a brother or judges his brother speaks evil of the law and judges the law. But if you judge the law, you are not a doer of the law but a judge <span class=\"supplied\">of the law</span>.<span class=\"note\">The words “of the law” are not in the Greek text, but are an understood repetition from the previous clause</span>'),
('LEB', 'James', '4', '12', '5', 'There is one lawgiver and judge who is able to save and to destroy. But who are you to judge yourneighbor?'),
('LEB', 'James', '4', '13', '7', '<span class=\"verse-title\">Arrogant Boasting About the Future</span>Come now, you who say, “Today or tomorrow we will travel to such and such a city and spend a year there, and carry on business and make a profit,”'),
('LEB', 'James', '4', '14', '7', 'you who do not know <span class=\"idiom\">what will happen tomorrow</span><span class=\"note\">Literally “the <span class=\"supplied\">circumstance</span> of tomorrow”</span>, <span class=\"idiom\">what your life will be like</span><span class=\"note\">Literally “of what sort your life”</span>. For you are a smoky vapor that appears for a short time and then disappears.'),
('LEB', 'James', '4', '15', '7', 'Instead you should say, “If the Lord wills, we will live and do this or that.”'),
('LEB', 'James', '4', '16', '7', 'But now you boast in your arrogance. All such boasting is evil.'),
('LEB', 'James', '4', '17', '7', 'Therefore, to the one who knows to do good and does not do <span class=\"supplied\">it</span>, to him it is sin.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'James', '5', '1', '1', '<span class=\"verse-title\">Woes on the Rich Who Oppress Others</span>Come now, you rich people, weep <span class=\"supplied\">and</span> cry aloud over the miseries that are coming upon you!'),
('LEB', 'James', '5', '2', '1', 'Your wealth has rotted, and your clothing has become moth-eaten.'),
('LEB', 'James', '5', '3', '1', 'Your gold and silver have become corroded, and their corrosion will be a witness against you, and it will consume your flesh like fire. You have stored up treasure in the last days.'),
('LEB', 'James', '5', '4', '1', 'Behold, the wages that were held back by you from the workers who reap your fields cry out, and the cries of the reapers have come to the ears of the Lord of hosts.'),
('LEB', 'James', '5', '5', '1', 'You have lived self-indulgently on the earth<span class=\"note\">Or “land”</span>and have lived luxuriously. You have fattened your hearts in the day of slaughter.'),
('LEB', 'James', '5', '6', '1', 'You have condemned, you have murdered the righteous <span class=\"supplied\">person</span>; he does not resist you.'),
('LEB', 'James', '5', '7', '3', '<span class=\"verse-title\">Exhortation to Patience</span>Therefore be patient, brothers, until the coming of the Lord. Behold, the farmer waits for the precious fruit of the soil, being patient concerning it until it receives the early and late rains.'),
('LEB', 'James', '5', '8', '3', 'You also be patient. Strengthen your hearts, because the coming of the Lord is near.'),
('LEB', 'James', '5', '9', '3', 'Brothers, do not complain against one another, in order that you may not be judged. Behold, the judge stands before the doors!'),
('LEB', 'James', '5', '10', '3', 'Brothers, take <span class=\"supplied\">as an</span> example of perseverance and endurance the prophets who spoke in the name of the Lord.'),
('LEB', 'James', '5', '11', '3', 'Behold, we consider blessed those who have endured. You have heard about the patient endurance of Job, and you saw the outcome from the Lord, that the Lord is compassionate and merciful.'),
('LEB', 'James', '5', '12', '3', 'Now above all, my brothers, do not swear either by heaven or by earth or by any other oath, but let your yes be yes and your no, no, in order that you may not fall under judgment.'),
('LEB', 'James', '5', '13', '5', '<span class=\"verse-title\">The Effective Prayer of Faith</span>Is anyone among you suffering misfortune? He should pray. Is anyone cheerful? He should sing praise.'),
('LEB', 'James', '5', '14', '5', 'Is anyone among you sick? He should summon the elders of the church and they should pray over him, anointing him with olive oil in the name of the Lord.'),
('LEB', 'James', '5', '15', '5', 'And the prayer of faith will save the one who is sick, and the Lord will raise him up, and if he has committed sins <span class=\"idiom\">he will be forgiven</span><span class=\"note\">Literally “it will be forgiven him”</span>.'),
('LEB', 'James', '5', '16', '5', 'Therefore confess your sins to one another, and pray for one another, so that you may be healed. The effective prayer of a righteous person accomplishes much.'),
('LEB', 'James', '5', '17', '5', 'Elijah was a human being<span class=\"note\">Literally “man,” but in a generic sense; the emphasis is not on Elijah’s masculine gender but his shared humanity</span>with the same nature as us, and <span class=\"idiom\">he prayed fervently</span><span class=\"note\">Literally “he prayed with prayer”</span>for <span class=\"supplied\">it</span> not to rain, and it did not rain on the land <span class=\"supplied\">for</span> three years and six months.'),
('LEB', 'James', '5', '18', '5', 'And he prayed again, and the sky gave rain and the earth produced its fruit.'),
('LEB', 'James', '5', '19', '6', 'My brothers, if anyone among you should wander away from the truth and someone turns him back,'),
('LEB', 'James', '5', '20', '6', 'he should know that the one who turns a sinner back from the error of his way will save that person’s<span class=\"note\">Literally “his,” but in context this refers to the sinner, not the person who turns the sinner back</span>soul from death, and will cover over a great number of sins.')
;

