INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Philemon', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, a prisoner of Christ Jesus, and Timothy our brother, to Philemon, our dear friend and fellow worker,'),
('LEB', 'Philemon', '1', '2', '1', 'and to Apphia our sister, and to Archippus our fellow soldier, and to the church in your house.'),
('LEB', 'Philemon', '1', '3', '1', 'Grace to you and peace from God our Father and the Lord Jesus Christ.'),
('LEB', 'Philemon', '1', '4', '3', '<span class=\"verse-title\">Thanksgiving and Prayer for Philemon</span>I thank my God, always making mention of you in my prayers,'),
('LEB', 'Philemon', '1', '5', '3', '<span class=\"supplied\">because I</span>hear about your love and faith which you have toward the Lord Jesus and for all the saints.'),
('LEB', 'Philemon', '1', '6', '3', '<span class=\"supplied\">I pray</span> that the fellowship of your faith may become effective in the knowledge <span class=\"supplied\">of</span> every good <span class=\"supplied\">thing</span> that <span class=\"supplied\">is</span> in us for Christ.'),
('LEB', 'Philemon', '1', '7', '3', 'For I have great joy and encouragement from your love, because the hearts of the saints have been refreshed through you, brother.'),
('LEB', 'Philemon', '1', '8', '5', '<span class=\"verse-title\">Paul’s Appeal for Onesimus</span>Therefore, <span class=\"supplied\">although I</span>have great confidence in Christ to order you <span class=\"supplied\">to do what</span> is proper,'),
('LEB', 'Philemon', '1', '9', '5', 'instead I appeal to <span class=\"supplied\">you</span> because of love, <span class=\"supplied\">since I</span>am such a one as Paul, now an old man and also a prisoner of Christ Jesus.'),
('LEB', 'Philemon', '1', '10', '5', 'I am appealing to you concerning my child whom I became the father of during my imprisonment, Onesimus.'),
('LEB', 'Philemon', '1', '11', '5', 'Once he <span class=\"supplied\">was</span> useless to you, but now <span class=\"supplied\">he is</span> useful to you<span class=\"note\">Some manuscripts have “both to you”</span>and to me,'),
('LEB', 'Philemon', '1', '12', '5', 'whom I have sent back to you himself, that is, my heart,'),
('LEB', 'Philemon', '1', '13', '5', 'whom I wanted to keep with me, in order that he might serve me on behalf of you during my imprisonment for the gospel.'),
('LEB', 'Philemon', '1', '14', '5', 'But apart from your consent, I wanted to do nothing, in order that your good <span class=\"supplied\">deed</span> might be not as according to necessity, but according to <span class=\"supplied\">your own</span> free will.'),
('LEB', 'Philemon', '1', '15', '5', 'For perhaps because of this, he was separated <span class=\"supplied\">from you</span> for a time, in order that you might have him back forever,'),
('LEB', 'Philemon', '1', '16', '5', 'no longer as a slave, but more than a slave, a beloved brother, especially to me, but how much more to you, both in the flesh and in the Lord.'),
('LEB', 'Philemon', '1', '17', '7', '<span class=\"verse-title\">Paul’s Request to Philemon</span>If therefore you consider me a partner, receive him as <span class=\"supplied\">you would</span> me.'),
('LEB', 'Philemon', '1', '18', '7', 'But if in anything he has caused you loss or owes <span class=\"supplied\">you anything</span>, <span class=\"idiom\">charge this to my account</span><span class=\"note\">“this to me charge to <span class=\"supplied\">my</span> account”</span>.'),
('LEB', 'Philemon', '1', '19', '7', 'I, Paul, write <span class=\"supplied\">this</span> with my <span class=\"supplied\">own</span> hand: I will pay it back, lest I mention to you that <span class=\"idiom\">you owe me even your very self besides</span><span class=\"note\">“even yourself to me you owe besides”</span>.'),
('LEB', 'Philemon', '1', '20', '7', 'Yes, brother, I ought to have some benefit of you in the Lord; refresh my heart in Christ.'),
('LEB', 'Philemon', '1', '21', '8', 'Confident of your obedience, I am writing to you <span class=\"supplied\">because I</span>know that you will do even beyond what I say.'),
('LEB', 'Philemon', '1', '22', '8', 'At the same time also, prepare a guest room for me, for I hope that through your prayers I will be restored to you.'),
('LEB', 'Philemon', '1', '23', '10', '<span class=\"verse-title\">Final Greetings and Benediction</span>Epaphras, my fellow prisoner in Christ Jesus, greets you,'),
('LEB', 'Philemon', '1', '24', '10', '<span class=\"supplied\">and so do</span> Mark, Aristarchus, Demas, <span class=\"supplied\">and</span> Luke, my fellow workers.'),
('LEB', 'Philemon', '1', '25', '10', 'The grace of the Lord Jesus Christ <span class=\"supplied\">be</span> with your spirit.')
;

