INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '1', '1', '1', '<span class=\"verse-title\">Greeting</span>Paul, a slave of Christ Jesus, called <span class=\"supplied\">to be</span> an apostle, set apart for the gospel of God,'),
('LEB', 'Romans', '1', '2', '1', 'which he promised previously through his prophets in the holy scriptures,'),
('LEB', 'Romans', '1', '3', '1', 'concerning his Son, who was born <span class=\"idiom\">a descendant</span><span class=\"note\">“of the seed”</span>of David according to the flesh,'),
('LEB', 'Romans', '1', '4', '1', 'who was declared Son of God in power according to <span class=\"idiom\">the Holy Spirit</span><span class=\"note\">“the Spirit of holiness”</span>by the resurrection from the dead of Jesus Christ our Lord,'),
('LEB', 'Romans', '1', '5', '1', 'through whom we have received grace and apostleship for the obedience of faith among all the Gentiles<span class=\"note\">Or “nations”; the same Greek word can be translated “nations” or “Gentiles” depending on the context</span>on behalf of his name,'),
('LEB', 'Romans', '1', '6', '1', 'among whom you also are <span class=\"supplied\">the</span> called of Jesus Christ.'),
('LEB', 'Romans', '1', '7', '1', 'To all those in Rome who are loved by God, called <span class=\"supplied\">to be</span> saints. Grace to you and peace from God our Father and the Lord Jesus Christ.'),
('LEB', 'Romans', '1', '8', '3', '<span class=\"verse-title\">Paul Wants to Visit Rome</span>First, I give thanks to my God through Jesus Christ for all of you, because your faith is being proclaimed in the whole world.'),
('LEB', 'Romans', '1', '9', '3', 'For God, whom I serve with my spirit in the gospel of his Son, is my witness, how constantly I make mention of you,'),
('LEB', 'Romans', '1', '10', '3', 'always asking in my prayers if somehow now at last I may succeed to come to you in the will of God.'),
('LEB', 'Romans', '1', '11', '3', 'For I desire to see you, in order that I may impart some spiritual gift to you, in order to strengthen you,'),
('LEB', 'Romans', '1', '12', '3', 'that is, to be encouraged together with you through <span class=\"idiom\">our mutual faith</span><span class=\"note\">“the in one another faith”</span>, both yours and mine.'),
('LEB', 'Romans', '1', '13', '3', 'Now I do not want you to be ignorant, brothers, that often I intended to come to you, and was prevented until now, in order that I might have some fruit among you also, just as also among the rest of the Gentiles.<span class=\"note\">Or “nations”; the same Greek word can be translated “nations” or “Gentiles” depending on the context</span>'),
('LEB', 'Romans', '1', '14', '3', 'I am under obligation both to Greeks and to barbarians, both to the wise and to the foolish.'),
('LEB', 'Romans', '1', '15', '3', 'Thus <span class=\"idiom\">I am eager</span><span class=\"note\">“the according to me eagerness”</span>to proclaim the gospel also to you who <span class=\"supplied\">are</span> in Rome.'),
('LEB', 'Romans', '1', '16', '5', '<span class=\"verse-title\">The Gospel’s Power for Salvation</span>For I am not ashamed of the gospel, for it is the power of God for salvation to everyone who believes, to the Jew first and also to the Greek.'),
('LEB', 'Romans', '1', '17', '5', 'For the righteousness of God is revealed in it from faith to faith, just as it is written, “But the one who is righteous by faith will live.”<span class=\"note\">Or “But the one who is righteous will live by faith” (differing only in word order)</span>'),
('LEB', 'Romans', '1', '18', '7', '<span class=\"verse-title\">God’s Wrath Revealed Against Sinful Humanity</span>For the wrath of God is revealed from heaven against all impiety and unrighteousness of people, who suppress the truth in unrighteousness,'),
('LEB', 'Romans', '1', '19', '7', 'because what can be known about God is evident among<span class=\"note\">Or “in”; or “within”</span>them, for God made <span class=\"supplied\">it</span> clear to them.'),
('LEB', 'Romans', '1', '20', '7', 'For from the creation of the world, his invisible <span class=\"supplied\">attributes</span>, both his eternal power and deity, are discerned clearly, being understood in the things created, so that they are without excuse.'),
('LEB', 'Romans', '1', '21', '7', 'For <span class=\"supplied\">although they</span> knew God, they did not honor <span class=\"supplied\">him</span> as God or give thanks, but they became futile in their reasoning, and their senseless hearts were darkened.'),
('LEB', 'Romans', '1', '22', '7', 'Claiming to be wise, they became fools,'),
('LEB', 'Romans', '1', '23', '7', 'and exchanged the glory of the immortal God with the likeness of an image of mortal human beings and birds and quadrupeds and reptiles.'),
('LEB', 'Romans', '1', '24', '8', 'Therefore God gave them over in the desires of their hearts to immorality, <span class=\"supplied\">that</span> their bodies would be dishonored among themselves,'),
('LEB', 'Romans', '1', '25', '8', 'who exchanged the truth of God with a lie, and worshiped and served the creation rather than the Creator, who is blessed for eternity. Amen.'),
('LEB', 'Romans', '1', '26', '10', '<span class=\"verse-title\">God Hands Sinful Humanity over to Depravity</span>Because of this, God gave them over to degrading passions, for their females exchanged the natural relations for those contrary to nature,'),
('LEB', 'Romans', '1', '27', '10', 'and likewise also the males, abandoning the natural relations with the female, were inflamed in their desire toward one another, males with males committing the shameless deed, and receiving in themselves the penalty that was necessary for their error.'),
('LEB', 'Romans', '1', '28', '10', 'And just as they did not see fit <span class=\"idiom\">to recognize God</span><span class=\"note\">“to have God in recognition”</span>, God gave them over to a debased mind, to do the things <span class=\"supplied\">that are</span> not proper,'),
('LEB', 'Romans', '1', '29', '10', 'being filled with all unrighteousness, wickedness, greediness, malice, full of envy, murder, strife, deceit, malevolence. <span class=\"supplied\">They are</span> gossipers,'),
('LEB', 'Romans', '1', '30', '10', 'slanderers, haters of God, insolent, arrogant, boasters, contrivers of evil, disobedient to parents,'),
('LEB', 'Romans', '1', '31', '10', 'senseless, faithless, unfeeling, unmerciful,'),
('LEB', 'Romans', '1', '32', '10', 'who, <span class=\"supplied\">although they</span>know the requirements of God, that those who do such things are worthy of death, not only do they do the same <span class=\"supplied\">things</span>, but also they approve of those who do <span class=\"supplied\">them</span>.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '2', '1', '1', '<span class=\"verse-title\">The Righteous and Impartial Judgment of God</span>Therefore you are without excuse, O man, every one <span class=\"supplied\">of you</span> who passes judgment. For in that which you pass judgment on someone else, you condemn yourself, for you who are passing judgment are doing the same <span class=\"supplied\">things</span>.'),
('LEB', 'Romans', '2', '2', '1', 'Now we know that the judgment of God is according to truth against those who do such things.'),
('LEB', 'Romans', '2', '3', '1', 'But do you think this, O man who passes judgment on those who do such things, and who does the same <span class=\"supplied\">things</span>, that you will escape the judgment of God?'),
('LEB', 'Romans', '2', '4', '1', 'Or do you despise the wealth of his kindness and forbearance and patience, not knowing that the kindness of God leads you to repentance?'),
('LEB', 'Romans', '2', '5', '1', 'But because of your stubbornness and unrepentant heart, you are storing up for yourself wrath in the day of wrath and of the revelation of the righteous judgment of God,'),
('LEB', 'Romans', '2', '6', '1', 'who will reward each one according to his works:'),
('LEB', 'Romans', '2', '7', '1', 'to those who, by perseverance in good work, seek glory and honor and immortality, eternal life,'),
('LEB', 'Romans', '2', '8', '1', 'but to those <span class=\"supplied\">who act</span> from selfish ambition and who disobey the truth, but who obey unrighteousness, wrath and anger.'),
('LEB', 'Romans', '2', '9', '1', '<span class=\"supplied\">There will be</span> affliction and distress for every <span class=\"idiom\">human being</span><span class=\"note\">“soul of man”</span>who does evil, of the Jew first and of the Greek,'),
('LEB', 'Romans', '2', '10', '1', 'but glory and honor and peace to everyone who does good, to the Jew first and to the Greek.'),
('LEB', 'Romans', '2', '11', '1', 'For <span class=\"supplied\">there</span> is no partiality with God.'),
('LEB', 'Romans', '2', '12', '2', 'For as many as have sinned without law will also perish without law, and as many as have sinned under the law will be judged by the law.'),
('LEB', 'Romans', '2', '13', '2', 'For it is not the hearers of the law <span class=\"supplied\">who are</span> righteous in the sight of God, but the doers of the law will be declared righteous.<span class=\"note\">Or “will be justified”</span>'),
('LEB', 'Romans', '2', '14', '2', 'For whenever the Gentiles, who do not have the law, do by nature the things of the law, these, <span class=\"supplied\">although they</span>do not have the law, are a law to themselves,'),
('LEB', 'Romans', '2', '15', '2', 'who show the work of the law written on their hearts, their conscience bearing witness and their thoughts <span class=\"supplied\">one</span> after another accusing or even defending them'),
('LEB', 'Romans', '2', '16', '2', 'on the day when God judges the secret things of people, according to my gospel, through<span class=\"note\">Or “by”</span>Christ Jesus.'),
('LEB', 'Romans', '2', '17', '4', '<span class=\"verse-title\">Jews also Condemned by the Law</span>But if you call yourself a Jew and rely on the law and boast in God'),
('LEB', 'Romans', '2', '18', '4', 'and know his will and approve the things that are superior, <span class=\"supplied\">because you</span>are instructed by the law,'),
('LEB', 'Romans', '2', '19', '4', 'and are confident <span class=\"supplied\">that</span> you yourself are a guide of the blind, a light of those in darkness,'),
('LEB', 'Romans', '2', '20', '4', 'an instructor of the foolish, a teacher of the immature, having the embodiment of knowledge and of the truth in the law.'),
('LEB', 'Romans', '2', '21', '4', 'Therefore, the one who teaches someone else, do you not teach yourself? The one who preaches not to steal, do you steal?'),
('LEB', 'Romans', '2', '22', '4', 'The one who says not to commit adultery, do you commit adultery? The one who abhors idols, do you rob temples?'),
('LEB', 'Romans', '2', '23', '4', 'Who boast in the law, by the transgression of the law you dishonor God!<span class=\"note\">Or “do you dishonor God?” (a number of translators and interpreters take this phrase as a final rhetorical question; the present translation regards it as a final summary statement to be taken ironically)</span>'),
('LEB', 'Romans', '2', '24', '4', 'For just as it is written, “The name of God is blasphemed among the Gentiles because of you.”<span class=\"note\">Isa 52:5</span>'),
('LEB', 'Romans', '2', '25', '5', 'For circumcision is of value if you do the law, but if you should be a transgressor of the law, your circumcision has become uncircumcision.'),
('LEB', 'Romans', '2', '26', '5', 'Therefore, if the uncircumcised person follows the requirements of the law, will not his uncircumcision be credited for circumcision?'),
('LEB', 'Romans', '2', '27', '5', 'And the uncircumcised person by nature who carries out the law will judge you who, <span class=\"supplied\">though provided</span> with <span class=\"idiom\">the precise written code</span><span class=\"note\">“the letter”</span>and circumcision <span class=\"supplied\">are</span> a transgressor of the law.'),
('LEB', 'Romans', '2', '28', '5', 'For the Jew is not <span class=\"idiom\">one outwardly</span><span class=\"note\">“in the open”</span>, nor <span class=\"supplied\">is</span> circumcision <span class=\"idiom\">outwardly</span><span class=\"note\">“in the open”</span>, in the flesh.'),
('LEB', 'Romans', '2', '29', '5', 'But the Jew <span class=\"idiom\">is one inwardly</span><span class=\"note\">“in secret”</span>, and circumcision <span class=\"supplied\">is</span> of the heart, by the Spirit, not by the letter, whose praise <span class=\"supplied\">is</span> not from people but from God.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '3', '1', '1', '<span class=\"verse-title\">Jews Still Have an Advantage</span>Therefore, what <span class=\"supplied\">is</span> the advantage of the Jew, or what <span class=\"supplied\">is</span> the use of circumcision?'),
('LEB', 'Romans', '3', '2', '1', 'Much in every way. For first, that they were entrusted with the oracles of God.'),
('LEB', 'Romans', '3', '3', '1', '<span class=\"idiom\">What is the result</span><span class=\"note\">“for what”</span>if some refused to believe? Their unbelief will not nullify the faithfulness of God, <span class=\"supplied\">will it</span>?'),
('LEB', 'Romans', '3', '4', '1', 'May it never be! But let God be true but every human being a liar, just as it is written, “In order that you may be justified in your words,  and may prevail when you arejudged.”<span class=\"note\">Ps 51:4</span>'),
('LEB', 'Romans', '3', '5', '3', 'But if our unrighteousness demonstrates the righteousness of God, what shall we say? God, who inflicts wrath, <span class=\"supplied\">is</span> not unjust, <span class=\"supplied\">is he</span>? (I am speaking according to a human perspective.)'),
('LEB', 'Romans', '3', '6', '3', 'May it never be! For otherwise, how will God judge the world?'),
('LEB', 'Romans', '3', '7', '3', 'But if by my lying, the truth of God abounded to his glory, why am I also still condemned as a sinner?'),
('LEB', 'Romans', '3', '8', '3', 'And <span class=\"supplied\">why</span> not (as we are slandered, and as some affirm that we say), “Let us do evil, in order that good may come <span class=\"supplied\">of it</span>? Their<span class=\"note\">“whose”</span>condemnation is just!'),
('LEB', 'Romans', '3', '9', '5', '<span class=\"verse-title\">The Entire World Guilty of Sin</span>What then? Do we have an advantage? Not at all. For we have already charged both Jews and Greeks are all under sin,'),
('LEB', 'Romans', '3', '10', '5', 'just as it is written,'),
('LEB', 'Romans', '3', '11', '6', '“<span class=\"supplied\">There</span> is no one righteous, not even one;'),
('LEB', 'Romans', '3', '12', '6', '<span class=\"supplied\">there</span> is no one who understands;  <span class=\"supplied\">there</span> is no one who seeks God.'),
('LEB', 'Romans', '3', '13', '6', 'All have turned aside together; they have become worthless;  <span class=\"supplied\">There</span> is no one who practices kindness;  <span class=\"supplied\">there</span> is not even one.'),
('LEB', 'Romans', '3', '14', '6', 'Their throat <span class=\"supplied\">is</span> an opened grave;  they deceive with their tongues;  the venom of asps <span class=\"supplied\">is</span> under their lips,<span class=\"note\">Ps 5:9 and Ps 140:3</span>'),
('LEB', 'Romans', '3', '15', '6', 'whose mouth is full of cursing and bitterness.<span class=\"note\">Ps 10:7</span>'),
('LEB', 'Romans', '3', '16', '6', 'Their feet <span class=\"supplied\">are</span> swift to shed blood;'),
('LEB', 'Romans', '3', '17', '6', 'destruction and distress <span class=\"supplied\">are</span> in their paths,'),
('LEB', 'Romans', '3', '18', '6', 'and they have not known the way of peace.'),
('LEB', 'Romans', '3', '19', '7', 'Now we know that whatever the law says, it speaks to those under the law, in order that every mouth may be closed and the whole world may become accountable to God.'),
('LEB', 'Romans', '3', '20', '7', 'For by the works of the law <span class=\"idiom\">no person will be declared righteous</span><span class=\"note\">“all flesh will not be declared righteous”</span>before him, for through the law <span class=\"supplied\">comes</span> knowledge of sin.'),
('LEB', 'Romans', '3', '21', '9', '<span class=\"verse-title\">Righteousness through Faith Revealed</span>But now, apart from the law, the righteousness of God has been revealed, being testified about by the law and the prophets—'),
('LEB', 'Romans', '3', '22', '9', 'that is, the righteousness of God through faith in Jesus Christ<span class=\"note\">Or “through the faithfulness of Jesus Christ”</span>to all who believe. For <span class=\"supplied\">there</span> is no distinction,'),
('LEB', 'Romans', '3', '23', '9', 'for all have sinned and fall short of the glory of God,'),
('LEB', 'Romans', '3', '24', '9', 'being justified as a gift by his grace, through the redemption which is in Christ Jesus,'),
('LEB', 'Romans', '3', '25', '9', 'whom God made publicly available as the mercy seat<span class=\"note\">Or “as the place of propitiation”</span>through faith in his blood, for a demonstration of his righteousness, because of the passing over of previously committed sins,'),
('LEB', 'Romans', '3', '26', '9', 'in the forbearance of God, for the demonstration of his righteousness in the present time, so that he should be just and the one who justifies the <span class=\"supplied\">person</span> by faith<span class=\"note\">Or “by Jesus’ faithfulness”</span>in Jesus.'),
('LEB', 'Romans', '3', '27', '10', 'Therefore, where <span class=\"supplied\">is</span> boasting? It has been excluded. By what kind of law? Of works? No, but by a law<span class=\"note\">Or “a principle”</span>of faith.'),
('LEB', 'Romans', '3', '28', '10', 'For we consider a person to be justified by faith apart from the works of the law.'),
('LEB', 'Romans', '3', '29', '10', 'Or <span class=\"supplied\">is God</span> the God of the Jews only? <span class=\"supplied\">Is he</span> not also <span class=\"supplied\">the God</span> of the Gentiles? Yes, also of the Gentiles,'),
('LEB', 'Romans', '3', '30', '10', 'since God <span class=\"supplied\">is</span> one, who will justify <span class=\"idiom\">those who are circumcised</span><span class=\"note\">“circumcision”</span>by faith and <span class=\"idiom\">those who are uncircumcised</span><span class=\"note\">“uncircumcision”</span>through faith.'),
('LEB', 'Romans', '3', '31', '10', 'Therefore, do we nullify the law through faith? May it never be! But we uphold the law.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '4', '1', '1', '<span class=\"verse-title\">Abraham’s Faith Counted as Righteousness</span>What then shall we say <span class=\"supplied\">that</span> Abraham, our ancestor according to the flesh, has found?'),
('LEB', 'Romans', '4', '2', '1', 'For if Abraham was justified by works, he has something to boast about, but not before God.'),
('LEB', 'Romans', '4', '3', '1', 'For what does the scripture say? “And Abraham believed God, and it was credited to him for righteousness.”<span class=\"note\">Gen 15:6</span>'),
('LEB', 'Romans', '4', '4', '1', 'Now to the one who works, his pay is not credited according to grace, but according to his due.'),
('LEB', 'Romans', '4', '5', '1', 'But to the one who does not work, but who believes in the one who justifies the ungodly, his faith is credited for righteousness,'),
('LEB', 'Romans', '4', '6', '1', 'just as David also speaks about the blessing of the person to whom God credits righteousness apart from works:'),
('LEB', 'Romans', '4', '7', '2', '“Blessed <span class=\"supplied\">are they</span> whose lawless deeds have been forgiven,  and whose sins are covered over.'),
('LEB', 'Romans', '4', '8', '2', 'Blessed <span class=\"supplied\">is</span> the person against whom the Lord will never count sin.”<span class=\"note\">Ps 32:1–2</span>'),
('LEB', 'Romans', '4', '9', '3', 'Therefore, <span class=\"supplied\">is</span> this blessing for <span class=\"idiom\">those who are circumcised</span><span class=\"note\">“the circumcision”</span>, or also for <span class=\"idiom\">those who are uncircumcised</span><span class=\"note\">“the uncircumcision”</span>? For we say, “Faith was credited to Abraham for righteousness.”<span class=\"note\">Gen 15:6</span>'),
('LEB', 'Romans', '4', '10', '3', 'How then was it credited? <span class=\"supplied\">While he</span>was <span class=\"idiom\">circumcised</span><span class=\"note\">“in circumcision”</span>or <span class=\"idiom\">uncircumcised</span><span class=\"note\">“in uncircumcision”</span>? Not <span class=\"idiom\">while circumcised</span><span class=\"note\">“in circumcision”</span>but <span class=\"idiom\">while uncircumcised</span><span class=\"note\">“in uncircumcision”</span>!'),
('LEB', 'Romans', '4', '11', '3', 'And he received the sign of circumcision <span class=\"supplied\">as</span> a seal<span class=\"note\">Or “confirmation”</span>of the righteousness by faith which <span class=\"supplied\">he had</span> <span class=\"idiom\">while uncircumcised</span><span class=\"note\">“in uncircumcision”</span>, so that he could be the father of all who believe <span class=\"idiom\">although they are uncircumcised</span><span class=\"note\">“through uncircumcision”</span>, so that righteousness could be credited to them,<span class=\"note\">Some manuscripts have “could be credited to them also”</span>'),
('LEB', 'Romans', '4', '12', '3', 'and the father <span class=\"idiom\">of those who are circumcised</span><span class=\"note\">“of the circumcision”</span>to those who are not only from the circumcision, but who also follow in the footsteps of the faith of our father Abraham <span class=\"idiom\">which he had while uncircumcised</span><span class=\"note\">“of the in uncircumcision faith of our father Abraham”</span>.'),
('LEB', 'Romans', '4', '13', '5', '<span class=\"verse-title\">The Promise to Abraham Secured through Faith</span>For the promise to Abraham or to his descendants, <span class=\"supplied\">that</span> he would be heir of the world, <span class=\"supplied\">was</span> not through the law, but through the righteousness by faith.'),
('LEB', 'Romans', '4', '14', '5', 'For if those of the law <span class=\"supplied\">are</span> heirs, faith is rendered void and the promise is nullified.'),
('LEB', 'Romans', '4', '15', '5', 'For the law produces wrath, but where <span class=\"supplied\">there</span> is no law, neither <span class=\"supplied\">is there</span> transgression.'),
('LEB', 'Romans', '4', '16', '5', 'Because of this, <span class=\"supplied\">it is</span> by faith, in order that <span class=\"supplied\">it may be</span> according to grace, so that the promise may be secure to all the descendants, not only to those of the law, but also to those of the faith of Abraham, who is the father of us all'),
('LEB', 'Romans', '4', '17', '5', '(just as it is written, “I have made you the father of many nations”)<span class=\"note\">Gen 17:5</span>before God, in whom he believed, the one who makes the dead alive and who calls the things that are not as <span class=\"supplied\">though</span> they are,'),
('LEB', 'Romans', '4', '18', '5', 'who against hope believed in hope, so that he became the father of many nations, according to what was said, “so will your descendants be.”<span class=\"note\">Gen 15:5</span>'),
('LEB', 'Romans', '4', '19', '5', 'And not being weak in faith, he considered his own body as good as dead, <span class=\"note\">Some manuscripts have “already as good as dead”</span><span class=\"supplied\">because he</span>was approximately a hundred years old, and the deadness of Sarah’s womb.'),
('LEB', 'Romans', '4', '20', '5', 'And he did not waver in unbelief at the promise of God, but was strengthened in faith, giving glory to God'),
('LEB', 'Romans', '4', '21', '5', 'and being fully convinced that what he had promised, he was also able to do.'),
('LEB', 'Romans', '4', '22', '5', 'Therefore<span class=\"note\">Some manuscripts have “Therefore, indeed,”</span>it was credited to him for righteousness.'),
('LEB', 'Romans', '4', '23', '5', 'But it was not written for the sake of him alone that it was credited to him,'),
('LEB', 'Romans', '4', '24', '5', 'but also for the sake of us to whom it is going to be credited, to those who believe in the one who raised Jesus our Lord from the dead,'),
('LEB', 'Romans', '4', '25', '5', 'who was handed over on account of our trespasses, and was raised up in the interest of our justification.<span class=\"note\">Or “vindication”; or “acquittal”</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '5', '1', '1', '<span class=\"verse-title\">Reconciliation with God through Faith in Christ</span>Therefore, <span class=\"supplied\">because we</span>have been declared righteous by faith, we have<span class=\"note\">Although a number of important manuscripts read the subjunctive mood here (“let us have”), almost all English versions prefer the indicative mood (“we have”) which is supported by many other manuscripts</span>peace with God through our Lord Jesus Christ,'),
('LEB', 'Romans', '5', '2', '1', 'through whom also we have <span class=\"supplied\">obtained</span> access by faith into this grace in which we stand, and we boast in the hope of the glory of God.'),
('LEB', 'Romans', '5', '3', '1', 'And not only <span class=\"supplied\">this</span>, but we also boast in our afflictions, <span class=\"supplied\">because we</span>know that affliction produces patient endurance,'),
('LEB', 'Romans', '5', '4', '1', 'and patient endurance, proven character, and proven character, hope,'),
('LEB', 'Romans', '5', '5', '1', 'and hope does not disappoint, because the love of God has been poured out in our hearts through the Holy Spirit who was given to us.'),
('LEB', 'Romans', '5', '6', '2', 'For <span class=\"supplied\">while</span>we were still helpless, yet at the proper time Christ died for the ungodly.'),
('LEB', 'Romans', '5', '7', '2', 'For only rarely will someone die on behalf of a righteous person (for on behalf of a good person possibly someone might even dare to die),'),
('LEB', 'Romans', '5', '8', '2', 'but God demonstrates his own love for us, <span class=\"supplied\">in</span> that <span class=\"supplied\">while</span>we were still sinners, Christ died for us.'),
('LEB', 'Romans', '5', '9', '2', 'Therefore, by much more, <span class=\"supplied\">because we</span>have been declared righteous now by his blood, we will be saved through him from the wrath.'),
('LEB', 'Romans', '5', '10', '2', 'For if, <span class=\"supplied\">while we</span>were enemies, we were reconciled to God through the death of his Son, by much more, having been reconciled, we will be saved by his life.'),
('LEB', 'Romans', '5', '11', '2', 'And not only <span class=\"supplied\">this</span>, but also <span class=\"supplied\">we are</span> boasting in God through our Lord Jesus Christ, through whom we have now received the reconciliation.'),
('LEB', 'Romans', '5', '12', '4', '<span class=\"verse-title\">Death Came through Adam but Life Comes through Christ</span>Because of this, just as sin entered into the world through one man, and death through sin, so also death spread to all people because all sinned.'),
('LEB', 'Romans', '5', '13', '4', 'For until the law, sin was in the world, but sin is not charged to one’s account <span class=\"supplied\">when there</span>is no law.'),
('LEB', 'Romans', '5', '14', '4', 'But death reigned from Adam until Moses even over those who did not sin in the likeness of the transgression of Adam, who is a type of the one who is to come.'),
('LEB', 'Romans', '5', '15', '4', '<span class=\"idiom\">But the gift is not like the trespass</span><span class=\"note\">“but not like the trespass so also the gift”</span>, for if by the trespass of the one, the many died, by much more did the grace of God and the gift by the grace of the one man, Jesus Christ, multiply to the many.'),
('LEB', 'Romans', '5', '16', '4', 'And the gift <span class=\"supplied\">is</span> not as through the one who sinned, for on the one hand, judgment from the one <span class=\"supplied\">sin</span> <span class=\"supplied\">led</span> to condemnation, but the gift, from many trespasses, <span class=\"supplied\">led</span> to justification.'),
('LEB', 'Romans', '5', '17', '4', 'For if by the trespass of the one <span class=\"supplied\">man</span>, death reigned through the one <span class=\"supplied\">man</span>, much more will those who receive the abundance of grace and of the gift of righteousness reign in life through the one, Jesus Christ.'),
('LEB', 'Romans', '5', '18', '4', 'Consequently therefore, as through one trespass <span class=\"supplied\">came</span> condemnation to all people, so also through one righteous deed <span class=\"supplied\">came</span> justification of life to all people.'),
('LEB', 'Romans', '5', '19', '4', 'For just as through the disobedience of the one man, the many were made sinners, so also through the obedience of the one, the many will be made righteous.'),
('LEB', 'Romans', '5', '20', '4', 'Now the law came in as a side issue, in order that the trespass could increase, but where sin increased, grace was present in greater abundance,'),
('LEB', 'Romans', '5', '21', '4', 'so that just as sin reigned in death, so also grace would reign through righteousness to eternal life through Jesus Christ our Lord.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '6', '1', '1', '<span class=\"verse-title\">Formerly Dead to Sin, Now Alive in Christ</span>What therefore shall we say? Shall we continue in sin, in order that grace may increase?'),
('LEB', 'Romans', '6', '2', '1', 'May it never be! How can we who died to sin still live in it?'),
('LEB', 'Romans', '6', '3', '1', 'Or do you not know that as many as were baptized into Christ Jesus were baptized into his death?'),
('LEB', 'Romans', '6', '4', '1', 'Therefore we have been buried with him through baptism into death, in order that just as Christ was raised from the dead through the glory of the Father, so also we may live <span class=\"idiom\">a new way of life</span><span class=\"note\">“in newness of life”</span>.'),
('LEB', 'Romans', '6', '5', '1', 'For if we have become identified with <span class=\"supplied\">him</span> in the likeness of his death, certainly also we will be <span class=\"supplied\">identified with him in the likeness</span><span class=\"note\">The elliptical phrase “identified with him in the likeness” has been supplied in the translation for clarity</span>of <span class=\"supplied\">his</span> resurrection,'),
('LEB', 'Romans', '6', '6', '1', 'knowing this, that our old man was crucified together with <span class=\"supplied\">him</span>, in order that the body of sin may be done away with, <span class=\"supplied\">that</span> we may no longer be enslaved to sin.'),
('LEB', 'Romans', '6', '7', '1', 'For the one who has died has been freed from sin.'),
('LEB', 'Romans', '6', '8', '2', 'Now if we died with Christ, we believe that we will also live with him,'),
('LEB', 'Romans', '6', '9', '2', 'knowing that Christ, <span class=\"supplied\">because he</span>has been raised from the dead, is going to die no more, death no longer being master over him.'),
('LEB', 'Romans', '6', '10', '2', 'For that <span class=\"supplied\">death</span> he died, he died to sin once and never again, but that <span class=\"supplied\">life</span> he lives, he lives to God.'),
('LEB', 'Romans', '6', '11', '2', 'So also you, consider yourselves to be dead to sin, but alive to God in Christ Jesus.'),
('LEB', 'Romans', '6', '12', '3', 'Therefore do not let sin reign in your mortal body, so that <span class=\"supplied\">you</span> obey its desires,'),
('LEB', 'Romans', '6', '13', '3', 'and do not present your members to sin <span class=\"supplied\">as</span> instruments of unrighteousness, but present yourselves to God as those who are alive from the dead, and your members to God <span class=\"supplied\">as</span> instruments of righteousness.'),
('LEB', 'Romans', '6', '14', '3', 'For sin will not be master over you, because you are not under law, but under grace.'),
('LEB', 'Romans', '6', '15', '5', '<span class=\"verse-title\">Set Free from Sin</span>What then? Shall we sin because we are not under law but under grace? May it never be!'),
('LEB', 'Romans', '6', '16', '5', 'Do you not know that to whomever you present yourselves <span class=\"supplied\">as</span> slaves for obedience, you are slaves to whomever you obey, whether sin, <span class=\"supplied\">leading</span> to death, or obedience, <span class=\"supplied\">leading</span> to righteousness?'),
('LEB', 'Romans', '6', '17', '5', 'But thanks <span class=\"supplied\">be</span> to God that you were slaves of sin, but you have obeyed from the heart the pattern of teaching to which you were entrusted,'),
('LEB', 'Romans', '6', '18', '5', 'and having been set free from sin, you became enslaved to righteousness.'),
('LEB', 'Romans', '6', '19', '5', '(I am speaking in human terms because of the weakness of your flesh.) For just as you presented your members <span class=\"supplied\">as</span> slaves to immorality and lawlessness, <span class=\"supplied\">leading</span> to lawlessness, so now present your members <span class=\"supplied\">as</span> slaves to righteousness, <span class=\"supplied\">leading</span> to sanctification.'),
('LEB', 'Romans', '6', '20', '5', 'For when you were slaves of sin, you were free with respect to righteousness.'),
('LEB', 'Romans', '6', '21', '6', 'Therefore what sort of fruit did you have then, about which you are now ashamed? For the end of those <span class=\"supplied\">things</span> <span class=\"supplied\">is</span> death.'),
('LEB', 'Romans', '6', '22', '6', 'But now, having been set free from sin and having been enslaved to God, you have your fruit <span class=\"supplied\">leading</span> to sanctification, and its end <span class=\"supplied\">is</span> eternal life.'),
('LEB', 'Romans', '6', '23', '6', 'For the compensation due sin <span class=\"supplied\">is</span> death, but the gift of God <span class=\"supplied\">is</span> eternal life in Christ Jesus our Lord.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '7', '1', '1', '<span class=\"verse-title\">Released from the Law through Death</span>Or do you not know, brothers (for I am speaking to those who know the law), that the law is master of a person for as long a time <span class=\"supplied\">as</span> he lives?'),
('LEB', 'Romans', '7', '2', '1', 'For the married woman is bound by law to <span class=\"supplied\">her</span> husband while he lives, but if her husband dies, she is released from the law of the husband.'),
('LEB', 'Romans', '7', '3', '1', 'Therefore as a result, if she belongs to another man <span class=\"supplied\">while</span>her husband is living, she will be called an adulteress. But if her husband dies, she is free from the law, so that she is not an adulteress <span class=\"supplied\">if she</span>belongs to another man.'),
('LEB', 'Romans', '7', '4', '1', 'So then, my brothers, you also were brought to death with respect to the law through the body of Christ, so that you may belong to another, to the one who was raised from the dead, in order that we may bear fruit for God.'),
('LEB', 'Romans', '7', '5', '1', 'For when we were in the flesh, sinful desires were working through the law in our members, to bear fruit for death.'),
('LEB', 'Romans', '7', '6', '1', 'But now we have been released from the law, <span class=\"supplied\">because we</span>have died <span class=\"supplied\">to that</span> by which we were bound, so that we may serve in newness of the Spirit and not in oldness of the letter <span class=\"supplied\">of the law</span>.'),
('LEB', 'Romans', '7', '7', '3', '<span class=\"verse-title\">Knowledge of Sin Comes through the Law</span>What then shall we say? <span class=\"supplied\">Is</span> the law sin? May it never be! But I would not have known sin except through the law, for I would not have known covetousness if the law had not said, “Do not covet.”<span class=\"note\">Exod 20:17; Deut 5:21</span>'),
('LEB', 'Romans', '7', '8', '3', 'But sin, seizing an opportunity through the commandment, produced in me all <span class=\"supplied\">kinds of</span> covetousness. For apart from the law, sin <span class=\"supplied\">is</span> dead.'),
('LEB', 'Romans', '7', '9', '3', 'And I was alive once, apart from the law, but <span class=\"supplied\">when</span>the commandment came, sin sprang to life'),
('LEB', 'Romans', '7', '10', '3', 'and I died, and this commandment which <span class=\"supplied\">was</span> to <span class=\"supplied\">lead to</span> life was found with respect to me to <span class=\"supplied\">lead to</span> death.'),
('LEB', 'Romans', '7', '11', '3', 'For sin, seizing the opportunity through the commandment, deceived me and through it killed <span class=\"supplied\">me</span>.'),
('LEB', 'Romans', '7', '12', '3', 'So then, the law <span class=\"supplied\">is</span> holy, and the commandment <span class=\"supplied\">is</span> holy and righteous and good.'),
('LEB', 'Romans', '7', '13', '5', '<span class=\"verse-title\">Internal Conflict with Sin</span>Therefore, <span class=\"supplied\">did that which is</span> good become death to me? May it never be! Rather <span class=\"supplied\">it was</span> sin, in order that it might be recognized <span class=\"supplied\">as</span> sin, producing death through <span class=\"supplied\">what is</span> good for me, in order that sin might become sinful to an extraordinary degree through the commandment.'),
('LEB', 'Romans', '7', '14', '5', 'For we know that the law is spiritual, but I am fleshly, <span class=\"idiom\">sold into slavery to sin</span><span class=\"note\">“sold under sin”</span>.'),
('LEB', 'Romans', '7', '15', '5', 'For what I am doing I do not understand, because what I want <span class=\"supplied\">to do</span>, this I do not practice, but what I hate, this I do.'),
('LEB', 'Romans', '7', '16', '5', 'But if what I do not want <span class=\"supplied\">to do</span>, this I do, I agree with the law that <span class=\"supplied\">it is</span> good.'),
('LEB', 'Romans', '7', '17', '5', 'But now I am no longer the one doing it, but sin that lives in me.'),
('LEB', 'Romans', '7', '18', '5', 'For I know that good does not live in me, that is, in my flesh. For the willing is present in me, but the doing <span class=\"supplied\">of</span> the good <span class=\"supplied\">is</span> not.'),
('LEB', 'Romans', '7', '19', '5', 'For the good that I want <span class=\"supplied\">to do</span>, I do not do, but the evil that I do not want <span class=\"supplied\">to do</span>, this I do.'),
('LEB', 'Romans', '7', '20', '5', 'But if what I do not want <span class=\"supplied\">to do</span>, this I am doing, I am no longer the one doing it, but sin that lives in me.'),
('LEB', 'Romans', '7', '21', '6', 'Consequently, I find the principle with me, the one who wants to do good, that evil is present with me.<span class=\"note\">Or “in me”</span>'),
('LEB', 'Romans', '7', '22', '6', 'For I joyfully agree with the law of God in my inner person,'),
('LEB', 'Romans', '7', '23', '6', 'but I observe another law in my members, at war with the law of my mind and making me captive to the law of sin that exists in my members.'),
('LEB', 'Romans', '7', '24', '6', 'Wretched man <span class=\"supplied\">that</span> I <span class=\"supplied\">am</span>! Who will rescue me from this body of death?'),
('LEB', 'Romans', '7', '25', '6', 'Thanks <span class=\"supplied\">be</span><span class=\"note\">Some manuscripts have “But thanks <span class=\"supplied\">be</span>”</span>to God through Jesus Christ our Lord! So then, I myself with my mind am enslaved to the law of God, but with my flesh <span class=\"supplied\">I am enslaved</span> to the law of sin.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '8', '1', '1', '<span class=\"verse-title\">Set Free from the Law of Sin and Death</span>Consequently, <span class=\"supplied\">there is</span> now no condemnation for those <span class=\"supplied\">who are</span> in Christ Jesus.'),
('LEB', 'Romans', '8', '2', '1', 'For the law of the Spirit of life in Christ Jesus has set you free from the law of sin and death.'),
('LEB', 'Romans', '8', '3', '1', 'For what <span class=\"supplied\">was</span> impossible for the law, in that it was weak through the flesh, God <span class=\"supplied\">did</span>. <span class=\"supplied\">By</span>sending his own Son in the likeness of sinful flesh and concerning sin, he condemned sin in the flesh,'),
('LEB', 'Romans', '8', '4', '1', 'in order that the requirement of the law would be fulfilled in us, who do not live according to the flesh but according to the Spirit.'),
('LEB', 'Romans', '8', '5', '1', 'For those who are <span class=\"supplied\">living</span> according to the flesh are intent on the things of the flesh, but those <span class=\"supplied\">who are living</span> according to the Spirit <span class=\"supplied\">are intent on</span> the things of the Spirit.'),
('LEB', 'Romans', '8', '6', '1', 'For the mindset of the flesh <span class=\"supplied\">is</span> death, but the mindset of the Spirit <span class=\"supplied\">is</span> life and peace,'),
('LEB', 'Romans', '8', '7', '1', 'because the mindset of the flesh <span class=\"supplied\">is</span> enmity toward God, for <span class=\"supplied\">it is</span> not subjected to the law of God, for <span class=\"supplied\">it is</span> not able <span class=\"supplied\">to do so</span>,'),
('LEB', 'Romans', '8', '8', '1', 'and those who are in the flesh are not able to please God.'),
('LEB', 'Romans', '8', '9', '2', 'But you are not in the flesh but in the Spirit, if indeed the Spirit of God lives in you. But if anyone does not have the Spirit of Christ, this person <span class=\"idiom\">does not belong to him</span><span class=\"note\">“is not of him”</span>.'),
('LEB', 'Romans', '8', '10', '2', 'But if Christ <span class=\"supplied\">is</span> in you, the body <span class=\"supplied\">is</span> dead because of sin, but the Spirit <span class=\"supplied\">is</span> life because of righteousness.'),
('LEB', 'Romans', '8', '11', '2', 'And if the Spirit of the one who raised Jesus from the dead lives in you, the one who raised Christ Jesus<span class=\"note\">Some manuscripts omit “Jesus”</span>from the dead will also make alive your mortal bodies through his Spirit who lives in you.'),
('LEB', 'Romans', '8', '12', '3', 'So then, brothers, we are obligated not to the flesh, to live according to the flesh.'),
('LEB', 'Romans', '8', '13', '3', 'For if you live according to the flesh, you are going to die, but if by the Spirit you put to death the deeds of the body, you will live.'),
('LEB', 'Romans', '8', '14', '3', 'For all those who are led by the Spirit of God, these are sons of God.'),
('LEB', 'Romans', '8', '15', '3', 'For you have not received a spirit of slavery <span class=\"supplied\">leading</span> to fear again, but you have received the Spirit of adoption, by whom we cry out, “Abba!<span class=\"note\">“Abba” means “father” in Aramaic</span>Father!”'),
('LEB', 'Romans', '8', '16', '3', 'The Spirit himself confirms to our spirit that we are children of God,'),
('LEB', 'Romans', '8', '17', '3', 'and if children, also heirs—heirs of God and fellow heirs with Christ, if indeed we suffer together <span class=\"supplied\">with him</span> so that we may also be glorified together <span class=\"supplied\">with him</span>.'),
('LEB', 'Romans', '8', '18', '5', '<span class=\"verse-title\">The Glory that is to be Revealed</span>For I consider that the sufferings of the present time are not worthy <span class=\"supplied\">to be compared</span> with the glory that is about to be revealed to us.'),
('LEB', 'Romans', '8', '19', '5', 'For the eagerly expecting creation awaits eagerly the revelation of the sons of God.'),
('LEB', 'Romans', '8', '20', '5', 'For the creation has been subjected to futility, not willingly, but because of the one who subjected <span class=\"supplied\">it</span>, in hope'),
('LEB', 'Romans', '8', '21', '5', 'that the creation itself also will be set free from its servility to decay, into the glorious freedom of the children of God.'),
('LEB', 'Romans', '8', '22', '5', 'For we know that the whole creation groans together and suffers agony together until now.'),
('LEB', 'Romans', '8', '23', '5', 'Not only <span class=\"supplied\">this</span>, but we ourselves also, having the first fruits of the Spirit, even we ourselves groan within ourselves <span class=\"supplied\">while we</span>await eagerly <span class=\"supplied\">our</span> adoption, the redemption of our body.'),
('LEB', 'Romans', '8', '24', '5', 'For in hope we were saved, but hope that is seen is not hope, for who hopes for what he sees?'),
('LEB', 'Romans', '8', '25', '5', 'But if we hope for what we do not see, we await <span class=\"supplied\">it</span> eagerly with patient endurance.'),
('LEB', 'Romans', '8', '26', '6', 'And likewise also, the Spirit helps <span class=\"supplied\">us</span> in our weakness, for we do not know how to pray as one ought, but the Spirit himself intercedes <span class=\"supplied\">for us</span> <span class=\"supplied\">with</span> unexpressed groanings.'),
('LEB', 'Romans', '8', '27', '6', 'And the one who searches our hearts knows what the mindset of the Spirit <span class=\"supplied\">is</span>, because he intercedes on behalf of the saints according to <span class=\"supplied\">the will of</span> God.'),
('LEB', 'Romans', '8', '28', '6', 'And we know that all <span class=\"supplied\">things</span> work together for good for those who love God, for those who are called according to <span class=\"supplied\">his</span> purpose,'),
('LEB', 'Romans', '8', '29', '6', 'because <span class=\"supplied\">those</span> whom he foreknew, he also predestined <span class=\"supplied\">to be</span> conformed to the image of his Son, so that he should be the firstborn among many brothers.'),
('LEB', 'Romans', '8', '30', '6', 'And <span class=\"supplied\">those</span> whom he predestined, these <span class=\"supplied\">he</span> also called, and <span class=\"supplied\">those</span> whom he called, these <span class=\"supplied\">he</span> also justified, and <span class=\"supplied\">those</span> whom he justified, these <span class=\"supplied\">he</span> also glorified.'),
('LEB', 'Romans', '8', '31', '8', '<span class=\"verse-title\">Victory in Christ</span>What then shall we say about these <span class=\"supplied\">things</span>? If God <span class=\"supplied\">is</span> for us, who <span class=\"supplied\">can be</span> against us?'),
('LEB', 'Romans', '8', '32', '8', 'Indeed, <span class=\"supplied\">he</span> who did not spare his own Son, but gave him up for us all, how will he not also, together with him, freely give us all <span class=\"supplied\">things</span>?'),
('LEB', 'Romans', '8', '33', '8', 'Who will bring charges against God’s elect? God <span class=\"supplied\">is</span> the one who justifies.'),
('LEB', 'Romans', '8', '34', '8', 'Who <span class=\"supplied\">is</span> the one who condemns? Christ<span class=\"note\">Some manuscripts have “Christ Jesus”</span><span class=\"supplied\">is</span> the one who died, and more than that, who was raised, who is also at the right hand of God, who also intercedes for us.'),
('LEB', 'Romans', '8', '35', '8', 'Who will separate us from the love of Christ? <span class=\"supplied\">Will</span> affliction or distress or persecution or hunger or lack of sufficient clothing or danger or the sword?'),
('LEB', 'Romans', '8', '36', '8', 'Just as it is written, “On account of you we are being put to death the whole day <span class=\"supplied\">long</span>;  we are considered as sheep for slaughter.”<span class=\"note\">Ps 44:22</span>'),
('LEB', 'Romans', '8', '37', '10', '<span class=\"supplied\">No</span>, but in all these <span class=\"supplied\">things</span> we prevail completely through the one who loved us.'),
('LEB', 'Romans', '8', '38', '10', 'For I am convinced that neither death, nor life, nor angels, nor rulers, nor things present, nor things to come, nor powers,'),
('LEB', 'Romans', '8', '39', '10', 'nor height, nor depth, nor any other created thing, will be able to separate us from the love of God that is in Christ Jesus our Lord.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '9', '1', '1', '<span class=\"verse-title\">Israel’s Rejection</span>I am telling the truth in Christ—<span class=\"supplied\">I am</span> not lying; my conscience bears witness to me in the Holy Spirit—'),
('LEB', 'Romans', '9', '2', '1', 'that my grief is great and <span class=\"supplied\">there is</span> constant distress in my heart.'),
('LEB', 'Romans', '9', '3', '1', 'For I could wish myself to be accursed from Christ for the sake of my brothers, my fellow countrymen according to the flesh,'),
('LEB', 'Romans', '9', '4', '1', 'who are Israelites, <span class=\"supplied\">to</span> whom <span class=\"supplied\">belong</span> the adoption, and the glory, and the covenants, and the giving of the law, and the <span class=\"supplied\">temple</span> service, and the promises,'),
('LEB', 'Romans', '9', '5', '1', '<span class=\"supplied\">to</span> whom <span class=\"supplied\">belong</span> the patriarchs, and from whom <span class=\"supplied\">is</span> the Christ according to human descent, who is God over all, blessed <span class=\"idiom\">forever</span><span class=\"note\">“for eternity”</span>! Amen.'),
('LEB', 'Romans', '9', '6', '2', 'But <span class=\"supplied\">it is</span> not as if the word of God had failed. For not all those <span class=\"supplied\">who are descended</span> from Israel <span class=\"supplied\">are truly</span> Israel,'),
('LEB', 'Romans', '9', '7', '2', 'nor <span class=\"supplied\">are they</span> all children because they are descendants of Abraham, but “In Isaac will your descendants be named.”<span class=\"note\">Gen 21:12</span>'),
('LEB', 'Romans', '9', '8', '2', 'That is, <span class=\"supplied\">it is</span> not the children <span class=\"idiom\">by human descent</span><span class=\"note\">“of the flesh”</span><span class=\"supplied\">who are</span> children of God, but the children of the promise are counted as descendants.'),
('LEB', 'Romans', '9', '9', '2', 'For the statement of the promise <span class=\"supplied\">is</span> this: “At this time I will return and <span class=\"idiom\">Sarah will have</span><span class=\"note\">“there will be to Sarah”</span>a son.”<span class=\"note\">Gen 18:10, 14</span>'),
('LEB', 'Romans', '9', '10', '2', 'And not only <span class=\"supplied\">this</span>, but also <span class=\"supplied\">when</span>Rebecca conceived children by one <span class=\"supplied\">man</span>,<span class=\"note\">Or perhaps “by one <span class=\"supplied\">act of sexual intercourse</span>”</span>Isaac our father—'),
('LEB', 'Romans', '9', '11', '2', 'for <span class=\"supplied\">although they</span>had not yet been born, or done anything good or evil, in order that the purpose of God according to election might remain,'),
('LEB', 'Romans', '9', '12', '2', 'not by works but by the one who calls—it was said to her, “The older will serve the younger,”<span class=\"note\">Gen 25:23</span>'),
('LEB', 'Romans', '9', '13', '2', 'just as it is written, “Jacob I loved, but Esau I hated.”<span class=\"note\">Mal 1:2–3</span>'),
('LEB', 'Romans', '9', '14', '4', '<span class=\"verse-title\">God’s Sovereign Choice to Show Mercy</span>What then shall we say? <span class=\"supplied\">There is</span> no injustice with God, <span class=\"supplied\">is there</span>?May it never be!'),
('LEB', 'Romans', '9', '15', '4', 'For to Moses he says, “I will have mercy on whomever I have mercy, and I will have compassion on whomever I have compassion.”<span class=\"note\">Exod 33:19</span>'),
('LEB', 'Romans', '9', '16', '4', 'Consequently therefore, <span class=\"idiom\">it does not depend on the</span><span class=\"note\">“not of the”</span>one who wills or on the one who runs, but on God who shows mercy.'),
('LEB', 'Romans', '9', '17', '4', 'For the scripture says to Pharaoh, “For this very <span class=\"supplied\">reason</span> I have raised you up, so that I may demonstrate my power in you, and so that my name might be proclaimed in all the earth.”<span class=\"note\">Exod 9:16</span>'),
('LEB', 'Romans', '9', '18', '4', 'Consequently therefore, he has mercy on whomever he wishes, and he hardens whomever he wishes.'),
('LEB', 'Romans', '9', '19', '5', 'Therefore you will say to me, “Why then does he still find fault? For who has resisted<span class=\"note\">Or “who resists”</span>his will?'),
('LEB', 'Romans', '9', '20', '5', 'On the contrary, O man, who are you who answers back to God? Will what is molded say to the one who molded <span class=\"supplied\">it</span>, “Why did you make me like this”?<span class=\"note\">Isa 29:16; 45:9</span>'),
('LEB', 'Romans', '9', '21', '5', 'Or does the potter not have authority over the clay, to make from the same lump a vessel that <span class=\"supplied\">is</span> for <span class=\"idiom\">honorable use</span><span class=\"note\">“honor”</span>and <span class=\"supplied\">one</span> that <span class=\"supplied\">is</span> for <span class=\"idiom\">ordinary use</span><span class=\"note\">“dishonor”</span>?'),
('LEB', 'Romans', '9', '22', '5', 'And <span class=\"supplied\">what</span> if God, wanting to demonstrate his wrath and to make known his power, endured with much patience vessels of wrath prepared for destruction?'),
('LEB', 'Romans', '9', '23', '5', 'And <span class=\"supplied\">he did so</span>in order that he could make known the riches of his glory upon vessels of mercy that he prepared beforehand for glory,'),
('LEB', 'Romans', '9', '24', '5', 'us whom he also called, not only from the Jews but also from the Gentiles?'),
('LEB', 'Romans', '9', '25', '5', 'As he also says in Hosea,'),
('LEB', 'Romans', '9', '26', '6', '“I will call those <span class=\"supplied\">who were</span> not my people, ‘My people,’  and those <span class=\"supplied\">who were</span> not loved, ‘Loved.’<span class=\"note\">Hos 2:23</span>'),
('LEB', 'Romans', '9', '27', '7', 'And Isaiah cries out concerning Israel,'),
('LEB', 'Romans', '9', '28', '8', '“<span class=\"supplied\">Even</span> if the number of the sons of Israel is like the sand of the sea,  the remnant will be saved,'),
('LEB', 'Romans', '9', '29', '9', 'And just as Isaiah foretold, “If the Lord of hosts had not left us descendants,  we would have become like Sodom  and would have resembled Gomorrah.”<span class=\"note\">Isa 1:9</span>'),
('LEB', 'Romans', '9', '30', '11', 'What then shall we say? That the Gentiles, who did not pursue righteousness, attained righteousness—even the righteousness <span class=\"supplied\">that is</span> by faith.'),
('LEB', 'Romans', '9', '31', '11', 'But Israel, pursuing the law of righteousness, did not attain to the law.'),
('LEB', 'Romans', '9', '32', '11', 'Why that? Because <span class=\"supplied\">they did</span> not <span class=\"supplied\">pursue it</span> by faith, but as <span class=\"supplied\">if</span> by works. They stumbled over the <span class=\"idiom\">stone that causes people to stumble</span><span class=\"note\">“stone of stumbling”</span>,'),
('LEB', 'Romans', '9', '33', '11', 'just as it is written, “Behold, I am laying in Zion <span class=\"idiom\">a stone that causes people to stumble</span><span class=\"note\">“a stone of stumbling”</span>,  and <span class=\"idiom\">a rock that causes them to fall</span><span class=\"note\">“a rock of offense”</span>,  and the one who believes in him will not be put to shame.”<span class=\"note\">Isa 28:16; 8:14</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '10', '1', '1', '<span class=\"verse-title\">The Righteousness of God through Faith in Christ</span>Brothers, the desire of my heart and my prayer to God on behalf of them <span class=\"supplied\">is</span> for <span class=\"supplied\">their</span> salvation.'),
('LEB', 'Romans', '10', '2', '1', 'For I testify about them that they have a zeal for God, but not according to knowledge.'),
('LEB', 'Romans', '10', '3', '1', 'For ignoring the righteousness of God, and seeking to establish their own,<span class=\"note\">Some manuscripts have “their own righteousness”</span>they did not subject themselves to the righteousness of God.'),
('LEB', 'Romans', '10', '4', '1', 'For Christ <span class=\"supplied\">is the</span> end of the law for righteousness to everyone who believes.'),
('LEB', 'Romans', '10', '5', '2', 'For Moses writes about the righteousness <span class=\"supplied\">that is</span> from the law: “The person who does <span class=\"supplied\">this</span><span class=\"note\">Some manuscripts explicitly state “these <span class=\"supplied\">things</span>”</span>will live by it.”<span class=\"note\">Lev 18:5</span><span class=\"note\">Some manuscripts have “them”</span>'),
('LEB', 'Romans', '10', '6', '2', 'But the righteousness from faith speaks like this: “Do not say in your heart,<span class=\"note\">Deut 9:4</span>‘Who will ascend into heaven?’ ”<span class=\"note\">Deut 30:12</span>(that is, to bring Christ down),'),
('LEB', 'Romans', '10', '7', '2', 'or “Who will descend into the abyss?”<span class=\"note\">Deut 30:13</span>(that is, to bring Christ up from the dead).'),
('LEB', 'Romans', '10', '8', '2', 'But what does it say? “The word is near to you, in your mouth and in your heart”<span class=\"note\">Deut 30:14</span>(that is, the word of faith that we proclaim),'),
('LEB', 'Romans', '10', '9', '2', 'that<span class=\"note\">Or “because”</span>if you confess with your mouth “Jesus <span class=\"supplied\">is</span> Lord” and believe in your heart that God raised him from the dead, you will be saved.'),
('LEB', 'Romans', '10', '10', '2', 'For with the heart one believes, resulting in righteousness, and with the mouth one confesses, resulting in salvation.'),
('LEB', 'Romans', '10', '11', '2', 'For the scripture says, “Everyone who believes in him will not be put to shame.”<span class=\"note\">Isa 28:16</span>'),
('LEB', 'Romans', '10', '12', '2', 'For <span class=\"supplied\">there</span> is no distinction between Jew and Greek, for the same <span class=\"supplied\">Lord</span> <span class=\"supplied\">is</span> Lord of all, who is rich to all who call upon him.'),
('LEB', 'Romans', '10', '13', '2', 'For “everyone who calls upon the name of the Lord will be saved.”<span class=\"note\">Joel 2:32</span>'),
('LEB', 'Romans', '10', '14', '3', 'How then will they call upon <span class=\"supplied\">him</span> in whom they have not believed? And how will they believe <span class=\"supplied\">in him</span> about whom they have not heard? And how will they hear about <span class=\"supplied\">him</span> without one who preaches <span class=\"supplied\">to them</span>?'),
('LEB', 'Romans', '10', '15', '3', 'And how will they preach, unless they are sent? Just as it is written, “How timely <span class=\"supplied\">are</span> the feet of those who bring good news of good things.”<span class=\"note\">Isa 52:7; Nah 1:15</span>'),
('LEB', 'Romans', '10', '16', '3', 'But not all have obeyed the good news, for Isaiah says, “Lord, who has believed our report?”<span class=\"note\">Isa 53:1</span>'),
('LEB', 'Romans', '10', '17', '3', 'Consequently, faith <span class=\"supplied\">comes</span> by hearing, and hearing through the word about Christ.'),
('LEB', 'Romans', '10', '18', '4', 'But I say, they have not heard, have they?On the contrary, “Their voice has gone out to all the earth,  and their words to the ends of the inhabited world.”<span class=\"note\">Ps 19:4</span>'),
('LEB', 'Romans', '10', '19', '6', 'But I say, Israel did not know, did they?First, Moses says, “I will provoke you <span class=\"supplied\">to jealousy</span> by <span class=\"supplied\">those who are</span> not a nation;  by a senseless nation I will provoke you <span class=\"supplied\">to anger</span>.”<span class=\"note\">Deut 32:21</span>'),
('LEB', 'Romans', '10', '20', '8', 'And Isaiah is very bold and says, “I was found by those who did not seek me;  I became known to those who did not ask for me.”<span class=\"note\">Isa 65:1</span>'),
('LEB', 'Romans', '10', '21', '10', 'But about Israel he says, “The whole day <span class=\"supplied\">long</span> I held out my hands  to a disobedient and resistant people.”<span class=\"note\">Isa 65:2</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '11', '1', '1', '<span class=\"verse-title\">A Remnant of Israel Remains</span>Therefore I say, God has not rejected his people, has he?May it never be! For I also am an Israelite, from the descendants of Abraham, of the tribe of Benjamin.'),
('LEB', 'Romans', '11', '2', '1', 'God has not rejected his people, whom he foreknew! Or do you not know, in <span class=\"supplied\">the passage about</span>Elijah, what the scripture says—how he appeals to God against Israel?'),
('LEB', 'Romans', '11', '3', '1', '“Lord, they have killed your prophets, they have torn down your altars, and I alone am left, and they are seeking my life!”<span class=\"note\">1 Kgs 19:10, 14</span>'),
('LEB', 'Romans', '11', '4', '1', 'But what does the divine response say to him? “I have left for myself seven thousand people<span class=\"note\">Or perhaps “males,” referring to men only</span>who have not bent the knee to Baal.”<span class=\"note\">1 Kgs 19:18</span>'),
('LEB', 'Romans', '11', '5', '1', 'So in this way also at the present time, there is a remnant <span class=\"idiom\">selected by grace</span><span class=\"note\">“according to selection of grace”</span>.'),
('LEB', 'Romans', '11', '6', '1', 'But if by grace, <span class=\"supplied\">it is</span> no longer by works, for otherwise grace would no longer be grace.'),
('LEB', 'Romans', '11', '7', '2', 'What then? What Israel was searching for, this it did not obtain. But the elect obtained <span class=\"supplied\">it</span>, and the rest were hardened,'),
('LEB', 'Romans', '11', '8', '2', 'just as it is written, “God gave them a spirit of stupor,  eyes that do not see and ears that do not hear,  until this very day.”<span class=\"note\">Deut 29:4; Isa 29:10</span>'),
('LEB', 'Romans', '11', '9', '4', 'And David says,'),
('LEB', 'Romans', '11', '10', '5', '“Let their table become a snare and a trap,  and a cause for stumbling and a retribution to them;'),
('LEB', 'Romans', '11', '11', '6', 'I say then, they did not stumble so that they fell, <span class=\"supplied\">did they</span>?May it never be! But by their trespass, salvation <span class=\"supplied\">has come</span> to the Gentiles, in order to provoke them <span class=\"supplied\">to jealousy</span>.'),
('LEB', 'Romans', '11', '12', '6', 'And if their trespass <span class=\"supplied\">means</span> riches for the world and their loss <span class=\"supplied\">means</span> riches for the Gentiles, how much more <span class=\"supplied\">will</span> their fullness <span class=\"supplied\">mean</span>?'),
('LEB', 'Romans', '11', '13', '8', '<span class=\"verse-title\">Gentile Branches Grafted in</span>Now I am speaking to you Gentiles. Therefore, inasmuch as I am apostle to the Gentiles, I promote my ministry,'),
('LEB', 'Romans', '11', '14', '8', 'if somehow I may provoke my people to jealousy and save some of them.'),
('LEB', 'Romans', '11', '15', '8', 'For if their rejection <span class=\"supplied\">means</span> the reconciliation of the world, what <span class=\"supplied\">will</span> their acceptance <span class=\"supplied\">mean</span> except life from the dead?'),
('LEB', 'Romans', '11', '16', '8', 'Now if the first fruits <span class=\"supplied\">are</span> holy, <span class=\"supplied\">so</span> also <span class=\"supplied\">is</span> the <span class=\"supplied\">whole</span> batch of dough, and if the root <span class=\"supplied\">is</span> holy, <span class=\"supplied\">so</span> also <span class=\"supplied\">are</span> the branches.'),
('LEB', 'Romans', '11', '17', '9', 'Now if some of the branches were broken off, and you, <span class=\"supplied\">although you</span>were a wild olive tree, were grafted in among them and became a sharer of the root of the olive tree’s richness,'),
('LEB', 'Romans', '11', '18', '9', 'do not boast against the branches. But if you boast against <span class=\"supplied\">them</span>, you do not support the root, but the root <span class=\"supplied\">supports</span> you.'),
('LEB', 'Romans', '11', '19', '9', 'Then you will say, “Branches were broken off in order that I could be grafted in.”'),
('LEB', 'Romans', '11', '20', '9', 'Well said! They were broken off because of unbelief, but you stand firm because of faith. Do not think arrogant <span class=\"supplied\">thoughts</span>, but be afraid.'),
('LEB', 'Romans', '11', '21', '9', 'For if God did not spare the <span class=\"idiom\">natural</span><span class=\"note\">“according to nature”</span>branches, neither will he spare you.<span class=\"note\">Some manuscripts have “perhaps he will not spare you either”</span>'),
('LEB', 'Romans', '11', '22', '9', 'See, then, the kindness and severity of God: severity upon those who have fallen, but upon you the kindness of God—if you continue in his kindness, for otherwise you also will be cut off.'),
('LEB', 'Romans', '11', '23', '9', 'And those also, if they do not persist in unbelief, will be grafted in, because God is able to graft them in again.'),
('LEB', 'Romans', '11', '24', '9', 'For if you were cut off from what is by nature a wild olive tree, and contrary to nature were grafted into a cultivated olive tree, how much more will these who are <span class=\"idiom\">natural branches</span><span class=\"note\">“by nature”</span>be grafted into their own olive tree?'),
('LEB', 'Romans', '11', '25', '11', '<span class=\"verse-title\">All Israel to be Saved</span>For I do not want you to be ignorant, brothers, of this mystery, so that you will not be wise <span class=\"idiom\">in your own sight</span>,<span class=\"note\">“in yourselves”</span>that a partial hardening has happened to Israel, until the full number of the Gentiles has come in,'),
('LEB', 'Romans', '11', '26', '11', 'and so all Israel will be saved, just as it is written,'),
('LEB', 'Romans', '11', '27', '12', '“The deliverer will come out of Zion;  he will turn away ungodliness from Jacob.'),
('LEB', 'Romans', '11', '28', '13', 'With respect to the gospel, <span class=\"supplied\">they are</span> enemies for your sake, but with respect to election, <span class=\"supplied\">they are</span> dearly loved for the sake of the fathers.'),
('LEB', 'Romans', '11', '29', '13', 'For the gifts and the calling of God <span class=\"supplied\">are</span> irrevocable.'),
('LEB', 'Romans', '11', '30', '13', 'For just as you formerly were disobedient to God, but now have been shown mercy because of the disobedience of these,'),
('LEB', 'Romans', '11', '31', '13', 'so also these have now been disobedient for your mercy, in order that they also may now be shown mercy.'),
('LEB', 'Romans', '11', '32', '13', 'For God confined them all in disobedience, in order that he could have mercy on them all.'),
('LEB', 'Romans', '11', '33', '14', 'Oh, the depth of the riches  and the wisdom and the knowledge of God!  How unsearchable <span class=\"supplied\">are</span> his judgments  and <span class=\"supplied\">how</span> incomprehensible <span class=\"supplied\">are</span> his ways!'),
('LEB', 'Romans', '11', '34', '14', '“For who has known the mind of the Lord,  or who has been his counselor?<span class=\"note\">Isa 40:13</span>'),
('LEB', 'Romans', '11', '35', '14', 'Or who has given in advance to him,  and it will be paid back to him?”<span class=\"note\">Job 41:11</span>'),
('LEB', 'Romans', '11', '36', '14', 'For from him and through him and to him <span class=\"supplied\">are</span> all <span class=\"supplied\">things</span>.  To him <span class=\"supplied\">be</span> glory for eternity! Amen.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '12', '1', '1', '<span class=\"verse-title\">A Life Dedicated to God</span>Therefore I exhort you, brothers, through the mercies of God, to present your bodies <span class=\"supplied\">as</span> a living sacrifice, holy <span class=\"supplied\">and</span> pleasing to God, <span class=\"supplied\">which is</span> your reasonable service.'),
('LEB', 'Romans', '12', '2', '1', 'And do not be conformed to this age, but be transformed by the renewal of your mind, so that you may approve what <span class=\"supplied\">is</span> the good and well-pleasing and perfect will of God.'),
('LEB', 'Romans', '12', '3', '3', '<span class=\"verse-title\">A Variety of Gifts in the Body of Christ</span>For by the grace given to me I say to everyone who is among you not to think more highly of yourself than what one ought to think, but to think <span class=\"idiom\">sensibly</span><span class=\"note\">“so as to be sensible”</span>, as God has apportioned a measure of faith to each one.'),
('LEB', 'Romans', '12', '4', '3', 'For just as in one body we have many members, but all the members do not have the same function,'),
('LEB', 'Romans', '12', '5', '3', 'in the same way we who are many are one body in Christ, and <span class=\"idiom\">individually</span><span class=\"note\">“with respect to one”</span>members of one another,'),
('LEB', 'Romans', '12', '6', '3', 'but having different gifts according to the grace given to us: if <span class=\"supplied\">it is</span> prophecy, according to the proportion of <span class=\"supplied\">his</span> faith;'),
('LEB', 'Romans', '12', '7', '3', 'if <span class=\"supplied\">it is</span> service, by service; if <span class=\"supplied\">it is</span> one who teaches, by teaching;'),
('LEB', 'Romans', '12', '8', '3', 'if <span class=\"supplied\">it is</span> one who exhorts, by exhortation; one who gives, with sincerity; one who leads, with diligence; one who shows mercy, with cheerfulness.'),
('LEB', 'Romans', '12', '9', '5', '<span class=\"verse-title\">Living in Love</span>Love must be without hypocrisy. Abhor what <span class=\"supplied\">is</span> evil; be attached to what <span class=\"supplied\">is</span> good,'),
('LEB', 'Romans', '12', '10', '5', 'being devoted to one another in brotherly love, esteeming one another <span class=\"supplied\">more highly</span> in honor,'),
('LEB', 'Romans', '12', '11', '5', 'not lagging in diligence, being enthusiastic in spirit, serving the Lord,'),
('LEB', 'Romans', '12', '12', '5', 'rejoicing in hope, enduring in affliction, being devoted to prayer,'),
('LEB', 'Romans', '12', '13', '5', 'contributing to the needs of the saints, pursuing hospitality.'),
('LEB', 'Romans', '12', '14', '6', 'Bless those who persecute,<span class=\"note\">Some manuscripts have “who persecute you”</span>bless and do not curse <span class=\"supplied\">them</span>.'),
('LEB', 'Romans', '12', '15', '6', 'Rejoice with those who rejoice; weep with those who weep.'),
('LEB', 'Romans', '12', '16', '6', 'Think the same <span class=\"supplied\">thing</span> toward one another; <span class=\"idiom\">do not think arrogantly</span><span class=\"note\">“think not the arrogant”</span>, but associate with the lowly. Do not be wise <span class=\"idiom\">in your own sight</span><span class=\"note\">“in the sight of yourselves”</span>.'),
('LEB', 'Romans', '12', '17', '6', 'Pay back no one evil for evil. Take thought for <span class=\"supplied\">what is</span> good in the sight of all people.'),
('LEB', 'Romans', '12', '18', '6', 'If <span class=\"supplied\">it is</span> possible on your <span class=\"supplied\">part</span>, be at peace with all people.'),
('LEB', 'Romans', '12', '19', '6', 'Do not take revenge yourselves, dear friends, but give place to <span class=\"supplied\">God’s</span> wrath, for it is written, “Vengeance <span class=\"supplied\">is</span> mine, I will repay,”<span class=\"note\">Deut 32:35</span>says the Lord.'),
('LEB', 'Romans', '12', '20', '6', 'But “if your enemy is hungry, feed him; if he is thirsty, give him <span class=\"supplied\">something</span> to drink; for <span class=\"supplied\">by</span>doing this, you will heap up coals of fire upon his head.”<span class=\"note\">Prov 25:21–22</span>'),
('LEB', 'Romans', '12', '21', '6', 'Do not be overcome by evil, but overcome evil with good.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '13', '1', '1', '<span class=\"verse-title\">Obedience to the Governing Authorities</span>Let every person be subject to the governing authorities, for <span class=\"supplied\">there</span> is no authority except by God, and those that exist are put in place by God.'),
('LEB', 'Romans', '13', '2', '1', 'So then, the one who resists authority resists the ordinance <span class=\"supplied\">which is</span> from God, and those who resist will receive condemnation on themselves.'),
('LEB', 'Romans', '13', '3', '1', 'For rulers are not a <span class=\"supplied\">cause of</span> terror for a good deed, but for bad <span class=\"supplied\">conduct</span>. So do you want not to be afraid of authority? Do what <span class=\"supplied\">is</span> good, and you will have praise from it,'),
('LEB', 'Romans', '13', '4', '1', 'for it is God’s servant to you for what <span class=\"supplied\">is</span> good. But if you do what <span class=\"supplied\">is</span> bad, be afraid, because it does not bear the sword to no purpose. For it is God’s servant, the one who avenges for punishment on the one who does <span class=\"supplied\">what is</span> bad.'),
('LEB', 'Romans', '13', '5', '1', 'Therefore <span class=\"supplied\">it is</span> necessary to be in subjection, not only because of wrath but also because of conscience.'),
('LEB', 'Romans', '13', '6', '1', 'For because of this you also pay taxes, for <span class=\"supplied\">the authorities</span><span class=\"note\">“they”</span>are servants of God, busily engaged in this very <span class=\"supplied\">thing</span>.'),
('LEB', 'Romans', '13', '7', '1', 'Pay to everyone <span class=\"supplied\">what is</span> owed: <span class=\"supplied\">pay</span> taxes to whom taxes <span class=\"supplied\">are due</span>; <span class=\"supplied\">pay</span> customs duties to whom customs duties <span class=\"supplied\">are due</span>; <span class=\"supplied\">pay</span> respect to whom respect <span class=\"supplied\">is due</span>; <span class=\"supplied\">pay</span> honor to whom honor <span class=\"supplied\">is due</span>.<span class=\"note\">Due to the very compressed style in this verse, many words must be supplied to make sense in English</span>'),
('LEB', 'Romans', '13', '8', '3', '<span class=\"verse-title\">Love Fulfills the Law</span>Owe nothing to anyone, except to love one another, for the one who loves someone else has fulfilled the law.'),
('LEB', 'Romans', '13', '9', '3', 'For the <span class=\"supplied\">commandments</span>, “You shall not commit adultery, you shall not commit murder, you shall not steal, you shall not covet,”<span class=\"note\">Exod 20:13–15, 17; Deut 5:17–19, 21</span>and if <span class=\"supplied\">there is</span> any other commandment, are summed up in this statement: “You shall love your neighbor as yourself.”<span class=\"note\">Lev 19:18</span>'),
('LEB', 'Romans', '13', '10', '3', 'Love does not commit evil against a neighbor. Therefore love <span class=\"supplied\">is the</span> fulfillment of the law.'),
('LEB', 'Romans', '13', '11', '4', 'And <span class=\"supplied\">do</span> this <span class=\"supplied\">because you</span>know the time, that <span class=\"supplied\">it is</span> already the hour for you to wake up from sleep. For our salvation <span class=\"supplied\">is</span> nearer now than when we believed.'),
('LEB', 'Romans', '13', '12', '4', 'The night is far gone, and the day has drawn near. Therefore let us throw off<span class=\"note\">Some manuscripts have “let us lay aside”</span>the deeds of darkness and put on the weapons of light.'),
('LEB', 'Romans', '13', '13', '4', 'Let us live decently, as in the day, not in carousing and drunkenness, not in sexual immorality and licentiousness, not in strife and jealousy.'),
('LEB', 'Romans', '13', '14', '4', 'But put on the Lord Jesus Christ and do not make provision for the desires of the flesh.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '14', '1', '1', '<span class=\"verse-title\">Do Not Pass Judgment on One Another</span>Now receive the one who is weak in faith, <span class=\"supplied\">but</span> not for quarrels about opinions.'),
('LEB', 'Romans', '14', '2', '1', 'One believes <span class=\"supplied\">he may</span> eat all <span class=\"supplied\">things</span>, but the one who is weak eats <span class=\"supplied\">only</span> vegetables.'),
('LEB', 'Romans', '14', '3', '1', 'The one who eats must not despise the one who does not eat, and the one who does not eat must not judge the one who eats, because God has accepted him.'),
('LEB', 'Romans', '14', '4', '1', 'Who are you, who passes judgment on the domestic slave belonging to someone else? To his own master he stands or falls, and he will stand, for the Lord is able to make him stand.'),
('LEB', 'Romans', '14', '5', '2', 'One person<span class=\"note\">Some manuscripts have “For one person”</span>prefers <span class=\"supplied\">one</span> day over <span class=\"supplied\">another</span> day, and another person regards every day <span class=\"supplied\">alike</span>. Each one must be fully convinced in his own mind.'),
('LEB', 'Romans', '14', '6', '2', 'The one who is intent on the day is intent on <span class=\"supplied\">it</span> for the Lord, and the one who eats eats for the Lord, because he is thankful to God, and the one who does not eat does not eat for the Lord, and he is thankful to God.'),
('LEB', 'Romans', '14', '7', '2', 'For none of us lives for himself and none dies for himself.'),
('LEB', 'Romans', '14', '8', '2', 'For if we live, we live for the Lord, and if we die, we die for the Lord. Therefore whether we live <span class=\"supplied\">or</span> whether we die, we are the Lord’s.'),
('LEB', 'Romans', '14', '9', '2', 'For Christ died and became alive again for this <span class=\"supplied\">reason</span>, in order that he might be Lord of both the dead and the living.'),
('LEB', 'Romans', '14', '10', '3', 'But why do you judge your brother? Or also, why do you despise your brother? For we will all stand before the judgment seat of God.'),
('LEB', 'Romans', '14', '11', '3', 'For it is written, “As I live, says the Lord, every knee will bow to me,  and every tongue will praise God.”<span class=\"note\">Isa 45:23</span>'),
('LEB', 'Romans', '14', '12', '5', 'So<span class=\"note\">Some manuscripts have “So then,”</span>each one of us will give an account concerning himself.<span class=\"note\">Some manuscripts have “an account concerning himself to God”</span>'),
('LEB', 'Romans', '14', '13', '6', 'Therefore, let us no longer pass judgment on one another, but rather decide this: not to place a cause for stumbling or a temptation before a brother.'),
('LEB', 'Romans', '14', '14', '6', 'I know and am convinced in the Lord Jesus that nothing <span class=\"supplied\">is</span> unclean of itself, except to the one who considers something to be unclean; to that person <span class=\"supplied\">it is</span> unclean.'),
('LEB', 'Romans', '14', '15', '6', 'For if because of food, your brother is grieved, you are no longer living according to love. Do not destroy by your food that person for whom Christ died.'),
('LEB', 'Romans', '14', '16', '6', 'Therefore do not let your good be slandered.'),
('LEB', 'Romans', '14', '17', '6', 'For the kingdom of God is not eating and drinking, but righteousness and peace and joy in the Holy Spirit.'),
('LEB', 'Romans', '14', '18', '6', 'For the one who serves Christ in this <span class=\"supplied\">way</span> <span class=\"supplied\">is</span> well-pleasing to God and approved by people.'),
('LEB', 'Romans', '14', '19', '7', 'So then, let us pursue <span class=\"idiom\">what promotes peace</span><span class=\"note\">“the things of peace”</span>and <span class=\"idiom\">what edifies one another</span><span class=\"note\">“the things of edification toward one another”</span>.'),
('LEB', 'Romans', '14', '20', '7', 'Do not destroy the work of God on account of food. All <span class=\"supplied\">things</span> <span class=\"supplied\">are</span> clean, but <span class=\"supplied\">it is</span> wrong for the person <span class=\"idiom\">who eats and stumbles in the process</span><span class=\"note\">“who eats with stumbling”</span>.'),
('LEB', 'Romans', '14', '21', '7', '<span class=\"supplied\">It is</span> good not to eat meat or to drink wine or <span class=\"supplied\">to do anything</span> by which your brother stumbles or is offended or is weakened.<span class=\"note\">Some manuscripts omit “or is offended or is weakened”</span>'),
('LEB', 'Romans', '14', '22', '7', 'The faith that you have, have with respect to yourself before God. Blessed <span class=\"supplied\">is</span> the one who does not pass judgment on himself by what he approves.'),
('LEB', 'Romans', '14', '23', '7', 'But the one who doubts is condemned if he eats, because he does not <span class=\"supplied\">do so</span> from faith, and everything that <span class=\"supplied\">is</span> not from faith is sin.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '15', '1', '1', '<span class=\"verse-title\">Accept One Another according to Christ’s Example</span>But we who are strong ought to bear the weaknesses of the weak, and not to please ourselves.'),
('LEB', 'Romans', '15', '2', '1', 'Let each one of us please his neighbor for his good, for the purpose of edification.'),
('LEB', 'Romans', '15', '3', '1', 'For even Christ did not please himself, but just as it is written, “The insults of those who insult you have fallen on me.”<span class=\"note\">Ps 69:9</span>'),
('LEB', 'Romans', '15', '4', '1', 'For whatever was written beforehand was written for our instruction, in order that through patient endurance and through the encouragement of the scriptures we may have hope.'),
('LEB', 'Romans', '15', '5', '1', 'Now may the God of patient endurance and of encouragement grant you <span class=\"idiom\">to be in agreement</span><span class=\"note\">“to think the same”</span>with one another, in accordance with Christ Jesus,'),
('LEB', 'Romans', '15', '6', '1', 'so that with one mind you may glorify with one mouth the God and Father of our Lord Jesus Christ.'),
('LEB', 'Romans', '15', '7', '1', 'Therefore accept one another, just as Christ also has accepted you, to the glory of God.'),
('LEB', 'Romans', '15', '8', '2', 'For I say, Christ has become a servant of the circumcision on behalf of the truth of God, in order to confirm the promises to the fathers,'),
('LEB', 'Romans', '15', '9', '2', 'and that the Gentiles may glorify God for <span class=\"supplied\">his</span> mercy, just as it is written, “Because of this, I will praise you among the Gentiles,  and I will sing praise to your name.”<span class=\"note\">Ps 18:49</span>'),
('LEB', 'Romans', '15', '10', '4', 'And again it says, “Rejoice, Gentiles, with his people.”<span class=\"note\">Deut 32:43</span>'),
('LEB', 'Romans', '15', '11', '6', 'And again, “Praise the Lord, all the Gentiles,  and let all the peoples praise him.”<span class=\"note\">Ps 117:1</span>'),
('LEB', 'Romans', '15', '12', '8', 'And again Isaiah says, “The root of Jesse will come,  even the one who rises to rule over the Gentiles;  in him the Gentiles will put their hope.”<span class=\"note\">Isa 11:10</span>'),
('LEB', 'Romans', '15', '13', '10', 'Now may the God of hope fill you with all joy and peace in believing, so that you may abound in hope by the power of the Holy Spirit.'),
('LEB', 'Romans', '15', '14', '12', '<span class=\"verse-title\">Paul’s Ministry to the Gentiles</span>Now I myself also am convinced about you, my brothers, that <span class=\"supplied\">you</span> yourselves also are full of goodness, filled with all knowledge, able also to instruct one another.'),
('LEB', 'Romans', '15', '15', '12', 'But I have written to you more boldly on <span class=\"supplied\">some</span> points, so as to remind you <span class=\"supplied\">again</span> because of the grace that has been given to me by God,'),
('LEB', 'Romans', '15', '16', '12', 'with the result that I am a servant of Christ Jesus to the Gentiles, serving the gospel of God as a priest, in order that the offering of the Gentiles may become acceptable, sanctified by the Holy Spirit.'),
('LEB', 'Romans', '15', '17', '12', 'Therefore I have a reason for boasting in Christ Jesus regarding the things concerning God.'),
('LEB', 'Romans', '15', '18', '12', 'For I will not dare to speak about anything except <span class=\"supplied\">that</span> which Christ has accomplished through me, resulting in the obedience of the Gentiles by word and deed,'),
('LEB', 'Romans', '15', '19', '12', 'by the power of signs and wonders, by the power of the Spirit,<span class=\"note\">Some manuscripts have “of the Spirit of God”</span>so that from Jerusalem and <span class=\"supplied\">traveling</span> around as far as Illyricum I have fully proclaimed the gospel of Christ.'),
('LEB', 'Romans', '15', '20', '12', 'And so, having as my ambition to proclaim the gospel where Christ has not been named, in order that I will not build on the foundation belonging to someone else,'),
('LEB', 'Romans', '15', '21', '12', 'but just as it is written, “<span class=\"supplied\">Those</span> to whom <span class=\"supplied\">it was</span> not announced concerning him will see,  and <span class=\"supplied\">those</span> who have not heard will understand.”<span class=\"note\">Isa 52:15</span>'),
('LEB', 'Romans', '15', '22', '15', '<span class=\"verse-title\">Paul’s Travel Plans</span>For this reason also I was hindered many <span class=\"supplied\">times</span> from coming to you,'),
('LEB', 'Romans', '15', '23', '15', 'and now, no longer having a place in these regions, but having a desire for many years to come to you'),
('LEB', 'Romans', '15', '24', '15', 'whenever I travel to Spain. For I hope <span class=\"supplied\">while I</span>am passing through to see you and to be sent on my way by you, whenever I have first enjoyed your <span class=\"supplied\">company</span> for a while.'),
('LEB', 'Romans', '15', '25', '15', 'But now I am traveling to Jerusalem, serving the saints.'),
('LEB', 'Romans', '15', '26', '15', 'For Macedonia and Achaia were pleased to make some contribution for the poor among the saints in Jerusalem.'),
('LEB', 'Romans', '15', '27', '15', 'For they were pleased <span class=\"supplied\">to do so</span>, and they are obligated to them. For if the Gentiles have shared in their spiritual <span class=\"supplied\">things</span>, they ought also to serve them in material <span class=\"supplied\">things</span>.'),
('LEB', 'Romans', '15', '28', '15', 'Therefore, <span class=\"supplied\">after I</span>have accomplished this and sealed this fruit <span class=\"supplied\">for delivery</span> to them, I will depart by way of you for Spain,'),
('LEB', 'Romans', '15', '29', '15', 'and I know that <span class=\"supplied\">when I</span>come to you, I will come in the fullness of the blessing of Christ.'),
('LEB', 'Romans', '15', '30', '16', 'Now I exhort you, brothers, through our Lord Jesus Christ and through the love of the Spirit, to contend along with me in your prayers on my behalf to God,'),
('LEB', 'Romans', '15', '31', '16', 'that I may be rescued from those who are disobedient in Judea, and my ministry in Jerusalem may be acceptable to the saints,'),
('LEB', 'Romans', '15', '32', '16', 'so that, coming to you with joy by the will of God, I may rest with you.'),
('LEB', 'Romans', '15', '33', '16', 'Now <span class=\"supplied\">may</span> the God of peace <span class=\"supplied\">be</span> with all of you. Amen.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Romans', '16', '1', '1', '<span class=\"verse-title\">Many Personal Greetings</span>Now I commend to you Phoebe our sister, who is also a servant<span class=\"note\">Or “a deaconess”; some interpreters understand this term to refer to a specific office (deacon/deaconess) which Phoebe held in the local church at Cenchrea</span>of the church in Cenchrea,'),
('LEB', 'Romans', '16', '2', '1', 'in order that you may welcome her in the Lord in a manner worthy of the saints, and help her in whatever task she may have need from you, for she herself also has been a helper of many, even me myself.'),
('LEB', 'Romans', '16', '3', '2', 'Greet Prisca and Aquila, my fellow workers in Christ Jesus,'),
('LEB', 'Romans', '16', '4', '2', 'who risked their own necks for my life, for which not only I am thankful, but also all the churches of the Gentiles;'),
('LEB', 'Romans', '16', '5', '2', 'also <span class=\"supplied\">greet</span><span class=\"note\">The verb is supplied as an understood repetition from v. 3</span>the church in their house. Greet Epenetus my dear <span class=\"supplied\">friend</span>, who is <span class=\"idiom\">the first convert</span><span class=\"note\">“the first fruits”</span>of Asia for Christ.'),
('LEB', 'Romans', '16', '6', '2', 'Greet Mary, who <span class=\"idiom\">has worked hard</span><span class=\"note\">“has labored much”</span>for you.'),
('LEB', 'Romans', '16', '7', '2', 'Greet Andronicus and Junia,<span class=\"note\">Or “Junias,” the masculine form of the same name</span>my compatriots<span class=\"note\">Or “relatives”</span>and my fellow prisoners, who are well known to<span class=\"note\">Or “are outstanding among”</span>the apostles, who were also in Christ before me.'),
('LEB', 'Romans', '16', '8', '2', 'Greet Ampliatus, my dear <span class=\"supplied\">friend</span> in the Lord.'),
('LEB', 'Romans', '16', '9', '2', 'Greet Urbanus, our fellow worker in Christ, and my dear <span class=\"supplied\">friend</span> Stachys.'),
('LEB', 'Romans', '16', '10', '2', 'Greet Apelles, who <span class=\"supplied\">is</span> approved in Christ. Greet those of the <span class=\"supplied\">household</span> of Aristobulus.'),
('LEB', 'Romans', '16', '11', '2', 'Greet Herodion my compatriot.<span class=\"note\">Or “relative”</span>Greet those of the <span class=\"supplied\">household</span> of Narcissus who are in the Lord.'),
('LEB', 'Romans', '16', '12', '2', 'Greet Tryphena and Tryphosa, the laborers in the Lord. Greet Persis, the dear <span class=\"supplied\">friend</span> who <span class=\"idiom\">has worked hard</span><span class=\"note\">“has labored much”</span>in the Lord.'),
('LEB', 'Romans', '16', '13', '2', 'Greet Rufus, the chosen one in the Lord, and his mother and mine.'),
('LEB', 'Romans', '16', '14', '2', 'Greet Asyncritus, Phlegon, Hermes, Patrobas, Hermas, and the brothers with them.'),
('LEB', 'Romans', '16', '15', '2', 'Greet Philologus and Julia, Nereus and his sister, and Olympas, and all the saints <span class=\"supplied\">who are</span> with them.'),
('LEB', 'Romans', '16', '16', '2', 'Greet one another with a holy kiss. All the churches of Christ greet you.'),
('LEB', 'Romans', '16', '17', '4', '<span class=\"verse-title\">Concluding Exhortations</span>Now I exhort you, brothers, to look out for those who cause dissensions and temptations contrary to the teaching which you learned, and stay away from them.'),
('LEB', 'Romans', '16', '18', '4', 'For such people do not serve our Lord Christ, but their own stomach, and by smooth speech and flattery they deceive the hearts of the unsuspecting.'),
('LEB', 'Romans', '16', '19', '4', 'For <span class=\"supplied\">the report of</span> your obedience has reached to all; therefore I am rejoicing over you, and I want you to be wise toward what <span class=\"supplied\">is</span> good, but innocent toward what <span class=\"supplied\">is</span> evil.'),
('LEB', 'Romans', '16', '20', '4', 'And in a short time the God of peace will crush Satan under your feet. The grace of our Lord Jesus Christ<span class=\"note\">Some manuscripts omit “Christ”</span><span class=\"supplied\">be</span> with you.'),
('LEB', 'Romans', '16', '21', '6', '<span class=\"verse-title\">Greetings from Paul’s Associates</span>Timothy, my fellow worker, greets you, and Lucius and Jason and Sosipater, my compatriots.<span class=\"note\">Or “relatives”</span>'),
('LEB', 'Romans', '16', '22', '7', 'I, Tertius, the one who wrote this letter, greet you in the Lord.'),
('LEB', 'Romans', '16', '23', '8', 'Gaius, my host and <span class=\"supplied\">the host</span> of the whole church, greets you. Erastus the city treasurer greets you, and Quartus the brother.'),
('LEB', 'Romans', '16', '24', '10', '<span class=\"verse-title\">Benediction</span>The grace of our Lord Jesus Christ <span class=\"supplied\">be</span> with all of you. Amen.<span class=\"note\">Some manuscripts include vv. 25–27, “25 Now to the one who is able to strengthen you according to my gospel and the preaching of Jesus Christ, according to the revelation of the mystery that had been kept secret for eternal ages, 26 but now has been revealed, and through the prophetic scriptures has been made known according to the command of the eternal God, resulting in obedience of faith to all the Gentiles, 27 to the only wise God, through Jesus Christ, to whom <span class=\"supplied\">be</span> the glory for eternity. Amen.”</span>')
;

