INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '1', '1', '1', '<span class=\"verse-title\">Introduction</span>The words of Amos, who was among the shepherds from Tekoa, which he saw concerning Israel in the days of Uzziah the king of Judah and in the days of Jeroboam the son of Jehoash, two years <span class=\"idiom\">before</span><span class=\"note\">Literally “to the face of”</span>the earthquake.'),
('LEB', 'Amos', '1', '2', '3', '<span class=\"verse-title\">Judgment on Israel’s Neighbors</span>And he said, “Adonai roars from Zion and he utters his voice from Jerusalem; the pastures of the shepherds wither and the top of Carmel dries up.”'),
('LEB', 'Amos', '1', '3', '3', 'Thus says Adonai, “For three transgressions of Damascus and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because they threshed Gilead with threshing sledges of iron!'),
('LEB', 'Amos', '1', '4', '3', 'So I will send fire against Hazael’s house and it will consume the citadel fortresses of Ben-Hadad.'),
('LEB', 'Amos', '1', '5', '3', 'I will break the gate bars of Damascus and I will cut off the inhabitants from the Valley of Aven and the one who takes hold of the scepter of Beth Eden, and the people of Aram will go into exile to Kir,” says Adonai.'),
('LEB', 'Amos', '1', '6', '4', 'Thus says Adonai: “For three transgressions of Gaza and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because they exiled a whole community, handing them over to Edom!'),
('LEB', 'Amos', '1', '7', '4', 'So I will send a fire against the wall of Gaza and it will devour its citadel fortresses.'),
('LEB', 'Amos', '1', '8', '4', 'And I will cut off the inhabitants from Ashdod and the one who takes hold of the scepter of Ashkelon. I will also turn my hand against Ekron, and the remnant of the Philistines will perish,” says the Lord Adonai.'),
('LEB', 'Amos', '1', '9', '5', 'Thus says Adonai: “For three transgressions of Tyre and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because they delivered up a whole community to Edom and they did not remember the covenant of brotherhood!'),
('LEB', 'Amos', '1', '10', '5', 'So I will send a fire against the wall of Tyre and it will devour its citadel fortresses.”'),
('LEB', 'Amos', '1', '11', '6', 'Thus says Adonai: “For three transgressions of Edom and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because he pursued his brother with the sword! He stifled his compassion and his anger tore <span class=\"supplied\">them</span> apart <span class=\"idiom\">continually</span>,<span class=\"note\">Literally “forever”</span>and he kept his rage forever.'),
('LEB', 'Amos', '1', '12', '6', 'So I will send a fire against Teman and it will devour the citadel fortresses of Bozrah.”'),
('LEB', 'Amos', '1', '13', '7', 'Thus says Adonai: “For three transgressions of Ammon and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because they ripped open the pregnant women of Gilead in order to enlarge their territory!'),
('LEB', 'Amos', '1', '14', '7', 'So I will kindle a fire against the wall of Rabbah and it will devour its citadel fortresses with a war cry on the day of battle, with a storm on the day of the violent tempest.'),
('LEB', 'Amos', '1', '15', '7', 'And their king will go into exile, he and his commanders together,” says Adonai.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '2', '1', '0', 'Thus says Adonai: “For three transgressions of Moab and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because he burned to lime the bones of the king of Edom.'),
('LEB', 'Amos', '2', '2', '0', 'So I will send a fire against Moab and it will devour the citadel fortresses of Kerioth, and Moab will die amid uproar, amid war cries <span class=\"supplied\">and</span> amid the sound of a horn.'),
('LEB', 'Amos', '2', '3', '0', 'And I will cut off <span class=\"supplied\">the</span> ruler from its midst and I will kill all of its officials with him,” says Adonai.'),
('LEB', 'Amos', '2', '4', '2', '<span class=\"verse-title\">Judgment on Judah</span>Thus says Adonai: “For three transgressions of Judah and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because they have rejected the law of Adonai and have not kept his rules, and their lies have led them astray, <span class=\"idiom\">after which their ancestors walked</span>!<span class=\"note\">Literally “which their ancestors walked after them”</span>'),
('LEB', 'Amos', '2', '5', '2', 'So I will send a fire against Judah and it will devour the citadel fortresses of Jerusalem.'),
('LEB', 'Amos', '2', '6', '4', '<span class=\"verse-title\">Judgment on Israel</span>Thus says Adonai: “For three transgressions of Israel and for four I will not revoke <span class=\"supplied\">the punishment</span>,<span class=\"note\">Or “it”</span>because they sell the righteous for money and the poor for a pair of sandals!'),
('LEB', 'Amos', '2', '7', '4', 'Those who trample the heads of the powerless into the dust of the ground and turn aside the way of the destitute, a man and his father <span class=\"idiom\">have sexual relations with</span><span class=\"note\">Literally “go to”</span>the same girl, so that <span class=\"supplied\">they</span> profane my holy name.'),
('LEB', 'Amos', '2', '8', '4', 'They stretch themselves out beside every altar on clothing taken in pledge and they drink wine, bought with fines imposed,<span class=\"note\">Literally “imposing a fine”</span>in the house of their God.'),
('LEB', 'Amos', '2', '9', '4', 'Yet I destroyed the Amorite <span class=\"idiom\">before them</span>,<span class=\"note\">Literally “from the face of them”</span><span class=\"idiom\">who was as tall as</span><span class=\"note\">Literally “whose height was as the height of”</span>cedars and was as strong as the oaks. I destroyed his fruit above and his roots beneath.'),
('LEB', 'Amos', '2', '10', '4', 'And I brought you up from the land of Egypt, and I led you in the wilderness forty years to take possession of the land of the Amorite.'),
('LEB', 'Amos', '2', '11', '4', 'And I raised up some <span class=\"supplied\">of</span> your sons to <span class=\"supplied\">be</span> prophets and some <span class=\"supplied\">of</span> your young men to <span class=\"supplied\">be</span> Nazirites. Is it not so, O <span class=\"idiom\">people</span><span class=\"note\">Literally “children”</span>of Israel? <span class=\"supplied\">This is</span> the declaration of Adonai!'),
('LEB', 'Amos', '2', '12', '4', 'But you made the Nazirites drink wine and commanded the prophets, saying, ‘You shall not prophesy.’'),
('LEB', 'Amos', '2', '13', '4', 'Look! I <span class=\"supplied\">am</span> going to press <span class=\"supplied\">you</span> down in your place just as a utility cart full of mature stalks of grain <span class=\"supplied\">is pressed down</span>.'),
('LEB', 'Amos', '2', '14', '4', 'Flight will perish from <span class=\"supplied\">the</span> swift and <span class=\"supplied\">the</span> strong person will not muster his strength and <span class=\"supplied\">the</span> warrior will not save his life.'),
('LEB', 'Amos', '2', '15', '4', 'And <span class=\"supplied\">the</span> one who takes hold of the bow will not stand and <span class=\"supplied\">the one who is</span> swift on his feet will not save himself, nor will <span class=\"supplied\">the</span> one who rides the horse save his life.'),
('LEB', 'Amos', '2', '16', '4', 'Even those who are strong of heart among the mighty will flee away naked from the city on that day. <span class=\"supplied\">This is</span> the declaration of Adonai!”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '3', '1', '1', '<span class=\"verse-title\">Israel’s Guilt and Punishment</span>Hear this word that Adonai has spoken against you, O people of Israel, against the whole clan that I brought up from the land of Egypt:<span class=\"note\">Hebrew “Egypt, saying”</span>'),
('LEB', 'Amos', '3', '2', '1', '“You only have I <span class=\"idiom\">chosen</span><span class=\"note\">Literally “known”</span>of all the clans of the earth. Therefore I will punish you for all your iniquities.'),
('LEB', 'Amos', '3', '3', '1', 'Do two walk together unless they have met?'),
('LEB', 'Amos', '3', '4', '1', 'Does a lion roar in the forest <span class=\"idiom\">when he has no prey</span>?<span class=\"note\">Literally “and there is no prey to him”</span>Does a fierce, young lion cry out from his den unless he has caught <span class=\"supplied\">something</span>?'),
('LEB', 'Amos', '3', '5', '1', 'Does a bird fall into a trapping net on the earth when there is no snare for it? Does a trapping net spring up from the ground unless it has certainly caught something?'),
('LEB', 'Amos', '3', '6', '1', 'Or is a horn blown in a city and people are not afraid? Or does a disaster occur in the city and Adonai has not done <span class=\"supplied\">it</span>?'),
('LEB', 'Amos', '3', '7', '1', 'Surely my Lord does not do anything unless he has revealed his secret to his servants the prophets.'),
('LEB', 'Amos', '3', '8', '1', 'A lion has roared! Who is not afraid? My Lord Adonai has spoken, who will not prophesy?'),
('LEB', 'Amos', '3', '9', '1', 'Proclaim to the citadel fortresses in Ashdod and the citadel fortresses in the land of Egypt and say: “Gather on the mountains of Samaria and see the great panic in her midst and the oppression in her midst!”'),
('LEB', 'Amos', '3', '10', '1', '“They do not know <span class=\"supplied\">how</span> to do right,” <span class=\"idiom\">declares Adonai</span>,<span class=\"note\">Literally “the declaration of Adonai”</span>“those who store up violence and destruction in their citadel fortresses.”'),
('LEB', 'Amos', '3', '11', '1', 'Therefore, thus says my Lord Adonai, “A foe shall surround the land and bring down your strongholds, and your citadel fortresses shall be plundered.”'),
('LEB', 'Amos', '3', '12', '1', 'Thus says Adonai, “Just as the shepherd rescues two legs or a piece of an ear from the mouth of the lion, so shall the <span class=\"idiom\">people</span><span class=\"note\">Literally “children”</span>of Israel who dwell in Samaria, with the corner of a couch and the damask of a bed.”'),
('LEB', 'Amos', '3', '13', '1', '“Listen and testify against the house of Jacob,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>my Lord Adonai, the God of hosts.'),
('LEB', 'Amos', '3', '14', '1', '“For on the day I punish Israel for <span class=\"idiom\">its transgression</span>,<span class=\"note\">Literally “the transgression of Israel upon it”</span>I will also punish the altars of Bethel and the horns of the altar will be cut off and fall to the ground.'),
('LEB', 'Amos', '3', '15', '1', 'I will ruin the winter house as well as the summer house, and the houses of ivory will perish and the great houses shall come to an end,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '4', '1', '1', '<span class=\"verse-title\">Social and Spiritual Corruption</span>Hear this word, <span class=\"supplied\">you</span> cows of Bashan who <span class=\"supplied\">live</span> on the mountain of Samaria, who oppress the powerless, who crush the poor, who say to their husbands, “Bring <span class=\"supplied\">something</span> so that we may drink!”'),
('LEB', 'Amos', '4', '2', '1', 'My Lord Adonai has sworn by his holiness that, “Behold, the days are coming upon you <span class=\"idiom\">when they</span><span class=\"note\">Literally “and he”</span>will take you away with hooks, even the last of you with fishing hooks.'),
('LEB', 'Amos', '4', '3', '1', 'And you shall leave through breaches <span class=\"supplied\">in the wall</span>, each one in front of her. You will be dragged off toward Harmon,”<span class=\"note\">The meaning of this Hebrew word is uncertain</span><span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai.'),
('LEB', 'Amos', '4', '4', '1', '“Come <span class=\"supplied\">to</span> Bethel and transgress; <span class=\"supplied\">to</span> Gilgal and <span class=\"idiom\">multiply transgression</span>!<span class=\"note\">Literally “increase to transgress”</span>Bring your sacrifices in the morning and your tithes on the <span class=\"idiom\">third day</span>.<span class=\"note\">Literally “for three of days”</span>'),
('LEB', 'Amos', '4', '5', '1', 'And bring a thank offering of unleavened bread, and proclaim freewill offerings, pronounce them, for so you love <span class=\"supplied\">to do</span>, O <span class=\"idiom\">people</span><span class=\"note\">Literally “children”</span>of Israel,” <span class=\"supplied\">is</span> the declaration of my Lord Adonai.'),
('LEB', 'Amos', '4', '6', '1', '“And I<span class=\"note\">Emphatic use of personal pronoun</span>in turn gave you cleanness of teeth in all your cities and lack of bread in all your places. Yet you did not return to me,” <span class=\"supplied\">is</span> the declaration of Adonai.'),
('LEB', 'Amos', '4', '7', '1', '“And I also withheld the rain from you when <span class=\"supplied\">there were</span> still three months to the harvest. And I would send rain on one city and send no rain on another city. One tract of land will be rained on, and <span class=\"supplied\">the</span> tract of land <span class=\"idiom\">on which it does not rain</span><span class=\"note\">Literally “which does not rain down on it”</span>will dry up.'),
('LEB', 'Amos', '4', '8', '1', 'So two <span class=\"supplied\">or</span> three cities wandered to one city to drink water and they were not satisfied, yet you did not return to me,” <span class=\"supplied\">is</span> the declaration of Adonai.'),
('LEB', 'Amos', '4', '9', '1', '“I struck you with blight and with mildew. Frequently the cutting locust devoured your gardens and your vineyards and your fig trees and your olive trees, yet you did not return to me,” <span class=\"supplied\">is</span> the declaration of Adonai.'),
('LEB', 'Amos', '4', '10', '1', '“I sent among you a plague in the manner of Egypt; I killed your young men with the sword, along with the captivity of your horses. And I made the stench of your camps go up into your nostrils, yet you did not return to me,” <span class=\"supplied\">is</span> the declaration of Adonai.'),
('LEB', 'Amos', '4', '11', '1', '“I overthrew some of you as God overthrew Sodom and Gomorrah, and you were as a stick snatched from <span class=\"supplied\">the</span> fire, and yet you did not return to me,” <span class=\"supplied\">is</span> the declaration of Adonai.'),
('LEB', 'Amos', '4', '12', '1', '“Therefore, thus I will do to you, <span class=\"supplied\">O</span> Israel. Because I will do this to you, O Israel, prepare to meet your God!'),
('LEB', 'Amos', '4', '13', '1', 'Yes, here is the one who forms <span class=\"supplied\">the</span> mountains, and the one who creates the wind, and the one who reveals to humans what his thoughts <span class=\"supplied\">are</span>, and the one who treads on the heights of the earth; Adonai, the God of hosts, <span class=\"supplied\">is</span> his name!”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '5', '1', '1', '<span class=\"verse-title\">A Lament and Call to Repentance</span>Hear this word that I <span class=\"supplied\">am</span> going to intone over you <span class=\"supplied\">as</span> a lament, O house of Israel!'),
('LEB', 'Amos', '5', '2', '1', 'Virgin Israel has fallen and will not rise again. She is deserted on her land; there is no one to raise her up.'),
('LEB', 'Amos', '5', '3', '1', 'For thus says my Lord Adonai, “The city that marches out <span class=\"supplied\">with</span> a thousand will <span class=\"supplied\">only</span> have a hundred left. And the one that marches out <span class=\"supplied\">with</span> a hundred will <span class=\"supplied\">only</span> have ten left for the house of Israel.”'),
('LEB', 'Amos', '5', '4', '1', 'For thus says Adonai to the house of Israel, “Seek me so that you may live.”'),
('LEB', 'Amos', '5', '5', '1', 'But do not seek Bethel or go <span class=\"supplied\">to</span> Gilgal or cross over to Beersheba, for Gilgal will certainly go into exile and Bethel will come to disaster.”'),
('LEB', 'Amos', '5', '6', '1', 'Seek Adonai so that you may live, so that he will not break out like a fire <span class=\"supplied\">against</span> the house of Joseph! And it will devour, <span class=\"idiom\">with none to quench</span><span class=\"note\">Literally “and there is not one to quench”</span><span class=\"supplied\">it</span> for Bethel.'),
('LEB', 'Amos', '5', '7', '1', '<span class=\"supplied\">Ah,</span> you who turn justice into wormwood and hurl righteousness to the ground!'),
('LEB', 'Amos', '5', '8', '1', 'The one who made the Pleiades and Orion and who turns deep darkness into the morning and darkens day <span class=\"supplied\">into</span> night, the one who calls for the waters of the sea and pours them out on the surface of the earth, Adonai <span class=\"supplied\">is</span> his name!'),
('LEB', 'Amos', '5', '9', '1', 'The one who makes destruction flash upon <span class=\"supplied\">the</span> fierce, <span class=\"idiom\">so that</span><span class=\"note\">Literally “and”</span>destruction comes upon <span class=\"supplied\">the</span> fortification.'),
('LEB', 'Amos', '5', '10', '1', 'They hate the one who reproves in the gate and they abhor the one who speaks honestly.'),
('LEB', 'Amos', '5', '11', '1', 'Therefore, because you trample on <span class=\"supplied\">the</span> poor and you take a grain tax from them, you built houses of dressed stone, but you will not live in them. You built vineyards of delightfulness, but you will not drink their wine.'),
('LEB', 'Amos', '5', '12', '1', 'For I know your transgressions <span class=\"supplied\">are</span> many and your sins <span class=\"supplied\">are</span> numerous, <span class=\"supplied\">you</span> foes of <span class=\"supplied\">the</span> righteous, those who take a bribe, and <span class=\"idiom\">those who</span><span class=\"note\">Literally “they”</span>push aside <span class=\"supplied\">the</span> poor <span class=\"supplied\">ones</span> in the gate!'),
('LEB', 'Amos', '5', '13', '1', 'Therefore, whoever has insight will keep silent in that time, for it <span class=\"supplied\">is</span> a time of evil.'),
('LEB', 'Amos', '5', '14', '1', 'Seek good and not bad in order that you may live, and so Adonai, the God of hosts, will be with you, as you have said.'),
('LEB', 'Amos', '5', '15', '1', 'Hate evil and love good and establish justice in the gate; perhaps Adonai, the God of hosts, will be gracious <span class=\"supplied\">to</span> the remnant of Joseph.'),
('LEB', 'Amos', '5', '16', '1', 'Therefore, thus says Adonai, the God of hosts, my Lord, “In all <span class=\"supplied\">of</span> the public squares <span class=\"supplied\">there will be</span> wailing, and in all <span class=\"supplied\">of</span> the streets <span class=\"supplied\">they will say</span>, ‘Alas, alas, alas!’ They shall call <span class=\"supplied\">the</span> farmers to mourning and <span class=\"supplied\">to</span> wailing, to those who are skilled <span class=\"supplied\">in</span> lamentation.'),
('LEB', 'Amos', '5', '17', '1', 'And in all <span class=\"supplied\">of the</span> vineyards <span class=\"supplied\">there will be</span> wailing, because I will pass in your midst,” says Adonai.'),
('LEB', 'Amos', '5', '18', '3', '<span class=\"verse-title\">The Day of Adonai</span>Alas, those who desire the day of Adonai, why <span class=\"supplied\">is</span> this for you the day of Adonai? It <span class=\"supplied\">will be</span> darkness and not light!'),
('LEB', 'Amos', '5', '19', '3', '<span class=\"supplied\">It will be</span> as <span class=\"supplied\">if</span> a man fled from a lion and a bear met him; or he went <span class=\"supplied\">into</span> the house and leaned his hand against the wall and a snake bit him.'),
('LEB', 'Amos', '5', '20', '3', '<span class=\"supplied\">Is</span> not the day of Adonai darkness and not light, and pitch dark with no brightness in it?'),
('LEB', 'Amos', '5', '21', '3', '“I hate, I despise your festivals, and I take no delight in your assemblies.'),
('LEB', 'Amos', '5', '22', '3', 'Yes, <span class=\"supplied\">even</span> if you offer me your burnt offerings and grain offerings, I will not accept <span class=\"supplied\">them</span>, and I will not look at the fellowship offerings of your fattened animals.'),
('LEB', 'Amos', '5', '23', '3', 'Remove from me the noise of your songs, and I do not want to hear the melody of your harps!'),
('LEB', 'Amos', '5', '24', '3', 'But let justice roll on like the water, and righteousness like an ever-flowing stream.'),
('LEB', 'Amos', '5', '25', '3', 'Did you bring to me sacrifices and offering<span class=\"supplied\">s</span> those forty years in the desert, O house of Israel?'),
('LEB', 'Amos', '5', '26', '3', 'And you will take up Sikkuth, your king, and Kaiwan, your images, the star of your gods which you made for yourselves.'),
('LEB', 'Amos', '5', '27', '3', 'And I will deport you beyond Damascus,” says Adonai—the God of hosts <span class=\"supplied\">is</span> his name.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '6', '1', '1', '<span class=\"verse-title\">Woe to the Complacent</span>Alas <span class=\"supplied\">for</span> those being at ease in Zion, and those who feel secure on Mount Samaria, the notables of the best of the nations! The house of Israel resorts to them.'),
('LEB', 'Amos', '6', '2', '1', 'Cross over <span class=\"supplied\">to</span> Calneh and see, and go from there <span class=\"supplied\">to</span> Hamath Rabbah and go down <span class=\"supplied\">to</span> Gath of the Philistines. <span class=\"supplied\">Are</span> you better than these kingdoms, or is their territory greater than your territory?'),
('LEB', 'Amos', '6', '3', '1', 'You that put off the day of disaster and bring near a reign of violence!'),
('LEB', 'Amos', '6', '4', '1', '<span class=\"supplied\">Alas for</span> those who lie on beds of ivory and lounge on their couches, and those eating young rams from <span class=\"supplied\">the</span> sheep and goats, and bull-calves from the middle of <span class=\"supplied\">the</span> animal stall.'),
('LEB', 'Amos', '6', '5', '1', '<span class=\"supplied\">Alas for those</span> who sing to the tune of the harp; like David they improvise on instruments of music.'),
('LEB', 'Amos', '6', '6', '1', '<span class=\"supplied\">Alas for those</span> who drink from sprinkling bowls of wine and anoint themselves with the best of olive oils and are not grieved over the ruin of Joseph.'),
('LEB', 'Amos', '6', '7', '1', 'Therefore, they shall now go into exile at the head of the exiles and the feast of lounging shall pass away.'),
('LEB', 'Amos', '6', '8', '3', '<span class=\"verse-title\">Adonai Abhors Israel’s Pride</span>My Lord Adonai has sworn by himself, <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai, the God of hosts: “I abhor the pride of Jacob and I hate his citadel fortresses and I will deliver <span class=\"supplied\">the</span> city and its fullness!”'),
('LEB', 'Amos', '6', '9', '3', 'And then if ten people remain in one house, they too will die.'),
('LEB', 'Amos', '6', '10', '3', 'And <span class=\"supplied\">if</span> one’s relative, who burns <span class=\"supplied\">the body</span>, lifts it up and brings the body out of the house and he will say to someone in the innermost part of the house, “<span class=\"supplied\">Are there</span> any more with you?” and he will say, “None,” then he will say, “Silence,” because <span class=\"supplied\">we</span> must not invoke the name of Adonai.'),
('LEB', 'Amos', '6', '11', '3', 'Look, Adonai <span class=\"supplied\">is</span> going to command and the great house will be destroyed <span class=\"supplied\">to</span> bits and the little house <span class=\"supplied\">to</span> pieces.'),
('LEB', 'Amos', '6', '12', '3', 'Do horses run on rocks, or does one plow the sea with oxen?<span class=\"note\">Or “does one plow them with oxen”</span>But you have turned justice into poison and <span class=\"supplied\">the</span> fruit of righteousness into wormwood!'),
('LEB', 'Amos', '6', '13', '3', '<span class=\"supplied\">You</span> who rejoice over Lo-Debar, who say, “Have we not taken Karnaim for ourselves by our strength?”'),
('LEB', 'Amos', '6', '14', '3', 'Indeed, I <span class=\"supplied\">am</span> going to raise up against you a nation, O house of Israel, <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai, the God of hosts. And they shall oppress you from Lebo-hamath up to the wadi of the Arabah.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '7', '1', '1', '<span class=\"verse-title\">Warning Visions</span>This is what my Lord Adonai showed me, and look, <span class=\"supplied\">he</span> is going to form locusts at the beginning of the sprouting of the second crop, and look, after the mowings of the king.'),
('LEB', 'Amos', '7', '2', '1', 'And then when they<span class=\"note\">Hebrew “he/it”</span>finished eating the vegetation of the land, I said, “O Lord Adonai, please forgive! How can Jacob stand, because he <span class=\"supplied\">is</span> small?”'),
('LEB', 'Amos', '7', '3', '1', 'Adonai relented concerning this. “It will not be,” said Adonai.'),
('LEB', 'Amos', '7', '4', '1', 'This is what my Lord Adonai showed me, and look, my Lord Adonai was going to call for a legal case with fire, and it devoured the great deep and it ate up the plots of ground.'),
('LEB', 'Amos', '7', '5', '1', 'Then I said, “<span class=\"supplied\">O</span> Lord Adonai, please stop! How can Jacob stand, because he <span class=\"supplied\">is</span> small?”'),
('LEB', 'Amos', '7', '6', '1', 'Adonai also relented concerning this. “This also will not be,” said my Lord Adonai.'),
('LEB', 'Amos', '7', '7', '1', 'This is what he showed me: Behold, my Lord <span class=\"supplied\">was</span> standing beside a wall <span class=\"supplied\">built with</span> a plummet, and a plummet <span class=\"supplied\">was</span> in his hand.'),
('LEB', 'Amos', '7', '8', '1', 'And Adonai said to me, “What do you see?” And I said, “A plummet.” And my Lord said, “Look, I <span class=\"supplied\">am</span> going to set a plummet in the midst of my people, Israel. I will not pass them by again.'),
('LEB', 'Amos', '7', '9', '1', 'The high places of Isaac shall become desolate and the sanctuaries of Israel shall be laid waste. And I will rise against the house of Jeroboam with the sword.”'),
('LEB', 'Amos', '7', '10', '3', '<span class=\"verse-title\">Amaziah’s Opposition</span>Then Amaziah the priest of Bethel sent to Jeroboam the king of Israel, saying, “Amos has conspired against you in the midst of the house of Israel. The land is not able to endure all of his words.'),
('LEB', 'Amos', '7', '11', '3', 'For this Amos has said, ‘Jeroboam will die by the sword and Israel will certainly go into exile <span class=\"supplied\">away</span> from his land.’ ”'),
('LEB', 'Amos', '7', '12', '3', 'And Amaziah said to Amos, “<span class=\"supplied\">O</span> seer, go, flee to the land of Judah and earn food there and prophesy there!”'),
('LEB', 'Amos', '7', '13', '3', 'But do not prophesy again at Bethel, because this <span class=\"supplied\">is</span> a sanctuary of a king and this <span class=\"supplied\">is</span> a temple of a kingdom.”'),
('LEB', 'Amos', '7', '14', '3', 'And Amos answered and said to Amaziah, “I am not a prophet and I <span class=\"supplied\">am</span> not a son of a prophet, but I <span class=\"supplied\">am</span> a herdsman and I am one taking care of sycamore trees.'),
('LEB', 'Amos', '7', '15', '3', 'And Adonai took me from <span class=\"supplied\">following</span> behind the sheep and goats and Adonai said to me, “Go, prophesy to my people Israel!'),
('LEB', 'Amos', '7', '16', '3', 'And so then, hear the word of Adonai! You are saying, ‘You must not prophesy against Israel and you must not preach against the house of Isaac!’'),
('LEB', 'Amos', '7', '17', '3', 'Therefore, thus says Adonai, ‘Your wife will become a prostitute in the city and your sons and your daughters will fall by the sword and your land will be divided with a line, and you<span class=\"note\">Emphatic second person pronoun</span>will die in an unclean land and Israel will surely go into exile from this land.’ ”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '8', '1', '1', '<span class=\"verse-title\">A Basket of Ripe Fruit</span>My Lord Adonai showed me this, and there was a basket of summer fruit.'),
('LEB', 'Amos', '8', '2', '1', 'And he said, “What do you see, Amos?” And I said, “A basket of summer fruit.” And Adonai said to me, “The end has come upon my people Israel. I will not pass by them again!”'),
('LEB', 'Amos', '8', '3', '1', '“And the songs of the temple shall become wailings in that day,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>my Lord Adonai. “The corpses are numerous; he throws them in every place. Be quiet!”'),
('LEB', 'Amos', '8', '4', '1', 'Hear this, those who trample on <span class=\"supplied\">the</span> poor and who annihilate the afflicted of <span class=\"supplied\">the</span> land,'),
('LEB', 'Amos', '8', '5', '1', 'saying, “When will the new moon be over, so that we can sell grain? And the Sabbath, so that we can open the grain bins, that we can make <span class=\"supplied\">the</span> ephah small and make <span class=\"supplied\">the</span> shekel large, and can practice deceit <span class=\"supplied\">with</span> a set of scales of deceit?'),
('LEB', 'Amos', '8', '6', '1', '<span class=\"idiom\">That we can</span><span class=\"note\">Literally “to buy”</span>buy <span class=\"supplied\">the</span> powerless with silver and <span class=\"supplied\">the</span> poor for the sake of a pair of sandals, and we can sell the waste of the grain?”'),
('LEB', 'Amos', '8', '7', '1', 'Adonai has sworn by the pride of Jacob, “Surely I will never forget any of their deeds!'),
('LEB', 'Amos', '8', '8', '1', 'On account of this, will not the land tremble and will not every living <span class=\"supplied\">thing</span> in it mourn? And all of it will rise like the Nile and it will be tossed about and subside like the Nile of Egypt.'),
('LEB', 'Amos', '8', '9', '1', 'And then in that day,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>my Lord Adonai, “I<span class=\"note\">Literally “and I”</span>will make the sun go down at noon and I will darken the land on a day of light.'),
('LEB', 'Amos', '8', '10', '1', 'And I will turn your feasts into mourning and all of your songs into lament, and I will put sackcloth on all loins and baldness on every head. And I will make it like the mourning for an only child, and its end like a bitter day.'),
('LEB', 'Amos', '8', '11', '1', 'Look, the days are coming,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>my Lord Adonai, “when I will send a famine in the land, not a famine for bread and not a thirst for water, but <span class=\"idiom\">of hearing</span><span class=\"note\">Literally “but if to hear”</span>the words of Adonai!'),
('LEB', 'Amos', '8', '12', '1', 'And they will wander from sea to sea and from <span class=\"supplied\">the</span> north and to <span class=\"supplied\">the</span> east. They will roam about to seek the word of Adonai, but they will not find <span class=\"supplied\">it</span>!'),
('LEB', 'Amos', '8', '13', '1', 'In that day the beautiful young women and the young men will faint because of thirst.'),
('LEB', 'Amos', '8', '14', '1', '<span class=\"supplied\">These are</span> those who swear by the guilt of Samaria and say, ‘By the life of your gods, O Dan,’ and ‘By the life of the way of Beersheba,’ they will fall and they will not rise again.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Amos', '9', '1', '1', '<span class=\"verse-title\">Destruction of Israel</span>I saw my Lord standing by the altar and he said, “Strike the capitals so that the thresholds will shake, and shatter them on the head of all of them, and I will kill the rest of them with the sword. A fugitive belonging to them will not run away, and a survivor belonging to them will not escape.'),
('LEB', 'Amos', '9', '2', '1', 'If they dig into Sheol, from there my hand will take them, and <span class=\"supplied\">even</span> if they climb up <span class=\"supplied\">to</span> heaven, from there I will bring them down.'),
('LEB', 'Amos', '9', '3', '1', 'And <span class=\"supplied\">even</span> if they hide themselves on the top of Carmel, from there I will search and will take them, and <span class=\"supplied\">even</span> if they hide from before my eyes at the bottom of the sea, from there I will command the sea serpent and it will bite them.'),
('LEB', 'Amos', '9', '4', '1', 'And <span class=\"supplied\">even</span> if they go into captivity before their enemies, from there I will command the sword and it will kill them, and I will fix my eyes on them for harm and not for good.”'),
('LEB', 'Amos', '9', '5', '1', 'And <span class=\"supplied\">thus will do</span> the Lord Adonai of hosts, who touches the earth and it melts, and all of those living in it mourn, and all of it rises like the Nile and it sinks down like <span class=\"supplied\">the</span> Nile of Egypt,'),
('LEB', 'Amos', '9', '6', '1', 'who builds his upper chambers in the heavens and lays the foundation of his vault on the earth, who calls for the waters of the sea and pours them on the surface of the earth—Adonai is his name.'),
('LEB', 'Amos', '9', '7', '1', '“Are you not like the Cushites to me, O people of Israel?” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai. “Did I not bring up Israel from the land of Egypt and <span class=\"supplied\">the</span> Philistines from Caphtor and <span class=\"idiom\">the Arameans</span><span class=\"note\">Literally “Aram”</span>from Kir?'),
('LEB', 'Amos', '9', '8', '1', 'Look, the eyes of my Lord Adonai <span class=\"supplied\">are</span> on the kingdom of sin, and I will destroy it from the surface of the earth. However, I will not utterly destroy the house of Jacob,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai.'),
('LEB', 'Amos', '9', '9', '1', '“Yes, look, I <span class=\"supplied\">am</span> going to command and I will shake the house of Israel among all the nations like one who shakes with a sieve, but not a pebble will fall <span class=\"supplied\">to the</span> ground.'),
('LEB', 'Amos', '9', '10', '1', 'All the sinners of my people will die by the sword, who say, ‘Evil will not overtake or confront us.’'),
('LEB', 'Amos', '9', '11', '3', '<span class=\"verse-title\">Restoration of Israel</span>On that day I will raise up the booth of David that is fallen, and I will repair its breaches and will raise up its ruins and will build it like the days of old.'),
('LEB', 'Amos', '9', '12', '3', 'Thus they may take possession of the remnant of Edom and all the nations <span class=\"idiom\">who are called by my name</span>,”<span class=\"note\">Literally “who my name is called over them”</span><span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai, <span class=\"supplied\">who</span> does this.'),
('LEB', 'Amos', '9', '13', '3', '“Look, days are coming,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai, “when <span class=\"supplied\">the one who</span> plows will overtake <span class=\"supplied\">the one who</span> reaps, the one who treads grapes <span class=\"supplied\">will catch up</span> with the one who sows the seed. And the mountains will drip sweet wine and all of the hills will flow <span class=\"supplied\">with it</span>.'),
('LEB', 'Amos', '9', '14', '3', 'And I will restore the fortunes of my people Israel, and they will rebuild <span class=\"supplied\">the</span> desolated cities and will inhabit <span class=\"supplied\">them</span>. And they will plant vineyards and will drink their wine, and they will make gardens and will eat their fruit.'),
('LEB', 'Amos', '9', '15', '3', 'And I will plant them on their land and they will not be uprooted again from their land that I have given to them,” says Adonai your God.')
;

