INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '1', '1', '1', '<span class=\"verse-title\">The King’s Banquets</span>And it happened in the days of Ahasuerus, the Ahasuerus who reigned from India to Cush<span class=\"note\">That is, “Ethiopia”</span>—<span class=\"supplied\">over</span> one hundred and twenty-seven provinces.<span class=\"note\">Hebrew “province”</span>'),
('LEB', 'Esther', '1', '2', '1', 'In those days as King Ahasuerus was sitting on the throne of his kingdom, which <span class=\"supplied\">was</span> in the citadel of Susa,'),
('LEB', 'Esther', '1', '3', '1', 'he gave a banquet in the third year of his reign for all his officials and servants. The army of Persia and Media and the nobles and officials of the provinces were in his presence'),
('LEB', 'Esther', '1', '4', '1', 'as he displayed the wealth of the glory of his kingdom and the glorious splendor of his greatness <span class=\"supplied\">for</span> many days, one hundred and eighty days<span class=\"note\">Hebrew “day”</span>.'),
('LEB', 'Esther', '1', '5', '2', 'And when those days were completed, the king gave for all the people that were present at the citadel of Susa, both great and small, a banquet in the courtyard of the king’s palace garden that lasted seven days.'),
('LEB', 'Esther', '1', '6', '2', 'There were curtains of finely woven linen and blue cloth tied with cords of fine white linen and purple cloth to silver curtain rings and pillars of alabaster, <span class=\"supplied\">and</span> couches of gold and silver on a paved floor of alabaster, precious stone, mother-of-pearl, and costly stones.<span class=\"note\">Hebrew “stone”</span>'),
('LEB', 'Esther', '1', '7', '2', 'Drinks were served in goblets of gold and <span class=\"idiom\">goblets of different kinds</span>,<span class=\"note\">“goblets from changing goblets”</span>and <span class=\"supplied\">there was</span> <span class=\"idiom\">plentiful royal wine according to the bounty of the king</span>.<span class=\"note\">“much wine of the kingdom according to the hand of the king”</span>'),
('LEB', 'Esther', '1', '8', '2', 'There were no restrictions on the drinking, for the king had instructed every official of his palace to do as each one pleased.'),
('LEB', 'Esther', '1', '9', '2', 'Furthermore, Queen Vashti gave a banquet for the women <span class=\"supplied\">in</span> <span class=\"idiom\">the palace</span><span class=\"note\">“<span class=\"supplied\">in</span> the house of the reign” or “<span class=\"supplied\">in</span> the house of the kingdom”</span>that belonged to King Ahasuerus.'),
('LEB', 'Esther', '1', '10', '4', '<span class=\"verse-title\">Queen Vashti Refuses the King’s Request</span>On the seventh day, when the heart of the king was merry with wine, he said to Mehuman, Biztha, Harbona, Bigtha, Abagtha, Zethar, and Carcas, seven of the eunuchs attending King Ahasuerus,'),
('LEB', 'Esther', '1', '11', '4', 'to bring Queen Vashti before the king <span class=\"idiom\">with her royal crown</span><span class=\"note\">“with <span class=\"supplied\">her</span> headdress of <span class=\"supplied\">the</span> kingdom”</span>to show the people and the officials her beauty, <span class=\"idiom\">for she was very attractive</span>.<span class=\"note\">“for she <span class=\"supplied\">was</span> of good appearance”</span>'),
('LEB', 'Esther', '1', '12', '4', 'But Queen Vashti refused to come at the word of the king that <span class=\"supplied\">was</span> <span class=\"idiom\">conveyed by</span><span class=\"note\">“by the hand of”</span>the eunuchs. And the king became very angry, and his anger burned in him.'),
('LEB', 'Esther', '1', '13', '5', 'And the king said to the wise men, <span class=\"idiom\">the ones who know the times</span><span class=\"note\">“the knowers of the times”</span>—for it <span class=\"supplied\">was</span> the procedure of the king before all those who knew law and rights;<span class=\"note\">Or “custom and legalities”</span>'),
('LEB', 'Esther', '1', '14', '5', 'and those next to him were Carshena, Shethar, Admatha, Tarshish, Meres, Marsena, Memucan, the seven officials of Persia and Media who <span class=\"idiom\">had access to the king</span><span class=\"note\">“saw the face of the king”</span>and sat first in the kingdom—'),
('LEB', 'Esther', '1', '15', '5', '“According to <span class=\"supplied\">the</span> law, what is to be done with Queen Vashti, because she has not done the command of King Ahasuerus <span class=\"idiom\">conveyed by</span><span class=\"note\">“by the hand of”</span>the eunuchs?'),
('LEB', 'Esther', '1', '16', '5', 'And Memucan said before the king and the officials, “Not only has Queen Vashti done wrong to the king, but to all the officials and all of the people who <span class=\"supplied\">are</span> in all the provinces of King Ahasuerus.'),
('LEB', 'Esther', '1', '17', '5', 'For this deed of the queen <span class=\"idiom\">will be known</span><span class=\"note\">“will go out”</span>to all the women, causing them <span class=\"idiom\">to look with contempt on their husbands</span>,<span class=\"note\">“to despise their husbands in their eyes”</span>as they will say, ‘King Ahasuerus commanded Queen Vashti to be brought before him but she did not come!’'),
('LEB', 'Esther', '1', '18', '5', 'This day the women of nobility from Persia and Media will respond to all the officials of the king and there will be no end to contempt and anger.'),
('LEB', 'Esther', '1', '19', '5', '<span class=\"idiom\">If it pleases</span><span class=\"note\">“If it is good to”</span>the king, let <span class=\"idiom\">a royal edict</span><span class=\"note\">“a word of the kingdom”</span>go out from him, and let it be written among the laws of Persia and Media so that it will not be altered, that Vashti cannot come before King Ahasuerus; and let the king give her royal position to her neighbor who <span class=\"supplied\">is</span> better than she.'),
('LEB', 'Esther', '1', '20', '5', 'And let the king’s decree that he will make be proclaimed in all his kingdom, because it <span class=\"supplied\">is</span> vast and all the women will honor their husbands, great and small.”<span class=\"note\">Or “high and low”</span>'),
('LEB', 'Esther', '1', '21', '6', '<span class=\"idiom\">This advice pleased the king</span><span class=\"note\">“The word was good in the eyes of the king</span>and the officials, and the king acted according to the word of Memucan.'),
('LEB', 'Esther', '1', '22', '6', 'And he sent letters to all the provinces of the king, to each province according to its own script, and to every people in their own <span class=\"idiom\">language</span>,<span class=\"note\">“tongue”</span>that every man should be the master of his house and who speaks in the <span class=\"idiom\">language</span><span class=\"note\">“tongue”</span>of his people.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '2', '1', '1', '<span class=\"verse-title\">Esther is Chosen Queen</span>After these things, when the anger of King Ahasuerus subsided, he remembered Vashti and what she had done and what had been decreed against her.'),
('LEB', 'Esther', '2', '2', '1', 'And the king’s servants attending him said, “Let them seek attractive young virgins for the king.'),
('LEB', 'Esther', '2', '3', '1', 'Let the king appoint chief officers in all the provinces of his kingdom, and let them gather every attractive young virgin to the <span class=\"idiom\">harem</span><span class=\"note\">“house of the women”</span>in the citadel of Susa <span class=\"idiom\">under the care of</span><span class=\"note\">“to the hand of”</span>Hegai, the king’s eunuch, who is in charge of the women; and let him give <span class=\"supplied\">them</span> their beauty treatment.'),
('LEB', 'Esther', '2', '4', '1', 'And let the young woman <span class=\"idiom\">who is pleasing</span><span class=\"note\">“who is good”</span>in the king’s eyes become queen in place of Vashti. The thing was good in the king’s eyes, and he acted accordingly.'),
('LEB', 'Esther', '2', '5', '2', 'There was a Jew in the citadel of Susa whose name <span class=\"supplied\">was</span> Mordecai son of Jair, son of Shimei, son of Kish, a Benjaminite,'),
('LEB', 'Esther', '2', '6', '2', 'who was deported<span class=\"note\">Or “exiled”</span>from Jerusalem with the exiles<span class=\"note\">Hebrew “exile”</span>who were deported<span class=\"note\">Or “exiled”</span>with Jeconiah<span class=\"note\">A variant spelling of “Jehoiachin”</span>the king of Judah, whom King Nebuchadnezzar of Babylon had deported.<span class=\"note\">Or “exiled”</span>'),
('LEB', 'Esther', '2', '7', '2', 'He<span class=\"note\">That is, Mordecai</span>was raising Hadassah, that <span class=\"supplied\">is</span> Esther, his uncle’s daughter,<span class=\"note\">That is, his cousin</span>for she did not have a father or a mother; the young woman <span class=\"supplied\">had</span> a beautiful figure and <span class=\"supplied\">was</span> very attractive. When her father and mother died, Mordecai had taken her as his daughter.'),
('LEB', 'Esther', '2', '8', '2', 'And it happened, at the proclaiming of the edict of the king and his law, when many young women were being gathered to the citadel of Susa <span class=\"idiom\">under Hegai’s care</span>,<span class=\"note\">“to the hand of Hegai”</span>Esther was taken to the <span class=\"idiom\">king’s palace</span><span class=\"note\">“house of the king”</span><span class=\"idiom\">under the care of</span><span class=\"note\">“to the hand of”</span>Hegai who was in charge of the women.'),
('LEB', 'Esther', '2', '9', '2', '<span class=\"idiom\">The young woman pleased him</span><span class=\"note\">“the young woman was good in his eyes”</span>and she won favor in his presence, and he quickly provided for her beauty treatment and her portion of food, with seven chosen maids to give to her from the <span class=\"idiom\">king’s palace</span>,<span class=\"note\">“house of the king”</span>and he advanced her and her maids to the best part of the <span class=\"idiom\">harem</span>.<span class=\"note\">“house of the women”</span>'),
('LEB', 'Esther', '2', '10', '2', 'Esther did not disclose her people and her family because Modecai had charged her that she must not tell.'),
('LEB', 'Esther', '2', '11', '2', 'And every day Modecai would walk up and down in front of the courtyard of the <span class=\"idiom\">harem</span><span class=\"note\">“house of the women”</span>to learn <span class=\"idiom\">how Esther was doing</span>.<span class=\"note\">“the peace of Esther and how it does/does with her”</span>'),
('LEB', 'Esther', '2', '12', '3', 'When the turn came for each girl to go to King Ahasuerus, after the end of twelve months of being under the regulations of the women—for the days of their beauty treatments had to be filled, six months with the oil of myrrh and six months with perfumes and women’s cosmetics—'),
('LEB', 'Esther', '2', '13', '3', 'in this way, the girl goes to the king and all that she asks is given to her <span class=\"idiom\">to take</span><span class=\"note\">“to go”</span>with her from the <span class=\"idiom\">harem</span><span class=\"note\">“house of the women”</span>to the <span class=\"idiom\">king’s palace</span>.<span class=\"note\">“house of the king”</span>'),
('LEB', 'Esther', '2', '14', '3', 'In the evening she would go and in the morning she would return to the <span class=\"idiom\">second harem</span><span class=\"note\">“second house of the women”</span><span class=\"idiom\">under the care of</span><span class=\"note\">“to the hand of”</span>Shaashgaz, the king’s eunuch in charge of the concubines. She would not go back to the king unless the king delighted in her and she was called by name.'),
('LEB', 'Esther', '2', '15', '4', 'When the turn came near for Esther daughter of Abihail the uncle of Mordecai, who had taken <span class=\"supplied\">her</span> as a daughter, to go to the king, she did not ask anything except what Hegai the eunuch of the king who was in charge of the women, advised. And Esther carried favor in the eyes of everyone that saw her.'),
('LEB', 'Esther', '2', '16', '4', 'Esther was taken to King Ahasuerus, to his <span class=\"idiom\">palace</span>,<span class=\"note\">“house of the reign” or “house of the kingdom”</span>in the tenth month that is Tebeth in the seventh year of his reign.'),
('LEB', 'Esther', '2', '17', '4', 'And the king loved Esther more than all the women, and she won his favor and loyalty more than all the virgins, so he put a <span class=\"idiom\">royal crown</span><span class=\"note\">“crown of the kingdom”</span>on her head and made her queen instead of Vashti.'),
('LEB', 'Esther', '2', '18', '4', 'And the king gave a great banquet, Esther’s banquet, for all his officials and servants. And he granted a tax amnesty<span class=\"note\">See HALOT 252–253 s.v.</span>to the provinces and he gave gifts with royal liberality.'),
('LEB', 'Esther', '2', '19', '6', '<span class=\"verse-title\">A Plot Against the King</span>When <span class=\"supplied\">the</span> virgins were gathered a second time, Mordecai <span class=\"supplied\">was</span> sitting at the gate of the king.'),
('LEB', 'Esther', '2', '20', '6', 'Esther had not made known her family and her people, just as Mordecai had instructed her; for Esther <span class=\"idiom\">did what Mordecai told her</span>,<span class=\"note\">“did the word of Mordecai”</span>just as when she was brought up by him.'),
('LEB', 'Esther', '2', '21', '6', 'In those days Mordecai <span class=\"supplied\">was</span> sitting at the gate of the king. Bigthana and Teresh, two of the king’s eunuchs from the keepers of the threshold, became angry and they conspired <span class=\"idiom\">to assassinate</span><span class=\"note\">“to send a hand against”</span>King Ahasuerus.'),
('LEB', 'Esther', '2', '22', '6', 'And the matter became known to Mordecai and he told <span class=\"supplied\">it</span> to Queen Esther, and Esther told <span class=\"supplied\">it</span> to the king in the name of Mordecai.'),
('LEB', 'Esther', '2', '23', '6', 'And the matter was investigated and found <span class=\"supplied\">to be so</span>; and the two of them were hanged on <span class=\"supplied\">the</span> gallows, and it was written in the scroll of the events of the days before the presence of the king.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '3', '1', '1', '<span class=\"verse-title\">Haman is Promoted</span>After these things King Ahasuerus promoted Haman son of Hammedatha the Agagite, and he exalted him and set <span class=\"idiom\">his position</span><span class=\"note\">“his throne”</span>above all the officials who <span class=\"supplied\">were</span> with him.'),
('LEB', 'Esther', '3', '2', '1', 'And all of the king’s servants who <span class=\"supplied\">were</span> at the gate of the king <span class=\"supplied\">were</span> kneeling and bowing down to Haman; for so the king had commanded concerning him, but Mordecai did not kneel and bow down.'),
('LEB', 'Esther', '3', '3', '1', 'And the king’s servants who <span class=\"supplied\">were</span> at the gate of the king said to Mordecai, “Why <span class=\"supplied\">are</span> you transgressing the command of the king?”'),
('LEB', 'Esther', '3', '4', '1', 'They spoke to him day after day, but he did not listen to them, and they informed Haman to see if <span class=\"idiom\">Mordecai’s resolve would prevail</span>;<span class=\"note\">“the word’s of Mordecai would stand”</span>for he had told them that he <span class=\"supplied\">was</span> a Jew.'),
('LEB', 'Esther', '3', '5', '1', 'And Haman saw that Mordecai was not kneeling and bowing down to him, and he was filled <span class=\"supplied\">with</span> anger.'),
('LEB', 'Esther', '3', '6', '1', 'But <span class=\"idiom\">he considered it beneath him</span><span class=\"note\">“he despised it in his eyes”</span>to lay hands on Mordecai only, for they told him of Mordecai’s people, and Haman sought to destroy all the Jews, the people of Mordecai, who <span class=\"supplied\">were</span> in the kingdom of Ahasuerus.'),
('LEB', 'Esther', '3', '7', '2', 'In the first month, that <span class=\"supplied\">is</span>, the month of Nisan, in the twelfth year of King Ahasurus, he cast pur—that <span class=\"supplied\">is</span>, the lot—before the presence of Haman <span class=\"idiom\">for the day and for the month</span>,<span class=\"note\">“from day to day and from month to month”</span>until<span class=\"note\">The Septuagint adds, “and the lot fell on the thirteenth day of”</span>the twelfth month, that <span class=\"supplied\">is</span>, the month of Adar.'),
('LEB', 'Esther', '3', '8', '2', 'And Haman said to King Ahasuerus, “There is a certain people scattered and separated among the peoples in all of the provinces of your kingdom; their laws <span class=\"supplied\">are</span> different from every <span class=\"supplied\">other</span> people, and they do not <span class=\"idiom\">observe</span><span class=\"note\">“do”</span>the laws of the king; it is not appropriate for the king to tolerate them.'),
('LEB', 'Esther', '3', '9', '2', 'If it pleases the king, let a <span class=\"supplied\">decree</span> be issued to destroy them, and I will pay<span class=\"note\">Or “I will weigh”</span>ten thousand talents<span class=\"note\">Hebrew “talent”</span>of silver to those who do the job, to bring to the treasury of the king.”'),
('LEB', 'Esther', '3', '10', '2', 'So the king removed his signet ring from his hand and gave it to Haman son of Hammedatha the Agagite, the enemy of the Jews.'),
('LEB', 'Esther', '3', '11', '2', 'And the king said to Haman, “The money <span class=\"supplied\">is</span> given to you and to the people to do with it <span class=\"idiom\">as you see fit</span>.<span class=\"note\">“as the good <span class=\"supplied\">is</span> in your eyes”</span>'),
('LEB', 'Esther', '3', '12', '3', 'And the king’s secretaries were called in the first month on the thirteenth day, and <span class=\"supplied\">a decree</span> was issued, according to all that Haman commanded, to the satraps of the king and to the governors who <span class=\"supplied\">were</span> over all the provinces, and to <span class=\"supplied\">the</span> officials of all the people, to each province according to <span class=\"supplied\">its own</span> script and to all people according to their own language; <span class=\"supplied\">it was</span> written in the name of King Ahasuerus and <span class=\"supplied\">was</span> sealed with the king’s ring.'),
('LEB', 'Esther', '3', '13', '3', 'Letters <span class=\"supplied\">were</span> sent by couriers<span class=\"note\">Or “by runners”</span>to all the provinces of the king to destroy, to kill, and to annihilate all the Jews, <span class=\"idiom\">both young and old</span>,<span class=\"note\">“from young to old”</span>women and children, on one day, the thirteenth day of the month, that <span class=\"supplied\">is</span> Adar, and to plunder their goods.'),
('LEB', 'Esther', '3', '14', '3', 'A copy of the edict <span class=\"supplied\">was</span> presented <span class=\"supplied\">as</span> law in every province making <span class=\"supplied\">it</span> known to all the people to be ready for that day.'),
('LEB', 'Esther', '3', '15', '3', 'The couriers went out quickly by order of the king, and the law was issued in the citadel of Susa. The king and Haman sat down to drink; and the city of Susa was bewildered.<span class=\"note\">Or “disturbed”</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '4', '1', '1', '<span class=\"verse-title\">Mordecai Tells Esther of Haman’s Plot</span>Mordecai learned all that had been done and he tore his clothes and put on sackcloth and ashes. And he went through the middle of the city and cried out a loud and bitter cry;'),
('LEB', 'Esther', '4', '2', '1', 'he went up to the entrance of the gate of the king, for he could not go to the gate of the king in sackcloth.'),
('LEB', 'Esther', '4', '3', '1', 'In every province <span class=\"supplied\">each</span> place where the king’s edict and his law came, there <span class=\"supplied\">was</span> great mourning for the Jews with fasting, crying, wailing, <span class=\"supplied\">and</span> sackcloth; and ashes were spread out as a bed for them.'),
('LEB', 'Esther', '4', '4', '2', 'And Esther’s maids and her eunuchs came and they told her, and the queen was deeply distressed; she sent garments to clothe Mordecai so that he might remove his sackcloth—but he did not accept <span class=\"supplied\">them</span>.'),
('LEB', 'Esther', '4', '5', '2', 'Then Esther called Hathach from the king’s eunuchs <span class=\"idiom\">who regularly attended to her</span>,<span class=\"note\">“who stood before her presence”</span>and she ordered him <span class=\"supplied\">to go</span> to Mordecai to learn what was happening and why.'),
('LEB', 'Esther', '4', '6', '2', 'So Hathach went out to Mordecai, to the public square of the city, which <span class=\"supplied\">was</span> in front of the gate of the king,'),
('LEB', 'Esther', '4', '7', '2', 'and Mordecai told him all that had happened to him, and the exact amount of money that Haman has promised to pay to the treasury of the king for the destruction of the Jews.'),
('LEB', 'Esther', '4', '8', '2', 'And he gave him a copy of the edict of the law that had been issued in Susa for their destruction to show Esther, and to inform her, and to charge her to go to the king and make supplication to him and entreat before him for her people.'),
('LEB', 'Esther', '4', '9', '3', 'And Hathach went <span class=\"supplied\">back</span> and told Esther the words of Mordecai.'),
('LEB', 'Esther', '4', '10', '3', 'And Esther spoke to Hathach and <span class=\"idiom\">she gave him a message for Mordecai</span>:<span class=\"note\">“she charged him to Mordecai”</span>'),
('LEB', 'Esther', '4', '11', '3', '“All the king’s servants and the people of the king’s provinces know that <span class=\"supplied\">if</span> any man or woman who goes to the king to the inner courtyard, who is not called, he has one law, to be killed, except if the king extends to him the gold scepter so that he may live. I have not been called to come to the king <span class=\"idiom\">for thirty days</span>.”<span class=\"note\">“these thirty days”</span>'),
('LEB', 'Esther', '4', '12', '3', 'And they told Mordecai the words of Esther.'),
('LEB', 'Esther', '4', '13', '3', 'Then Mordecai told <span class=\"supplied\">them</span> to reply to Esther: “Do not think that your life will be saved <span class=\"supplied\">in</span> the palace of the king more than all the Jews.'),
('LEB', 'Esther', '4', '14', '3', 'For if indeed you keep silent at this time, relief and deliverance will arise for the Jews from another place, and you and the family of your father will perish. Who knows? <span class=\"supplied\">Perhaps</span> you have come to a royal position for a time such as this.”'),
('LEB', 'Esther', '4', '15', '3', 'Esther replied to Mordecai:'),
('LEB', 'Esther', '4', '16', '3', '“Go, gather all the Jews that are found in Susa and fast for me; do not eat or drink <span class=\"supplied\">for</span> three days, both night and day. I and my young girls will fast likewise, and then I will go to the king, which <span class=\"supplied\">is</span> not according to the law; if I perish, I perish.'),
('LEB', 'Esther', '4', '17', '3', 'And Mordecai went away and he did everything that Esther commanded him.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '5', '1', '1', '<span class=\"verse-title\">Esther’s Banquet</span>And it happened, on the third day, and Esther put on royal clothes, and she stood in the inner courtyard of the <span class=\"idiom\">king’s palace</span>,<span class=\"note\">“house of the king”</span>opposite the <span class=\"idiom\">king’s palace</span>;<span class=\"note\">“house of the king”</span>the king <span class=\"supplied\">was</span> sitting on his royal throne in the <span class=\"idiom\">throne room</span><span class=\"note\">“house of the reign” or “house of the kingdom”</span>opposite the doorway of the palace.'),
('LEB', 'Esther', '5', '2', '1', 'When the king saw Queen Esther standing in the courtyard she found favor in his eyes, and the king held out the gold scepter that <span class=\"supplied\">was</span> in his hand to Esther, and Esther approached and touched the top of the scepter.'),
('LEB', 'Esther', '5', '3', '1', 'And the king said to her, “What <span class=\"supplied\">is</span> it, Queen Esther? What <span class=\"supplied\">is</span> your request? It will be given to you—even half the kingdom.”'),
('LEB', 'Esther', '5', '4', '1', 'And Esther said, “If it is good to the king, let the king and Haman come today to the banquet that I have prepared for him.”'),
('LEB', 'Esther', '5', '5', '1', 'And the king said, “Bring Haman quickly <span class=\"idiom\">to fulfill</span><span class=\"note\">“to do”</span>the request of Esther.” So the king and Haman came to the banquet that Esther had prepared.'),
('LEB', 'Esther', '5', '6', '1', 'And the king said to Esther <span class=\"idiom\">while they were drinking wine</span>,<span class=\"note\">“at the meal of wine”</span>“What <span class=\"supplied\">is</span> your petition? It will be given to you. What <span class=\"supplied\">is</span> your request? Even half the kingdom, it will done.'),
('LEB', 'Esther', '5', '7', '1', 'And Esther answered and said, “<span class=\"supplied\">This is</span> my petition and my request.'),
('LEB', 'Esther', '5', '8', '1', 'If I have found favor in the eyes of the king,<span class=\"note\">Or “I have won the favor of the king</span>and if it is good to the king to grant my petition and fulfill my request, let the king and Haman come to the banquet that I will prepare for them tomorrow, and I will do according to the word of the king.'),
('LEB', 'Esther', '5', '9', '2', 'And Haman went out on that day rejoicing and <span class=\"idiom\">feeling good</span>.<span class=\"note\">“good of heart”</span>But when Haman saw Mordecai at the gate of the king, and he did not rise or tremble before him, Haman was filled <span class=\"idiom\">with rage toward</span><span class=\"note\">“rage to”</span>Mordecai.'),
('LEB', 'Esther', '5', '10', '2', 'But Haman controlled himself and went to his house, and he sent <span class=\"supplied\">for</span> and brought his friends and Zeresh his wife.'),
('LEB', 'Esther', '5', '11', '2', 'And Haman recounted to them the splendor of his wealth and the number of his sons and all <span class=\"supplied\">the ways</span> that the king had honored him and promoted him above the officials and king’s servants.'),
('LEB', 'Esther', '5', '12', '2', '<span class=\"idiom\">And Haman added</span>,<span class=\"note\">“And Haman said also”</span>“Esther the Queen did not let <span class=\"supplied\">just anyone</span> come to the banquet that she prepared with the king except me, and I am also invited tomorrow to her <span class=\"supplied\">banquet</span> with the king.'),
('LEB', 'Esther', '5', '13', '2', 'But all this <span class=\"idiom\">fails to satisfy me</span><span class=\"note\">“it is not sufficient for me”</span><span class=\"idiom\">when</span><span class=\"note\">“at every time”</span>I see Mordecai the Jew setting at the gate of the king.”'),
('LEB', 'Esther', '5', '14', '2', 'And Zeresh his wife and all of his friends said to him, “Let them make a gallows fifty cubits<span class=\"note\">Hebrew “cubit”</span>high, and in the morning tell the king, “Let them hang Mordecai on it; then go with the king to the banquet happily.” The advice pleased Haman, so he had the gallows made.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '6', '1', '1', '<span class=\"verse-title\">Mordecai is Honored</span>During that night the king’s sleep escaped <span class=\"supplied\">him</span>, and he gave orders to bring the <span class=\"idiom\">scroll of records and chronicles</span>,<span class=\"note\">“the scroll of remembrance and the events of the days”</span>and they were read before the king.'),
('LEB', 'Esther', '6', '2', '1', 'And it was found written how Mordecai had reported concerning Bigthana and Teresh, two of the king’s eunuchs from the keepers of the threshold who had conspired <span class=\"idiom\">to assassinate</span><span class=\"note\">“to send a hand against”</span>King Ahasuerus.'),
('LEB', 'Esther', '6', '3', '1', 'And the king asked, “What has been done to bestow honor to Mordecai for this?” And the king’s servants who attended him said, “Nothing has been done for him.”'),
('LEB', 'Esther', '6', '4', '1', 'And the king asked, “Who <span class=\"supplied\">is</span> in the courtyard?” Haman had just come to the courtyard of the king’s outer palace to tell the king to hang Mordecai on the gallows that he had prepared for him.'),
('LEB', 'Esther', '6', '5', '1', 'And the king’s servants said to him, “Look! Haman <span class=\"supplied\">is</span> standing in the courtyard.” And the king said, “Let him come.”'),
('LEB', 'Esther', '6', '6', '1', 'And Haman came, and the king said to him, “What <span class=\"supplied\">is</span> to be done for the man whom the king wishes to honor?” And Haman thought to himself, “Whom would the king wish to honor more than me?”'),
('LEB', 'Esther', '6', '7', '1', 'So Haman said to the king, “For a man whom the king wishes to honor,'),
('LEB', 'Esther', '6', '8', '1', 'let them bring <span class=\"idiom\">royal clothing</span><span class=\"note\">“clothing of the kingdom”</span>with which the king has clothed himself, and a horse that the king has ridden, and on whose head a royal head-dress has been given.'),
('LEB', 'Esther', '6', '9', '1', 'And let the clothing and the horse be given <span class=\"idiom\">to the man</span><span class=\"note\">“to the hand of the man”</span>by the officials of the king’s nobles; let them cloth the man whom the king wishes to honor, and let him ride on his horse through the public square of the city, and let them proclaim before him, ‘Thus, it will be done for the man whom the king wishes to honor.’ ”'),
('LEB', 'Esther', '6', '10', '1', 'Then the king said to Haman, “Quickly, take the clothing and the horse, just as you have said, and do so to Mordecai the Jew who sits at the gate of the king; you must not leave out anything from what you have said.”'),
('LEB', 'Esther', '6', '11', '1', 'So Haman took the clothing and the horse, and he clothed Mordecai and let him ride through the public square of the city; and he proclaimed before him, “Thus, it is done to the man whom the king wishes to honor.”'),
('LEB', 'Esther', '6', '12', '2', 'Then Mordecai returned to the gate of the king, and Haman rushed to his house mournful and with his head covered.'),
('LEB', 'Esther', '6', '13', '2', 'And Haman told Zeresh his wife and all his friends all that had happened to him. And his advisers and Zeresh his wife said to him, “If Mordecai, before whom you have begun to fall, <span class=\"supplied\">is</span> <span class=\"idiom\">from the descendants of the Jews</span>,<span class=\"note\">“from seed of the Jews”</span>you will not prevail against him, but will certainly fall before him.”'),
('LEB', 'Esther', '6', '14', '2', 'As they <span class=\"supplied\">were</span> still speaking with him the king’s eunuchs arrived and hurried to bring Haman to the banquet that Esther had prepared.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '7', '1', '1', '<span class=\"verse-title\">Esther’s Banquet</span>So the king and Haman went <span class=\"idiom\">to dine</span><span class=\"note\">“to drink”</span>with Queen Esther.'),
('LEB', 'Esther', '7', '2', '1', 'And the king again said to Esther, on the second day <span class=\"idiom\">while they were drinking</span>,<span class=\"note\">“at the meal of wine”</span>“What <span class=\"supplied\">is</span> your petition, Queen Esther? It will be given to you. What <span class=\"supplied\">is</span> your request? It will be given <span class=\"supplied\">to you</span>—even half the kingdom.”'),
('LEB', 'Esther', '7', '3', '1', 'Then Queen Esther answered, and she said, “If I have found favor in your eyes,<span class=\"note\">Or “If I have won your favor”</span>O king, and if it is good to the king, let my life be given to me at my petition and my people at my request;'),
('LEB', 'Esther', '7', '4', '1', 'I and my people have been sold to be destroyed and killed, to be annihilated. If we had been sold as male and female slaves I would have kept quiet, because this<span class=\"note\">Hebrew “there”</span>is not a need sufficient to trouble the king.”<span class=\"note\">See HALOT 1437, s.v. NRSV translates, “but no enemy can compensate for this damage to the king”</span>'),
('LEB', 'Esther', '7', '5', '1', 'And King Ahasuerus said to Queen Esther, “Who <span class=\"supplied\">is</span> he, and where <span class=\"supplied\">is</span> he, who <span class=\"idiom\">gave himself the right to do this</span>?”<span class=\"note\">“has filled his heart to do so”</span>'),
('LEB', 'Esther', '7', '6', '1', 'And Esther said, “The adversary and enemy <span class=\"supplied\">is</span> this evil Haman!” And Haman was terrified before the king and queen.'),
('LEB', 'Esther', '7', '7', '3', '<span class=\"verse-title\">Haman is Hanged</span>The king rose in his anger <span class=\"idiom\">from the banquet</span><span class=\"note\">“from the banquet of wine”</span><span class=\"supplied\">and went</span> to the palace garden, and Haman stood to beg for his life from Queen Esther, for <span class=\"idiom\">he realized that the king was determined to make an end to his life</span>.<span class=\"note\">“that evil had been determined for him from the king”</span>'),
('LEB', 'Esther', '7', '8', '3', 'And the king returned from the palace garden to the <span class=\"idiom\">banquet hall</span>,<span class=\"note\">“house of the meal of wine”</span><span class=\"supplied\">where</span> Haman <span class=\"supplied\">was</span> lying prostrate on the couch that Esther <span class=\"supplied\">was</span> on, and the king said, “Will he also molest the queen with me in the house?” As the words<span class=\"note\">Hebrew “word”</span>went from the king’s mouth they covered Haman’s face.'),
('LEB', 'Esther', '7', '9', '3', 'And Habrona, one of the eunuchs in the presence of the king, said, “Look, the same gallows that Haman had prepared for Mordecai who spoke good <span class=\"supplied\">for the sake</span> of the king stands at Haman’s house, fifty cubits high.” And the king said, “Hang him on it.”'),
('LEB', 'Esther', '7', '10', '3', 'And they hanged Haman on the gallows that he had prepared for Mordecai, and the anger of the king was abated.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '8', '1', '1', '<span class=\"verse-title\">Mordecai is Promoted</span>On that day King Ahasuerus gave Queen Esther the house of Haman, the enemy of the Jews; and Mordecai came before the king, for Esther had told what he <span class=\"supplied\">was</span> to her.'),
('LEB', 'Esther', '8', '2', '1', 'And the king removed his signet ring that he had taken away from Haman, and he gave it to Mordecai. So Esther set Mordecai over the house of Haman.'),
('LEB', 'Esther', '8', '3', '2', 'And Esther again spoke before the king, and she fell before his feet and wept, pleading for his grace to avert Haman the Agagite’s evil <span class=\"supplied\">plan</span> and the plot that he devised against the Jews.'),
('LEB', 'Esther', '8', '4', '2', 'And the king held out to Esther the scepter of gold, and Esther rose and stood before the king,'),
('LEB', 'Esther', '8', '5', '2', 'and she said, “If it is good to the king, and if I have found favor before him,<span class=\"note\">Or “if I have won his favor”</span>and if the king is pleased with this matter, and <span class=\"idiom\">I have his approval</span>,<span class=\"note\">“I <span class=\"supplied\">am</span> good in his eyes”</span>let <span class=\"supplied\">an edict</span> be written to revoke the letters of the plans of Haman son of Hammedatha the Agagite, which he wrote to destroy the Jews that <span class=\"supplied\">are</span> in all the provinces of the king.'),
('LEB', 'Esther', '8', '6', '2', 'For <span class=\"idiom\">how can I bear</span><span class=\"note\">“how am I able”</span>to look on the disaster that will find my people, and <span class=\"idiom\">how can I bear</span><span class=\"note\">“how am I able”</span>to look on the destruction of my family?”'),
('LEB', 'Esther', '8', '7', '2', 'And King Ahasuerus said to Queen Esther and to Mordecai the Jew, “Look, I have given Haman’s house to Esther, and they have hanged him on the gallows because he <span class=\"idiom\">plotted against</span><span class=\"note\">“sent his hand against”</span>the Jews.'),
('LEB', 'Esther', '8', '8', '2', 'Write <span class=\"idiom\">as you see fit</span><span class=\"note\">“as it <span class=\"supplied\">is</span> good in your eyes”</span>concerning the Jews in the name of the king, and seal <span class=\"supplied\">it</span> with the king’s signet ring; for a decree that is written in the name of the king and sealed with the king’s signet ring cannot be revoked.”'),
('LEB', 'Esther', '8', '9', '3', 'And the secretaries of the king were summoned<span class=\"note\">Or “called”</span>at that time, in the third month, which <span class=\"supplied\">is</span> in the month of Sivan on the twenty-third <span class=\"supplied\">day</span>, and <span class=\"supplied\">an edict</span> was written according to all that Mordecai commanded, to the Jews and to the governors and satraps and officials of the provinces from India to Cush<span class=\"note\">That is, “Ethiopia”</span>—one hundred and twenty-seven provinces<span class=\"note\">Hebrew “province”</span>—each province according to its own script and to every people in their own <span class=\"idiom\">language</span>,<span class=\"note\">“tongue”</span>and to the Jews in their own script and language.'),
('LEB', 'Esther', '8', '10', '3', 'And he wrote in the name of King Ahasuerus, and he sealed <span class=\"supplied\">the letters</span> with the king’s signet ring and sent them<span class=\"note\">Hebrew “the letters”</span>by couriers on horses, riding on royal horses <span class=\"idiom\">bred by</span><span class=\"note\">“sons of”</span>racing mares.<span class=\"note\">See HALOT 1244 s.v.</span>'),
('LEB', 'Esther', '8', '11', '3', '<span class=\"supplied\">In them</span> the king allowed the Jews who <span class=\"supplied\">were</span> in every city to assemble and <span class=\"idiom\">defend their lives</span>,<span class=\"note\">“to stand for their live<span class=\"supplied\">s</span>”</span>to destroy and kill and annihilate any army of any people or province attacking them, including women and children, and to plunder their spoil,'),
('LEB', 'Esther', '8', '12', '3', 'in one day in all the provinces of King Ahasuerus, on the thirteenth <span class=\"supplied\">day</span> of the twelfth month, which is the month of Adar.'),
('LEB', 'Esther', '8', '13', '3', 'A copy of the <span class=\"idiom\">edict</span><span class=\"note\">“writing”</span><span class=\"supplied\">was</span> to be given <span class=\"supplied\">as</span> law in each province to inform all the people, so that the Jews would be ready<span class=\"note\">See HALOT 902 s.v.</span>on that day to avenge themselves from their enemies.'),
('LEB', 'Esther', '8', '14', '3', 'The mounted couriers on the royal horses went out without delay, urged by the king’s word. The law was given in the citadel of Susa.'),
('LEB', 'Esther', '8', '15', '4', 'Mordecai went out from the presence of the king in <span class=\"idiom\">royal clothing</span><span class=\"note\">“clothing of the kingdom”</span>of blue cloth and white linen, and a great crown of gold and a robe of fine white linen and purple, and the city of Susa was shouting and rejoicing.'),
('LEB', 'Esther', '8', '16', '4', 'For the Jews, there was light and gladness, joy and honor.'),
('LEB', 'Esther', '8', '17', '4', 'In every province and city, wherever the king’s edict and his law came, there was gladness and joy for the Jews, a banquet and a <span class=\"idiom\">holiday</span>,<span class=\"note\">“day of good”</span>and many of the people from the country <span class=\"supplied\">were</span> posing as Jews because the fear of the Jews had fallen on them.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '9', '1', '1', '<span class=\"verse-title\">The Jews Destroy Their Enemies</span>In the twelfth month, that <span class=\"supplied\">is</span> the month of Adar, on the thirteenth day, on which the edict of the king arrived and his law was enacted, on the day in which the enemies of the Jews had hoped to gain power over them but was overturned, <span class=\"supplied\">and</span> the Jews gained power against their enemies,'),
('LEB', 'Esther', '9', '2', '1', 'the Jews gathered in their cities in all the provinces of King Ahasuerus <span class=\"idiom\">to strike against</span><span class=\"note\">“to send a hand against”</span>those who sought their destruction, and no one could withstand them,<span class=\"note\">Or “stand in their presence”</span>as the fear of them fell on all the people.'),
('LEB', 'Esther', '9', '3', '1', 'All the officials of the provinces, the satraps, governors, and <span class=\"idiom\">those who did the work of the king</span><span class=\"note\">“the doers of the work who <span class=\"supplied\">were</span> for the king”</span><span class=\"supplied\">were</span> supporting the Jews, because the fear of Mordecai had fallen on them.'),
('LEB', 'Esther', '9', '4', '1', 'For Mordecai <span class=\"supplied\">was</span> high-ranking in the <span class=\"idiom\">king’s palace</span><span class=\"note\">“house of the king”</span>and his fame spread throughout all the provinces as <span class=\"idiom\">Mordecai grew more and more powerful</span>.<span class=\"note\">“the man Mordecai <span class=\"supplied\">was</span> going and becoming great”</span>'),
('LEB', 'Esther', '9', '5', '1', 'The Jews struck down all their enemies with <span class=\"idiom\">the sword</span>,<span class=\"note\">“the striking of <span class=\"supplied\">the</span> sword”</span>killing and destroying <span class=\"supplied\">them</span>; and they did as they pleased with those that hated them.'),
('LEB', 'Esther', '9', '6', '1', 'And in the citadel of Susa the Jews killed and destroyed five hundred men,'),
('LEB', 'Esther', '9', '7', '1', 'and Parshandatha, Dalphon, Aspatha,'),
('LEB', 'Esther', '9', '8', '1', 'Portha, Adalia, Aridatha,'),
('LEB', 'Esther', '9', '9', '1', 'Parmashta, Arisai, Aridai, and Vaizatha,'),
('LEB', 'Esther', '9', '10', '1', 'the ten sons of Haman, the son of Hammedatha, the enemy of the Jews; but they did not <span class=\"idiom\">touch</span><span class=\"note\">“send their hand to”</span>the plunder.'),
('LEB', 'Esther', '9', '11', '2', 'On that day the number of those being killed in the citadel of Susa <span class=\"idiom\">was reported to</span><span class=\"note\">“came before”</span>the king.'),
('LEB', 'Esther', '9', '12', '2', 'And the king said to Queen Esther, “In the citadel of Susa the Jews killed and destroyed five hundred men and the ten sons of Haman. What have they done in the rest of the king’s provinces? What <span class=\"supplied\">is</span> your petition? It will be granted to you. And what further <span class=\"supplied\">is</span> your request? It will be done.”'),
('LEB', 'Esther', '9', '13', '2', 'Esther replied, “If it is good to the king, let tomorrow also be granted to the Jews who <span class=\"supplied\">are</span> in Susa to do according to the edict of today; and let them hang Haman’s ten sons on the gallows.”'),
('LEB', 'Esther', '9', '14', '2', 'And the king said to do so. And a decree was issued in Susa and Haman’s ten sons were hanged.'),
('LEB', 'Esther', '9', '15', '2', 'And the Jews were gathered who <span class=\"supplied\">were</span> in Susa, and on the fourteenth day of the month of Adar and they killed in Susa three hundred men, but they did not <span class=\"idiom\">touch</span><span class=\"note\">“send their hand to”</span>the plunder.'),
('LEB', 'Esther', '9', '16', '3', 'The rest of the Jews who <span class=\"supplied\">were</span> in the king’s provinces gathered and <span class=\"idiom\">defended their lives</span><span class=\"note\">“to stand for their live<span class=\"supplied\">s</span>”</span>and <span class=\"idiom\">found repose</span><span class=\"note\">“rested”</span>from their enemies. And they killed seventy-five thousand of those that hated them, but they did not <span class=\"idiom\">touch</span><span class=\"note\">“send their hand to”</span>the plunder.'),
('LEB', 'Esther', '9', '17', '3', '<span class=\"supplied\">This was</span> on the thirteenth day of the month of Adar. <span class=\"supplied\">They</span> rested on the fourteenth <span class=\"supplied\">day</span> and made it a day of feasting and joy.'),
('LEB', 'Esther', '9', '18', '3', 'But the Jews who <span class=\"supplied\">were</span> in Susa gathered on the thirteenth and on the fourteenth day, and rested on the fifteenth day. And they made it a day of feasting and joy.'),
('LEB', 'Esther', '9', '19', '3', 'Therefore the Jews in the rural <span class=\"supplied\">areas</span>, living in the rural towns, made the fourteenth month of Adar a day of joy and feasting, a festive day of giving gifts to each other.'),
('LEB', 'Esther', '9', '20', '5', '<span class=\"verse-title\">The Feast of Purim</span>Mordecai wrote down these things and he sent letters to all the Jews who <span class=\"supplied\">were</span> in all <span class=\"supplied\">of</span> the provinces of King Ahasuerus, <span class=\"supplied\">both</span> near and far,'),
('LEB', 'Esther', '9', '21', '5', 'to impose on them to keep the fourteenth day of the month of Adar, and the fifteenth <span class=\"supplied\">day</span>, <span class=\"idiom\">every year</span>,<span class=\"note\">“and every year and year”</span>'),
('LEB', 'Esther', '9', '22', '5', 'as the day that the Jews <span class=\"idiom\">found relief</span><span class=\"note\">“rested”</span>from their enemies, and the month which changed for them from sorrow to joy, and from a mourning ceremony to a <span class=\"idiom\">festive day</span>;<span class=\"note\">“a day of good”</span>to make them days of feasting and joy, and giving gifts to each other and to the poor.'),
('LEB', 'Esther', '9', '23', '5', 'And the Jews adopted what they had begun to do and what Mordecai had written to them.'),
('LEB', 'Esther', '9', '24', '6', 'For Haman the son of Hammedatha the Agagite, the enemy of all the Jews had plotted against the Jews to destroy them, and he had cast pur, that <span class=\"supplied\">is</span> the lot, to rout them out and destroy them.'),
('LEB', 'Esther', '9', '25', '6', 'But when it came<span class=\"note\">Or “she came”</span><span class=\"idiom\">to the attention of</span><span class=\"note\">“before”</span>the king, he <span class=\"idiom\">gave orders in writing</span><span class=\"note\">“said with a scroll”</span><span class=\"supplied\">that</span> his evil plot that he had devised against the Jews should return on his head, and they hung him and his sons on the gallows.'),
('LEB', 'Esther', '9', '26', '6', 'Therefore they called these days Purim, because of the name Pur. Thus because of all the words of this letter, and of what they faced concerning this, and of what had happened to them,'),
('LEB', 'Esther', '9', '27', '6', 'the Jews established and adopted <span class=\"supplied\">it</span> for themselves and for their offspring, and for all who joined them. They did not neglect <span class=\"idiom\">to observe</span><span class=\"note\">“to be doing”</span>these two days every year as it was written and appointed to them.'),
('LEB', 'Esther', '9', '28', '6', 'These days <span class=\"supplied\">are</span> to be remembered and <span class=\"supplied\">are</span> to be kept in every generation, and in family, province, and city; and these days of Purim are not <span class=\"supplied\">to be</span> neglected among the Jews, and their memory shall not come to an end among their offspring.'),
('LEB', 'Esther', '9', '29', '7', 'So Queen Esther the daughter of Abihail and Mordecai the Jew wrote in full authority to confirm this second letter of Purim.'),
('LEB', 'Esther', '9', '30', '7', 'He sent letters of words of peace and truth to all the Jews, to the one hundred and twenty-seven provinces<span class=\"note\">Hebrew “province”</span>of Ahasuerus’ kingdom,'),
('LEB', 'Esther', '9', '31', '7', 'to establish these days of Purim at their appointed times, just as Mordecai the Jew and Queen Esther had imposed, and just as they had imposed on themselves and their offspring regulations of the fast and their lament.'),
('LEB', 'Esther', '9', '32', '7', 'And the command of Esther established these practices of Purim, and <span class=\"supplied\">it was</span> written on the scroll.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Esther', '10', '1', '1', '<span class=\"verse-title\">Title</span>King Ahasuerus imposed forced labor on the land and islands of the sea.'),
('LEB', 'Esther', '10', '2', '1', 'All the work of his authority and his <span class=\"idiom\">powerful deeds</span>,<span class=\"note\">“power”</span>and the full accounting of the greatness of Mordecai, to which the king advanced him, are they not written on the scroll of the <span class=\"idiom\">chronicles</span><span class=\"note\">“the events of the days”</span>of the kings of Media and Persia?'),
('LEB', 'Esther', '10', '3', '1', 'For Mordecai the Jew <span class=\"supplied\">was</span> second-in-command to King Ahasuerus. <span class=\"supplied\">He was</span> great for the Jews and popular with many of his brothers, for he sought good for his people, <span class=\"idiom\">interceding for the welfare of all his descendants</span>.<span class=\"note\">“spoke peace for all his offspring”</span>')
;

