INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '1', '1', '1', '<span class=\"verse-title\">The Decree of Cyrus</span>In the first year of Cyrus king of Persia, in order to accomplish the word of Adonai by the mouth of Jeremiah, Adonai stirred the spirit of Cyrus king of Persia and he sent a message to all of his kingdom and also <span class=\"supplied\">put the message</span> in writing:'),
('LEB', 'Ezra', '1', '2', '2', '“Thus says Cyrus king of Persia: Adonai, the God of the heavens, has given me all the kingdoms of the earth. And he himself has appointed me to build a house for him in Jerusalem, which is in Judah.'),
('LEB', 'Ezra', '1', '3', '2', 'Whoever among you <span class=\"supplied\">who is</span> from all of his people, may his God be with him and may he go up to Jerusalem, which is in Judah, and may he build the house of Adonai, the God of Israel. He is the God who <span class=\"supplied\">is</span> in Jerusalem.'),
('LEB', 'Ezra', '1', '4', '2', 'And let every survivor, from wherever he <span class=\"idiom\">resides</span><span class=\"note\">“resides as a foreigner”</span>be assisted by the men of that place with silver and gold, with possessions and domestic animals, and with the freewill offering for the house of God which is in Jerusalem.”'),
('LEB', 'Ezra', '1', '5', '3', 'So the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>for Judah and Benjamin, and the priests and the Levites—to all whose spirit God had stirred—<span class=\"supplied\">prepared</span> to go up and build the house of Adonai which is in Jerusalem.'),
('LEB', 'Ezra', '1', '6', '3', 'And all of their neighbors <span class=\"idiom\">helped them</span><span class=\"note\">“helped with their hands”</span>with objects of silver, gold, possessions, domestic animal<span class=\"supplied\">s</span>, and with valuable gifts—besides all of <span class=\"supplied\">the</span> freewill offering.'),
('LEB', 'Ezra', '1', '7', '3', 'And Cyrus the king brought out the objects of the house of Adonai that Nebuchadnezzar had brought from Jerusalem and placed in the house of his gods.'),
('LEB', 'Ezra', '1', '8', '3', 'Cyrus the king of Persia let them go out by the hand of Mithredath the treasurer, and he counted them out to Sheshbazzar the prince of Judah.'),
('LEB', 'Ezra', '1', '9', '3', 'Now these were the inventories: thirty gold metal dishes, one thousand silver metal dishes, twenty-nine vessels,'),
('LEB', 'Ezra', '1', '10', '3', 'thirty bowls of gold, four hundred and ten matching silver metal bowls, and one thousand other objects.'),
('LEB', 'Ezra', '1', '11', '3', 'All of the objects of gold and silver metal <span class=\"supplied\">were</span> five thousand four hundred. All this Sheshbazzar brought up along with the exiles from Babylonia to Jerusalem.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '2', '1', '1', '<span class=\"verse-title\">The List of Returned Exiles</span>Now these were the people<span class=\"note\">Or “sons”</span>of the province who came up from the captivity of the exile whom Nebuchadnezzar the king of Babylon carried captive to Babylonia. They returned to Jerusalem and Judah, each to his <span class=\"supplied\">own</span> city.'),
('LEB', 'Ezra', '2', '2', '1', 'They came with Zerubbabel, Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, Bilshan, Mispar, Bigvai, Rehum, and Baanah.'),
('LEB', 'Ezra', '2', '3', '2', 'The number of the men of the people of Israel:'),
('LEB', 'Ezra', '2', '4', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Parosh, two thousand one hundred and seventy-two;'),
('LEB', 'Ezra', '2', '5', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Shephatiah, three hundred and seventy-two;'),
('LEB', 'Ezra', '2', '6', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Arah, seven hundred and seventy-five;'),
('LEB', 'Ezra', '2', '7', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Pahath-moab, <span class=\"supplied\">particularly</span> the descendants<span class=\"note\">Or “sons”</span>of Jeshua and Joab, two thousand eight hundred and twelve;'),
('LEB', 'Ezra', '2', '8', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Elam, one thousand two hundred and fifty-four;'),
('LEB', 'Ezra', '2', '9', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Zattu, nine hundred and forty-five;'),
('LEB', 'Ezra', '2', '10', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Zaccai, seven hundred and sixty;'),
('LEB', 'Ezra', '2', '11', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Bani, six hundred and forty-two;'),
('LEB', 'Ezra', '2', '12', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Bebai, six hundred and twenty-three;'),
('LEB', 'Ezra', '2', '13', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Azgad, one thousand two hundred and twenty-two;'),
('LEB', 'Ezra', '2', '14', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Adonikam, six hundred and sixty-six;'),
('LEB', 'Ezra', '2', '15', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Bigvai, two thousand fifty-six;'),
('LEB', 'Ezra', '2', '16', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Adin, four hundred and fifty-four;'),
('LEB', 'Ezra', '2', '17', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Ater, <span class=\"supplied\">particularly</span> of Hezekiah, ninety-eight;'),
('LEB', 'Ezra', '2', '18', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Bezai, three hundred and twenty-three;'),
('LEB', 'Ezra', '2', '19', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Jorah, one hundred and twelve;'),
('LEB', 'Ezra', '2', '20', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Hashum, two hundred and twenty-three;'),
('LEB', 'Ezra', '2', '21', '2', 'the descendants<span class=\"note\">Or “sons”</span>of Gibbar, ninety-five;'),
('LEB', 'Ezra', '2', '22', '2', 'the people<span class=\"note\">Or “sons”</span>of Bethlehem, one hundred and twenty-three;'),
('LEB', 'Ezra', '2', '23', '2', 'the men of Netophah, fifty-six;'),
('LEB', 'Ezra', '2', '24', '2', 'the men of Anathoth, one hundred and twenty-eight;'),
('LEB', 'Ezra', '2', '25', '2', 'the people<span class=\"note\">Or “sons”</span>of Azmaveth, forty-two;'),
('LEB', 'Ezra', '2', '26', '2', 'the people<span class=\"note\">Or “sons”</span>of Kiriath Αrim, Kephirah, and Beeroth, seven hundred and forty-three;'),
('LEB', 'Ezra', '2', '27', '2', 'the people<span class=\"note\">Or “sons”</span>of Ramah and Geba, six hundred and twenty-one;'),
('LEB', 'Ezra', '2', '28', '2', 'the men of Micmash, one hundred and twenty-two;'),
('LEB', 'Ezra', '2', '29', '2', 'the men of Bethel and Ai, two hundred and twenty-three;'),
('LEB', 'Ezra', '2', '30', '2', 'the people<span class=\"note\">Or “sons”</span>of Nebo, fifty-two;'),
('LEB', 'Ezra', '2', '31', '2', 'the people<span class=\"note\">Or “sons”</span>of Magbish, one hundred and fifty-six;'),
('LEB', 'Ezra', '2', '32', '2', 'the people<span class=\"note\">Or “sons”</span>of the other Elam, one thousand two hundred and fifty-four;'),
('LEB', 'Ezra', '2', '33', '2', 'the people<span class=\"note\">Or “sons”</span>of Harim, three hundred and twenty;'),
('LEB', 'Ezra', '2', '34', '2', 'the people<span class=\"note\">Or “sons”</span>of Lod, Hadid, and Ono, seven hundred and twenty-five;'),
('LEB', 'Ezra', '2', '35', '2', 'the people<span class=\"note\">Or “sons”</span>of Jericho, three hundred and forty-five;'),
('LEB', 'Ezra', '2', '36', '3', 'The priests: the descendants<span class=\"note\">Or “sons”</span>of Jedaiah, of the house of Jeshua, nine hundred and seventy-three;'),
('LEB', 'Ezra', '2', '37', '3', 'the descendants<span class=\"note\">Or “sons”</span>of Immer, one thousand fifty-two;'),
('LEB', 'Ezra', '2', '38', '3', 'the descendants<span class=\"note\">Or “sons”</span>of Pashhur, one thousand two hundred and forty-seven;'),
('LEB', 'Ezra', '2', '39', '3', 'the descendants<span class=\"note\">Or “sons”</span>of Harim, one thousand seventeen.'),
('LEB', 'Ezra', '2', '40', '4', 'The Levites: the descendants<span class=\"note\">Or “sons”</span>of Jeshua and Kadmiel, of the descendants<span class=\"note\">Or “sons”</span>of Hodaviah, seventy-four.'),
('LEB', 'Ezra', '2', '41', '5', 'The singers: the descendants<span class=\"note\">Or “sons”</span>of Asaph, one hundred and twenty-eight.'),
('LEB', 'Ezra', '2', '42', '6', 'The descendants<span class=\"note\">Or “sons”</span>of the gatekeepers: the descendants<span class=\"note\">Or “sons”</span>of Shallum, the descendants<span class=\"note\">Or “sons”</span>of Ater, the descendants<span class=\"note\">Or “sons”</span>of Talmon, the descendants<span class=\"note\">Or “sons”</span>of Akkub, the descendants<span class=\"note\">Or “sons”</span>of Hatita, and the descendants<span class=\"note\">Or “sons”</span>of Shobai; in total one hundred and thirty-nine.'),
('LEB', 'Ezra', '2', '43', '7', 'The temple servants: the descendants<span class=\"note\">Or “sons”</span>of Ziha, the descendants<span class=\"note\">Or “sons”</span>of Hasupha, the descendants<span class=\"note\">Or “sons”</span>of Tabbaoth,'),
('LEB', 'Ezra', '2', '44', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Keros, the descendants<span class=\"note\">Or “sons”</span>of Siaha, the descendants<span class=\"note\">Or “sons”</span>of Padon,'),
('LEB', 'Ezra', '2', '45', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Lebanah, the descendants<span class=\"note\">Or “sons”</span>of Hagabah, the descendants<span class=\"note\">Or “sons”</span>of Akkub,'),
('LEB', 'Ezra', '2', '46', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Hagab, the descendants<span class=\"note\">Or “sons”</span>of Shamlai, the descendants<span class=\"note\">Or “sons”</span>of Hanan,'),
('LEB', 'Ezra', '2', '47', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Giddel, the descendants<span class=\"note\">Or “sons”</span>of Gahar, the descendants<span class=\"note\">Or “sons”</span>of Reaiah,'),
('LEB', 'Ezra', '2', '48', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Rezin, the descendants<span class=\"note\">Or “sons”</span>of Nekoda, the descendants<span class=\"note\">Or “sons”</span>of Gazzam,'),
('LEB', 'Ezra', '2', '49', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Uzza, the descendants<span class=\"note\">Or “sons”</span>of Paseah, the descendants<span class=\"note\">Or “sons”</span>of Besai,'),
('LEB', 'Ezra', '2', '50', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Asnah, the descendants<span class=\"note\">Or “sons”</span>of Meunim, the descendants<span class=\"note\">Or “sons”</span>of Nephisim,'),
('LEB', 'Ezra', '2', '51', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Bakbuk, the descendants<span class=\"note\">Or “sons”</span>of Hakupha, the descendants<span class=\"note\">Or “sons”</span>of Harhur,'),
('LEB', 'Ezra', '2', '52', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Bazluth, the descendants<span class=\"note\">Or “sons”</span>of Mehida, the descendants<span class=\"note\">Or “sons”</span>of Harsha,'),
('LEB', 'Ezra', '2', '53', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Barkos, the descendants<span class=\"note\">Or “sons”</span>of Sisera, the descendants<span class=\"note\">Or “sons”</span>of Temah,'),
('LEB', 'Ezra', '2', '54', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Neziah, and the descendants<span class=\"note\">Or “sons”</span>of Hatipha.'),
('LEB', 'Ezra', '2', '55', '8', 'The descendants<span class=\"note\">Or “sons”</span>of Solomon’s servants: the descendants<span class=\"note\">Or “sons”</span>of Sotai, the descendants<span class=\"note\">Or “sons”</span>of Hassophereth, the descendants<span class=\"note\">Or “sons”</span>of Peruda,'),
('LEB', 'Ezra', '2', '56', '8', 'the descendants<span class=\"note\">Or “sons”</span>of Jaalah, the descendants<span class=\"note\">Or “sons”</span>of Darkon, the descendants<span class=\"note\">Or “sons”</span>of Giddel,'),
('LEB', 'Ezra', '2', '57', '8', 'the descendants<span class=\"note\">Or “sons”</span>of Shephatiah, the descendants<span class=\"note\">Or “sons”</span>of Hattil, the descendants<span class=\"note\">Or “sons”</span>of Pochereth-hazzebaim, and the descendants<span class=\"note\">Or “sons”</span>of Ami.'),
('LEB', 'Ezra', '2', '58', '9', 'All the temple servants and the descendants<span class=\"note\">Or “sons”</span>of Solomon’s servants were three hundred and ninety-two.'),
('LEB', 'Ezra', '2', '59', '10', 'Now these were the ones who came up from Tel-melah, Tel-harsha, Cherub, Addan, and Immer, but they were not able to prove their fathers’ household and their descent, if they were from Israel:'),
('LEB', 'Ezra', '2', '60', '10', 'the descendants<span class=\"note\">Or “sons”</span>of Delaiah, the descendants<span class=\"note\">Or “sons”</span>of Tobiah, and the descendants<span class=\"note\">Or “sons”</span>of Nekoda, six hundred and fifty-two.'),
('LEB', 'Ezra', '2', '61', '10', 'And from the descendants<span class=\"note\">Or “sons”</span>of the priests: the descendants<span class=\"note\">Or “sons”</span>of Habaiah, the descendants<span class=\"note\">Or “sons”</span>of Hakkoz, and the descendants<span class=\"note\">Or “sons”</span>of Barzillai (who took a wife from the daughters of Barzillai the Gileadite, and was called by their name).'),
('LEB', 'Ezra', '2', '62', '10', 'These sought their record in the genealogy <span class=\"supplied\">records</span>, but they were not found, and <span class=\"idiom\">were excluded from the priesthood as unclean</span>.<span class=\"note\">“they were unclean from the priesthood”</span>'),
('LEB', 'Ezra', '2', '63', '10', 'The governor said to them that they could not eat from the holy food of the sanctuary<span class=\"note\">Or “most holy things”</span>until there was present a priest for the Urim and Thummim.'),
('LEB', 'Ezra', '2', '64', '11', 'The whole assembly together was forty-two thousand three hundred and sixty,'),
('LEB', 'Ezra', '2', '65', '11', 'apart from their male and female servants, of whom were seven thousand three hundred and thirty-seven; and they had two hundred male and female singers.'),
('LEB', 'Ezra', '2', '66', '11', 'Their horses <span class=\"supplied\">numbered</span> seven hundred and thirty-six, their mules <span class=\"supplied\">numbered</span> two hundred and forty-five,'),
('LEB', 'Ezra', '2', '67', '11', 'their camels <span class=\"supplied\">numbered</span> four hundred and thirty-five, their donkeys <span class=\"supplied\">numbered</span> six thousand seven hundred and twenty.'),
('LEB', 'Ezra', '2', '68', '13', '<span class=\"verse-title\">Gifts Given for Temple Work</span>When <span class=\"supplied\">some</span> of the heads of <span class=\"idiom\">families</span><span class=\"note\">“the fathers”</span>came to the house of Adonai that <span class=\"supplied\">is</span> in Jerusalem, they gave freewill offerings for the house of God to erect it on its place.'),
('LEB', 'Ezra', '2', '69', '13', 'According to their ability they gave to the treasury room for the work sixty-one thousand darics of gold, five thousand minas of silver, and one hundred priestly tunics.'),
('LEB', 'Ezra', '2', '70', '14', 'The priests, the Levites, and some of the people lived <span class=\"supplied\">in Jerusalem</span>, and the singers, the gatekeepers, and the temple servants <span class=\"supplied\">lived</span> in their cities, and all Israel in their cities.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '3', '1', '1', '<span class=\"verse-title\">Worship in Jerusalem Restored</span>Now the seventh month drew near and the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span><span class=\"supplied\">were</span> in the cities, <span class=\"supplied\">so</span> the people gathered as <span class=\"idiom\">one</span><span class=\"note\">“one man”</span>in Jerusalem.'),
('LEB', 'Ezra', '3', '2', '1', 'And Jeshua son of Jehozadak and his brothers the priests stood up, and Zerubbabel the son of Shealtiel and his brothers built the altar of the God of Israel, in order to offer burnt offerings on it, as it is written in the law of Moses, the man of God.'),
('LEB', 'Ezra', '3', '3', '1', 'They set up the altar on its foundations, because <span class=\"idiom\">they were in terror</span><span class=\"note\">“in terror before them”</span>because of the peoples of the lands. And they offered burnt offerings on it for Adonai, burnt offerings for the morning and the evening.'),
('LEB', 'Ezra', '3', '4', '1', 'And they kept the feast of booths, as it is written, and <span class=\"supplied\">offered</span> burnt offerings day by day in number according to the ordinance <span class=\"idiom\">as described for each day</span>.<span class=\"note\">“the daily word on its day”</span>'),
('LEB', 'Ezra', '3', '5', '1', 'After <span class=\"supplied\">this, they presented</span> the daily sacrifice of burnt offerings, <span class=\"supplied\">the offerings</span> for the New Moon Festival, and for all of the appointed times consecrated for Adonai and for all who gave a freewill offering to Adonai.'),
('LEB', 'Ezra', '3', '6', '1', 'From the first day of the seventh month they began to offer burnt offerings to Adonai. But the temple of Adonai was not yet founded.'),
('LEB', 'Ezra', '3', '7', '1', 'So they gave money to the stone craftsmen and skilled craftsmen, and food, drink, and olive oil to the Sidonians and Tyrians, to bring cedar trees from Lebanon to the sea of Joppa, according to the authorization over them of Cyrus king of Persia.'),
('LEB', 'Ezra', '3', '8', '3', '<span class=\"verse-title\">Foundation of the Temple is Laid</span>In the second year after their coming to the house of God at Jerusalem, in the second month, Zerubbabel son of Shealtiel and Jeshua son of Jehozadak began <span class=\"supplied\">their work</span>, and the remainder of their brothers the priests and the Levites and all who came from the captivity to Jerusalem. They appointed the Levites <span class=\"idiom\">from twenty years and older</span><span class=\"note\">“a son of twenty years and above”</span>to direct the work of the house of Adonai.'),
('LEB', 'Ezra', '3', '9', '3', 'And Jeshua <span class=\"supplied\">with</span> his sons and brothers, and Kadmiel and his sons—the sons of Judah—together directed the workers in the house of God, <span class=\"supplied\">along with</span> the sons of Henadad and their sons and brothers the Levites.'),
('LEB', 'Ezra', '3', '10', '4', 'And the builders laid the foundation of the temple of Adonai, and the priests <span class=\"supplied\">in their</span> apparel with the trumpets, and the Levites, the sons of Asaph, with the cymbals, were positioned to praise Adonai, <span class=\"idiom\">as described by</span><span class=\"note\">“by the hands of”</span>King David of Israel.'),
('LEB', 'Ezra', '3', '11', '4', 'And they <span class=\"idiom\">sang responsively</span>,<span class=\"note\">“they answered”</span>with praising and thanksgiving to Adonai <span class=\"supplied\">saying</span>, “For he is good, for his loyal love is everlasting for Israel.”'),
('LEB', 'Ezra', '3', '12', '5', 'And all of the people responded with a great shout of joyful acclaim in praise to Adonai because the house of Adonai was laid.'),
('LEB', 'Ezra', '3', '13', '5', 'But many of the elderly priests, Levites, and heads of the families who had seen the first temple, wept with a loud voice when they saw the foundation of this house, but many <span class=\"idiom\">shouted aloud with joy</span>.<span class=\"note\">“exalted with voice in joy with a shout”</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '4', '1', '1', '<span class=\"verse-title\">Resistance to Rebuilding the House of God</span>Now the enemies of Judah and Benjamin heard that the <span class=\"idiom\">returned exiles</span><span class=\"note\">“the sons of the exile”</span><span class=\"supplied\">were</span> building a temple for Adonai the God of Israel.'),
('LEB', 'Ezra', '4', '2', '1', 'And they approached Zerubbabel and the heads of the <span class=\"idiom\">families</span>,<span class=\"note\">“fathers”</span>and they said to them, “Let us build with you. Like you, we seek your God and have been sacrificing <span class=\"supplied\">to him</span> from the days of Esarhaddon the king of Assyria who brought us up here.'),
('LEB', 'Ezra', '4', '3', '1', 'But Zerubbabel, Jeshua, and the rest of the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>of Israel said to them, “<span class=\"supplied\">It is</span> not for you but for us to build a house for our God. For we ourselves alone will build <span class=\"supplied\">it</span> for Adonai the God of Israel, just as Cyrus the king of Persia has commanded us.”'),
('LEB', 'Ezra', '4', '4', '2', 'Then the people of the land discouraged <span class=\"idiom\">the people of Judah</span><span class=\"note\">“the hands of the people of Judah”</span>and made them afraid to build'),
('LEB', 'Ezra', '4', '5', '2', 'and bribed officials against them to frustrate their plan for all the days of Cyrus king of Persia until the reign of Darius king of Persia.'),
('LEB', 'Ezra', '4', '6', '4', '<span class=\"verse-title\">Resistance to Rebuilding Jerusalem</span>In the reign of Ahasuerus, at the beginning of his reign, they wrote an accusation against the inhabitants of Judah and Jerusalem.'),
('LEB', 'Ezra', '4', '7', '4', 'And in the days of Artaxerxes, Bishlam, Mithredath, Tabeel, and the rest of their colleagues wrote to Artaxerxes king of Persia. The letter was written in Aramaic and translated from Aramaic.'),
('LEB', 'Ezra', '4', '8', '4', 'Rehum the royal officer and Shimshai the scribe wrote a letter against Jerusalem to King Artaxerxes as follows'),
('LEB', 'Ezra', '4', '9', '4', '(then Rehum the royal officer, Shimshai the scribe, and the rest of their associates, the judges, the envoys, the officials, the Persians, the Erechs, the Babylonians, the Susians (that is the Elamites)'),
('LEB', 'Ezra', '4', '10', '4', 'and the rest of the nations whom the great and noble Osnappar deported and settled in the cities of Samaria and the rest of <span class=\"supplied\">the province</span> Beyond the River) and now'),
('LEB', 'Ezra', '4', '11', '4', 'this is the copy of the letter which they sent to him:'),
('LEB', 'Ezra', '4', '12', '5', '“To King Artaxerxes <span class=\"supplied\">from</span> your servants, the men of <span class=\"supplied\">the province</span> Beyond the River. And now,'),
('LEB', 'Ezra', '4', '13', '5', 'be it known to the king that the Jews who have come up from near you to us have gone to Jerusalem. They are building the rebellious and wicked city. They are finishing the wall and repairing the foundation.'),
('LEB', 'Ezra', '4', '14', '5', 'Now be it known to the king that if this city is built and the walls are finished, they will not pay tribute and toll, and the royal revenue will be reduced.'),
('LEB', 'Ezra', '4', '15', '5', 'Now since we eat the salt of the palace and the dishonor of the king is not proper for us to see, we send and make <span class=\"supplied\">this</span> known to the king,'),
('LEB', 'Ezra', '4', '16', '5', 'so that it may be investigated in the book of records of your ancestors.<span class=\"note\">Or “fathers”</span>You will find in the book of records and learn that this city is a rebellious city, hurtful to kings and provinces, and they have rebelled in its midst from ancient times. Because of that this city was destroyed.'),
('LEB', 'Ezra', '4', '17', '6', 'The king sent a reply: “To Rehum the royal officer, Shimshai the scribe, and the rest of their associates who live in Samaria and the rest <span class=\"supplied\">of the province</span> Beyond the River, greetings. And now'),
('LEB', 'Ezra', '4', '18', '6', 'the letter that you sent to us has been translated <span class=\"supplied\">and</span> read before me.'),
('LEB', 'Ezra', '4', '19', '6', 'And <span class=\"idiom\">I issued</span><span class=\"note\">“by my means made”</span>a decree, and they searched and found that this city from ancient days revolted against kings, and rebellion and sedition has been made in it.'),
('LEB', 'Ezra', '4', '20', '6', 'Mighty kings have ruled over Jerusalem, <span class=\"supplied\">governing</span> all <span class=\"supplied\">the province</span> Beyond the River, to whom tribute, duty, and tax has been given.'),
('LEB', 'Ezra', '4', '21', '6', 'So now, issue forth a decree that these men stop and this city not be built, until a decree is issued from me.'),
('LEB', 'Ezra', '4', '22', '6', 'And be careful not to be negligent on this matter. Why should damage grow to hurt kings?”'),
('LEB', 'Ezra', '4', '23', '7', 'Then when a copy of the letter of King Artaxerxes was read before Rehum, Shimshai the scribe, and their associates they returned in a hurry to Jerusalem against the Jews and they stopped them by force and power.'),
('LEB', 'Ezra', '4', '24', '7', 'Then the work on the house of God in Jerusalem stopped, and was discontinued until the second year of the reign of Darius king of Persia.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '5', '1', '1', '<span class=\"verse-title\">Temple Restoration Resumed</span>Now the prophets, Haggai and Zechariah the son of Iddo, prophesied to the Jews who were in <span class=\"idiom\">Judah</span><span class=\"note\">“Jehud”</span>and in Jerusalem, in the name of the God of Israel who was over them.'),
('LEB', 'Ezra', '5', '2', '1', 'Then Zerubbabel the son of Shealtiel and Jeshua the son of Jozadak set out and began to build the house of God that is in Jerusalem. And with them the prophets of God <span class=\"supplied\">were</span> helping them.'),
('LEB', 'Ezra', '5', '3', '2', 'At the same time Tattenai, governor of <span class=\"supplied\">the province</span> Beyond the River, and Shethar-bozenai, and their associates came to them and spoke to them thus: “Who issued you all a decree to build this house and to finish this structure?”'),
('LEB', 'Ezra', '5', '4', '2', 'Then we<span class=\"note\">Hebrew is first person plural</span>asked them this: “What are the names of the men who are building this building?”'),
('LEB', 'Ezra', '5', '5', '2', 'And the eye of their God was on the elders of the Jews, and they did not stop them until the report came to Darius, and then <span class=\"supplied\">answer</span> was received.'),
('LEB', 'Ezra', '5', '6', '3', 'The copy of the letter that Tattenai, the governor of <span class=\"supplied\">the province</span> Beyond the River, and Shethar-bozenai and his associates the envoys who were in <span class=\"supplied\">the province</span> Beyond the River sent to Darius the king.'),
('LEB', 'Ezra', '5', '7', '3', 'They sent to him the report <span class=\"idiom\">in which was written as follows</span>:<span class=\"note\">“and like this was written in its middle”</span>“To Darius the king, all peace.'),
('LEB', 'Ezra', '5', '8', '3', 'May it be known to the king that we went to the province of Judah, the house of the great God. It is being built with stone blocks and timber is being put in the walls. This work is being done with diligence and is making progress in their hands.'),
('LEB', 'Ezra', '5', '9', '3', 'Then we asked those elders and said this to them, ‘Who issued forth to you a decree to build this house and to finish this structure?’'),
('LEB', 'Ezra', '5', '10', '3', 'We also asked them their names to make them known to you, that we might write down the <span class=\"idiom\">name of their leaders</span>.<span class=\"note\">“name of the men at their head”</span>'),
('LEB', 'Ezra', '5', '11', '3', 'And this is the answer they returned to us: ‘We are servants of the God of heaven and earth, and we are building the house that was built formerly many years ago, <span class=\"supplied\">which</span> a great king of Israel had built and finished.'),
('LEB', 'Ezra', '5', '12', '3', 'But because our ancestors<span class=\"note\">Or “fathers”</span>angered the God of heaven, he gave them into the hand of the Chaldean King Nebuchadnezzar of Babylon. He destroyed this house and carried away the people to Babylonia.'),
('LEB', 'Ezra', '5', '13', '3', 'But in the first year of King Cyrus of Babylon’s reign he issued forth a decree to build this house of God.'),
('LEB', 'Ezra', '5', '14', '3', 'Also, the gold and silver vessels of the house of God, which Nebuchadnezzar took away from the temple in Jerusalem and brought to the temple in Babylonia, King Cyrus removed them from the temple in Babylonia and they were given to Sheshbazzar, whom he appointed governor.'),
('LEB', 'Ezra', '5', '15', '3', 'He said to him, ‘Take these vessels. Go put them in the temple in Jerusalem and let the house of God be built on its site.’'),
('LEB', 'Ezra', '5', '16', '3', 'Then this Sheshbazzar came and laid the foundation of the house of God in Jerusalem. And from that <span class=\"supplied\">time</span> until now it is being built, but not yet finished.’'),
('LEB', 'Ezra', '5', '17', '3', 'And now, if it seems good for the king, let it be investigated in the house of the treasury of the king in Babylonia <span class=\"supplied\">to see</span> if a decree was issued forth from King Cyrus to build this house of God in Jerusalem. And let the king send to us his desire on this matter.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '6', '1', '1', '<span class=\"verse-title\">Darius’ Search for the Decree</span>Then King Darius issued forth a decree, and they searched the house of the treasury of scrolls being stored in Babylonia.'),
('LEB', 'Ezra', '6', '2', '1', 'But it was in Ecbatana in the province of Media, in the citadel, that a certain scroll had written on it, “A record.'),
('LEB', 'Ezra', '6', '3', '1', 'In the first year of King Cyrus, he issued forth a decree concerning the house of God in Jerusalem. Let the house be built, the place where sacrifices are offered and let its foundations be raised. Its height <span class=\"supplied\">shall be</span> sixty cubits and its width sixty cubits,'),
('LEB', 'Ezra', '6', '4', '1', 'with three layers of great stones and a layer of timber. Let the new expenses be paid from the house of the king.'),
('LEB', 'Ezra', '6', '5', '1', 'Also, let the gold and silver vessels of the house of God, which Nebuchadnezzar took from the temple in Jerusalem and brought to Babylonia, be returned and brought to the temple in Jerusalem to its place. Put them in the house of God.”'),
('LEB', 'Ezra', '6', '6', '3', '<span class=\"verse-title\">The Decree of Darius</span>“Now then, Tattenai governor of <span class=\"supplied\">the province</span> Beyond the River, Shethar-bozenai, and your associates, the envoys who are in <span class=\"supplied\">the province</span> Beyond the River—keep far away from there.'),
('LEB', 'Ezra', '6', '7', '3', 'Leave this work of the house of God alone. Let the governor of the Jews and the elders of the Jews build this house of God on its site.'),
('LEB', 'Ezra', '6', '8', '3', 'And I issue forth a decree for what you should do for these elders of the Jews to build this house of God. The full expense will be paid to these men from the riches of the king from the taxes of <span class=\"supplied\">the province</span> Beyond the River, without delay.'),
('LEB', 'Ezra', '6', '9', '3', 'Whatever may be needed—<span class=\"idiom\">young bulls</span>,<span class=\"note\">“the sons of young bulls”</span>young rams, sheep for burnt offerings to the God of heaven, wheat, salt, wine, and oil for the priests in Jerusalem—let it be given to them day by day with no negligence,'),
('LEB', 'Ezra', '6', '10', '3', 'that they may offer incense offerings to the God of heaven, and pray for the life of the king and his children.'),
('LEB', 'Ezra', '6', '11', '3', 'Furthermore, I issue forth a decree that if any person violates this decree, let a beam be pulled out from his house and let him be impaled on it. And let his house be made a pile of rubble on <span class=\"supplied\">account of</span> this.'),
('LEB', 'Ezra', '6', '12', '3', 'May the God who has set his name there overthrow any king or people who sets his hand to alter <span class=\"supplied\">or</span> to destroy this house of God in Jerusalem. I, Darius, issue forth a decree. Let it be done with diligence.”'),
('LEB', 'Ezra', '6', '13', '5', '<span class=\"verse-title\">Temple is Dedicated and Completed</span>Then Tattenai the governor of the <span class=\"supplied\">province</span> Beyond the River, Shethar-bozenai, and their associates consequently did with diligence what Darius the king ordered.'),
('LEB', 'Ezra', '6', '14', '5', 'So the elders of the Jews were building and prospering, through the prophecy of Haggai the prophet and Zechariah son of Iddo. They finished building by the command of the God of Israel and by the decree of Cyrus, Darius, and King Artaxerxes of Persia.'),
('LEB', 'Ezra', '6', '15', '5', 'This house was completed on the third day of the month of Adar, which was in the sixth year of the reign of King Darius.'),
('LEB', 'Ezra', '6', '16', '6', 'And the <span class=\"idiom\">Israelites</span>,<span class=\"note\">“sons/children of Israel”</span>the priests, the Levites, and the rest of the <span class=\"idiom\">returned exiles</span><span class=\"note\">“sons of the exile”</span>celebrated the dedication of this house of God with joy.'),
('LEB', 'Ezra', '6', '17', '6', 'And they offered during the dedication of this house of God one hundred young bulls, two hundred young rams, four hundred lambs, and twelve male goats as a sin offering for Israel <span class=\"supplied\">according to</span> the number of the tribes of Israel.'),
('LEB', 'Ezra', '6', '18', '6', 'Then they set the priests in their divisions and the Levites in their sections for the work of God in Jerusalem, as it is written in the book of Moses.'),
('LEB', 'Ezra', '6', '19', '8', '<span class=\"verse-title\">The Celebration of Passover</span>On the fourteenth day of the first month the returned exiles observed the Passover feast.'),
('LEB', 'Ezra', '6', '20', '8', 'For the priests and Levites together had consecrated themselves; all of them were clean. And they slaughtered the Passover sacrifice for all of the returned exiles, for their brothers the priests, and for themselves.'),
('LEB', 'Ezra', '6', '21', '8', 'The <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span>who returned from the exile and all those who separated themselves from the uncleanness of the nations of the earth to seek Adonai the God of Israel, ate.'),
('LEB', 'Ezra', '6', '22', '8', 'With joy they celebrated the festival of unleavened bread <span class=\"supplied\">for</span> seven days, because Adonai had made them joyful and had turned the heart of the king of Assyria toward them in order to help them with the work of their hands on the house of the God of Israel.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '7', '1', '1', '<span class=\"verse-title\">Ezra’s Arrival and Work</span>After these things <span class=\"supplied\">during</span> the reign of King Artaxerxes of Persia, Ezra the son of Seraiah, son of Azariah, son of Hilkiah,'),
('LEB', 'Ezra', '7', '2', '1', 'son of Shallum, son of Zadok, son of Ahitub,'),
('LEB', 'Ezra', '7', '3', '1', 'son of Amariah, son of Azariah, son of Meraioth,'),
('LEB', 'Ezra', '7', '4', '1', ', son of Zerahiah, son of Uzzi, son of Bukki,'),
('LEB', 'Ezra', '7', '5', '1', 'son of Abishua, son of Phinehas, son of Eleazar, son of Aaron the chief priest—'),
('LEB', 'Ezra', '7', '6', '1', 'this Ezra went up from Babylonia. He was a scribe skilled in the law of Moses, which Adonai the God of Israel gave. The king granted him all his requests, for the hand of Adonai was upon him.'),
('LEB', 'Ezra', '7', '7', '2', 'Some of the <span class=\"idiom\">Israelites</span>,<span class=\"note\">“sons/children of Israel”</span>some priests and Levites, the singers, the gatekeepers, and the temple servants went up to Jerusalem in the seventh year of King Artaxerxes.'),
('LEB', 'Ezra', '7', '8', '2', 'He came to Jerusalem in the fifth month, which was in the seventh year of the king.'),
('LEB', 'Ezra', '7', '9', '2', 'For on the first day of the first month he began the journey from Babylonia; and on the first day of the fifth month he came to Jerusalem, for the good hand of his God <span class=\"supplied\">was</span> on him.'),
('LEB', 'Ezra', '7', '10', '2', 'For Ezra had set his heart to seek the law of Adonai, to do <span class=\"supplied\">it</span>, and to teach the regulations and judgments in Israel.'),
('LEB', 'Ezra', '7', '11', '4', '<span class=\"verse-title\">Artaxerxes’ Letter to Ezra</span>This is the copy of the letter that King Artaxerxes gave to Ezra the priest, the scribe of the scroll of the words of the commands of Adonai and his statutes for Israel:'),
('LEB', 'Ezra', '7', '12', '4', '“Artaxerxes, the king of kings, to Ezra the priest, the scribe of the law of the God of the heavens. Peace. And now'),
('LEB', 'Ezra', '7', '13', '4', 'I issue forth a decree that any of the people of Israel, their priests, or their Levites in my kingdom who are willing to go to Jerusalem may go with you.'),
('LEB', 'Ezra', '7', '14', '4', 'For you are sent from the king and his seven counselors to enquire about Judah and Jerusalem concerning the law of your God, which is in your hand.'),
('LEB', 'Ezra', '7', '15', '4', 'Also, bring the silver and gold that the king and his advisors have freely offered to the God of Israel whose dwelling is in Jerusalem,'),
('LEB', 'Ezra', '7', '16', '4', 'and all of the silver and gold that you will find in the whole province of Babylonia, with the freewill offerings of the people and the priests giving willingly for the house of their God in Jerusalem.'),
('LEB', 'Ezra', '7', '17', '4', 'With this money, then, with diligence you must buy young bulls, young rams, lambs, and their offerings and libations. You must offer them on the altar that is in the house of your God in Jerusalem.'),
('LEB', 'Ezra', '7', '18', '4', 'You may do whatever seems best to you and your brothers to do with the remainder of the silver and gold according to the desire of your God.'),
('LEB', 'Ezra', '7', '19', '4', 'And the vessels that were given to you for the service of the house of your God you shall deliver before the God of Jerusalem.'),
('LEB', 'Ezra', '7', '20', '4', 'And the remainder of the needs for the house of your God that falls to you to provide, you may provide from the house of the king’s treasury.”'),
('LEB', 'Ezra', '7', '21', '5', '“I, even I, King Artaxerxes, issue forth a decree to all the treasurers who are in <span class=\"supplied\">the province</span> Beyond the River. Whatever the priest Ezra, the scribe of the law of the God of heaven, may ask of you, let it be done with diligence,'),
('LEB', 'Ezra', '7', '22', '5', 'up to one hundred talents of silver, one hundred measures of wheat, one hundred baths of wine, one hundred baths of oil, and <span class=\"idiom\">unlimited salt</span>.<span class=\"note\">“salt that is not specified”</span>'),
('LEB', 'Ezra', '7', '23', '5', 'All that is commanded by the God of heaven, let it be done with diligence for the house of the God of heaven, otherwise wrath will come on the kingdom of the king and his sons.'),
('LEB', 'Ezra', '7', '24', '5', 'You also should be aware that it is not permitted to place tax, tribute, or duty upon all of the priests, the Levites, the singers, the doorkeepers, the temple servants, and other servants of the house of God.'),
('LEB', 'Ezra', '7', '25', '6', '“You, Ezra, according to the wisdom of your God that you possess, appoint magistrates and judges who can judge all of the people <span class=\"supplied\">in the province</span> Beyond the River who know the laws of your God. And you will teach those who do not know.'),
('LEB', 'Ezra', '7', '26', '6', 'All who do not obey the law of your God and the law of the king, let judgment be executed on him with diligence, whether for death or for banishment or for confiscation of goods and for imprisonment.”'),
('LEB', 'Ezra', '7', '27', '7', 'Blessed be Adonai the God of our ancestors,<span class=\"note\">Or “fathers”</span>who put this in the heart of the king to glorify the house of Adonai in Jerusalem'),
('LEB', 'Ezra', '7', '28', '7', 'and who extended to me loyal love before the king and his counselors, and before all of the mighty officials of the king. I took courage, for the hand of Adonai my God was upon me, and I gathered leaders from Israel to go up with me.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '8', '1', '1', '<span class=\"verse-title\">Family Heads Who Returned With Ezra</span>These were the heads of their <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>and the register of those returnees from Babylonia who <span class=\"supplied\">came up</span> with me in the reign of King Artaxerxes:'),
('LEB', 'Ezra', '8', '2', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Phinehas: Gershom. From the descendants<span class=\"note\">Or “sons”</span>of Ithamar: Daniel. From the descendants<span class=\"note\">Or “sons”</span>of David: Hattush.'),
('LEB', 'Ezra', '8', '3', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Shecaniah, from the descendants<span class=\"note\">Or “sons”</span>of Parosh: Zechariah and with him one hundred and fifty registered males.'),
('LEB', 'Ezra', '8', '4', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Pahath-Moab: Eliehoenai son of Zerahiah and with him two hundred males.'),
('LEB', 'Ezra', '8', '5', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of <span class=\"supplied\">Zattu</span>:<span class=\"note\">Commentators and translators agree that there is a name missing from the Masoretic text. Zattu has been restored from the LXX</span>Shecaniah son of Jahaziel, and with him three hundred males.'),
('LEB', 'Ezra', '8', '6', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Adin: Ebed son of Jehonathan, and with him fifty males.'),
('LEB', 'Ezra', '8', '7', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Elam: Jeshaiah son of Athaliah, and with him seventy males.'),
('LEB', 'Ezra', '8', '8', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Shephatiah: Zebadiah son of Michael, and with him eighty males.'),
('LEB', 'Ezra', '8', '9', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Joab: Obadiah son of Jehiel, and with him two hundred and eighteen males.'),
('LEB', 'Ezra', '8', '10', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of <span class=\"supplied\">Bani</span>:<span class=\"note\">Commentators and translators agree that there is a name missing from the Masoretic text. Bani has been restored from the LXX</span>Shelomith son of Josiphiah, and with him one hundred and sixty males.'),
('LEB', 'Ezra', '8', '11', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Bebai: Zechariah son of Bebai, and with him twenty-eight males.'),
('LEB', 'Ezra', '8', '12', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Azgad: Jehohanan son of Haqqatan, and with him one hundred and ten males.'),
('LEB', 'Ezra', '8', '13', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Adonikam, those who came last, these were their names: Eliphelet, Jeiel, Shemaiah, and with them sixty males.'),
('LEB', 'Ezra', '8', '14', '1', 'From the descendants<span class=\"note\">Or “sons”</span>of Bigvai: Uthai son of Zabud,<span class=\"note\">Or “and Zabud”</span>and with him seventy males.'),
('LEB', 'Ezra', '8', '15', '3', '<span class=\"verse-title\">Servants for the Temple are Gathered</span>I gathered them by the river that goes to Ahava and we camped there for three days. And I looked at the people and the priests, I found no one there from the sons of Levi.'),
('LEB', 'Ezra', '8', '16', '3', 'And I sent for Eliezer, Ariel, Shemaiah, Elnathan, Jarib, Elnathan, Nathan, Zechariah, and Meshullam, who were family heads, and for Jehoiarib and Elnathan who were wise.'),
('LEB', 'Ezra', '8', '17', '3', 'I sent them to Iddo, the head of the place called Casiphia, and I placed in their mouths what words to say to Iddo and his brothers the temple servants in Casiphia, to send to us ministers for the house of our God.'),
('LEB', 'Ezra', '8', '18', '3', 'With the good hand of our God before us, they brought us a man of understanding from the sons of Mahli, son of Levi, son of Israel—Sherebiah and his sons and brothers, eighteen <span class=\"supplied\">in total</span>.'),
('LEB', 'Ezra', '8', '19', '3', 'Also Hashabiah and with him Jeshaiah, the sons of Merari, with his brothers and their sons, twenty <span class=\"supplied\">in total</span>.'),
('LEB', 'Ezra', '8', '20', '3', 'And from the temple servants, whom David and <span class=\"supplied\">his</span> officials had set up to serve the Levites, two hundred and twenty <span class=\"supplied\">in total</span>. All of them were registered by name.'),
('LEB', 'Ezra', '8', '21', '5', '<span class=\"verse-title\">Ezra Proclaims a Fast</span>I proclaimed a fast there at the river Ahava to humble ourselves before our God in order to seek from him a safe journey for us, our children, and our possessions.'),
('LEB', 'Ezra', '8', '22', '5', 'For I was ashamed to ask the king for troops and horses to protect us from enemies on the way because we said to the king, “the hand of our God is favorable to all who seek him, but his strength and anger are against all who forsake them.”'),
('LEB', 'Ezra', '8', '23', '5', 'So we fasted and sought our God for this and he responded to our prayer.'),
('LEB', 'Ezra', '8', '24', '7', '<span class=\"verse-title\">The Priests’ Gift for the Temple</span>I set apart twelve of the official priests: Sherebiah, Hashabiah, and ten of their brothers with them.'),
('LEB', 'Ezra', '8', '25', '7', 'Then I weighed out to them silver and gold and the vessels, the offering of the house of our God that the king, his counselors, his commanders, and all of Israel who was present offered.'),
('LEB', 'Ezra', '8', '26', '7', 'I weighed out into their hand six hundred and fifty talents of silver, one hundred vessels of silver, one hundred talents of gold,'),
('LEB', 'Ezra', '8', '27', '7', 'twenty gold bowls worth one thousand darics, and two vessels of good polished bronze as precious as gold.'),
('LEB', 'Ezra', '8', '28', '7', 'And I said to them, “You are holy to Adonai and the vessels are holy. The silver and gold are a freewill offering to Adonai, God of your ancestors.<span class=\"note\">Or “fathers”</span>'),
('LEB', 'Ezra', '8', '29', '7', 'Guard and look after <span class=\"supplied\">them</span> until you weigh <span class=\"supplied\">them</span> before the chief priests, the Levites, and the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>of Israel in Jerusalem, in the chamber of the house of Adonai.”'),
('LEB', 'Ezra', '8', '30', '7', 'So the priests and Levites took over the weighed silver, gold, and the vessels to bring to Jerusalem for the house of our God.'),
('LEB', 'Ezra', '8', '31', '9', '<span class=\"verse-title\">Return to Jerusalem</span>On the twelfth day of the first month we set out from the river of Ahava to go to Jerusalem. The hand of our God was on us and he delivered us from the hand of the enemy and from ambushing on the way.'),
('LEB', 'Ezra', '8', '32', '9', 'We came to Jerusalem and remained there three days.'),
('LEB', 'Ezra', '8', '33', '9', 'On the fourth day, the silver, gold, and vessels were weighed in the house of our God into the hand of priest Meremoth, the son of Uriah, and with him Eleazar son of Phinehas. With them were the Levites, Jehozabad son of Jeshua and Noadiah son of Binnui.'),
('LEB', 'Ezra', '8', '34', '9', 'The amount and weight of all the weighed <span class=\"supplied\">items</span> was recorded at that time.'),
('LEB', 'Ezra', '8', '35', '10', 'The exiles that returned from captivity offered burnt offerings to the God of Israel; twelve bulls for all Israel, ninety-six rams, seventy-seven lambs, and twelve goats as a sin offering. All was a burnt offering to Adonai.'),
('LEB', 'Ezra', '8', '36', '10', 'They delivered the customs of the king to the king’s satraps and to the governor of <span class=\"supplied\">the province</span> Beyond the River. And they supported the people of the house of God.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '9', '1', '1', '<span class=\"verse-title\">Disdain Over Mixed Marriages</span>After finishing these things the officials approached me saying, “The people of Israel, the priests, and the Levites have not separated from the people of the lands with their detestable things, and from the Canaanites, Hittites, Perizzites, Jebusites, Ammonites, Moabites, Egyptians, and Amorites.'),
('LEB', 'Ezra', '9', '2', '1', 'For they have taken from their daughters for themselves and their sons. So the holy seed has mixed itself with the peoples of the lands, and the hand of the officials and prefects were foremost in this sin.'),
('LEB', 'Ezra', '9', '3', '1', 'When I heard this I tore my garment and my robe, and I pulled the hair out from my head and beard, and I sat appalled.'),
('LEB', 'Ezra', '9', '4', '1', 'Then all who trembled at the words of the God of Israel because of the sin of the returned exiles were gathered around me and I sat appalled until the evening offering.'),
('LEB', 'Ezra', '9', '5', '3', '<span class=\"verse-title\">Ezra Prays</span>At the evening offering I got up from my mourning posture and, with my garment and robe torn, I fell down on my knees and I spread out my palms to Adonai my God'),
('LEB', 'Ezra', '9', '6', '3', 'and said, “My God, I am ashamed and embarrassed to lift my face to you, my God. For our sins have risen above our heads and our guilt has grown up to the heavens.'),
('LEB', 'Ezra', '9', '7', '3', 'From the days of our ancestors<span class=\"note\">Or “fathers”</span>until this day we have been in great guilt, and because of our sins we ourselves, our kings, and our priests have been handed into the hand of the kings of the lands, to the sword, to captivity, to plunder, and to utter shame, as it is this day.'),
('LEB', 'Ezra', '9', '8', '3', 'But now for a brief moment mercy has been shown by Adonai our God, who left behind for us a remnant, and given us security in his holy place—for our God to brighten our eyes and to give us brief relief in our bondage.'),
('LEB', 'Ezra', '9', '9', '3', 'For we are slaves and in our bondage our God did not forsake us, and he has extended to us loyal love in the presence of the kings of Persia, to give to us deliverance<span class=\"note\">Or “preservation”</span><span class=\"supplied\">and</span> to set up the house of our God, to repair its ruins, and to give us a wall in Judea and Jerusalem.'),
('LEB', 'Ezra', '9', '10', '4', '“And now our God what shall we say after this? For we have forsaken your commandments,'),
('LEB', 'Ezra', '9', '11', '4', 'which you commanded by the hand of your servants the prophets saying, ‘The land that you are entering to possess is a land of impurity with the impurity of the peoples of the lands, with their detestable things which they have filled from end to end with their uncleanness.'),
('LEB', 'Ezra', '9', '12', '4', 'Therefore, do not give your daughters to their sons, and do not take their daughters for your sons. Do not seek their peace and prosperity so that forever you may be strong and eat the good of the land and may give it as an inheritance to your sons.’'),
('LEB', 'Ezra', '9', '13', '4', 'After all that has come upon us for our evil practices and for our great guilt—you, our God, have held back less than our guilt <span class=\"supplied\">deserved</span> and you have given us a remainder such as this.'),
('LEB', 'Ezra', '9', '14', '4', 'Shall we again break your commandments and intermarry with the peoples who practice these detestable things? Would you not be angry with us until you destroy us with no remnant or remainder?'),
('LEB', 'Ezra', '9', '15', '4', 'Adonai, God of Israel, you are righteous, for we have been left this day as a remnant. Here we are before you in our guilt, for none can stand before you because of this.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Ezra', '10', '1', '1', '<span class=\"verse-title\">The People Respond</span>While Ezra was praying and confessing, weeping and throwing himself down before the house of God, a very great assembly of men, women, and children from Israel gathered to him. And the people wept bitterly.'),
('LEB', 'Ezra', '10', '2', '1', 'Shecaniah son of Jehiel, of the sons of Elam, answered and said to Ezra, “We ourselves have broken faith with our God and have married foreign women from the peoples of the land, and even now there is hope for Israel in spite of this.'),
('LEB', 'Ezra', '10', '3', '1', 'So now let us make a covenant with our God to send away all of these women and their offspring, according to the advice of my lord and those who tremble at the commandment of our God. Let it be done according to the law.'),
('LEB', 'Ezra', '10', '4', '1', 'Arise, for it is your task and we are with you. Be strong and do it.”'),
('LEB', 'Ezra', '10', '5', '1', 'Then Ezra stood up and made the chief priests, Levites, and all of Israel swear to do according to what was said. So they swore this oath.'),
('LEB', 'Ezra', '10', '6', '3', '<span class=\"verse-title\">Foreign Wives and Children are Sent Away</span>Ezra rose from before the house of God and went to the chamber of Jehohanan son of Eliashib. He did not eat food nor drink water because he was mourning over the sin of the exiles.'),
('LEB', 'Ezra', '10', '7', '3', 'And they sent a proclamation through Judah and Jerusalem to all the <span class=\"idiom\">returned exiles</span><span class=\"note\">“the sons of the exile”</span>to assemble in Jerusalem.'),
('LEB', 'Ezra', '10', '8', '3', 'Anyone who did not come within three days, by decision of the officials and elders, all of his possessions would be devoted to God, and he himself would be excluded from the assembly of exiles.'),
('LEB', 'Ezra', '10', '9', '4', 'Then all the men of Judah and Benjamin assembled in Jerusalem within the three days. It was the ninth month on the twentieth day of the month. All the people sat in the public square of the house of God trembling because of this matter and from the rains.'),
('LEB', 'Ezra', '10', '10', '4', 'Then Ezra the priest stood up and said to them, “You have broke faith and married foreign women, increasing the guilt of Israel.'),
('LEB', 'Ezra', '10', '11', '4', 'Now make a confession to Adonai the God of your ancestors<span class=\"note\">Or “fathers”</span>and do his will. Separate yourselves from the peoples of the land and from the foreign women.”'),
('LEB', 'Ezra', '10', '12', '5', 'Then all the assembly answered with a great voice and said, “It is so. We must do according to your words.'),
('LEB', 'Ezra', '10', '13', '5', 'But the people are many, and it is the time of rain; we are unable to stand outside. The task is not for one day or two, for we greatly rebelled in this matter.'),
('LEB', 'Ezra', '10', '14', '5', 'Please let our leaders stand for the whole assembly, and let all that are in our cities who have married foreign women come at set times, and with them the elders of and judges of each city, until the fierce wrath of our God because of this matter is averted from us.”'),
('LEB', 'Ezra', '10', '15', '5', 'Only Jehonathan son of Asahel and Jahzeiah son of Tikvah stood against this, and the Levites Meshullam and Shabbethai supported them.'),
('LEB', 'Ezra', '10', '16', '6', 'The <span class=\"idiom\">returned exiles</span><span class=\"note\">“the sons of the exile”</span>did so. Ezra the priest selected men, the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>according to the house of their fathers, all of them by name. They sat down to examine the matter on the first day of the tenth month.'),
('LEB', 'Ezra', '10', '17', '6', 'They finished <span class=\"supplied\">investigating</span> all the men who married foreign women by the first day of the first month.'),
('LEB', 'Ezra', '10', '18', '7', 'There was found from the sons of the priests those who had married foreign women, from the sons of Jeshua son of Jehozadak and his brothers: Maaseiah, Eliezer, Jarib, and Gedaliah.'),
('LEB', 'Ezra', '10', '19', '7', '<span class=\"idiom\">They pledged themselves</span><span class=\"note\">“they gave their hand”</span>to put away their wives, and their guilt offering was a ram of the flock for their guilt.'),
('LEB', 'Ezra', '10', '20', '7', 'From the sons of Immer: Hanani and Zebadiah.'),
('LEB', 'Ezra', '10', '21', '7', 'From the sons of Harim: Maaseiah, Elijah, Shemaiah, Jehiel, and Uzziah.'),
('LEB', 'Ezra', '10', '22', '7', 'From the sons of Pashhur: Elioenai, Maaseiah, Ishmael, Nethanel, Jozabad, and Eleasah.'),
('LEB', 'Ezra', '10', '23', '8', 'From the Levites: Jozabad, Shimei, Kelaiah (that is, Kelita), Pethahiah, Judah, and Eliezer.'),
('LEB', 'Ezra', '10', '24', '8', 'From the singers: Eliashib. From the gatekeepers: Shallum, Telem, and Uri.'),
('LEB', 'Ezra', '10', '25', '9', 'And from Israel, the sons of Parosh: Ramiah, Izziah, Malkijah, Mijamin, Eleazar, Malkijah, and Benaiah.'),
('LEB', 'Ezra', '10', '26', '9', 'From the sons of Elam: Mattaniah, Zechariah, Jehiel, Abdi, Jeremoth, and Elijah.'),
('LEB', 'Ezra', '10', '27', '9', 'From the sons of Zattu: Elioenai, Eliashib, Mattaniah, Jeremoth, Zabad, and Aziza.'),
('LEB', 'Ezra', '10', '28', '9', 'From the sons of Bebai: Jehohanan, Hananiah, Zabbai, and Athlai.'),
('LEB', 'Ezra', '10', '29', '9', 'From the sons of Bani: Meshullam, Malluch, Adaiah, Jashub, Sheal, and Jeremoth.'),
('LEB', 'Ezra', '10', '30', '9', 'From the sons of Pahath-Moab: Adna, Kelal, Benaiah, Maaseiah, Mattaniah, Bezalel, Binnui, and Manasseh.'),
('LEB', 'Ezra', '10', '31', '9', 'From the sons of Harim: Eliezer, Isshiah, Malkijah, Shemaiah, Simeon,'),
('LEB', 'Ezra', '10', '32', '9', 'Benjamin, Malluch, and Shemariah.'),
('LEB', 'Ezra', '10', '33', '9', 'From the sons of Hashum: Mattenai, Mattattah, Zabad, Eliphelet, Jeremai, Manasseh, and Shimei.'),
('LEB', 'Ezra', '10', '34', '9', 'From the sons of Bani: Maadai, Amram, Uel,'),
('LEB', 'Ezra', '10', '35', '9', 'Benaiah, Bedeiah, Keluhi,'),
('LEB', 'Ezra', '10', '36', '9', 'Vaniah, Meremoth, Eliashib,'),
('LEB', 'Ezra', '10', '37', '9', 'Mattaniah, Mattenai, Jaasu,'),
('LEB', 'Ezra', '10', '38', '9', 'Bani, Binnui, Shimei,'),
('LEB', 'Ezra', '10', '39', '9', 'Shelemiah, Nathan, Adaiah,'),
('LEB', 'Ezra', '10', '40', '9', 'Macnadebai, Shashai, Sharai,'),
('LEB', 'Ezra', '10', '41', '9', 'Azarel, Shelemiah, Shemariah,'),
('LEB', 'Ezra', '10', '42', '9', 'Shallum, Amariah, and Joseph.'),
('LEB', 'Ezra', '10', '43', '9', 'From the sons of Nebo: Jeiel, Mattithiah, Zabad, Zebina, Iddo, Joel, and Benaiah.'),
('LEB', 'Ezra', '10', '44', '9', 'All of these had married foreign wives, and some from among the wives bore children.')
;

