INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Haggai', '1', '1', '1', '<span class=\"verse-title\">The Temple Lies in Ruins</span>In the second year of King Darius, in the sixth month, on <span class=\"supplied\">the</span> first day, the word of Adonai came <span class=\"idiom\">through</span><span class=\"note\">“through the hand of”</span>Haggai the prophet to Zerubbabel the son of Shealtiel, governor of Judah, and to Joshua the son of Jehozadak, the high priest, saying,'),
('LEB', 'Haggai', '1', '2', '1', '“Thus says Adonai of hosts: ‘This people says, “<span class=\"idiom\">The time has not come to rebuild the temple of Adonai</span>.’ ” <span class=\"note\">“The time is not coming, the time for the house of Adonai to be built”</span>'),
('LEB', 'Haggai', '1', '3', '1', 'And the word of Adonai came <span class=\"idiom\">through</span><span class=\"note\">“through the hand of”</span>Haggai the prophet, saying,'),
('LEB', 'Haggai', '1', '4', '1', '“<span class=\"supplied\">Is it</span> a time for you yourselves to dwell in your houses that have been paneled <span class=\"supplied\">while</span> this house<span class=\"note\">That is, the temple</span><span class=\"supplied\">is</span> desolate?”'),
('LEB', 'Haggai', '1', '5', '1', 'And so then, thus says Adonai of hosts: ‘<span class=\"idiom\">Consider your ways</span>!<span class=\"note\">“Set your heart on your ways”</span>'),
('LEB', 'Haggai', '1', '6', '1', 'You have sown much but have harvested little. You have eaten without <span class=\"supplied\">being</span> satisfied; <span class=\"idiom\">you have drunk without being satiated</span>;<span class=\"note\">“You have drunk, without becoming drunk”</span>you have worn clothes without <span class=\"supplied\">being</span> warm; the one who earns wages puts it in <span class=\"idiom\">a pouch with holes</span>.’<span class=\"note\">“a pierced pouch”</span>'),
('LEB', 'Haggai', '1', '7', '1', 'Thus says Adonai of hosts: ‘<span class=\"idiom\">Consider your ways</span>!<span class=\"note\">“Set your heart on your ways”</span>'),
('LEB', 'Haggai', '1', '8', '1', 'Go up the mountain and bring wood and build the house<span class=\"note\">That is, the temple</span>so that I may be pleased with it and honored,’ says Adonai.'),
('LEB', 'Haggai', '1', '9', '1', '‘You have looked for much, and look! <span class=\"supplied\">It came</span> to little; and <span class=\"supplied\">when</span> you brought <span class=\"supplied\">it</span> home, I blew it <span class=\"supplied\">away</span>. Why?’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of ”</span>Adonai of hosts. ‘Because my house <span class=\"supplied\">is</span> desolate and you <span class=\"supplied\">are</span> running each to your own house!'),
('LEB', 'Haggai', '1', '10', '1', 'Therefore, because of you <span class=\"supplied\">the</span> heavens have withheld <span class=\"supplied\">the</span> dew and the earth has withheld its produce.'),
('LEB', 'Haggai', '1', '11', '1', 'I have called for a drought on the land and the hills,<span class=\"note\">Or mountains</span>on the grain, the new wine, the olive oil, on what the soil produces, on human beings and wild animals,<span class=\"note\">Hebrew “animal”</span>and on <span class=\"idiom\">all their labor</span>.’ ”<span class=\"note\">“all the labor of <span class=\"supplied\">the</span> hands”</span>'),
('LEB', 'Haggai', '1', '12', '2', 'Zerubbabel son of Shealtiel, Joshua son of Jehozadak, the high priest, and all the remnant of the people gave heed to the voice of Adonai their God and to the words of Haggai the prophet, as Adonai their God had sent him, <span class=\"idiom\">and the people feared Adonai</span>.<span class=\"note\">“and the people feared from before Adonai”</span>'),
('LEB', 'Haggai', '1', '13', '2', 'And Haggai the messenger of Adonai spoke to the people with the message of Adonai, saying, “ ‘I <span class=\"supplied\">am</span> with you’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai.”'),
('LEB', 'Haggai', '1', '14', '2', 'And Adonai stirred up the spirit of Zerubbabel son of Shealtiel, governor of Judah, and the spirit of Joshua son of Jehozadak, the high priest, and the spirit of all the remnant of the people. And they came and did <span class=\"supplied\">the</span> work on the house of Adonai of hosts, their God,'),
('LEB', 'Haggai', '1', '15', '2', 'on the twenty-fourth day of the sixth month in the second year of King Darius.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Haggai', '2', '1', '1', '<span class=\"verse-title\">A Promise to Rebuild</span>In the seventh <span class=\"supplied\">month</span> on the twenty-first day, the word of Adonai <span class=\"idiom\">came through</span><span class=\"note\">“came through the hand of”</span>Haggai the prophet, saying,'),
('LEB', 'Haggai', '2', '2', '1', '“Speak now to Zerubbabel son of Shealtiel, governor of Judah, and to Joshua son of Jehozadak, the high priest, and to the remnant of the people, saying,'),
('LEB', 'Haggai', '2', '3', '1', '‘Who among you <span class=\"supplied\">is</span> left that saw this house in its former glory? And how do you see it now? Does it seem like nothing <span class=\"idiom\">to you</span>?<span class=\"note\">“in your eyes”</span>'),
('LEB', 'Haggai', '2', '4', '1', '‘But now take courage,<span class=\"note\">Or “be strong”</span>Zerubbabel,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai. ‘Take courage,<span class=\"note\">Or “Be strong”</span>Joshua son of Jehozadak, the high priest, and take courage,<span class=\"note\">Or “be strong”</span>all the people of the land,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai. ‘Do the work, because I <span class=\"supplied\">am</span> with you,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai of hosts,'),
('LEB', 'Haggai', '2', '5', '1', '‘according to <span class=\"idiom\">the promise</span><span class=\"note\">“the word”</span>that <span class=\"idiom\">I covenanted</span><span class=\"note\">“I cut”</span>with you when you came out of Egypt. My spirit <span class=\"idiom\">is with you</span>;<span class=\"note\">“<span class=\"supplied\">is</span> standing in your midst”</span>do not be afraid.’'),
('LEB', 'Haggai', '2', '6', '1', 'For thus says Adonai of hosts: ‘Once again, in a little while, I will shake the heavens and the earth and the sea and dry land.'),
('LEB', 'Haggai', '2', '7', '1', 'I will shake all the nations so that the treasure of all the nations will come, and I will fill this house<span class=\"note\">That is, the temple</span><span class=\"supplied\">with</span> glory,’ says Adonai of hosts.'),
('LEB', 'Haggai', '2', '8', '1', '‘The silver <span class=\"supplied\">is</span> mine and the gold <span class=\"supplied\">is</span> mine,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai of hosts.'),
('LEB', 'Haggai', '2', '9', '1', '‘The latter glory of this house will be greater than the former,’ says Adonai of hosts, ‘and in this place I will give peace’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai of hosts.’ ”'),
('LEB', 'Haggai', '2', '10', '2', 'On <span class=\"supplied\">the</span> twenty-fourth <span class=\"supplied\">day</span> of the ninth <span class=\"supplied\">month</span>, in the second year of Darius, the word of Adonai came to the prophet Haggai, saying,'),
('LEB', 'Haggai', '2', '11', '2', '“Thus says Adonai of hosts: ‘Ask now the priests <span class=\"supplied\">for</span> a ruling:<span class=\"note\">Or “a torah,” or “a law”</span>'),
('LEB', 'Haggai', '2', '12', '2', 'If a man carries<span class=\"note\">“lifts”</span>consecrated meat in the hem of his garment, and his hem touches bread, or stew, or wine, or olive oil, or any kind of food, will it become holy?’ ” The priests answered, “No.”'),
('LEB', 'Haggai', '2', '13', '2', 'Then Haggai said, “If one who is unclean from contact with a corpse touches any of these, will it become unclean?” The priests answered, “Yes, it will be become unclean.”'),
('LEB', 'Haggai', '2', '14', '2', 'And Haggai answered and said, “ ‘So <span class=\"supplied\">it is with</span> this people, and <span class=\"supplied\">with</span> this nation before me,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai, ‘and so <span class=\"supplied\">it is with</span> every kind of work of their hands; and what they offer there <span class=\"supplied\">is</span> unclean.'),
('LEB', 'Haggai', '2', '15', '2', 'But now, please <span class=\"idiom\">consider</span><span class=\"note\">“set your heart”</span>from this day forward, before one stone was placed on another in the temple of Adonai,'),
('LEB', 'Haggai', '2', '16', '2', '<span class=\"idiom\">from that time when</span><span class=\"note\">Or “from their being,” or “from the time they were then”</span>one came to a heap of twenty <span class=\"supplied\">measures</span>, there were <span class=\"supplied\">only</span> ten, and <span class=\"supplied\">when</span> one came to the wine vat to draw out fifty measures,<span class=\"note\">Hebrew “measure”</span>there were <span class=\"supplied\">only</span> twenty.'),
('LEB', 'Haggai', '2', '17', '2', 'I struck you with blight, and with plant mildew, and hail, all the work of your hands. But <span class=\"idiom\">you did not come back to me</span>,’<span class=\"note\">“there were none of you to me”</span><span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai.'),
('LEB', 'Haggai', '2', '18', '2', '‘<span class=\"idiom\">Please consider</span><span class=\"note\">“Please set your heart”</span>from this day forward, from the twenty-fourth day of the ninth <span class=\"supplied\">month</span>, from the day that the foundation of Adonai’s temple was laid,<span class=\"note\">Or “placed,” or “set”</span><span class=\"idiom\">consider</span>:<span class=\"note\">“set your heart”</span>'),
('LEB', 'Haggai', '2', '19', '2', '<span class=\"supplied\">Is there</span> still seed in the store chamber? Do the vine, the fig tree, the pomegranate, and the olive tree still produce nothing? From this day <span class=\"supplied\">forward</span> I will bless <span class=\"supplied\">you</span>.’ ”'),
('LEB', 'Haggai', '2', '20', '4', '<span class=\"verse-title\">The Coming Kingdom</span>And the word of Adonai came to Haggai a second time on the twenty-fourth <span class=\"supplied\">day</span> of the month saying,'),
('LEB', 'Haggai', '2', '21', '4', '“Say to Zerubbabel, governor of Judah: I <span class=\"supplied\">am</span> going to shake the heavens and the earth,'),
('LEB', 'Haggai', '2', '22', '4', 'and I will overthrow the thrones of kingdoms and destroy the military strength of the kingdoms of the nations. I will overthrow chariots and their drivers; horses and their riders will fall, every one by the sword of another!'),
('LEB', 'Haggai', '2', '23', '4', '‘On that day,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai of hosts, ‘I will take you, Zerubbabel son of Shealtiel, my servant,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai, ‘and I will make you a signet ring, for I have chosen you,’ <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai of hosts.”')
;

