INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '1', '1', '1', '<span class=\"verse-title\">God Commands Hosea to Start a Family</span>The word of Adonai that came to Hosea son of Beeri, in the days of Uzziah, Jotham, Ahaz, and Hezekiah, the kings of Judah, and in the days of Jeroboam the son of Joash, king of Israel.'),
('LEB', 'Hosea', '1', '2', '2', '<span class=\"idiom\">At the beginning when Adonai spoke</span><span class=\"note\">Literally “<span class=\"supplied\">At</span> the beginning of the talking of Adonai”</span>through Hosea,  Adonai said to Hosea,  “Go, take for yourself a wife and children of whoredom,  because the land commits great whoredom  <span class=\"idiom\">forsaking Adonai</span>.”<span class=\"note\">Literally “from behind Adonai”</span>'),
('LEB', 'Hosea', '1', '3', '2', 'So he went and took Gomer daughter of Diblaim,  and she conceived and bore him a son.'),
('LEB', 'Hosea', '1', '4', '2', 'And Adonai said to him,  “<span class=\"idiom\">Name him</span><span class=\"note\">Literally “Call his name”</span>Jezreel;<span class=\"note\">Jezreel means “God sows”</span> because in a little while <span class=\"idiom\">I will punish</span><span class=\"note\">Literally “I will visit sin upon”</span>the house of Jehu<span class=\"note\">Or “the dynasty of Jehu”</span> for the blood<span class=\"note\">Or “bloodshed”</span>of Jezreel,<span class=\"note\">Jezreel means “God sows”</span> and I will put an end to the kingdom of the house of Israel.<span class=\"note\">Or “the dynasty of Israel”</span>'),
('LEB', 'Hosea', '1', '5', '2', '<span class=\"idiom\">On that day</span><span class=\"note\">Literally “And it will happen on that day”</span> I will break the bow of Israel  in the Valley of Jezreel.”'),
('LEB', 'Hosea', '1', '6', '3', 'And she conceived again and bore a daughter, and he<span class=\"note\">Adonai</span>said to him,'),
('LEB', 'Hosea', '1', '7', '4', '“<span class=\"idiom\">Name her</span><span class=\"note\">Literally “Call her name”</span>Lo-ruhamah,<span class=\"note\">Lo-ruhamah means “Not pitied”</span> for I will no longer have pity  on the house of Israel  or <span class=\"idiom\">forgive them</span>.<span class=\"note\">Literally “raise them up”</span>'),
('LEB', 'Hosea', '1', '8', '4', 'But I will have pity <span class=\"supplied\">on</span> the house of Judah  and I will save them by Adonai their God,  and will not deliver them  by bow, sword, war,  horses, or horsemen.'),
('LEB', 'Hosea', '1', '9', '4', 'And when she had weaned Lo-ruhamah,<span class=\"note\">Lo-ruhamah means “Not pitied”</span>she conceived and bore a son.'),
('LEB', 'Hosea', '1', '10', '4', 'And he<span class=\"note\">Adonai</span>said, “<span class=\"idiom\">Name him</span><span class=\"note\">Literally “Call his name”</span>Lo-ammi,<span class=\"note\">Lo-ammi means “not my people”</span> for you <span class=\"supplied\">are</span> not my people  and I am not your <span class=\"supplied\">God</span>.<span class=\"note\">Hebrew “not yours”</span>'),
('LEB', 'Hosea', '1', '11', '4', '<span class=\"note\">Hosea 1:10–2:23 in the English Bible is 2:1–25 in the Hebrew Bible</span>The number of the children of Israel  will be like the sand of the sea  that cannot be measured or counted;  and in the place where it is said to them,  “You are not my people,”  it will be said to them,  “Children of <span class=\"supplied\">the</span> living God.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '2', '1', '1', '<span class=\"verse-title\">The Unfaithful Wife</span>Say to your brother,<span class=\"note\">Hebrew “brothers”</span>“Ammi,”<span class=\"note\">Ammi means “My people”</span> and to your sister,<span class=\"note\">Hebrew “sisters”</span>“Ruhamah.”<span class=\"note\">Ruhamah means “Pitied”</span>'),
('LEB', 'Hosea', '2', '2', '1', 'Plead with your mother, plead—  because she <span class=\"supplied\">is</span> not my wife,  and I <span class=\"supplied\">am</span> not her husband.  Let her put away her whoring <span class=\"idiom\">from before her</span>,<span class=\"note\">Literally “from her face”</span> and her adultery from between her breasts.'),
('LEB', 'Hosea', '2', '3', '1', 'Lest I strip her naked  and expose her like the day when she was born;  I will make her like the desert  and turn her into parched land;  I will kill her with thirst.'),
('LEB', 'Hosea', '2', '4', '1', 'And I will not have pity on her children,  because <span class=\"supplied\">they are</span> children of whoredom.'),
('LEB', 'Hosea', '2', '5', '1', 'Because their mother was unfaithful;<span class=\"note\">Or “their mother played the whore”</span> she who conceived them has acted shamefully,  for she said:  “I will go after my lovers,  the ones who give <span class=\"supplied\">me</span> my bread, my water,  my wool, and my flax,  my oil, and my drink.”'),
('LEB', 'Hosea', '2', '6', '1', 'Therefore, Look!  I <span class=\"supplied\">am</span> going to hedge her path<span class=\"note\">Hebrew “your path”</span><span class=\"idiom\">with thorns</span>,<span class=\"note\">Literally “with the thorns”</span> and I will build a stone wall, a stone wall <span class=\"supplied\">against</span> her,  and she will not find her paths.'),
('LEB', 'Hosea', '2', '7', '1', 'Then she will pursue <span class=\"idiom\">her lovers</span>,<span class=\"note\">Literally “the ones who love her”</span> but she will not overtake them;  she will seek them and not find <span class=\"supplied\">them</span>;  and she will say, “I will go  and return to my first husband  because <span class=\"supplied\">it was</span> better for me then than now.”'),
('LEB', 'Hosea', '2', '8', '1', 'But she did not know  that <span class=\"supplied\">it was</span> I who gave her  grain, new wine, and oil,  and who gave her silver in abundance,  and gold which they made into a Baal.'),
('LEB', 'Hosea', '2', '9', '1', 'Therefore I will take again  my grain in its time,  and my wine in its season;  and I will take away my wool and my flax,  <span class=\"supplied\">which were</span> to cover her nakedness.'),
('LEB', 'Hosea', '2', '10', '1', 'And now I will uncover her nakedness  before the eyes of her lovers,  and no one will rescue her from my hand.'),
('LEB', 'Hosea', '2', '11', '1', 'And I will put an end to all her mirth,  her festivals,<span class=\"note\">Hebrew “festival”</span>her new moons,<span class=\"note\">Hebrew “new moon”</span>and her Sabbaths,<span class=\"note\">Hebrew “Sabbath”</span> and all her appointed festivals;<span class=\"note\">Hebrew “festival”</span>'),
('LEB', 'Hosea', '2', '12', '1', 'and I will lay waste to her vines<span class=\"note\">Hebrew “vine”</span>and her fig trees,<span class=\"note\">Hebrew “fig tree”</span> of which she said,  “They <span class=\"supplied\">are</span> my payment for prostitution,  which my lovers gave to me.”  I will make them a forest,  and the wild animals<span class=\"note\">Hebrew “animal”</span>of the field will devour them.'),
('LEB', 'Hosea', '2', '13', '1', '<span class=\"idiom\">I will punish her</span><span class=\"note\">Literally “To visit sins upon her;” see 1:4</span><span class=\"supplied\">for</span> the days of the Baals,  to whom she burns incense,  and she decked herself <span class=\"supplied\">with</span> her ornamental ring and jewelry,  and she went after her lovers, and forgot me  —a declaration of Adonai.'),
('LEB', 'Hosea', '2', '14', '1', 'Therefore, Look! I <span class=\"supplied\">am</span> going to allure her  and bring her <span class=\"supplied\">into</span> the desert,  and <span class=\"idiom\">I will speak tenderly to her</span>.<span class=\"note\">Literally “I will speak to her heart”</span>'),
('LEB', 'Hosea', '2', '15', '1', 'From there I will give her  her vineyards,  and the Valley of Achor as a doorway of hope.  And there she will respond,  as <span class=\"supplied\">in</span> the days of her youth,  just as <span class=\"supplied\">in</span> the day of her coming out of  the land of Egypt.'),
('LEB', 'Hosea', '2', '16', '1', '<span class=\"idiom\">And on that day</span>—<span class=\"note\">Literally, “And it will happen on that day”</span> a declaration of Adonai—  you will call me, “My husband;”<span class=\"note\">Hebrew “Ishi”</span> you will no longer call me, “My Baal.”<span class=\"note\">Hebrew “Baali”</span>'),
('LEB', 'Hosea', '2', '17', '1', 'I will remove the names  of the Baals from her mouth,  and they will no longer be mentioned by their name.'),
('LEB', 'Hosea', '2', '18', '1', 'I will make a covenant for them on that day,  with the animals<span class=\"note\">Hebrew “animal”</span>of the field,  with the birds<span class=\"note\">Hebrew “bird”</span>of the heaven, and  <span class=\"supplied\">with</span> the creeping things<span class=\"note\">Hebrew “creeping thing”</span>of the ground;  <span class=\"supplied\">the</span> bow, <span class=\"supplied\">the</span> sword, and <span class=\"supplied\">the</span> war I will abolish from the land, and I will let them lie down in safety.'),
('LEB', 'Hosea', '2', '19', '1', 'And I will take you as my wife forever;  I will take you as a wife for myself in righteousness and in justice,  in steadfast love and in mercy.'),
('LEB', 'Hosea', '2', '20', '1', '<span class=\"idiom\">I will take you as my wife</span><span class=\"note\">Literally “I will take you as a wife to me”</span>in faithfulness,  and you will know Adonai.'),
('LEB', 'Hosea', '2', '21', '1', 'On that day I will answer, <span class=\"idiom\">declares Adonai</span>,<span class=\"note\">Literally “a declaration of Adonai</span> I will answer the heavens,  and they will answer the earth.'),
('LEB', 'Hosea', '2', '22', '1', 'And the earth will answer  the grain, the wine, and the oil,  and they will answer Jezreel.<span class=\"note\">Jezreel means “God sows”</span>'),
('LEB', 'Hosea', '2', '23', '1', 'I will sow her for myself in the land;  I will have pity on Lo-ruhama;<span class=\"note\">Lo-ruhama means “Not pitied”</span> I will say to Lo-ammi,<span class=\"note\">Lo-ammi means “Not my people”</span> “You are my people,”  and he himself will say, “<span class=\"supplied\">you are</span> my God.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '3', '1', '1', '<span class=\"verse-title\">Another Symbolic Marriage</span>And Adonai said to me again,  “Go, love a woman  <span class=\"idiom\">who has a lover</span><span class=\"note\">Literally “<span class=\"supplied\">who is</span> beloved of a friend”</span>and <span class=\"supplied\">is</span> committing adultery,  just like the love of Adonai <span class=\"supplied\">for</span> the children of Israel,  but they <span class=\"supplied\">are</span> turning to other gods  and love raisin cakes.”'),
('LEB', 'Hosea', '3', '2', '1', 'So I bought her for fifteen shekels of silver  and a homer of barely and a measure of wine.<span class=\"note\">Hebrew “a measure of barley”; the LXX has “a nebel of wine,” although some modern translations, e.g. NASB, have “a homer and a half of barley”</span>'),
('LEB', 'Hosea', '3', '3', '1', 'And I said to her,  “<span class=\"idiom\">You must remain as mine</span><span class=\"note\">Literally “You must sit <span class=\"supplied\">at home</span> for me”</span>for many days,  and you will not play the whore;  <span class=\"idiom\">you will not belong</span><span class=\"note\">Literally “you will not be”</span>to a man,  and I <span class=\"supplied\">will</span> belong to you.”'),
('LEB', 'Hosea', '3', '4', '1', 'The children of Israel will remain for many days  without a king and prince,  without sacrifice and stone pillar, ephod and teraphim.'),
('LEB', 'Hosea', '3', '5', '1', 'Afterward the children of Israel will return  and seek Adonai their God and David their king.  They will come in fear to Adonai  and to his goodness at the end of days.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '4', '1', '1', '<span class=\"verse-title\">Adonai Has an Indictment</span>Hear the word of Adonai, <span class=\"supplied\">O</span> children of Israel,  for Adonai has an indictment against the inhabitants of the land.  There is no faithfulness or loyalty,  there is no knowledge of God in the land.'),
('LEB', 'Hosea', '4', '2', '1', 'Swearing and lying,  murdering and stealing,  and adultery break out,<span class=\"note\">The LXX adds “and adultery breaks out in the land”</span> and bloodshed follows bloodshed.'),
('LEB', 'Hosea', '4', '3', '1', 'Therefore the land mourns,  and all <span class=\"supplied\">those</span> living in it languish  with the animals of the field,  and the birds of the heaven,  and even the fish of the sea  are being swept away.'),
('LEB', 'Hosea', '4', '4', '1', 'Yet, let no one contend,  and let no one accuse,  for with you, O priest, <span class=\"supplied\">is my</span> contention.<span class=\"note\">The Hebrew is unclear; the NASB translates “For your people are like those who contend with the priest”</span>'),
('LEB', 'Hosea', '4', '5', '1', 'You will stumble <span class=\"supplied\">by</span> day,  and the priest also will stumble  with you at night.  And I will destroy your mother;'),
('LEB', 'Hosea', '4', '6', '1', 'My people are destroyed  for lack of knowledge;  because you have rejected knowledge,  I reject you from acting as a priest for me.<span class=\"note\">Or “to me”</span> And since you have forgotten the law of your God,  I will also forget your children.<span class=\"note\">Hebrew “sons”</span>'),
('LEB', 'Hosea', '4', '7', '1', 'When they became many, their sin increased against me;  they changed<span class=\"note\">Hebrew uncertain; MT “I will exchange”</span>their glory into shame.'),
('LEB', 'Hosea', '4', '8', '1', '<span class=\"idiom\">They feed on the sin of my people</span>,<span class=\"note\">Literally “They eat the sins of my people”</span> <span class=\"idiom\">they are greedy</span><span class=\"note\">Literally “they lift up their throat”</span>for their iniquity.'),
('LEB', 'Hosea', '4', '9', '1', 'And it will be like people, like priest;  I will punish them<span class=\"note\">Hebrew “him”</span><span class=\"supplied\">for</span> their<span class=\"note\">Hebrew “his”</span>ways,  and I will requite them<span class=\"note\">Hebrew “him”</span>for their<span class=\"note\">Hebrew “his”</span>deeds.'),
('LEB', 'Hosea', '4', '10', '1', 'They will eat and not be satisfied;  they will play the whore and not multiply,  because they have forsaken Adonai <span class=\"idiom\">to devote themselves to'),
('LEB', 'Hosea', '4', '11', '1', 'whoredom</span>.<span class=\"note\">Literally “to watch over whoredom”</span> Wine and new wine <span class=\"idiom\">take away the understanding</span>.<span class=\"note\">Literally “take away heart”</span>'),
('LEB', 'Hosea', '4', '12', '1', 'My people,  consult <span class=\"idiom\">their wooden idols</span>,<span class=\"note\">Literally “their wood”</span> and their divining rod gives them oracles;  because a spirit of whoredom led <span class=\"supplied\">them</span> astray,  and they played the whore from under their God.<span class=\"note\">That is, “they played the whore forsaking their God”; See Ezek 23:5</span>'),
('LEB', 'Hosea', '4', '13', '1', 'On the tops of the mountains they sacrifice,  and on the hills they make offerings,  under oak, poplar, and terebinth,  because their<span class=\"note\">Hebrew “its”</span>shade is good.  Therefore your daughters play the whore,  and all your daughters-in-law<span class=\"note\">Or “brides”</span>commit adultery.'),
('LEB', 'Hosea', '4', '14', '1', '<span class=\"idiom\">I will not punish your daughters</span><span class=\"note\">Literally “I will not visit sins upon your daughters”</span>when they play the whore,  or your daughters-in-law<span class=\"note\">Or “brides”</span>when they commit adultery;  because they go aside with whores,  and they sacrifice with temple prostitutes,  a people that does not understand comes to ruin.'),
('LEB', 'Hosea', '4', '15', '1', 'Even though you, <span class=\"supplied\">O</span> Israel, <span class=\"supplied\">are</span> playing the whore,  do not let Judah become guilty;  do not enter Gilgal,  or go up <span class=\"supplied\">to</span> Beth-aven;  and do not swear,  “<span class=\"idiom\">As Adonai lives</span>!”<span class=\"note\">Literally “the life of Adonai”</span>'),
('LEB', 'Hosea', '4', '16', '1', 'Indeed, like a stubborn heifer,  Israel is stubborn;  Now Adonai will feed them,  like a lamb in broad pasture.<span class=\"note\">Or “Can Adonai feed them, like a lamb in broad pasture?”</span>'),
('LEB', 'Hosea', '4', '17', '1', 'Ephraim is joined to idols;  let him alone.'),
('LEB', 'Hosea', '4', '18', '1', 'When their drinking has ended,  they surely indulge in sexual orgies.  They love lewdness more than their<span class=\"note\">Hebrew “her”</span>glory.'),
('LEB', 'Hosea', '4', '19', '1', 'A wind has wrapped them<span class=\"note\">Hebrew “her”</span>in its wings,  and they will be ashamed because of their altars.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '5', '1', '1', '<span class=\"verse-title\">The Priests Are a Snare</span>Hear this, <span class=\"supplied\">O</span> priests!  Give heed, <span class=\"supplied\">O</span> house of Israel!  Listen, <span class=\"supplied\">O</span> house of the king!  Because the judgment <span class=\"supplied\">applies</span> to you;  because you have been a snare for Mizpah,  and a net spread out on Tabor;'),
('LEB', 'Hosea', '5', '2', '1', 'they dug a deep pit<span class=\"note\">Hebrew uncertain</span><span class=\"supplied\">in</span> Shittim,  but I <span class=\"supplied\">am</span> a punishment for all of them.'),
('LEB', 'Hosea', '5', '3', '1', 'I myself know Ephraim,  and Israel is not hidden from me;  because now you have played the whore, <span class=\"supplied\">O</span> Ephraim—  Israel is defiled.'),
('LEB', 'Hosea', '5', '4', '1', 'Their deeds do not permit them  to return them to God.  Because a spirit of whoredom <span class=\"supplied\">is</span> in their midst,  they do not know Adonai.'),
('LEB', 'Hosea', '5', '5', '1', 'The pride of Israel testifies <span class=\"idiom\">against him</span>,<span class=\"note\">Literally “against his face;” see 7:10</span> and Israel and Ephraim stumble in their guilt,  and Judah stumbles with them.'),
('LEB', 'Hosea', '5', '6', '1', 'With their flocks<span class=\"note\">Hebrew “flock”</span>and herds<span class=\"note\">Hebrew “herd”</span>they will go  to seek Adonai, but they will not find him;  he has withdrawn from them.'),
('LEB', 'Hosea', '5', '7', '1', 'They have dealt faithlessly with Adonai  because they have borne illegitimate children.  Now <span class=\"supplied\">the</span> new moon will devour them with their fields.'),
('LEB', 'Hosea', '5', '8', '1', 'Blow the <span class=\"idiom\">horn</span><span class=\"note\">Hebrew “shofar”</span>in Gibeah,  <span class=\"supplied\">the</span> trumpet in Ramah.  Sound the alarm <span class=\"supplied\">in</span> Beth-aven;  <span class=\"supplied\">look</span> behind you, Benjamin.'),
('LEB', 'Hosea', '5', '9', '1', 'Ephraim will be a desolation  in the day of punishment;  among the tribes of Israel  I will reveal what is true.'),
('LEB', 'Hosea', '5', '10', '1', 'The princes of Judah have become  like those who remove a landmark;  on them I will pour out  my wrath like water.'),
('LEB', 'Hosea', '5', '11', '1', 'Ephraim is oppressed,  crushed <span class=\"supplied\">in</span> judgment,  because he was determined  to go after filth.<span class=\"note\">Hebrew uncertain; another possible translation is “that he follows human commands”</span>'),
('LEB', 'Hosea', '5', '12', '1', 'But I <span class=\"supplied\">am</span> like a maggot to Ephraim  and like rottenness to the house of Judah.'),
('LEB', 'Hosea', '5', '13', '1', 'And <span class=\"supplied\">when</span> Ephraim saw his illness,  and Judah his wound,  Ephraim went to Assyria,  he sent to the great king.<span class=\"note\">Some translate literally “King Jareb” (see the NASB, NKJV)</span> But he was unable to cure you  and heal your wound.'),
('LEB', 'Hosea', '5', '14', '1', 'Because I <span class=\"supplied\">will be</span> like a lion to Ephraim  and like a fierce strong lion to the house of Judah.  I myself will tear and I will go;  I will carry off, and there is no one who delivers.'),
('LEB', 'Hosea', '5', '15', '1', '<span class=\"idiom\">I will return again</span><span class=\"note\">Literally “I will go, I will return”</span>to my place  until they acknowledge <span class=\"supplied\">their</span> guilt  and seek my face;  in their distress they will search<span class=\"note\">Or “they will beg favor of”</span>me.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '6', '1', '1', '<span class=\"verse-title\">A Call to Adonai</span>Come, let us return to Adonai;  because <span class=\"supplied\">it is</span> he who has torn, and he will heal us;  he has struck us down and will bind us up.'),
('LEB', 'Hosea', '6', '2', '1', 'He will revive us after two days;  on the third day he will raise us up,  that we may live in his presence.<span class=\"note\">Or “before his face”</span>'),
('LEB', 'Hosea', '6', '3', '1', 'Let us know, let us press on to know Adonai;  his rising <span class=\"supplied\">is</span> sure like <span class=\"supplied\">the</span> dawn.  He will come like the showers to us,  like <span class=\"supplied\">the</span> spring rain that waters <span class=\"supplied\">the</span> earth.'),
('LEB', 'Hosea', '6', '4', '1', 'What will I do with you, <span class=\"supplied\">O</span> Ephraim?  What will I do with you, <span class=\"supplied\">O</span> Judah?  Your love <span class=\"supplied\">is</span> like a morning cloud,  like the dew that goes away early in the morning.'),
('LEB', 'Hosea', '6', '5', '1', 'Therefore, I have hewn <span class=\"supplied\">them</span> by <span class=\"supplied\">the</span> prophets;  I have killed them by the words of my mouth,  and my judgment<span class=\"note\">Hebrew “your judgments”</span>goes forth like the light.'),
('LEB', 'Hosea', '6', '6', '1', 'Because I desire steadfast love and not sacrifice,  and knowledge of God rather than burnt offerings.'),
('LEB', 'Hosea', '6', '7', '1', 'But like Adam, they transgressed <span class=\"supplied\">the</span> covenant;  there they dealt faithlessly with me.'),
('LEB', 'Hosea', '6', '8', '1', 'Gilead <span class=\"supplied\">is</span> a city of evil,  a cunning <span class=\"supplied\">city</span> because of blood.<span class=\"note\">The Hebrew is difficult; NRSV translates “tracked with blood”</span>'),
('LEB', 'Hosea', '6', '9', '1', 'Like bandits lying in wait,  <span class=\"supplied\">so is</span> a band of priests;  they murder <span class=\"supplied\">on the</span> road to Shechem;  indeed, they commit a monstrous crime.'),
('LEB', 'Hosea', '6', '10', '1', 'In the house of Israel I have seen something horrible;  Ephraim’s unfaithfulness <span class=\"supplied\">is</span> there.  Israel is defiled.'),
('LEB', 'Hosea', '6', '11', '3', '<span class=\"verse-title\">Ephraim’s Guilt</span>For you also, <span class=\"supplied\">O</span> Judah, a harvest is appointed,  when I restore the fortunes of my people,')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '7', '1', '0', 'when I would heal Israel,  and the corruption of Ephraim is revealed,  and the wicked deeds of Samaria;  because they deal <span class=\"supplied\">in</span> falsehood,  <span class=\"supplied\">the</span> thief breaks in,<span class=\"note\">Or “comes in”</span> <span class=\"supplied\">and the</span> bandit raids the outside.'),
('LEB', 'Hosea', '7', '2', '0', '<span class=\"idiom\">But they did not consider</span><span class=\"note\">Literally “But they did not say to their heart”</span> that I remember all their wickedness.  Now their deeds surround them;  they are before my face.'),
('LEB', 'Hosea', '7', '3', '0', 'By their wickedness they make <span class=\"supplied\">the</span> king glad,  and <span class=\"supplied\">the</span> officials by their treacheries.'),
('LEB', 'Hosea', '7', '4', '0', 'All of them commit adultery,  like a burning oven  whose baker has stopped from stirring the fire,  and from kneading <span class=\"supplied\">the</span> dough until it is leavened.'),
('LEB', 'Hosea', '7', '5', '0', '<span class=\"supplied\">On</span> the day of our king, the princes  became sick <span class=\"supplied\">with</span> the heat of wine;<span class=\"note\">This phrase refers to the effects of wine on the body</span> he stretched out his hand with mockers.'),
('LEB', 'Hosea', '7', '6', '0', 'Because they are kindled<span class=\"note\">Hebrew “they drew near;” other ancient translations read “they are kindled”</span>like an oven,  their heart burns within them;  all night their anger <span class=\"idiom\">smolders</span>,<span class=\"note\">Literally “sleeps”</span> <span class=\"supplied\">in the</span> morning it blazes like a flaming fire.'),
('LEB', 'Hosea', '7', '7', '0', 'All of them are hot as an oven,  and they devour<span class=\"note\">Or “they eat”</span>their rulers.  All their kings have fallen;  there is none who calls to me amongst them.'),
('LEB', 'Hosea', '7', '8', '0', 'Ephraim mixes himself  with the nations;  Ephraim is a bread cake  not turned over.'),
('LEB', 'Hosea', '7', '9', '0', 'Foreigners devour<span class=\"note\">Or “Foreigners eat”</span>his strength,  and he does not know <span class=\"supplied\">it</span>;  <span class=\"idiom\">mold</span><span class=\"note\">Literally “grey hair,” but in this case the word refers to the “hairs of mold” on food</span>is also sprinkled upon him,  and he does not know <span class=\"supplied\">it</span>.'),
('LEB', 'Hosea', '7', '10', '0', 'The pride of Israel <span class=\"idiom\">testifies against him</span><span class=\"note\">Literally “answers against his face”</span>—  they do not return to Adonai their God;  they do not seek him for all of this.<span class=\"note\">Or “in all of this”</span>'),
('LEB', 'Hosea', '7', '11', '0', 'Ephraim was like a dove,  silly, <span class=\"idiom\">without sense</span>;<span class=\"note\">Literally “without heart”</span> they call <span class=\"supplied\">to</span> Egypt,  they go <span class=\"supplied\">to</span> Assyria.'),
('LEB', 'Hosea', '7', '12', '0', 'Just as they go, I will cast my net  over them;  I will bring them down  like the birds<span class=\"note\">Hebrew “bird”</span>of the heavens;<span class=\"note\">Or “sky”</span> I will discipline them  according to a report to their assembly.<span class=\"note\">Hebrew uncertain</span>'),
('LEB', 'Hosea', '7', '13', '0', 'Woe to them, because they have strayed from me!  Destruction to them, because they have rebelled against me!  I myself would redeem them,  but they speak lies against me.'),
('LEB', 'Hosea', '7', '14', '0', 'They do not cry out to me from their heart,  but they wail on their beds;  because of grain and new wine they lacerate<span class=\"note\">Or “gash”</span>themselves;  they depart from me.'),
('LEB', 'Hosea', '7', '15', '0', 'And I myself trained  and strengthened their arms;  but they plan evil against me.'),
('LEB', 'Hosea', '7', '16', '0', 'They turn, not to the Most High,<span class=\"note\">Hebrew uncertain; the NRSV translates “to that which does not profit”; the NASB translates “but not upward”</span> like a slack bow;  their officials will fall by the sword  because of the anger of their tongue.  This <span class=\"supplied\">is</span> their scorn<span class=\"note\">The NRSV translates “So much for their babbling”</span> in the land of Egypt.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '8', '1', '1', '<span class=\"verse-title\">Israel Rejects the Good</span><span class=\"supplied\">Put</span> to your lips <span class=\"supplied\">the</span> trumpet  like a vulture over the house of Adonai,  because they have <span class=\"idiom\">broken my covenant</span><span class=\"note\">Literally “transgressed my covenant”</span> and rebelled against my law.'),
('LEB', 'Hosea', '8', '2', '1', 'They cry out to me,  “My God! We, Israel, know you!”'),
('LEB', 'Hosea', '8', '3', '1', 'Israel has spurned <span class=\"supplied\">the</span> good;  <span class=\"supplied\">the</span> enemy will pursue him.'),
('LEB', 'Hosea', '8', '4', '1', 'They appointed kings, but not through me;  they made officials, but without my knowledge.  <span class=\"supplied\">With</span> their silver and gold  they made idols for themselves  for their<span class=\"note\">Hebrew “his”</span>own <span class=\"idiom\">destruction</span>.<span class=\"note\">Literally “cut off”</span>'),
('LEB', 'Hosea', '8', '5', '1', 'Your calf is rejected,<span class=\"note\">Hebrew “he rejects” or “has rejected you”</span><span class=\"supplied\">O</span> Samaria;  my anger burns against them.  How long<span class=\"note\">Hebrew “Until when”</span>will they be incapable of innocence?'),
('LEB', 'Hosea', '8', '6', '1', 'Because <span class=\"supplied\">it is</span> from Israel,  an artisan made it,  it <span class=\"supplied\">is</span> not a god;  for the calf of Samaria  will be broken <span class=\"supplied\">to</span> pieces.'),
('LEB', 'Hosea', '8', '7', '1', 'Because they sow the wind,  they will reap the whirlwind.  <span class=\"supplied\">The</span> standing grain does not have heads;<span class=\"note\">Hebrew “head”</span> it will not yield flour.  <span class=\"supplied\">And</span> if it would yield,  strangers would devour it.'),
('LEB', 'Hosea', '8', '8', '1', 'Israel is swallowed up;  now they are among the nations,  like an object that no one desires.'),
('LEB', 'Hosea', '8', '9', '1', 'For they have gone up <span class=\"supplied\">to</span> Assyria,  a wild donkey alone to itself;  Ephraim has sold itself <span class=\"supplied\">for</span> lovers.'),
('LEB', 'Hosea', '8', '10', '1', 'Even though they have sold themselves to the nations,  now I will gather them.  They will soon writhe  from the burden of kings<span class=\"note\">Hebrew “king”</span>and princes.'),
('LEB', 'Hosea', '8', '11', '1', 'When Ephraim multiplied altars  to expiate sins,  they became to him altars to sin <span class=\"supplied\">on</span>.'),
('LEB', 'Hosea', '8', '12', '1', 'I write for him myriads of my instruction;<span class=\"note\">Or “my law”</span> they are regarded as a strange thing.'),
('LEB', 'Hosea', '8', '13', '1', 'They offer sacrifices of my choice<span class=\"note\">Hebrew uncertain; or “loved ones”</span> and they eat flesh;  Adonai does not accept them.  Now he will remember their iniquity  and punish their sins;  they will return <span class=\"supplied\">to</span> Egypt.'),
('LEB', 'Hosea', '8', '14', '1', 'Israel has forgotten his maker and built palaces,  and Judah has multiplied fortified cities;  but I will send fire on his cities  and it will devour her strongholds.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '9', '1', '1', '<span class=\"verse-title\">Ephraim Faces Punishment</span>Do not rejoice, <span class=\"supplied\">O</span> Israel,  do not exult like the nations!  For you played the whore, departing from your God;  you loved a harlot’s wage  on all the threshing floors of grain.'),
('LEB', 'Hosea', '9', '2', '1', 'Threshing floor and wine vat will not feed them,  and new wine will fail her.<span class=\"note\">That is, Israel</span>'),
('LEB', 'Hosea', '9', '3', '1', 'They will not remain  in the land of Adonai.  But Ephraim will return <span class=\"supplied\">to</span> Egypt,  and in Assyria they will eat unclean food.'),
('LEB', 'Hosea', '9', '4', '1', 'They will not pour <span class=\"supplied\">drink offerings of</span> wine to Adonai,  and their sacrifices will not please him.  <span class=\"supplied\">They are</span> like mourners’ bread for them;  all those who eat it will be defiled.  For their bread will be <span class=\"idiom\">for their hunger</span>;<span class=\"note\">Literally “for their soul”</span> it will not come <span class=\"supplied\">to</span> the house of Adonai.'),
('LEB', 'Hosea', '9', '5', '1', 'What will you do on the day of <span class=\"supplied\">the</span> appointed time,  and on the day of the festival of Adonai?'),
('LEB', 'Hosea', '9', '6', '1', 'For look! <span class=\"supplied\">If</span> they flee from the destruction,  Egypt will gather them;  Memphis<span class=\"note\">Hebrew “Noph”</span>will bury them.  Nettles will possess  their precious things of silver;  thorns <span class=\"supplied\">will be</span> in their tents.'),
('LEB', 'Hosea', '9', '7', '1', 'The days of punishment have come;  the days of retribution have come;  Israel knows!  The prophet <span class=\"supplied\">is</span> a fool,  the man of the spirit <span class=\"supplied\">is</span> acting like a madman.  Because of the greatness of your sin,  <span class=\"supplied\">your</span> hostility <span class=\"supplied\">is</span> great.'),
('LEB', 'Hosea', '9', '8', '1', 'The prophet keeps watch <span class=\"supplied\">over</span> Ephraim for my God;  the snare of a fowler <span class=\"supplied\">is</span> on all his ways,  and hostility in the house of his God.'),
('LEB', 'Hosea', '9', '9', '1', '<span class=\"idiom\">They deeply corrupted themselves</span><span class=\"note\">Literally “They made deep, they corrupted themselves”</span> as <span class=\"supplied\">in</span> the days of Gibeah;  he will remember their sin,  he will punish their sins.'),
('LEB', 'Hosea', '9', '10', '1', 'Like the grapes in the wilderness,  I found Israel.  Like early ripened fruit on the fig tree in the first season,<span class=\"note\">Or “in the beginning”</span> I saw your ancestors.<span class=\"note\">Or “fathers”</span> They themselves came <span class=\"supplied\">to</span> Baal Peor,  and they consecrated themselves to shame.  And they became detestable things,  like <span class=\"idiom\">the thing they love</span>.<span class=\"note\">Literally “like loving things”</span>'),
('LEB', 'Hosea', '9', '11', '1', 'Ephraim’s glory <span class=\"supplied\">is</span> like a bird;  it will fly away—  no birth, no pregnancy, and no conception.'),
('LEB', 'Hosea', '9', '12', '1', 'Even though they bring up their children,  I will bereave them before maturity.<span class=\"note\">Or “until no one is left”</span> Woe to them indeed,  when I depart from them!'),
('LEB', 'Hosea', '9', '13', '1', 'Ephraim, as I see <span class=\"supplied\">it</span>,  <span class=\"supplied\">is</span> like a palm in a meadow;  but Ephraim must bring out  his children to the slayer.'),
('LEB', 'Hosea', '9', '14', '1', 'Give them, <span class=\"supplied\">O</span> Adonai—  what will you give <span class=\"supplied\">them</span>?  Give them a miscarrying womb  and dry breasts.'),
('LEB', 'Hosea', '9', '15', '1', 'Every evil of theirs <span class=\"supplied\">began</span> at Gilgal,  so I <span class=\"supplied\">began</span> to hate them there;  because of the evil of their deeds  I will drive them out from my house.  I will love them no more;  all their officials <span class=\"supplied\">are</span> rebels.'),
('LEB', 'Hosea', '9', '16', '1', 'Ephraim is stricken,  their root is dried up,  they shall not bear fruit.  Even if they give birth,  I will kill the cherished offspring of their womb.'),
('LEB', 'Hosea', '9', '17', '1', 'My God will reject them  because they did not listen to him,  and they will be wanderers among the nations.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '10', '1', '1', '<span class=\"verse-title\">Israel Is Punished</span>Israel <span class=\"supplied\">is</span> a luxuriant vine;<span class=\"note\">Or “ravaged vine”</span> he yields fruit for himself.  The more his fruit increased,  <span class=\"supplied\">the more</span> he made numerous altars.  The more his land prospered,  <span class=\"supplied\">the more</span> he<span class=\"note\">Hebrew “they”</span>improved<span class=\"note\">Or “made beautiful”</span><span class=\"supplied\">his</span> stone pillars.'),
('LEB', 'Hosea', '10', '2', '1', 'Their heart is false;  now they must bear <span class=\"supplied\">their</span> guilt.  He himself<span class=\"note\">That is, “Adonai himself”</span>will break down their altars;  he will destroy their stone pillars.'),
('LEB', 'Hosea', '10', '3', '1', 'For now they will say,  “We have no king;  indeed, we did not fear Adonai,  and what can a king do for us?”'),
('LEB', 'Hosea', '10', '4', '1', 'They utter words of vain oaths  <span class=\"supplied\">when</span> <span class=\"idiom\">making covenants</span>,<span class=\"note\">Literally “cutting covenant”</span> and judgment blossoms like a poisonous plant  on the furrows of the field.'),
('LEB', 'Hosea', '10', '5', '1', 'The inhabitants<span class=\"note\">Hebrew “inhabitant”</span>of Samaria tremble  for the calf<span class=\"note\">Hebrew “calves”</span>of Beth-aven.  Indeed, his people will mourn for it,  and his idolatrous priests will wail<span class=\"note\">Or “rejoice”</span>over it—  over its glory because it has departed from it.'),
('LEB', 'Hosea', '10', '6', '1', 'It will also be brought to Assyria,  <span class=\"supplied\">as</span> tribute to <span class=\"supplied\">the</span> great king.<span class=\"note\">See 5:13; some translate literally “King Jareb”</span> Ephraim will obtain disgrace  and Israel will be ashamed from his advice.<span class=\"note\">Or “counsel”</span>'),
('LEB', 'Hosea', '10', '7', '1', 'Samaria will be destroyed;  her king <span class=\"supplied\">is</span> like a chip on the surface of the water.'),
('LEB', 'Hosea', '10', '8', '1', 'The high places of Aven,  the sin of Israel, will be destroyed.  Thorn and thistle will grow  on their altars.  They will say to the mountains, “Cover us,”  and to the hills, “Fall on us.”'),
('LEB', 'Hosea', '10', '9', '1', 'From the days of Gibeah you have sinned, <span class=\"supplied\">O</span> Israel;  there <span class=\"idiom\">they have remained</span>.<span class=\"note\">Literally “they stood”</span> Will not war in Gibeah overtake them  against the children of evil?'),
('LEB', 'Hosea', '10', '10', '1', 'In my desire<span class=\"note\">The LXX translates “I will come”</span>I will punish them;  nations will be gathered against them  when they are punished for <span class=\"idiom\">their double iniquities</span>.<span class=\"note\">So <span class=\"italic\">Qere</span>; Masoretic Hebrew text (<span class=\"italic\">Kethib</span>) “their two eyes”</span>'),
('LEB', 'Hosea', '10', '11', '1', 'Ephraim <span class=\"supplied\">was</span> a trained heifer,  that loved to thresh <span class=\"supplied\">grain</span>,  and I myself <span class=\"idiom\">spared</span><span class=\"note\">Literally “passed over”</span> the fairness of her neck;  I will make Ephraim break the ground,  Judah will plow,  Jacob must till for himself.'),
('LEB', 'Hosea', '10', '12', '1', 'Sow for yourselves righteousness;  <span class=\"idiom\">reap loyal love</span>.<span class=\"note\">Literally “reap according to loyal love”</span> Break up for yourself fallow ground;  <span class=\"supplied\">it is</span> time to seek Adonai  so he will come and rain  righteousness upon you.'),
('LEB', 'Hosea', '10', '13', '1', 'You have plowed wickedness,  you have reaped injustice,  you have eaten the fruit of lies,<span class=\"note\">Hebrew “lie”</span> because you have trusted in your strength,  in the multitude of your warriors.'),
('LEB', 'Hosea', '10', '14', '1', 'The tumult of war will rise up against your people,  and all your fortresses will be destroyed,  as Shalman destroyed Beth-arbel;  on the day of war  mothers were dashed to pieces with <span class=\"supplied\">their</span> children.<span class=\"note\">Or “upon <span class=\"supplied\">their</span> children”</span>'),
('LEB', 'Hosea', '10', '15', '1', 'So it will be done to you, <span class=\"supplied\">O</span> Bethel,  because of the evil of your wickedness;  at dawn, the king of Israel  will be utterly destroyed.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '11', '1', '1', '<span class=\"verse-title\">God Will Have Compassion</span>When Israel was a child, I loved him,  and out of Egypt I called my son.'),
('LEB', 'Hosea', '11', '2', '1', 'When I called<span class=\"note\">Hebrew “When they called”; the LXX and modern translations read “When I called”</span>them, they went from my face.<span class=\"note\">Hebrew “their face”</span> They sacrificed to the Baals, and they sacrificed to idols.'),
('LEB', 'Hosea', '11', '3', '1', 'And I myself taught Ephraim to walk;  I took them<span class=\"note\">Hebrew uncertain</span>in my<span class=\"note\">Hebrew “his”</span>arms,  but they did not know that I healed them.'),
('LEB', 'Hosea', '11', '4', '1', 'I drew them <span class=\"idiom\">with human ties</span>,<span class=\"note\">Literally “ropes of a human”</span> with the bands of love.  I was to them like one who lifted up<span class=\"note\">Or “like one who imposed”</span>a yoke on their jaws,<span class=\"note\">Or “infants to their cheeks”</span> <span class=\"supplied\">though</span> I bent down to them<span class=\"note\">Hebrew “him”</span><span class=\"supplied\">and</span> let them<span class=\"note\">Hebrew “him”</span>eat.'),
('LEB', 'Hosea', '11', '5', '1', 'He will return<span class=\"note\">Or “They will not return”</span>to the land of Egypt,  and Assyria will be his king,<span class=\"note\">That is “Israel’s king”</span> because they refused to return.'),
('LEB', 'Hosea', '11', '6', '1', '<span class=\"supplied\">The</span> sword rages in his cities;  it consumes his false prophets  and devours because of their plans.'),
('LEB', 'Hosea', '11', '7', '1', 'My people are bent on backsliding from me.  To the Most High they call,  he does not raise them at all.'),
('LEB', 'Hosea', '11', '8', '1', 'How can I give you up, <span class=\"supplied\">O</span> Ephraim?  <span class=\"supplied\">How</span> can I hand you over, <span class=\"supplied\">O</span> Israel?  How can I make you like Admah?  <span class=\"supplied\">How</span> can I treat you like Zeboiim?  My heart is disturbed<span class=\"note\">Or “My heart is overturned”</span>within me;  <span class=\"idiom\">all</span><span class=\"note\">Literally “together”</span>my compassions are aroused.'),
('LEB', 'Hosea', '11', '9', '1', '<span class=\"idiom\">I will not execute</span><span class=\"note\">Literally “I will not do”</span><span class=\"idiom\">my fierce anger</span>,<span class=\"note\">Literally “the anger of my nose”</span> I will not again destroy Ephraim;  because I <span class=\"supplied\">am</span> God  and not a mortal,<span class=\"note\">Or “human”</span> <span class=\"supplied\">the</span> Holy <span class=\"supplied\">One</span> in your midst;  and I will not come in wrath.'),
('LEB', 'Hosea', '11', '10', '1', 'They will go after Adonai;  he roars like a lion.  When he roars,  his children will come trembling  from <span class=\"supplied\">the</span> sea.<span class=\"note\">That is, “<span class=\"supplied\">the</span> West”</span>'),
('LEB', 'Hosea', '11', '11', '1', 'They will tremble like birds<span class=\"note\">Hebrew “bird”</span>from Egypt,  and like doves<span class=\"note\">Hebrew “dove”</span>from the land of Assyria;  and I will let them return<span class=\"note\">Hebrew “I will cause them to live”</span>to their homes—  a declaration of Adonai.'),
('LEB', 'Hosea', '11', '12', '3', '<span class=\"verse-title\">Israel’s History</span><span class=\"note\">Hosea 11:12–12:14 in the English Bible is 12:1–15 in the Hebrew Bible</span>Ephraim has surrounded me with lies,<span class=\"note\">Hebrew “lie”</span> and the house of Israel with deceit;  and Judah is still wandering with God  and <span class=\"supplied\">is</span> faithful to the Holy One.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '12', '1', '0', 'Ephraim herds <span class=\"supplied\">the</span> wind<span class=\"note\">Or “Ephraim befriends <span class=\"supplied\">the</span> wind”</span> and <span class=\"supplied\">is</span> pursuing <span class=\"supplied\">the</span> east wind all day long;  he multiplies deception and violence  and he<span class=\"note\">Hebrew “they”</span><span class=\"idiom\">makes a treaty with Assyria</span>,<span class=\"note\">Literally “cuts a covenant with Assyria”</span> and oil is brought to Egypt.'),
('LEB', 'Hosea', '12', '2', '0', 'Adonai has a quarrel<span class=\"note\">This word in Hebrew conveys a legal setting</span>with Judah  and will punish Jacob according to his ways  and repay him according to his deeds.'),
('LEB', 'Hosea', '12', '3', '0', 'In the womb he deceived his brother,  and in his manhood he struggled with God.'),
('LEB', 'Hosea', '12', '4', '0', 'He struggled with <span class=\"supplied\">the</span> angel and prevailed;  he pleaded for his mercy.  He met him at Bethel,  and there he spoke with him.<span class=\"note\">Hebrew “us”</span>'),
('LEB', 'Hosea', '12', '5', '0', 'Adonai the God of hosts,  Adonai <span class=\"supplied\">is</span> his renowned name!'),
('LEB', 'Hosea', '12', '6', '0', 'But you, you must return to your God;  keep love and justice,  and wait continually for your God.'),
('LEB', 'Hosea', '12', '7', '0', '<span class=\"supplied\">The</span> trader, in his hand <span class=\"supplied\">are</span> scales of deceit;<span class=\"note\">Or “false balances”</span> he loves to oppress.'),
('LEB', 'Hosea', '12', '8', '0', 'And Ephraim said, “Surely, I am rich,  I gained<span class=\"note\">Or “I found”</span>wealth for myself;  in all my toil they have not found guilt in me  that is <span class=\"supplied\">sin</span>.'),
('LEB', 'Hosea', '12', '9', '0', 'But I <span class=\"supplied\">am</span> Adonai your God  since<span class=\"note\">Or “from”</span>the land of Egypt;  I will make you live in tents again,  like the days of <span class=\"supplied\">the</span> appointed festival.'),
('LEB', 'Hosea', '12', '10', '0', 'I spoke to the prophets;  I myself multiplied revelations<span class=\"note\">Hebrew “revelation”</span> and through the hand of the prophets I will destroy.'),
('LEB', 'Hosea', '12', '11', '0', 'If <span class=\"supplied\">in</span> Gilead <span class=\"supplied\">there is</span> evil,  surely they will come to nothing.  In Gilgal they sacrifice bulls,  also their altars will be like stone heaps  on furrows of <span class=\"supplied\">the</span> field.'),
('LEB', 'Hosea', '12', '12', '0', 'Jacob fled <span class=\"supplied\">to</span> the open field of Aram,<span class=\"note\">Or “the land of Aram”</span> and Israel served for a wife,  and for a wife he watched over <span class=\"supplied\">sheep</span>.'),
('LEB', 'Hosea', '12', '13', '0', 'And by a prophet Adonai brought  Israel up from Egypt,  and by a prophet  he<span class=\"note\">Israel</span>was watched over.'),
('LEB', 'Hosea', '12', '14', '0', 'Ephraim has caused bitter provocation,  and his Lord will <span class=\"idiom\">hold him responsible for his crimes</span><span class=\"note\">Literally “will bring down on him his blood”</span> and pay back to him his insults.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '13', '1', '1', '<span class=\"verse-title\">Adonai’s Judgment on Idolatrous Israel</span>When Ephraim spoke,<span class=\"note\">Hebrew “speaks”</span><span class=\"supplied\">there was</span> terror;  he was exalted in Israel,  but he incurred guilt through Baal and died.'),
('LEB', 'Hosea', '13', '2', '1', 'And now they sin again,  and they make for themselves a molten idol,  idols from their silver metal according to their understanding,  all of them the work of skilled craftsmen.  To these they say, “Sacrifice!”  People are kissing bull calves.'),
('LEB', 'Hosea', '13', '3', '1', 'Therefore, they will be like the morning cloud,  and like <span class=\"supplied\">the</span> dew of early morning going <span class=\"supplied\">away</span>,  like chaff swirling from <span class=\"supplied\">the</span> threshing floor,  or like smoke from a window.'),
('LEB', 'Hosea', '13', '4', '1', 'I <span class=\"supplied\">am</span> Adonai your God  since<span class=\"note\">Or “from”</span>the land of Egypt;  you know no god except me,  and no one saves besides me.'),
('LEB', 'Hosea', '13', '5', '1', 'I fed you<span class=\"note\">So LXX; Hebrew “I knew you”</span>in the desert,  in the land of drought.'),
('LEB', 'Hosea', '13', '6', '1', 'When I fed them,<span class=\"note\">Hebrew “According to their pasture”</span>they were satisfied;  they were satisfied and their heart was lifted up;  therefore they forgot me.'),
('LEB', 'Hosea', '13', '7', '1', 'And I will be like a lion to them;  I lie in wait beside <span class=\"supplied\">the</span> way, like a leopard.'),
('LEB', 'Hosea', '13', '8', '1', 'I will attack them like a bear robbed of her offspring,  and I will tear open the covering of their heart;  there I will devour them like a lion,  like an animal of the field would mutilate them.'),
('LEB', 'Hosea', '13', '9', '1', 'I will destroy you,<span class=\"note\">Hebrew “He destroys you”</span><span class=\"supplied\">O</span> Israel;  who will help you?<span class=\"note\">Hebrew “for in me, in your help”</span>'),
('LEB', 'Hosea', '13', '10', '1', 'Where now <span class=\"supplied\">is</span> your king that he may save you?  <span class=\"supplied\">Where</span> in all your cities <span class=\"supplied\">are</span> your judges,  of whom you said, “Give to  me a king and rulers?”'),
('LEB', 'Hosea', '13', '11', '1', 'I gave you a king in my anger,  and I took <span class=\"supplied\">him</span> in my wrath.'),
('LEB', 'Hosea', '13', '12', '1', 'The sin of Ephraim <span class=\"supplied\">is</span> wrapped up;  his sin <span class=\"supplied\">is</span> concealed.'),
('LEB', 'Hosea', '13', '13', '1', 'The labor pains of childbirth come for him;  he <span class=\"supplied\">is</span> an unwise son  because <span class=\"supplied\">at the</span> proper time, he does not present himself  <span class=\"idiom\">at the mouth of the womb</span>.<span class=\"note\">Literally “the place where the sons burst forth”</span>'),
('LEB', 'Hosea', '13', '14', '1', 'Should I redeem them from <span class=\"idiom\">the power</span><span class=\"note\">Literally “the hand”</span>of Sheol? <span class=\"note\">“Sheol” is a Hebrew term for the place where the dead reside, i.e., the underworld</span> Should I deliver them from death?  Where <span class=\"supplied\">are</span> your plagues, <span class=\"supplied\">O</span> Death?  Where <span class=\"supplied\">is</span> your destruction, <span class=\"supplied\">O</span> Sheol?<span class=\"note\">“Sheol” is a Hebrew term for the place where the dead reside, i.e., the underworld</span> Compassion is hidden from my eyes.'),
('LEB', 'Hosea', '13', '15', '1', 'Although he may flourish among reeds,<span class=\"note\">Hebrew “brothers”</span> <span class=\"supplied\">the</span> east wind will come, a wind of Adonai  rising from <span class=\"supplied\">the</span> desert;  his fountain will dry up,  his spring will be parched.  It will plunder his treasury,<span class=\"note\">Or “its treasury”</span> every object of desire.'),
('LEB', 'Hosea', '13', '16', '1', '<span class=\"note\">Hosea 13:16–14:9 in the English Bible is 14:1–10 in the Hebrew Bible</span>Samaria will be guilty,  because she has rebelled against her God;  they will fall by <span class=\"supplied\">the</span> sword,  their children will be dashed to pieces,  and their pregnant women will be ripped open.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Hosea', '14', '1', '1', '<span class=\"verse-title\">Return to Adonai</span>Return to Adonai your God, <span class=\"supplied\">O</span> Israel,  for you have stumbled because of your sin.'),
('LEB', 'Hosea', '14', '2', '1', 'Take words with you,  and return to Adonai.  Say to him,  “Take away all guilt;  accept good, and we will offer  the fruit<span class=\"note\">Hebrew uncertain</span>of our lips.'),
('LEB', 'Hosea', '14', '3', '1', 'Assyria will not save us;  we will not ride on horses,<span class=\"note\">Hebrew “horse”</span> and we will say no more, “Our God,”  to the work of our hands  because in you <span class=\"supplied\">the</span> fatherless child finds mercy.'),
('LEB', 'Hosea', '14', '4', '1', 'I will heal their disloyalty;<span class=\"note\">Or “backsliding”</span> I will love them freely  because my anger has turned back  from them.<span class=\"note\">Hebrew “him”</span>'),
('LEB', 'Hosea', '14', '5', '1', 'I will be like the dew to Israel;  he will blossom like the lily plant,  and he will strike his roots like the <span class=\"supplied\">trees of</span> Lebanon.'),
('LEB', 'Hosea', '14', '6', '1', 'His new plant shoots will spread out;  his splendor will be like the olive tree,  and his scent like the <span class=\"supplied\">trees of</span> Lebanon.'),
('LEB', 'Hosea', '14', '7', '1', '<span class=\"idiom\">They will again dwell</span><span class=\"note\">Literally “They shall return, they shall dwell”</span>in my<span class=\"note\">Hebrew “his”</span>shadow;  they will grow grain  and they will blossom like the plant vine;  his fame <span class=\"supplied\">will be</span> like the wine of Lebanon.'),
('LEB', 'Hosea', '14', '8', '1', '<span class=\"supplied\">O</span> Ephraim, <span class=\"idiom\">what have I to do</span><span class=\"note\">Literally “what for me”</span>with idols?  I myself have answered and looked after you.<span class=\"note\">Hebrew “him”</span> I am like a luxuriant cypress;  your fruit<span class=\"note\">Or “your faithfulness”</span>comes from me.'),
('LEB', 'Hosea', '14', '9', '1', 'Who <span class=\"supplied\">is</span> wise that he can understand these <span class=\"supplied\">things</span>?  Who is discerning that he knows them?  The ways of Adonai <span class=\"supplied\">are</span> right,  and <span class=\"supplied\">the</span> righteous walk in them;  but transgressors stumble in them.')
;

