INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Jonah', '1', '1', '1', '<span class=\"verse-title\">Jonah Disobeys Adonai</span>And the word of Adonai came to Jonah the son of Amittai, saying,'),
('LEB', 'Jonah', '1', '2', '1', '“Get up! Go to the great city Nineveh and cry out against her, because their evil has come up <span class=\"idiom\">before me</span>.”<span class=\"note\">Literally “to my face”</span>'),
('LEB', 'Jonah', '1', '3', '1', 'But Jonah set out to flee toward Tarshish from <span class=\"idiom\">the presence of</span><span class=\"note\">Literally “from to face of”</span>Adonai. And he went down <span class=\"supplied\">to</span> Joppa and found a merchant ship going <span class=\"supplied\">to</span> Tarshish, and paid her fare, and went on board her to go with them toward Tarshish from <span class=\"idiom\">the presence of</span><span class=\"note\">Literally “from to face of”</span>Adonai.'),
('LEB', 'Jonah', '1', '4', '2', 'And Adonai hurled a great wind upon the sea, and it was a great storm on the sea, and the merchant ship <span class=\"idiom\">was in danger of breaking up</span>.<span class=\"note\">Literally “threatened to be broken up”</span>'),
('LEB', 'Jonah', '1', '5', '2', 'And the mariners were afraid, and each cried out to his god. And they threw the <span class=\"idiom\">contents</span><span class=\"note\">Literally “objects”</span>that were in the merchant ship into the sea to lighten it for them. And <span class=\"supplied\">meanwhile</span> Jonah went down into the hold of the vessel and lay down and fell asleep.'),
('LEB', 'Jonah', '1', '6', '2', 'And the captain<span class=\"note\">Or “commander”</span>of the ship approached him and said to him, “Why are you <span class=\"idiom\">sound asleep</span>?<span class=\"note\">Literally “in a deep sleep”</span>Get up! Call on your god! Perhaps <span class=\"supplied\">your</span> god<span class=\"note\">Literally “the god,” with the article indicating previous reference</span>will take notice of us and we won’t perish!”'),
('LEB', 'Jonah', '1', '7', '2', 'And they said <span class=\"idiom\">to one another</span>,<span class=\"note\">Literally “each to his friend/companion”</span>“Come, let us cast lots so that we may know on whose account this disaster <span class=\"supplied\">has come</span> on us!” And they cast lots, and the lot fell on Jonah.'),
('LEB', 'Jonah', '1', '8', '2', 'So they said to him, “Please tell us whoever <span class=\"supplied\">is responsible that</span> this disaster <span class=\"supplied\">has come</span> upon us! What <span class=\"supplied\">is</span> your occupation? And from where do you come? What <span class=\"supplied\">is</span> your country? And from which people <span class=\"supplied\">are</span> you?”'),
('LEB', 'Jonah', '1', '9', '2', 'And he said to them, “I <span class=\"supplied\">am</span> a Hebrew, and I fear Adonai, the God of heaven, who made the sea and the dry land.”'),
('LEB', 'Jonah', '1', '10', '2', 'Then the men <span class=\"idiom\">were greatly afraid</span>,<span class=\"note\">Literally “were afraid with a great fear”</span>and they said to him, “What <span class=\"supplied\">is</span> this you have done?” because they<span class=\"note\">Literally “the men” but this is redundant in English</span>knew that he <span class=\"supplied\">was</span> fleeing <span class=\"idiom\">from the presence of</span><span class=\"note\">Literally “from before the face of”</span>Adonai (because he had told them).'),
('LEB', 'Jonah', '1', '11', '2', 'So they said to him, “What shall we do to you so that the sea may quiet down for us?” because the sea <span class=\"idiom\">was growing more and more tempestuous</span>.<span class=\"note\">Literally “going/growing and storming”</span>'),
('LEB', 'Jonah', '1', '12', '2', 'And he said to them, “Pick me up and hurl me into the sea so that the sea may quiet down for you, because I know that on account of me this great storm <span class=\"supplied\">has come</span> upon you all.”'),
('LEB', 'Jonah', '1', '13', '2', 'But the men rowed <span class=\"supplied\">hard</span> to bring <span class=\"supplied\">the ship</span><span class=\"note\">Here the direct object is supplied from context</span>back to the dry land, and they could not <span class=\"supplied\">do so</span> because the sea <span class=\"idiom\">was growing more and more tempestuous</span><span class=\"note\">Literally “going/growing and storming”</span>against them.'),
('LEB', 'Jonah', '1', '14', '2', 'So they cried out to Adonai, and they said, “O Adonai! Please do not let us perish because of this man’s life, and <span class=\"idiom\">do not make us guilty of innocent blood</span>,<span class=\"note\">Literally “do not give innocent blood on us”</span>because you, O Adonai, did what you wanted.”'),
('LEB', 'Jonah', '1', '15', '2', 'And they picked Jonah up and hurled him into the sea, and the sea ceased from its raging.'),
('LEB', 'Jonah', '1', '16', '2', 'So the men feared Adonai <span class=\"idiom\">greatly</span>,<span class=\"note\">Literally “with a great fear”</span>and they offered a sacrifice to Adonai and <span class=\"idiom\">made</span><span class=\"note\">Literally “vowed”</span>vows.'),
('LEB', 'Jonah', '1', '17', '4', '<span class=\"verse-title\">Jonah Is Swallowed by a Fish and Prays to Adonai</span><span class=\"note\">Jonah 1:17–2:10 in the English Bible is 2:1–11 in the Hebrew Bible</span>And Adonai provided a large fish to swallow up Jonah, and Jonah was in the belly of the fish three days and three nights.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Jonah', '2', '1', '0', 'And Jonah prayed to Adonai his God from the belly of the fish'),
('LEB', 'Jonah', '2', '2', '0', 'and said,'),
('LEB', 'Jonah', '2', '3', '1', '“I called <span class=\"idiom\">from my distress</span><span class=\"note\">Literally “from distress for me”</span>to Adonai,  and he answered me;  from the belly of Sheol<span class=\"note\">“Sheol” is a Hebrew term for the place where the dead reside (i.e. the Underworld)</span>I cried for help—  you heard my voice.'),
('LEB', 'Jonah', '2', '4', '1', 'And you threw me <span class=\"supplied\">into the</span> deep,  into the heart of <span class=\"supplied\">the</span> seas,  and <span class=\"supplied\">the</span> sea currents surrounded me;  all your breakers and your surging waves  passed over me.'),
('LEB', 'Jonah', '2', '5', '1', 'And I said, ‘I am banished<span class=\"note\">Or “expelled,” or “driven away”</span> from your sight;  how<span class=\"note\">Or “however, I will continue to look on your holy temple”</span><span class=\"idiom\">will I continue to look</span><span class=\"note\">Literally “will I do again to look,” meaning “will I continue to look”</span> <span class=\"idiom\">on your holy temple</span>?’<span class=\"note\">Literally “on the temple of your holiness”</span>'),
('LEB', 'Jonah', '2', '6', '1', '<span class=\"supplied\">The</span> waters encompassed me up to <span class=\"supplied\">my</span> neck;  <span class=\"supplied\">the</span> deep surrounded me;  seaweed was wrapped around my head.'),
('LEB', 'Jonah', '2', '7', '1', 'I went down to the foundations of <span class=\"supplied\">the</span> mountains;  the Underworld—its bars <span class=\"supplied\">were</span> around me forever.  But you brought up my life from <span class=\"supplied\">the</span> pit,  Adonai my God.'),
('LEB', 'Jonah', '2', '8', '1', 'When my life was ebbing away from me,  I remembered Adonai,  and my prayer came to you,  <span class=\"idiom\">to your holy temple</span>.<span class=\"note\">Literally “to the temple of your holiness”</span>'),
('LEB', 'Jonah', '2', '9', '1', 'Those who worship vain idols  forsake their loyal love.<span class=\"note\">This could mean (1) they forsake the loyal love they should show to God or (2) they forfeit <span class=\"supplied\">forsake</span> the loyal love that God would have shown to them</span>'),
('LEB', 'Jonah', '2', '10', '2', 'And Adonai spoke to the fish, and it vomited Jonah out on the dry land.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Jonah', '3', '1', '1', '<span class=\"verse-title\">The People of Nineveh Repent at Jonah’s Proclamation</span>And the word of Adonai came to Jonah a second <span class=\"supplied\">time</span>, saying,'),
('LEB', 'Jonah', '3', '2', '1', '“Get up! Go to Nineveh, the great city, and proclaim to it the message that I <span class=\"supplied\">am</span> telling you.”'),
('LEB', 'Jonah', '3', '3', '1', 'So Jonah got up<span class=\"note\">Or “set out”</span>and went to Nineveh according to the word of Adonai. Now Nineveh was <span class=\"idiom\">an extraordinarily great city</span><span class=\"note\">Literally “a great city to God” or “a great city to <span class=\"supplied\">the</span> gods,” a disputed phrase which may refer to God’s estimate or ownership of Nineveh, to the presence of many idols, or an idiom referring to the size of Nineveh (this translation takes the last view)</span>—a journey of three days <span class=\"supplied\">across</span>.<span class=\"note\">This phrase may also refer to a journey on which business was done, so that “three days” is the total elapsed time</span>'),
('LEB', 'Jonah', '3', '4', '1', 'And Jonah began to go into the city a journey of one day, and he cried out and said, “Forty more days and Nineveh will be demolished!”<span class=\"note\">Or “overthrown”</span>'),
('LEB', 'Jonah', '3', '5', '1', 'And the people of Nineveh believed in God, and they proclaimed a fast and put on sackcloth—from the greatest of them <span class=\"idiom\">to the least important</span>.<span class=\"note\">Literally “to the smallest of them”</span>'),
('LEB', 'Jonah', '3', '6', '3', '<span class=\"verse-title\">The King’s Proclamation</span>And the news reached the king of Nineveh, and he rose from his throne and removed his royal robe, put on sackcloth, and sat in the ashes.'),
('LEB', 'Jonah', '3', '7', '3', 'And he had a proclamation made, and said, “In Nineveh, by a decree of the king and his nobles:'),
('LEB', 'Jonah', '3', '8', '5', '“No human being or animal, no herd or flock, shall taste anything! They must not eat, and they must not drink water!'),
('LEB', 'Jonah', '3', '9', '5', 'And <span class=\"supplied\">the</span> human beings and <span class=\"supplied\">the</span> animals must be covered <span class=\"supplied\">with</span> sackcloth! And they must call forcefully to God, and each must turn from his evil way and from the violence that is in his<span class=\"note\">Hebrew “their”</span>hands.'),
('LEB', 'Jonah', '3', '10', '6', 'And God saw their deeds—that they turned from their evil ways—and God changed his mind about the evil that he had said <span class=\"supplied\">he would</span> bring upon them, and he did not do <span class=\"supplied\">it</span>.<span class=\"note\">Here the direct object is supplied from context in the English translation</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Jonah', '4', '1', '1', '<span class=\"verse-title\">Jonah Is Angry at Adonai’s Compassion</span>And this<span class=\"note\">Hebrew “it”</span><span class=\"idiom\">was greatly displeasing</span><span class=\"note\">Literally “was displeasing <span class=\"supplied\">with</span> great displeasure”</span>to Jonah, and <span class=\"idiom\">he became furious</span>.<span class=\"note\">Literally “it was hot for him”</span>'),
('LEB', 'Jonah', '4', '2', '1', 'And he prayed to Adonai and said, “O Adonai, <span class=\"supplied\">was</span> this not <span class=\"idiom\">what I said</span><span class=\"note\">Literally “my word”</span>while I was in my homeland? Therefore <span class=\"idiom\">I originally fled</span><span class=\"note\">Literally “I did the first time to flee”</span>to Tarshish, because I knew that you <span class=\"supplied\">are</span> a gracious and compassionate God, slow to anger <span class=\"idiom\">and having great steadfast love</span>,<span class=\"note\">Literally “and great of steadfast love”</span>and one who relents concerning calamity.<span class=\"note\">That is, calamity sent by God as judgment</span>'),
('LEB', 'Jonah', '4', '3', '1', 'And so then, Adonai, please take my life from me, because <span class=\"supplied\">for</span> me death <span class=\"supplied\">is</span> better than life!”'),
('LEB', 'Jonah', '4', '4', '1', 'And Adonai said, “<span class=\"idiom\">Is it right for you to be angry</span>?”<span class=\"note\">Literally “Rightfully is it hot for you”; some take this to mean “Are you so very angry?” (<span class=\"italic\">Targum</span> Jonah 4:4; see also JPS, NEB, NET)</span>'),
('LEB', 'Jonah', '4', '5', '2', 'And Jonah went out from the city and sat <span class=\"supplied\">down</span> east of the city, and he made for himself a shelter there. And he sat under it in the shade, <span class=\"idiom\">waiting to see</span><span class=\"note\">Literally “until he would see”</span>what would happen with the city.'),
('LEB', 'Jonah', '4', '6', '2', 'And Adonai appointed a plant,<span class=\"note\">Probably a castor oil plant, though some have suggested some type of gourd plant</span>and he made it grow up over Jonah to be a shade over his head, to save him from his discomfort. And Jonah <span class=\"idiom\">was very glad</span><span class=\"note\">Literally “was glad with great joy”</span>about the plant.'),
('LEB', 'Jonah', '4', '7', '2', 'So God appointed a worm <span class=\"idiom\">at daybreak</span><span class=\"note\">Literally “at the coming up of the dawn”</span>the next day, and it attacked the plant, and it withered.'),
('LEB', 'Jonah', '4', '8', '2', '<span class=\"idiom\">And when the sun rose</span>,<span class=\"note\">Literally “and it happened at the rising of the sun”</span>God appointed a scorching east wind, and the sun beat down on Jonah’s head and he grew faint. <span class=\"idiom\">And he asked that he could die</span><span class=\"note\">Literally “and he asked his soul to die”</span>and said, “My death <span class=\"supplied\">is</span> better than my life!”'),
('LEB', 'Jonah', '4', '9', '2', 'So God said to Jonah, “<span class=\"idiom\">Is it right for you to be angry</span><span class=\"note\">Literally “rightfully is it hot for you”; some take this to mean “Are you so very angry?” (<span class=\"italic\">Targum</span> Jonah 4:4; see also JPS, NEB, NET)</span>about the plant?” And he said, “<span class=\"idiom\">It is right for me to be angry enough to die</span>!”<span class=\"note\">Literally “Rightfully it is hot for me until death”</span>'),
('LEB', 'Jonah', '4', '10', '3', 'But Adonai said, “You are troubled about the plant, for which you did not labor nor cause it to grow. <span class=\"idiom\">It grew up in a night and it perished in a night</span>!<span class=\"note\">Literally “Which was a son of a night and <span class=\"supplied\">as</span> a son of a night it perished”</span>'),
('LEB', 'Jonah', '4', '11', '3', 'And should I not be concerned about Nineveh, the great city, <span class=\"idiom\">in which there are</span><span class=\"note\">Literally “which there are in it”</span>more <span class=\"idiom\">than one hundred and twenty thousand</span><span class=\"note\">Literally “than two ten myriad” (12 x 10,000)</span>people who do not know right from left,<span class=\"note\">“<span class=\"supplied\">hand</span>” is often supplied, but it is not clear just what deficiency is meant by this expression, which occurs only here in biblical Hebrew</span>plus many animals?”')
;

