INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Lamentations', '1', '1', '1', '<span class=\"verse-title\">The Desolate City</span>How desolate the city sits  <span class=\"supplied\">that</span> was full of people!  She has become like a widow,  <span class=\"supplied\">once</span> great among the nations!  Like a woman of nobility in the provinces,  she has become a forced laborer.'),
('LEB', 'Lamentations', '1', '2', '1', 'She weeps bitterly in the night,  her tears <span class=\"supplied\">are</span> on her cheeks;  she has no comforter  among all her lovers.  All her friends have been unfaithful to her;  they have become her enemies.'),
('LEB', 'Lamentations', '1', '3', '1', 'Judah has gone into exile with misery  and under hard servitude;  she lives among the nations,  she has not found a resting place;  all her pursuers have overtaken her  amidst <span class=\"supplied\">her</span> distress.'),
('LEB', 'Lamentations', '1', '4', '1', 'The roads of Zion <span class=\"supplied\">are</span> mourning  because no one comes to the festival.  All her gates <span class=\"supplied\">are</span> desolate,  her priests groan;  her young women <span class=\"supplied\">are</span> worried,  and she herself suffers bitterly.'),
('LEB', 'Lamentations', '1', '5', '1', 'Her foes have become <span class=\"supplied\">her</span> <span class=\"idiom\">master</span>,<span class=\"note\">Literally “head”</span> her enemies are at ease;  Adonai has made her suffer  because of the greatness of her transgressions.  Her children have gone away,  captive before the foe.'),
('LEB', 'Lamentations', '1', '6', '1', 'All her majesty has gone away  from the daughter of Zion;  her princes have become like young stags  that have not found pasture;  they have gone away without strength,  before the pursuer.'),
('LEB', 'Lamentations', '1', '7', '1', 'Jerusalem remembers  the days of her misery and wanderings,  all her treasures  that were from the days of long ago.  When her people fell into <span class=\"supplied\">the</span> hand of the enemy,  there was no one helping her;  the enemies saw her, they mocked  at her destruction.'),
('LEB', 'Lamentations', '1', '8', '1', 'Jerusalem sinned grievously,  thus she became an objection of derision;  all those who honored her despise her  because they have seen her nakedness.  She herself groans  and turns away.'),
('LEB', 'Lamentations', '1', '9', '1', 'Her uncleanness <span class=\"supplied\">was</span> in her skirts;  she did not remember her future,  she has descended beyond understanding,  there is no comforter for her.  See, O Adonai, my persecution!  <span class=\"supplied\">My</span> enemy has been made great!'),
('LEB', 'Lamentations', '1', '10', '1', 'The enemy has stretched out his hand  over all her treasures;  for she has seen the nations,  they entered her sanctuary,  those whom you commanded not to enter  in your assembly.'),
('LEB', 'Lamentations', '1', '11', '1', 'All her people groan,  they are searching for bread.  They give their treasures for food,  to bring back life.  See, O Adonai, and look,  <span class=\"supplied\">how</span> I am despised.'),
('LEB', 'Lamentations', '1', '12', '1', 'Is it nothing to you, <span class=\"idiom\">all who pass by</span>?<span class=\"note\">Literally “all who cross a road”</span> Look and see  if there is sorrow like my sorrow,<span class=\"note\">Or “pain like my pain”</span> which was dealt to me,  which Adonai inflicted  on the <span class=\"idiom\">day of his wrath</span>.<span class=\"note\">Literally “on the day of the blaze of his nose”</span>'),
('LEB', 'Lamentations', '1', '13', '1', 'From heaven he sent fire,  into my bones he let it descend.  He spread out a net for my feet;  he turned me back,  he gave me devastation,  fainting all day.'),
('LEB', 'Lamentations', '1', '14', '1', 'My rebellion was bound <span class=\"supplied\">as</span> a yoke,  with his hand it was fastened together;  it was put on my neck  <span class=\"supplied\">and</span> caused my strength to fail.  The Lord gave me into the hands  <span class=\"supplied\">of those whom</span> I cannot withstand.'),
('LEB', 'Lamentations', '1', '15', '1', 'The Lord has rejected  all my mighty ones in my midst.  He called an assembly against me,  to crush my young men;  <span class=\"supplied\">like in</span> a wine press,  the Lord has trodden <span class=\"supplied\">on</span>  the virgin daughter of Judah.'),
('LEB', 'Lamentations', '1', '16', '1', 'For these <span class=\"supplied\">things</span>, I am weeping,  <span class=\"idiom\">my eyes flow with tears</span>;<span class=\"note\">Literally “my eye my eye is going down <span class=\"supplied\">with</span> water”</span> because a comforter is far from me,  one to restore my life.  My sons are desolate  because <span class=\"supplied\">the</span> enemy has prevailed.'),
('LEB', 'Lamentations', '1', '17', '1', 'Zion stretches out her hands;  there is no one to comfort her.  Adonai has commanded against Jacob,  <span class=\"supplied\">that</span> those surrounding him<span class=\"note\">NRSV translates “his neighbors”</span><span class=\"supplied\">should be</span> his enemies;  Jerusalem has become  a defilement among them.'),
('LEB', 'Lamentations', '1', '18', '1', 'Adonai is righteous;  I have rebelled <span class=\"supplied\">against</span> <span class=\"idiom\">his word</span>.<span class=\"note\">Literally “his mouth”</span> Please hear, all <span class=\"supplied\">the</span> nations,  And see my pain;  My young women<span class=\"note\">Or “virgins”</span>and young men  went into captivity.'),
('LEB', 'Lamentations', '1', '19', '1', 'I have called to my lovers,  they themselves deceived me;  my priests and elders perished in the city  when they sought food for themselves  to revive their life.<span class=\"note\">Or “their soul”</span>'),
('LEB', 'Lamentations', '1', '20', '1', 'See, O Adonai, that <span class=\"idiom\">I am in distress</span>;<span class=\"note\">Literally “<span class=\"supplied\">there is</span> distress for me”</span> <span class=\"idiom\">my stomach</span><span class=\"note\">Literally “inner parts”</span>is in torment,  my heart has turned inside me  because I have certainly rebelled.  From outside a sword brings bereavement,  inside the house <span class=\"supplied\">it is</span> like death.'),
('LEB', 'Lamentations', '1', '21', '1', 'They hear that I was groaning;  <span class=\"supplied\">there is</span> no comforter for me.  All my enemies have heard my misery,  they are pleased that you have done it.  Bring <span class=\"supplied\">that</span> day that you have proclaimed,<span class=\"note\">Or “you have called”</span> And let them be like me.'),
('LEB', 'Lamentations', '1', '22', '1', 'Let all their evil come before you;  and deal with them  just as you have dealt with me  because of all my crimes;  for my groaning is much and my heart <span class=\"supplied\">is</span> faint.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Lamentations', '2', '1', '1', '<span class=\"verse-title\">The Lord is Angry</span>How, <span class=\"idiom\">in his anger</span>,<span class=\"note\">Literally “in his nose”</span> the Lord has covered the daughter of Zion in a cloud!  He has thrown down from heavens <span class=\"supplied\">to</span> earth  the splendor of Israel,  and he has not remembered his footstool  in the day of <span class=\"idiom\">his anger</span>.<span class=\"note\">Literally “his nose”</span>'),
('LEB', 'Lamentations', '2', '2', '1', 'The Lord has devoured; he has not shown mercy  to all the dwellings of Jacob;  he has broken down in his wrath  the fortifications of the daughter of Judah;  he has leveled to the ground, he has dishonored  the kingdom and its commanders.<span class=\"note\">Or “her commanders”</span>'),
('LEB', 'Lamentations', '2', '3', '1', 'He has cut down <span class=\"idiom\">in fierce anger</span><span class=\"note\">Literally “in a fierce nose”</span> all the might of Israel;  he has withdrawn his right hand  from the faces of <span class=\"supplied\">the</span> enemy,  and he has burned in Jacob like a flaming fire,  it has consumed all around.'),
('LEB', 'Lamentations', '2', '4', '1', 'He has bent his bow like an enemy;  he has set his right hand  like a foe, and he has slain  all <span class=\"supplied\">the</span> treasures of <span class=\"supplied\">the</span> eye;<span class=\"note\">NRSV translates “all in whom we took pride”</span> in the tent of the daughter of Zion,  he has poured out his anger like fire.'),
('LEB', 'Lamentations', '2', '5', '1', 'The Lord has become like an enemy;  he has destroyed Israel;  he has destroyed all its citadel fortresses;<span class=\"note\">Or “her citadel fortresses”</span> he has ruined all its fortifications  and multiplied lamentation and mourning  in the daughter of Judah.'),
('LEB', 'Lamentations', '2', '6', '1', 'He has broken down <span class=\"idiom\">his dwelling</span><span class=\"note\">Literally “his booth”; or “his tabernacle”</span>place like the garden;  he has ruined his appointed feasts;  Adonai has made <span class=\"supplied\">them</span> forget in Zion  <span class=\"idiom\">festival</span><span class=\"note\">Literally “appointed time”</span>and Sabbath,  and he has despised in his anger  king and priest.'),
('LEB', 'Lamentations', '2', '7', '1', 'The Lord has rejected his altar;  he has rejected his sanctuary;  he has delivered into the hands of the enemy  the walls of its citadel fortresses.<span class=\"note\">Or “her citadel fortress”</span> They have cried out in the house of Adonai  like a day of an appointed feast.'),
('LEB', 'Lamentations', '2', '8', '1', 'Adonai has planned to destroy  the wall of the daughter of Zion.  He measured <span class=\"supplied\">with</span> a line; he has not restrained  his hand from destroying;  he caused rampart and wall to mourn;  together they have languished away.'),
('LEB', 'Lamentations', '2', '9', '1', 'Her gates have sunk into the earth;  he has ruined and broken her bars,  her kings and its princes <span class=\"supplied\">are</span> among the nations;  there is no more law.<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span> Also, her prophets have not found  a revelation from Adonai.'),
('LEB', 'Lamentations', '2', '10', '1', 'They sit on the ground,  the elders of the daughter of Zion are silent.  They cast dust on their head,  they have put on sackcloth;  the young women of Jerusalem  have bowed their head down to the ground.'),
('LEB', 'Lamentations', '2', '11', '1', 'My eyes have <span class=\"idiom\">spent all their tears</span>;<span class=\"note\">Literally “finished with the weeping”</span> <span class=\"idiom\">my stomach</span><span class=\"note\">Literally “my inward parts”</span>is in torment,  <span class=\"idiom\">my heart</span><span class=\"note\">Literally “my liver”</span>is poured out on the earth  because of the destruction of the daughter of my people,  because child and babe faint  in <span class=\"supplied\">the</span> public squares of a city.'),
('LEB', 'Lamentations', '2', '12', '1', 'To their mothers they say,  “Where is the bread and wine?”  as they faint like the wounded  in <span class=\"supplied\">the</span> public squares of a city,  as their life is being poured out  onto the bosom of their mothers.'),
('LEB', 'Lamentations', '2', '13', '1', 'What can I say for you? What can I compare to you,  O daughter of Jerusalem?  To what can I liken you so that I can comfort you,  O virgin daughter of Zion?  For your destruction <span class=\"supplied\">is</span> as vast as the sea;  who can heal you?'),
('LEB', 'Lamentations', '2', '14', '1', 'Your prophets had a vision for you,  false and worthless;  they have not exposed your sin,  to restore your fortune;  they have seen oracles for you,  false and misleading.'),
('LEB', 'Lamentations', '2', '15', '1', 'They clap hands over you,  all who pass along the way;  they hiss and they shake their head,  at the daughter of Jerusalem.  Is this the city of which it is said,  “A perfection of beauty, a joy for all the earth?”'),
('LEB', 'Lamentations', '2', '16', '1', 'They have opened their mouths against you,  all your enemies.  They hiss and gnash a tooth,  and they say, “We have destroyed <span class=\"supplied\">her</span>!  Surely this <span class=\"supplied\">is</span> the day we have hoped for;  we have found <span class=\"supplied\">it</span>, we have seen <span class=\"supplied\">it</span>!”'),
('LEB', 'Lamentations', '2', '17', '1', 'Adonai has done what he has planned;  he has fulfilled his promise  that he ordained from the days of old;  he has demolished and not shown mercy;  he has made an enemy rejoice over you,  he has exalted the <span class=\"idiom\">might</span><span class=\"note\">Literally “horn”</span>of your foes.'),
('LEB', 'Lamentations', '2', '18', '1', 'Their heart cried to the Lord,  “O wall of the daughter of Zion,  let tears stream down like a river;  day and night,  do not give yourself relief,  do not give your eyes rest.'),
('LEB', 'Lamentations', '2', '19', '1', '“Arise, cry out in the night,  at the beginning of the night watches;  pour out your heart like water,  before the face of the Lord.  Lift to him your hands,  for the life of your children,  who faint in starvation,  at the head of all streets.”'),
('LEB', 'Lamentations', '2', '20', '1', 'See, Adonai, and take note!  With whom have you dealt thus?  Should women eat their young  children of tender care?  Should priest and prophet be slain  in the sanctuary of the Lord?'),
('LEB', 'Lamentations', '2', '21', '1', 'They lie in <span class=\"supplied\">the</span> soil of <span class=\"supplied\">the</span> streets,  young and old;  my young women<span class=\"note\">Or “my virgins”</span>and young men,  they have fallen by the sword;  you have slain on the day of <span class=\"idiom\">your anger</span>,<span class=\"note\">Literally “your nose”</span> you have slaughtered and not shown mercy.'),
('LEB', 'Lamentations', '2', '22', '1', 'You have summoned my horror from all around,  as if for a feast day;  no one on the day of Adonai’s anger  <span class=\"supplied\">is</span> a fugitive and a survivor;  whoever I have cared for and reared,  my enemy has destroyed.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Lamentations', '3', '1', '1', '<span class=\"verse-title\">Israel’s Affliction</span>I am a man who has seen misery,  under the rod of his wrath.'),
('LEB', 'Lamentations', '3', '2', '1', 'He has driven me along, he brought  darkness and not light.'),
('LEB', 'Lamentations', '3', '3', '1', 'Surely he has turned his hand against me,  all day long.'),
('LEB', 'Lamentations', '3', '4', '1', 'He has worn out my flesh and skin,  he has broken my bones.'),
('LEB', 'Lamentations', '3', '5', '1', '<span class=\"idiom\">He has besieged</span><span class=\"note\">Literally “he has built against”</span>and engulfed me  with bitterness and hardship.'),
('LEB', 'Lamentations', '3', '6', '1', 'In darkness he has let me dwell  like <span class=\"supplied\">the</span> dead of long ago.'),
('LEB', 'Lamentations', '3', '7', '1', 'He has built a wall around me, I cannot go out;  he has made my bronze fetters heavy.'),
('LEB', 'Lamentations', '3', '8', '1', 'Though I cry out for help,  he shuts out my prayers.'),
('LEB', 'Lamentations', '3', '9', '1', 'He has blocked my ways with dressed stones;  he has made my paths crooked.'),
('LEB', 'Lamentations', '3', '10', '1', 'To me he <span class=\"supplied\">is</span> like a bear lying in wait,  a lion in hiding.'),
('LEB', 'Lamentations', '3', '11', '1', 'He has forsaken my way and torn me to pieces;  he has caused me desolation.'),
('LEB', 'Lamentations', '3', '12', '1', 'He has bent his bow and set me  as the target for the arrow.'),
('LEB', 'Lamentations', '3', '13', '1', 'He shot <span class=\"idiom\">the arrows of his quiver</span><span class=\"note\">Literally “the offspring of his arrow quiver”</span> into my kidneys.'),
('LEB', 'Lamentations', '3', '14', '1', 'I have become a laughingstock for all the people,  their mocking song all day long.'),
('LEB', 'Lamentations', '3', '15', '1', 'He has filled me with bitterness,  he has drenched me <span class=\"supplied\">with</span> wormwood.'),
('LEB', 'Lamentations', '3', '16', '1', 'He has broken my teeth on grit,  he has trampled me down in ash.'),
('LEB', 'Lamentations', '3', '17', '1', 'My life has been removed from peace,  I have forgotten goodness.'),
('LEB', 'Lamentations', '3', '18', '1', 'And I have said, “My glory is ruined,  my expectation from Adonai.”'),
('LEB', 'Lamentations', '3', '19', '1', 'Remember my misery and bitterness,  the wormwood<span class=\"note\">Or “the bitter substance”</span>and venom!'),
('LEB', 'Lamentations', '3', '20', '1', 'Surely my soul remembers  and bows down within me.'),
('LEB', 'Lamentations', '3', '21', '1', 'This <span class=\"idiom\">I have reminded myself</span>,<span class=\"note\">Literally “I have brought back to my heart”</span> therefore I will hope.'),
('LEB', 'Lamentations', '3', '22', '1', 'The loyal love of Adonai does not cease;  his compassions do not come to an end.'),
('LEB', 'Lamentations', '3', '23', '1', '<span class=\"supplied\">They</span> are new in the morning,  great is your faithfulness.'),
('LEB', 'Lamentations', '3', '24', '1', '“Adonai is my portion,”  says my soul,  “Thus I will hope on him.”'),
('LEB', 'Lamentations', '3', '25', '1', 'Adonai is good to those who wait on him,  to the person that seeks him.'),
('LEB', 'Lamentations', '3', '26', '1', '<span class=\"supplied\">It is</span> good to wait in silence  for the salvation of Adonai.'),
('LEB', 'Lamentations', '3', '27', '1', '<span class=\"supplied\">It is</span> good for a man who carries  the yoke of his childhood.'),
('LEB', 'Lamentations', '3', '28', '1', 'Let him sit alone and be silent  when he<span class=\"note\">Adonai</span>has laid it on him.'),
('LEB', 'Lamentations', '3', '29', '1', 'Let <span class=\"idiom\">him put</span><span class=\"note\">Literally “him give”</span>his mouth in the dust;  perhaps there is hope.'),
('LEB', 'Lamentations', '3', '30', '1', 'Let him give a cheek to his smiter,  let him be filled with disgrace.'),
('LEB', 'Lamentations', '3', '31', '1', 'For the Lord will not reject  forever.'),
('LEB', 'Lamentations', '3', '32', '1', 'For even though he causes grief he has compassion  according to the greatness of his royal love.'),
('LEB', 'Lamentations', '3', '33', '1', 'He does not <span class=\"idiom\">afflict willingly</span>,<span class=\"note\">Literally “afflict from the heart”</span> or grieve <span class=\"idiom\">anyone</span>.<span class=\"note\">Literally “the sons of men”</span>'),
('LEB', 'Lamentations', '3', '34', '1', 'To crush under his feet  all <span class=\"supplied\">the</span> prisoners of <span class=\"supplied\">the</span> earth;'),
('LEB', 'Lamentations', '3', '35', '1', '<span class=\"idiom\">to deprive one of justice</span><span class=\"note\">Literally “to turn aside the judgment of a man”</span> before the face of the Most High;'),
('LEB', 'Lamentations', '3', '36', '1', 'to subvert a person in a legal dispute  —the Lord has not found delight <span class=\"supplied\">in these things</span>.'),
('LEB', 'Lamentations', '3', '37', '1', '<span class=\"idiom\">Who can speak</span><span class=\"note\">Literally “Who is this that speaks”</span>and it will happen  <span class=\"supplied\">if</span> the Lord has not commanded <span class=\"supplied\">it</span>?'),
('LEB', 'Lamentations', '3', '38', '1', '<span class=\"supplied\">Is</span> it not from the mouth of the Most High  <span class=\"supplied\">that</span> disaster and good will come?'),
('LEB', 'Lamentations', '3', '39', '1', 'Why should any living person complain  about his sin?'),
('LEB', 'Lamentations', '3', '40', '1', 'Let us test and examine our ways;  let us return to Adonai.'),
('LEB', 'Lamentations', '3', '41', '1', 'Let us lift up our hearts with our hands  to God in the heavens.'),
('LEB', 'Lamentations', '3', '42', '1', 'We ourselves have transgressed and rebelled,  you have not forgiven.'),
('LEB', 'Lamentations', '3', '43', '1', 'You have covered <span class=\"supplied\">yourself</span> <span class=\"idiom\">in anger</span><span class=\"note\">Literally “in the nose”</span>and pursued us,  you have slain and not shown mercy.'),
('LEB', 'Lamentations', '3', '44', '1', 'You have covered yourself in a cloud  <span class=\"idiom\">so that prayer cannot pass through</span>.<span class=\"note\">Literally “from a passing prayer”</span>'),
('LEB', 'Lamentations', '3', '45', '1', 'You have made us scum and refuse  in the midst of the nations.'),
('LEB', 'Lamentations', '3', '46', '1', 'All our enemies  have opened their mouth against us.'),
('LEB', 'Lamentations', '3', '47', '1', 'Fear and a pit have come upon us,  desolation and destruction.'),
('LEB', 'Lamentations', '3', '48', '1', 'Channels of water run down my eyes  because of the destruction of the daughter of my people.'),
('LEB', 'Lamentations', '3', '49', '1', 'My eyes have poured down unceasingly  without respite,'),
('LEB', 'Lamentations', '3', '50', '1', 'until Adonai looks down  and sees from heaven.'),
('LEB', 'Lamentations', '3', '51', '1', 'My eyes inflict my soul  because of all the daughters of my city.'),
('LEB', 'Lamentations', '3', '52', '1', 'My enemies hunt me without cause,  like a bird.'),
('LEB', 'Lamentations', '3', '53', '1', '<span class=\"idiom\">They have silenced me in a pit</span>,<span class=\"note\">Literally “they have put to silence my life in a pit”</span> they have thrown a stone at me.'),
('LEB', 'Lamentations', '3', '54', '1', 'Water has flown over my head,  I said, “I am cut off.”'),
('LEB', 'Lamentations', '3', '55', '1', 'I have called your name, O Adonai,  from the depths of the pit.'),
('LEB', 'Lamentations', '3', '56', '1', 'You have heard my cry, “Do not shut your ear  to my cry for help, for my relief!”'),
('LEB', 'Lamentations', '3', '57', '1', 'You came near on a day <span class=\"supplied\">when</span> I called you,  you said, “Do not fear!”'),
('LEB', 'Lamentations', '3', '58', '1', 'O Lord, you have pleaded for <span class=\"idiom\">my cause</span>,<span class=\"note\">Literally “the legal disputes of my soul”</span> you have redeemed my life.'),
('LEB', 'Lamentations', '3', '59', '1', 'You have seen my injustice, O Adonai;  judge my case.'),
('LEB', 'Lamentations', '3', '60', '1', 'You have seen all their vengeance,  all there plans against me.'),
('LEB', 'Lamentations', '3', '61', '1', 'You have heard their disgrace, O Adonai,  all their plans against me.'),
('LEB', 'Lamentations', '3', '62', '1', 'The lips and meditation of my assailants  <span class=\"supplied\">are</span> against me all day long.'),
('LEB', 'Lamentations', '3', '63', '1', 'Look at their sitting and their standing,  I <span class=\"supplied\">am</span> their mocking song.'),
('LEB', 'Lamentations', '3', '64', '1', 'Return to them what is deserved, O Adonai,  according to the work of their hands.'),
('LEB', 'Lamentations', '3', '65', '1', 'Give them a stubborn heart;  curse them!'),
('LEB', 'Lamentations', '3', '66', '1', 'Pursue them <span class=\"idiom\">in anger</span><span class=\"note\">Literally “in nose”</span>and destroy them  from under the heavens of Adonai.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Lamentations', '4', '1', '1', '<span class=\"verse-title\">Zion Is Punished</span>How <span class=\"supplied\">the</span> gold has grown dim,  the pure gold has changed.  The stones of holiness are scattered  at the head of every street.'),
('LEB', 'Lamentations', '4', '2', '1', 'The precious sons of Zion  weighed against fine gold,  how they are thought of as earthen vessels of clay,  the work of the potter’s hands.'),
('LEB', 'Lamentations', '4', '3', '1', 'Even the jackal bears the beast  and nurses their cubs;  <span class=\"supplied\">but</span> the daughter of my people has become ruthless,  like ostriches in the wilderness.'),
('LEB', 'Lamentations', '4', '4', '1', 'The tongue of the nursling cleaves  to its palate in thirst.  Children beg <span class=\"supplied\">for</span> food,  <span class=\"idiom\">no one lays it out before them</span>.<span class=\"note\">Literally “nothing spreads to them”</span>'),
('LEB', 'Lamentations', '4', '5', '1', 'The ones who eat delicacies,  they are ruined in the streets;  the ones nurtured in purple  lie <span class=\"supplied\">on</span> piles of trash.'),
('LEB', 'Lamentations', '4', '6', '1', 'The iniquity of the daughter of my people is greater  than the sin of Sodom;  it was overthrown in a moment  and no hands were laid on her.'),
('LEB', 'Lamentations', '4', '7', '1', 'Her princes were purer than snow,  they were whiter than milk;  <span class=\"supplied\">their</span> bodies were more ruddy than rubies,  sapphire their appearance.'),
('LEB', 'Lamentations', '4', '8', '1', '<span class=\"supplied\">Now</span> their appearance is blacker than soot,  they are not recognized in the streets;  their skin has shriveled on their bones,  it has become dry like wood.'),
('LEB', 'Lamentations', '4', '9', '1', 'Happier were <span class=\"supplied\">the</span> victims of <span class=\"supplied\">the</span> sword  than the victims of famine;  they have pined away, very hungry  for the crops of my field.'),
('LEB', 'Lamentations', '4', '10', '1', '<span class=\"supplied\">The</span> hands of compassionate women,  have cooked their children;  they became as something to eat  in the destruction of the daughter of my people.'),
('LEB', 'Lamentations', '4', '11', '1', 'Adonai has completed his anger,  he has poured out <span class=\"idiom\">his fierce anger</span>;<span class=\"note\">Literally “the fierce anger of his nose”</span> he has kindled a fire in Zion,  it consumed her<span class=\"note\">Or “its”</span>foundations.'),
('LEB', 'Lamentations', '4', '12', '1', '<span class=\"supplied\">The</span> kings of <span class=\"supplied\">the</span> earth did not believe,  and all <span class=\"supplied\">the</span> inhabitants of <span class=\"supplied\">the</span> world,  that a foe and an enemy could enter  into the gates of Jerusalem.'),
('LEB', 'Lamentations', '4', '13', '1', 'Because of the sins of her prophets,  the guilt of her priests,  who shed blood in her midst,  of righteous people.'),
('LEB', 'Lamentations', '4', '14', '1', 'They wander blindly in the streets;  they were defiled with the blood,  their clothes  could not be touched.'),
('LEB', 'Lamentations', '4', '15', '1', '“Go away! Defiled!” they shout to them.  “Go away! Go away! Do not touch!”  so they left, they left; it was said among the nations,  “<span class=\"idiom\">They will no longer dwell with us</span>.”<span class=\"note\">Literally “They will no longer be <span class=\"supplied\">here</span> as aliens”</span>'),
('LEB', 'Lamentations', '4', '16', '1', 'The presence of Adonai has scattered them,  he will no longer watch over them;  <span class=\"idiom\">they did not honor the priests</span>,<span class=\"note\">Literally “they did not lift up the faces of the priests”</span> they did not show mercy <span class=\"supplied\">to</span> elders.'),
('LEB', 'Lamentations', '4', '17', '1', 'Still our eyes failed,  <span class=\"supplied\">looking for</span> our help in vain;  in our watchtower, we kept watch  for a nation that could not save.'),
('LEB', 'Lamentations', '4', '18', '1', 'They hunted our steps,  from walking in our streets;  our end has come near, <span class=\"idiom\">our days are finished</span>,<span class=\"note\">Literally “our days are filled”</span> our end has come.'),
('LEB', 'Lamentations', '4', '19', '1', 'Our pursuers were swifter  than <span class=\"supplied\">the</span> eagles of <span class=\"supplied\">the</span> heavens;  they chased us on the mountains,  they have set an ambush for us in the desert.'),
('LEB', 'Lamentations', '4', '20', '1', 'The breath of our nostrils, the anointed one of Adonai,  was captured in their pits;  of whom we said, “In his shadow  we will live among the nations.”'),
('LEB', 'Lamentations', '4', '21', '1', 'Rejoice and be glad, O daughter of Edom,  you who dwell in the land of Uz;  but to you also the cup will pass,  you will become drunk and strip yourself bare.'),
('LEB', 'Lamentations', '4', '22', '1', 'The <span class=\"supplied\">punishment</span> of your iniquity is completed, O daughter of Zion,  your exile will not continue;  <span class=\"supplied\">but</span> he will punish your iniquity, O daughter of Edom,  he will reveal your sins.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Lamentations', '5', '1', '1', '<span class=\"verse-title\">A Request for Mercy</span>Remember, O Adonai, what has become of us;  take note, and see our disgrace!'),
('LEB', 'Lamentations', '5', '2', '1', 'Our inheritance has been turned over to strangers,  our houses, to foreigners.'),
('LEB', 'Lamentations', '5', '3', '1', 'We have become orphans, fatherless,  our mothers are like widows.'),
('LEB', 'Lamentations', '5', '4', '1', '<span class=\"idiom\">We pay for water with money</span>,<span class=\"note\">Literally “we drink our water by money”</span> our wood comes <span class=\"supplied\">to us</span> at a price.'),
('LEB', 'Lamentations', '5', '5', '1', 'We are driven on our necks;  we are weary, there is no rest for us.'),
('LEB', 'Lamentations', '5', '6', '1', 'We have made a deal with Egypt <span class=\"supplied\">and</span> Assyria  to be satisfied <span class=\"supplied\">with</span> food.'),
('LEB', 'Lamentations', '5', '7', '1', 'Our fathers have sinned, they are no more;  we bear their iniquity.'),
('LEB', 'Lamentations', '5', '8', '1', 'Slaves rule over us;  there is no one to deliver us from their hand.'),
('LEB', 'Lamentations', '5', '9', '1', '<span class=\"idiom\">We risk our life for food</span><span class=\"note\">Literally “We take our food at our life”</span> because of the sword of the desert.'),
('LEB', 'Lamentations', '5', '10', '1', 'Our skin is hot like an oven  because of the scorching famine.'),
('LEB', 'Lamentations', '5', '11', '1', 'They raped women in Zion,  young women<span class=\"note\">Or “virgins”</span>in the cities of Judah.'),
('LEB', 'Lamentations', '5', '12', '1', 'They hang princes by their hand;  they do not show respect before elders.'),
('LEB', 'Lamentations', '5', '13', '1', 'Young men must carry a hand-mill  and boys stumble under the wood.'),
('LEB', 'Lamentations', '5', '14', '1', 'Elders are no longer at the gate,  young men no longer play stringed instruments.'),
('LEB', 'Lamentations', '5', '15', '1', 'The joy of our hearts has stopped;  our circle-dancing has changed to a mourning ceremony.'),
('LEB', 'Lamentations', '5', '16', '1', 'The crown has fallen from our head;  woe to us, for we have sinned!'),
('LEB', 'Lamentations', '5', '17', '1', 'Because of this, our heart has become faint,  because of these, our eyes have become dim.'),
('LEB', 'Lamentations', '5', '18', '1', 'Because of Mount Zion, which lies desolate,  <span class=\"idiom\">foxes tread on it</span>.<span class=\"note\">Literally “foxes go on it”</span>'),
('LEB', 'Lamentations', '5', '19', '1', 'You, O Adonai, will sit forever  <span class=\"supplied\">on</span> your throne for generation to generation.'),
('LEB', 'Lamentations', '5', '20', '1', 'Why have you forgotten us forever?  Why have you forsaken us <span class=\"idiom\">for so long</span>?<span class=\"note\">Literally “for long days”</span>'),
('LEB', 'Lamentations', '5', '21', '1', 'Restore us to you, O Adonai, that we will be restored;  renew our days as of old.'),
('LEB', 'Lamentations', '5', '22', '1', 'Unless you have utterly rejected us,  unless you are angry with us beyond measure.')
;

