INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Malachi', '1', '1', '0', '<span class=\"idiom\">An oracle</span>.<span class=\"note\">Literally “A burden”</span>The word of Adonai to Israel <span class=\"idiom\">through</span><span class=\"note\">Literally “by the hand of”</span>Malachi.<span class=\"note\">The name “Malachi” means “my messenger” in Hebrew</span>'),
('LEB', 'Malachi', '1', '2', '2', '<span class=\"verse-title\">An Oracle Against Edom</span>“I have loved you,” says Adonai, but you say, “How have you loved us?” “<span class=\"supplied\">Is</span> Esau not Jacob’s brother?” <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai. “I have loved Jacob,'),
('LEB', 'Malachi', '1', '3', '2', 'but Esau I have hated. I have made his<span class=\"note\">That is, “Esau’s”</span>mountain ranges a desolation, and <span class=\"supplied\">given</span> his inheritance to the jackals of <span class=\"supplied\">the</span> desert.”'),
('LEB', 'Malachi', '1', '4', '2', 'If Edom says, “We are shattered, but we will return and rebuild <span class=\"supplied\">the</span> ruins,” Adonai of hosts says this: “They may build, but I will tear down; and they will be called a territory of wickedness, and the people <span class=\"supplied\">with</span> whom Adonai is angry forever.”'),
('LEB', 'Malachi', '1', '5', '2', 'Your eyes will see <span class=\"supplied\">this</span>, and you will say, “Adonai is great beyond the borders<span class=\"note\">Hebrew “boundary”</span>of Israel.”'),
('LEB', 'Malachi', '1', '6', '4', '<span class=\"verse-title\">An Oracle Against the Temple Priesthood</span>“A son honors <span class=\"supplied\">his</span> father, and a slave his master;<span class=\"note\">Hebrew “masters”</span>but if I <span class=\"supplied\">am</span> a father, where <span class=\"supplied\">is</span> my honor, and if I <span class=\"supplied\">am</span> a master,<span class=\"note\">Hebrew “masters”</span>where <span class=\"supplied\">is</span> my reverence?” says Adonai of hosts to you, O priests, <span class=\"idiom\">who despise</span><span class=\"note\">Literally “despisers of”</span>my name. “But you say, ‘How have we despised your name?’'),
('LEB', 'Malachi', '1', '7', '4', '<span class=\"supplied\">You are</span> presenting defiled food on my altar! But you ask, ‘How have we defiled you?’ By saying <span class=\"supplied\">that</span> the table of Adonai is despised!'),
('LEB', 'Malachi', '1', '8', '4', 'When you offer a blind <span class=\"supplied\">animal</span> for sacrifice, is that not wrong?<span class=\"note\">Or “is there no wrong?”</span>And when you offer <span class=\"supplied\">the</span> lame and the one who is ill, is that not wrong?<span class=\"note\">Or “is there no wrong?”</span>Present it, please, to your governor! Will he be pleased with you? <span class=\"idiom\">Will he show you favor</span>?”<span class=\"note\">Literally “Will he lift your face?”</span>says Adonai of hosts.'),
('LEB', 'Malachi', '1', '9', '4', 'So then, <span class=\"idiom\">implore the favor of God</span><span class=\"note\">Literally “appease, please, the face of God”</span>so that he will be gracious to us. “<span class=\"idiom\">This is what you have done</span>.<span class=\"note\">Literally “From your hand was this”</span><span class=\"idiom\">Will he show favor to any of you</span>?”<span class=\"note\">Literally “will he lift up from you a face”</span>says Adonai of hosts.'),
('LEB', 'Malachi', '1', '10', '4', '“Who also among you will shut <span class=\"supplied\">the temple</span> doors <span class=\"supplied\">so that</span> you will not kindle fire in vain <span class=\"supplied\">on</span> my altar? I take no pleasure in you,” says Adonai of hosts, “and <span class=\"idiom\">I will not accept</span><span class=\"note\">Literally “I will not take pleasure in”</span>an offering from your hand.'),
('LEB', 'Malachi', '1', '11', '4', 'From the rising of the sun to its setting, my name <span class=\"supplied\">is</span> great among the nations, and in every place incense <span class=\"supplied\">is</span> being presented to my name, and a pure offering. For my name <span class=\"supplied\">is</span> great among the nations,” says Adonai of hosts.'),
('LEB', 'Malachi', '1', '12', '4', '“But you <span class=\"supplied\">are</span> profaning it by saying the table of the Lord <span class=\"supplied\">is</span> defiled, and its fruit—its food<span class=\"note\">The Hebrew here is difficult; “its food” may function to explain “its fruit”</span>—is despised!'),
('LEB', 'Malachi', '1', '13', '4', 'And you say, ‘Look! <span class=\"supplied\">This is</span> a weariness,’ and you sniff <span class=\"supplied\">with disdain</span> at it,” says Adonai of hosts. “And you bring <span class=\"supplied\">the</span> stolen, the lame, and the one that is sick—<span class=\"supplied\">this</span> you bring as the offering! Should I <span class=\"idiom\">accept it</span><span class=\"note\">Literally “take pleasure in it”</span>from your hand?” says Adonai.'),
('LEB', 'Malachi', '1', '14', '4', '“Cursed is the one who cheats, who has in his flock a male and vows <span class=\"supplied\">it</span>, but <span class=\"supplied\">instead</span> sacrifices a blemished one to the Lord! For I <span class=\"supplied\">am</span> a great king,” says Adonai of hosts, “and my name <span class=\"supplied\">is</span> awesome among the nations.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Malachi', '2', '1', '0', '“And so then, O priests, this command <span class=\"supplied\">is</span> for you:'),
('LEB', 'Malachi', '2', '2', '0', 'If you will not listen, and if you will not <span class=\"idiom\">take it to heart</span><span class=\"note\">Literally, “place <span class=\"supplied\">it</span> on <span class=\"supplied\">your</span> heart”</span>to give glory to my name,” says Adonai of hosts, “then I will send the curse on you, and I will curse your blessings; moreover I have <span class=\"supplied\">already</span> cursed them because <span class=\"idiom\">you are not taking it to heart</span>.<span class=\"note\">Literally “you <span class=\"supplied\">are</span> not placing <span class=\"supplied\">it</span> on <span class=\"supplied\">your</span> heart”</span>'),
('LEB', 'Malachi', '2', '3', '0', 'Look! I <span class=\"supplied\">am</span> going to rebuke <span class=\"idiom\">your offspring</span>,<span class=\"note\">Literally “for you the offspring”</span>and I will scatter offal on your faces, <span class=\"supplied\">the</span> offal of your religious feasts, and you will be carried to it.<span class=\"note\">The Hebrew is difficult. The subject is indefinite, and “it” likely refers to a refuse or waste pile</span>'),
('LEB', 'Malachi', '2', '4', '1', '“Then you will know that I have sent to you this command, that my covenant with Levi <span class=\"idiom\">continues</span>,”<span class=\"note\">Literally “be”</span>says Adonai of hosts.'),
('LEB', 'Malachi', '2', '5', '1', '“My covenant with him was <span class=\"supplied\">one of</span> life and peace, and I gave them to him. <span class=\"supplied\">This required</span> reverence, and he revered<span class=\"note\">Or “feared”</span>me and stood in awe <span class=\"idiom\">before</span><span class=\"note\">Literally “from the face of”</span>my name.'),
('LEB', 'Malachi', '2', '6', '1', '<span class=\"supplied\">The</span> instruction of truth<span class=\"note\">Or “law of truth”</span>was in his mouth, and wickedness was not found on his lips. In peace and in uprightness<span class=\"note\">Or “rectitude,” or “fairness”</span>he walked with me, and he brought back many from sin.<span class=\"note\">Or “iniquity”</span>'),
('LEB', 'Malachi', '2', '7', '1', 'For the lips of <span class=\"supplied\">the</span> priest should guard knowledge, and they should seek instruction<span class=\"note\">Or “law”</span>from his mouth, for he <span class=\"supplied\">is</span> the messenger of Adonai of hosts.'),
('LEB', 'Malachi', '2', '8', '1', 'But you, you have turned from the way; you have caused many to stumble by <span class=\"supplied\">your</span> instruction;<span class=\"note\">Or “<span class=\"supplied\">the</span> law”</span>you have ruined the covenant of Levi,” says Adonai of hosts.'),
('LEB', 'Malachi', '2', '9', '1', '“And in turn I have made you despised and humbled before all the people, inasmuch as you <span class=\"supplied\">are</span> not keeping<span class=\"note\">Or “observing”</span>my way, but are <span class=\"idiom\">favoring your own instruction</span>.”<span class=\"note\">Literally “lifting faces in the instruction/law”</span>'),
('LEB', 'Malachi', '2', '10', '3', '<span class=\"verse-title\">Adonai Hates Faithlessness</span><span class=\"idiom\">Do we not all have</span><span class=\"note\">Literally “<span class=\"supplied\">Is</span> for all of us not”</span>one father? Has not one God created us? Why <span class=\"supplied\">then</span> are we unfaithful <span class=\"idiom\">to one another</span>,<span class=\"note\">Literally “each man to his brother”</span>profaning the covenant of our ancestors?<span class=\"note\">Or “fathers”</span>'),
('LEB', 'Malachi', '2', '11', '3', 'Judah has been faithless, and a detestable thing has been done in Israel and in Jerusalem. Judah has profaned the sanctuary of Adonai which he loves, and has married the daughter of a foreign<span class=\"note\">Or “pagan”</span>god.'),
('LEB', 'Malachi', '2', '12', '3', 'May Adonai cut off from the tents of Jacob the man who does this, <span class=\"supplied\">the</span> one who is awake and <span class=\"supplied\">who</span> answers, and <span class=\"supplied\">the one who</span> brings an offering to Adonai of hosts!'),
('LEB', 'Malachi', '2', '13', '4', 'And this you do <span class=\"idiom\">as well</span>:<span class=\"note\">Literally “a second time”</span><span class=\"supplied\">you</span> cover the altar of Adonai <span class=\"supplied\">with</span> tears, <span class=\"supplied\">with</span> weeping and <span class=\"supplied\">with</span> groaning, because he<span class=\"note\">Adonai</span><span class=\"idiom\">no longer regards the offering</span><span class=\"note\">Literally “there is no longer turning to the offering”</span>or accepts <span class=\"supplied\">it</span> <span class=\"supplied\">with</span> favor from your hand.'),
('LEB', 'Malachi', '2', '14', '4', 'But you ask, “<span class=\"idiom\">For what reason</span>?”<span class=\"note\">Literally “Because of what?”</span>Because Adonai stands as a witness between you and the wife of your youth, against whom you have been unfaithful, even though she <span class=\"supplied\">is</span> your marriage partner and <span class=\"idiom\">your wife by covenant</span>.<span class=\"note\">Literally “the wife of your covenant”</span>'),
('LEB', 'Malachi', '2', '15', '4', '<span class=\"idiom\">Did not one God make them?</span><span class=\"note\">Literally “Not one did he make”</span>But a remnant of <span class=\"supplied\">the</span> spirit is his.<span class=\"note\">The meaning of this sentence is difficult; literally “And a remnant of the spirit to him”</span>And what does the one <span class=\"supplied\">God</span> desire? An offspring of God.<span class=\"note\">Or “a godly offspring”</span><span class=\"idiom\">You must be attentive to</span><span class=\"note\">Literally “You must keep watch on”</span>your spirit, and you must not be unfaithful to the wife of your youth.'),
('LEB', 'Malachi', '2', '16', '4', '“For <span class=\"supplied\">I</span> hate divorce,”<span class=\"note\">Hebrew “sending away”</span>says Adonai, the God of Israel, “and he <span class=\"supplied\">who</span> covers his clothing <span class=\"supplied\">with</span> violence,” says Adonai of hosts. “<span class=\"idiom\">You must be attentive to</span><span class=\"note\">Literally “You must keep watch on”</span>your spirit and you must not be unfaithful.”'),
('LEB', 'Malachi', '2', '17', '5', 'You have wearied Adonai with your words, but you ask, “With what have we wearied <span class=\"supplied\">him</span>?” <span class=\"supplied\">You have done so</span> <span class=\"idiom\">when you say</span>,<span class=\"note\">Literally “at your saying”</span>“Everyone who does evil <span class=\"supplied\">is</span> good in the <span class=\"idiom\">sight</span><span class=\"note\">Literally “eyes”</span>of Adonai, and in them he delights,” or “Where <span class=\"supplied\">is</span> the God of justice?”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Malachi', '3', '1', '1', '<span class=\"verse-title\">Adonai’s Messenger is Coming</span>“Look! I <span class=\"supplied\">am</span> going to send my messenger,<span class=\"note\">Or “my angel”</span>and he will prepare<span class=\"note\">Or “clear”</span><span class=\"supplied\">the</span> way <span class=\"idiom\">before me</span>.<span class=\"note\">Literally “before my face”</span>And the Lord whom you <span class=\"supplied\">are</span> seeking will come suddenly to his temple, and the messenger of the covenant, <span class=\"supplied\">in</span> whom you <span class=\"supplied\">are</span> taking pleasure—look!—<span class=\"supplied\">he is</span> about to come,” says Adonai of hosts.'),
('LEB', 'Malachi', '3', '2', '1', 'And who <span class=\"supplied\">can</span> endure the day of his coming? And who <span class=\"supplied\">is</span> the one who can stand <span class=\"idiom\">when he appears</span>?<span class=\"note\">Literally “at his appearing”</span>For he <span class=\"supplied\">is</span> like a refiner’s fire, like launderers’ alkali.<span class=\"note\">Or “lye,” or “soap”</span>'),
('LEB', 'Malachi', '3', '3', '1', 'He will sit <span class=\"supplied\">as</span> a refiner and purifier of silver; he will purify the children of Levi, and he will refine them like gold and like silver, and they will present to Adonai offerings<span class=\"note\">Hebrew “offering”</span>in righteousness.'),
('LEB', 'Malachi', '3', '4', '1', 'And the offering of Judah and Jerusalem will be pleasing to Adonai, like <span class=\"supplied\">in the</span> days of old and like <span class=\"supplied\">in</span> former years.'),
('LEB', 'Malachi', '3', '5', '2', '“Then I will approach you for judgment, and I will be a swift witness against the sorcerers and against the adulterers, and against those who swear <span class=\"idiom\">falsely</span>,<span class=\"note\">Literally “as far as the falseness”</span>and against the oppressors of <span class=\"supplied\">the</span> hired worker <span class=\"supplied\">with his</span> wages, <span class=\"supplied\">the</span> widow and <span class=\"supplied\">the</span> orphan, and <span class=\"idiom\">the abusers of</span><span class=\"note\">Literally “<span class=\"supplied\">those</span> pushing aside”</span><span class=\"supplied\">the</span> alien,<span class=\"note\">Or “sojourner”</span>and <span class=\"supplied\">yet</span> do not fear me,” says Adonai of hosts.'),
('LEB', 'Malachi', '3', '6', '4', '<span class=\"verse-title\">An Overflowing Blessing</span>“For I, Adonai, have not changed,<span class=\"note\">Or “I do not change”</span>and you, O children of Jacob, have not perished.<span class=\"note\">Or “are not destroyed”</span>'),
('LEB', 'Malachi', '3', '7', '4', 'From the days of your ancestors<span class=\"note\">Or “fathers”</span>you have turned aside from my rules, and have not kept<span class=\"note\">Or “observed”</span><span class=\"supplied\">them</span>! Return to me and I will return to you,” says Adonai of hosts, “but you say, ‘How shall we return?’'),
('LEB', 'Malachi', '3', '8', '5', 'Will a human <span class=\"supplied\">dare to</span> rob God? Yet you <span class=\"supplied\">are</span> robbing me! And you say, ‘How have we robbed you?’ In the tithes and the contributions!'),
('LEB', 'Malachi', '3', '9', '5', 'You <span class=\"supplied\">are</span> being cursed with <span class=\"supplied\">a</span> curse, for you <span class=\"supplied\">are</span> robbing me, the whole nation <span class=\"supplied\">of you</span>!'),
('LEB', 'Malachi', '3', '10', '5', 'Bring the whole tithe to <span class=\"idiom\">the storehouse</span>,<span class=\"note\">Hebrew “the house of the treasure”</span>so that there will be food in my house, and test me please in this,” says Adonai of hosts, “if I will not open for you the windows of heaven, and pour forth for you <span class=\"idiom\">an overflowing blessing</span>.<span class=\"note\">Literally, “a blessing up to not enough”</span>'),
('LEB', 'Malachi', '3', '11', '5', 'I will rebuke the devourer<span class=\"note\">NRSV, JPS interpret this word as “locust”</span>for you; it will not destroy the fruit of your soil; your vine in the field will not be unfruitful,” says Adonai of hosts.'),
('LEB', 'Malachi', '3', '12', '5', '“And all the nations will call you blessed, because you will be <span class=\"idiom\">a land in which one takes joy</span>,”<span class=\"note\">Literally “a land of desire”</span>says Adonai of hosts.'),
('LEB', 'Malachi', '3', '13', '5', '“Your words have been harsh<span class=\"note\">Hebrew “strong”</span>against me,” says Adonai. “But you say, ‘How have we spoken together against you?’'),
('LEB', 'Malachi', '3', '14', '5', 'You have said, ‘<span class=\"supplied\">It is</span> useless<span class=\"note\">Or “vain”</span>to serve God! What <span class=\"supplied\">is the</span> gain if we keep<span class=\"note\">Or “observe”</span>his requirements, and if we walk as mourners <span class=\"idiom\">before</span><span class=\"note\">Literally “from the face of”</span>Adonai of hosts?'),
('LEB', 'Malachi', '3', '15', '5', 'And now we <span class=\"supplied\">are</span> calling <span class=\"supplied\">the</span> arrogant blessed! Not only do those who do wickedness prosper; they also test God and they escape!’ ”'),
('LEB', 'Malachi', '3', '16', '7', '<span class=\"verse-title\">A Book of Remembrance is Written</span>Then those who revered<span class=\"note\">Or “fear”</span>Adonai spoke <span class=\"idiom\">with one another</span>.<span class=\"note\">Literally “each with his friend/companion”</span>And Adonai listened attentively<span class=\"note\">Or “gave heed”</span>and heard, and a scroll of remembrance was written <span class=\"idiom\">before him</span><span class=\"note\">Literally “to the face of him”</span>of those who revere<span class=\"note\">Or “fear”</span>Adonai and ponder his name.'),
('LEB', 'Malachi', '3', '17', '7', '“They will be mine,” says Adonai of hosts, “on the day that I <span class=\"supplied\">am</span> acting, <span class=\"supplied\">my</span> treasured possession. I will have compassion on them as a man has compassion on his son who serves him.'),
('LEB', 'Malachi', '3', '18', '7', 'You will return and see <span class=\"supplied\">the difference</span> between <span class=\"supplied\">the</span> righteous and <span class=\"supplied\">the</span> wicked, between <span class=\"supplied\">the one who</span> serves God and the one who does not serve him.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Malachi', '4', '1', '0', '<span class=\"note\">Malachi 4:1–6 in the English Bible is 3:19–24 in the Hebrew Bible</span>“For look! The day <span class=\"supplied\">is</span> about to come, burning like an oven, and all the arrogant and every <span class=\"idiom\">evildoer</span><span class=\"note\">Literally “doer of wickedness”</span>will be stubble. The coming day will consume<span class=\"note\">Or “devour”</span>them,” says Adonai of hosts. “It will not leave behind for them root or branch.'),
('LEB', 'Malachi', '4', '2', '0', 'But for you who revere<span class=\"note\">Or “fear”</span>my name, the sun of righteousness will rise, with healing in its wings, and you will go out and leap like <span class=\"idiom\">fattened calves</span>.<span class=\"note\">Literally “bull-calves of <span class=\"supplied\">the</span> animal stall” (on the idiom see HALOT 631 s.v.)</span>'),
('LEB', 'Malachi', '4', '3', '0', 'You will trample down the wicked, for they will be ashes under the soles of your feet on the day that I <span class=\"supplied\">am</span> going to act,” says Adonai of hosts.'),
('LEB', 'Malachi', '4', '4', '1', '“Remember the instruction<span class=\"note\">Or “law”; Hebrew <span class=\"italic\">torah</span></span>of my servant Moses, which I commanded him at Horeb to all Israel, the rules and regulations.'),
('LEB', 'Malachi', '4', '5', '1', 'Look! I <span class=\"supplied\">am</span> going to send to you Elijah the prophet before the coming of the great and awesome day of Adonai!'),
('LEB', 'Malachi', '4', '6', '1', 'And he will bring back<span class=\"note\">Or “And he will restore”</span><span class=\"supplied\">the</span> hearts of <span class=\"supplied\">the</span> fathers to <span class=\"supplied\">the</span> sons, and the hearts of <span class=\"supplied\">the</span> sons to their fathers, so that I will not come and strike the land <span class=\"supplied\">with</span> a ban.”')
;

