INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Micah', '1', '1', '1', '<span class=\"verse-title\">The Impending Doom of Samaria and Jerusalem</span>The word of Adonai that came to Micah the Morashtite in the days of Jotham, Ahaz, and Hezekiah, the kings of Judah, that he saw concerning Samaria and Jerusalem:'),
('LEB', 'Micah', '1', '2', '2', 'Hear, all you peoples;  give heed, O earth and its fullness.  And let the Lord Adonai be against you as a witness,  the Lord from <span class=\"idiom\">his holy temple</span>.<span class=\"note\">“the temple of his holiness”</span>'),
('LEB', 'Micah', '1', '3', '2', 'For behold, Adonai is coming out from his place,  and he will come down and tread upon the high places of the earth.'),
('LEB', 'Micah', '1', '4', '2', 'The mountains will melt under him  and the valleys will burst open,  like wax before the fire,  like water rushing down a slope.'),
('LEB', 'Micah', '1', '5', '2', 'All this <span class=\"supplied\">is</span> for the rebellion of Jacob,  and for the sins of the house of Israel.  What <span class=\"supplied\">is</span> the rebellion of Jacob?  <span class=\"supplied\">Is it</span> not Samaria?  And what <span class=\"supplied\">are</span> the high places of Judah?  <span class=\"supplied\">Are they</span> not Jerusalem?'),
('LEB', 'Micah', '1', '6', '2', 'So I will make Samaria as a heap of rubble in the field,  a place for planting a vineyard.  And I will pour down her stones into the valley  and uncover her foundations.'),
('LEB', 'Micah', '1', '7', '2', 'Then all her idols will be broken in pieces,  and all her prostitution wages will be burned in the fire,  and all her idols I will make a desolation,  For from the wage of a prostitute she gathered <span class=\"supplied\">them</span>,  and to the wage of a prostitute they will return.'),
('LEB', 'Micah', '1', '8', '2', 'On account of this I will lament and wail.  I will go about barefoot and naked.  I will make a lamentation like the jackals,  and a mourning ceremony like the <span class=\"idiom\">ostriches</span>.<span class=\"note\">“daughters of an ostrich”</span>'),
('LEB', 'Micah', '1', '9', '2', 'For her wounds <span class=\"supplied\">are</span> incurable,  because it has come to Judah.  It has reached to the gate of my people, to Jerusalem.'),
('LEB', 'Micah', '1', '10', '2', 'Do not tell <span class=\"supplied\">it</span> in Gath;  you must not weep at all.  In Beth-le-Aphrah  roll yourself <span class=\"supplied\">in</span> dust.'),
('LEB', 'Micah', '1', '11', '2', 'Pass on, you inhabitants of Shaphir,  in naked shame.  The inhabitants of Zaanan do not come forth;  the wailing of Beth-ha-Ezel will take its protection from you.'),
('LEB', 'Micah', '1', '12', '2', 'For the inhabitants of Maroth  writhed for good,  because disaster has come down from Adonai  to the gate of Jerusalem.'),
('LEB', 'Micah', '1', '13', '2', 'Harness the chariot to the team of horses,  O inhabitants of Lachish;  it <span class=\"supplied\">is</span> the beginning of sin  for the daughter of Zion,  for the transgressions of Israel  were found in you.'),
('LEB', 'Micah', '1', '14', '2', 'Therefore you will give parting gifts  to Moresheth-Gath;  the houses of Achzib <span class=\"supplied\">will be</span> a deception  to the kings of Israel.'),
('LEB', 'Micah', '1', '15', '2', 'I will again bring the conqueror upon you,  O inhabitants of Mareshah;  the glory of Israel  will come to Adullam.'),
('LEB', 'Micah', '1', '16', '2', 'Make yourselves bald  and cut off your hair  for the children of your pleasure.  Expand your baldness as the eagle,  for they will go into exile away from you.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Micah', '2', '1', '1', '<span class=\"verse-title\">Woe to the Oppressors of God’s People</span>Woe <span class=\"supplied\">to</span> those who plan wickedness  and evil deeds upon their beds!  In the light of the morning they did it,  because they have power in their hands.'),
('LEB', 'Micah', '2', '2', '1', 'They covet fields and seize <span class=\"supplied\">them</span>,  and houses, and they take <span class=\"supplied\">them</span> away.  They oppress a man and his house;  a man and his inheritance.'),
('LEB', 'Micah', '2', '3', '2', 'Therefore, thus says Adonai: Look! I am planning disaster against this family from which you will not be able to remove your necks. You will not walk proudly, for it <span class=\"supplied\">is</span> a time of disaster.'),
('LEB', 'Micah', '2', '4', '3', 'In that day they will raise a proverb against you,  and will wail a bitter wailing, saying,  “We are utterly ruined;  he exchanges <span class=\"supplied\">the</span> portion of my people.  How he removes <span class=\"supplied\">it</span> from me;  he apportions our field to an apostate.”'),
('LEB', 'Micah', '2', '5', '3', 'Therefore you will have no one casting a line by lot  in the assembly of Adonai.'),
('LEB', 'Micah', '2', '6', '3', '“Do not preach!” they are preaching.  They should not preach to these;  disgrace will not overtake us.'),
('LEB', 'Micah', '2', '7', '3', 'Should <span class=\"supplied\">this</span> be said, O house of Jacob?  Is the patience<span class=\"note\">Or “spirit”</span>of Adonai shortened?  <span class=\"supplied\">Are</span> these his deeds?  Are my words not pleasing  to him who walks upright?'),
('LEB', 'Micah', '2', '8', '3', 'But <span class=\"idiom\">recently</span><span class=\"note\">“yesterday”</span>my people have risen up as an enemy;  from before the cloak you strip off the robe  from those passing by <span class=\"supplied\">in</span> confidence,  returning <span class=\"supplied\">from</span> war.'),
('LEB', 'Micah', '2', '9', '3', 'You have driven out the women of my people  from the houses of their<span class=\"note\">Hebrew “her”</span>pleasure.  From their<span class=\"note\">Hebrew “her”</span>children you have taken away  my glory forever.'),
('LEB', 'Micah', '2', '10', '3', 'Arise and go,  for this <span class=\"supplied\">is</span> no resting place,  on account of uncleanness <span class=\"supplied\">that</span> destroys  with painful destruction.'),
('LEB', 'Micah', '2', '11', '3', 'If a man walks about in a spirit of deception and lies,  <span class=\"supplied\">saying</span> “I will preach to you of wine and strong drink,”  then he would be a preacher <span class=\"supplied\">for</span> this people!'),
('LEB', 'Micah', '2', '12', '3', 'I will surely gather all of you, O Jacob;  I will surely gather together the remainder of Israel.  I will set them like sheep of Bozrah.  Like a herd in the midst of their pasture  they will be in tumult from people.'),
('LEB', 'Micah', '2', '13', '3', 'The one who breaks out before them goes up;  they break through and pass the gate,  going out through it.  Their king passes before them,  Adonai at their head.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Micah', '3', '1', '1', '<span class=\"verse-title\">Israel’s Leaders Denounced</span>And I said,  “Listen, O heads of Jacob  and leaders of the house of Israel!  <span class=\"supplied\">Is it</span> not for you to know justice?'),
('LEB', 'Micah', '3', '2', '1', '<span class=\"supplied\">Those of you who are</span> haters of good  and lovers of evil,  <span class=\"supplied\">who</span> tear their skin from them  and their flesh from their bones,'),
('LEB', 'Micah', '3', '3', '1', 'and who eat the flesh of my people,  and strip their skin from them,  and break their bones,  and chop <span class=\"supplied\">them</span> like meat in the pot,  and like flesh in the midst of a cooking pot.”'),
('LEB', 'Micah', '3', '4', '1', 'Then they will cry to Adonai,  but he will not answer them.  He will hide his face from them at that time,  when they have made their deeds evil.'),
('LEB', 'Micah', '3', '5', '1', 'Thus says Adonai concerning the prophets  who are leading my people astray,  who are biting with their teeth  and proclaim, “Peace,”  but whoever puts nothing into their mouths  they declare war against.'),
('LEB', 'Micah', '3', '6', '1', 'Therefore <span class=\"supplied\">it will be as</span> night to you, without vision,  and darkness to you, without divination.  And the sun will set on the prophets,  and the day will grow dark over them.'),
('LEB', 'Micah', '3', '7', '1', 'Then the seers will be disgraced,  and those practicing divination will be put to shame.  All of them will cover their lips,  for there is no reply from God.'),
('LEB', 'Micah', '3', '8', '1', 'But I, I am filled <span class=\"supplied\">with</span> power,  with the Spirit of Adonai,  and with justice and might,  to declare to Jacob his rebellion,  and to Israel his sin.'),
('LEB', 'Micah', '3', '9', '1', 'Hear this, O rulers of the house of Jacob  and leaders of the house of Israel,  those detesting justice  and perverting all that <span class=\"supplied\">is</span> right,'),
('LEB', 'Micah', '3', '10', '1', 'he who builds Zion with blood  and Jerusalem with wickedness.'),
('LEB', 'Micah', '3', '11', '1', 'Its rulers judge for a bribe;  its priests teach for a price;  its prophets practice divination for money.  But they lean on Adonai, saying,  “<span class=\"supplied\">Is</span> not Adonai in our midst?  Disaster will not come upon us.”'),
('LEB', 'Micah', '3', '12', '1', 'Therefore on account of you  Zion will be plowed <span class=\"supplied\">as</span> a field,  and Jerusalem will be a heap of rubble,  and <span class=\"idiom\">the temple mount</span><span class=\"note\">“the mountain of the house”</span>as a high place <span class=\"supplied\">in</span> a forest.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Micah', '4', '1', '1', '<span class=\"verse-title\">The Mountain of Adonai</span>And it will be <span class=\"supplied\">that</span> at the end of those days,  the mountain of Adonai  will be established as the highest of the mountains,  and it will be lifted up above the hills,  and people will stream to it.'),
('LEB', 'Micah', '4', '2', '1', 'And many nations will come and say,  “Come! Let us go up to the mountain of Adonai,  and to the <span class=\"idiom\">temple</span><span class=\"note\">“house”</span>of the God of Jacob,  that he may teach us his ways,  and that we may walk in his paths,”  for the law will go out from Zion,  and the word of Adonai from Jerusalem.'),
('LEB', 'Micah', '4', '3', '1', 'And he will judge between many peoples  and will arbitrate for strong nations far away;  and they will beat their swords into plowshares  and their spears into pruning hooks;  nation will not lift up a sword against a nation,  and they will no longer learn war.'),
('LEB', 'Micah', '4', '4', '1', 'But they will sit, each under his vine  and under his fig tree,  and no one will make them afraid,  for the mouth of Adonai of hosts has spoken.'),
('LEB', 'Micah', '4', '5', '1', 'For all the nations walk,  each in the name of its god,  but we will walk in the name of Adonai our God,  forever and ever.'),
('LEB', 'Micah', '4', '6', '3', '<span class=\"verse-title\">Adonai Will Deliver Zion</span>“In that day,” <span class=\"idiom\">declares Adonai,</span><span class=\"note\">“a declaration of Adonai”</span> “I will assemble the one who limps,  and I will gather the one who has been scattered,  and <span class=\"supplied\">those</span> whom I have mistreated.'),
('LEB', 'Micah', '4', '7', '3', 'And I will make the one who limps a remnant,  and the one driven far away a strong nation,  and Adonai will reign over them on Mount Zion  from now to forever.'),
('LEB', 'Micah', '4', '8', '3', 'And you, O Migdal-Eder,<span class=\"note\">Or “tower of the flock”</span> hill of the daughter of Zion,  to you it will come,  and the former dominion will come,  <span class=\"supplied\">the</span> reign of the daughter of Jerusalem.'),
('LEB', 'Micah', '4', '9', '3', 'So then, why do you shout a loud shout?  Is there no king in you?  Has your counselor perished  that pangs like a woman in labor have seized you?'),
('LEB', 'Micah', '4', '10', '3', 'Writhe and groan, O daughter of Zion,  like a woman in labor.  For now you will go forth from the city,  and you will camp in the field;  you will go to Babylon.  There you will be rescued;  there Adonai will redeem you  from the hand of your enemies.'),
('LEB', 'Micah', '4', '11', '3', 'And now, many nations are gathered against you  who are saying, ‘Let her be defiled,  and let our eyes gaze upon Zion.’'),
('LEB', 'Micah', '4', '12', '3', 'But they do not know the thoughts of Adonai,  and they do not understand his plan,  that he has gathered them as sheaves  to his threshing floor.'),
('LEB', 'Micah', '4', '13', '3', 'Arise and thresh, O daughter of Zion,  for your horn I will make <span class=\"supplied\">as</span> iron  and your hooves <span class=\"supplied\">as</span> bronze.  And you will break many peoples in pieces,  and their gain you will devote to destruction to Adonai,  and their wealth to the Lord of the whole earth.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Micah', '5', '1', '1', '<span class=\"verse-title\">A Ruler from Bethlehem</span><span class=\"note\">Micah 5:1–15 in the English Bible is 4:14–5:14 in the Hebrew Bible</span>Now muster troops, O daughter of troops;  a siege he puts against us.  They strike the ruler of Israel  with a rod on the cheek.'),
('LEB', 'Micah', '5', '2', '1', 'But you, O Bethlehem Ephrathah,  <span class=\"supplied\">too</span> small to be among the clans of Judah,  from you one will go out for me,  to be ruler in Israel;  and his origins <span class=\"supplied\">are</span> from of old,  from ancient days.'),
('LEB', 'Micah', '5', '3', '1', 'Therefore he will give them up  until the time of she who is with child has given birth.  And the rest of his brothers will return  to the children of Israel.'),
('LEB', 'Micah', '5', '4', '1', 'And he will stand and shepherd <span class=\"supplied\">his flock</span>  in the strength of Adonai,  in the majesty of the name of Adonai his God.  And they will live,  for now he will be great unto the ends of the earth.'),
('LEB', 'Micah', '5', '5', '1', 'And this one will be peace.  <span class=\"supplied\">As for</span> the Assyrian,<span class=\"note\">Hebrew “Assyria”</span>when he comes into our land  and when he treads on our fortresses,  then we will raise up against him seven shepherds  and eight leaders of men.'),
('LEB', 'Micah', '5', '6', '1', 'And they will shepherd the land of Assyria with the sword,  and the land of Nimrod at its entrances.  And he will rescue <span class=\"supplied\">us</span> from the Assyrian<span class=\"note\">Hebrew “Assyria”</span> when he comes into our land,  and when they tread upon our border.'),
('LEB', 'Micah', '5', '7', '3', '<span class=\"verse-title\">A Remnant Delivered</span>And the remnant of Jacob will be  in the midst of many nations,  like dew from Adonai,  like showers upon the grass  which does not wait for a man,  nor delays for the children of humankind.'),
('LEB', 'Micah', '5', '8', '3', 'And the remnant of Jacob will be among the nations,  in the midst of many peoples,  like a lion among the wild animals of the forest,  like a young lion among the herds of sheep  which, when it passes through and treads <span class=\"supplied\">down</span>  and tears in pieces, there is none who <span class=\"supplied\">can</span> deliver.'),
('LEB', 'Micah', '5', '9', '3', 'Your hand will be lifted high over your enemies,  and all your foes will be cut off.'),
('LEB', 'Micah', '5', '10', '3', '“And it will happen <span class=\"supplied\">that</span> in that day,” <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai,  “then I will cut off your horses from among you,  and I will destroy your chariots.'),
('LEB', 'Micah', '5', '11', '3', 'And I will cut off the cities of your land,  and I will demolish all your fortifications.'),
('LEB', 'Micah', '5', '12', '3', 'And I will cut off sorceries from your hand,  and you will not have soothsayers.'),
('LEB', 'Micah', '5', '13', '3', 'And I will cut off your idols  and your stone pillars from among you,  and you will no longer bow down  to the work of your hands.'),
('LEB', 'Micah', '5', '14', '3', 'And I will uproot your Asherahs from among you,  and I will destroy your cities.'),
('LEB', 'Micah', '5', '15', '3', 'And in anger and in wrath I will execute vengeance  on the nations who did not obey.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Micah', '6', '1', '1', '<span class=\"verse-title\">Adonai Brings a Charge against Israel</span>Hear now what Adonai says:  “Arise! Plead <span class=\"supplied\">your case</span> with the mountains,  and let the hills hear your voice.”'),
('LEB', 'Micah', '6', '2', '1', 'Hear, O mountains, the indictment of Adonai,  and you eternal foundations of the earth,  for Adonai has an indictment against his people,  and against Israel he contends.'),
('LEB', 'Micah', '6', '3', '1', '“O my people, what have I done to you,  and how have I wearied you? Answer me!'),
('LEB', 'Micah', '6', '4', '1', 'For I brought you up from the land of Egypt,  and from the house of slavery I redeemed you.  And I sent Moses, Aaron, and Miriam before you.'),
('LEB', 'Micah', '6', '5', '1', 'O my people, remember what Balak the king of Moab devised,  and what Balaam the son of Beor answered him,  and <span class=\"supplied\">what happened from</span> Shittim to Gilgal,  so that you might know the righteous acts of Adonai.”'),
('LEB', 'Micah', '6', '6', '3', '<span class=\"verse-title\">What Does Adonai Require?</span>With what shall I approach Adonai,  and bow down to God on high?  Shall I approach him with burnt offerings,  with bull calves a year old?'),
('LEB', 'Micah', '6', '7', '3', 'Will Adonai be pleased with thousands of rams,  with myriads of rivers of oil?  Shall I give my firstborn for my transgression,  the fruit of my body <span class=\"supplied\">for the</span> sin of my soul?'),
('LEB', 'Micah', '6', '8', '3', 'He has told you, O mortal, what <span class=\"supplied\">is</span> good,  and what does Adonai ask from you  but to do justice, and to love kindness,  and to walk humbly with your God?'),
('LEB', 'Micah', '6', '9', '5', '<span class=\"verse-title\">The Destruction of the Wicked</span>The voice of Adonai calls to the city  (<span class=\"supplied\">it is</span> sound judgment to fear your name):  “Hear, <span class=\"supplied\">O</span> staff!<span class=\"note\">Or “tribe”</span>Now who has appointed it?'),
('LEB', 'Micah', '6', '10', '5', 'Is there any longer a man <span class=\"supplied\">in</span> the house of the wicked  treasures of wickedness,  and the ephah of scarcity <span class=\"supplied\">which is</span> accursed?<span class=\"note\">The meaning of the Hebrew text is uncertain</span>'),
('LEB', 'Micah', '6', '11', '5', 'Shall I regard as pure <span class=\"supplied\">the one</span> with scales of wickedness,  and with a bag of deceitful weights?'),
('LEB', 'Micah', '6', '12', '5', 'Because her rich are full of violence,  and her inhabitants speak lies,  and their tongue <span class=\"supplied\">is</span> deceitful in their mouth.'),
('LEB', 'Micah', '6', '13', '5', 'And I also <span class=\"idiom\">have made you sick by striking you down</span>,<span class=\"note\">“I have made sick to strike you down”</span> making <span class=\"supplied\">you</span> desolate because of your sins.'),
('LEB', 'Micah', '6', '14', '5', 'You yourself will eat but not be satisfied;  your hunger <span class=\"supplied\">will be</span> in your midst,  and you will put away, but you will not save,  and what you save I will hand over to the sword.'),
('LEB', 'Micah', '6', '15', '5', 'You yourself will sow, but you will not reap;  you will tread olives, but you will not anoint yourself with oil;  <span class=\"supplied\">you will tread</span> grapes, but you will not drink wine.'),
('LEB', 'Micah', '6', '16', '5', 'For you have observed the regulations of Omri  and all the works of the house of Ahab.  And you have walked in their counsels,  so that I am making you a desolation  and your inhabitants an object of scorn.  So you will bear the scorn of my people.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Micah', '7', '1', '1', '<span class=\"verse-title\">Wait Upon Adonai</span>Woe is me! For I have become  like the gatherings of summer,  like the gleanings of the grape harvest,  <span class=\"supplied\">when</span> there is no cluster of grapes to eat  <span class=\"supplied\">or</span> early ripened fruit <span class=\"supplied\">that</span> my soul desires.'),
('LEB', 'Micah', '7', '2', '1', 'The faithful <span class=\"supplied\">person</span> has perished from the land,  and there is none who is upright among humankind.  All of them lie in wait;  each hunts his brother <span class=\"supplied\">with</span> a net.'),
('LEB', 'Micah', '7', '3', '1', 'Their hands <span class=\"supplied\">are</span> upon evil, to do <span class=\"supplied\">it</span> well;  the official and the judge ask for the bribe,  and the great <span class=\"supplied\">man</span> utters the evil desire of his soul;  and they weave <span class=\"supplied\">it</span> together.'),
('LEB', 'Micah', '7', '4', '1', 'The best of them <span class=\"supplied\">is</span> like a brier;  <span class=\"supplied\">the most</span> upright <span class=\"supplied\">worse</span> than a thorn hedge.  The day of your watchman, your punishment, has come;  now their confusion will come.'),
('LEB', 'Micah', '7', '5', '1', 'Do not put faith in a friend;  put no trust in a close friend.  Guard the doorways of your mouth  from the one who lies in your lap.'),
('LEB', 'Micah', '7', '6', '1', 'For a son treats a father with contempt;  a daughter rises up against her mother,  a daughter-in-law against her mother-in-law;  <span class=\"supplied\">the</span> enemies of a man <span class=\"supplied\">are</span> the men of his own house.'),
('LEB', 'Micah', '7', '7', '1', 'But <span class=\"supplied\">as for</span> me, I will look to Adonai;  I will wait for the God of my salvation.  My God will hear me.'),
('LEB', 'Micah', '7', '8', '1', 'You should not rejoice over me, O my enemy!  When I fall I will stand up;  when I sit in darkness  Adonai <span class=\"supplied\">will be</span> a light for me.'),
('LEB', 'Micah', '7', '9', '1', 'I will bear the rage of Adonai,  for I have sinned against him,  until he pleads my cause  and executes my justice.  He will bring me out to the light;  I will see his righteousness.'),
('LEB', 'Micah', '7', '10', '1', 'Then my enemy will see,  and shame will cover her who said to me,  “Where <span class=\"supplied\">is</span> Adonai your God?”  My eyes will look upon her;  now she will become a trampling place,  like mud in the streets.'),
('LEB', 'Micah', '7', '11', '1', 'A day for building your walls;  <span class=\"supplied\">on</span> that day he will extend <span class=\"supplied\">your</span> boundary.'),
('LEB', 'Micah', '7', '12', '1', '<span class=\"supplied\">On</span> that day he will come to you  from Assyria and the cities of Egypt,  and from Egypt to the River,  and from sea to sea  and mountain to mountain.'),
('LEB', 'Micah', '7', '13', '1', 'But the earth will be a desolation  because of its inhabitants,  for the fruit of their deeds.'),
('LEB', 'Micah', '7', '14', '1', 'Shepherd your people with your staff,  the flock of your inheritance,  those dwelling alone <span class=\"supplied\">in</span> a forest  in the midst of Carmel.  Let them feed in Bashan and Gilead,  as <span class=\"supplied\">in</span> the days of old.'),
('LEB', 'Micah', '7', '15', '1', 'As <span class=\"supplied\">in</span> the days when you came out  from the land of Egypt  I will show him wondrous things.'),
('LEB', 'Micah', '7', '16', '1', 'The nations will see and be ashamed  because of all their might.  They will lay <span class=\"supplied\">the</span> hand on <span class=\"supplied\">the</span> mouth;  their ears will be deaf.'),
('LEB', 'Micah', '7', '17', '1', 'They will lick the dust like the serpent,  like the crawling things of the earth.  They will come trembling from their strongholds  to Adonai our God.  Let them fear and be afraid of you.'),
('LEB', 'Micah', '7', '18', '1', 'Who <span class=\"supplied\">is</span> a God like you, forgiving sin  and passing over rebellion for the remnant of his inheritance?  He does not retain his anger forever,  for he delights in loyal love.'),
('LEB', 'Micah', '7', '19', '1', '<span class=\"idiom\">He will again have compassion</span><span class=\"note\">“He will return, he will have compassion”</span>on us;  he will trample our iniquities.  And you will hurl all their sins  in the depths of the sea.'),
('LEB', 'Micah', '7', '20', '1', 'You will show faithfulness to Jacob,  and loyal love to Abraham,  as you have sworn to our ancestors<span class=\"note\">Or “fathers”</span> from the days of old.')
;

