INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nahum', '1', '1', '1', '<span class=\"verse-title\">Superscription</span>The oracle concerning Nineveh—  the scroll of the vision of Nahum the Elkoshite:'),
('LEB', 'Nahum', '1', '2', '3', '<span class=\"verse-title\">Half-Acrostic: Adonai Takes Vengeance against His Enemies</span>Adonai is a jealous God and avenging;  Adonai is avenging and <span class=\"idiom\">full of wrath</span>.<span class=\"note\">Literally “a lord of wrath”</span> Adonai takes vengeance against his enemies;  he rages against his adversaries.'),
('LEB', 'Nahum', '1', '3', '3', 'Adonai is slow to anger but great <span class=\"supplied\">in</span> power;  he will certainly not allow <span class=\"supplied\">the guilty</span> to go unpunished.  <span class=\"idiom\">He marches</span><span class=\"note\">Literally “His path”</span>in storm wind and in gale;  storm clouds <span class=\"supplied\">are the</span> dust of his feet.'),
('LEB', 'Nahum', '1', '4', '3', 'He rebukes the sea and he dries up the rivers;  he makes all the rivers run dry.  Bashan and Carmel wither;<span class=\"note\">MT reads “languishes,” but the versions reflect “withers,” which also restores the acrostic</span> the blossom of Lebanon languishes.'),
('LEB', 'Nahum', '1', '5', '3', 'Mountains quake before him;  the hills shake apart.<span class=\"note\">Or “melt”</span> The earth heaves before him—  the world and all her inhabitants.'),
('LEB', 'Nahum', '1', '6', '3', 'His indignation—who can stand before it?  Who can endure <span class=\"idiom\">his fierce anger</span>?<span class=\"note\">Literally “the heat of his anger”</span> His wrath is poured out like fire;  rocks are shattered before<span class=\"note\">Or “by”</span>him.'),
('LEB', 'Nahum', '1', '7', '3', 'Adonai is good—a refuge in <span class=\"supplied\">the</span> day of distress;  <span class=\"supplied\">he knows</span> those who take refuge in him.'),
('LEB', 'Nahum', '1', '8', '3', 'But with a rushing torrent he will bring <span class=\"supplied\">Nineveh</span> to an end;  he will chase his enemies into darkness.'),
('LEB', 'Nahum', '1', '9', '5', '<span class=\"verse-title\">Adonai Will Destroy Nineveh</span>What<span class=\"note\">Or “Why …?”</span>do you plot against Adonai?  <span class=\"idiom\">He will completely destroy it</span>;<span class=\"note\">Literally “he will make a complete destruction”</span> trouble will not rise up a second time!'),
('LEB', 'Nahum', '1', '10', '5', 'For like entangled thorns,  and like their drink which is drunk,  they will be consumed like fully dry chaff.'),
('LEB', 'Nahum', '1', '11', '5', 'From you goes out one who plots evil against Adonai,  one who plans wickedness.'),
('LEB', 'Nahum', '1', '12', '7', '<span class=\"verse-title\">Adonai Will Deliver Judah and Destroy Nineveh</span>Adonai says this:'),
('LEB', 'Nahum', '1', '13', '8', '“Even though <span class=\"supplied\">they are</span> powerful and likewise many,  even so they will be cut off and pass away.  Though I have afflicted you,<span class=\"note\">That is, Judah</span> I will afflict you<span class=\"note\">That is, Judah</span>no longer.'),
('LEB', 'Nahum', '1', '14', '9', 'Adonai has commanded concerning you:'),
('LEB', 'Nahum', '1', '15', '10', '“Your name will no longer be sown.  I will cut off <span class=\"idiom\">the idols and images</span><span class=\"note\">Literally “the idols and the molten idols”</span>from the <span class=\"idiom\">temple</span><span class=\"note\">Literally “house”</span>of your gods;  <span class=\"idiom\">I will send you to the grave</span><span class=\"note\">Literally “I will make your grave”</span>because you are worthless.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nahum', '2', '1', '1', '<span class=\"verse-title\">The Divine Warrior Will Attack Nineveh</span><span class=\"idiom\">One who shatters</span><span class=\"note\">Literally “a shatterer”</span>has come up against you!  Guard <span class=\"supplied\">the</span> fortification!  Watch <span class=\"supplied\">the</span> road!<span class=\"note\">Or “way”</span> Gird <span class=\"supplied\">your</span> loins!  <span class=\"idiom\">Muster</span><span class=\"note\">Or “Collect”</span>all <span class=\"supplied\">your</span> strength!'),
('LEB', 'Nahum', '2', '2', '1', 'For Adonai will restore the majesty of Jacob  like the majesty of Israel;  for ravagers have ravaged them  and ruined <span class=\"supplied\">their</span> branches.'),
('LEB', 'Nahum', '2', '3', '3', '<span class=\"verse-title\">The Enemy Army Conquers the City of Nineveh</span>The shields of his warriors <span class=\"supplied\">are</span> dyed red;  The powerful men <span class=\"supplied\">are</span> dressed in scarlet.  The metal of the chariots<span class=\"note\">Hebrew “chariot”</span><span class=\"supplied\">shines</span> like fire <span class=\"idiom\">on the day of battle</span>,<span class=\"note\">Literally “on the day of his preparation”</span> and <span class=\"supplied\">their</span> spears quiver.'),
('LEB', 'Nahum', '2', '4', '3', 'The chariots<span class=\"note\">Hebrew “chariot”</span>race madly through the streets;  they rush back and forth in the public squares.  Their appearance like lightning bolts,  they dart about like flashes of lightning.'),
('LEB', 'Nahum', '2', '5', '3', 'He calls his officers;  they stumble as they march;  they rush to her wall;  they set the covering<span class=\"note\">The Hebrew word describes a small portable roof to protect siege warriors from arrows and debris hurled at them from the fortified city wall</span>in place.'),
('LEB', 'Nahum', '2', '6', '3', 'The gates of the river are opened;  the palace trembles.'),
('LEB', 'Nahum', '2', '7', '3', '<span class=\"idiom\">Her goddess is taken out and taken into exile</span>;<span class=\"note\">Literally “It is decreed <span class=\"supplied\">that</span> she be exiled <span class=\"supplied\">and</span> led away.” MT reads the very enigmatic “And he is placed, she is sent into exile, she is taken up.” The BHS editors suggest the conjectural emendation “And her goddess <span class=\"supplied\">= the idol of the patron deity of Nineveh</span> is taken and taken into exile.” This is adopted in the translation on the basis of internal evidence</span> her maidservants moan like doves;  they beat on their breasts.'),
('LEB', 'Nahum', '2', '8', '3', 'Nineveh <span class=\"supplied\">is</span> like a pool of water without its water.<span class=\"note\">MT reads “from her days.” Greek LXX and Syriac Peshitta reflect “from her waters”</span> <span class=\"idiom\">As they flee</span>,<span class=\"note\">Literally “And they flee away”</span><span class=\"supplied\">she cries,</span> “Stop! Stop!”  But there is no one who turns back.'),
('LEB', 'Nahum', '2', '9', '3', 'Plunder the silver! Plunder the gold!  There is no end to the spoils,<span class=\"note\">Literally “the supply”</span> an abundance of <span class=\"idiom\">everything one could want</span>!<span class=\"note\">Literally “every kind of desirable object”</span>'),
('LEB', 'Nahum', '2', '10', '3', 'Emptiness and plundering and devastation!  Their hearts faint and their knees tremble,<span class=\"note\">Or “totter”</span> <span class=\"idiom\">All their loins shake</span><span class=\"note\">Literally “And shaking of all loins”</span>and all their faces <span class=\"idiom\">turn</span><span class=\"note\">Literally “gather”</span>pale.'),
('LEB', 'Nahum', '2', '11', '5', '<span class=\"verse-title\">The Divine Warrior Will Hunt down the Mighty Lions</span>Where <span class=\"supplied\">now</span> <span class=\"supplied\">is</span> the den of <span class=\"supplied\">the</span> lions  and <span class=\"supplied\">the</span> cave of the fierce lions?  There the lioness, the cub, and the lion once <span class=\"idiom\">prowled</span>,<span class=\"note\">Literally “went”</span> <span class=\"idiom\">and no one disturbed them</span>.<span class=\"note\">Literally “there <span class=\"supplied\">is</span> no one making <span class=\"supplied\">them</span> afraid”</span>'),
('LEB', 'Nahum', '2', '12', '5', 'The lion tore apart enough <span class=\"supplied\">prey</span> for his cubs,  he strangled <span class=\"supplied\">prey</span> for his lioness;  he filled <span class=\"idiom\">his lair</span><span class=\"note\">Literally “his holes”</span><span class=\"supplied\">with</span> prey  and his den <span class=\"supplied\">with</span> mangled carcass.'),
('LEB', 'Nahum', '2', '13', '5', '“Look! I am against you!” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai of hosts.  “I will burn her chariots <span class=\"idiom\">with fire</span>;<span class=\"note\">Literally “with smoke”</span> the sword will devour fierce lions.  I will cut off your prey from the earth;  the voice of your messengers will no longer be heard.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nahum', '3', '1', '1', '<span class=\"verse-title\">The Doom of the Wicked City is Certain</span>Woe to the city <span class=\"supplied\">that has shed</span> <span class=\"idiom\">much blood</span>!<span class=\"note\">Literally “bloods”</span> <span class=\"idiom\">She is a deceiver</span>,<span class=\"note\">Literally “All of her <span class=\"supplied\">is</span> deception”</span> She is filled <span class=\"supplied\">with</span> plunder,  <span class=\"idiom\">She has hoarded her spoils of war</span>.<span class=\"note\">Literally “Prey does not depart”</span>'),
('LEB', 'Nahum', '3', '2', '1', 'The crack of the whip!  The rumbling of the <span class=\"supplied\">chariot</span> wheel!  The galloping of the horse!  The racing of the chariot!'),
('LEB', 'Nahum', '3', '3', '1', 'Chariots charge!  Swords flash!  Spears glitter!  <span class=\"idiom\">Many corpses are piled high</span>!<span class=\"note\">Literally “Many dead, piles of corpses”</span> There is no end to the slain!  They stumble over their dead!'),
('LEB', 'Nahum', '3', '4', '3', '<span class=\"verse-title\">Harlot Nineveh Will Get What She Deserves</span>“Because of the many idolatries of <span class=\"supplied\">the</span> prostitute,  the beautiful charm <span class=\"supplied\">of</span> a mistress of witchcraft,  she who enslaves nations by her harlotries,  and peoples by her sorceries,'),
('LEB', 'Nahum', '3', '5', '3', '“Look! I am against you!” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai.  “I will strip up your skirts over your face;  I will let nations look <span class=\"supplied\">at</span> your nakedness and your shame.'),
('LEB', 'Nahum', '3', '6', '3', '“I will throw filth upon you,  I will treat you with contempt,  I will make you a spectacle.'),
('LEB', 'Nahum', '3', '7', '3', '“And it will be that everyone who sees you will flee from you,  And <span class=\"idiom\">they</span><span class=\"note\">Hebrew “he”</span>will say, ‘Nineveh is destroyed!’  Who will mourn for her?  From whence shall I seek comforters for you?”'),
('LEB', 'Nahum', '3', '8', '5', '<span class=\"verse-title\">Nineveh Will Suffer the Same Fate She Inflicted on Thebes</span>Are you better than Thebes?<span class=\"note\">Hebrew “No-Amon”</span> She who sits at the Nile, surrounded by her waters,  her rampart <span class=\"supplied\">was the</span> sea and water <span class=\"supplied\">was</span> her wall.'),
('LEB', 'Nahum', '3', '9', '5', 'Cush <span class=\"supplied\">was</span> her strength, Egypt without end;  Put and Libya were among <span class=\"idiom\">your allies</span>.<span class=\"note\">Literally “your helpers”</span>'),
('LEB', 'Nahum', '3', '10', '5', 'Yet she went into captivity as an exile;  her children were dashed to pieces at the head of <span class=\"supplied\">the</span> streets;  they cast lots for all of her nobles;  all of her dignitaries were bound with chains.'),
('LEB', 'Nahum', '3', '11', '5', 'You also will behave like a drunkard;  You also will hide yourself;  You also will seek refuge from <span class=\"supplied\">the</span> enemy.'),
('LEB', 'Nahum', '3', '12', '7', '<span class=\"verse-title\">Nineveh’s Defenses Will Fail</span>All of your fortifications <span class=\"supplied\">are like</span> fig trees with <span class=\"supplied\">ripe</span> firstfruits—  if they are shaken, they will fall into the mouth of the eater.'),
('LEB', 'Nahum', '3', '13', '7', 'Look! Your troops <span class=\"supplied\">are like</span> women in your midst.  The gates of your land are wide open to your enemies;  fire will consume the bars <span class=\"supplied\">of your gates</span>.'),
('LEB', 'Nahum', '3', '14', '7', 'Draw water for a siege!  Strengthen your fortifications!  Go to the mud <span class=\"supplied\">pit</span>!  Trample the clay!  Grasp the brick mold!'),
('LEB', 'Nahum', '3', '15', '7', 'There fire will consume you;  the sword will cut you off.  It will consume you like the locust.'),
('LEB', 'Nahum', '3', '16', '9', '<span class=\"verse-title\">Nineveh’s Defenders Will Flee</span>Multiply yourself like the locust!  Multiply yourself like the grasshopper!'),
('LEB', 'Nahum', '3', '17', '9', 'You have increased your merchants more than the stars of heaven;  <span class=\"supplied\">like</span> the locust they will shed <span class=\"supplied\">their skin</span> and fly away.'),
('LEB', 'Nahum', '3', '18', '11', '<span class=\"verse-title\">Nineveh Will Come to an End</span>Your shepherds are sleeping, <span class=\"supplied\">O</span> king of Assyria!  Your nobles slumber.  Your people are scattered on the mountains;  no one can gather them.'),
('LEB', 'Nahum', '3', '19', '11', 'There is no healing for your wound;  your injury is fatal.  All who hear the report of you will clap <span class=\"supplied\">their</span> hands <span class=\"supplied\">for joy</span> concerning you,  <span class=\"idiom\">For who has not suffered at the hands of your endless cruelty</span>?<span class=\"note\">Literally “For over whom has your endless cruelty not passed?”</span>')
;

