INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '1', '1', '1', '<span class=\"verse-title\">Nehemiah’s Prayer for the People</span>The words of Nehemiah son of Hacaliah.'),
('LEB', 'Nehemiah', '1', '2', '2', 'It happened in the month of Kislev, in the twentieth year, that I myself was in the citadel in Susa,'),
('LEB', 'Nehemiah', '1', '3', '2', 'and one of my brothers, Hanani, came with some men from Judah. I asked them about the Jews who had escaped the captivity and about Jerusalem.'),
('LEB', 'Nehemiah', '1', '4', '3', 'When I heard these words, I sat and wept and mourned for days, and I was fasting and praying before the God of the heavens.'),
('LEB', 'Nehemiah', '1', '5', '3', 'I said, “O Adonai of the heavens, the great and awesome one who keeps the covenant and loyal love for the ones who love him and for those who keep his commands.'),
('LEB', 'Nehemiah', '1', '6', '3', 'Please, let your ear be attentive and your eyes open to hear the prayer of your servant that I am praying before you by day and by night for your servants, the <span class=\"idiom\">Israelites</span>,<span class=\"note\">“sons/children of Israel”</span>and confessing the sins of the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span>that we have sinned against you. I and my father’s house have sinned.'),
('LEB', 'Nehemiah', '1', '7', '3', 'We have certainly offended you and have not kept the commands, regulations, and judgments that you have commanded your servant Moses.'),
('LEB', 'Nehemiah', '1', '8', '3', 'Please, remember the word that you have commanded to your servant Moses, saying, ‘If you act unfaithfully I will scatter you all among the nations.'),
('LEB', 'Nehemiah', '1', '9', '3', 'But if you return to me and keep my commandments and do them, even though all of your outcasts are at the furthest parts of heaven, I will gather them and bring them to the place which I have chosen to make my name dwell.’'),
('LEB', 'Nehemiah', '1', '10', '3', 'They are your servants and your people whom you have redeemed by your great power and by your strong hand.'),
('LEB', 'Nehemiah', '1', '11', '3', 'O Lord, please let your ear be attentive to the prayer of your servant and to the prayer of your servants who delight to revere in your name. Please, let your servant be successful this day and give him compassion before this man.” I was cupbearer for the king.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '2', '1', '1', '<span class=\"verse-title\">Nehemiah Sent</span>It happened in the month of Nisan, in the twentieth year of King Artaxerxes, when wine was before him, I carried the wine and gave it to the king. And I had never been sad before the king.'),
('LEB', 'Nehemiah', '2', '2', '1', 'So the king said to me, “Why is your face sad since you are not sick? This is nothing but sadness of the heart.” And I was very much afraid.'),
('LEB', 'Nehemiah', '2', '3', '1', 'I said to the king, “May the king live forever! Why should my face not be sad when the city of my ancestors’<span class=\"note\">Or “fathers’ ”</span>burial site<span class=\"note\">Hebrew “sites”</span>is ruined and her gates are consumed by fire?”'),
('LEB', 'Nehemiah', '2', '4', '1', 'Then the king said to me, “What is your request?” So I prayed to the God of the heavens.'),
('LEB', 'Nehemiah', '2', '5', '1', 'Then I said to the king, “If it pleases the king, and if your servant has <span class=\"supplied\">found</span> favor in your presence, <span class=\"supplied\">I ask</span> that you send me to Judah, to the city of my ancestors’<span class=\"note\">Or “fathers’ ”</span>burial sites, so that I may rebuild it.”'),
('LEB', 'Nehemiah', '2', '6', '2', 'With the queen sitting beside him, the king said to me, “How long will your journey be and when will you return?” So it pleased the king and he sent me, and I set for him an appointed time.'),
('LEB', 'Nehemiah', '2', '7', '2', 'Then I said to the king, “If it is good for the king, let letters be given to me for the governors <span class=\"supplied\">in the province</span> Beyond the River, that they may let me pass until I come to Judah.'),
('LEB', 'Nehemiah', '2', '8', '2', 'Also, a letter to Asaph, keeper of the king’s land reserve, that he should give me timber for laying the beams for the gates of the citadel of the house and for the walls of the city, and for the house which I will enter.” And the king gave <span class=\"supplied\">permission</span> to me, according to the good hand of God on me.'),
('LEB', 'Nehemiah', '2', '9', '3', 'I came to the governors of <span class=\"supplied\">the province</span> Beyond the River, and I gave them the letters of the king. Then the king sent troop commanders and horses with me.'),
('LEB', 'Nehemiah', '2', '10', '3', 'But when Sanballat the Horonite and the Ammonite servant Tobiah heard <span class=\"supplied\">this</span>, <span class=\"idiom\">they were greatly displeased</span><span class=\"note\">“it was a great disaster for them”</span>that a person had come to seek the welfare of the <span class=\"idiom\">Israelites</span>.<span class=\"note\">“sons/children of Israel”</span>'),
('LEB', 'Nehemiah', '2', '11', '5', '<span class=\"verse-title\">Nehemiah Inspects the Walls and Decides to Restore Them</span>I came to Jerusalem and was there for three days.'),
('LEB', 'Nehemiah', '2', '12', '5', 'I got up during the night, I and a few men with me. I did not tell anybody what my God put in my heart to do for Jerusalem. No animal <span class=\"supplied\">was</span> with me except the animal that I was riding on.'),
('LEB', 'Nehemiah', '2', '13', '5', 'I went out during the night at the gate of the valley by the Dragon spring and to the Dung Gate. And I examined the walls in Jerusalem and its gates that had been destroyed by the fire.'),
('LEB', 'Nehemiah', '2', '14', '5', 'I crossed over to the Fountain Gate and to the King’s Pool, but there was no place for <span class=\"idiom\">my mount</span><span class=\"note\">“the animal under me”</span>to cross over.'),
('LEB', 'Nehemiah', '2', '15', '5', 'So I went up by the valley during the night and was examining the wall. Then I returned and came to the Valley Gate and returned.'),
('LEB', 'Nehemiah', '2', '16', '5', 'The prefects did not know where I had gone and what I was doing. I had not yet told the Jews, the priests, the nobles, the prefects, and the rest of the workers.'),
('LEB', 'Nehemiah', '2', '17', '6', 'Then I said to them, “You see the misery that we are in, that Jerusalem is ruined and its gates burned by the fire. Come, build the walls of Jerusalem and we shall no longer be a disgrace.”'),
('LEB', 'Nehemiah', '2', '18', '6', 'I told them of the good hand of my God that was upon me and surely the words of the king that were spoken to me. And they said, “Let us arise and build!” And they strengthened their hands for <span class=\"supplied\">this</span> good work.'),
('LEB', 'Nehemiah', '2', '19', '6', 'But Sanballat the Horonite, the Ammonite servant Tobiah, and Geshem the Arab heard it, and they mocked and despised us, saying, “What is this thing that you are doing? Are you rebelling against the king?”'),
('LEB', 'Nehemiah', '2', '20', '6', 'Then I answered and said to them, “The God of the heavens himself will let us succeed, and we his servants shall arise and build. But for you there is no share, right, or memorial in Jerusalem.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '3', '1', '1', '<span class=\"verse-title\">Organization of the Work</span>Then Eliashib the high priest and his brothers the priests arose and rebuilt the Sheep Gate. They consecrated it and erected its doors. They consecrated it up to the Tower of the Hundred and up to the Tower of Hananel.'),
('LEB', 'Nehemiah', '3', '2', '1', 'And <span class=\"idiom\">next to him</span><span class=\"note\">“at his hand”</span>the men of Jericho built, and <span class=\"idiom\">next to him</span><span class=\"note\">“at his hand”</span>Zaccur son of Imri built.'),
('LEB', 'Nehemiah', '3', '3', '2', 'The sons of Hassenaah built the Fish Gate. They laid its beams and erected its doors, its bolts, and its bars.'),
('LEB', 'Nehemiah', '3', '4', '2', '<span class=\"idiom\">Next to them</span><span class=\"note\">“At their hand”</span>Meremoth son of Uriah, son of Hakkoz, repaired. <span class=\"idiom\">Next to them</span><span class=\"note\">“At their hand”</span>Meshullam son of Berekiah, son of Meshezabel, repaired. <span class=\"idiom\">Next to them</span><span class=\"note\">“At their hand”</span>Zadok son of Baana repaired.'),
('LEB', 'Nehemiah', '3', '5', '2', '<span class=\"idiom\">Next to them</span><span class=\"note\">“At their hand”</span>the Tekoites repaired, but their nobles did not put their neck to the work of their lord.'),
('LEB', 'Nehemiah', '3', '6', '3', 'Jehoiada the son of Paseah and Meshullam repaired the old Yeshanah Gate. They laid its beams and erected its doors, its bolts, and its bars.'),
('LEB', 'Nehemiah', '3', '7', '3', '<span class=\"idiom\">Next to them</span><span class=\"note\">“At their hand”</span>Melatiah the Gibeonite and Jadon the Meronothite, the men of Gibeon and Mizpah who were under the rule of the governor of <span class=\"supplied\">the province</span> Beyond the River, repaired.'),
('LEB', 'Nehemiah', '3', '8', '3', '<span class=\"idiom\">Next to him</span><span class=\"note\">“At his hand”</span>Uzziel son of Harhaiah (goldsmiths) repaired. <span class=\"idiom\">Next to him</span><span class=\"note\">“At his hand”</span>Hananiah son of the perfume-makers repaired. They restored Jerusalem up to the Broad Wall.'),
('LEB', 'Nehemiah', '3', '9', '3', '<span class=\"idiom\">Next to them</span><span class=\"note\">“At their hand”</span>Rephaiah son of Hur, commander of half the district of Jerusalem, repaired.'),
('LEB', 'Nehemiah', '3', '10', '3', '<span class=\"idiom\">Next to them</span><span class=\"note\">“At their hand”</span>Jedaiah son of Harumaph repaired opposite his house. <span class=\"idiom\">Next to him</span><span class=\"note\">“At his hand”</span>Hattush son of Hashabneiah repaired.'),
('LEB', 'Nehemiah', '3', '11', '4', 'Malkijah son of Harim and Hasshub son of Pahath-Moab repaired another section and the Tower of the Ovens.'),
('LEB', 'Nehemiah', '3', '12', '4', '<span class=\"idiom\">Next to him</span><span class=\"note\">“At his hand”</span>Shallum son of Hallohesh, commander of half of the district of Jerusalem, repaired with his daughters.'),
('LEB', 'Nehemiah', '3', '13', '5', 'Hanun and the inhabitants of Zanoah repaired the Valley Gate. They rebuilt it and erected its doors, its bolts, and its bars, and a thousand cubits of the wall up to the Dung Gate.'),
('LEB', 'Nehemiah', '3', '14', '6', 'Malkijah son of Recab, commander of the district of Beth-haccherem, repaired the Dung Gate. He rebuilt it and erected its doors, its bolts, and its bars.'),
('LEB', 'Nehemiah', '3', '15', '7', 'Shallun son of Col-Hozeh, the commander of the district of Mizpah, repaired the Fountain Gate. He rebuilt it and covered it and erected its doors, its bolts, its bars, and <span class=\"supplied\">he built</span> the wall of the Pool of Shelah of the king’s garden, right up to the steps going down from the city of David.'),
('LEB', 'Nehemiah', '3', '16', '7', 'After him Nehemiah son of Azbuk, commander of half of the district of Beth Zur, repaired up to <span class=\"supplied\">a point</span> opposite the burial sites of David, and up to the artificial pool and to the house of the mighty warriors.'),
('LEB', 'Nehemiah', '3', '17', '8', 'After him the Levites repaired; Rehum son of Bani, and next to him Hashabiah, commander of half of the district of Keilah, repaired his district.'),
('LEB', 'Nehemiah', '3', '18', '8', 'After him their brothers repaired: Bavvai son of Henadad, commander of half of the district of Keilah,'),
('LEB', 'Nehemiah', '3', '19', '8', '<span class=\"idiom\">next to him</span><span class=\"note\">“at his hand”</span>Ezer son of Jeshua, commander of Mizpah, repaired a second section of a wall opposite of the ascent of the armory at the angle.'),
('LEB', 'Nehemiah', '3', '20', '8', 'After him Baruch son of Zabbai zealously repaired a second section of a wall from the angle up to the doorway of the house of Eliashib the high priest.'),
('LEB', 'Nehemiah', '3', '21', '8', 'After him Meremoth son of Uriah, son of Hakkoz, repaired a second section of a wall from the doorway of the house of Eliashib up to the end of the house of Eliashib.'),
('LEB', 'Nehemiah', '3', '22', '9', 'After him the priests, men from the vicinity, repaired.'),
('LEB', 'Nehemiah', '3', '23', '9', 'After them Benjamin and Hasshub repaired opposite their house. After them Azariah son of Maaseiah, son of Ananiah, repaired beside his house.'),
('LEB', 'Nehemiah', '3', '24', '9', 'After him Binnui son of Henadad repaired a second section of a wall from the house of Azariah up to the angle up to the corner.'),
('LEB', 'Nehemiah', '3', '25', '9', 'Palal son of Uzai <span class=\"supplied\">repaired</span> opposite the Angle at the tower that juts out from the upper house of the king, at the courtyard of the guard. After him Pedaiah son of Parosh'),
('LEB', 'Nehemiah', '3', '26', '9', 'and the temple servants who were living on Ophel <span class=\"supplied\">repaired</span> up to opposite the Water Gate on the east and the projecting tower.'),
('LEB', 'Nehemiah', '3', '27', '9', 'After him the Tekoites repaired a second section of a wall opposite the projecting tower that goes out as far as the wall of Ophel.'),
('LEB', 'Nehemiah', '3', '28', '10', 'Above the Horse Gate the priests repaired, each one opposite his house.'),
('LEB', 'Nehemiah', '3', '29', '10', 'After them Zadok son of Immer repaired opposite his house. After him Shemaiah son of Shecaniah, keeper of the East Gate, repaired.'),
('LEB', 'Nehemiah', '3', '30', '10', 'After him Hananiah son of Shelemiah and Hanun the sixth son of Zalaph repaired another section. After him Meshullam son of Berekiah repaired <span class=\"supplied\">the wall</span> opposite his room.'),
('LEB', 'Nehemiah', '3', '31', '10', 'After him Malkijah, <span class=\"idiom\">one of the goldsmiths</span>,<span class=\"note\">“the son of the goldsmith”</span>repaired up to the house of the temple servants and the merchants, opposite the Enrollment Gate and up to the upper room of the corner.'),
('LEB', 'Nehemiah', '3', '32', '10', 'Between the upper room of the corner to the Sheep Gate the goldsmiths and merchants repaired.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '4', '1', '1', '<span class=\"verse-title\">Opposition Begins</span><span class=\"note\">Nehemiah 4:1–23 in the English Bible is 3:33–4:17 in the Hebrew Bible</span>Now it happened when Sanballat heard that we were building the wall, <span class=\"supplied\">he</span> became angry and greatly provoked, and he mocked the Jews.'),
('LEB', 'Nehemiah', '4', '2', '1', 'Then he said before his brothers and the army of Samaria, “What are the feeble Jews doing? Will they restore <span class=\"supplied\">these things</span> for themselves? Will they sacrifice? Will they finish it in a day? Will they revive the stones from the piles of rubble—even those burned up?”'),
('LEB', 'Nehemiah', '4', '3', '2', 'Tobiah the Ammonite was beside him and said, “Their wall of stone that they are building would break down if a fox went on it!”'),
('LEB', 'Nehemiah', '4', '4', '3', 'Hear, our God, for we are despised. Turn their scorn on their head and give them over to plunder in the land of captivity.'),
('LEB', 'Nehemiah', '4', '5', '3', 'Do not cover their guilt, and do not let their sin be blotted out from before you. They have <span class=\"idiom\">provoked the builders to anger</span>.<span class=\"note\">“provoked anger before the builders”</span>'),
('LEB', 'Nehemiah', '4', '6', '4', 'So we rebuilt the wall, and all of the wall was joined up to half <span class=\"supplied\">its height</span>. For the people had a heart to do <span class=\"supplied\">it</span>.'),
('LEB', 'Nehemiah', '4', '7', '6', '<span class=\"verse-title\">Opposition Stopped</span>Now when Sanballat, Tobiah, the Arabs, the Ammonites, and the Ashdodites heard that the restoration of the walls of Jerusalem were going forward and the gaps were being closed, they were very angry.'),
('LEB', 'Nehemiah', '4', '8', '6', 'So all of them plotted together to come fight against Jerusalem and to make trouble for it.'),
('LEB', 'Nehemiah', '4', '9', '6', 'So we prayed to our God and set up a guard against them day and night.'),
('LEB', 'Nehemiah', '4', '10', '7', 'But Judah said, “The strength of the carriers is failing, and there is too much dirt, and we are not able to build at the wall.”'),
('LEB', 'Nehemiah', '4', '11', '7', 'Then our enemies said, “They will not know nor see until we come upon them and will kill them and stop the work.”'),
('LEB', 'Nehemiah', '4', '12', '7', 'When the Jews who lived beside them came, they said to us ten times, “From all of the places where they live, <span class=\"supplied\">they will come up</span> against us.”'),
('LEB', 'Nehemiah', '4', '13', '7', 'I stationed the people behind the deepest part of the wall in the open places according to their families, with their swords, spears, and bows.'),
('LEB', 'Nehemiah', '4', '14', '7', 'And I looked, got up, and said to the nobles, prefects, and the rest of the people, “Do not be afraid of them. Remember the Lord, who is great and awesome, and fight for your brothers, your sons, your daughters, your wives, and your houses.”'),
('LEB', 'Nehemiah', '4', '15', '8', 'It happened when our enemies heard that their plan was known to us, that God had frustrated <span class=\"supplied\">it</span>, and we all returned to the wall—each to his work.'),
('LEB', 'Nehemiah', '4', '16', '8', 'From that day, half of my servants were working on craftsmanship, half were holding spears, small shields, bows, and breastplates. The commanders were behind the whole house of Judah.'),
('LEB', 'Nehemiah', '4', '17', '8', 'The ones who were building the wall and the ones <span class=\"idiom\">who carried the materials</span><span class=\"note\">“who carried the burden”</span>were carrying in one hand while doing the task, and with the other hand were grasping a weapon.'),
('LEB', 'Nehemiah', '4', '18', '8', 'Each of the builders had his sword tied to his side while building. And the man who sounded the trumpet was beside me.'),
('LEB', 'Nehemiah', '4', '19', '8', 'I said to the nobles, to the prefects, and to the rest of the people, “The work is great and widespread, and we are spread out over the wall far from each other.'),
('LEB', 'Nehemiah', '4', '20', '8', 'Wherever you hear the sound of the trumpet, come together to us there. Our God will fight for us.”'),
('LEB', 'Nehemiah', '4', '21', '9', 'So we labored at the work, and half of them were holding the spears from dawn until the stars came out.'),
('LEB', 'Nehemiah', '4', '22', '9', 'At the time I also said to the people, “Let each man and his servant spend the night inside Jerusalem, so that they will be a guard for us in the night and work in the day.”'),
('LEB', 'Nehemiah', '4', '23', '9', 'So neither I nor my brothers nor my young men nor the men of the guard who were behind me took off our clothes. Each one <span class=\"supplied\">kept</span> his weapon <span class=\"supplied\">even</span> in the water.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '5', '1', '1', '<span class=\"verse-title\">Nehemiah Deals with Strife</span>Now there was a great cry of distress of the people and of their wives <span class=\"supplied\">against</span> their Jewish brothers.'),
('LEB', 'Nehemiah', '5', '2', '1', 'There were those who were saying, “Our sons and daughters, we are many. We must get grain so that we may eat and live.”'),
('LEB', 'Nehemiah', '5', '3', '1', 'There were also those saying, “We have pledged our fields and our vineyards and our houses so that we can get grain in the famine.”'),
('LEB', 'Nehemiah', '5', '4', '1', 'And there were those who were saying, “We have borrowed money on our fields and our vineyards for the tax of the king.'),
('LEB', 'Nehemiah', '5', '5', '1', 'Now our flesh is like the flesh of our brothers, our sons are like their sons. Look, we are subduing our sons and our daughters to be slaves, and there are some from our daughters being molested. <span class=\"idiom\">We are powerless</span>,<span class=\"note\">“There is no power in our hand”</span>and our fields and vineyards <span class=\"supplied\">belong</span> to others.”'),
('LEB', 'Nehemiah', '5', '6', '2', 'I was very angry when I heard their shouts and these words.'),
('LEB', 'Nehemiah', '5', '7', '2', 'I thought over this in my heart, and then I quarreled with the nobles and the prefects. I said to them, “You yourselves are taking interest from your own brother!” So I called the great assembly against them,'),
('LEB', 'Nehemiah', '5', '8', '2', 'and I said to them: “We ourselves have bought back our brothers the Jews who were sold to the nations as we were able. But now you yourselves have sold your brothers so they may be sold to us!” They were silent and could not find a word <span class=\"supplied\">to say</span>.'),
('LEB', 'Nehemiah', '5', '9', '3', 'So I said, “The thing that you are doing is not good. Should you not walk in the fear of our God <span class=\"supplied\">to prevent</span> the disgrace from the nations, our enemies?'),
('LEB', 'Nehemiah', '5', '10', '3', 'Also, I and my brothers and my servants are lending them money and grain. Please stop <span class=\"supplied\">taking</span> this interest.'),
('LEB', 'Nehemiah', '5', '11', '3', 'Please restore to them this day their fields, their vineyards, their olive groves, their houses, and the interest on the money, the grain, the grape juice, and the olive oil that you have been taking from them.”'),
('LEB', 'Nehemiah', '5', '12', '3', 'So they said, “We will restore it and will not request <span class=\"supplied\">anything more</span>. So we will do as you say.” Then I called the priests and made them take an oath to do this promise.'),
('LEB', 'Nehemiah', '5', '13', '3', 'I also shook out my garment and said, “This is how God will shake out everyone from his house who will not keep this promise. So this is how his possessions will be shaken out and emptied.” And all the assembly said, “Amen!” And they praised Adonai, and the people kept this promise.'),
('LEB', 'Nehemiah', '5', '14', '5', '<span class=\"verse-title\">Nehemiah Denies His Allotment</span>Moreover, from the appointed day I was made their governor in the land of Judah, from the twentieth year until the thirty-second year of King Artaxerxes—twelve years. My brothers and I did not eat the food <span class=\"supplied\">allowance</span> of the governor.'),
('LEB', 'Nehemiah', '5', '15', '5', 'The former governors who were before me laid burdens on the people, and they took food and wine from them, besides forty shekels. Also, their servants controlled the people, but I did not do so because of the fear of God.'),
('LEB', 'Nehemiah', '5', '16', '5', 'I also devoted myself to the work of this wall, and we did not buy land. All of my servants were gathered for the work.'),
('LEB', 'Nehemiah', '5', '17', '5', 'One hundred and fifty men, prefects and Jews, and those who came to us from the nations around us, <span class=\"supplied\">were</span> at my table.'),
('LEB', 'Nehemiah', '5', '18', '5', 'Now what was prepared each day for me was one ox, six choice sheep, and birds. And every ten days all <span class=\"supplied\">kinds of</span> wine were made. But for this I did not demand the food <span class=\"supplied\">allowance</span> of the governor because the slavery was too heavy on this people.'),
('LEB', 'Nehemiah', '5', '19', '5', 'Remember me for good, my God, all that I have done for this people.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '6', '1', '1', '<span class=\"verse-title\">Enemies Foiled</span>Now when it was reported to Sanballat, Tobiah, Geshem the Arab, and to the rest of our enemies that I had built the wall and that no gap was left in it—though up to that time I had not erected doors in the gates—'),
('LEB', 'Nehemiah', '6', '2', '1', 'Sanballat and Geshem sent to me, saying, “Come and let us meet together in <span class=\"supplied\">one of</span> the villages in the plain of Ono.” But they planned to do evil to me.'),
('LEB', 'Nehemiah', '6', '3', '1', 'So I sent messengers to them, saying, “I am doing a great work and I am not able to come down. Why should the work stop while I leave it and come down to you all?”'),
('LEB', 'Nehemiah', '6', '4', '1', 'And they sent a message to me four times like this, and I returned an answer like this to them.'),
('LEB', 'Nehemiah', '6', '5', '1', 'And Sanballat sent his servant with an open letter, <span class=\"supplied\">another</span> word like this to me a fifth time, in his hand.'),
('LEB', 'Nehemiah', '6', '6', '1', 'In it was written, “It has been reported among the nations, and Gashmu also is saying it, that you and the Jews are considering rebellion. Therefore, truly you are building the wall and you are becoming their king, according to these words.'),
('LEB', 'Nehemiah', '6', '7', '1', 'You have also set up prophets to proclaim in Jerusalem concerning you, saying, ‘<span class=\"supplied\">There is</span> a king in Judah.’ And now it will be proclaimed to the king according to these words. Now, come and we will plan together.”'),
('LEB', 'Nehemiah', '6', '8', '1', 'So I sent to him saying, “None of these words you have spoken has happened. You are indeed saying <span class=\"supplied\">things</span> created in your own mind”—'),
('LEB', 'Nehemiah', '6', '9', '1', 'for all of them <span class=\"supplied\">sought</span> to frighten us, saying, “their hands will not do the work.” And now, <span class=\"supplied\">God</span>, strengthen my hands.'),
('LEB', 'Nehemiah', '6', '10', '2', 'Now I went into the house of Shemaiah son of Delaiah, son of Mehetabel, who was confined <span class=\"supplied\">at home</span>, and he said, “Let us meet in the house of God, inside the temple, and let us close the doors of the temple; for they are coming to kill you—during the night they are coming to kill you.”'),
('LEB', 'Nehemiah', '6', '11', '2', 'But I said, “Should a man like me run away? And would a man like me go into the temple so that he can save his life? I will not go in!”'),
('LEB', 'Nehemiah', '6', '12', '2', 'Then I look and realized God had not sent him; rather, he had spoken the prophecy against me <span class=\"supplied\">because</span> Tobiah and Sanballat had hired him.'),
('LEB', 'Nehemiah', '6', '13', '2', 'For this reason he was hired: to frighten <span class=\"supplied\">me</span> so that I would act and sin, so that they would have a bad report so they could taunt me.'),
('LEB', 'Nehemiah', '6', '14', '2', 'Remember, O my God, Tobiah and Sanballat according to their works, and also Noadiah the prophetess, and the remainder of the prophets who were frightening me.'),
('LEB', 'Nehemiah', '6', '15', '4', '<span class=\"verse-title\">The Wall is Completed</span>So the wall was finished on the twenty-fifth day of Elul, in fifty-two days.'),
('LEB', 'Nehemiah', '6', '16', '4', 'When our enemies heard of this, all of the nations surrounding us were afraid and <span class=\"idiom\">lost their confidence</span>.<span class=\"note\">“fell much in their eyes”</span>They knew that this work had been done with <span class=\"supplied\">the help of</span> our God.'),
('LEB', 'Nehemiah', '6', '17', '4', 'Also, in those days the nobles of Judah increasingly sent their letters to Tobiah, and <span class=\"supplied\">letters</span> from Tobiah returned to them.'),
('LEB', 'Nehemiah', '6', '18', '4', 'For many in Judah were bound by oath to him because he was the son-in-law of Shecaniah son of Arah. His son Jehohanan took as a wife the daughter of Meshullam son of Berekiah.'),
('LEB', 'Nehemiah', '6', '19', '4', 'They also were speaking of his good deeds in my presence, and they were sending my words out to him. Tobiah sent letters to intimidate me.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '7', '1', '0', 'Now when the wall had been built and I had erected the doors and appointed the gatekeepers, singers, and the Levites,'),
('LEB', 'Nehemiah', '7', '2', '0', 'I gave command over Jerusalem to my brother Hanani and Hananiah the commander of the citadel. For he was a faithful man and feared God more than many.'),
('LEB', 'Nehemiah', '7', '3', '0', 'I said to them, “Do not open the gates of Jerusalem until the sun is hot. While they are standing guard let them shut and fasten the doors. And appoint guards from the inhabitants of Jerusalem, one at his post and another opposite his house.”'),
('LEB', 'Nehemiah', '7', '4', '0', 'The city <span class=\"supplied\">was</span> widespread and large, but the people in it were few and no houses were rebuilt.'),
('LEB', 'Nehemiah', '7', '5', '2', '<span class=\"verse-title\">Lists of the Exiles Who Returned</span>Then my God put into my heart to assemble the nobles, the prefects, and the people to be enrolled. I found the book of the genealogy of those who first came back, and I found <span class=\"supplied\">this</span> written upon it:'),
('LEB', 'Nehemiah', '7', '6', '3', 'These are the people of the province who came up from captivity of the exiles whom Nebuchadnezzar king of Babylon had carried into exile. They returned to Jerusalem and to Judah, each one to his city.'),
('LEB', 'Nehemiah', '7', '7', '3', 'These came with Zerubbabel, Joshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, Baanah.'),
('LEB', 'Nehemiah', '7', '8', '4', 'The number of the men of the people of Israel:'),
('LEB', 'Nehemiah', '7', '9', '4', 'the descendants<span class=\"note\">Or “sons”</span>of Parosh, two thousand one hundred and seventy-two.'),
('LEB', 'Nehemiah', '7', '10', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Shephatiah, three hundred and seventy-two.'),
('LEB', 'Nehemiah', '7', '11', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Arah, six hundred and fifty-two.'),
('LEB', 'Nehemiah', '7', '12', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Pahath-Moab, of the descendants<span class=\"note\">Or “sons”</span>of Jeshua and Joab, two thousand eight hundred and eighteen.'),
('LEB', 'Nehemiah', '7', '13', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Elam, one thousand two hundred and fifty-four.'),
('LEB', 'Nehemiah', '7', '14', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Zattu, eight hundred and forty-five.'),
('LEB', 'Nehemiah', '7', '15', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Zaccai, seven hundred and sixty.'),
('LEB', 'Nehemiah', '7', '16', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Binnui, six hundred and forty-eight.'),
('LEB', 'Nehemiah', '7', '17', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Bebai, six hundred and twenty-eight.'),
('LEB', 'Nehemiah', '7', '18', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Azgad, two thousand three hundred and twenty-two.'),
('LEB', 'Nehemiah', '7', '19', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Adonikam, six hundred and sixty-seven.'),
('LEB', 'Nehemiah', '7', '20', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Bigvai, two thousand and sixty-seven.'),
('LEB', 'Nehemiah', '7', '21', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Adin, six hundred and fifty-five.'),
('LEB', 'Nehemiah', '7', '22', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Ater, <span class=\"supplied\">namely</span> of Hezekiah, ninety-eight.'),
('LEB', 'Nehemiah', '7', '23', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Hashum, three hundred and twenty-eight.'),
('LEB', 'Nehemiah', '7', '24', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Bezai, three hundred and twenty-four.'),
('LEB', 'Nehemiah', '7', '25', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Hariph, one hundred and twelve.'),
('LEB', 'Nehemiah', '7', '26', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Gibeon, ninety-five.'),
('LEB', 'Nehemiah', '7', '27', '4', 'The men of Bethlehem and Netophah, one hundred and eighty-eight.'),
('LEB', 'Nehemiah', '7', '28', '4', 'The men of Anathoth, one hundred and twenty-eight.'),
('LEB', 'Nehemiah', '7', '29', '4', 'The men of Beth-azmaveth, forty-two.'),
('LEB', 'Nehemiah', '7', '30', '4', 'The men of Kiriath-Jearim, Kephirah, and Beeroth, seven hundred and forty-three.'),
('LEB', 'Nehemiah', '7', '31', '4', 'The men of Ramah and Geba, six hundred and twenty-one.'),
('LEB', 'Nehemiah', '7', '32', '4', 'The men of Micmash, one hundred and twenty-two.'),
('LEB', 'Nehemiah', '7', '33', '4', 'The men of Bethel and Ai, one hundred and twenty-three.'),
('LEB', 'Nehemiah', '7', '34', '4', 'The men of the other Nebo, fifty-two.'),
('LEB', 'Nehemiah', '7', '35', '4', 'The people<span class=\"note\">Or “sons”</span>of the other Elam, one thousand two hundred and fifty-four.'),
('LEB', 'Nehemiah', '7', '36', '4', 'The people<span class=\"note\">Or “sons”</span>of Harim, three hundred and twenty.'),
('LEB', 'Nehemiah', '7', '37', '4', 'The people<span class=\"note\">Or “sons”</span>of Jericho, three hundred and forty-five.'),
('LEB', 'Nehemiah', '7', '38', '4', 'The people<span class=\"note\">Or “sons”</span>of Lod, Hadid, and Ono, seven hundred and twenty-one.'),
('LEB', 'Nehemiah', '7', '39', '5', 'The priests: The descendants<span class=\"note\">Or “sons”</span>of Jedaiah, of the house of Jeshua, nine hundred and seventy-three.'),
('LEB', 'Nehemiah', '7', '40', '5', 'The descendants<span class=\"note\">Or “sons”</span>of Immer, one thousand and fifty-two.'),
('LEB', 'Nehemiah', '7', '41', '5', 'The descendants<span class=\"note\">Or “sons”</span>of Pashhur, one thousand two hundred and forty-seven.'),
('LEB', 'Nehemiah', '7', '42', '5', 'The descendants<span class=\"note\">Or “sons”</span>of Harim, one thousand and seventeen.'),
('LEB', 'Nehemiah', '7', '43', '6', 'The Levites: the descendants<span class=\"note\">Or “sons”</span>of Jeshua, <span class=\"supplied\">namely</span> of Kadmiel of the descendants<span class=\"note\">Or “sons”</span>of Hodaviah, seventy-four.'),
('LEB', 'Nehemiah', '7', '44', '6', 'The singers: the descendants<span class=\"note\">Or “sons”</span>of Asaph, one hundred and forty-eight.'),
('LEB', 'Nehemiah', '7', '45', '6', 'The gatekeepers: the descendants<span class=\"note\">Or “sons”</span>of Shallum, the descendants<span class=\"note\">Or “sons”</span>of Ater, the descendants<span class=\"note\">Or “sons”</span>of Talmon, the descendants<span class=\"note\">Or “sons”</span>of Akkub, the descendants<span class=\"note\">Or “sons”</span>of Hatita, the descendants<span class=\"note\">Or “sons”</span>of Shobai, one hundred and thirty-eight.'),
('LEB', 'Nehemiah', '7', '46', '7', 'The temple servants: the descendants<span class=\"note\">Or “sons”</span>of Ziha, the descendants<span class=\"note\">Or “sons”</span>of Hasupha, the descendants<span class=\"note\">Or “sons”</span>of Tabbaoth,'),
('LEB', 'Nehemiah', '7', '47', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Keros, the descendants<span class=\"note\">Or “sons”</span>of Siaha, the descendants<span class=\"note\">Or “sons”</span>of Padon,'),
('LEB', 'Nehemiah', '7', '48', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Lebanah, the descendants<span class=\"note\">Or “sons”</span>of Hagaba, the descendants<span class=\"note\">Or “sons”</span>of Shalmai,'),
('LEB', 'Nehemiah', '7', '49', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Hanan, the descendants<span class=\"note\">Or “sons”</span>of Giddel, the descendants<span class=\"note\">Or “sons”</span>of Gahar,'),
('LEB', 'Nehemiah', '7', '50', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Reaiah, the descendants<span class=\"note\">Or “sons”</span>of Rezin, the descendants<span class=\"note\">Or “sons”</span>of Nekoda,'),
('LEB', 'Nehemiah', '7', '51', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Gazzam, the descendants<span class=\"note\">Or “sons”</span>of Uzza, the descendants<span class=\"note\">Or “sons”</span>of Paseah,'),
('LEB', 'Nehemiah', '7', '52', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Besai, the descendants<span class=\"note\">Or “sons”</span>of Meunim, the descendants<span class=\"note\">Or “sons”</span>of Nephushesim,'),
('LEB', 'Nehemiah', '7', '53', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Bakbuk, the descendants<span class=\"note\">Or “sons”</span>of Hakupha, the descendants<span class=\"note\">Or “sons”</span>of Harhur,'),
('LEB', 'Nehemiah', '7', '54', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Bazlith, the descendants<span class=\"note\">Or “sons”</span>of Mehida, the descendants<span class=\"note\">Or “sons”</span>of Harsha,'),
('LEB', 'Nehemiah', '7', '55', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Barkos, the descendants<span class=\"note\">Or “sons”</span>of Sisera, the descendants<span class=\"note\">Or “sons”</span>of Temah,'),
('LEB', 'Nehemiah', '7', '56', '7', 'the descendants<span class=\"note\">Or “sons”</span>of Neziah, the descendants<span class=\"note\">Or “sons”</span>of Hatipha.'),
('LEB', 'Nehemiah', '7', '57', '8', 'The descendants<span class=\"note\">Or “sons”</span>of Solomon’s servants: the descendants<span class=\"note\">Or “sons”</span>of Sotai, the descendants<span class=\"note\">Or “sons”</span>of Sophereth, the descendants<span class=\"note\">Or “sons”</span>of Perida,'),
('LEB', 'Nehemiah', '7', '58', '8', 'the descendants<span class=\"note\">Or “sons”</span>of Jaala, the descendants<span class=\"note\">Or “sons”</span>of Darkon, the descendants<span class=\"note\">Or “sons”</span>of Giddel,'),
('LEB', 'Nehemiah', '7', '59', '8', 'the descendants<span class=\"note\">Or “sons”</span>of Shephatiah, the descendants<span class=\"note\">Or “sons”</span>of Hattil, the descendants<span class=\"note\">Or “sons”</span>of Pochereth-Hazzebaim, the descendants<span class=\"note\">Or “sons”</span>of Amon.'),
('LEB', 'Nehemiah', '7', '60', '9', 'All the temple servants and the descendants<span class=\"note\">Or “sons”</span>of Solomon’s servants were three hundred and ninety-two.'),
('LEB', 'Nehemiah', '7', '61', '10', 'These were the ones who came up from Tel-melah, Tel-harsha, Cherub, Addon, and Immer, but they were not able to prove their ancestral houses or their descent, whether they were from Israel:'),
('LEB', 'Nehemiah', '7', '62', '10', 'the descendants<span class=\"note\">Or “sons”</span>of Delaiah, the descendants<span class=\"note\">Or “sons”</span>of Tobiah, the descendants<span class=\"note\">Or “sons”</span>of Nekoda, six hundred and forty-two.'),
('LEB', 'Nehemiah', '7', '63', '10', 'And from the priests: the descendants<span class=\"note\">Or “sons”</span>of Hobaiah, the descendants<span class=\"note\">Or “sons”</span>of Hakkoz, the descendants<span class=\"note\">Or “sons”</span>of Barzillai (who had taken as a wife from the daughters of Barzillai the Gileadite and was called by their name).'),
('LEB', 'Nehemiah', '7', '64', '10', 'These sought their record among those enrolled in the genealogy, but it was not found there, so they were excluded as unclean from the priesthood.'),
('LEB', 'Nehemiah', '7', '65', '10', 'So the governor said to them that they could not eat the most holy food until a priest could come with Urim and Thummim.'),
('LEB', 'Nehemiah', '7', '66', '11', 'All of the assembly together was forty-two thousand three hundred and sixty,'),
('LEB', 'Nehemiah', '7', '67', '11', 'besides their servants and female slaves—these were seven thousand three hundred and thirty-seven. And the male and female singers were two hundred and forty-five,<span class=\"note\">After this verse, some versions add verse 68: “Their horses were seven hundred and thirty-six; their mules two hundred and forty-five”; compare Ezra 2:66</span>'),
('LEB', 'Nehemiah', '7', '69', '11', '<span class=\"note\">Nehemiah 7:69–73 in the English Bible is 7:68–72 in the Hebrew Bible</span><span class=\"supplied\">there were</span> four hundred and thirty-five camels and six thousand seven hundred and twenty male donkeys.'),
('LEB', 'Nehemiah', '7', '70', '12', 'Now some from the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>gave to the work. The governor gave to the storehouse one thousand darics of gold, fifty basins, and five hundred and thirty priestly tunics.'),
('LEB', 'Nehemiah', '7', '71', '12', 'Now some of the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>gave to the storehouse of the work twenty thousand gold darics and two thousand two hundred silver minas.'),
('LEB', 'Nehemiah', '7', '72', '12', 'And what the rest of the people gave was twenty thousand darics of gold, and two thousand silver minas, and sixty-seven priestly tunics.'),
('LEB', 'Nehemiah', '7', '73', '13', 'So the priests, the Levites, the gatekeepers, the singers, some of the people, the temple servants, and all Israel settled in their cities. When the seventh month came, the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span><span class=\"supplied\">were</span> in their cities.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '8', '1', '1', '<span class=\"verse-title\">Ezra Reads the Law to the People</span>All of the people gathered as one to the public square before the Water Gate. They asked Ezra the scribe to bring the book of the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>of Moses that Adonai had commanded Israel.'),
('LEB', 'Nehemiah', '8', '2', '1', 'So Ezra the priest brought the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>before the assembly for <span class=\"supplied\">each</span> man and woman to hear with understanding, on the first day of the seventh month.'),
('LEB', 'Nehemiah', '8', '3', '1', 'He read from it facing the public square before the Water Gate from dawn until noon that day, opposite the men, women, and those with understanding. The ears of all the people <span class=\"supplied\">were attentive</span> to the book of the law.<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>'),
('LEB', 'Nehemiah', '8', '4', '1', 'Then Ezra the scribe stood on a wooden podium that had been made for the occasion. And beside him stood Mattithiah, Shema, Anaiah, Uriah, Hilkiah, and Maaseiah on his right. On his left <span class=\"supplied\">was</span> Pedaiah, Mishael, Malkijah, Hashum, Hashbaddanah, Zechariah, and Meshullam.'),
('LEB', 'Nehemiah', '8', '5', '1', 'Ezra opened the book in the sight of all the people, because he was above all of the people. When he opened it all the people stood up.'),
('LEB', 'Nehemiah', '8', '6', '1', 'Then Ezra blessed Adonai the great God, and all of the people answered, “Amen! Amen!” while lifting their hands. Then they bowed down and worshiped Adonai <span class=\"supplied\">with their</span> noses to the ground.'),
('LEB', 'Nehemiah', '8', '7', '1', 'And Jeshua, Bani, Sherebiah, Jamin, Akkub, Shabbethai, Hodiah, Maaseiah, Kelita, Azariah, Jozabad, Hanan, Pelaiah, and the Levites were teaching the people from the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>while the people were in their places.'),
('LEB', 'Nehemiah', '8', '8', '1', 'So they read the book from the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>of God, making it clear and giving the meaning so that they could understand the reading.'),
('LEB', 'Nehemiah', '8', '9', '2', 'Nehemiah the governor, Ezra the priest and scribe, and the Levites who taught the people said to all of the people, “This day is holy to Adonai your God. Do not mourn nor weep.” For all of the people wept when they heard the words of the law.<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>'),
('LEB', 'Nehemiah', '8', '10', '2', 'Then he said to them, “Go, eat festive food and drink sweet drinks, and send a share to those for whom nothing is prepared; for this day is holy to our lord. Do not be grieved because the joy of Adonai is your refuge.”'),
('LEB', 'Nehemiah', '8', '11', '2', 'So the Levites silenced all of the people, saying, “Silence, for this day is holy. Do not be grieved.”'),
('LEB', 'Nehemiah', '8', '12', '2', 'All of the people went to eat, to drink, to send a share, and to have great joy because they understood the words that they had made known to them.'),
('LEB', 'Nehemiah', '8', '13', '4', '<span class=\"verse-title\">Festival of Booths</span>On the second day the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>of all the people, the priests, and the Levites gathered together to Ezra the scribe to study the words of the law.<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>'),
('LEB', 'Nehemiah', '8', '14', '4', 'They found written in the law,<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>which Adonai had commanded by the hand of Moses, that the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span>should live in booths during the festival of the seventh month,'),
('LEB', 'Nehemiah', '8', '15', '4', 'and that they should proclaim and give voice in all of their cities in Jerusalem, saying, “Go out to the hill and bring olive tree branches, olive oil wood branches, myrtle shrub branches, palm tree branches, and other leafy tree branches to make booths, as it is written.”'),
('LEB', 'Nehemiah', '8', '16', '4', 'So the people went out and brought them and made booths for themselves, each on his roof, in their courtyards, in the courtyards of the house of God, in the public square of the Water Gate, and in the public square of the Gate of Ephraim.'),
('LEB', 'Nehemiah', '8', '17', '4', 'And all of the assembly of those who returned from captivity made booths and lived in the booths because the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span>had not done it from the days of Jeshua son of Nun until that day. And there was very great joy.'),
('LEB', 'Nehemiah', '8', '18', '4', 'And he read from the scroll of the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>of God day by day from the first day up to the last day. They celebrated the festival for seven days, and on the eighth day there was an assembly according to the rule.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '9', '1', '1', '<span class=\"verse-title\">The Nation Confesses</span>On the twenty-fourth day of this month the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span>gathered in fasting, in sackcloths, and with soil on them.'),
('LEB', 'Nehemiah', '9', '2', '1', 'Those of the seed of Israel separated themselves from all of the foreigners and stood and confessed their sins and the iniquities of their ancestors.<span class=\"note\">Or “fathers”</span>'),
('LEB', 'Nehemiah', '9', '3', '1', 'They stood up in their place and read from the book of the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>of Adonai their God for a fourth part of the day, and for a fourth they were confessing and worshiping Adonai their God.'),
('LEB', 'Nehemiah', '9', '4', '1', 'Then Jeshua, Bani, Kadmiel, Shebaniah, Bunni, Sherebiah, Bani, and Kenani stood on the platform of the Levites and cried out with a loud voice to Adonai their God.'),
('LEB', 'Nehemiah', '9', '5', '1', 'Then the Levites, Jeshua, Kadmiel, Bani, Hashabneiah, Sherebiah, Hodiah, Shebaniah, and Pethahiah said, “Stand up, bless Adonai your God from everlasting until everlasting. Blessed be your glorious name that is being exalted above all blessing and praise!'),
('LEB', 'Nehemiah', '9', '6', '2', '“You alone are Adonai. You alone have made the heavens, the heavens of the heavens, and all of their army, the earth and all that is in it, the waters and all that is in them. You give life to all of them, and the army of the heavens worship you.'),
('LEB', 'Nehemiah', '9', '7', '2', 'You are Adonai, the God who chose Abram and brought him from Ur of the Chaldeans and named him Abraham.'),
('LEB', 'Nehemiah', '9', '8', '2', 'You found his heart faithful before you and made a covenant with him to give the land of the Canaanite, the Hittite, the Amorite, the Perizzite, the Jebusite and the Girgashite—to give <span class=\"supplied\">it</span> to his seed. And you have kept your word because you are righteous.'),
('LEB', 'Nehemiah', '9', '9', '3', '“You saw the misery of our ancestors<span class=\"note\">Or “fathers”</span>in Egypt, and you heard their shout at the Red Sea.'),
('LEB', 'Nehemiah', '9', '10', '3', 'You gave signs and wonders against Pharaoh, all of his servants, and all of the people of his land because you knew that they acted arrogantly against them. You made a name for yourself, as it is this day.'),
('LEB', 'Nehemiah', '9', '11', '3', 'And you divided the sea before them, and they passed through the sea on dry ground, but their pursuers you threw into the depths like a stone into mighty waters.'),
('LEB', 'Nehemiah', '9', '12', '3', 'You led them by day with a column of cloud and with a column of fire by night, to give them light on the way that they were to go.'),
('LEB', 'Nehemiah', '9', '13', '3', 'Then you came down on Mount Sinai and spoke with them from heaven and gave them right judgments and true teachings, good regulations and commandments.'),
('LEB', 'Nehemiah', '9', '14', '3', 'You made known your holy Sabbath to them and gave them commandments, regulations, and law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>by the hand of your servant Moses.'),
('LEB', 'Nehemiah', '9', '15', '3', 'You gave them bread from heaven for their starvation, and you caused water to go out from a rock for their thirst. You told them to go in order to take into possession the land that you have sworn by your hand to give to them.'),
('LEB', 'Nehemiah', '9', '16', '4', '“But they and our ancestors<span class=\"note\">Or “fathers”</span>acted arrogantly and stiffened their neck and did not listen to your commandments.'),
('LEB', 'Nehemiah', '9', '17', '4', 'They refused to listen and did not remember your wonders that you did among them. They stiffened their neck and in their rebellion <span class=\"idiom\">determined</span><span class=\"note\">“they gave head to”</span>to return to their slavery. But you are a God of forgiveness, gracious and compassionate, <span class=\"idiom\">slow to anger</span>,<span class=\"note\">“long of nose”</span>abundant in loyal love, so you did not abandon them.'),
('LEB', 'Nehemiah', '9', '18', '4', 'Even when they made for themselves a molten idol of a calf and said, ‘This is your God who brought you out from Egypt,’ and committed great blasphemies.'),
('LEB', 'Nehemiah', '9', '19', '4', 'But you in your many mercies did not abandon them in the desert. The column of cloud <span class=\"supplied\">that was</span> over them in the day did not cease to leave them on the way, and the column of fire by night <span class=\"supplied\">that</span> gave light to them on the way that they went.'),
('LEB', 'Nehemiah', '9', '20', '4', 'And you gave your good Spirit to instruct them and did not withhold your manna from their mouth and gave them water for their thirst.'),
('LEB', 'Nehemiah', '9', '21', '4', 'Forty years you sustained them in the desert—they were not in need. Their clothing did not wear out and their feet did not swell.'),
('LEB', 'Nehemiah', '9', '22', '4', 'And you gave them kingdoms and nations and allotted them a portion. They took into possession the land of Sihon king of Heshbon and the land of Og king of Bashan.'),
('LEB', 'Nehemiah', '9', '23', '4', 'You made their children<span class=\"note\">Or “sons”</span>numerous like the stars of the heavens and brought them to the land that you told their ancestors<span class=\"note\">Or “fathers”</span>to enter in order to take possession.'),
('LEB', 'Nehemiah', '9', '24', '4', 'So the children<span class=\"note\">Or “sons”</span>went in and took possession of the land. You subdued before them the inhabitants of the land, the Canaanites; you gave them into their hand, and their kings and the nations of the land to do with them according to their pleasure.'),
('LEB', 'Nehemiah', '9', '25', '4', 'And they captured fortified cities and a fertile land and took possession of houses filled with every good thing: hewn cisterns, vineyards, olive groves, and many <span class=\"supplied\">fruit</span> trees. They ate and became full, and they became fat and took delight in your great goodness.'),
('LEB', 'Nehemiah', '9', '26', '5', '“But they rebelled and were rebellious against you and cast your law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>behind their back and killed your prophets, who had warned them to turn back to you, and they did great blasphemies.'),
('LEB', 'Nehemiah', '9', '27', '5', 'Therefore you gave them into the hand of their enemy, and they brought trouble to them. Then in the time of their trouble they cried out to you, and you heard from the heavens, and according to your great compassions, you gave them saviors, and you saved them from the hand of their enemies.'),
('LEB', 'Nehemiah', '9', '28', '5', 'But when they had rest they returned to doing evil before you, and you abandoned them in the hand of their enemies, and they ruled over them. Then they returned and cried out to you, and from the heavens you heard and many times rescued them according to your compassions.'),
('LEB', 'Nehemiah', '9', '29', '5', 'You warned them so that they would return to your law.<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>Yet they acted arrogantly and did not listen to your commandments but sinned against your judgments that a person must do so that they may live. They turned a stubborn shoulder and stiffened their neck and would not listen.'),
('LEB', 'Nehemiah', '9', '30', '5', 'You were patient toward them for many years, and you have warned them by your spirit through the hand of your prophets, but they did not listen. So you gave them into the hand of the nations of the lands.'),
('LEB', 'Nehemiah', '9', '31', '5', 'But in your great compassions you did not put an end to them, and you did not abandon them. For you are a gracious and compassionate God.'),
('LEB', 'Nehemiah', '9', '32', '6', '“And now our God, the great, mighty, and awesome God who keeps <span class=\"supplied\">his</span> covenant and loyal love, do not belittle in your presence all of the hardship that is found in us, our kings, our officials, our priests, our prophets, our ancestors,<span class=\"note\">Or “fathers”</span>and all of our people, from the days of the kings of Assyria until this day.'),
('LEB', 'Nehemiah', '9', '33', '6', 'You are righteous in everything that has come on us, for you dealt faithfully, and we have acted wickedly.'),
('LEB', 'Nehemiah', '9', '34', '6', 'Our kings, our officials, our priests, and our ancestors<span class=\"note\">Or “fathers”</span>did not keep your law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>and did not listen to your commandments and statutes that you declared to them.'),
('LEB', 'Nehemiah', '9', '35', '6', 'And in their kingdom and in the greatness you gave to them, and in the wide and fertile land that you gave before them, they did not serve you and did not turn from their evil deeds.'),
('LEB', 'Nehemiah', '9', '36', '6', 'Behold, we are slaves to this day, and the land that you have given to our ancestors<span class=\"note\">Or “fathers”</span>to eat its fruits and <span class=\"supplied\">enjoy</span> its goodness—behold, we are slaves in it!'),
('LEB', 'Nehemiah', '9', '37', '6', 'Its rich yield goes to the kings whom you have given over us because of our sins, and <span class=\"supplied\">they are</span> ruling over our dead bodies and our livestock at their pleasure. We are in great trouble.'),
('LEB', 'Nehemiah', '9', '38', '7', '<span class=\"note\">Nehemiah 9:38–10:39 in the English Bible is 10:1–40 in the Hebrew Bible</span>“Now because of all of this we make a binding written agreement and are writing on the sealed documents <span class=\"supplied\">the names of</span> our commanders, our Levites, and our priests.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '10', '1', '1', '<span class=\"verse-title\">The Names of Those Who Signed the Covenant</span>Upon the sealed documents: Nehemiah the governor, son of Hacaliah and Zedekiah;'),
('LEB', 'Nehemiah', '10', '2', '1', 'Seraiah, Azariah, Jeremiah,'),
('LEB', 'Nehemiah', '10', '3', '1', 'Pashhur, Amariah, Malkijah,'),
('LEB', 'Nehemiah', '10', '4', '1', 'Hattush, Shebaniah, Malluch,'),
('LEB', 'Nehemiah', '10', '5', '1', 'Harim, Meremoth, Obadiah,'),
('LEB', 'Nehemiah', '10', '6', '1', 'Daniel, Ginnethon, Baruch,'),
('LEB', 'Nehemiah', '10', '7', '1', 'Meshullam, Abijah, Mijamin,'),
('LEB', 'Nehemiah', '10', '8', '1', 'Maaziah, Bilgai, Shemaiah—these are the priests.'),
('LEB', 'Nehemiah', '10', '9', '1', 'And the Levites: Jeshua son of Azaniah, Binnui from the sons of Henadad, Kadmiel;'),
('LEB', 'Nehemiah', '10', '10', '1', 'their brothers Shebaniah, Hodiah, Kelita, Pelaiah, Hanan,'),
('LEB', 'Nehemiah', '10', '11', '1', 'Mica, Rehob, Hashabiah,'),
('LEB', 'Nehemiah', '10', '12', '1', 'Zaccur, Shereiah, Shebanaih,'),
('LEB', 'Nehemiah', '10', '13', '1', 'Hodiah, Bani, Beninu.'),
('LEB', 'Nehemiah', '10', '14', '1', 'The heads of the people: Parosh, Pahath-Moab, Elam, Zattu, Bani,'),
('LEB', 'Nehemiah', '10', '15', '1', 'Bunni, Azgad, Bebai,'),
('LEB', 'Nehemiah', '10', '16', '1', 'Adonijah, Bigvai, Adin,'),
('LEB', 'Nehemiah', '10', '17', '1', 'Ater, Hezekiah, Azzur,'),
('LEB', 'Nehemiah', '10', '18', '1', 'Hodiah, Hashum, Bezai,'),
('LEB', 'Nehemiah', '10', '19', '1', 'Hariph, Anathoth, Nobai,'),
('LEB', 'Nehemiah', '10', '20', '1', 'Magpiash, Meshullam, Hezir,'),
('LEB', 'Nehemiah', '10', '21', '1', 'Meshezabel, Zadok, Jaddua,'),
('LEB', 'Nehemiah', '10', '22', '1', 'Pelatiah, Hanan, Anaiah,'),
('LEB', 'Nehemiah', '10', '23', '1', 'Hoshea, Hananiah, Hasshub,'),
('LEB', 'Nehemiah', '10', '24', '1', 'Hallohesh, Pilha, Shobek,'),
('LEB', 'Nehemiah', '10', '25', '1', 'Rehum, Hashabnah, Maaseiah,'),
('LEB', 'Nehemiah', '10', '26', '1', 'Ahijah, Hanan, Anan,'),
('LEB', 'Nehemiah', '10', '27', '1', 'Malluch, Harim, Baanah.'),
('LEB', 'Nehemiah', '10', '28', '3', '<span class=\"verse-title\">A Summary of the Covenant</span>“The rest of the people, the priests, the Levites, the gatekeepers, the singers, the temple servants, and all who separated themselves from the peoples of the lands to <span class=\"supplied\">observe</span> the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>of God—their wives, their sons, their daughters, and all who know and understand—'),
('LEB', 'Nehemiah', '10', '29', '3', '<span class=\"supplied\">are</span> helping their brothers, their nobles, and entering into a solemn oath to walk in the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>of God which was given by the hand of Moses the servant of God, and to observe and do all of the commandments of Adonai our Lord and his judgments and regulations.'),
('LEB', 'Nehemiah', '10', '30', '3', 'We will not give our daughters to the peoples of the land nor take their daughters for our sons.'),
('LEB', 'Nehemiah', '10', '31', '3', 'And the peoples of the land who bring merchandise and any grain on the Sabbath day to sell, we will not accept it from them on the Sabbath or on a holy day. We will forego <span class=\"supplied\">the crops of</span> the seventh year and <span class=\"supplied\">cancel</span> every debt.'),
('LEB', 'Nehemiah', '10', '32', '4', '“We put on ourselves the commandment upon us to yearly give a third of a shekel for the service of the house of our God:'),
('LEB', 'Nehemiah', '10', '33', '4', 'for the rows of bread, the offering of the daily sacrifice, the continual <span class=\"supplied\">burnt</span> sacrifice, the Sabbaths, the new moon festivals, the appointed <span class=\"supplied\">festival</span> times, the holy objects, the sin offerings that make atonement for Israel, and for all the work of the house of our God.'),
('LEB', 'Nehemiah', '10', '34', '4', 'And we have cast lots for the contributions of the wood offering of the priests, the Levites, and the people to bring <span class=\"supplied\">it</span> to the house of our God, by our fathers’ houses, at designated times, year by year, to burn on the altar of Adonai our God—as it is written in the law.<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>'),
('LEB', 'Nehemiah', '10', '35', '4', 'We <span class=\"supplied\">also</span> bring the first fruits of our soil and the first fruits of all the fruit trees, year by year, for the house of Adonai.'),
('LEB', 'Nehemiah', '10', '36', '4', 'And the firstborn of our sons and beasts—as it is written in the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>—and the firstborn of our cattle and sheep, to bring to the house of our God <span class=\"supplied\">and</span> to the priests serving in the house of our God.'),
('LEB', 'Nehemiah', '10', '37', '4', 'And we bring the best of our dough, our offerings, the fruit of every tree, new wine, and olive oil to the priests, to the chambers of the house of our God; and <span class=\"supplied\">to bring</span> the tithe of our soil to the Levites, for the Levites <span class=\"supplied\">receive</span> the tithes in all of our rural towns.'),
('LEB', 'Nehemiah', '10', '38', '4', 'And the priest, the descendant<span class=\"note\">Or “son”</span>of Aaron, will be with the Levites during the tithe the Levites receive. The Levites will bring up a tithe of the tithes for the house of our God to the chambers of the storehouse.'),
('LEB', 'Nehemiah', '10', '39', '4', 'For the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span>and the <span class=\"idiom\">Levites</span><span class=\"note\">“sons/children of Levi”</span>will bring to the storerooms the offering of grain, new wine, and olive oil. These are the objects of the sanctuary and the priests who minister and the gatekeepers and singers. We will not neglect the house of our God.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '11', '1', '1', '<span class=\"verse-title\">The Leaders and Servants in Jerusalem</span>Now the commanders of the people lived in Jerusalem, but the remainder of the people cast lots to bring one out of ten to live in the holy city of Jerusalem, the <span class=\"supplied\">other</span> nine’s place <span class=\"supplied\">was in</span> the <span class=\"supplied\">other</span> cities.'),
('LEB', 'Nehemiah', '11', '2', '1', 'And the people blessed all the men who willingly offered to live in Jerusalem.'),
('LEB', 'Nehemiah', '11', '3', '2', 'These are the heads of the province who lived in Jerusalem, but in the cities of Judah each one lived on his property in their cities: Israel, the priests, the Levites, the temple servants, and the descendants<span class=\"note\">Or “sons”</span>of Solomon’s servants.'),
('LEB', 'Nehemiah', '11', '4', '2', 'And <span class=\"supplied\">some</span> from the descendants<span class=\"note\">Or “sons”</span>of Judah and Benjamin lived in Jerusalem. From the descendants<span class=\"note\">Or “sons”</span>of Judah: Athaiah son of Uzziah, son of Zechariah, son of Amariah, son of Shephatiah, son of Mahalalel, from the descendants<span class=\"note\">Or “sons”</span>of Perez;'),
('LEB', 'Nehemiah', '11', '5', '2', 'and Maaseiah son of Baruch, son of Col-Hozeh, son of Hazaiah, son of Adaiah, son of Jehoiarib, son of Zechariah, son<span class=\"note\">Or “descendant”</span>of the Shilonite.'),
('LEB', 'Nehemiah', '11', '6', '2', 'All of the descendants<span class=\"note\">Or “sons”</span>of Perez who were living in Jerusalem <span class=\"supplied\">were</span> four hundred and sixty-eight able-bodied men.'),
('LEB', 'Nehemiah', '11', '7', '3', 'These are the descendants<span class=\"note\">Or “sons”</span>of Benjamin: Sallu son of Meshullam, son of Joed, son of Pedaiah, son of Kolaiah, son of Maaseiah, son of Ithiel, son of Jeshaiah.'),
('LEB', 'Nehemiah', '11', '8', '3', 'And <span class=\"supplied\">following</span> after him Gabbai, Sallai, nine hundred and twenty-eight.'),
('LEB', 'Nehemiah', '11', '9', '3', 'And Joel son of Zicri, their chief officer; and Judah son of Hassenuah, second <span class=\"supplied\">in command</span> over the city.'),
('LEB', 'Nehemiah', '11', '10', '4', 'From the priests: Jedaiah son of Jehoiarib, Jakin,'),
('LEB', 'Nehemiah', '11', '11', '4', 'Seraiah son of Hilkiah, son of Meshullam, son of Zadok, son of Meraioth, son of Ahitub—the leader of the house of God—'),
('LEB', 'Nehemiah', '11', '12', '4', 'and their brothers who did the work of the house, eight hundred and twenty-two. And Adaiah son of Jeroham, son of Pelaliah, son of Amzi, son of Zechariah, son of Pashhur, son of Malkijah,'),
('LEB', 'Nehemiah', '11', '13', '4', 'and his brothers, heads of the <span class=\"idiom\">families</span>,<span class=\"note\">“fathers”</span>two hundred and forty-two. And Amashai son of Azarel, son of Ahzai, son of Meshillemoth, son of Immer,'),
('LEB', 'Nehemiah', '11', '14', '4', 'and their brothers; mighty warriors of strength, one hundred and twenty-eight. The chief officer over them <span class=\"supplied\">was</span> Zabdiel son of Hagedolim.'),
('LEB', 'Nehemiah', '11', '15', '5', 'Now from the Levites: Shemaiah son of Hasshub, son of Azrikam, son of Hashabiah, son of Bunni;'),
('LEB', 'Nehemiah', '11', '16', '5', 'and Shabbethai and Jehozabad, leaders over the work of the Levites outside of the house of God;'),
('LEB', 'Nehemiah', '11', '17', '5', 'Mattaniah son of Micah, son of Zabdi, son<span class=\"note\">Or “descendant”</span>of Asaph, <span class=\"supplied\">who was</span> the leader to begin the thanksgiving prayer, and Bakbukiah the second of his brothers; Abda son of Shammua, son of Galal, son of Jeduthun.'),
('LEB', 'Nehemiah', '11', '18', '5', 'All of the Levites in the holy city <span class=\"supplied\">were</span> two hundred and eighty-four.'),
('LEB', 'Nehemiah', '11', '19', '6', 'The gatekeepers: Akkub, Talmon, and their brothers, the keepers of the gates, one hundred and seventy-two.'),
('LEB', 'Nehemiah', '11', '20', '6', 'And the remainder of Israel, the priests and the Levites, in all of the cities of Judah, each in his inheritance.'),
('LEB', 'Nehemiah', '11', '21', '6', 'But the temple servants were living on the Ophel; Ziha and Gishpa <span class=\"supplied\">were</span> over the temple servants.'),
('LEB', 'Nehemiah', '11', '22', '7', 'The chief officer of the Levites in Jerusalem <span class=\"supplied\">was</span> Uzzi son of Bani, son of Hashabiah, son of Mattaniah, son of Mica, from the descendants<span class=\"note\">Or “sons”</span>of Asaph, the singers over the work of the house of God.'),
('LEB', 'Nehemiah', '11', '23', '7', 'For <span class=\"supplied\">there was</span> a command of the king concerning them and a regulation concerning the singers, required <span class=\"idiom\">day by day</span>.<span class=\"note\">“a word for a day on his day”</span>'),
('LEB', 'Nehemiah', '11', '24', '7', 'And Pethahiah son of Meshezabel, from the descendants<span class=\"note\">Or “sons”</span>of Zerah the son of Judah, <span class=\"supplied\">was</span> at the hand of the king in all matters concerning the people.'),
('LEB', 'Nehemiah', '11', '25', '9', '<span class=\"verse-title\">Villages Outside of Jerusalem</span>As for the villages in their territories, <span class=\"supplied\">some</span> from the descendants<span class=\"note\">Or “sons”</span>of Judah lived in Kiriath-Arba and <span class=\"idiom\">its settlements</span>,<span class=\"note\">“its daughters”</span>Dibon and <span class=\"idiom\">its settlements</span>,<span class=\"note\">“its daughters”</span>Jekabzeel and <span class=\"idiom\">its settlements</span>,<span class=\"note\">“its daughters”</span>'),
('LEB', 'Nehemiah', '11', '26', '9', 'Jeshua, Moladah, Beth Pelet,'),
('LEB', 'Nehemiah', '11', '27', '9', 'Hazar Shual, Beersheba and <span class=\"idiom\">its settlements</span>,<span class=\"note\">“its daughters”</span>'),
('LEB', 'Nehemiah', '11', '28', '9', 'Ziklad, Meconah and <span class=\"idiom\">its settlements</span>,<span class=\"note\">“its daughters”</span>'),
('LEB', 'Nehemiah', '11', '29', '9', 'En-Rimmon, Zorah, Jarmuch,'),
('LEB', 'Nehemiah', '11', '30', '9', 'Zanoah, Adullam and <span class=\"idiom\">their settlements</span>,<span class=\"note\">“their daughters”</span>Lachish and its fields, and Azekah and <span class=\"idiom\">its settlements</span>.<span class=\"note\">“its daughters”</span>So they camped from Beersheba up to <span class=\"supplied\">the</span> Valley <span class=\"supplied\">of</span> Hinnom.'),
('LEB', 'Nehemiah', '11', '31', '9', 'The descendants<span class=\"note\">Or “sons”</span>of Benjamin from Geba, Micmash, Aija, Bethel and <span class=\"idiom\">their settlements</span>,<span class=\"note\">“their daughters”</span>'),
('LEB', 'Nehemiah', '11', '32', '9', 'Anathoth, Nob, Ananiah,'),
('LEB', 'Nehemiah', '11', '33', '9', 'Hazor, Ramah, Gittaim,'),
('LEB', 'Nehemiah', '11', '34', '9', 'Hadid, Zeboim, Neballat,'),
('LEB', 'Nehemiah', '11', '35', '9', 'Lod, and Ono the valley of the artisans.'),
('LEB', 'Nehemiah', '11', '36', '9', 'And from the Levites the working groups of Judah <span class=\"supplied\">were assigned</span> to Benjamin.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '12', '1', '1', '<span class=\"verse-title\">The Leaders and Servants in Jerusalem</span>These <span class=\"supplied\">are</span> the priests and the Levites who came up with Zerubbabel son of Shealtiel and Jeshua: Seraiah, Jeremiah, Ezra,'),
('LEB', 'Nehemiah', '12', '2', '1', 'Amariah, Malluch, Hattush,'),
('LEB', 'Nehemiah', '12', '3', '1', 'Shecaniah, Rehum, Meremoth,'),
('LEB', 'Nehemiah', '12', '4', '1', 'Iddo, Ginnethoi, Abijah,'),
('LEB', 'Nehemiah', '12', '5', '1', 'Mijamin, Maadiah, Bilgah,'),
('LEB', 'Nehemiah', '12', '6', '1', 'Shemaiah, Jehoiarib, Jedaiah,'),
('LEB', 'Nehemiah', '12', '7', '1', 'Sallu, Amok, Hilkiah, Jedaiah. These <span class=\"supplied\">are</span> the heads of the priests and their brothers in the days of Jeshua.'),
('LEB', 'Nehemiah', '12', '8', '2', 'And the Levites: Jeshua, Binnui, Kadmiel, Sherebiah, Judah, and Mattaniah and his brothers <span class=\"supplied\">who were</span> in charge of the songs of thanksgiving.'),
('LEB', 'Nehemiah', '12', '9', '2', 'And Bakbukiah, Unno, their brothers <span class=\"supplied\">stood</span> opposite them during service.'),
('LEB', 'Nehemiah', '12', '10', '2', 'Jeshua fathered Jehoiakim; Jehoiakim fathered Eliashib; Eliashib <span class=\"supplied\">fathered</span> Jehoiada;'),
('LEB', 'Nehemiah', '12', '11', '2', 'Jehoiada fathered Jehonathan; Jehonathan fathered Jaddua.'),
('LEB', 'Nehemiah', '12', '12', '3', 'Now in the days of Jehoiakim the priests and the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>were: of Seraiah, Meraiah; of Jeremiah, Hananiah;'),
('LEB', 'Nehemiah', '12', '13', '3', 'of Ezra, Meshullam; of Amariah, Jehohanan;'),
('LEB', 'Nehemiah', '12', '14', '3', 'of Melichu, Jonathan; of Shebaniah, Joseph;'),
('LEB', 'Nehemiah', '12', '15', '3', 'of Harim, Adna; of Meraioth, Helkai;'),
('LEB', 'Nehemiah', '12', '16', '3', 'of Adaia, Zechariah; of Ginnethon, Meshullam;'),
('LEB', 'Nehemiah', '12', '17', '3', 'of Abijah, Zicri; of Miniamin; of Moadiah, Piltai;'),
('LEB', 'Nehemiah', '12', '18', '3', 'of Bilgah, Shammua; of Shemaiah, Jehonathan;'),
('LEB', 'Nehemiah', '12', '19', '3', 'of Jehoiarib, Mattenai; of Jedaiah, Uzzi;'),
('LEB', 'Nehemiah', '12', '20', '3', 'of Sallu, Kallai; of Amok, Eber;'),
('LEB', 'Nehemiah', '12', '21', '3', 'of Hilkiah, Hashabiah; <span class=\"supplied\">and</span> of Jedaiah, Nethanel.'),
('LEB', 'Nehemiah', '12', '22', '4', 'In the days of Eliashib, Jehoiada, Jehohanan, and Jaddua the Levites were recorded as heads of the <span class=\"idiom\">families</span>.<span class=\"note\">“fathers”</span>So <span class=\"supplied\">these were</span> the priests <span class=\"supplied\">during</span> the reign of Darius the Persian.'),
('LEB', 'Nehemiah', '12', '23', '4', 'The descendants<span class=\"note\">Or “sons”</span>of Levi and the heads of the <span class=\"idiom\">families</span><span class=\"note\">“fathers”</span>were recorded in the scroll of the Annals until the days of Jehohanan son of Eliashib.'),
('LEB', 'Nehemiah', '12', '24', '4', 'And the heads of the Levites: Hashabiah, Sherebiah, Jeshua son of Kadmiel, and their brothers opposite them, to praise and to give thanks by the command of David the man of God, section alongside section.'),
('LEB', 'Nehemiah', '12', '25', '4', 'Mattaniah, Bakbukiah, Obadiah, Meshullam, Talmon, and Akkub were gatekeepers standing guard at the storerooms of the gates.'),
('LEB', 'Nehemiah', '12', '26', '4', 'These were in the days of Jehoiakim son of Jeshua, son of Jehozadak, and in the days of Nehemiah the governor and Ezra the priest and scribe.'),
('LEB', 'Nehemiah', '12', '27', '6', '<span class=\"verse-title\">Dedication of the Wall of Jerusalem</span>At the dedication of the wall of Jerusalem they sought the Levites from all of their places in order to bring them to Jerusalem to do the dedication with joy, thanksgivings, song and cymbals, stringed instruments and lyres.'),
('LEB', 'Nehemiah', '12', '28', '6', 'The <span class=\"idiom\">singers</span><span class=\"note\">“sons of the singers”</span>were gathered from the circuit all around Jerusalem and from the villages of Netophathite,'),
('LEB', 'Nehemiah', '12', '29', '6', 'from Beth Gilgal, from the field of Geba and Azmaveth; for the singers built for themselves villages all around Jerusalem.'),
('LEB', 'Nehemiah', '12', '30', '6', 'And the priests and the Levites purified themselves and purified the people, the gates, and the wall.'),
('LEB', 'Nehemiah', '12', '31', '7', 'Then I brought the commanders of Judah up on to the wall. I appointed two great choirs; <span class=\"supplied\">one went in</span> a procession to the right on the wall to the Dung Gate.'),
('LEB', 'Nehemiah', '12', '32', '7', 'After them went Hoshaiah, half of the commanders of Judah,'),
('LEB', 'Nehemiah', '12', '33', '7', 'Azariah, Ezra, Meshullam,'),
('LEB', 'Nehemiah', '12', '34', '7', 'Judah, Benjamin, Shemaiah, Jeremiah,'),
('LEB', 'Nehemiah', '12', '35', '7', 'and the <span class=\"idiom\">priests</span><span class=\"note\">“sons of the priests”</span>with trumpets; Zechariah son of Jehonathan, son of Shemaiah, son of Mattaniah, son of Micaiah, son of Zaccur, son of Asaph;'),
('LEB', 'Nehemiah', '12', '36', '7', 'and his brothers Shemaiah, Azarel, Milalai, Gilalai, Maai, Nethanel, Judah, and Hanani with the instruments of the songs of David the man of God; and Ezra the scribe <span class=\"supplied\">went</span> before them.'),
('LEB', 'Nehemiah', '12', '37', '7', 'At the Fountain Gate opposite them they went up the steps of the city of David, at the assent to the wall, over the house of David, and up to the Water Gate to the east.'),
('LEB', 'Nehemiah', '12', '38', '8', 'Then the second choir went the opposite <span class=\"supplied\">way</span>. I <span class=\"supplied\">followed</span> after them with half of the people on the wall, from over the Tower of the Ovens up to the Wide Wall'),
('LEB', 'Nehemiah', '12', '39', '8', 'and over the Gate of Ephraim, at the Old Gate, at the Fish Gate, the Tower of Hananel and the Tower of the Hundred, and <span class=\"supplied\">to</span> the Sheep Gate. And they <span class=\"supplied\">stopped and</span> stood at the Gate of the Guard.'),
('LEB', 'Nehemiah', '12', '40', '8', 'So the two choirs stood in the house of God, and I and half of the prefects with me;'),
('LEB', 'Nehemiah', '12', '41', '8', 'and the priests Eliakim, Maaseiah, Miniamin, Micaiah, Elioenai, Zechariah, and Hananiah with the trumpets;'),
('LEB', 'Nehemiah', '12', '42', '8', 'Maaseiah, Shemaiah, Eleazar, Uzzi, Jehohanan, Malkijah, Elam, and Ezer. And the singers sang with Jizrahiah the chief officer.'),
('LEB', 'Nehemiah', '12', '43', '8', 'They offered on that day great sacrifices and rejoiced because God brought great joy to them. And the women and children also rejoiced. The joy of Jerusalem was heard from afar.'),
('LEB', 'Nehemiah', '12', '44', '10', '<span class=\"verse-title\">Celebration at the Temple</span>On that day men were appointed for the storehouse rooms, the offerings, the first fruits, and the tithes, in order to gather in them from the fields of the cities the requirements of the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>for the priests and Levites; for the joy of Judah <span class=\"supplied\">was</span> upon the priests and Levites standing there.'),
('LEB', 'Nehemiah', '12', '45', '10', 'They kept the responsibility of their God and the responsibility of cleansing, and the singers and gatekeepers, according to the command of David and his son Solomon.'),
('LEB', 'Nehemiah', '12', '46', '10', 'For in the days of David and Asaph from ancient times there was the head of the singers and a song of praise and thanksgiving to God.'),
('LEB', 'Nehemiah', '12', '47', '10', 'So all of Israel in the days of Zerubbabel and in the days of Nehemiah gave the daily food portions of the singers and gatekeepers. And they set apart <span class=\"supplied\">that which was for</span> the Levites, and the Levites set apart <span class=\"supplied\">that which was for</span> the descendants<span class=\"note\">Or “sons”</span>of Aaron.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Nehemiah', '13', '1', '1', '<span class=\"verse-title\">Israel Separates Itself</span>On that day the book of Moses was read in the hearing of the people and it was found written in it that no Ammonite or Moabite should ever come into the assembly of God'),
('LEB', 'Nehemiah', '13', '2', '1', 'because they did not come to meet the <span class=\"idiom\">Israelites</span><span class=\"note\">“sons/children of Israel”</span>with bread and water, but hired Balaam against them in order to curse them—but our God changed the curse into a blessing.'),
('LEB', 'Nehemiah', '13', '3', '1', 'So it happened when they heard the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>that they separated all of the foreign people from Israel.'),
('LEB', 'Nehemiah', '13', '4', '3', '<span class=\"verse-title\">Nehemiah Brings Reform</span>Before this, Eliashib the priest who was appointed over the chambers of the house of our God—the one related to Tobiah—'),
('LEB', 'Nehemiah', '13', '5', '3', 'prepared for <span class=\"supplied\">Tobiah</span> a large chamber where they had formerly put the grain offering, the frankincense, the <span class=\"supplied\">temple</span> objects, tithes of grain, wine, and oil commanded for the Levites, the singers, the gatekeepers, and the offerings of the priests.'),
('LEB', 'Nehemiah', '13', '6', '3', 'During all of this, I was not in Jerusalem because in the thirty-second year of Artaxerxes king of Babylon I went to the king. At the end of <span class=\"supplied\">some</span> days I asked permission from the king <span class=\"supplied\">to leave</span>.'),
('LEB', 'Nehemiah', '13', '7', '3', 'So I came to Jerusalem. And I came to learn of the wrong that Eliashib had done for Tobiah by making him a room in the courtyard of the house of God.'),
('LEB', 'Nehemiah', '13', '8', '3', 'It was very displeasing for me, and I threw all of the objects from the house of Tobiah outside of the chamber.'),
('LEB', 'Nehemiah', '13', '9', '3', 'And I spoke <span class=\"supplied\">in order</span>, and they cleansed the chambers. Then I returned the objects of the house of God—the grain offering and the frankincense.'),
('LEB', 'Nehemiah', '13', '10', '4', 'And then I came to learn that the food of the Levites had not been given to them, so that the Levites and the singers, the doers of the work, had gone back each to his field.'),
('LEB', 'Nehemiah', '13', '11', '4', 'So I quarreled with the prefects, and I said, “Why is the house of God forsaken?” And I gathered them and set them at their station.'),
('LEB', 'Nehemiah', '13', '12', '4', 'So all of Judah brought the tithe of grain, new wine, and olive oil into the storehouses.'),
('LEB', 'Nehemiah', '13', '13', '4', 'I appointed as treasurer over the storehouses Shelemiah the priest, Zadok the scribe, Pedaiah from the Levites, and as their hand Hanan son of Zaccur, son of Mattaniah, for they were considered faithful. <span class=\"supplied\">The responsibility given</span> to them was to distribute to their brothers.'),
('LEB', 'Nehemiah', '13', '14', '4', 'Remember me, my God, concerning this, and do not wipe out my loyal acts which I have done in the house of my God and in his service.'),
('LEB', 'Nehemiah', '13', '15', '6', '<span class=\"verse-title\">Nehemiah Begins Sabbath Reforms</span>In those days I saw in Judah <span class=\"supplied\">people</span> treading the wine press on the Sabbath, bringing in heaps <span class=\"supplied\">of grain</span> and loading them on donkeys along with wine, grapes and figs, and every kind of burden and bringing <span class=\"supplied\">it all</span> to Jerusalem on the day of the Sabbath. And I warned them at that time against selling food.'),
('LEB', 'Nehemiah', '13', '16', '6', 'Tyrian men who lived in <span class=\"supplied\">Jerusalem</span> brought fish and every kind of merchandise and sold <span class=\"supplied\">it</span> on the Sabbath to the descendants<span class=\"note\">Or “sons”</span>of Judah and in Jerusalem.'),
('LEB', 'Nehemiah', '13', '17', '6', 'So I quarreled with the nobles of Judah and said to them, “What is this evil thing that you are doing, profaning the day of the Sabbath?'),
('LEB', 'Nehemiah', '13', '18', '6', 'Did not your ancestors<span class=\"note\">Or “fathers”</span>do this also, and our God brought on us all of this disaster and on this city <span class=\"supplied\">too</span>? Now you are adding fierce wrath on Israel by profaning the Sabbath!”'),
('LEB', 'Nehemiah', '13', '19', '7', 'So when it became dark at the gates of Jerusalem before the Sabbath, I commanded that the doors be shut and said that they should not be opened until after the Sabbath. And I appointed some of my young men over the gates <span class=\"supplied\">to prevent</span> any <span class=\"idiom\">goods</span><span class=\"note\">“burden”</span>being brought in on the day of the Sabbath.'),
('LEB', 'Nehemiah', '13', '20', '7', 'So the merchants and the sellers of merchandise spent the night outside of Jerusalem once or twice.'),
('LEB', 'Nehemiah', '13', '21', '7', 'But I warned them and said to them, “Why are you spending the night opposite the wall? If you do <span class=\"supplied\">it again</span>, I will lay hands against you.” From that time on they did not come on the Sabbath.'),
('LEB', 'Nehemiah', '13', '22', '7', 'And then I told two Levites that they must purify themselves and come to guard the gates in order to consecrate the day of the Sabbath. Remember this also, my God, and take pity on me according to the greatness of your loyal love.'),
('LEB', 'Nehemiah', '13', '23', '9', '<span class=\"verse-title\">Mixed Marriages are Condemned</span>Also in those days I saw Jews who had married women of Ashdod, Ammon, and Moab.'),
('LEB', 'Nehemiah', '13', '24', '9', 'Half of their children spoke Ashdodite and could not speak Judean, but <span class=\"supplied\">only</span> the tongues of other nations.'),
('LEB', 'Nehemiah', '13', '25', '9', 'So I quarreled with them and cursed them and beat some of their men and pulled out their hair. I made them take an oath by God: “Do not give your daughters to their sons or take their daughters for your sons or for yourselves.'),
('LEB', 'Nehemiah', '13', '26', '9', 'Did not King Solomon of Israel sin in this way? And among the many nations there was no king like him, and he was beloved by his God, and God made him king over all Israel. Yet the foreign women made even him sin.'),
('LEB', 'Nehemiah', '13', '27', '9', 'Should we listen to you all and do this great evil, acting unfaithfully against our God by marrying foreign women?”'),
('LEB', 'Nehemiah', '13', '28', '10', 'One from the sons of Jehoiada, son of the high priest Eliashib, <span class=\"supplied\">who was</span> the son-in-law of Sanballat the Horonote <span class=\"supplied\">was there</span>. I chased him away from me.'),
('LEB', 'Nehemiah', '13', '29', '10', 'Remember them, my God, because of their defilements of the priesthood and the covenant of the priesthood and the Levites.'),
('LEB', 'Nehemiah', '13', '30', '11', 'So I cleansed them from everything foreign, and I established responsibilities for the priests and Levites, each in his own work,'),
('LEB', 'Nehemiah', '13', '31', '11', 'a contribution of the wood offering at appointed times, and for the first fruits. Remember me, my God, for good.')
;

