INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Obadiah', '1', '1', '1', '<span class=\"verse-title\">God’s Judgment on Edom</span>The vision of Obadiah. Thus says my Lord Adonai concerning Edom:'),
('LEB', 'Obadiah', '1', '2', '3', '<span class=\"verse-title\">Edom’s Approaching Destruction</span>We have heard a report from Adonai, and a messenger has been sent among the nations: “Rise up and let us rise against it<span class=\"note\">That is, Edom</span>for battle.”'),
('LEB', 'Obadiah', '1', '3', '3', '“Look, I will<span class=\"note\">The NET Bible note for this verse points out: “The Hebrew perfect verb form used here usually describes past events. However, here and several times in the following verses it is best understood as portraying certain fulfillment of events that at the time of writing were still future. It is the perfect of certitude”</span>make you insignificant among the nations. You <span class=\"supplied\">will be</span> utterly despised!'),
('LEB', 'Obadiah', '1', '4', '3', 'The pride of your heart has deceived you, you who live in the clefts of a rock, the heights of its dwelling, <span class=\"supplied\">you who</span> say in your heart: ‘Who can bring me down <span class=\"supplied\">to the</span> ground?’'),
('LEB', 'Obadiah', '1', '5', '3', '<span class=\"supplied\">Even</span> if you soar like the eagle, <span class=\"supplied\">even</span> if your nest is set among <span class=\"supplied\">the</span> stars, from there I will bring you down!” <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai:'),
('LEB', 'Obadiah', '1', '6', '3', '“If thieves came to you, if plunderers of <span class=\"supplied\">the</span> night—How you have been destroyed!—would they not steal <span class=\"idiom\">what they wanted</span>?<span class=\"note\">“their sufficiency”</span>If grape gatherers came, would they not leave gleanings?'),
('LEB', 'Obadiah', '1', '7', '3', 'How Esau has been pillaged; his treasures have been ransacked!'),
('LEB', 'Obadiah', '1', '8', '3', 'All of your <span class=\"idiom\">allies</span><span class=\"note\">“men of your covenant”</span>have driven you up to the boundary; your <span class=\"idiom\">confederates</span><span class=\"note\">“men of your peace”</span>have deceived you and have prevailed against you. <span class=\"supplied\">Those who eat</span> your bread have set an ambush for you, there is no<span class=\"note\">The preposition בּ plus אֵין indicates the absence of a thing within a location</span>understanding of it.<span class=\"note\">Or “in him”</span>'),
('LEB', 'Obadiah', '1', '9', '3', 'On that day,” <span class=\"idiom\">declares</span><span class=\"note\">“a declaration of”</span>Adonai, “will I not destroy the wise men from Edom, and understanding from the mountain of Esau?'),
('LEB', 'Obadiah', '1', '10', '5', '<span class=\"verse-title\">Edom’s Treachery against Judah</span>“Because of the violence done to your brother Jacob, shame will cover you and you will be cut off forever.'),
('LEB', 'Obadiah', '1', '11', '5', 'On <span class=\"idiom\">the day you stood nearby</span>,<span class=\"note\">“the day of your standing nearby”</span><span class=\"idiom\">on the day strangers took</span><span class=\"note\">“the day of the taking captive by strangers”</span>his wealth, and foreigners entered his gates and cast lots over Jerusalem, you were also like one of them.'),
('LEB', 'Obadiah', '1', '12', '5', 'But you should not have gloated<span class=\"note\">The Hebrew expression “to look upon” often has the sense of “to feast the eyes upon” or “to gloat over”</span>over your brother’s day, on the day of his misfortune, and you should not have rejoiced over the <span class=\"idiom\">people</span><span class=\"note\">“son”</span>of Judah on the day of their perishing, and you should not have opened your mouth wide on the day of distress.'),
('LEB', 'Obadiah', '1', '13', '5', 'You should not have entered the gate of my people on the day of their disaster. You also should not have gloated over his misery on the day of his disaster, and you should not have stretched out <span class=\"supplied\">your hands</span> on the day of his disaster.'),
('LEB', 'Obadiah', '1', '14', '5', 'And you should not have stood at the crossroad<span class=\"supplied\">s</span> to cut off his fugitives and you should not have handed over his survivors on the day of distress.'),
('LEB', 'Obadiah', '1', '15', '7', '<span class=\"verse-title\">Future Judgment of the Nations</span>“For the day of Adonai <span class=\"supplied\">is</span> near against all the nations! Just as you have done, it will be done to you. Your deeds will return on your <span class=\"supplied\">own</span> head.'),
('LEB', 'Obadiah', '1', '16', '7', 'For just as you have drunk on <span class=\"idiom\">my holy mountain</span>,<span class=\"note\">“the mountain of my holiness”</span>all the nations will drink continually. They will drink and they will slurp, and they will be as <span class=\"supplied\">if</span> they had never been.'),
('LEB', 'Obadiah', '1', '17', '7', 'But on Mount Zion there will be an escape, and it will be holy, and the house of Jacob will take possession <span class=\"supplied\">of</span> their dispossessors.'),
('LEB', 'Obadiah', '1', '18', '7', 'And the house of Jacob will be a fire and the house of Joseph a flame, and the house of Esau stubble; and they will set them on fire and will consume them. And there will not be a survivor for the house of Esau,” for Adonai has spoken.'),
('LEB', 'Obadiah', '1', '19', '9', '<span class=\"verse-title\">Future Blessing for Israel</span>Those of the Negev will take possession of the mountain of Esau, and those of the Shephelah <span class=\"supplied\">will possess the land of</span> the Philistines, and they shall take possession of the territory of Ephraim and the territory of Samaria, and Benjamin <span class=\"supplied\">will take possession of</span> Gilead.'),
('LEB', 'Obadiah', '1', '20', '9', 'And the exiles<span class=\"note\">Hebrew “exile”</span>of this army of the people of Israel <span class=\"supplied\">will possess</span> Canaan up to Zarephath, and the exiles<span class=\"note\">Hebrew “exile”</span>of Jerusalem who <span class=\"supplied\">are</span> in Sepharad will take possession of the cities of the Negev.'),
('LEB', 'Obadiah', '1', '21', '9', 'And those who have been saved will go up on Mount Zion to rule the mountain of Esau. And the kingdom <span class=\"idiom\">will belong to</span><span class=\"note\">“will be for”</span>Adonai.')
;

