INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '1', '1', '1', '<span class=\"verse-title\">Title</span>The Song of Songs,<span class=\"note\">This construction conveys a superlative connotation, e.g., “The most exquisite song”</span>which <span class=\"supplied\">is</span> for<span class=\"note\">Or “by Solomon” or “about/concerning Solomon”</span>Solomon.'),
('LEB', 'Song of Solomon', '1', '2', '3', '<span class=\"verse-title\">Maiden’s Soliloquy</span><span class=\"idiom\">May<span class=\"note\">In the maiden’s soliloquy, she thinks about her beloved in her thoughts (“May he kiss me!”), then poetically speaks to him as if he were in her presence (“for your love is better than wine”). To avoid confusion, the translation uses the second-person form throughout vv. 2–4</span>you kiss me</span><span class=\"note\">“May he kiss me”</span><span class=\"idiom\">passionately with your lips</span>,<span class=\"note\">“with the kisses of his mouth”</span> for your love <span class=\"supplied\">is</span> better than wine.<span class=\"note\">The shift from the third person “he … his” to the second person “you … your” in vv. 2–4 should not be interpreted as suggesting two different referents, that is, one male whom the maiden is addressing as “you,” and another to whom she refers as “he.” Rather, this shift is a poetic device (called “grammatical differentiation”) that is not uncommon in Hebrew poetry (e.g., Gen 49:4; Deut 32:15; Psa 23:2–5; Isa 1:29; 42:20; 54:1; Jer 22:24; Amos 4:1; Mic 7:19; Lam 3:1; Song 4:2; 6:6). This shift is characteristic of a soliloquy, a dramatic or literary form in which a character reveals her thoughts without addressing a listener who is actually present (e.g., 2 Sam 19:4). In this case, the maiden’s private thoughts about her beloved (v. 2a) shift to an imaginary address to her beloved (vv. 2b–4a)</span>'),
('LEB', 'Song of Solomon', '1', '3', '3', 'As fragrance, <span class=\"idiom\">your perfumes</span><span class=\"note\">“your oil lotions”</span><span class=\"supplied\">are</span> <span class=\"idiom\">delightful</span>;<span class=\"note\">“good”</span> your name is poured out <span class=\"idiom\">perfume</span>;<span class=\"note\">“oil lotion”</span> therefore young women love you.'),
('LEB', 'Song of Solomon', '1', '4', '3', 'Draw me after you, let us run!  May the king bring me into his chambers!<span class=\"note\">Or “The king has brought me into his chambers”</span> Let us be joyful and let us rejoice in you;  let us extol your love more than wine.  Rightly do they love you!'),
('LEB', 'Song of Solomon', '1', '5', '5', '<span class=\"verse-title\">Maiden’s Self-Description</span>I <span class=\"supplied\">am</span> black but beautiful,<span class=\"note\">Or “black and beautiful”</span><span class=\"idiom\">O maidens of Jerusalem</span>,<span class=\"note\">“O daughters of Jerusalem”</span> like the tents of Kedar, like the curtains of Solomon.'),
('LEB', 'Song of Solomon', '1', '6', '5', 'Do not gaze at me because I am black, <span class=\"note\">This is figurative for the maiden’s physical appearance; her skin was darkly tanned</span> because the sun has stared <span class=\"supplied\">at</span> me.  The sons of my mother were angry with me;  they made me keeper of the vineyards,  <span class=\"supplied\">but</span> my own “vineyard”<span class=\"note\">“my vineyard that for me”</span>I did not keep.'),
('LEB', 'Song of Solomon', '1', '7', '7', '<span class=\"verse-title\">Dialogue between Shepherdess and Shepherd</span>Tell me, <span class=\"supplied\">you</span> whom my <span class=\"idiom\">heart</span><span class=\"note\">“soul”</span>loves,  where do you pasture your flock,  where do your sheep lie down at the noon?  <span class=\"idiom\">For why should I be like</span><span class=\"note\">“For to what will I be like”</span>one who is veiled<span class=\"note\">The reading of the MT (“like one who is veiled”) is supported by the LXX. However, several ancient versions (Syriac Peshitta, Latin Vulgate, Symmachus) reflect an alternate Hebrew textual tradition in which two letters are transposed, resulting in the reading “like one who wanders about.” This makes good sense contextually, since the maiden does not know where her beloved would be at noon</span> beside the flocks of your companions?'),
('LEB', 'Song of Solomon', '1', '8', '7', 'If you do not know, O fairest among women,  follow <span class=\"idiom\">the tracks</span><span class=\"note\">“in the tracks”</span>of the flock,  and pasture your little lambs<span class=\"note\">Or “your kids”</span>beside the tents of the shepherds.'),
('LEB', 'Song of Solomon', '1', '9', '9', '<span class=\"verse-title\">Man’s Poetic Praise of His Beloved</span>To a mare<span class=\"note\">Or “my mare”</span>among the chariots<span class=\"note\">Or “chariot horses”</span>of Pharaoh,  I compare you, my beloved.'),
('LEB', 'Song of Solomon', '1', '10', '9', 'Your cheeks are beautiful with ornaments,  your neck with strings of jewels.'),
('LEB', 'Song of Solomon', '1', '11', '9', 'We will make ornaments of gold for you  with studs<span class=\"note\">Or “droplets”</span>of silver.'),
('LEB', 'Song of Solomon', '1', '12', '11', '<span class=\"verse-title\">Maiden’s Poetic Praise of Her Beloved</span>While the king <span class=\"supplied\">was</span> on his couch,  my nard gave its fragrance.'),
('LEB', 'Song of Solomon', '1', '13', '11', 'My beloved <span class=\"supplied\">is</span> to me <span class=\"idiom\">a pouch</span><span class=\"note\">“the bag”</span>of myrrh,  he spends the night<span class=\"note\">Or “he lays”</span>between my breasts.'),
('LEB', 'Song of Solomon', '1', '14', '11', 'My beloved <span class=\"supplied\">is</span> to me a cluster of blossoms of henna  in the vineyards of En Gedi.'),
('LEB', 'Song of Solomon', '1', '15', '13', '<span class=\"verse-title\">Mutual Admiration</span>Look! You <span class=\"supplied\">are</span> beautiful, my beloved.  Look! You <span class=\"supplied\">are</span> beautiful;  your eyes <span class=\"supplied\">are</span> doves.'),
('LEB', 'Song of Solomon', '1', '16', '13', 'Look! You <span class=\"supplied\">are</span> beautiful, my beloved,  truly pleasant.  Truly our couch <span class=\"supplied\">is</span> <span class=\"idiom\">verdant</span>;<span class=\"note\">“green”</span>'),
('LEB', 'Song of Solomon', '1', '17', '13', 'the beams of our house <span class=\"supplied\">are</span> cedar;  our rafter <span class=\"supplied\">is</span> cypress.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '2', '1', '1', '<span class=\"verse-title\">Dialogue between Maiden and Her Beloved</span>I <span class=\"supplied\">am</span> a rose<span class=\"note\">More likely “meadow saffron” or “crocus.” Hebrew scholars and botanists suggest the term refers to <span class=\"italic\">Ashodelos</span> (lily family), <span class=\"italic\">Narcissus tazetta</span> (narcissus or daffodil), or <span class=\"italic\">Colchicum autumnale</span> (meadow saffron or crocus) (e.g., Isa 35:1). The location of this flower in Sharon suggests a common wild flower rather than a rose. The maiden compares herself to a simple, common flower of the field</span>of Sharon,  a lily of the valleys.'),
('LEB', 'Song of Solomon', '2', '2', '1', 'Like a lily among the thorns,<span class=\"note\">Or “brambles”</span> so <span class=\"supplied\">is</span> my love among the maidens.'),
('LEB', 'Song of Solomon', '2', '3', '1', 'As an apple tree among the trees of the forest,  so <span class=\"supplied\">is</span> my beloved among the young men.  In his shade <span class=\"idiom\">I sat down with delight</span>,<span class=\"note\">“I sat down and I delighted”</span> and his fruit <span class=\"supplied\">was</span> sweet to my palate.'),
('LEB', 'Song of Solomon', '2', '4', '3', '<span class=\"verse-title\">Banquet Hall of Love</span>He brought me to the house of the wine,  and his intention <span class=\"supplied\">was</span> love toward me.'),
('LEB', 'Song of Solomon', '2', '5', '3', 'Sustain me with the raisins,  refresh me with the apples,  <span class=\"idiom\">for I <span class=\"supplied\">am</span> lovesick</span>.<span class=\"note\">“for I myself <span class=\"supplied\">am</span> sick with love”</span>'),
('LEB', 'Song of Solomon', '2', '6', '5', '<span class=\"verse-title\">Double Refrain: Embrace and Adjuration</span>His left <span class=\"supplied\">hand</span> <span class=\"supplied\">is</span> under my head,  and his right <span class=\"supplied\">hand</span> embraces<span class=\"note\">Or “would embrace me”</span>me.'),
('LEB', 'Song of Solomon', '2', '7', '5', 'I adjure you, <span class=\"idiom\">O maidens of Jerusalem</span>,<span class=\"note\">“O daughters of Jerusalem”</span> by the gazelles or by the does of the field,  do not arouse or awaken love until it pleases!<span class=\"note\">Or “Do not stir up or awaken the love until it is willing,” or “Do not disturb or interrupt <span class=\"supplied\">our</span> lovemaking until it is satisfied”</span>'),
('LEB', 'Song of Solomon', '2', '8', '7', '<span class=\"verse-title\">Rendezvous in the Countryside</span>The voice of my beloved!  Look! Here <span class=\"idiom\">he</span><span class=\"note\">“this one”</span>comes leaping upon the mountains,  bounding over the hills!'),
('LEB', 'Song of Solomon', '2', '9', '7', 'My beloved is like a gazelle or <span class=\"idiom\">a young stag</span>.<span class=\"note\">“the fawn of the stag”</span> Look! <span class=\"idiom\">He is</span><span class=\"note\">“This <span class=\"supplied\">is he</span>”</span>standing behind our wall,  gazing <span class=\"idiom\">through</span><span class=\"note\">“from”</span>the window,  looking <span class=\"idiom\">through</span><span class=\"note\">“from”</span>the lattice.'),
('LEB', 'Song of Solomon', '2', '10', '7', 'My beloved answered and said to me,  “<span class=\"idiom\">Arise</span>,<span class=\"note\">“Arise, you”</span>my beloved! <span class=\"idiom\">Come, my beauty</span>!<span class=\"note\">“And come, you”</span>'),
('LEB', 'Song of Solomon', '2', '11', '7', 'For look! The winter is over;  <span class=\"idiom\">the rainy season</span><span class=\"note\">“the rain”</span><span class=\"idiom\">has turned and gone away</span>.<span class=\"note\">“is over; it is gone”</span>'),
('LEB', 'Song of Solomon', '2', '12', '7', 'The blossoms <span class=\"idiom\">appear</span><span class=\"note\">“is seen”</span><span class=\"idiom\">in the land</span>;<span class=\"note\">“on the earth”</span> <span class=\"idiom\">the time of singing<span class=\"note\">Most likely, a subtle word play occurs here since there are two different words in Hebrew spelled the same way: “pruning” and “singing.” The former plays upon the first line and the latter upon the third line</span>has arrived</span>;<span class=\"note\">“the time of the song arrived”</span> the voice of the turtledove is heard in our land.'),
('LEB', 'Song of Solomon', '2', '13', '7', 'The fig tree puts forth her figs,  and the vines <span class=\"supplied\">are in</span> blossom; they give fragrance.  <span class=\"idiom\">Arise</span>,<span class=\"note\">“Arise, to you!”</span>my beloved! <span class=\"idiom\">Come, my beauty</span>!”<span class=\"note\">“My beauty, come, you”</span>'),
('LEB', 'Song of Solomon', '2', '14', '7', 'My dove, in the clefts of the rock,  <span class=\"idiom\">in the secluded place</span><span class=\"note\">“in the secret place”</span><span class=\"note\">Or “in the covering”</span><span class=\"idiom\">in the mountain</span>,<span class=\"note\">“foothold in the rock”</span><span class=\"note\">Or “cliff”</span> Let me see your face,  let me hear your voice;  for your voice <span class=\"supplied\">is</span> sweet and your face <span class=\"supplied\">is</span> lovely.'),
('LEB', 'Song of Solomon', '2', '15', '7', 'Catch for us the foxes,  the little foxes destroying vineyards,  for<span class=\"note\">Or “while”</span>our vineyards <span class=\"supplied\">are in</span> blossom!'),
('LEB', 'Song of Solomon', '2', '16', '9', '<span class=\"verse-title\">Poetic Refrain(s)</span><span class=\"idiom\">My beloved belongs to me and I belong to him</span>;<span class=\"note\">“My beloved for me and I for him”</span> he pastures his flock among the lilies.'),
('LEB', 'Song of Solomon', '2', '17', '9', 'Until the day breathes and the shadows flee,  turn, my beloved!  <span class=\"idiom\">Be like</span><span class=\"note\">“Be like for you”</span>a gazelle<span class=\"note\">Or “a buck gazelle”</span>or <span class=\"idiom\">young stag</span><span class=\"note\">“the fawn of the stag”</span>on the cleft mountains.<span class=\"note\">Or “the mountains of Bether”</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '3', '1', '1', '<span class=\"verse-title\">Maiden’s Dream (?): Seeking and Finding</span>On my bed in the night,  I sought<span class=\"note\">Or “I seek”</span>him whom my <span class=\"idiom\">heart</span><span class=\"note\">“soul”</span>loves.  I sought him, but I did not find him.'),
('LEB', 'Song of Solomon', '3', '2', '1', 'Now I will arise, and I will go about in the city,  in the streets and in the squares;  I will seek him whom my <span class=\"idiom\">heart</span><span class=\"note\">“soul”</span>loves.  I sought him, but I did not find him.'),
('LEB', 'Song of Solomon', '3', '3', '1', 'The sentinels who go about in the city found me.  “Have you seen the one whom my <span class=\"idiom\">heart</span><span class=\"note\">“soul”</span>loves?”'),
('LEB', 'Song of Solomon', '3', '4', '1', '<span class=\"idiom\">Scarcely had I passed</span><span class=\"note\">“As little that I passed”</span>by them  when I found him whom my <span class=\"idiom\">heart</span><span class=\"note\">“soul”</span>loves.  I held him and I would not let him go  until I brought him to the house of my mother,  into the bedroom chamber of she who conceived me.'),
('LEB', 'Song of Solomon', '3', '5', '3', '<span class=\"verse-title\">Adjuration Refrain</span>I adjure you, <span class=\"idiom\">O maidens of Jerusalem</span>,<span class=\"note\">“O daughters of Jerusalem”</span> by the gazelles or by the does of the field,  do not arouse or awaken love until it pleases!<span class=\"note\">Or “Do not stir up or awaken the love until it is willing,” or “Do not disturb or interrupt <span class=\"supplied\">our</span> love-making until it is satisfied”</span>'),
('LEB', 'Song of Solomon', '3', '6', '5', '<span class=\"verse-title\">Royal Wedding Procession</span>What <span class=\"supplied\">is</span> this coming up from the desert  like a column of smoke,  perfumed with myrrh and frankincense  from all the fragrant powders of the merchant?'),
('LEB', 'Song of Solomon', '3', '7', '5', 'Look! <span class=\"supplied\">It is</span> Solomon’s <span class=\"idiom\">portable couch</span>!<span class=\"note\">“couch” or “portable sedan chair”</span> Sixty mighty men surround <span class=\"idiom\">it</span>,<span class=\"note\">“her”</span> the mighty men of Israel.'),
('LEB', 'Song of Solomon', '3', '8', '5', 'All of them <span class=\"idiom\">wield swords</span>;<span class=\"note\">“holders of sword”</span> <span class=\"supplied\">they are</span> <span class=\"idiom\">trained in warfare</span>,<span class=\"note\">“learnt of war”</span> each with his sword at his thigh  <span class=\"supplied\">to guard</span> <span class=\"idiom\">against terror</span><span class=\"note\">“because of the fear”</span>in the night.'),
('LEB', 'Song of Solomon', '3', '9', '5', '<span class=\"idiom\">King Solomon</span><span class=\"note\">“The king, Solomon”</span>made for himself a sedan chair  from the wood of Lebanon.'),
('LEB', 'Song of Solomon', '3', '10', '5', 'He made its column of silver, its back<span class=\"note\">Or “its support,” “its base,” “its headrest,” “its litter,” “its cover”</span>of gold, its seat of purple;  its interior is inlaid <span class=\"supplied\">with</span> leather<span class=\"note\">Or “love.” The Hebrew term here translated “leather” is spelled the same as the term for “love.” Most likely this is an example of a word play that puns on the intentional ambiguity: “Its interior was inlaid with leather//love by the maidens of Jerusalem”</span>by <span class=\"idiom\">the maidens of Jerusalem</span>.<span class=\"note\">“by the daughters of Jerusalem”</span>'),
('LEB', 'Song of Solomon', '3', '11', '5', 'Come out and look, <span class=\"idiom\">O maidens of Zion</span>,<span class=\"note\">“O daughters of Zion”</span>at <span class=\"idiom\">King Solomon</span>,<span class=\"note\">“the king, Solomon”</span> at the crown with which his mother crowned him  on the day of his wedding,  on the day of the joy of his heart!')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '4', '1', '1', '<span class=\"verse-title\">Groom’s Praise of His Bride</span><span class=\"idiom\">Oh my</span>!<span class=\"note\">“Behold!” Or “Look!”</span>You <span class=\"supplied\">are</span> beautiful, my beloved!  <span class=\"idiom\">Oh my</span>!<span class=\"note\">“Behold!” Or “Look!”</span>You <span class=\"supplied\">are</span> beautiful!  Your eyes <span class=\"supplied\">are</span> doves  from behind your veil.  Your hair <span class=\"supplied\">is</span> like a flock of goats  that move down from the mountains of Gilead.'),
('LEB', 'Song of Solomon', '4', '2', '1', 'Your teeth <span class=\"supplied\">are</span> like a flock of shorn ewes  that came up from the washing,  all of them bearing twins,  and there is none bereaved among them.'),
('LEB', 'Song of Solomon', '4', '3', '1', 'Your lips <span class=\"supplied\">are</span> like a thread of crimson,  and your mouth <span class=\"supplied\">is</span> lovely.  Your temple <span class=\"supplied\">is</span> like pomegranate  from behind your veil.'),
('LEB', 'Song of Solomon', '4', '4', '1', 'Your neck <span class=\"supplied\">is</span> like the tower of David,  built in courses;  a thousand <span class=\"idiom\">ornaments</span><span class=\"note\">“shields”</span>are hung on it,  all the shields of the warriors.'),
('LEB', 'Song of Solomon', '4', '5', '1', 'Your two breasts <span class=\"supplied\">are</span> like two fawns,  twins of a gazelle that feed among the lilies.'),
('LEB', 'Song of Solomon', '4', '6', '1', 'Until the day breathes and the shadows flee,  I will go to the mountain of the myrrh,  to the hill of the frankincense.'),
('LEB', 'Song of Solomon', '4', '7', '1', 'You <span class=\"supplied\">are</span> completely beautiful, my beloved!  <span class=\"idiom\">You are flawless</span>!<span class=\"note\">“There is no flaw in you!”</span>'),
('LEB', 'Song of Solomon', '4', '8', '3', '<span class=\"verse-title\">The Mountains and Fragrance of Lebanon</span>Come<span class=\"note\">Or “You must come”</span>with me from Lebanon, my bride!  Come with me<span class=\"note\">Or “With me”</span>from Lebanon!  Look from the top of Amana,  from the top of Senir and Hermon,  from the dwelling places of the lions,  from the mountains of leopard.'),
('LEB', 'Song of Solomon', '4', '9', '3', 'You have stolen (my) heart, my sister bride!  You have stolen <span class=\"supplied\">my</span> heart with one <span class=\"supplied\">glance</span> from your eyes,  with one ornament from your necklaces.'),
('LEB', 'Song of Solomon', '4', '10', '3', 'How beautiful is your love, my sister bride!  How better is your love than wine,  and the fragrance of your oils than any spice!'),
('LEB', 'Song of Solomon', '4', '11', '3', 'Your lips drip nectar, <span class=\"supplied\">my</span> bride;  honey and milk <span class=\"supplied\">are</span> under your lips;  the scent of your garments <span class=\"supplied\">is</span> like the scent of Lebanon.'),
('LEB', 'Song of Solomon', '4', '12', '5', '<span class=\"verse-title\">The Locked Garden of Delights Is Unlocked</span>A garden locked <span class=\"supplied\">is</span> my sister bride,  a spring enclosed,<span class=\"note\">Or “a source locked”</span>a fountain sealed.'),
('LEB', 'Song of Solomon', '4', '13', '5', 'Your shoots<span class=\"note\">Or “your channel”</span><span class=\"supplied\">are</span> an orchard of pomegranates with <span class=\"idiom\">choice fruit</span>,<span class=\"note\">“fruit of choice things”</span> henna with nard;'),
('LEB', 'Song of Solomon', '4', '14', '5', 'nard and saffron, calamus and cinnamon spice with all trees of frankincense,  myrrh and aloes with all chief spices.'),
('LEB', 'Song of Solomon', '4', '15', '5', 'A garden fountain, a well of living water,  flowing (streams) from Lebanon.'),
('LEB', 'Song of Solomon', '4', '16', '5', 'Awake, O north wind! Come, O south wind!  Blow upon my garden! Let its fragrances<span class=\"note\">Or “perfumes”</span>waft forth!<span class=\"note\">Or “His perfumes can waft down”</span> Let my beloved come to his garden,  let him eat his choice fruit!')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '5', '1', '0', 'I have come to my garden, my sister bride,  I have gathered my myrrh with my spice,  I have eaten my honeycomb with my honey,  I have drunk my wine with my milk!  Eat, O friends! <span class=\"idiom\">Drink and become drunk <span class=\"supplied\">with</span> love</span>!<span class=\"note\">Or “Drink and become drunk, O lovers!”</span>'),
('LEB', 'Song of Solomon', '5', '2', '2', '<span class=\"verse-title\">Maiden’s Dream: Seeking and Not Finding</span>I <span class=\"supplied\">was</span> asleep but<span class=\"note\">Or “and”</span>my heart was awake.  A sound! My beloved knocking!<span class=\"note\">Or “The sound of my beloved knocking!”</span> “Open to me, my sister, my beloved,  my dove, my perfect one!  For my head is full of dew,  <span class=\"idiom\">my hair drenched from the moist night air</span>.”<span class=\"note\">“my locks with drops of night”</span>'),
('LEB', 'Song of Solomon', '5', '3', '2', 'I have taken off my tunic, <span class=\"idiom\">must I put it on</span>?<span class=\"note\">“How will I put it on?”</span> I have bathed my feet, <span class=\"idiom\">must I soil them</span>?<span class=\"note\">“How will I soil them?”</span>'),
('LEB', 'Song of Solomon', '5', '4', '2', 'My beloved thrust his hand into the opening,  and my inmost yearned for him.'),
('LEB', 'Song of Solomon', '5', '5', '2', 'I myself arose to open to my beloved;  my hands dripped with myrrh,  my fingers with liquid myrrh  upon the handles of the bolt.'),
('LEB', 'Song of Solomon', '5', '6', '2', 'I opened myself to my beloved,  but my beloved had turned and gone;<span class=\"note\">Or “my beloved had left; he was gone”</span> my heart sank<span class=\"note\">Or “my soul left”</span>when he turned away.<span class=\"note\">Or “when he was speaking.” Translations equivocate on how to translate this verb, since there are two terms in Hebrew spelled identically: “to speak” and “to turn aside” (HALOT 1:210). The context suggests the latter</span> I sought him, but I did not find him;  I called him, but he did not answer me.'),
('LEB', 'Song of Solomon', '5', '7', '2', 'The sentinels making rounds in the city found me;  they beat me, they wounded me;  they took my cloak<span class=\"note\">Or “mantle”</span>away from me—  <span class=\"idiom\">those sentinels on the walls</span>!<span class=\"note\">“the sentinels of the walls”</span>'),
('LEB', 'Song of Solomon', '5', '8', '4', '<span class=\"verse-title\">Adjuration Refrain</span>I adjure you, <span class=\"idiom\">O maidens of Jerusalem</span>,<span class=\"note\">“O daughters of Jerusalem”</span> if you find my beloved, what will you tell him?  <span class=\"supplied\">Tell him</span> that I am <span class=\"idiom\">lovesick</span>!<span class=\"note\">“sick <span class=\"supplied\">with</span> love”</span>'),
('LEB', 'Song of Solomon', '5', '9', '6', '<span class=\"verse-title\">Maiden’s Praise of Her Beloved</span><span class=\"idiom\">How is your beloved better than another lover</span>,<span class=\"note\">“What <span class=\"supplied\">is</span> your beloved more than <span class=\"supplied\">another</span> beloved …?”</span> O most beautiful among women?  <span class=\"idiom\">How is your beloved better than another lover</span>, <span class=\"note\">“What <span class=\"supplied\">is</span> your beloved more than <span class=\"supplied\">another</span> beloved …?”</span> that you adjure us thus?'),
('LEB', 'Song of Solomon', '5', '10', '6', 'My beloved <span class=\"supplied\">is</span> radiant and <span class=\"idiom\">ruddy</span>,<span class=\"note\">“red”</span> distinguished <span class=\"idiom\">among</span><span class=\"note\">“more than”</span>ten thousand.'),
('LEB', 'Song of Solomon', '5', '11', '6', 'His head <span class=\"supplied\">is</span> gold, refined gold;  his locks <span class=\"supplied\">are</span> wavy, black as a raven.'),
('LEB', 'Song of Solomon', '5', '12', '6', 'His eyes <span class=\"supplied\">are</span> like doves beside springs<span class=\"note\">Or “streams”</span>of water,  bathed in milk, <span class=\"idiom\">set like mounted jewels</span>.<span class=\"note\">“dwelling in a setting”</span><span class=\"note\">Or “seated at a <span class=\"supplied\">suitable</span> mounting”</span>'),
('LEB', 'Song of Solomon', '5', '13', '6', 'His cheeks <span class=\"supplied\">are</span> like beds of spice, a tower of fragrances;  his lips <span class=\"supplied\">are</span> lilies dripping liquid myrrh.'),
('LEB', 'Song of Solomon', '5', '14', '6', 'His arms <span class=\"supplied\">are</span> <span class=\"idiom\">rods</span><span class=\"note\">“cylinders”</span><span class=\"note\">Or “rings”</span>of gold <span class=\"idiom\">engraved with</span><span class=\"note\">“filled with”</span>jewels;  his belly<span class=\"note\">Or “body”</span><span class=\"supplied\">is</span> polished ivory covered with sapphires.<span class=\"note\">Or “works of ivory set with sapphire”</span>'),
('LEB', 'Song of Solomon', '5', '15', '6', 'His legs <span class=\"supplied\">are</span> columns of alabaster,<span class=\"note\">Or “marble”</span>set on bases of gold;  his appearance <span class=\"supplied\">is</span> like Lebanon, choice as <span class=\"idiom\">its cedars</span>.<span class=\"note\">“the cedars”</span>'),
('LEB', 'Song of Solomon', '5', '16', '6', '<span class=\"idiom\">His mouth</span><span class=\"note\">Or “his palate”</span><span class=\"supplied\">is</span> sweet,  and he is altogether desirable.  This <span class=\"supplied\">is</span> my beloved;  this <span class=\"supplied\">is</span> my friend, <span class=\"idiom\">O young women of Jerusalem</span>.<span class=\"note\">“O daughters of Jerusalem”</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '6', '1', '0', 'Where has your beloved gone,  O most beautiful among women?  Where has your beloved turned  that we may seek him with you?'),
('LEB', 'Song of Solomon', '6', '2', '0', 'My beloved has gone down to his garden,  to the garden bed of the spice,  to pasture his flock and to gather lilies in the garden.'),
('LEB', 'Song of Solomon', '6', '3', '2', '<span class=\"verse-title\">Mutual Possession Refrain</span><span class=\"idiom\">I belong to my beloved and he belongs to me</span>;<span class=\"note\">“I for my beloved and he for me”</span> he pastures his flock among the lilies.'),
('LEB', 'Song of Solomon', '6', '4', '4', '<span class=\"verse-title\">Solomon’s Praise of His Beloved</span>You <span class=\"supplied\">are</span> beautiful, my beloved, as Tirzah,  lovely as Jerusalem,  <span class=\"idiom\">overwhelming as an army with banners</span>.<span class=\"note\">“terrible as the bannered ones”</span>'),
('LEB', 'Song of Solomon', '6', '5', '4', 'Turn away your eyes from before me,  for they overwhelm me.  Your hair <span class=\"supplied\">is</span> like a flock of the goats  that moves down from Gilead.'),
('LEB', 'Song of Solomon', '6', '6', '4', 'Your teeth <span class=\"supplied\">are</span> like a flock of the ewes  that have come up from the washing,  all of them bearing twins,  and there is none bereaved among them.'),
('LEB', 'Song of Solomon', '6', '7', '4', 'Your cheeks <span class=\"idiom\">behind</span><span class=\"note\">“from behind”</span>your veil  <span class=\"supplied\">are</span> like halves of a pomegranate.'),
('LEB', 'Song of Solomon', '6', '8', '6', '<span class=\"verse-title\">The Maiden’s Beauty Is without Peer</span>Sixty queens there <span class=\"supplied\">are</span>, eighty concubines,  and maidens beyond number.'),
('LEB', 'Song of Solomon', '6', '9', '6', 'My dove, <span class=\"idiom\">she is the one</span>;<span class=\"note\">“she <span class=\"supplied\">is</span> one”</span><span class=\"note\">The term “one” functions here as an adjective of quality: “unique, singular, the only one”</span> my perfect, <span class=\"idiom\">she is the only one</span>;<span class=\"note\">“she <span class=\"supplied\">is</span> one”</span><span class=\"note\">Or “the only daughter of her mother.” Although the latter option is permissible, the term is used elsewhere of the heir as the favored child (e.g., Gen 22:2; Prov 4:3). This nuance is supported by the parallel term “favorite”</span> she <span class=\"supplied\">is</span> <span class=\"idiom\">the favorite of</span><span class=\"note\">Or “she <span class=\"supplied\">is</span> the pure one.” Since there are two Hebrew terms spelled the same way, some relate this to the adjective that means “pure.” Others relate it to the verb that means “to choose, select.” The parallelism favors the latter</span><span class=\"note\">“the favorite for”</span>her mother who bore her.  Maidens see her and consider her fortunate;<span class=\"note\">Or “call her happy” or “call her blessed” or “bless her”</span> queens and concubines praise her:'),
('LEB', 'Song of Solomon', '6', '10', '6', '“Who <span class=\"supplied\">is</span> this that looks down like the dawn,  beautiful as the moon,  <span class=\"idiom\">bright as the sun</span>,<span class=\"note\">“pure as the glow”</span><span class=\"note\">Or “bright as the heat of the sun.” The Hebrew term “glow” poetically refers to the bright rays of the sun (Psa 19:7; Isa 24:23; 30:26)</span> <span class=\"idiom\">overwhelming as an army with banners</span>?”<span class=\"note\">“terrible as the bannered ones”</span>'),
('LEB', 'Song of Solomon', '6', '11', '8', '<span class=\"verse-title\">The Journey to the Valley</span>I went down to the orchard of the walnut trees  to look at the blossoms of the valley,  to see <span class=\"supplied\">whether</span> the vine<span class=\"supplied\">s</span> have sprouted,  <span class=\"supplied\">whether</span> the pomegranates have blossomed.'),
('LEB', 'Song of Solomon', '6', '12', '8', 'I did not know my <span class=\"idiom\">heart</span><span class=\"note\">“soul”</span>set me  <span class=\"supplied\">in</span> a chariot of my princely people.<span class=\"note\">Or “Before I was aware, my soul made me like the chariots of Amminadib” (KJV, ASV) or “Before I knew it, my desire set me mid the chariots of Ammi-nadib” (JPS) or “Before I was aware, my soul set me over the chariots of my noble people” (NASB) or “Before I realized it, my desire set me among the royal chariots of my people” (NIV) or “… among the chariots of Amminadab” (NIV margin) or “… among the chariots of the people of the prince” (NIV margin)</span>'),
('LEB', 'Song of Solomon', '6', '13', '8', '<span class=\"note\">Song of Songs 6:13–7:13 in the English Bible is 7:1–14 in the Hebrew Bible</span>Turn, turn,<span class=\"note\">Or “Return, return …!”</span>O Shulammite!<span class=\"note\">Or “O perfect one,” “O peaceful one,” “O bride.” Many interpreters take this moniker as suggesting the maiden was from the village of Shulem (alternately called Shunem)</span> Turn, turn<span class=\"note\">Or “Return, return …!”</span>so that we may look upon you!  Why do you look upon the Shulammite  as <span class=\"supplied\">at</span> a dance of the two armies?')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '7', '1', '1', '<span class=\"verse-title\">Solomon’s Praise of His Dancing Maiden</span>How beautiful are your feet in sandals,  O royal princess!<span class=\"note\">Or “O daughter of leader”</span> The curves of your <span class=\"idiom\">thighs</span><span class=\"note\">“thigh”</span><span class=\"supplied\">are</span> like <span class=\"idiom\">jewels</span>,<span class=\"note\">“ornaments”</span> the work of the hands of a craftsman.'),
('LEB', 'Song of Solomon', '7', '2', '1', 'Your navel <span class=\"supplied\">is</span> <span class=\"idiom\">a round wine-mixing bowl</span><span class=\"note\">“a bowl of the roundness”</span> that does not lack mixed<span class=\"note\">Or “blended”</span>wine!  Your belly <span class=\"supplied\">is</span> a heap of wheat  encircled with lilies.'),
('LEB', 'Song of Solomon', '7', '3', '1', 'Your two breasts <span class=\"supplied\">are</span> like two fawns,  twins of a gazelle.'),
('LEB', 'Song of Solomon', '7', '4', '1', 'Your neck <span class=\"supplied\">is</span> like a tower of ivory;  your eyes <span class=\"supplied\">are</span> pools in Heshbon at the gate of Beth Rabbim.  Your nose <span class=\"supplied\">is</span> like the tower of Lebanon  <span class=\"idiom\">looking out over Damascus</span>.<span class=\"note\">“looking out over the face of Damascus”</span>'),
('LEB', 'Song of Solomon', '7', '5', '1', '<span class=\"idiom\">Your head crowns you like Carmel</span>;<span class=\"note\">“Your head <span class=\"supplied\">is</span> on you like the Carmel”</span><span class=\"note\">Because of its height and fertility, Mount Carmel is often associated with royalty</span> the flowing locks of your head <span class=\"supplied\">are</span> like <span class=\"idiom\">purple tapestry</span>;<span class=\"note\">“the purple”</span> a king is held captive in the tresses!'),
('LEB', 'Song of Solomon', '7', '6', '1', 'How beautiful you are and how pleasant,  O loved one in the delights!'),
('LEB', 'Song of Solomon', '7', '7', '1', '<span class=\"idiom\">Your stature</span><span class=\"note\">“this your height”</span><span class=\"supplied\">is</span> like the palm tree,  and your breasts <span class=\"supplied\">are</span> like clusters.'),
('LEB', 'Song of Solomon', '7', '8', '1', 'I say, “I will climb up the palm tree;  I will lay hold of its fruit clusters.”  Let your breasts <span class=\"supplied\">be pleasing</span> like clusters of the vine  and the scent of your breath like the apples.'),
('LEB', 'Song of Solomon', '7', '9', '1', 'Your palate <span class=\"supplied\">is</span> like the best wine that goes down for my beloved,  smoothly gliding over my lips and teeth.<span class=\"note\">Or “over lips of sleepers.” One Hebrew textual tradition preserves the reading “lips of those who sleep” (MT). Another Hebrew tradition reads “my lips and my teeth,” as reflected by the ancient versions (LXX, Latin Vulgate, Aramaic Targum, Syriac Peshitta). The latter is adopted here since it makes the most sense poetically</span>'),
('LEB', 'Song of Solomon', '7', '10', '3', '<span class=\"verse-title\">Mutual Possession Refrain</span><span class=\"idiom\">I belong to my beloved</span>,<span class=\"note\">“I <span class=\"supplied\">am</span> for my beloved”</span> <span class=\"idiom\">and he desires me</span>!<span class=\"note\">“and his desire <span class=\"supplied\">is</span> for me.” Or “and his desire belongs to me”</span>'),
('LEB', 'Song of Solomon', '7', '11', '5', '<span class=\"verse-title\">Rendezvous in the Countryside</span>Come, my beloved, let us <span class=\"idiom\">go out to the countryside</span>;<span class=\"note\">“go forth into the field”</span> let us spend the night<span class=\"note\">Or “lodge”</span>in the villages.'),
('LEB', 'Song of Solomon', '7', '12', '5', 'Let us rise early <span class=\"supplied\">to go</span><span class=\"note\">Or “let us go”</span>to the vineyards;  let us see whether the vine has budded,<span class=\"note\">Or “sprouted”</span> <span class=\"supplied\">whether</span> the grape blossom has opened,  and <span class=\"supplied\">whether</span> the pomegranates <span class=\"idiom\">are in bloom</span>;<span class=\"note\">“have bloomed”</span> there I will give my love to you.'),
('LEB', 'Song of Solomon', '7', '13', '5', 'The mandrakes give <span class=\"supplied\">off their</span> fragrance,  and <span class=\"idiom\">over our doorway is every kind of delicious fruit</span>;<span class=\"note\">Or “over our doorways all choice <span class=\"supplied\">things</span>”</span> both <span class=\"idiom\">fresh and dried fruit I have stored up</span><span class=\"note\">“new also old I have laid up”</span>for you, O my beloved.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Song of Solomon', '8', '1', '1', '<span class=\"verse-title\">Maiden’s Fanciful Wish</span><span class=\"idiom\">How I wish that you were my little brother</span>,<span class=\"note\">“O that he would give you like a brother to me”</span><span class=\"note\">The Hebrew construction (which is somewhat misleading if rendered in a woodenly literal sense) is an idiom expressing one’s fanciful wish</span> <span class=\"supplied\">who</span> nursed <span class=\"idiom\">upon my mother’s breasts</span>!<span class=\"note\">“at the breast of my mother”</span> <span class=\"supplied\">If</span> <span class=\"idiom\">I met you outside</span>,<span class=\"note\">“I will find you in the street”</span>I would kiss you,  <span class=\"idiom\">and no one would despise me</span>!<span class=\"note\">“also they would not despise me”</span>'),
('LEB', 'Song of Solomon', '8', '2', '1', '<span class=\"idiom\">I would surely bring you</span><span class=\"note\">“I would lead you and I would bring you”</span><span class=\"note\">The combination of the two verbs creates a hendiadys which may be rendered more cogently as “I would surely bring you …”</span>to the house of my mother,  <span class=\"idiom\">who would surely teach me</span>;<span class=\"note\">“she will teach me”</span> <span class=\"idiom\">I would give you spiced wine to drink</span>,<span class=\"note\">“I would give you to drink from the wine of the spice”</span> the <span class=\"idiom\">sweet wine</span><span class=\"note\">Or “juice”</span>of my pomegranates.<span class=\"note\">The traditional Hebrew reads the singular “my pomegranate.” However, the plural reading “my pomegranates” is attested in numerous medieval Hebrew manuscripts and is reflected in the ancient versions (Greek Septuagint, Aramaic Targum, Syriac Peshitta). The latter makes the most sense in this context as a euphemistic description of the maiden’s delights</span>'),
('LEB', 'Song of Solomon', '8', '3', '3', '<span class=\"verse-title\">Double Refrain: Embrace and Adjuration</span>His left <span class=\"supplied\">hand is</span> under my head,  and his right <span class=\"supplied\">hand</span> embraces<span class=\"note\">Or “embraced”</span>me.'),
('LEB', 'Song of Solomon', '8', '4', '3', 'I adjure you, <span class=\"idiom\">O maidens of Jerusalem</span>,<span class=\"note\">“O daughters of Jerusalem”</span> do not<span class=\"note\">Or “Why must you … before it pleases?”</span>arouse or awaken love until it pleases!<span class=\"note\">Or “Do not stir up or awaken the love until it is willing,” or “Do not disturb or interrupt <span class=\"supplied\">our</span> lovemaking until it is satisfied”</span>'),
('LEB', 'Song of Solomon', '8', '5', '5', '<span class=\"verse-title\">Up from the Wilderness and under the Apple Tree</span>Who <span class=\"supplied\">is</span> this coming up from the wilderness,  leaning upon her beloved?  Under the apple tree I awakened you;  there your mother <span class=\"idiom\">conceived you</span>;<span class=\"note\">“was in labor with you”</span> there she who was in labor gave birth to you.'),
('LEB', 'Song of Solomon', '8', '6', '7', '<span class=\"verse-title\">The Nature of Genuine Romantic Love</span>Set me as a seal upon your heart,  as a seal upon your arm;  for love <span class=\"supplied\">is</span> strong as death;  passion <span class=\"supplied\">is</span> fierce as Sheol;  its flashes <span class=\"supplied\">are</span> flashes of fire;  <span class=\"supplied\">it is</span> a blazing flame.'),
('LEB', 'Song of Solomon', '8', '7', '7', 'Many waters cannot quench love;  rivers cannot sweep it away.<span class=\"note\">Or “and rivers cannot engulf it”</span> If a man were to give all the wealth of his house <span class=\"idiom\">for love</span>,<span class=\"note\">“in the love”</span> he would be utterly scorned.<span class=\"note\">“they will utterly scorn him”</span>'),
('LEB', 'Song of Solomon', '8', '8', '9', '<span class=\"verse-title\">Maiden’s Virtuous Chastity and Voluptuous Beauty</span><span class=\"idiom\">We have a little sister</span>,<span class=\"note\">“a little sister for us”</span> <span class=\"idiom\">and she does not yet have any breasts</span>.<span class=\"note\">“and there is no breast for her”</span> What should we do for our sister  <span class=\"idiom\">on the day when she is betrothed</span>?<span class=\"note\">“on the day when it is spoken of her”</span><span class=\"note\">Or “on the day when she is spoken for”</span>'),
('LEB', 'Song of Solomon', '8', '9', '9', 'If she <span class=\"supplied\">is</span> a wall,  <span class=\"idiom\">we will adorn her with a turret of silver</span>;<span class=\"note\">“we will build upon her a camp of silver”</span><span class=\"note\">The term translated “turret” refers to the decorative parapet adorning the top of a building. This image is likely figurative for a silver tiara set upon the head</span> but if she <span class=\"supplied\">is</span> a door,  we will barricade her with boards of cedar.<span class=\"note\">Or “we will enclose her”</span>'),
('LEB', 'Song of Solomon', '8', '10', '9', 'I <span class=\"supplied\">was</span> a wall, and my breasts <span class=\"supplied\">were</span> like the towers,  <span class=\"idiom\">so <span class=\"supplied\">my betrothed</span> viewed me with great delight</span>.<span class=\"note\">“then I was in his eyes as <span class=\"supplied\">one who</span> finds peace”</span>'),
('LEB', 'Song of Solomon', '8', '11', '11', '<span class=\"verse-title\">Solomon’s Vineyard and the Maiden’s Gift</span><span class=\"idiom\">Solomon had a vineyard</span><span class=\"note\">“A vineyard was for Solomon”</span>at Baal-hamon;  <span class=\"idiom\">he entrusted his vineyard to the keepers</span>;<span class=\"note\">“he gave the vineyard to the keepers”</span> <span class=\"idiom\">people paid a thousand silver <span class=\"supplied\">pieces</span> for its fruit</span>.<span class=\"note\">“each one brought a thousand silver <span class=\"supplied\">pieces</span> for his fruit”</span>'),
('LEB', 'Song of Solomon', '8', '12', '11', '<span class=\"idiom\">My own “vineyard” belongs to me</span>;<span class=\"note\">“My vineyard that for me before my face”</span> the “thousand” are for you, O Solomon,  <span class=\"idiom\">and “two hundred” for those who tend its fruit</span>.<span class=\"note\">“and two hundred for <span class=\"supplied\">the</span> keepers <span class=\"supplied\">of</span> his fruit”</span>'),
('LEB', 'Song of Solomon', '8', '13', '13', '<span class=\"verse-title\">Closing Words of Mutual Love</span>O you who dwell in the garden,  <span class=\"supplied\">my</span> companions are listening to your voice.  Let me hear <span class=\"supplied\">it</span>!'),
('LEB', 'Song of Solomon', '8', '14', '13', 'Flee, my beloved!  <span class=\"idiom\">Be like a gazelle</span><span class=\"note\">“and be like for you to a gazelle”</span>or <span class=\"idiom\">a young stag</span><span class=\"note\">“to the fawn of the stag”</span> upon <span class=\"idiom\">the perfumed mountains</span>!<span class=\"note\">“the mountains of spices”</span>')
;

