INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '1', '1', '0', 'In the eighth month, in the second year of Darius, the word of Adonai came<span class=\"note\">Literally “was”</span>to the prophet Zechariah son of Berekiah, son of Iddo, saying,'),
('LEB', 'Zechariah', '1', '2', '0', '“Adonai <span class=\"idiom\">was very angry with your ancestors</span>.<span class=\"note\">Literally “was angry against your ancestors <span class=\"supplied\">with</span> anger”</span>'),
('LEB', 'Zechariah', '1', '3', '0', 'You must say to them: ‘Thus says Adonai of hosts: “Return to me,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts, “and I will return to you,” says Adonai of hosts.'),
('LEB', 'Zechariah', '1', '4', '0', '“Do not be like your ancestors,<span class=\"note\">Or “fathers”</span>to whom the former prophets proclaimed, saying, ‘Thus says Adonai of hosts: “Return from your evil ways and your evil deeds!” ’ But they did not hear<span class=\"note\">Or “listen”</span>and they did not pay attention<span class=\"note\">Or “give heed”</span>to me,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai.'),
('LEB', 'Zechariah', '1', '5', '0', '“Your ancestors,<span class=\"note\">Or “fathers”</span>where are they? And the prophets, do they live forever?'),
('LEB', 'Zechariah', '1', '6', '0', 'However, did not my words and my regulations which I commanded my servants the prophets overtake your ancestors?<span class=\"note\">Or “fathers”</span>And they repented and said, ‘Adonai of hosts planned to do with us according to our ways, and according to our deeds so he has dealt with us.’ ” ’ ”'),
('LEB', 'Zechariah', '1', '7', '2', '<span class=\"verse-title\">Zechariah’s First Vision</span>On the twenty-fourth day of <span class=\"supplied\">the</span> eleventh month, the month of Shebat, in the second year of Darius, the word of Adonai came to Zechariah the prophet, son of Berekiah, son of Iddo, saying,'),
('LEB', 'Zechariah', '1', '8', '2', '<span class=\"idiom\">I had a vision in the night</span>,<span class=\"note\">Literally “I saw the night,” which means “I had a vision”</span>and look, a man riding on a red horse. And he <span class=\"supplied\">was</span> standing between the myrtle shrubs that <span class=\"supplied\">were</span> in the ravine, and behind him <span class=\"supplied\">were</span> red, reddish-brown, and white horses.'),
('LEB', 'Zechariah', '1', '9', '2', 'And I asked, “What <span class=\"supplied\">are</span> these, my lord?” And the angel <span class=\"supplied\">who was</span> talking with me said, “I will show you what these are.”'),
('LEB', 'Zechariah', '1', '10', '2', 'And the man standing between the myrtle shrubs answered and said, “These <span class=\"supplied\">are</span> those whom Adonai has sent to patrol<span class=\"note\">Or “to go about,” or “to walk through”</span><span class=\"supplied\">the</span> earth.”'),
('LEB', 'Zechariah', '1', '11', '2', 'And they answered the angel of Adonai who was standing between the myrtle shrubs, and they said, “We have patrolled<span class=\"note\">Or “have gone about,” or “have walked through”</span>the earth, and look, all the earth <span class=\"idiom\">is dwelling in peace</span>.”<span class=\"note\">Literally “<span class=\"supplied\">is</span> dwelling and <span class=\"supplied\">is</span> at rest”</span>'),
('LEB', 'Zechariah', '1', '12', '2', 'The angel of Adonai answered and said, “O Adonai of hosts, <span class=\"idiom\">how long</span><span class=\"note\">Literally “until when”</span>will you have no compassion on Jerusalem and the cities of Judah, <span class=\"supplied\">with</span> which you showed fury these seventy years?”<span class=\"note\">Hebrew “year”</span>'),
('LEB', 'Zechariah', '1', '13', '2', '<span class=\"supplied\">With</span> gracious<span class=\"note\">Or “kind”; literally “good”</span>and comforting words Adonai answered the angel who was talking with me.'),
('LEB', 'Zechariah', '1', '14', '2', 'And the angel who was talking with me said to me, “Proclaim, saying, ‘Thus says Adonai of hosts: “<span class=\"idiom\">I am very jealous</span><span class=\"note\">Literally “I am jealous <span class=\"supplied\">with</span> a great jealousy”</span>for Jerusalem and for Zion!'),
('LEB', 'Zechariah', '1', '15', '2', 'And <span class=\"idiom\">I am extremely angry</span><span class=\"note\">Literally “<span class=\"supplied\">With</span> a great anger I am angry”</span>with the nations that are at ease, for <span class=\"supplied\">while</span> I was a little angry, they <span class=\"idiom\">furthered disaster</span>.”<span class=\"note\">Literally “helped disaster”</span>'),
('LEB', 'Zechariah', '1', '16', '2', 'Therefore, thus says Adonai: “I have returned to Jerusalem with compassion. My temple<span class=\"note\">Or “house”</span>will be built in it,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai of hosts, “and a measuring line will be stretched out over Jerusalem.” ’'),
('LEB', 'Zechariah', '1', '17', '2', 'Proclaim again, saying, ‘Thus says Adonai of hosts: “My cities shall again overflow from prosperity, and Adonai will comfort Zion again, and he will choose Jerusalem again.” ’ ”'),
('LEB', 'Zechariah', '1', '18', '4', '<span class=\"verse-title\">Zechariah’s Second Vision</span><span class=\"note\">Zechariah 1:18–2:17 in the English Bible is 2:1–13 in the Hebrew Bible</span>And I <span class=\"idiom\">looked up</span><span class=\"note\">Literally “lifted up my eyes”</span>and I saw, and look, <span class=\"supplied\">there were</span> four horns!'),
('LEB', 'Zechariah', '1', '19', '4', 'And I said to the angel <span class=\"supplied\">who was</span> talking with me, “What <span class=\"supplied\">are</span> these?” And he said to me, “These <span class=\"supplied\">are</span> the horns that have scattered Judah, Israel, and Jerusalem.”'),
('LEB', 'Zechariah', '1', '20', '4', 'Then Adonai showed me four skilled craftsmen,'),
('LEB', 'Zechariah', '1', '21', '4', 'and I asked, “What <span class=\"supplied\">are</span> these coming to do?” And he answered, saying, “These <span class=\"supplied\">are</span> the horns that scattered Judah, <span class=\"idiom\">so that no man</span><span class=\"note\">Literally “according to the mouth of a man”</span>lifted up his head; but these have come to frighten them, to strike down the horns of the nations that lifted a horn against the land of Judah to scatter it.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '2', '1', '1', '<span class=\"verse-title\">Zechariah’s Third Vision</span>And I <span class=\"idiom\">looked up</span><span class=\"note\">Literally “lifted up my eyes”</span>and I saw, and look, a man, and in his hand <span class=\"supplied\">was</span> a measuring rope!'),
('LEB', 'Zechariah', '2', '2', '1', 'And I asked, “Where <span class=\"supplied\">are</span> you going?” And he answered me, “To measure Jerusalem to see what <span class=\"supplied\">is</span> its width and what <span class=\"supplied\">is</span> its length.”'),
('LEB', 'Zechariah', '2', '3', '1', 'And look, the angel who was talking to me <span class=\"supplied\">was</span> coming forward, and another angel <span class=\"supplied\">was</span> coming forward to meet him.'),
('LEB', 'Zechariah', '2', '4', '1', 'And he said to him, “Run, say to that young man, ‘Jerusalem shall be inhabited <span class=\"idiom\">like villages without walls</span><span class=\"note\">Literally “<span class=\"supplied\">like</span> open regions”</span>because of the multitude of people and animals in its midst.'),
('LEB', 'Zechariah', '2', '5', '1', 'And I will be for it a wall of fire all around,’ <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai, ‘and I will be <span class=\"supplied\">the</span> glory in its midst.’ ”'),
('LEB', 'Zechariah', '2', '6', '2', '“Woe! Woe! Flee from <span class=\"supplied\">the</span> land of <span class=\"supplied\">the</span> north,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai, “for I have scattered you like <span class=\"supplied\">the</span> four winds of the heavens,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai.'),
('LEB', 'Zechariah', '2', '7', '2', '“Woe, Zion! Escape, you inhabitants of <span class=\"supplied\">the</span> daughter of Babylon!”'),
('LEB', 'Zechariah', '2', '8', '2', 'For thus said Adonai of hosts, after glory<span class=\"note\">The phrase “after glory” is difficult to interpret</span>he sent me against the nations plundering you: Truly, the one touching you <span class=\"supplied\">is</span> touching the apple<span class=\"note\">Hebrew “pupil,” but the expression “apple of his eye” has become well-established in English</span>of his eye.'),
('LEB', 'Zechariah', '2', '9', '2', '“Yes, look! I <span class=\"supplied\">am</span> going to wave my hand against them, and they will become plunder for their servants, and you will know that Adonai of hosts has sent me.'),
('LEB', 'Zechariah', '2', '10', '2', 'Sing and rejoice, O daughter of Zion, for look, I <span class=\"supplied\">am</span> coming and I will dwell in your midst,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “a declaration of”</span>Adonai.'),
('LEB', 'Zechariah', '2', '11', '2', '“Many nations will join themselves to Adonai on that day, and they will be my people, and I will dwell in your midst. And you will know that Adonai of hosts has sent me to you.'),
('LEB', 'Zechariah', '2', '12', '2', 'And Adonai will inherit Judah <span class=\"supplied\">as</span> his portion <span class=\"idiom\">in the holy land</span>,<span class=\"note\">Literally “upon <span class=\"supplied\">the</span> land of the holiness”</span>and he will again choose Jerusalem.'),
('LEB', 'Zechariah', '2', '13', '2', 'Be silent, <span class=\"idiom\">all people</span>,<span class=\"note\">Literally “all flesh”</span>before Adonai, for he is roused from <span class=\"idiom\">his holy dwelling</span>.”<span class=\"note\">Literally “the dwelling place of his holiness”</span>')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '3', '1', '1', '<span class=\"verse-title\">Zechariah’s Fourth Vision</span>And he showed me Joshua the high priest standing <span class=\"idiom\">before</span><span class=\"note\">Literally “to the face of”</span>the angel of Adonai; and Satan<span class=\"note\">Hebrew “the accuser,” or “the adversary”</span>was standing on his right to accuse him.'),
('LEB', 'Zechariah', '3', '2', '1', 'But Adonai said to Satan,<span class=\"note\">Hebrew “the accuser,” or “the adversary”</span>“Adonai rebukes you, O Satan!<span class=\"note\">Hebrew “the accuser,” or “the adversary”</span>Adonai who has chosen Jerusalem rebukes you! <span class=\"supplied\">Is</span> this not a stick snatched from the fire?”'),
('LEB', 'Zechariah', '3', '3', '1', 'And Joshua was clothed <span class=\"supplied\">in</span> filthy garments and was standing <span class=\"idiom\">before</span><span class=\"note\">Literally “to the face of”</span>the angel.'),
('LEB', 'Zechariah', '3', '4', '1', 'And he answered and said to the ones standing <span class=\"idiom\">before</span><span class=\"note\">Literally “to the face of”</span>him, saying, “Remove the filthy garments from him.” And he said to him, “See, I have taken away your guilt<span class=\"note\">The Hebrew term refers to guilt caused by sin (HALOT 800 s.v. 2)</span>from you, and will clothe you <span class=\"supplied\">with</span> rich garments.”'),
('LEB', 'Zechariah', '3', '5', '1', 'And I said, “Let them put a clean headband<span class=\"note\">Or “turban”</span>on his head.” And they put a clean headband on his head, and they clothed him <span class=\"supplied\">with</span> garments. And the angel of Adonai <span class=\"supplied\">was</span> standing <span class=\"supplied\">by</span>.'),
('LEB', 'Zechariah', '3', '6', '2', 'And the angel of Adonai assured Joshua, saying,'),
('LEB', 'Zechariah', '3', '7', '2', '“Thus says Adonai of hosts: ‘If you will walk in my ways, and if you will keep my requirements, then you will judge<span class=\"note\">Or “govern”</span>my house, and you will also guard my courtyards, and I will give to you passageways<span class=\"note\">Or “right of access”</span>among these that are standing here.'),
('LEB', 'Zechariah', '3', '8', '2', 'Listen, please, O Joshua the high priest, you and your companions<span class=\"note\">Possibly his fellow priests</span>that are sitting <span class=\"idiom\">before</span><span class=\"note\">Literally “to the face of”</span>you. For <span class=\"supplied\">the</span> men <span class=\"supplied\">are</span> a sign that,<span class=\"note\">Hebrew “for”</span>look, I <span class=\"supplied\">am</span> going to bring my servant <span class=\"supplied\">the</span> Branch.<span class=\"note\">Hebrew “Sprout” or “Shoot” (“Branch” is a traditional rendering in English)</span>'),
('LEB', 'Zechariah', '3', '9', '2', 'For consider, the stone that <span class=\"idiom\">I set before</span><span class=\"note\">Literally “I gave to the face of, ”or “I gave in the presence of”</span>Joshua, on one stone <span class=\"supplied\">are</span> seven eyes.<span class=\"note\">Or “facets”</span>Look, <span class=\"idiom\">I am going to engrave an inscription on it</span>,’<span class=\"note\">Literally “I <span class=\"supplied\">am</span> going to engrave its engraving”</span><span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts, ‘and I will remove the guilt of that land in a single day.'),
('LEB', 'Zechariah', '3', '10', '2', 'On that day,’ <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts, ‘you will invite <span class=\"idiom\">one another</span><span class=\"note\">Literally “a man to his friend”</span>under <span class=\"supplied\">the</span> vine and under <span class=\"supplied\">the</span> fig tree.’ ”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '4', '1', '1', '<span class=\"verse-title\">Zechariah’s Fifth Vision</span>And the angel <span class=\"supplied\">who was</span> talking with me returned, and he wakened me as one who is wakened from his sleep.'),
('LEB', 'Zechariah', '4', '2', '1', 'And he said to me, “What do you see?” And I said, “I see, and look, <span class=\"idiom\">a lampstand all of gold</span>,<span class=\"note\">Literally “a lampstand of gold in its totality”</span>and a bowl <span class=\"supplied\">was</span> on its top, and its seven lamps on it, and seven lips on <span class=\"supplied\">each of</span> the lamps that <span class=\"supplied\">are</span> on its top.'),
('LEB', 'Zechariah', '4', '3', '1', 'And <span class=\"supplied\">there are</span> two olive trees by it, one on the right of the bowl and the other on its left.”'),
('LEB', 'Zechariah', '4', '4', '1', 'And I answered and said to the angel <span class=\"supplied\">who was</span> talking to me, “What <span class=\"supplied\">are</span> these, my lord?”'),
('LEB', 'Zechariah', '4', '5', '1', 'And the angel <span class=\"supplied\">who was</span> talking with me answered and said to me, “Do you not know what these <span class=\"supplied\">are</span>?” And I said, “No, my lord.”'),
('LEB', 'Zechariah', '4', '6', '1', 'And he answered and said to me, “This <span class=\"supplied\">is</span> the word of Adonai to Zerubbabel, saying, ‘Not by strength and not by power, but <span class=\"supplied\">only</span> by my Spirit,’ says Adonai of hosts.'),
('LEB', 'Zechariah', '4', '7', '1', '‘Who <span class=\"supplied\">are</span> you O great mountain? <span class=\"idiom\">Before</span><span class=\"note\">Literally “To the face of”</span>Zerubbabel <span class=\"supplied\">you will become</span> level ground, and he will bring out the top stone amid the shouts of “Grace, grace to it!” ’ ”'),
('LEB', 'Zechariah', '4', '8', '1', 'And the word of Adonai came to me, saying,'),
('LEB', 'Zechariah', '4', '9', '1', '“The hands of Zerubbabel have founded this house, and his hands will finish it. And you will know that Adonai of hosts has sent me to you.'),
('LEB', 'Zechariah', '4', '10', '1', 'For whoever has despised the day of small <span class=\"supplied\">things</span> will rejoice and will see the <span class=\"idiom\">plumb line</span><span class=\"note\">Literally “the tin stone”; this could refer to a plumb line or a plummet</span>in the hand of Zerubbabel.”'),
('LEB', 'Zechariah', '4', '11', '2', 'These seven <span class=\"supplied\">are</span> the eyes of Adonai which <span class=\"supplied\">are</span> ranging <span class=\"idiom\">throughout the whole earth</span>.<span class=\"note\">Literally “in all the earth”</span>'),
('LEB', 'Zechariah', '4', '12', '2', 'And I answered and said to him, “What <span class=\"supplied\">are</span> these two olive trees on the right of the lampstand and on its left?”'),
('LEB', 'Zechariah', '4', '13', '2', 'And I replied a second <span class=\"supplied\">time</span> and asked him, “What <span class=\"supplied\">are</span> these two twigs of olive trees<span class=\"note\">Or “two clusters of olive branches”; literally “two ears of grain,” perhaps based on similarity of shape</span>on the right of the lampstand and on its left?”'),
('LEB', 'Zechariah', '4', '14', '2', 'And he replied to me, “Do you not know what these <span class=\"supplied\">are</span>?” And I said, “No, my lord.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '5', '1', '1', '<span class=\"verse-title\">Zechariah’s Sixth Vision</span><span class=\"idiom\">I looked up again</span>,<span class=\"note\">Literally “I did again, I lifted up my eyes”</span>and I saw, and look!—a flying scroll!'),
('LEB', 'Zechariah', '5', '2', '1', 'And he asked me, “What <span class=\"supplied\">are</span> you seeing?” And I said, “I <span class=\"supplied\">am</span> seeing a flying scroll twenty cubits long and ten cubits wide.”<span class=\"note\">That is, thirty feet by fifteen feet</span>'),
('LEB', 'Zechariah', '5', '3', '1', 'And he said to me, “This <span class=\"supplied\">is</span> the curse going out over the surface of the whole earth. For everyone who steals has gone unpunished<span class=\"note\">Many translations render this verb as “will be cut off”</span>according to it, and <span class=\"supplied\">likewise</span> everyone who swears <span class=\"supplied\">falsely</span> has gone unpunished according to it.'),
('LEB', 'Zechariah', '5', '4', '1', '‘I have sent it out,’ <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts, ‘and it will go into the house of the thief and into the house of the one swearing <span class=\"idiom\">falsely by my name</span>,<span class=\"note\">Literally “by my name to lie”</span>and it will spend the night in that<span class=\"note\">Hebrew “his”</span>house and will destroy it, with its timber and its stone.’ ”'),
('LEB', 'Zechariah', '5', '5', '3', '<span class=\"verse-title\">Zechariah’s Seventh Vision</span>And the angel who was speaking to me went out, and he said to me, “<span class=\"idiom\">Please look up</span>!<span class=\"note\">Literally “Lift, please, your eyes!”</span>See what this <span class=\"supplied\">is</span> going out.”'),
('LEB', 'Zechariah', '5', '6', '3', 'And I asked, “What <span class=\"supplied\">is</span> it?” And he said, “This <span class=\"supplied\">is</span> a basket<span class=\"note\">Or “an ephah,” a measure of grain</span>going out. And he said, “This <span class=\"supplied\">is</span> their iniquity<span class=\"note\">Hebrew “eye”; other ancient versions (LXX, Syriac) read “iniquity”</span>throughout all the earth.'),
('LEB', 'Zechariah', '5', '7', '3', 'And look, the lead cover was lifted and a woman <span class=\"supplied\">was</span> sitting inside the basket.<span class=\"note\">Or “ephah,” a measure of grain</span>'),
('LEB', 'Zechariah', '5', '8', '3', 'And he said, “This <span class=\"supplied\">is</span> Wickedness!” And he thrust her <span class=\"supplied\">back down</span> into the basket,<span class=\"note\">Or “ephah,” a measure of grain</span>and threw the lead cover on top of it.<span class=\"note\">That is, on top of the “basket” or “ephah”</span>'),
('LEB', 'Zechariah', '5', '9', '3', 'And I <span class=\"idiom\">looked up</span><span class=\"note\">Literally “lifted up my eyes”</span>and saw, and look!—two women coming forward, and <span class=\"supplied\">the</span> wind <span class=\"supplied\">was</span> in their wings, and they had wings like those of a stork, and they lifted up the basket<span class=\"note\">Or “ephah,” a measure of grain</span>between the earth and the sky.<span class=\"note\">Or “heaven”</span>'),
('LEB', 'Zechariah', '5', '10', '3', 'And I asked the angel who was talking to me, “Where <span class=\"supplied\">are</span> they taking the basket?”<span class=\"note\">Or “ephah,” a measure of grain</span>'),
('LEB', 'Zechariah', '5', '11', '3', 'And he said to me, “To build for it a house<span class=\"note\">Or “temple”</span>in the land of Shinar,<span class=\"note\">That is, Babylon (Gen 11:2)</span>and <span class=\"supplied\">when</span> it is put in place, it will be placed there on its site.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '6', '1', '1', '<span class=\"verse-title\">Zechariah’s Eighth Vision</span><span class=\"idiom\">I looked up again</span>,<span class=\"note\">Literally “I did again, I lifted up my eyes”</span>and I saw, and look!—four chariots coming out from between two mountains, and the mountains <span class=\"supplied\">were</span> mountains of bronze.'),
('LEB', 'Zechariah', '6', '2', '1', 'With the first chariot <span class=\"supplied\">there were</span> red horses, and with the second chariot <span class=\"supplied\">there were</span> black horses.'),
('LEB', 'Zechariah', '6', '3', '1', 'And with the third chariot <span class=\"supplied\">there were</span> white horses, and with the fourth chariot <span class=\"supplied\">there were</span> strong<span class=\"note\">Other ancient versions read “grey” here</span>dappled horses.'),
('LEB', 'Zechariah', '6', '4', '1', 'And I answered and said to the angel <span class=\"supplied\">that was</span> talking to me, “What <span class=\"supplied\">are</span> these, my lord?”'),
('LEB', 'Zechariah', '6', '5', '1', 'And the angel answered and said to me, “These <span class=\"supplied\">are</span> the four winds<span class=\"note\">Or “spirits” (The same Hebrew word can be translated “wind” or “spirit” depending on the context)</span>of the heavens going out after presenting themselves before the Lord of all the earth.'),
('LEB', 'Zechariah', '6', '6', '1', '<span class=\"idiom\">The one with</span><span class=\"note\">Literally “Her with which”</span>the black horses <span class=\"supplied\">is</span> going out to <span class=\"supplied\">the</span> north country, and the white <span class=\"supplied\">horses</span> go after them,<span class=\"note\">Some interpret the word “after” to indicate a westward direction</span>while the dappled <span class=\"supplied\">ones</span> go to the south country.”'),
('LEB', 'Zechariah', '6', '7', '1', 'When the strong <span class=\"supplied\">horses</span> went out, they were anxious to go to patrol the earth. And he<span class=\"note\">That is, “Lord of all the earth”</span>said, “Go, patrol the earth.” And they patrolled the earth.'),
('LEB', 'Zechariah', '6', '8', '1', 'And he cried out to me and said to me, “See those going out to <span class=\"supplied\">the</span> north country have set my spirit at rest in the north country.”'),
('LEB', 'Zechariah', '6', '9', '3', '<span class=\"verse-title\">The Branch is Crowned</span>And the word of Adonai came to me, saying,'),
('LEB', 'Zechariah', '6', '10', '3', '“Collect<span class=\"note\">The imperative “Collect” has no object; many translations supply “silver and gold” or “an offering”</span>from the exiles—from Heldai, Tobijah, and from Jedaiah, <span class=\"supplied\">all of</span> whom came from Babylon—and go on that day, go <span class=\"supplied\">to the</span> house of Josiah son of Zephaniah.'),
('LEB', 'Zechariah', '6', '11', '3', 'Take <span class=\"supplied\">the</span> silver and gold and make a crown, and set <span class=\"supplied\">it</span> on the head of Joshua son of Jehozadak, the high priest.'),
('LEB', 'Zechariah', '6', '12', '3', 'And say to him, ‘Thus says Adonai of hosts: “Look, <span class=\"supplied\">here is</span> a man whose name <span class=\"supplied\">is</span> Branch,<span class=\"note\">Hebrew “Sprout” or “Shoot” (“Branch” is a traditional rendering in English)</span>and from his place he will sprout, and he will build the temple of Adonai.'),
('LEB', 'Zechariah', '6', '13', '3', 'And he will build the temple of Adonai, and he will bear majesty and will sit and rule on his throne. And he shall be a priest on his throne, and the counsel of peace will be between the two of them.” ’<span class=\"note\">That is, between king and priest</span>'),
('LEB', 'Zechariah', '6', '14', '3', 'And the crown will be for Helem,<span class=\"note\">“Helem” is probably another name for Heldai (v. 10)</span>for Tobijah, for Jedaiah, and for Hen<span class=\"note\">“Hen” is frequently understood as a reference to Josiah (v. 10)</span>son of Zephaniah, as a memorial in the temple of Adonai.'),
('LEB', 'Zechariah', '6', '15', '3', 'And those who are far off will come and build the temple of Adonai, and you will know that Adonai of hosts has sent me to you. And it will happen if you will listen diligently to the voice of Adonai your God.”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '7', '1', '0', '<span class=\"idiom\">And then</span>,<span class=\"note\">Literally “and it happened”</span>in the fourth year of King Darius, the word of Adonai came to Zechariah on <span class=\"supplied\">the</span> fourth <span class=\"supplied\">day</span> of the ninth month, <span class=\"supplied\">which is</span> Kislev.'),
('LEB', 'Zechariah', '7', '2', '0', 'And <span class=\"supplied\">the people of</span> Bethel sent Sharezer and Regem-Melech, and their<span class=\"note\">Hebrew “his”</span>men, to entreat <span class=\"idiom\">the favor</span><span class=\"note\">Literally “the face”</span>of Adonai,'),
('LEB', 'Zechariah', '7', '3', '0', 'saying to the <span class=\"idiom\">priests of the house of Adonai of hosts</span><span class=\"note\">Literally “priests who <span class=\"supplied\">are</span> for the house of Adonai of hosts”</span>and to the prophets, “Should I mourn in the fifth month and keep myself separate<span class=\"note\">Or “abstain”; some interpret this as a reference to fasting</span>as I have done for these many years?”'),
('LEB', 'Zechariah', '7', '4', '0', 'And the word of Adonai of hosts came to me, saying,'),
('LEB', 'Zechariah', '7', '5', '0', '“Say to all the people of the land and to the priests: ‘When you fasted and lamented in the fifth and seventh months for these seventy years, did you really fast for me?'),
('LEB', 'Zechariah', '7', '6', '0', 'And when you eat and drink, are you not eating and drinking <span class=\"supplied\">for yourselves</span>?'),
('LEB', 'Zechariah', '7', '7', '0', '<span class=\"supplied\">Are</span> not <span class=\"supplied\">these</span> the words that Adonai proclaimed <span class=\"idiom\">through</span><span class=\"note\">Literally “by the hand of”</span>the former prophets, when Jerusalem and <span class=\"idiom\">its surrounding towns</span><span class=\"note\">Literally “her towns around her”</span>were inhabited and at ease, and the Negev<span class=\"note\">The Negev is an arid region south of the Judean hills</span>and the Shephelah<span class=\"note\">The Shephelah is a geographical area on the western edge of the Judean hills</span>were inhabited?’ ”'),
('LEB', 'Zechariah', '7', '8', '1', 'And the word of Adonai came to Zechariah, saying,'),
('LEB', 'Zechariah', '7', '9', '1', '“Thus says Adonai of hosts: ‘Judge <span class=\"supplied\">with</span> trustworthy justice, and show<span class=\"note\">Literally “do”</span>steadfast love and compassion <span class=\"idiom\">to one another</span>.<span class=\"note\">Literally “a man his brother”</span>'),
('LEB', 'Zechariah', '7', '10', '1', 'You must not oppress <span class=\"supplied\">the</span> widow, <span class=\"supplied\">the</span> orphan, <span class=\"supplied\">the</span> foreigner, and <span class=\"supplied\">the</span> needy. You must not devise evil in your heart <span class=\"idiom\">against one another</span>.’<span class=\"note\">Literally “a man his brother”</span>'),
('LEB', 'Zechariah', '7', '11', '1', 'But they refused to listen, and turned<span class=\"note\">Hebrew “gave”</span>a stubborn shoulder and <span class=\"idiom\">stopped their ears from listening</span>.<span class=\"note\">Literally “their ears were heavy from hearing”</span>'),
('LEB', 'Zechariah', '7', '12', '1', '<span class=\"idiom\">They made their hearts adamant</span><span class=\"note\">Literally “They set their hearts <span class=\"supplied\">like</span> hard stone”</span>in order not to hear the law<span class=\"note\">Hebrew <span class=\"italic\">torah</span></span>and the words that Adonai of hosts had sent by his spirit through<span class=\"note\">Literally “by the hand of”</span>the former prophets; <span class=\"supplied\">therefore</span> great wrath came from Adonai of hosts.'),
('LEB', 'Zechariah', '7', '13', '1', '‘Thus, just as I<span class=\"note\">Hebrew “he called” (but still referring to Adonai)</span>called and they would not hear, so they will call and I will not hear,’ says Adonai of hosts.'),
('LEB', 'Zechariah', '7', '14', '1', '‘And I scattered them with a wind among all the nations that they had not known; the land was made desolate behind them— no one crossing through <span class=\"supplied\">it</span> or returning—and they made the desirable land<span class=\"note\">Hebrew “land of desire,” but this could be understood as a land characterized by desire rather than a desirable land</span>a desolation.’ ”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '8', '1', '1', '<span class=\"verse-title\">Adonai’s Promise to Jerusalem</span>And the word of Adonai of hosts came, saying,'),
('LEB', 'Zechariah', '8', '2', '1', '“Thus says Adonai of hosts: ‘<span class=\"idiom\">I am exceedingly jealous for Zion</span>;<span class=\"note\">Literally “I am jealous for Zion <span class=\"supplied\">with</span> great jealousy”</span>I am jealous for it <span class=\"supplied\">with</span> great wrath.’'),
('LEB', 'Zechariah', '8', '3', '1', 'Thus says Adonai: ‘I have returned to Zion, and I will dwell in the midst of Jerusalem; and Jerusalem will be called the faithful city,<span class=\"note\">Or “the city of truth”</span>and the mountain of Adonai of hosts <span class=\"supplied\">will be called</span> the holy mountain.’'),
('LEB', 'Zechariah', '8', '4', '1', 'Thus says Adonai of hosts: ‘Old men and old women shall again sit in the public squares of Jerusalem, each with staff in hand<span class=\"note\">Hebrew “a man his staff in his hand”</span><span class=\"idiom\">because of great age</span>.<span class=\"note\">Literally “because of the multitude of days”</span>'),
('LEB', 'Zechariah', '8', '5', '1', 'And the public squares of the city will be filled <span class=\"supplied\">with</span> boys and girls playing in its public squares.’'),
('LEB', 'Zechariah', '8', '6', '1', 'Thus says Adonai of hosts: ‘<span class=\"supplied\">Even</span> if it seems impossible<span class=\"note\">Or “wonderful”</span><span class=\"idiom\">to the remnant</span><span class=\"note\">Literally “in the eyes of the remnant”</span>of this people in those days, should it also seem impossible<span class=\"note\">Or “wonderful”</span><span class=\"idiom\">to me</span>?’<span class=\"note\">Literally “in my eyes”</span><span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts.'),
('LEB', 'Zechariah', '8', '7', '1', 'Thus says Adonai of hosts: ‘Look! I <span class=\"supplied\">am</span> going to save my people from the land of the east, and from the land of the west,'),
('LEB', 'Zechariah', '8', '8', '1', 'and I will bring them and they will dwell in the midst of Jerusalem. They will be my people and I will be their God in faithfulness<span class=\"note\">Or “truth”</span>and in righteousness.’'),
('LEB', 'Zechariah', '8', '9', '2', '“Thus says Adonai of hosts: ‘Let your hands be strong, you<span class=\"note\">Hebrew “the <span class=\"supplied\">ones</span>”</span>who are hearing in these days these words from the mouth of the prophets who <span class=\"supplied\">were present</span> on <span class=\"supplied\">the</span> day <span class=\"idiom\">the foundation was laid for the rebuilding of the temple, the house of Adonai of hosts</span>.<span class=\"note\">Literally “the temple, the house of Adonai of hosts, was founded to be built”</span>'),
('LEB', 'Zechariah', '8', '10', '2', 'For before those days there was no wage for people or for animals, and there was no safety from the enemy for those who went out or those who came in, and I sent each person against <span class=\"idiom\">one another</span>.<span class=\"note\">Literally “his neighbor”</span>'),
('LEB', 'Zechariah', '8', '11', '2', 'But now <span class=\"idiom\">I will not deal with the remnant of this people as in the former days</span>,’<span class=\"note\">Literally “not like the former days I <span class=\"supplied\">will be</span> to the remnant”</span><span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts.'),
('LEB', 'Zechariah', '8', '12', '2', '‘For <span class=\"supplied\">there will be</span> a sowing of peace; the vine will give its fruit, and the soil will give its produce, and the heavens will give their dew. And I will cause the remnant of this people to inherit all these <span class=\"supplied\">things</span>.'),
('LEB', 'Zechariah', '8', '13', '2', '<span class=\"idiom\">And then</span>,<span class=\"note\">Literally “and it will happen”</span>just as you were a curse among the nations, O house of Judah and house of Israel, so will I save you, and you will be a blessing. You must not be afraid; let your hands be strong!’ ”'),
('LEB', 'Zechariah', '8', '14', '3', 'For thus says Adonai of hosts: “Just as I planned to bring disaster<span class=\"note\">Hebrew “evil”</span>on you when your ancestors<span class=\"note\">Or “fathers”</span>provoked me to anger,” says Adonai of hosts, “and I did not regret <span class=\"supplied\">it</span>,'),
('LEB', 'Zechariah', '8', '15', '3', '<span class=\"idiom\">so again I have planned</span><span class=\"note\">Literally “So I did again, I planned”</span>in these days to do good to Jerusalem and the house of Judah. Do not be afraid!'),
('LEB', 'Zechariah', '8', '16', '3', 'These <span class=\"supplied\">are</span> the things that you must do: speak truth, each <span class=\"supplied\">of you</span>, with his neighbor; practice trustworthy judgment and peace in your gates.'),
('LEB', 'Zechariah', '8', '17', '3', 'Do not devise evil in your hearts <span class=\"supplied\">against</span> your neighbor, and do not love <span class=\"idiom\">a false oath</span>,<span class=\"note\">Literally “an oath of deception”</span>because all these <span class=\"supplied\">are</span> things I hate,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai.'),
('LEB', 'Zechariah', '8', '18', '4', 'And the word of Adonai of hosts came to me, saying'),
('LEB', 'Zechariah', '8', '19', '4', '“Thus says Adonai of hosts: ‘The fast of the fourth <span class=\"supplied\">month</span>, the fifth <span class=\"supplied\">month</span>, the seventh <span class=\"supplied\">month</span>, and the tenth <span class=\"supplied\">month</span> will be for the house of Judah jubilation and joy and merry festivals; therefore love truth and peace.’'),
('LEB', 'Zechariah', '8', '20', '4', 'Thus says Adonai of hosts: ‘<span class=\"supplied\">It will happen</span> again that nations and the inhabitants of many cities will come.'),
('LEB', 'Zechariah', '8', '21', '4', 'And the inhabitants of one city will go to another <span class=\"supplied\">city</span>, saying, “Let us go immediately to entreat <span class=\"idiom\">the favor of</span><span class=\"note\">Literally “the face of”</span>Adonai, to seek Adonai of hosts—I also will go!”'),
('LEB', 'Zechariah', '8', '22', '4', 'And many peoples and powerful<span class=\"note\">Or “mighty”</span>nations will come to seek Adonai of hosts in Jerusalem, and to entreat <span class=\"idiom\">the favor of</span><span class=\"note\">Literally “the face of”</span>Adonai.’'),
('LEB', 'Zechariah', '8', '23', '4', 'Thus says Adonai of hosts: ‘In those days ten men from <span class=\"idiom\">all the nations of every language</span><span class=\"note\">Literally “all the languages of the nations”</span>will take hold of the hem of a Judean man,<span class=\"note\">Many versions translate “a Jew,” but “Judean” highlights Zechariah’s focus on provincial geography</span>saying, “Let us go with you, for we have heard <span class=\"supplied\">that</span> God <span class=\"supplied\">is</span> with you!” ’ ”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '9', '1', '0', 'An oracle. The word of Adonai <span class=\"supplied\">is</span> against the land of Hadrach,'),
('LEB', 'Zechariah', '9', '2', '1', 'and Damascus <span class=\"supplied\">is</span> its resting place.  For to Adonai belongs the eye of humankind,<span class=\"note\">“Eye of humankind” is difficult to understand in this context; some scholars emend the phrase to “cities of Aram” or “capital of Aram”</span> and all the tribes of Israel,'),
('LEB', 'Zechariah', '9', '3', '1', 'and also Hamath, <span class=\"supplied\">which</span> borders on it;  Tyre and Sidon—yes, they are very wise!<span class=\"note\">That is, wise in their own eyes (ironic)</span>'),
('LEB', 'Zechariah', '9', '4', '1', 'Tyre has built a fortification for itself,<span class=\"note\">Hebrew “her”</span> and it heaped up silver like dust,  and gold like <span class=\"supplied\">the</span> mud of <span class=\"supplied\">the</span> streets.'),
('LEB', 'Zechariah', '9', '5', '1', 'Look! The Lord will drive it<span class=\"note\">Hebrew “her”</span>out  and will hurl its<span class=\"note\">Hebrew “her”</span>outer ramparts into the sea,  and it<span class=\"note\">Hebrew “she”</span>will be consumed by fire.'),
('LEB', 'Zechariah', '9', '6', '1', 'Ashkelon will see and will be afraid,  and Gaza will writhe exceedingly,  and Ekron <span class=\"supplied\">also</span>, because its hope is ruined.<span class=\"note\">Traditionally “ashamed”; some presuppose a different Hebrew form and translate “withered”</span> And the king from Gaza will perish,  and Ashkelon will not be inhabited.'),
('LEB', 'Zechariah', '9', '7', '1', 'A mongrel people<span class=\"note\">That is, a people of mixed marriage; “half-breeds”</span>will dwell in Ashdod,  and I will cut down the pride of <span class=\"supplied\">the</span> Philistines.'),
('LEB', 'Zechariah', '9', '8', '1', 'I will remove its<span class=\"note\">Hebrew “his”</span>blood from its<span class=\"note\">Hebrew “his”</span>mouth,  and its<span class=\"note\">Hebrew “his”</span>abominations from between its<span class=\"note\">Hebrew “his”</span>teeth.  And it<span class=\"note\">Hebrew “he”</span>too will be a remnant for our God;  and it<span class=\"note\">Hebrew “he”</span>will be like a tribal chief<span class=\"note\">This word is sometimes interpreted as “clan”</span>in Judah,  and Ekron <span class=\"supplied\">will be</span> like <span class=\"supplied\">the</span> Jebusite.'),
('LEB', 'Zechariah', '9', '9', '1', 'But I will encamp at my temple<span class=\"note\">Or “house”</span><span class=\"supplied\">like a</span> guard,  against those crossing through and returning;  no oppressor will cross through them again,  for now I have seen with my <span class=\"supplied\">own</span> eyes.'),
('LEB', 'Zechariah', '9', '10', '1', 'Rejoice greatly, O daughter of Zion!  Shout aloud, O daughter of Jerusalem!  Look! Your king comes to you;  he <span class=\"supplied\">is</span> righteous and victorious,  humble and riding on a donkey,  and on a male donkey, <span class=\"idiom\">the foal of</span><span class=\"note\">Literally “the son of ”</span>a female donkey!'),
('LEB', 'Zechariah', '9', '11', '1', 'And I will cut off <span class=\"supplied\">the</span> chariot from Ephraim,  and <span class=\"supplied\">the</span> horse from Jerusalem;  the battle bow will be cut down,  and he will announce peace to the nations.  His dominion <span class=\"supplied\">will be</span> from sea to sea,  and from <span class=\"supplied\">the</span> River<span class=\"note\">That is, the Euphrates</span>to <span class=\"supplied\">the</span> ends of <span class=\"supplied\">the</span> earth.'),
('LEB', 'Zechariah', '9', '12', '1', '<span class=\"supplied\">As for</span> you also, because of the blood of your covenant,  I will release your prisoners from <span class=\"idiom\">the waterless pit</span>.<span class=\"note\">Literally “<span class=\"supplied\">the</span> cistern there is not water in him”</span>'),
('LEB', 'Zechariah', '9', '13', '1', 'Return to <span class=\"supplied\">the</span> fortress,  O prisoners of hope;  today <span class=\"supplied\">I am</span> declaring <span class=\"supplied\">that</span> I will repay you double.'),
('LEB', 'Zechariah', '9', '14', '1', 'For I have bent Judah <span class=\"supplied\">as</span> my bow;  I have set Ephraim <span class=\"supplied\">as an arrow</span>.  I will set in motion your sons, O Zion,  against your sons, O Javan.<span class=\"note\">That is, Greece</span> I will wield you like the sword of a warrior.'),
('LEB', 'Zechariah', '9', '15', '1', 'Then Adonai will appear over them,  and his arrow will go forth like lightning;  and my Lord Adonai will blow the trumpet,  and he shall go out in the storm winds of <span class=\"supplied\">the</span> south.'),
('LEB', 'Zechariah', '9', '16', '1', 'Adonai of hosts will defend them,  and they will devour and subdue the slingstones;<span class=\"note\">Perhaps metonymy for the slingers of stones</span> they will drink, they will make noise<span class=\"note\">LXX reads “they will drink blood like wine”</span>like wine,  and they will be full like the sacrificial basin,<span class=\"note\">That is, the ceremonial bowl used by the priest for sprinkling blood</span> <span class=\"supplied\">drenched</span> like the corners of an altar.'),
('LEB', 'Zechariah', '9', '17', '1', 'And Adonai their God will save them on that day,  as the flock of his people;  for <span class=\"supplied\">they are like</span> the stones of a diadem,  glittering on his land.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '10', '1', '1', '<span class=\"verse-title\">Adonai Gives Rain</span>Ask rain from Adonai in the season of <span class=\"supplied\">the</span> spring rain—'),
('LEB', 'Zechariah', '10', '2', '2', 'Adonai, who makes storm clouds,  and he gives showers of rain to them,  to everyone vegetation in the field.'),
('LEB', 'Zechariah', '10', '3', '2', 'Because the household gods<span class=\"note\">Hebrew <span class=\"italic\">teraphim</span></span>speak deceit,  and those who practice divination see a lie,  and the dreamers of vanity speak in vain.  Therefore <span class=\"supplied\">the people</span> wander like sheep;<span class=\"note\">Or “flocks”; the Hebrew term refers collectively to both sheep and goats (small livestock animals)</span> they are afflicted because there is no shepherd.'),
('LEB', 'Zechariah', '10', '4', '2', '<span class=\"idiom\">My anger burns</span><span class=\"note\">Literally “My nose becomes hot”</span>against the shepherds,  and I will punish the leaders,<span class=\"note\">Or “male goats”</span> because Adonai of hosts watches over his flock,<span class=\"note\">Or “herd”</span> the house of Judah;  and he will make them like his majestic horse in war.'),
('LEB', 'Zechariah', '10', '5', '2', 'From them<span class=\"note\">Hebrew “him” (or “it”), referring to the flock in v. 3</span><span class=\"supplied\">the</span> cornerstone will go out,  from them<span class=\"note\">Hebrew “him” (or “it”), referring to the flock in v. 3</span><span class=\"supplied\">the</span> tent peg,  from them<span class=\"note\">Hebrew “him” (or “it”), referring to the flock in v. 3</span><span class=\"supplied\">the</span> battle bow,  from them<span class=\"note\">Hebrew “him” (or “it”), referring to the flock in v. 3</span>every ruler,  <span class=\"supplied\">all</span> together.'),
('LEB', 'Zechariah', '10', '6', '2', 'And they will be like warriors,  trampling in the mud of <span class=\"supplied\">the</span> streets in the battle.  They will fight, because Adonai <span class=\"supplied\">is</span> with them,  and they will put to shame <span class=\"supplied\">the</span> riders on horses.'),
('LEB', 'Zechariah', '10', '7', '2', 'And I will strengthen the house of Judah,  and the house of Joseph I will save.  And I will bring them back, because I have compassion on them,  and they will be as if I had not rejected them,  for I <span class=\"supplied\">am</span> Adonai their God, and I will answer them.'),
('LEB', 'Zechariah', '10', '8', '2', 'And <span class=\"supplied\">the people of</span> Ephraim will be like <span class=\"supplied\">a</span> warrior,  and their heart will be glad as <span class=\"supplied\">with</span> wine.  And their children will see and rejoice;  their heart will shout in exultation in Adonai.'),
('LEB', 'Zechariah', '10', '9', '2', 'I will whistle to them and gather them,  for I have redeemed them,  and they will become numerous as they have been numerous <span class=\"supplied\">before</span>.'),
('LEB', 'Zechariah', '10', '10', '2', 'Though I sow<span class=\"note\">Or “scatter”</span>them among the nations,  in the distant places they will remember me,  and they will stay alive with their children, and they will return.'),
('LEB', 'Zechariah', '10', '11', '2', 'And I will bring them back from the land of Egypt,  and from Assyria I will gather them.  To the land of Gilead and Lebanon I will bring them,  until no <span class=\"supplied\">room</span> will be found for them <span class=\"supplied\">there</span>.'),
('LEB', 'Zechariah', '10', '12', '2', 'And he<span class=\"note\">LXX reads “they,” referring to the Israelites (so NIV, NRSV, NASB)</span>will pass through the sea of distress,  and he will strike the waves of the sea,  and all <span class=\"supplied\">the</span> depths of the Nile will dry up.  The pride of Assyria will be brought low,  and the scepter of Egypt will depart.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '11', '1', '0', 'Open your doors, <span class=\"supplied\">O</span> Lebanon,'),
('LEB', 'Zechariah', '11', '2', '1', 'so that fire will devour your cedars!'),
('LEB', 'Zechariah', '11', '3', '1', 'Wail, O juniper,<span class=\"note\">Or “cypress”</span>for <span class=\"supplied\">the</span> cedar has fallen,  for <span class=\"supplied\">the</span> magnificent <span class=\"supplied\">trees</span> are ruined!  Wail, oaks of Bashan,  for the impenetrable forest has come down!'),
('LEB', 'Zechariah', '11', '4', '3', '<span class=\"verse-title\">The Two Shepherds</span>Thus says Adonai my God: “Shepherd the flock<span class=\"note\">The Hebrew term refers collectively to both sheep and goats (small livestock animals)</span><span class=\"supplied\">doomed</span> to slaughter.'),
('LEB', 'Zechariah', '11', '5', '3', 'The ones buying them kill them and go unpunished, and the ones selling them say, ‘Blessed <span class=\"supplied\">be</span> Adonai, for I have become rich.’ Their own shepherds have no compassion for them.'),
('LEB', 'Zechariah', '11', '6', '3', 'For I will no longer have compassion on the inhabitants of the land,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai. “Look, I <span class=\"supplied\">am</span> going to cause humankind to fall, each into the hand of his neighbor, and into the hand of his king; and they will devastate the land, and I will not deliver <span class=\"supplied\">anyone</span> from their hand.”'),
('LEB', 'Zechariah', '11', '7', '4', 'And I shepherded the flock<span class=\"note\">The Hebrew term refers collectively to both sheep and goats (small livestock animals)</span><span class=\"supplied\">doomed</span> to slaughter, even<span class=\"note\">Hebrew “therefore”</span>the afflicted<span class=\"note\">LXX reads “merchants <span class=\"supplied\">of the flock</span>” which is reflected in some English translations</span>of the flock.<span class=\"note\">The Hebrew term refers collectively to both sheep and goats (small livestock animals)</span>I took two staffs, one I called Kindness, and the other I called Unity, and I shepherded the flock.<span class=\"note\">The Hebrew term refers collectively to both sheep and goats (small livestock animals)</span>'),
('LEB', 'Zechariah', '11', '8', '4', 'And I got rid of three shepherds in one month, for <span class=\"idiom\">I grew impatient</span><span class=\"note\">Literally “my soul became short”</span>with them, and <span class=\"idiom\">they also became tired of me</span>.<span class=\"note\">Literally “also their soul detested me”</span>'),
('LEB', 'Zechariah', '11', '9', '4', 'So I said, “I will not shepherd you! The <span class=\"supplied\">one</span> dying will die, and the <span class=\"supplied\">one</span> to be destroyed will be destroyed. And the <span class=\"supplied\">ones</span> remaining, let them devour <span class=\"idiom\">the flesh of each other</span>.”<span class=\"note\">Literally “each the flesh of her neighbor”</span>'),
('LEB', 'Zechariah', '11', '10', '4', 'And I took my staff Kindness and broke it, to break my covenant that I <span class=\"idiom\">had made</span><span class=\"note\">Literally “had cut”</span>with all the peoples.'),
('LEB', 'Zechariah', '11', '11', '4', 'And it was broken on that day. Then the afflicted<span class=\"note\">LXX reads “merchants (of the flock)” which is reflected in some English translations</span>of the flock,<span class=\"note\">The Hebrew term refers collectively to both sheep and goats (small livestock animals)</span>the <span class=\"supplied\">ones who were</span> watching me, knew that it <span class=\"supplied\">was</span> the word of Adonai.'),
('LEB', 'Zechariah', '11', '12', '4', 'And I said to them, “If <span class=\"idiom\">it seems right to you</span>,<span class=\"note\">Literally “<span class=\"supplied\">it is</span> good in your eyes”</span>give <span class=\"supplied\">me</span> my wages, but if not, <span class=\"idiom\">keep them</span>.”<span class=\"note\">Literally “refrain”</span>And they weighed out my wages, thirty silver <span class=\"supplied\">shekels</span>.'),
('LEB', 'Zechariah', '11', '13', '4', 'And Adonai said to me, “Throw it to the potter,”<span class=\"note\">Syriac reads “treasury,” followed by NAB, NRSV, TEV</span><span class=\"idiom\">this noble price</span><span class=\"note\">Literally “the price of honor”</span><span class=\"supplied\">at</span> which I was valued by them!” So I took the thirty silver <span class=\"supplied\">shekels</span> and I threw them to the potter<span class=\"note\">Syriac reads “treasury,” followed by NAB, NRSV, TEV</span><span class=\"supplied\">in</span> the house of Adonai.'),
('LEB', 'Zechariah', '11', '14', '4', 'Then I broke my second staff Unity to break the family ties between Judah and Israel.'),
('LEB', 'Zechariah', '11', '15', '5', 'And Adonai said to me, “Take again the implements<span class=\"note\">Hebrew “implement”</span>of a foolish shepherd.'),
('LEB', 'Zechariah', '11', '16', '5', 'For look, I <span class=\"supplied\">am</span> raising up a shepherd in the land who will not attend to the <span class=\"supplied\">ones that are</span> perishing; he will not seek the young man,<span class=\"note\">Syriac and other ancient versions read “the wandering” or “the scattered,” as do several English translations</span>he will not heal the <span class=\"supplied\">ones that are</span> crushed and he will not sustain the healthy <span class=\"supplied\">ones</span>; he will devour the flesh of the <span class=\"idiom\">fattened ones</span><span class=\"note\">Literally “the stall-fed”</span>and tear apart <span class=\"supplied\">even</span> their hoofs.'),
('LEB', 'Zechariah', '11', '17', '6', '“Woe, my worthless shepherd  who deserts the flock!<span class=\"note\">The Hebrew term refers collectively to both sheep and goats (small livestock animals)</span> <span class=\"supplied\">May</span> a sword <span class=\"supplied\">fall</span> on his arm  and on <span class=\"idiom\">his right eye</span>!<span class=\"note\">Literally “the eye of his right”</span> May his arm wither completely  and <span class=\"idiom\">his right eye</span><span class=\"note\">Literally “the eye of his right”</span>be utterly blinded!”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '12', '1', '1', '<span class=\"verse-title\">The Day of Adonai</span>An oracle. The word of Adonai concerning Israel. “<span class=\"idiom\">Thus declares</span><span class=\"note\">Literally “Declaration of”</span>Adonai, who stretches out <span class=\"supplied\">the</span> heavens, founds <span class=\"supplied\">the</span> earth, and forms the spirit of humankind in its midst:<span class=\"note\">Or “forms the spirit of a man within him”</span>'),
('LEB', 'Zechariah', '12', '2', '1', '‘Look, I <span class=\"supplied\">am</span> going to make Jerusalem a cup of reeling for all the surrounding nations; it will also be against Judah in the siege against Jerusalem.'),
('LEB', 'Zechariah', '12', '3', '1', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>on that day I will make Jerusalem a stone weight<span class=\"note\">Or “a heavy stone”</span>for all the peoples. All those lifting it up will grievously hurt themselves, and all the nations of the earth will assemble against it.'),
('LEB', 'Zechariah', '12', '4', '1', 'On that day,’ <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai, ‘I will strike every horse with confusion, and the one riding it with madness; but over the house of Judah <span class=\"idiom\">I will keep my eyes open</span>,<span class=\"note\">Literally “I will open my eyes,” that is, “I will be responsive” or “I will pay attention”</span>and I will strike every horse of the peoples with blindness.'),
('LEB', 'Zechariah', '12', '5', '1', 'And the clans of Judah will say <span class=\"idiom\">to themselves</span>,<span class=\"note\">Literally “in their heart”</span>“The inhabitants of Jerusalem are a strength to us,<span class=\"note\">Hebrew “me”</span>through Adonai of hosts, their God.”'),
('LEB', 'Zechariah', '12', '6', '2', '“ ‘On that day I will make the clans of Judah like a pan of fire among <span class=\"supplied\">sticks of</span> wood, and like a torch of fire among stalks<span class=\"note\">Hebrew “stalk”</span>of grain, and they will devour to <span class=\"supplied\">the</span> right and to <span class=\"supplied\">the</span> left all the surrounding peoples, and Jerusalem will be inhabited again <span class=\"supplied\">in</span> its place, in Jerusalem.'),
('LEB', 'Zechariah', '12', '7', '2', 'And Adonai will save the tents of Judah first, so that the glory of the house of David and the glory of the inhabitants<span class=\"note\">Hebrew “inhabitant”</span>of Jerusalem may not be exalted over Judah.'),
('LEB', 'Zechariah', '12', '8', '2', 'On that day Adonai will put a shield around the inhabitants<span class=\"note\">Hebrew “inhabitant”</span>of Jerusalem, and the one who stumbles among them on that day will be like David, and the house of David <span class=\"supplied\">will be</span> like God, like the angel of Adonai, <span class=\"idiom\">before them</span>.<span class=\"note\">Literally “to the face of them”</span>'),
('LEB', 'Zechariah', '12', '9', '2', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>on that day I will seek to destroy all the nations coming against Jerusalem.'),
('LEB', 'Zechariah', '12', '10', '3', '“ ‘I will pour on the house of David and on the inhabitants<span class=\"note\">Hebrew “inhabitant”</span>of Jerusalem a spirit of grace and supplication, and they will look to me whom they pierced, and they shall mourn over him, as one wails over an only child, and they will grieve bitterly over him as <span class=\"supplied\">one</span> grieves bitterly over a firstborn.'),
('LEB', 'Zechariah', '12', '11', '3', 'On that day the wailing will be great in Jerusalem, like the wailing for Hadad Rimmon in the plain of Megiddo.'),
('LEB', 'Zechariah', '12', '12', '3', 'And the land shall mourn, <span class=\"idiom\">each clan by itself</span>;<span class=\"note\">Literally “clans, clans alone”</span>the clan of the house of David by itself, and their wives by themselves; the clan of the house of Nathan by itself, and their wives by themselves;'),
('LEB', 'Zechariah', '12', '13', '3', 'the clan of the house of Levi by itself, and their wives by themselves; the clan of the Shimeites by itself, and their wives by themselves;'),
('LEB', 'Zechariah', '12', '14', '3', 'and all those clans remaining, <span class=\"idiom\">each clan by itself</span>,<span class=\"note\">Literally “clans, clans alone”</span>and their wives by themselves.’ ”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '13', '1', '0', '“ ‘On that day a well will be opened for the house of David and for the inhabitants of Jerusalem, <span class=\"idiom\">to cleanse them from sin and from impurity</span>.<span class=\"note\">Literally “for sin and for impurity”</span>'),
('LEB', 'Zechariah', '13', '2', '0', '<span class=\"idiom\">And then</span>,<span class=\"note\">Literally “And it will happen”</span>on that day,’ <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts, ‘I will cut off the names of the idols from the land, and they will no longer be remembered; and also the prophets and the spirit of uncleanness I will banish from the land.'),
('LEB', 'Zechariah', '13', '3', '0', '<span class=\"idiom\">And then</span>,<span class=\"note\">Literally “And it will happen”</span>if anyone prophesies again, his father and his mother who bore him will say to him, “You shall not live, because you have spoken a lie in the name of Adonai!” And his father and his mother who bore him will pierce him through when he prophesies.'),
('LEB', 'Zechariah', '13', '4', '0', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>on that day, each of the prophets will be ashamed because of his vision when he was prophesying, and they will not put on a cloak of hair in order to deceive,'),
('LEB', 'Zechariah', '13', '5', '0', 'but he will say, “I <span class=\"supplied\">am</span> not a prophet; I am a tiller of the soil, for a man has acquired me since my youth.”<span class=\"note\">Other translations read “for the land has been my possession since my youth”</span>'),
('LEB', 'Zechariah', '13', '6', '0', 'And someone<span class=\"note\">Hebrew “he”</span>shall say to him, “What <span class=\"supplied\">are</span> these wounds <span class=\"idiom\">between your arms</span>?”<span class=\"note\">Literally “between your hands”; that is, on the chest or on the back</span>and he will say, “Those I have received<span class=\"note\">Hebrew “have been struck”</span><span class=\"supplied\">in</span> the house of <span class=\"supplied\">the ones who</span> love me.” ’ ”'),
('LEB', 'Zechariah', '13', '7', '2', '<span class=\"verse-title\">The Sword Shall Strike the Shepherd</span>“O sword, awake against my shepherd,  against <span class=\"supplied\">the</span> man <span class=\"supplied\">who is</span> my associate,”  <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai of hosts.  “Strike the shepherd,  so that the sheep<span class=\"note\">Or “flock”; the Hebrew term refers collectively to both sheep and goats (small livestock animals)</span>may be scattered,  and I will turn my hand against the small <span class=\"supplied\">ones</span>.'),
('LEB', 'Zechariah', '13', '8', '2', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>in all the land,” <span class=\"idiom\">declares</span><span class=\"note\">Literally “declaration of”</span>Adonai,  “<span class=\"idiom\">two thirds</span><span class=\"note\">Literally “a mouth of two”</span>will be cut off and perish,  and one third will be left alive<span class=\"note\">Hebrew “left over”</span>in it.'),
('LEB', 'Zechariah', '13', '9', '2', 'And I will bring the <span class=\"supplied\">remaining</span> third into the fire,  and I will refine them like <span class=\"supplied\">one</span> refines silver,  and I will test them like <span class=\"supplied\">one</span> tests gold.  They<span class=\"note\">Hebrew “He”</span>will call my name,  and I will answer them.<span class=\"note\">Hebrew “him”</span> I will say, ‘They<span class=\"note\">Hebrew “He”</span>are my people,’  and they<span class=\"note\">Hebrew “he”</span>will say, ‘Adonai <span class=\"supplied\">is</span> my God.’ ”')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zechariah', '14', '1', '1', '<span class=\"verse-title\">Zechariah’s Apocalyptic Vision</span>Look! A day <span class=\"supplied\">is</span> coming for Adonai, when your plunder will be divided in your midst.'),
('LEB', 'Zechariah', '14', '2', '1', 'I will gather all the nations against Jerusalem to battle, and the city will be captured, and they will loot the houses, and the women will be raped; half of the city will go into exile, but the remainder of the people will not be cut off from the city.'),
('LEB', 'Zechariah', '14', '3', '1', 'Then Adonai will go forth and fight against those nations, like <span class=\"idiom\">when he fights</span><span class=\"note\">Literally “the day of his fighting”</span>on a day of battle.'),
('LEB', 'Zechariah', '14', '4', '1', 'On that day his feet will stand on <span class=\"idiom\">the Mount of Olives</span>,<span class=\"note\">Literally “the mountain of the olive trees”</span>which faces Jerusalem on <span class=\"supplied\">the</span> east; and <span class=\"idiom\">the Mount of Olives</span><span class=\"note\">Literally “the mountain of the olive trees”</span>will be split <span class=\"idiom\">in half</span>,<span class=\"note\">Literally “from its half”</span>from east to west, <span class=\"supplied\">by</span> a very great valley; and half of the mountain will withdraw toward the north, and the other half toward the south.'),
('LEB', 'Zechariah', '14', '5', '1', 'And you will flee <span class=\"supplied\">by</span> the valley of my mountains, because the valley of <span class=\"supplied\">the</span> mountains will reach to Azal, and you will flee like you fled from the earthquake in the days of King Uzziah of Judah. And Adonai my God will come, <span class=\"supplied\">and</span> all <span class=\"supplied\">the</span> holy ones with him.<span class=\"note\">Hebrew “you”; LXX has “him”</span>'),
('LEB', 'Zechariah', '14', '6', '2', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>on that day there will not be light,<span class=\"note\">Some suggest reading “flame” (= “heat”) here</span>the precious things will congeal.<span class=\"note\">Or “the noble ones will congeal”; the Hebrew is difficult here</span>'),
('LEB', 'Zechariah', '14', '7', '2', 'There shall be continuous day—it is known to Adonai—not day and not night; and at evening time there will be light.'),
('LEB', 'Zechariah', '14', '8', '3', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>on that day, living waters will flow out from Jerusalem, half of them to the eastern sea,<span class=\"note\">That is, the Dead Sea</span>and the other half to the western sea;<span class=\"note\">That is, the Mediterranean Sea</span>it will happen <span class=\"supplied\">both</span> in the summer and in the winter.'),
('LEB', 'Zechariah', '14', '9', '3', 'And Adonai will be king over all the earth; on that day Adonai will be one and his name one.'),
('LEB', 'Zechariah', '14', '10', '3', 'All the land will be transformed into a desert plateau<span class=\"note\">Or “will be changed like the Arabah”</span>from Geba to Rimmon south of Jerusalem. But it<span class=\"note\">That is, Jerusalem</span>will rise up high and it will stay<span class=\"note\">Or “remain”</span>in its place from the Gate of Benjamin to the place of <span class=\"supplied\">the</span> former gate, up to the Corner Gate and from the Tower of Hananel to the king’s winepresses.'),
('LEB', 'Zechariah', '14', '11', '3', 'And they<span class=\"note\">That is, the people</span>will dwell in it, and <span class=\"idiom\">there will be no more ban imposed</span>,<span class=\"note\">Literally “and there will not be a thing devoted to destruction” (that is, put under the ban of utter destruction)</span>and Jerusalem will dwell in security.'),
('LEB', 'Zechariah', '14', '12', '4', 'And this will be the plague <span class=\"supplied\">with</span> which Adonai will strike all the peoples that fight against Jerusalem: their<span class=\"note\">Hebrew “his”</span>flesh will rot while they<span class=\"note\">Hebrew “he”</span><span class=\"supplied\">are</span> standing on their<span class=\"note\">Hebrew “his”</span>feet; their<span class=\"note\">Hebrew “his”</span>eyes will rot in their sockets, and their<span class=\"note\">Hebrew “his”</span>tongues<span class=\"note\">Hebrew “tongue”</span>will rot in their mouths.<span class=\"note\">Hebrew “mouth”</span>'),
('LEB', 'Zechariah', '14', '13', '4', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>on that day a great panic from Adonai will fall<span class=\"note\">Hebrew “will be”</span>on them, and <span class=\"idiom\">they will seize one another’s hand</span>,<span class=\"note\">Literally “and a man will seize the hand of his neighbor”</span>and the hand of the one will be raised against the hand of <span class=\"idiom\">another</span>.<span class=\"note\">Literally “his neighbor”</span>'),
('LEB', 'Zechariah', '14', '14', '4', 'And Judah also will fight at<span class=\"note\">Or “against” (so NAB, CEV)</span>Jerusalem. And the wealth of all the surrounding nations will be collected—gold and silver, and garments <span class=\"idiom\">in great abundance</span>.<span class=\"note\">Literally “as far as the very multitude”</span>'),
('LEB', 'Zechariah', '14', '15', '4', '<span class=\"idiom\">Like this plague</span><span class=\"note\">Literally “And so”</span>will be the plague on the horse, the mule, the camel, and the donkey, and every kind of animal in those camps.'),
('LEB', 'Zechariah', '14', '16', '5', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>every survivor from all those nations coming against Jerusalem will go up year after year<span class=\"note\">Or “from year to year”; or “yearly”</span>to worship <span class=\"supplied\">the</span> king, Adonai of hosts, and celebrate the Feast of Booths.<span class=\"note\">That is, Succoth (or Tabernacles)</span>'),
('LEB', 'Zechariah', '14', '17', '5', '<span class=\"idiom\">And then</span><span class=\"note\">Literally “And it will happen”</span>whoever of the clans of the earth does not go up to Jerusalem to worship the king, Adonai of hosts, it will not rain on them.'),
('LEB', 'Zechariah', '14', '18', '5', 'And if the clan of Egypt will not go up and come in, on them will be that plague Adonai inflicts on the nations that do not go up to celebrate the Feast of Booths.'),
('LEB', 'Zechariah', '14', '19', '5', 'This will be the punishment of Egypt and the punishment of all the nations that do not go up to celebrate the Feast of Booths.'),
('LEB', 'Zechariah', '14', '20', '6', 'On that day there will be <span class=\"supplied\">inscribed</span> on the bells of the horses, “Holy to Adonai.” And the cooking pots in the house<span class=\"note\">Or “temple”</span>of Adonai will be <span class=\"supplied\">holy</span> like the sacrificial basins<span class=\"note\">That is, the ceremonial bowls used by the priests for sprinkling blood</span>before the altar.'),
('LEB', 'Zechariah', '14', '21', '6', 'And every cooking pot in Jerusalem and in Judah will be holy to Adonai of hosts, and all those who sacrifice will come and will take from them, and will cook in them, and there will be no longer a <span class=\"idiom\">trader</span><span class=\"note\">Literally “Canaanite” (Canaanites, especially Phoenicians, were merchants and traders)</span>in the house<span class=\"note\">Or “temple”</span>of Adonai of hosts on that day.')
;

