INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zephaniah', '1', '1', '1', '<span class=\"verse-title\">Judah’s Impending Judgment</span>The word of Adonai that came to Zephaniah the son of Cushi, the son of Gedaliah, the son of Amariah, the son of Hezekiah, in the days of Josiah son of Amon, king of Judah.'),
('LEB', 'Zephaniah', '1', '2', '2', '“I will surely destroy everything  from the face of the earth”—a declaration of Adonai.'),
('LEB', 'Zephaniah', '1', '3', '2', '“I will destroy humanity and beast;  I will destroy the birds of the sky  and the fish of the sea,  and the stumbling blocks<span class=\"note\">A reference to idols</span>with the wicked.  And I will cut off humankind  from the face of the earth”—a declaration of Adonai.'),
('LEB', 'Zephaniah', '1', '4', '2', '“And I will stretch out my hand against Judah  and against all the inhabitants of Jerusalem.  And I will cut off from this place  the remnant of Baal,  and the name of idolatrous priests with the priests,<span class=\"note\">The last phrase, “with the priests,” may be a later explanatory gloss</span>'),
('LEB', 'Zephaniah', '1', '5', '2', 'and those who bow down on the rooftops  to the host of heaven,  and those who bow down, swearing to Adonai  but <span class=\"supplied\">also</span> swearing by Milkom,<span class=\"note\">Or “their king”</span>'),
('LEB', 'Zephaniah', '1', '6', '2', 'and those who turned back from <span class=\"idiom\">following</span><span class=\"note\">“after”</span>Adonai,  and who did not seek Adonai,  and did not inquire of him.”'),
('LEB', 'Zephaniah', '1', '7', '2', 'Be silent before the Lord Adonai,  for the day of Adonai draws near,  for Adonai has provided a sacrifice  and has consecrated his guests.'),
('LEB', 'Zephaniah', '1', '8', '2', 'And it shall be <span class=\"supplied\">that</span> on the day of the sacrifice of Adonai,  I will punish the officials  and the sons of the king  and those who dress in foreign clothing.'),
('LEB', 'Zephaniah', '1', '9', '2', 'And on that day I will punish  all who leap over the threshold,  who fill up the house of their master  <span class=\"supplied\">with</span> violence and deceit.'),
('LEB', 'Zephaniah', '1', '10', '2', '“And there shall be on that day”—a declaration of Adonai—  “a <span class=\"idiom\">loud outcry</span><span class=\"note\">“voice of a cry of distress”</span>from the Fish Gate,  and a wailing from the Second District,  and a loud<span class=\"note\">Or “great”</span>crashing from the hills.'),
('LEB', 'Zephaniah', '1', '11', '2', 'The inhabitants of the Mortar shall wail,  for all the traders have perished;  all who trade with silver have been cut off.'),
('LEB', 'Zephaniah', '1', '12', '2', 'And it shall be <span class=\"supplied\">that</span> at that time  I will search Jerusalem with lamps,  and I will punish the men  <span class=\"idiom\">whose senses are dulled from drinking</span>,<span class=\"note\">“who are thickened with their dregs”</span> who say in their hearts,  ‘Adonai will not do good, nor will he do evil.’'),
('LEB', 'Zephaniah', '1', '13', '2', 'Then their wealth shall be as plunder,  and their homes as desolation.  And they shall build their houses and not inhabit them,  and they shall plant vineyards and not drink their wine.”'),
('LEB', 'Zephaniah', '1', '14', '2', 'The great day of Adonai draws near;  <span class=\"supplied\">it is</span> near and <span class=\"supplied\">coming</span> very swiftly.  The sound of the day of Adonai <span class=\"supplied\">is</span> bitterness;  there, a warrior cries out!'),
('LEB', 'Zephaniah', '1', '15', '2', 'That day <span class=\"supplied\">will be</span> a day of wrath,  a day of trouble and distress,  a day of disaster and ruination,  a day of darkness and deep gloom,  a day of clouds<span class=\"note\">Hebrew “cloud”</span>and thick clouds,<span class=\"note\">Hebrew “cloud”</span>'),
('LEB', 'Zephaniah', '1', '16', '2', 'a day of trumpet and <span class=\"supplied\">trumpet</span> blast  against the fortified cities  and against the high corner towers.'),
('LEB', 'Zephaniah', '1', '17', '2', 'And I will bring distress to all humankind,  and they shall walk about like the blind,  for they sinned against Adonai;  their blood shall be poured out like dust  and their entrails like dung.'),
('LEB', 'Zephaniah', '1', '18', '2', 'Moreover, their silver and their gold  will not be able to save them  on the day of the wrath of Adonai.  And in the fire of his zeal,  the whole land shall be consumed,  for a terrifying end he shall make  <span class=\"supplied\">for</span> all the inhabitants of the land.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zephaniah', '2', '1', '1', '<span class=\"verse-title\">Judgment of Judah’s Enemies</span>Gather yourselves together! Now gather together,  O nation having no shame!'),
('LEB', 'Zephaniah', '2', '2', '1', 'Before the birth of the decree,  the day flies away like chaff;  before the fierce anger of Adonai overtakes you;  before the day of the anger of Adonai overtakes you.'),
('LEB', 'Zephaniah', '2', '3', '1', 'Seek Adonai, all you afflicted of the land  who have fulfilled his law;  seek righteousness;  seek humility.  Perhaps you will be concealed  on the day of the anger of Adonai.'),
('LEB', 'Zephaniah', '2', '4', '1', 'For Gaza will be abandoned,  and Ashkelon as a desolation.  <span class=\"supplied\">As for</span> Ashdod, at noon they will drive her away,  and Ekron shall be uprooted.'),
('LEB', 'Zephaniah', '2', '5', '1', 'Woe <span class=\"supplied\">to you</span>, inhabitants of the region of the sea,  people of the Kerethites!  The word of Adonai <span class=\"supplied\">is</span> against you,  O Canaan, land of the Philistines.  I will destroy you <span class=\"idiom\">until there is no inhabitant</span>.<span class=\"note\">“from there is not an inhabitant”</span>'),
('LEB', 'Zephaniah', '2', '6', '1', 'And you, O region of the sea, shall become  pastures <span class=\"supplied\">and</span> meadows <span class=\"supplied\">for</span> shepherds  and sheep pens <span class=\"supplied\">for the</span> flocks.'),
('LEB', 'Zephaniah', '2', '7', '1', 'And it shall become a region  for the remnant of the house of Judah;  upon them they shall graze,  and in the houses of Ashkelon  they shall lie down in the evening.  For Adonai their God shall be mindful of them,  and he will restore their fortunes.'),
('LEB', 'Zephaniah', '2', '8', '1', 'I have heard the reproaches of Moab  and the scorning of the <span class=\"idiom\">Ammonites</span>,<span class=\"note\">“sons/children of Ammon”</span> <span class=\"supplied\">with</span> which they have taunted my nation  and made boasts against their territory.'),
('LEB', 'Zephaniah', '2', '9', '1', '“Therefore, as I live”—a declaration of Adonai of hosts,  the God of Israel—  “Moab shall be as Sodom,  and the <span class=\"idiom\">Ammonites</span><span class=\"note\">“sons/children of Ammon”</span>like Gomorrah,  a place of weeds and salt pits  and a desolation forever.  The remnant of my people shall plunder them,  and the remainder of my nation shall possess them.”'),
('LEB', 'Zephaniah', '2', '10', '1', 'This <span class=\"supplied\">shall be</span> for them in place of their pride  because they mocked and boasted  against the people of Adonai of hosts.'),
('LEB', 'Zephaniah', '2', '11', '1', 'Adonai <span class=\"supplied\">will be</span> awesome against them,  for he will destroy all the gods of the earth  and all the lands<span class=\"note\">Or “islands”</span>of the nations;  each in its place will bow down to him.'),
('LEB', 'Zephaniah', '2', '12', '1', 'You also, O Cushites,  they shall be killed by my sword.'),
('LEB', 'Zephaniah', '2', '13', '1', 'And he will stretch out his hand against the north,  and he will destroy Assyria  and will make Nineveh a desolation,  a dry wasteland like the desert.'),
('LEB', 'Zephaniah', '2', '14', '1', 'Herds shall lie down in her midst,  every wild animal of a nation;  even the desert owl and the screech owl  shall lodge on her capitals.  A voice shall hoot in the window;  rubble<span class=\"note\">The traditional Hebrew text has “waste,” while LXX has “a raven,” reflecting a different word with one consonant changed</span>on the threshold;  for the cedar <span class=\"supplied\">is</span> laid bare.'),
('LEB', 'Zephaniah', '2', '15', '1', 'This <span class=\"supplied\">is</span> the city of rejoicing  that lived securely;  the one saying in her heart,  “<span class=\"idiom\">I am, and there is none besides me</span>.”<span class=\"note\">“I <span class=\"supplied\">am</span> and none me”</span> How she has become a desolation,  a lair for wild animals!  Everyone who passes by her hisses and shakes his fist.')
;

INSERT INTO `bible_verses` (`version`, `book`, `chapter`, `verse`, `paragraph`, `content`) VALUES 
('LEB', 'Zephaniah', '3', '1', '1', '<span class=\"verse-title\">Judgment of Jerusalem and the Nations</span>Woe <span class=\"supplied\">to you</span>, O rebellious and defiled one!  The oppressing city!'),
('LEB', 'Zephaniah', '3', '2', '1', 'She listens to no voice;  she does not accept correction.  In Adonai she does not trust;  to her God she does not draw near.'),
('LEB', 'Zephaniah', '3', '3', '1', 'Her officials in her midst <span class=\"supplied\">are</span> roaring lions;  her judges <span class=\"supplied\">are</span> evening wolves;  they leave nothing until the morning.'),
('LEB', 'Zephaniah', '3', '4', '1', 'Her prophets <span class=\"supplied\">are</span> arrogant men of treachery;  her priests have defiled <span class=\"supplied\">that which is</span> holy;  they do violence to <span class=\"supplied\">the</span> law.'),
('LEB', 'Zephaniah', '3', '5', '1', 'Adonai <span class=\"supplied\">is</span> righteous in her midst;  he does not do wickedness.  <span class=\"idiom\">Morning by morning</span><span class=\"note\">“In the morning, in the morning”</span>he renders his judgment;  at dawn he does not fail,  but an evil one knows no shame.'),
('LEB', 'Zephaniah', '3', '6', '1', '“I have cut off nations;  their strongholds are deserted.  I have laid waste their streets,  so that none pass through.  Their cities have been destroyed  <span class=\"supplied\">and are</span> without a man, without an inhabitant.'),
('LEB', 'Zephaniah', '3', '7', '1', 'I have said, ‘Surely she will fear me;  she will accept discipline.  Then her dwelling place will not be cut down,  <span class=\"supplied\">nor</span> all that I have brought upon her.’  Surely they rise early;  they make all their deeds corrupt.'),
('LEB', 'Zephaniah', '3', '8', '1', '“Therefore, wait for me”—a declaration of Adonai—  “for the day of my rising as a witness.  For my decision <span class=\"supplied\">is</span> to gather nations,  to assemble<span class=\"note\">The traditional Hebrew has “assemble me”; this translation follows LXX</span>kingdoms,  to pour out my wrath upon them, all my burning anger.  For by the fire of my anger all the land shall be consumed.'),
('LEB', 'Zephaniah', '3', '9', '1', 'Because then I will <span class=\"idiom\">make the speech of the nations pure</span>;<span class=\"note\">“I will turn to the nations a purged lip”</span> that all of them might call on the name of Adonai,  to serve him <span class=\"idiom\">in unison</span>.<span class=\"note\">“with one shoulder”</span>'),
('LEB', 'Zephaniah', '3', '10', '1', 'From beyond the rivers of Cush  my worshipers and the daughter of my scattered ones  shall bring my offering.'),
('LEB', 'Zephaniah', '3', '11', '1', 'On that day you shall not be humiliated  on account of all your deeds  <span class=\"supplied\">by</span> which you have rebelled against me.  For then I shall remove from your midst  those exulting in your pride,  and you shall no longer be haughty  in <span class=\"idiom\">my holy mountain</span>.<span class=\"note\">“the mountain of my holiness”</span>'),
('LEB', 'Zephaniah', '3', '12', '1', 'And I will leave in your midst  a people afflicted and poor,  and they shall take refuge  in the name of Adonai.'),
('LEB', 'Zephaniah', '3', '13', '1', 'The remnant of Israel  shall not do wickedness;  they shall not speak deception,  nor shall a deceitful tongue be found in their mouth.  For they shall graze and lie down,  and none shall frighten <span class=\"supplied\">them</span>.”'),
('LEB', 'Zephaniah', '3', '14', '1', 'Shout for joy, O daughter of Zion!  Cry aloud, O Israel!  Rejoice and be jubilant with all your heart,  O daughter of Jerusalem!'),
('LEB', 'Zephaniah', '3', '15', '1', 'Adonai has annulled your judgments;  he has turned away your enemies.  The king of Israel, Adonai, <span class=\"supplied\">is</span> in your midst;  you shall no longer fear misfortune.'),
('LEB', 'Zephaniah', '3', '16', '1', 'On that day it shall be said to Jerusalem,  “Fear not, O Zion;  your hands shall not hang limp.'),
('LEB', 'Zephaniah', '3', '17', '1', 'Adonai your God <span class=\"supplied\">is</span> in your midst;  a mighty warrior who saves.  He shall rejoice over you with joy;  he renews<span class=\"note\">The translation follows the LXX text; the traditional Hebrew text reads “he will silence you in his love”</span>you in his love;  he will exult over you with singing.'),
('LEB', 'Zephaniah', '3', '18', '1', 'I will gather those of you grieving on account of the feast;  they were raising against her a reproach.'),
('LEB', 'Zephaniah', '3', '19', '1', 'Behold, at that time I will deal with all your oppressors;  I will save the lame and gather the outcast.  I will change<span class=\"note\">Or “make”</span>them from shame  to glory and <span class=\"idiom\">renown</span><span class=\"note\">“a name”</span>throughout the whole world.'),
('LEB', 'Zephaniah', '3', '20', '1', 'At that time I will bring you <span class=\"supplied\">in</span>;  at the time of my gathering you <span class=\"supplied\">together</span>.  For I will make you <span class=\"idiom\">renowned</span><span class=\"note\">“a name”</span>and praised  among all the nations of the earth  when I restore your fortunes before your eyes,”  says Adonai.')
;

